### ISSUE TITLE
Matching ... inside Python dict and set literals

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#1003]
Currently,

* `{$X}` matches only a one-element dict or one-element set,
* `{...}` matches only a one-element dict or one-element set,
* `{$X, ...}` matches only a two-element dict or two-element set,
* `{..., ...}` matches only a two-element dict or two-element set,
* `{$X, ..., ...}` matches only a three-element dict or three-element set,
* `{..., ..., ...}` matches only a three-element dict or three-element set,

and so on. This isn’t very useful or intuitive. I’d expect to be able to match

* a dict (only) literal of any size, perhaps with `{...}` (by analogy with how `{}` is the empty dict and not the empty set);
* a set (only) literal of any size, perhaps with `{$X, ...}`;
* a dict literal of any size including a particular key, perhaps with `{..., "foo": $VALUE, ...}`;
* a set literal of any size including a particular item, perhaps with `{..., "foo", ...}`.

**Comment by mschwager** [comment]
This is somewhat similar to #744.

From that issue I'd like to be able to match things like:

```
widgets = [
    ...
    { ..., path: $PATH, ... }
    ...
]
```

And this will grab all `dict`s (or objects in Javascript or Golang) that have a `path` key inside the `widgets` list. As mentioned above, we could also specify a pattern like `{ ..., path: $PATH, ... }` that would simply match all `dict`s or objects in the code with a `path` key.

I think it would also be worth considering the equivalent code for other languages here. E.g. what's the equivalent JS and Golang object notation that we'd search for?
