### ISSUE TITLE
where is semgrep architecture documentation

### ISSUE THREAD

**Issue by Sof0-0** [semgrep/semgrep#10046]
Hello! 
I am researching on the Semgrep functionality for the SAST.

And I could not find any information on how Semgrep is performing its scans. Does it build out the whole environment in the DB format and then performs quering on it or builds a tokenized tree? 

What is the operational procedure for it?

**Comment by ievans** [comment]
@aryx has probably written the best architecture overview, but I don't know where it is, I'll let him comment

**Comment by aryx** [comment]
[Semgrep-3.pdf](https://github.com/semgrep/semgrep/files/14983064/Semgrep-3.pdf)

**Comment by aryx** [comment]
There is no real documentation about the architecture of Semgrep unfortunately. I started to write one a long time ago in the attached PDF semgrep-3.pdf above, but it was never finished. Still the few first pages in chapter 2, especially section 2.6 can be useful, even if it's not really uptodate.
