### ISSUE TITLE
LOG_LEVEL variable causing high memory usage / process killed

### ISSUE THREAD

**Issue by calto001** [semgrep/semgrep#10044]
**Describe the bug**
When setting LOG_LEVEL=debug semgrep may be killed due to OOM. In version 1.63 [log levels could be ran from env variables](https://github.com/semgrep/semgrep/pull/9824). However if running Semgrep in Gitlab CI/CD there is already a default variable called `LOG_LEVEL`. In Gitlab if this value is set to `debug` than users may be unaware that Semgrep is running in debug mode and consuming extra memory, resulting in slower runs or the process being killed all together. 

Obviously things can fixed if users change the Semgrep job variable to be `LOG_LEVEL=none`, if they know whats causing the issue. It took me a few days of debugging to find that it was that variable causing the process to be killed. I ran Semgrep on 2 CPU and 12 GB of ram and still was killed. 

**To Reproduce**

- `export LOG_LEVEL=debug`
- Run semgrep version <= 1.63.0
- Add some various file types `touch test.js  test.py  test.rb  test.ts`
- Run `semgrep scan --config auto`
- View high memory usage or process being killed

**Expected behavior**
Process doesn't get killed. I'm not sure if `LOG_LEVEL=debug` is supposed to result in higher memory or not. But it currently does and Gitlab users should be aware of the potential impact.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep on Gitlab. But verified results running Semgrep on Docker as well as locally. 

**Use case**
Will allow users on Gitlab who have defaulted jobs to run with `LOG_LEVEL=debug` to not have Semgrep to crash.

**Comment by mjambon** [comment]
The simplest fix that comes to mind is for semgrep to honor only `SEMGREP_LOG_LEVEL` and not `LOG_LEVEL`.

**Comment by mjambon** [comment]
We fixed this issue by not consulting `LOG_LEVEL`. It will be effective in next week's release of semgrep (1.69.x).

Sorry for the trouble this caused. Thanks for your patience!

**Comment by calto001** [comment]
Thank you!
