### ISSUE TITLE
[JavaScript] function ...(...) { ... } or abstracting away named or anonymous functions

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#1007]
There is a confusion on how patterns for named and unnamed functions for JavaScript work:

when using `pattern: function (...) {...}` it sometimes catches named functions
link: https://semgrep.live/PeY3

while using `pattern: function $NAME (...) {...}` does not catch all named functions possible
link: https://semgrep.live/JDgR

as a researcher I would like to have "catch em all" pattern, whether it is named or unnamed, sometimes it is helpful to have one pattern to catch all function usage possible

**Comment by nbrahms** [comment]
@aryx It looks like named function patterns show up as statements, not expressions...

**Comment by nbrahms** [comment]
Also note that

```js
(function $NAME (...) {...})
```
matches as an expression

**Comment by nbrahms** [comment]
@inkz It seems like using a `patterns-either` with:
```js
(function $NAME (...) {...})
```
and
```js
function $NAME (...) {...}
```
as the two patterns will work for now

**Comment by inkz** [comment]
:wave:

**Comment by aryx** [comment]
maybe we could have function ...(...) { more stuff here }
to match named or unnamed functions? I remember @ajinabraham had to use many pattern-either to cover all the possible use of functions.

**Comment by aryx** [comment]
cc @ajinabraham this feature might simplify a few of your rules.
Basically instead of 
    - pattern-inside: |
        function $HANDLER(..., $WRITER http.ResponseWriter, ...) {
          ...
        }
    - pattern-inside: |
        function(..., $WRITER http.ResponseWriter, ...) {
          ...
        }

you can now just do function ...(..., $WRITER http.ResponseWriter, ...) { ... }

(this is a Go example, but this apply to JS as well).
