### ISSUE TITLE
 limit memory error on a docker file | Parsing bug

### ISSUE THREAD

**Issue by mustafanaa** [semgrep/semgrep#10084]
**Describe the bug**
A dockerfile that ends with ends a LABEL instruction causes limit memory error , I know that no dockerfile supposed to end with a LABEL , but my automatic scan can handle those type of files , and i cant not just exclude them or add them to .getignore because i cant always know their name in advance , on semgrep forum they suggested that i open a bug!

**To Reproduce**
Steps to reproduce the behavior, (https://semgrep.dev/playground/r/L1UqpL7/mona_pers1996_personal_org.npm-install-without-production-flag)

**Expected behavior**
I expect that this behavior gets parsed to taken care of with out causing a limit on memory 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by mjambon** [comment]
Thank you for reporting this, it's definitely undesired behavior.

The problem goes away if I add a trailing newline character so it could be a simple parsing bug but it doesn't explain the error messages about memory:
```
Error while running rules: 
                    You are seeing this because the engine was killed.

                    The most common reason this happens is because it used too much memory.
                    If your repo is large (~10k files or more), you have three options:
                    1. Increase the amount of memory available to semgrep
                    2. Reduce the number of jobs semgrep runs with via `-j <jobs>`. We
                        recommend using 1 job if you are running out of memory.
                    3. Scan the repo in parts (contact us for help)

                    Otherwise, it is likely that semgrep is hitting the limit on only some
                    files. In this case, you can try to set the limit on the amount of memory
                    semgrep can use on each file with `--max-memory <memory>`. We recommend
                    lowering this to a limit 70% of the available memory. For CI runs with
                    interfile analysis, the default max-memory is 5000MB. Without, the default
                    is unlimited.

                    The last thing you can try if none of these work is to raise the stack
                    limit with `ulimit -s <limit>`.

                    If you have tried all these steps and still are seeing this error, please
                    contact us.

                       Error: semgrep-core exited with unexpected output

                       INFO:semgrep_core:Existing stack limits: Soft: 10485760, Hard: 10485760
INFO:semgrep_core:Trying to set soft limit to 1048576000
INFO:semgrep_core:Failed to set stack limit to 1048576000, 10485760. Trying again.
INFO:semgrep_core:Trying to set soft limit to 1000000000
INFO:semgrep_core:Failed to set stack limit to 1000000000, 10485760. Trying again.
INFO:semgrep_core:Trying to set soft limit to 512000000
INFO:semgrep_core:Failed to set stack limit to 512000000, 10485760. Trying again.
INFO:semgrep_core:Trying to set soft limit to 104857600
INFO:semgrep_core:Failed to set stack limit to 104857600, 10485760. Trying again.
INFO:semgrep_core:Trying to set soft limit to 52428800
INFO:semgrep_core:Failed to set stack limit to 52428800, 10485760. Trying again.
INFO:semgrep_core:Trying to set soft limit to 51200000
INFO:semgrep_core:Failed to set stack limit to 51200000, 10485760. Trying again.
INFO:semgrep_core:Trying to set soft limit to 10485760
INFO:semgrep_core:Successfully set stack limit to 10485760, 10485760
!!!This is a proprietary extension of semgrep.!!!
!!!You should not call directly this program.!!!
```

**Comment by mustafanaa** [comment]
Hello , @mjambon and thanks for your feedback , would this be fixed soon ?

**Comment by mjambon** [comment]
Hopefully within the next month. Ping us if this is blocking you.

**Comment by mustafanaa** [comment]
Hello @mjambon yes this issue is blocking me , can it be fixed in the upcoming days ? Thank you so much and happy weekend

**Comment by mjambon** [comment]
@mustafanaa I'll work on it next week if there's no last-minute emergency. :crossed_fingers:

**Comment by mustafanaa** [comment]
Thanks , will be this on the next release ? When can i start testing it

**Comment by mjambon** [comment]
Good question. It should be in this week's release, watch for version 1.72.0. It should happen sometime this week or at the beginning of next week.
