### ISSUE TITLE
JavaScript Lexical error: WIERD end of file in regexp

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1009]
**Describe the bug**
Lexical error: WIERD end of file in regexp

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.live:
~https://semgrep.live/Gdgz~ https://semgrep.live/QrOP

**Expected behavior**
no lexical error

**Screenshots**

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
Probably a bug in the parsing of JSX. It thinks it's a regexp (//) when it's probably a tag.

**Comment by dlukeomalley** [comment]
@aryx @ievans also mentioned here for a reactjs repository: https://github.com/ajinabraham/njsscan/issues/9#issuecomment-644723240

**Comment by aryx** [comment]
I think L19 actually contains a real parse error:
{baz ? 'test' : <a href={parentTag}test2</a>}

the <a tag is not finished. there should be a '>' before test2 probably.
Not sure why the error message is not pointing there though.

**Comment by ievans** [comment]
@aryx user had a typo in the original, here is a failing case (I'll edit the original issue text too): https://semgrep.live/QrOP

**Comment by aryx** [comment]
This seems to work now.
