### ISSUE TITLE
Syntax Error on Javascript <>

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1010]
**Describe the bug**
Syntax Error on Javascript <>

**To Reproduce**
https://semgrep.live/Regv

**Expected behavior**
no syntax error

**Screenshots**

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
What does this construct mean? Is it a react JSX thing?
To which HTML element it corresponds to?

**Comment by ghbren** [comment]
I'm actually not sure exactly what `return (<>)` means, but it looks like react.
Do you plan to support react code, like the examples here https://www.w3schools.com/whatis/whatis_react.asp?
We have other return statements similar to the ones from this link.

**Comment by dlukeomalley** [comment]
@DrewDennison Is this a "flow"ism?

**Comment by DrewDennison** [comment]
`return (<>)` is returning the newish [React Fragment Short Syntax](https://reactjs.org/docs/fragments.html#short-syntax)

We definitely plan / do support react and JSX but we might need to update our AST for then it's `<>` and not `<foo>` cc @aryx
