### ISSUE TITLE
Parse 'declare type x = { stuff } ' typed Javascript declarations

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1012]
https://semgrep.live/BYG7

syntax error

**Comment by aryx** [comment]
Not a Javascript issue indeed. Semgrep does not currently support typescript (we're working on it, but it will take a few weeks).

**Comment by ghbren** [comment]
We have some .js code that uses `declare type`.  It appears to be valid with the javascript flow library.   https://flow.org/en/docs/libdefs/creation/
Is this something you can support?

**Comment by aryx** [comment]
We could extend the parser to just skip over those 'declare' type declarations. You would not be able to match over this code or express type-related patterns, but we should at least be able to analyze the truly javascript code in the file. Would that work for you?

**Comment by ghbren** [comment]
Sounds good for now, thank you!  
Can semgrep print out warnings that these things are skipped?

**Comment by aryx** [comment]
This now works in typescript mode: https://semgrep.dev/s/RrvY/
