### ISSUE TITLE
Parse typed javascript type declaration (Flow or Typescript)

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1013]
https://semgrep.live/DbAq

**Comment by nbrahms** [comment]
Hi @ghbren,

Thanks for filing this issue!

For tracking simplicity, I'm going to close this in favor of #1148 , which is currently in progress.

If this issue still persists after #1148 is closed, we should reopen this issue then.

**Comment by jedwards1211** [comment]
The problem with JS now is the possible syntaxes has forked.  Not only do you have to parse differently depending on if the user is using Flow or not, the user could also be using one the the three Babel pipeline operator proposals or other exotic syntax options.  Tools written in JS that use the user's installed Babel version/config will probably be able to offer better support than semgrep for bleeding edge language features.
