### ISSUE TITLE
Regression in parse error exit code in 0.10

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1023]
**Describe the bug**
In 0.9.0 when there is a bad pattern e.g. `$` it exits with exit code `4`. In 0.10.x, it exits with `2`

If not using semgrep.live: are you running off docker, an official binary, a local build?
official linux binary and docker containers. Not that I hacked around this for .live so it won't show up there.

**Comment by DrewDennison** [comment]
Can we add exit code to our regression test suite?

**Comment by DrewDennison** [comment]
regression seen in https://github.com/coinbase/salus/commit/282ddf940c5a24bb6f54ba132cd3fc64489aee31#diff-a3cee78d09fa30467a918e93fbbf29d4R602

**Comment by rcoh** [comment]
do we have documented exit code semantics anywhere? Eg. should the exit code be 4 if the rule is incorrectly structured?
