### ISSUE TITLE
JavaScript, consider uninitialised variables as var

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#1026]
**Is your feature request related to a problem? Please describe.**

Does it make sense to consider unintialized variables as `var/const/let` type in semgrep rule for JavaScript? I don't know if doing so will affect a rule looking for globally scoped var.

Based on : https://github.com/ajinabraham/nodejsscan/issues/177

**Comment by dlukeomalley** [comment]
@aryx @ievans @minusworld Thoughts on how to handle uninitialized variables or how to tweak the pattern here to catch @ajinabraham's case?

**Comment by aryx** [comment]
Not sure what you mean. Can you write a semgrep.live example with a certain pattern and the kind of code you would like it to match (with the equivalences the semgrep engine should handle automatically).

**Comment by minusworld** [comment]
@ajinabraham Is this the `xss_node.yaml` rule?

If so, I think if the rule is edited to include cases that don't require an intermediate variable initialization it will work here.

Something like
```js
$APP.get("...", function ($REQ, $RES) {
    var $USER = $REQ.query.$VAR;
    ...
    $INTERMEDIATE = $SOMETHING + $USER;
    ...
    $RES.send("..." + $INTERMEDAITE);
});
```

**Comment by ajinabraham** [comment]
Make sense, the `var` is not required for the variables. I can handle this with rule QA.
