### ISSUE TITLE
Semgrep Pro language server seems to force downloading rules online

### ISSUE THREAD

**Issue by kam193** [semgrep/semgrep#10279]
**Describe the bug**
I'm trying to [integrate](https://github.com/kam193/assemblyline-services/tree/main/semgrep) with the `semgrep lsp`, and support the Pro version as well. Unfortunately, it looks like the Pro engine has some differences in the behaviour, especially: despite having a list of configured rule files, it silently forces downloading rules from the Semgrep Repository. Finally, both local and repository rules are used. It doesn't work well in my use case, where rules should be strictly selected (and execution ideally without the Internet access, although Pro has to do verify the login, of course). 

When not using the `--pro` flag, semgrep OSS uses only local rules. 

**To Reproduce**
(I think it could be easily reproduced in the VSCode extension, but unfortunately, there is something in my Python setup that breaks the semgrep installation used by the extension).

1. Have semgrep server started like this:
```python
semgrep_server = subprocess.Popen(
    ["semgrep", "lsp", "--pro"],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    env={
        **os.environ["PATH"],
        "SEMGREP_APP_TOKEN": API_KEY,
        "SEMGREP_SEND_METRICS": "off",
    },
)
```
2. Initialize with the initial config like this (it's called through `pylspclient` client):
```
    processId=current_pid,
    initializationOptions={
        "scan": {
            "configuration": ["/path/to/rule/file.yaml"],
            "jobs": 1,
            "exclude": [],
            "include": [],
            "maxMemory": 500,
            "maxTargetBytes": 1000000,
            "timeout": 10,
            "timeoutThreshold": 3,
            "onlyGitDirty": False,
            "pro_intrafile": False,  # yes, it doesn't even have to be turn on
        },
        "doHover": False,
        "metrics": {"enabled": False},
    },
    capabilities={
        "codeActionProvider": False,
        "executeCommandProvider": {"commands": ["semgrep/ignore"]},
        "hoverProvider": False,
        "textDocumentSync": {"change": 2, "openClose": True, "save": True},
        "window": {"workDoneProgress": False},
    },
    trace=None,
    workspaceFolders=[
        {
            "uri": "path:///path/to/workspace/with/python/code",
            "name": "examples"
        }
    ],
```
3. Send the client initialized message or just refresh rules.
4. Notify opening the file.
5. Look that the diagnostic message contains results from the local ruleset as well as the semgrep repository.

If in the step 1 we skip the `--pro` flag, only local rules are downloaded.

Note: in the workspace is a one python code, and sending metrics is disabled all the way. So far I understand, using the Semgrep Registry requires enabling metrics - does it mean they are sent anyway?

**Expected behavior**
If the configuration is provided and does not contain `auto` or repository rules, no remote ruleset is downloaded.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
  - if it's the desired behaviour, then I'll use OSS engine only (this would be sad :()
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

Semgrep installed in Python virtualenv.
* package version: 1.74.0
* Semgrep Pro Engine version: b28c1e4 (in the LSP messages reported as 1.73.0)

**Use case**
Safe integrating with Semgrep Pro allowing using advanced data flow tainting in rules. The use case is quite unusual, as I don't scan my repositories, but want to extend a malware triage platform with rich Semgrep integration (in my specific use case, to scan open-source code). Language Server mode has a huge performance advantage over normal CLI scanning due to cached rules

**Comment by ajbt200128** [comment]
Hey! Just an FYI, we don't really intend the language server to be used outside of the extensions, so if you intend to use it this way, we can't guarantee things won't break or stop working in the future. ~~But the --pro flag does not affect anything in the language server, so you can just not pass it (really, this shouldn't be possible), and instead set the LSP setting "pro_intrafile"~~

**Comment by kam193** [comment]
Hey @ajbt200128 

I appreciate your answer, and I'm fully aware this is using in not intended way - and I accepted the risk of breaking in the future. It was however the only way to I've found to make semgrep keep rules loaded and just "change" the analysed file, when files are not known in advance and come one-by-one. Maybe there is an official feature I haven't seen that does that?

> But the --pro flag does not affect anything in the language server, so you can just not pass it (really, this shouldn't be possible), and instead set the LSP setting "pro_intrafile"

Hmm, I know I'm not an expert on the code base, and maybe I missed something, but I cannot agree with you. The `--pro` flag instructs the `semgrep` exec script to [load the pro binary](https://github.com/semgrep/semgrep/blob/92e33b859f6f0fef118bd1faad104c4a1e6dc104/cli/bin/semgrep#L123), and is set by [semgrep-vscode](https://github.com/semgrep/semgrep-vscode/blob/72754e188f7da5724474fb0ddd5f5d3d8a95fc10/src/lsp.ts#L88-L93). Later, the `pro_intrafile` setting is required to use pro features, but if you use it on the wrong binary, you will [get a warning](https://github.com/semgrep/semgrep/blob/92e33b859f6f0fef118bd1faad104c4a1e6dc104/src/osemgrep/language_server/scan_helpers/Scan_helpers.ml#L104-L109) and no Pro features. This is what I've found considering the integration ;)

**Comment by ajbt200128** [comment]
you're right! you do need to pass --pro missed that. After checking again, what's happening is that since you're logged in, the language server automatically downloads rules from your account. You have to be logged in to run the pro binary. You can try setting the lsp setting "ci" to false. This setting is for testing purposes only, so again it may break. I would also check the pro engine license agreement, as using the pro engine in this way may not be allowed under our terms of service (or may change in the future), but I am not a lawyer, so cannot say for sure if your use case does violate the license agreement.

**Comment by kam193** [comment]
Thank you for tips! Yeah, the license makes me worried, and if I manage to integrate the pro engine and confirm it does make sense, I'll try to contact the Semgrep company/support before using it for any not-mine code. My understanding is that as long as I use it against my own code, it's definitely covered by the contributors limit.
