### ISSUE TITLE
[Feature Request] Support for Filtering Findings from the CLI

### ISSUE THREAD

**Issue by drstevenbrule** [semgrep/semgrep#10317]
**Is your feature request related to a problem? Please describe.**
One way that Semgrep SCA differentiates itself from other solutions is by [reachability rules
](https://semgrep.dev/blog/2024/sca-reachability-analysis-methods). These are extremely helpful for prioritizing fixes. It's possible to filter these in the UI, but for pipelines and other post-processing applications this has to be parsed manually. 

**Describe the solution you'd like**
A good example of the UX that I find useful is [Trivy's filtering
](https://aquasecurity.github.io/trivy/v0.52/docs/configuration/filtering/). 

We can use `trivy image --severity HIGH,CRITICAL` to immediately filter the output. We already can somewhat filter by severity from the CLI by doing `--severity=ERROR`, although this doesn't quite match up with my use case (filtering by Critical, High, Medium, or Low).

I would really like the Semgrep CLI to support something similar, for example:
`semgrep ci --supply-chain --metrics off --no-suppress-errors --only-reachable --json --output=results.json`
where `--only-reachable` is an optional flag, or `--reachability=ALWAYS,CONDITIONALLY` 

**Describe alternatives you've considered**
The alternative is manually processing using some combination of `jq` and `grep`. This is not ideal and prone to error if the output ever changes.

**Use case**
This will enable me to build automations around only the vulnerabilities that I care about, which cuts down on vuln fatigue and developer overload.

**Comment by ievans** [comment]
Thanks for the great writeup on the request. Unfortunately, we're not likely to add this feature (elatedly: https://github.com/semgrep/semgrep/issues/5075):

> We do envision `semgrep ci` to be mostly used with semgrep.dev where users can configure what rules run 

The alternative you considered is probably your best option -- note that we actually formally specify the output of Semgrep (https://github.com/semgrep/semgrep-interfaces), so it is pretty stable; and we provide bindings for a few languages to automatically parse the output.
