### ISSUE TITLE
semgrep-core: unknown exception: End_of_file

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1037]
(using `develop` image at `14deabbf47ae`)

> git clone git://git.eclipse.org/gitroot/platform/eclipse.platform.swt.git
eclipse.platform.swt (master) [1]> time docker run --rm -v "$PWD:/home/repo" returntocorp/semgrep:develop --config=https://semgrep.live/p/findsecbugs
using config from https://semgrep.live/p/findsecbugs. Visit https://semgrep.live/registry to see all public rules.
running 43 rules.....
non-zero return code while invoking semgrep-core:
	an internal error occured while invoking semgrep-core:
	unknown exception: End_of_file
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://semgrep.dev
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://semgrep.dev
      383.77 real         0.05 user         0.08 sys

cc @ghbren who has reported similar issues anecdotally

**Comment by dlukeomalley** [comment]
Related to #312? Do you have a semgrep.live link for a repo?

**Comment by ievans** [comment]
Not related. No semgrep.live link as I don't know what file in this (giant) repo causes it. Will need OCaml backtraces to do so.

**Comment by ievans** [comment]
Related to https://github.com/returntocorp/semgrep/issues/1009

**Comment by ievans** [comment]
Confirmed fixed with semgrep 0.19.1 (fix probably happened earlier, that's just the version I used)
