### ISSUE TITLE
GOCD Pipeline Configuration

### ISSUE THREAD

**Issue by suprajasutti** [semgrep/semgrep#10396]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem I am currently facing. 

**Describe the solution you'd like**
We are currently using GOCD pipeline for CI/CD. However, in the semgrep documentation, I could not find instructions to configure semgrep.yml for GOCD pipeline

**Describe alternatives you've considered**
NA

**Use case**
CI/CD

**Additional context**

What additional set up is required for GOCD/pipelines that is not provided in the semgrep documentation

**Comment by aryx** [comment]
We're not aware of this CI system.
You can have a look at https://semgrep.dev/docs/semgrep-ci/sample-ci-configs
and maybe adapt one of our workflow to this new CI system.
If GOCD has the ability to run docker image in CI, this should be pretty simple.

**Comment by suprajasutti** [comment]
> We're not aware of this CI system. You can have a look at https://semgrep.dev/docs/semgrep-ci/sample-ci-configs and maybe adapt one of our workflow to this new CI system. If GOCD has the ability to run docker image in CI, this should be pretty simple.

**Comment by suprajasutti** [comment]
thank you!
