### ISSUE TITLE
Failure on complex JS destructuring patterns (objects in catch, array with default values)

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#1040]
Live example: https://semgrep.live/zd70/?version=develop

Semgrep can't parse these JS:
https://github.com/ajinabraham/nodejsscan/issues/179

**Comment by dlukeomalley** [comment]
@aryx @ievans Thoughts on these parse failures?

**Comment by aryx** [comment]
Yes I think certain Javascript "patterns" (not sure they call that pattern, but it's really the recent pattern-matching ability of Js where you can match object/records/ with also default values) are not yet handled. We parse them, but we don't handle them during the conversion to the generic AST.

**Comment by aryx** [comment]
@nbrahms does you recent PR fix that?

**Comment by nbrahms** [comment]
@aryx My guess is no, but I haven't tested this functionality yet.

**Comment by ievans** [comment]
@nbrahms @aryx I threw in an .live link to the original post that shows them still failing on `develop`

**Comment by nbrahms** [comment]
It is interesting that https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch says clearly that the nodes inside catch expressions are specifically identifiers, not patterns. However `node --check` parses the suggested code cleanly.

**Comment by nbrahms** [comment]
https://tc39.es/ecma262/#prod-CatchParameter contains the pattern spec

**Comment by nbrahms** [comment]
- The first pattern will be fixed by returntocorp/pfff#207
- The second pattern appears to already work in 0.14: https://semgrep.live/4brE/
