### ISSUE TITLE
Semgrep Python API ability to suppress parse errors

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#1041]
**Is your feature request related to a problem? Please describe.**
I am using semgrep python API in njsscan. Semgrep prints parse errors and other exception to output. Can this be suppressed? Am I missing a flag or option to make this less verbose? Ideally I would like to collect all of such issues in a variable which I can later decide weather to print or not.

Related issues: https://github.com/ajinabraham/njsscan/issues/9

**Comment by dlukeomalley** [comment]
@ajinabraham Thanks for filing. Adding @brendongo and @DrewDennison who I think will have thoughts given https://github.com/returntocorp/semgrep/pull/1034.

**Comment by brendongo** [comment]
The code printing out the parse errors should be this line https://github.com/returntocorp/semgrep/blob/v0.10.1/semgrep/semgrep/semgrep_main.py#L275 so as long as you are using the json format output it shouldnt print out parse errors. Though it looks like you are doing that in https://github.com/ajinabraham/libsast/blob/master/libsast/core_sgrep/helpers.py#L13

Is njsscan current released with a semgrep version < 0.10.0?

**Comment by brendongo** [comment]
Looks like existing libsast might be using 0.9.0 where this undesired behavior still exists. We fixed it in https://github.com/returntocorp/semgrep/pull/936

**Comment by ajinabraham** [comment]
I bumped to version 0.10.0, 5 days ago. Are you saying that this issue should not happen if I am on 0.10.0 ?

I can check with user to get his njsscan and libsast version.

**Comment by brendongo** [comment]
Yep! Verified using the python API on 0.10.0 and 0.9.0 on a file with a parse error and it prints out a message only on the later

**Comment by ajinabraham** [comment]
Awesome, I will ask the users to upgrade deps.
