### ISSUE TITLE
Recent versions not available on Homebrew

### ISSUE THREAD

**Issue by dan1elhughes** [semgrep/semgrep#10418]
**Describe the bug**
The CLI says an update is available, but [Homebrew is still on 1.78.0](https://formulae.brew.sh/formula/semgrep). This blocks semgrep running locally, due to `semgrep error: Invalid rule schema`.

**To Reproduce**

```
❯ semgrep --config auto .

Rules downloaded from https://semgrep.dev/c/auto failed to parse.
This is likely because rules have been added that use functionality introduced in later versions of semgrep.
Please upgrade to latest version of semgrep (see https://semgrep.dev/docs/upgrading/) and try again.

semgrep error: Invalid rule schema
  --> None:1
1 | a: b
  | ^^^

Additional properties are not allowed ('patterns' was unexpected)

[ERROR] invalid configuration file found (1 configs were invalid)

❯ semgrep --version
1.78.0

⏫  A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

❯ brew upgrade semgrep
Warning: semgrep 1.78.0 already installed
```

**Expected behavior**
`brew upgrade semgrep` should upgrade to[ 1.81.0](https://github.com/semgrep/semgrep/releases/tag/v1.81.0)

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

Using the homebrew version of Semgrep

**Use case**
What will fixing this bug enable for you?

Usage of Semgrep 😄

**Comment by aryx** [comment]
I think this is fixed now.
1.82.0 should be available on brew now.

**Comment by aryx** [comment]
@p4p3r why old versions of semgrep are failing when using c/auto?
