### ISSUE TITLE
semgrep error: invalid language: clojure

### ISSUE THREAD

**Issue by gbiagomba** [semgrep/semgrep#10439]
**Describe the bug**
I ran the following command `semgrep scan --config auto -j 10 -o "semgrep_output-$current_time.outout" -v` and got the following err
```
Semgrep rule registry URL is https://semgrep.dev/registry.
semgrep error: invalid language: clojure
  --> None:1
1 | a: b
  | ^^^

unsupported language: clojure. supported languages are: bash, c, c#, c++, cpp, csharp, dart, docker, dockerfile, elixir, ex, generic, go, golang, hack, hcl, html, java, javascript, js, json, jsonnet, julia, kotlin, kt, lua, none, ocaml, php, py, python, python2, python3, r, regex, ruby, rust, scala, sh, sol, solidity, swift, terraform, tf, ts, typescript, vue, yaml

Sending pseudonymous metrics since metrics are configured to AUTO and registry usage is True
```

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev/playground (click "share" and make public to get a shortlink):
I ran the above command the got the output I highlighted. 

**Expected behavior**
I expected the tool to run as it has in the past and give me results

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
No a local semgrep `/Users/gbiagomba/Library/Python/3.11/bin/semgrep`

**Use case**
What will fixing this bug enable for you?
Scanning the java code and finish the project I am working on

**Comment by gbiagomba** [comment]
I did search for clojure files and could not find any. So I don't know why or where this error is coming from

**Comment by nmote** [comment]
What is the output of `semgrep --version`?

**Comment by gbiagomba** [comment]
@nmote apologies, I am just seeing this. I am running semgrep version `0.117.0`. Below is the output of my command.
```
0.117.0

A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

Versions prior to 1.31.0 are no longer supported by Semgrep.dev, please upgrade.
```

I ran an upgrade and this is what I got
```
==> Upgrading semgrep
  1.76.0 -> 1.85.0
```

I performed an upgrade and I am still getting the same err
```
Semgrep rule registry URL is https://semgrep.dev/registry.
semgrep error: invalid language: clojure
  --> None:1
1 | a: b
  | ^^^

unsupported language: clojure. supported languages are: bash, c, c#, c++, cpp, csharp, dart, docker, dockerfile, elixir, ex, generic, go, golang, hack, hcl, html, java, javascript, js, json, jsonnet, julia, kotlin, kt, lua, none, ocaml, php, py, python, python2, python3, r, regex, ruby, rust, scala, sh, sol, solidity, swift, terraform, tf, ts, typescript, vue, yaml

Sending pseudonymous metrics since metrics are configured to AUTO and registry usage is True
```

**Comment by gbiagomba** [comment]
This is the command i ran `semgrep scan --config auto -j 10 --exclude '*example*' --exclude '*test*' --exclude '*sample*' --exclude '*.clj' --exclude '*.cljs' --exclude 'boot' --exclude '*.cl2' --exclude '*.cljs' --exclude '*.hl' --exclude '*.cljscm' --exclude '*.cljx' --exclude '*.hic' --exclude 'riemann.config' -o "semgrep_output-$current_time.outout" -v --dataflow-traces` and I am still getting the above output.
```
Semgrep rule registry URL is https://semgrep.dev/registry.
semgrep error: invalid language: clojure
  --> None:1
1 | a: b
  | ^^^

unsupported language: clojure. supported languages are: bash, c, c#, c++, cpp, csharp, dart, docker, dockerfile, elixir, ex, generic, go, golang, hack, hcl, html, java, javascript, js, json, jsonnet, julia, kotlin, kt, lua, none, ocaml, php, py, python, python2, python3, r, regex, ruby, rust, scala, sh, sol, solidity, swift, terraform, tf, ts, typescript, vue, yaml

Sending pseudonymous metrics since metrics are configured to AUTO and registry usage is True
```

**Comment by nmote** [comment]
I strongly suspect that you are somehow still running a very old version of Semgrep. Note that `semgrep --version` told you that you're running `0.117.0`, yet when you upgraded Semgrep it upgraded it from `1.76.0`, a much more recent version. I bet if you run `semgrep --version` it will still show `0.117.0`. You'll need to sort out your installation and make sure that you are actually running a recent version.

**Comment by gbiagomba** [comment]
@nmote, you were right. I didn't realize I had the pip package and the brew (sigh)
