### ISSUE TITLE
Error: Library "tree-sitter-lang.jsonnet" not found. -> required by library "parser_jsonnet.tree_sitter" in    _build/default/languages/jsonnet/tree-sitter -> required by executable Main in src/main/dune:2 -> required by _build/default/src/main/Main.exe

### ISSUE THREAD

**Issue by tangdouer** [semgrep/semgrep#10430]
Error: Library "tree-sitter-lang.jsonnet" not found.
-> required by library "parser_jsonnet.tree_sitter" in
   _build/default/languages/jsonnet/tree-sitter
-> required by executable Main in src/main/dune:2
-> required by _build/default/src/main/Main.exe

**Comment by nmote** [comment]
Feel free to re-file and make sure to fill out the full issue template

**Comment by blincoln-bf** [comment]
FWIW, in case anyone else finds this issue while troubleshooting errors during the build process, this error *seems* to occur if `make` ends up using `ocamlc` version 5.3.0 instead of the Semgrep-specific version `5.3.0+semgrep-fork@8521d35f98c3bbd7fdcb6678bf120b334b4b6a9c`.
