### ISSUE TITLE
semgrep --validate --metrics=off Not activated

### ISSUE THREAD

**Issue by Wadewfsssss** [semgrep/semgrep#10435]
**Describe the bug**
semgrep --validate --metrics=off Not activated

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev/playground (click "share" and make public to get a shortlink):

command:
semgrep --metrics=off --validate --config /tmp/semgrep-rules --json

semgrep-rules is local rules dir.

**Expected behavior**

**Screenshots**
<img width="701" alt="image" src="https://github.com/user-attachments/assets/0f176c01-df15-4a3b-9eff-0eee214b5ea5">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ *] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
official binary

**Use case**
make --metrics=off active.

**Comment by Wadewfsssss** [comment]
<img width="223" alt="image" src="https://github.com/user-attachments/assets/a8d0f9e7-10d0-452e-92a7-a210e9d5f5ac">

**Comment by nmote** [comment]
`--validate` pulls down the `p/semgrep-rule-lints` ruleset: https://github.com/semgrep/semgrep/blob/8096df8efed6c1c557b1ff2e70ad585a46a6793f/cli/src/semgrep/core_runner.py#L1111

So, it needs network access for that even though it's not sending metrics.

**Comment by Wadewfsssss** [comment]
Can not be used without Internet `--validate`
