### ISSUE TITLE
SAST advice for specifying minimum TLS versions in Java is incorrect

### ISSUE THREAD

**Issue by NeilMadden** [semgrep/semgrep#10452]
**Describe the bug**

Semgrep SAST raises a Medium severity issue for usage of `SSLContext.getInstance(“TLS”)` in Java, with the following description:

```
    The application was found enabling insecure TLS protocol versions. When enabling protocol
versions for an
    `SSLContext`, only the following versions should be allowed:
- TLSv1.2
- TLSv1.3
- DTLSv1.2
- DTLSv1.3

To
    mitigate potential security risks, it is strongly advised to enforce TLS 1.2 as the minimum
protocol version and
    disallow older versions such as TLS 1.0. Do note that newer versions of
Java do not even support TLS 1.0 and will
    throw `NoSuchAlgorithmException`. Versions of TLS
prior to 1.2 could expose the connection to downgrade attacks,
    where an adversary intercepts
the
connection and alters the requested protocol version to be a less secure
    one.

In many scenarios, relying on the default system configuration does not meet compliance
standards. This is
    due to the application being deployed across diverse systems with varying
configurations and Java versions. While
    the default value may be secure on modern and
up-to-date systems, it may not hold true for older systems.
    Consequently, it is highly
recommended to explicitly define a secure configuration in all cases.

Example
    configuring an SSLContext with TLSv1.2:
// Create an SSLContext with TLSv1.2 explicitly
SSLContext tlsContext
    = SSLContext.getInstance("TLSv1.2"); // or TLSv1.3, DTLSv1.2, DTLSv1.3

// Alternatively, set the enabled
    protocols
SSLContext serverSslContext = SSLContext.getInstance("TLS");
SSLEngine serverEngine =
    serverSslContext.createSSLEngine();
// Calling setEnabledProtocols will override the original context's configured
    protocol version
serverEngine.setEnabledProtocols(new String[]{ "TLSv1.2" });

For more information on
    `SSLContext` see:
-
    https://docs.oracle.com/en/java/javase/11/docs/api/java.base/javax/net/ssl/SSLContext.html

For more information
    on MiTM attacks see:
- https://owasp.org/www-community/attacks/Manipulator-in-the-middle_attack
```

However, this guidance is wrong:

* The value passed to `SSLContext.getInstance()` is the *maximum* TLS version supported, not the minimum. (The docs do not mention this, you have to [look at the OpenJDK code](https://github.com/openjdk/jdk/blob/fbe4cc96e223882a18c7ff666fe6f68b3fa2cfe4/src/java.base/share/classes/sun/security/ssl/SSLContextImpl.java#L629))
* Creating a fresh `SSLEngine` and setting enabled protocols on it is not something anyone should do: it only affects that one `SSLEngine` instance, and `SSLEngine` is a very low-level API that is incredibly hard to use correctly.

Both of these pieces of advice are likely to create more security issues than they solve. The correct way to specify the _minimum_ TLS version is to use the `jdk.tls.client.protocols` and `jdk.tls.server.protocols` system properties. (This will make the configuration invisible to SAST in most cases).

**Environment**

GitLab Semgrep SAST integration. Java 21.

Excerpt from report with identifiers:
```json
{
      "identifiers": [
        {
          "type": "semgrep_id",
          "name": "find_sec_bugs.SSL_CONTEXT-2",
          "value": "find_sec_bugs.SSL_CONTEXT-2"
        },
        {
          "type": "cwe",
          "name": "CWE-326",
          "value": "326",
          "url": "https://cwe.mitre.org/data/definitions/326.html"
        },
        {
          "type": "owasp",
          "name": "A02:2021 - Cryptographic Failures",
          "value": "A02:2021"
        },
        {
          "type": "owasp",
          "name": "A3:2017 - Sensitive Data Exposure",
          "value": "A3:2017"
        },
        {
          "type": "find_sec_bugs_type",
          "name": "Find Security Bugs-SSL_CONTEXT",
          "value": "SSL_CONTEXT"
        }
      ]
}
```

**Comment by ievans** [comment]
hey @NeilMadden, this repo is for the Semgrep engine which runs rules written by our team or others. 

Do you know where this rule originated from? I don't see it in our rules (https://github.com/semgrep/semgrep-rules), so I'm wondering if it was written by someone else (likely the Gitlab team)? In that case, you'd need to raise an issue with the original author (or fork & fix it).

**Comment by NeilMadden** [comment]
Ah yes, sorry. This does seem to be a Gitlab customisation: https://gitlab.com/gitlab-org/security-products/sast-rules/-/blob/main/java/crypto/rule-WeakTLSProtocolVersion.yml?ref_type=heads

I’ll report it to them.
