### ISSUE TITLE
Flag to choose severity scale for Sariff output

### ISSUE THREAD

**Issue by timjensen-wk** [semgrep/semgrep#10466]
**Is your feature request related to a problem? Please describe.**
Semgrep uses a non-standard severity rating scale, which causes a lot of confusion when trying to align with compliance and other tool outputs for prioritization. Instead of Error, Warning, and Info, most systems output High, Medium, and Low. This is especially problematic when using systems such as GitHub Advanced Security, where the findings get parsed into the Informational category because they are not standard.

**Describe the solution you'd like**
I would like us to have the ability to change the output in Sariff files to show the standardized severity. This could be a command line flag to switch between the built in ratings, and standardized ratings. 

**Use case**
This will allow us to use Semgrep in a professional capacity, make risk levels easier for engineers to understand, and will make it easier to explain to auditors.

**Comment by timjensen-wk** [comment]
Disregard, I reviewed the SARIF format and y'all are correctly reporting. GitHub Advanced Security should be the one converting.

**Comment by mjambon** [comment]
Good to know, thanks for the heads-up!
