### ISSUE TITLE
版本0.1.0命名有误，为symgrep

### ISSUE THREAD

**Issue by ZerryNi** [semgrep/semgrep#10469]
![image](https://github.com/user-attachments/assets/220b36f0-7e10-46ee-9d06-2bcca4d719ed)
源码地址
https://files.pythonhosted.org/packages/aa/8c/4cddb8e66211e3fffc98fddbb0bb5e753ab626c906b7f3eb366b001a78a8/symgrep-0.1.0.tar.gz#sha256=0a1cdfaf31e22d420ba4e13c3731576c0b349ca66b5b48eeffb3af8ea053e1af

**Comment by mjambon** [comment]
???
