### ISSUE TITLE
[Julia] The final curly brackets in a parametric type are not caught

### ISSUE THREAD

**Issue by iuliadmtru** [semgrep/semgrep#10467]
**Describe the bug**
When trying to catch a type such as `Vector{Int}` in a metavariable, the final curly bracket is not caught.

**To Reproduce**
https://semgrep.dev/playground/s/kxOGz

**Expected behavior**
I would expect the `$TYPE` metavariable to contain the entire type, with closing curly brackets.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
This makes it difficult or impossible to use rules such as `metavariable-regex` or `fix` with the metavariable containing the type in the replacement.

**Comment by mjambon** [comment]
Thanks for the report. It will be fixed in the next Semgrep release.
