### ISSUE TITLE
Docker images not tagged with release versions in the new registry

### ISSUE THREAD

**Issue by johan-detectify** [semgrep/semgrep#10472]
**Is your feature request related to a problem? Please describe.**

Docker images available at [semgrep/semgrep](https://hub.docker.com/r/semgrep/semgrep) does not tag images with versions while the old [returntocorp/semgrep](https://hub.docker.com/r/returntocorp/semgrep) does. 

**Describe the solution you'd like**

Tag the docker images like before

**Describe alternatives you've considered**

1. Continue using the "old" registry.
2. Remove the text saying "We've moved! Official Docker images for Semgrep now available at semgrep/semgrep" from [returntocorp/semgrep](https://hub.docker.com/r/returntocorp/semgrep) since images there are still published there.

**Use case**

This would let me to know which version of Semgrep I'm pulling. It'll also allow me to use Renovate to suggest updates when they're available.

**Additional context**

New releases are still are still published to [returntocorp/semgrep](https://hub.docker.com/r/returntocorp/semgrep) so I'll continue using that in the meantime, though it's not clear how long that will be maintained.

**Comment by aryx** [comment]
yes they are, look https://hub.docker.com/layers/semgrep/semgrep/1.85.0/images/sha256-078beadf18f3115b12eb7c2515162dbd6136209f403e5cba5368d92d1a272fb6?context=explore
this one is tagged with 1.85.0

**Comment by mjambon** [comment]
I'm closing the issue, then. Feel free to reopen if we missed something.
