### ISSUE TITLE
pattern-either or pattern-inside not detected as positive term

### ISSUE THREAD

**Issue by Kiblyn11** [semgrep/semgrep#10514]
**Describe the bug**
Encountering error "Rule parse error in rule ...:
 you need at least one positive term (not just negations or conditions)" when I have positive term in rule.

**To Reproduce**
Example rule:

```csharp
rules:
  - id: test
    languages:
      - csharp
    severity: ERROR
    message: test
    patterns:
      - pattern-either:
        - patterns:
          - pattern-inside: |
              [$HTTPMETHOD(...)]
              public $RET $FOO( ...) {
                  ...
              }
      - patterns:
        - pattern-not: |
              [$HTTPMETHOD(...)]
              public $RET $FOO(...) {
                  ...
                  if (!await Test(...))
                  ...
              }
      - metavariable-regex:
          metavariable: "$HTTPMETHOD"
          regex: "Http(Get|Post|Delete|Patch|Put)"
    path: .*\.cs
```

**Expected behavior**
Should work and not throw error

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep OSS CLI

**Comment by iuliadmtru** [comment]
The problem is that you have only a negative term inside `patterns`:
```
      - patterns:
        - pattern-not: |
              [$HTTPMETHOD(...)]
              public $RET $FOO(...) {
                  ...
                  if (!await Test(...))
                  ...
              }
```

`patterns` basically does a logical "and" between all the patterns inside it, trying to find a _positive_ range first. See the [documentation](https://semgrep.dev/docs/writing-rules/rule-syntax#patterns-operator-evaluation-strategy). `pattern-either` needs all child patterns to be positive, so simply removing the `patterns` inside it won't work.

Maybe you want something like this? It depends on what you're trying to achieve.

```
rules:
  - id: test
    languages:
      - csharp
    severity: ERROR
    message: test
    patterns:
      - pattern-inside: |
            [$HTTPMETHOD(...)]
            public $RET $FOO( ...) {
                ...
            }
      - pattern-not: |
            [$HTTPMETHOD(...)]
            public $RET $FOO(...) {
                ...
                if (!await Test(...))
                ...
            }
      - metavariable-regex:
          metavariable: "$HTTPMETHOD"
          regex: "Http(Get|Post|Delete|Patch|Put)"
    path: .*\.cs
```

**Comment by Kiblyn11** [comment]
OK I see I thought the issue was on the upper `patterns`, that make sense.

At first I wanted to do this to be able to place a metavariable that is linked to the pattern-not like this:

```
rules:
  - id: test
    languages:
      - csharp
    severity: ERROR
    message: test
    patterns:
      - pattern-either:
        - patterns:
          - pattern-inside: |
              [$HTTPMETHOD(...)]
              public $RET $FOO( ...) {
                  ...
              }
      - patterns:
        - pattern-not: |
              [$HTTPMETHOD(...)]
              public $RET $FOO(...) {
                  ...
                  if (!await $FUNC(...))
                  ...
              }
        - metavariable-regex:
            metavariable: "$FUNC"
            regex: "MyFunc"
      - metavariable-regex:
          metavariable: "$HTTPMETHOD"
          regex: "Http(Get|Post|Delete|Patch|Put)"
    path: .*\.cs
```

I believe there is no other way than to wrap in `patterns` to have that metavariable attached to the pattern-not.

**Comment by iuliadmtru** [comment]
I guess you could use `pattern-inside: ...` as a positive catch-all term, and have that inside the `patterns` together with the `pattern-not` and the `metavariable-regex`. I'm not sure if it's really equivalent though.

**Comment by Kiblyn11** [comment]
Clever but that doesn't work 😢 
It gives me this template
```
rules:
    - id: test
      languages:
          - csharp
      severity: ERROR
      message: test
      patterns:
          - pattern-either:
                - patterns:
                      - pattern-inside: |
                            [$HTTPMETHOD(...)]
                            public $RET $FOO( ...) {
                                ...
                            }
          - patterns:
                - pattern-inside: ...
                - pattern-not: |
                      [$HTTPMETHOD(...)]
                      public $RET $FOO(...) {
                          ...
                          if (!await $FUNC(...))
                          ...
                      }
                - metavariable-regex:
                      metavariable: $FUNC
                      regex: Can.*
          - metavariable-regex:
                metavariable: $HTTPMETHOD
                regex: Http(Get|Post|Delete|Patch|Put)
      path: .*\.cs
```

I'm trying to have a match on this code example
```
[HttpPost]
public async void Test([FromRoute] String param)
{
    var user = get_user();

    return true;
}
```

But not on this code
```
[HttpPost]
public async void Test([FromRoute] String param)
{
    var user = get_user();

    if (!await CanDoIt(user))
        return Forbid();

    return true;
}
```

**Comment by iuliadmtru** [comment]
Something like [this](https://semgrep.dev/playground/s/yy4wP)? I am not sure what you are trying to achieve with the `pattern-either`, so maybe I misunderstood what you need.

**Comment by Kiblyn11** [comment]
The pattern-either is because I anticipate to match on more specific endpoints (with specific param names).
But I tested your rule and it works perfectly, thank you !
Closing this as it was not an issue in fact but misunderstanding of the error.
