### ISSUE TITLE
Finding suppressed depending on languages specified

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1051]
Consider the following Java file:

```
$ cat test.java 
class Test {
    public static void main(String[] args) {
        foo();
    }
}
```

Using the following rule we get these results:

```
$ cat test.yaml 
rules:
- id: test-id
  message: test-message
  severity: WARNING
  languages: [java]
  pattern: foo(...)
```

```
$ python -m semgrep --config test.yaml test.java 
running 1 rules...
100%|███████████████████████████████████████████████████████████████████████████████████████████████|1/1
test.java
severity:warning rule:tmp.java-test.test-id: test-message
3:        foo();
```

However, if we add additional `languages` we get a different result:

```
$ cat test.yaml 
rules:
- id: test-id
  message: test-message
  severity: WARNING
  languages: [c, go, java, javascript, python]
  pattern: foo(...)
```

```
$ python -m semgrep --config test.yaml test.java 
running 1 rules...
100%|███████████████████████████████████████████████████████████████████████████████████████████████|1/1
```

**Comment by brendongo** [comment]
Moving java to be the first element in the languages list makes findings appear. Possibly something in semgrep-core only using the first language

**Comment by brendongo** [comment]
Issue is in semgrep-core:

rule.yaml
```
rules:
- id: 0.test-id
  pattern: foo(...)
  severity: WARNING
  languages:
  - go
  - java
  - c
  - javascript
  - python
  message: <internalonly>
```

```
semgrep-core -lang java -rules_file pattern.yaml test.java
```

will not show any findings

**Comment by mschwager** [comment]
> Issue is in semgrep-core:
> 
> rule.yaml
> 
> ```
> rules:
> - id: 0.test-id
>   pattern: foo(...)
>   severity: WARNING
>   languages:
>   - go
>   - java
>   - c
>   - javascript
>   - python
>   message: <internalonly>
> ```
> 
> ```
> semgrep-core -lang java -rules_file pattern.yaml test.java
> ```
> 
> will not show any findings

I'm confused, then why does `languages: [java]` work?

**Comment by brendongo** [comment]
I think there's some filtering in semgrep-core that happens when java is not the first element in the languages list.

**Comment by aryx** [comment]
The first language in the list is the one used to parse the pattern.
That means the generic AST for foo(...) in Java mode is differently from the generic AST
for foo(...) when parsed in C/Go/... mode. 
You can see the dump of the AST with -lang java -dump_pattern

**Comment by aryx** [comment]
I think you can also the the dump of the pattern in the editor in the advanced options.

**Comment by rcoh** [comment]
That's weird -- shouldn't we reparse the pattern in every language for the rule and use that?

**Comment by aryx** [comment]
Yep, you're right, we should.

**Comment by aryx** [comment]
I just assumed the resulting generic AST would be the same, but apparently it's not necessarily the case.

**Comment by brendongo** [comment]
As part of https://github.com/returntocorp/semgrep/pull/1142 I refactored the python side to only pass in one language to semgrep-core so we should no longer be seeing this issue once that is merged in.

**Comment by ievans** [comment]
@mschwager can you confirm and close this ticket if true?
