### ISSUE TITLE
Consider requiring comment symbol in 'nosem' functionality

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1053]
Currently 'nosem' functionality looks for the first line of a finding including " nosem". This yields false positives in situations like:

```python
def foobar():
    nosemblance_of_reality()
```

When we really only care about situations like:

```python
def foobar():
    insecure_func()  # nosem
```

One improvement here would be to require a comment character at the beginning of 'nosem' detection. The reason I initially decided against this was to avoid having to keep track of all possible comment styles in all languages, and a line containing " nosem" seems unlikely (this is why I chose to include a " " in the beginning), but maybe it's worth it. A good first pass could be something like `(#|//|/*) nosem`.

**Comment by nbrahms** [comment]
This looks like a bug waiting to happen, so prioritizing

**Comment by aryx** [comment]
still high priority?

**Comment by nbrahms** [comment]
Doing nothing until we get complaints :)
