### ISSUE TITLE
Support local Semgrep config file (like package.json)

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1054]
As I further adopt Semgrep into my local and CI/CD pipelines, I find myself wanting to customize further than using `--config` with registry or local files easily allows.

I'd like to define both local and remote Semgrep rules to run on my project. Right now I can do this via multiple invocations of `--config`. This has worked well so far, but now I want a rule from a remote check pack to exclude certain files. This requires me to download, check-in, and edit the check pack's YAML. Ideally I'd be able to specify check pack and rule specific "overrides" in a file for file include/exclude, as well as disabling specific rules from a check pack that I don't care about.

I'd also like to avoid complicated `--exclude` and `--exclude-dir` command line invocations by specifying these in the config file.

For some of the checks I run, I don't want them to fail the build, but I do want to be alerted about them or include them in json output.

I like Salus' [configuration format](https://github.com/coinbase/salus/blob/master/docs/configuration.md#salus-configurations).

Overall, I propose the following functionality:

1. Define local and remote check packs to run
1. Support overriding at the Semgrep-wide, check pack, and rule level the following:
     1. If it's enabled/disabled
     1. If it's blocking or non-blocking
     1. What files to include/exclude
1. Define where to post json results to, potentially to multiple endpoints

**Comment by mschwager** [comment]
Can we get 80% of the way there by making `--config` take a list instead of a single argument? Something like `semgrep --config https://semgrep.live/p/python subdir/security.yaml /path/to/configs`, which we then combine all the rules and run as normal.

> I'd also like to avoid complicated `--exclude` and `--exclude-dir` command line invocations by specifying these in the config file.

Is there something about the config file that makes it less complicated than the CLI flag? Note that we already have the [`paths`](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#paths) configuration file key.

> Define where to post json results to, potentially to multiple endpoints

I believe this already works with the `--json` and `--output` flag. Again, we could probably do multiple endpoints by making output a list. Is there a specific request for that?

**Comment by brendongo** [comment]
Using configs wont give you rule level control over includes excludes however so really the alternative solution is invoking semgrep multiple times with each pack containing the rules you want to run on the same targets.

**Comment by dlukeomalley** [comment]
@brendongo From our conversations, my understanding is that we're pausing work here until we have a stronger use case from more users.

**Comment by dlukeomalley** [comment]
Adding a configuration file that allows for specifying registry rules and rulesets by name could help address some of https://github.com/returntocorp/semgrep/issues/1704

**Comment by aryx** [comment]
Now that we allow multiple --config, one with a URL and one using a local file, at least half of luke's request can now be done.
Closing for now, we can still reopen later if we feel the need for a more complex config file.
