### ISSUE TITLE
Autocompleted paths don't work with `--exclude-dir`. e.g. data/ does not work

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1055]
If a trailing `/` is excluded in `--exclude-dir`, the ignore does not work. For users who are tab completing paths, the trailing `/` may be included and we should function with it.

CC @minusworld who ran into this issue

**Comment by brendongo** [comment]
When running with --exclude-dir on `dir` and `dir/` I get the same behavior on 0.11.0

**Comment by brendongo** [comment]
Confirmed that @minusworld likely ran on a previous version of semgrep.
