### ISSUE TITLE
Rule parse error in rule gitlab.find_sec_bugs.URLCONNECTION_SSRF_FD-1

### ISSUE THREAD

**Issue by ademar59** [semgrep/semgrep#10552]
**Describe the bug**
[ERROR] Rule parse error in rule gitlab.find_sec_bugs.URLCONNECTION_SSRF_FD-1:
 Invalid pattern for Java: Stdlib.Parsing.Parse_error
----- pattern -----
import java.net.URL
...

----- end pattern -----

**To Reproduce**
semgrep --disable-version-check --metrics=off -f https://semgrep.dev/p/findsecbugs .

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Run in local or ci sith semgrep image version latest

**Comment by mjambon** [comment]
Hi! Could you please provide details on the code to parse in the form of a link to the Semgrep Playground (https://semgrep.dev/playground/new)?

**Comment by ademar59** [comment]
https://semgrep.dev/playground/s/Gdjjy

**Comment by ademar59** [comment]
@mjambon any news

**Comment by GiantCrocodile** [comment]
Your playground example didn't throw any error for me. It just finds nothing. Is the issue still persisting for you? If so, can you update the example to reproduce the issue?

**Comment by ademar59** [comment]
the problem seems to be fixed
