### ISSUE TITLE
Support inline semgrep rules

### ISSUE THREAD

**Issue by rcoh** [semgrep/semgrep#1059]
**Is your feature request related to a problem? Please describe.**
One of the great features rust has is the ability to annotate a function with things like must_use [1] -- it's then a compiler error to call this function without assigning it's return value to a result.
With semgrep, it seems like we have the potential to bring this sort of lint to other languages.
[1] https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

**Describe the solution you'd like**
We could support this in Semgrep via comment annotations.
For example, if you have a function, and you want to enforce that callers catch exceptions it throws:
```
def find_targets(...):
   """
   semgrep:mustcatch[InvalidTargetError]
   """
   ....
```
Or a function where not using it's return value is probably a bug:
```
def run(f: str) -> int:
   """
   Run f as a command, return the exit code
   semgrep:mustuse
   """
```
`.pyi` files could also be used to add these annotations to existing libraries and built-ins (edited) 

Some other common patterns:
* A class that should never be instantiated (it should always be subclassed)
* A function that should only be called with a string literal argument (Eg. format)
* A function that should only be called after another function has been called.
* A function that requires a taint/untaint to have occured.

These meta rules would still be defined using the existing rules machinery. We would provide a standard set in the semgrep-rules repo, just at a more meta-level. (eg. you can define what must_use means when applied to a function definition). Individual users could also define their own meta-rules.

Obviously, this is slightly out of the current semgrep style of file local analysis, but I think a first-parsing pass maybe be worthwhile for these sorts of features.

**Describe Alternatives You've Considered**
I see this as having a couple of main advantages over hand writing rules for these sorts of cases:

It's easy for developers not versed in the semgrep rules language or the CI machinery to add rules for common cases.
Since the rules are in the code, they are less likely to become stale.

**Comment by aryx** [comment]
Follow

**Comment by aryx** [comment]
Recent need in OCaml: 
(* !Note that this assumes Naming_AST.resolved has been called before! *)
val propagate: Lang.t -> AST.program -> unit

**Comment by aryx** [comment]
cc @mjambon

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
keep it

**Comment by aryx** [comment]
👋

**Comment by mjambon** [comment]
.

**Comment by aryx** [comment]
:wave:

**Comment by ievans** [comment]
@aryx I think we should close this out, we aren't planning to do it and haven't had interest. We can add it to an internal hackathon doc though.
