### ISSUE TITLE
Local CLI slower than semgrep.live/scan

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1060]
I ran the same analysis both locally and on semgrep.live/scan and counter intuitively semgrep.live is much faster...

Running the django rule pack on Zulip takes 57s.
Running the django rule pack on Zulip online takes 35s.

```bash
$ semgrep --version
0.11.0
$ git clone git@github.com:zulip/zulip.git
$ cd zulip && git checkout 3d97050e75
$ time semgrep --config "https://semgrep.live/c/p/django"

...

semgrep --config "https://semgrep.live/p/django" --json  57.16s user 8.05s system 172% cpu 37.784 total
```

Semgrep scan: https://semgrep.live/scan/6562d0e3-e276-43b0-9f6c-9285c4cd74da

![image](https://user-images.githubusercontent.com/605906/84960418-67c93f00-b0b6-11ea-88b1-6264d1522444.png)

These numbers differ by 2 minutes from what @minusworld found (2m46s).

I also tried running the docker image locally:

```bash
$ time docker run --rm -v "${PWD}:/home/repo" returntocorp/semgrep --config 
using config from https://semgrep.live/p/django. Visit https://semgrep.live/registry to see all public rules.
running 19 rules.....

...

docker run --rm -v "${PWD}:/home/repo" returntocorp/semgrep --config   0.09s user 0.16s system 0% cpu 4:56.99 total
```

Docker takes 4m56s, using container with `Digest sha256:9f36defbdbe2e3ebca59d4988fac2bcc6d5d9d06dd78ae86bfc980c5e024840d`

**Comment by brendongo** [comment]
I think you're reading the timing information wrong? Looks like running it locally for you took 37.784 seconds.

FWIW when I run it locally it takes 15.897 seconds

**Comment by dlukeomalley** [comment]
Maybe I did, the wall clock time from a run just now was around 30s. I'll close for now.
