### ISSUE TITLE
semgrep homebrew recipe generates invalid fish shell completion file

### ISSUE THREAD

**Issue by simonwhitaker** [semgrep/semgrep#10618]
**Describe the bug**

After running `brew install semgrep` on a system that uses the fish shell, an invalid completion file is generated.

**To Reproduce**

```
$ brew install semgrep
$ cat /opt/homebrew/share/fish/vendor_completions.d/semgrep.fish

┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘
Semgrep CLI scans your code for bugs, security and dependency vulnerabilities.

For more information about Semgrep, visit https://semgrep.dev

Get Started:
  Run `semgrep login && semgrep ci` to enable Pro rules, Semgrep Supply Chain,
  and secrets scanning. Without logging in, Semgrep CLI will only run the free
  open-source rules available at https://semgrep.dev/r.

Commands:
  semgrep login                Enable Pro rules, Supply Chain, and secrets scanning
  semgrep ci                   Run Semgrep on the latest git diff (for use in CI)
  semgrep scan                 Run Semgrep rules on local directories or files

Help:
  semgrep COMMAND --help       For more information on each command

For the CLI docs visit https://semgrep.dev/docs/cli-reference
```

Then next time you open your shell, type `semgrep `. On typing the space, you'll get this error:

```
$ semgrep /opt/homebrew/share/fish/vendor_completions.d/semgrep.fish (line 22): Unexpected end of string, square brackets do not match
For the CLI docs visit https://semgrep.dev/docs/cli-reference
                                                                        ^
from sourcing file /opt/homebrew/share/fish/vendor_completions.d/semgrep.fish
source: Error while reading file '/opt/homebrew/share/fish/vendor_completions.d/semgrep.fish'
```

**Expected behavior**

A valid completion script is output

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

- MacOS 15.0.1
- fish 3.7.1
- semgrep 1.92.0

**Use case**

Command-line completion in fish.

**Comment by kopecs** [comment]
This is an issue in the brew formula; looks like it's because of the way click completion generation interacts with the fact that click is only used by default as a fallback for the CLI.

**Comment by kopecs** [comment]
To be resolved by https://github.com/Homebrew/homebrew-core/pull/195857
