### ISSUE TITLE
So much wrong answers!

### ISSUE THREAD

**Issue by JerryPW** [semgrep/semgrep#10626]
Hi! Thanks for your great work on detecting code vulnerbilities. 
However, when I was trying to utilize the reentrancy attack examples from https://github.com/pcaversaccio/reentrancy-attacks . I accidentally found out that semgrep had got 0 correct answer, i.e: none of the reentrancy attack had been detected by semgrep. Since I noticed that you got a really delicate website and detailed README in github, I wondered whether am I performing the right procedure. 
![截屏2024-10-29 00 06 23](https://github.com/user-attachments/assets/bb3de17b-f07f-40ff-9849-54eb59c1f8f4)

Is it proper for semgrep showing the result like this? If not, please inform me about the right way to use your product checking my code. If the total procedure is fine, could you please to tell me  about the why semgrep didn't perform well in these examples and what are suitable situations for utilizing semgrep.

Looking forward for your reply!

**Comment by ievans** [comment]
hi @JerryPW , this isn't an issue with the Semgrep engine (this repository). The question is what rules you are running Semgrep with: the default rules don't cover re-entrancy attacks. 

I'd recommend asking your question in Slack: https://go.semgrep.dev/slack
