### ISSUE TITLE
Matching expression which should be excluded: float constant with docstring

### ISSUE THREAD

**Issue by bellon-tiobe** [semgrep/semgrep#10644]
**Describe the bug**
Given this [target test code](https://semgrep.dev/playground/r/OrUN18p/juan_bellon_tiobe_com.asml-xxxx-document-constants):
```julia
module BadStyle
    # ruleid: asml-xxxx-document-constants
    const MAG_THRESHOLD::Float64 = 3.00 # In ppm

    # ruleid: asml-xxxx-document-constants
    const C_SPEED_OF_LIGHT = 299792458.0   # in m/s

    const TITLE = "Document constants"
    const NUMBER::Int64 = 42
end

module GoodStyle
    "C_SPEED_OF_LIGHT represents the speed of light in m/s"
    const C_SPEED_OF_LIGHT::Float64 = 299792458.0

    "MAG_THRESHOLD is dimensionless. A value of 0 means no expansion."
    const MAG_THRESHOLD::Float64 = 3e-6

    const BIT = (NUMBER == 42)
    const VECTOR::Array{Int,1} = [1, 2, 3]
end
```
only the first 2 definitions of `const` numbers should be "caught". However, the rule also flags the definition of `GoodStyle.MAG_THRESHOLD`, initialized to value `3e-6`. I have tried writing it as `3.0e-6` but it didn't matter.

**To Reproduce**
Go to [the rule definition](https://semgrep.dev/playground/r/OrUN18p/juan_bellon_tiobe_com.asml-xxxx-document-constants) and run it. Done.
But, for added fun, try swapping lines 16 & 17 and run again. Now the wrong match is on the previous `const` definition. How come?

**Expected behavior**
As indicated by the `ruleid` comments, only the first 2 definitions of `const` numbers should be flagged.

**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Same result with offline scan in WSL, with version 1.93.0 of Semgrep.

**Use case**
Implement a rule checking a point from ASML's _Julia_ coding standard: all float constants must be documented with a _docstring_.

**Comment by iuliadmtru** [comment]
You need a `pattern-not-inside` instead of a `pattern-not`: https://semgrep.dev/playground/s/kxEn2

**Comment by bellon-tiobe** [comment]
Thank you, Iulia! I would say, it is not intuitive: how did you know to use `pattern-not-inside` instead of `pattern-not`? In this case, there is nothing that suggests "inside"; it is just a pattern to either match or not. Is it just a matter of experience?

**Comment by iuliadmtru** [comment]
```
patterns:
      - pattern: $EXPR
      - pattern-not: |-
          "$DOCSTRING"
          $EXPR
```

This says that you are looking for something that looks both like `$EXPR` and not like `"$DOCSTRING"\n$EXPR`. The negation is redundant. `$EXPR` can never look like `something` + `$EXPR`, right? So this is just like writing:

```
pattern: $EXPR
```

which is why you see all those assignments matched.

What you want is something that looks like `$EXPR` but _is not INSIDE_ (or _is not contained within_) something that looks like `something` + `$EXPR`. Makes more sense now?

**Comment by bellon-tiobe** [comment]
Yes, it does. Thanks a lot!
