### ISSUE TITLE
Meaning of errors that Semgrep can produce

### ISSUE THREAD

**Issue by DmytroLynda** [semgrep/semgrep#10643]
Hi

I'm working on a solution that uses **Semgrep CLI** with custom rules to scan a code base for security vulnerabilities.
I have some difficulties to find this information in docs, so decided to ask here.

Basically I get the following json structure as a scan result: 
```
{
    errors: [],
    results: [],
    interfile_languages_used: [],
    paths: [],
    skipped_rules: [],
    version: []
}
```

Is it possible that I'll get a finding and an error for a single file on the same scan run?
If so, may I kindly ask you to provide some information when it happens? For example some specific error types.

**Semgrep version: 1.89.0**

Thank you in advance!

**Comment by kopecs** [comment]
> Is it possible that I'll get a finding and an error for a single file on the same scan run?

Yes. You could get, for instance, a [`PartialParsing`](https://github.com/semgrep/semgrep-interfaces/blob/64dd682a52edb70b47ad52687bc1c3e0bc4e8c3b/semgrep_output_v1.atd#L503) error but still have a finding. Something like
```ts
function func(x: number): void {
    return x;
}

class something
```
with the pattern
```
function $FUNC(...): void {
  ...
  return $_;
}
```
would be an example.

**Comment by ievans** [comment]
Hey, this is probably more appropriate as a discussion / help request on slack. Closing as an issue but feel free to re-open,
