### ISSUE TITLE
Does it support checking for MISRA-C guidelines ?

### ISSUE THREAD

**Issue by aygupt1822** [semgrep/semgrep#10664]
Does the Semgrep support checking for MISRA-C guidelines ?

Do I need to write my own custom ruleset based on MISRA-C guidelines because I was not able to find the proper ruleset for Semgrep in MISRA-C.

**Comment by nmote** [comment]
This issue tracker is for bugs and feature requests for the Semgrep engine itself. Feel free to ask about rulesets for specific purposes in our community slack.
