### ISSUE TITLE
Unable to parse pattern with Java field level annotation 

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1071]
The following pattern cannot parse because of the field level annoation `@Language`.

https://semgrep.live/nJ8b

**Comment by aryx** [comment]
Annotations on fields/statements are supported in tree-sitter, but not in the pfff java parser, which is used
to parse the pattern.

**Comment by emjin** [comment]
This works: https://semgrep.dev/s/emjin:java-annotation
