### ISSUE TITLE
Swift AST JSON, Visibility Modifier Issues

### ISSUE THREAD

**Issue by rebeccaswords** [semgrep/semgrep#10727]
**Describe the bug**
I am looking at the JSON AST (using CLI flag -show_ast_json) generated for the following Swift code:

```
public class Test {
    public var t: Int = 0
    open var u: String = "a"
    //package let v: Bool = false
    var w: Int = 5
    internal let x: Bool = true
    fileprivate let y: String = "b"
    private var z: Int = 10
}
```

I have two issues:
1. Uncommenting the package variable causes the parser to halt and generates the warning `fail to fully parse Test.swift`, and some other variables later in the file do not have visibility modifiers included in their KeywordAttr lists. I think this is because `package` is not included in the list of visibility modifiers for Swift.

2. The `fileprivate` variable is tagged with visibility `Public`. I was expecting it to be tagged as `Private` based on the Swift documentation.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev/playground (click "share" and make public to get a shortlink):
1. Place sample code in file Test.swift
2. Run `semgrep-core -show_ast_json Test.swift`
3. Examine KeywordAttr list on the entities associated with each VarDef definition.

**Expected behavior**
1. Use of the `package` modifier doesn't halt parsing
4. `fileprivate` variables are tagged with visibility `Private` instead of `Public`

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
official binary

**Use case**
What will fixing this bug enable for you?
Improve our ability to track visibility of symbols across Swift files

**Comment by nmote** [comment]
Thanks for the bug report. Could you share a bit more about your use of the `-show_ast_json` flag? We are considering removing it since it's a maintenance burden and we don't use it as part of our product.

**Comment by rebeccaswords** [comment]
We are working on adding support for Swift to our static analysis tool, and we use `show_ast_json` to help understand what SemGrep is doing. It has been useful for seeing how SemGrep thinks about Swift.

**Comment by nmote** [comment]
For that purpose, I recommend `semgrep-core -dump_ast` -- that will print the AST in a form that is automatically derived from our internal representation of the AST rather than a hand-maintained JSON format that has gradually drifted away from our actual AST.
