### ISSUE TITLE
SARIF output RPC error "Missing required field languages" when using join-mode rules

### ISSUE THREAD

**Issue by ansereb** [semgrep/semgrep#10723]
**Describe the bug**
Today SARIF output started to throw RPC errors, while JSON scan is still ok. Yesterday all scan were ok and no changes were made from my side.

**To Reproduce**
Launch the scan with
`semgrep scan  --sarif --output report.sarif` 
Gives following errors in scan status section:
```
Scanning 5974 files tracked by git with 2 Code rules:
  Scanning 5031 files with 2 <multilang> rules.
  Current version has 0 findings.

Skipping baseline scan, because there are no current findings.
RPC response indicated an error: Error handling RPC request:
Failure: Error in parsing: invalid YAML, /tmp/tmphiqcq8z3.json:41215:4: Missing required field languages
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Core_scan.rules_of_config.(fun) in file "OSS/src/core_scan/Core_scan.ml", line 393, characters 12-74
Called from Tracing.with_span.(fun) in file "OSS/libs/tracing/unix/Tracing.ml", line 316, characters 10-14
Re-raised at TCB.Printexc.raise_with_backtrace in file "OSS/TCB/TCB.ml", line 1064, characters 29-58
Called from RPC_return.sarif_format in file "OSS/src/rpc/RPC_return.ml", line 57, characters 4-66
Called from RPC.handle_call in file "OSS/src/rpc/RPC.ml", line 37, characters 8-157
Called from RPC.handle_single_request in file "OSS/src/rpc/RPC.ml", line 133, characters 8-29
```
Results in report.sarif contains
`"<ERROR: no SARIF output>"`

**Expected behavior**
Scan results in SARIF format

**Screenshots**
![image](https://github.com/user-attachments/assets/981fa411-e31e-4de8-bc14-57133664de34)

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Environment - Github Actions
Both docker semgrep/semgrep:latest (Digest: sha256:ae27024c16f7848cdbfd49c24ed0b78b13f13b85fcd7b87c679aaa8b0c0dce98) and pip (semgrep-1.99.0-cp38.cp39.cp310.cp311.py37.py38.py39.py310.py311-none-musllinux_1_0_x86_64.manylinux2014_x86_64.whl) versions

**Use case**
Continue to use semgrep in code scans

**Comment by nmote** [comment]
Thanks for the report. We recently changed how SARIF output is generated and it looks like you are running into a bug with the new codepath. We will take a look.

**Comment by aryx** [comment]
Can you paste the content of this /tmp/tmpxxx.json ?

**Comment by aryx** [comment]
also scan is supposed to take a --config as a parameter, so can you copy paste the actual config you've used
to run your scan and if it's using custom rules, can you copy the content of those rules so we can try to reproduce locally.

**Comment by ansereb** [comment]
Hi @aryx ! Thank you for quick response. In fact, full command i'm using is:
`semgrep scan --sarif --output report.sarif --metrics=off --config="p/default" --dataflow-traces --baseline-commit  ${{ github.event.pull_request.base.sha }}`
About /tmp/tmpxxx.json i think it is deleted right after executing semgrep scan. Here is the `ls /tmp` right after scan:
![image](https://github.com/user-attachments/assets/6de0af3b-1577-4a93-a472-8eb2a5f2c0eb)

**Comment by aryx** [comment]
Are you using custom rules?

**Comment by ansereb** [comment]
Yes, sorry, i just found out that we are using some rules from https://github.com/elttam/semgrep-rules . And after removing them SARIF is being created normally. I attached rules we are using
[rules.zip](https://github.com/user-attachments/files/18094533/rules.zip)

**Comment by ansereb** [comment]
Maybe some rule metadata format was changed which prevents SARIF formatting? It is interesting since JSON report is still OK running this rules

**Comment by aryx** [comment]
This is because one of your rule is a join mode rule,
generic/jsp-likely-xss.yaml
and such rule does not contain the `languages` field and the OCaml throw an error on such rule because
it does not handle such rule.
join-mode is actually deprecated and will be removed soon so you should probably remove this rule from your ruleset.

**Comment by aryx** [comment]
I can reproduce with
`semgrep scan --sarif --config jsp-likely-xss.yaml .`

**Comment by ansereb** [comment]
Thanks @aryx ! After removing the rule with `mode: join`, the SARIF is generated correctly. Should i close this issue?

**Comment by aryx** [comment]
I'm also making a proper fix that will auto close the issue once merged.
Thx for reporting!
