### ISSUE TITLE
Semgrep 1.100 issue - "requires login" message

### ISSUE THREAD

**Issue by massej** [semgrep/semgrep#10734]
**Describe the bug**
Since version 1.100 all elements detected in semgrep show "requires login" instead of the result in the json file.

**To Reproduce**
To install I use this command : python3 -m pip install semgrep

run semgrep using "semgrep scan" with the version 1.100 on a ubuntu linux. 

I did a rollback to 1.99 and semgrep is working.

**Expected behavior**
To have the description and lines of the result within the json file.

**Screenshots**
![image](https://github.com/user-attachments/assets/2f2b6f96-f022-40c8-8011-9b1b9a3b94b9)

**What is the priority of the bug to you?**
- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Microsoft Agent - Ubuntu 22.04 Image.

**Use case**
To be able to use semgrep.

**Comment by milanwilliams** [comment]
Hi @massej

This behavior is due to a planned change in Semgrep's output formats (introduced in version 1.100.0) as part of our updates to better distinguish between Semgrep Community Edition and the logged-in commercial platform. [View our blog post](https://semgrep.dev/blog/2024/important-updates-to-semgrep-oss/) for the full context.

As a result, some JSON fields, including matched lines, are now reserved for logged-in users of the commercial platform. 
For a full list of fields that differ between logged-out and logged-in use, please see our [documentation here](https://semgrep.dev/docs/semgrep-appsec-platform/json-and-sarif).

Though, we designed this change to have minimal impact on most community use cases. Since this is blocking you, please email me at [community-feedback@semgrep.com](community-feedback@semgrep.com), so I can help find a solution for you!

Milan

**Comment by massej** [comment]
Thank you for your quick reply @milanwilliams, I really appreciate

The lines attribute should be available with Semgrep CE according to the documentation : 
![image](https://github.com/user-attachments/assets/e3c51ad3-9c5e-4556-91b1-5a43e16c8a54)

Is there a reason why it is now requiring to have the commercial platform? Maybe I miss something?

**Comment by milanwilliams** [comment]
Hi @massej! This is an error in our documentation, sorry about that! I've opened a PR [here](https://github.com/semgrep/semgrep-docs/pull/1886) to fix this. 

To be clear, you will need to login in order for the `lines` field to be visible in the JSON output. To regain access, you can simply run `semgrep login` locally before your scan, or set the `SEMGREP_APP_TOKEN` in your [CI scan configuration](https://semgrep.dev/docs/semgrep-ci/ci-environment-variables#semgrep_app_token). 

To understand why we're changing the output formats, [you can view our blog post here](https://semgrep.dev/blog/2024/important-updates-to-semgrep-oss/). 

Let me know if you have any additional questions, here to help!

**Comment by massej** [comment]
Thank you for your quick reply, @milanwilliams 

Unfortunately, without the lines attribute, Semgrep CE loses much of its utility

**Comment by aryx** [comment]
The line numbers are still there; they do not require login. Not having those line numbers would indeed make semgrep CE pretty useless, but this is not the case; the line numbers are still there. The `lines` field was just containing the content of those lines, but this can be easily derived from the line numbers.

**Comment by massej** [comment]
@aryx are you sure that you use semgrep CE ? I just tested version 1.101 here is the result

{
  "filePath": "internal_api_apps/.apps.cjs",
  "lines": "requires login",
  "message": "A gitleaks aws-access-token was detected which attempts to identify hard-coded credentials. It is not recommended to store credentials in source-code, as this risks secrets being leaked and used by either an internal or external malicious adversary. It is recommended to use environment variables to securely provide credentials or retrieve credentials from a secure vault or HSM (Hardware Security Module).",
  "source": "[https://semgrep.dev/r/generic.secrets.gitleaks.aws-access-token.aws-access-token"](https://semgrep.dev/r/generic.secrets.gitleaks.aws-access-token.aws-access-token%22)
}

Also they updated the doc 
![image](https://github.com/user-attachments/assets/fde595c9-04bc-48e4-9cd8-29b5198971c6)

**Comment by aryx** [comment]
Those are fields of the `extra` object. The actual line/col information about a match are outside this extra object.
Give me the full command you run and the full JSON output and you will see the line/col where rules are matched.

**Comment by massej** [comment]
@aryx I see, i was always looking inside the extra object.

I can see the line number now, thank you!
