### ISSUE TITLE
Type propagation for go doesn't work when multiple variables are declared in a line

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#1077]
**Describe the bug**
When variables are declared together (var a, b = 1), only the first one is given the type int.

**To Reproduce**
https://semgrep.live/Kx96?version=develop

**Expected behavior**
Expected all three to be matched

**Comment by aryx** [comment]
I think it's normal, var a, b = 1  is just sugar for var a; var b = 1;  so we don't know anything about a.
Or am I wrong? var a, b = 1  means  var a = 1; var b = 1?

**Comment by dgryski** [comment]
`var a, b = 2` is not valid Go.  You need the same number of expressions on both sides of the equals sign.  Alternately you can have a function with the same number of return values.

https://golang.org/ref/spec#Assignments

**Comment by aryx** [comment]
closing then.
