### ISSUE TITLE
Semgrep match has incorrect range

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1081]
Even with @aryx's work merging the new pfff it appears the `@` is outside of the range: https://semgrep.live/10gQ?version=develop&stepByStep=1

![image](https://user-images.githubusercontent.com/605906/85178510-86087980-b233-11ea-849c-40e2e048de5b.png)

_Originally posted by @dlukeomalley in https://github.com/returntocorp/semgrep/issues/1072#issuecomment-646855139_

This is a continuation of https://github.com/returntocorp/semgrep/issues/959

**Comment by aryx** [comment]
Should work better once semgrep is using the latest pfff.
