### ISSUE TITLE
Support "final" in Java

### ISSUE THREAD

**Issue by sshayb** [semgrep/semgrep#1088]
**Is your feature request related to a problem? Please describe.**
Difficult to write rules to match functions called with static/const variables in Java. For example, here (https://semgrep.live/zdp0) I would expect lines 23 and 25 to match the pattern. Or even better - not require first 2 lines of the pattern at all and expect it to match on all 3 instances of MD5 use - i.e. lines 21, 23, 25.

**Describe the solution you'd like**
"final" in Java considered as const so that final variable propagation into functions will work as expected

**Describe alternatives you've considered**
Alternative suggested by Isaac: https://semgrep.live/L1d7

**Comment by dlukeomalley** [comment]
Thank you @sshayb for the ticket. Queuing this up for discussing on Monday with the team and will circle back. CC @ievans

**Comment by brendongo** [comment]
This will be in the next release but proof it works on develop here: https://semgrep.live/2Zvr?version=develop
