### ISSUE TITLE
Arbitrary files?

### ISSUE THREAD

**Issue by asad-awadia** [semgrep/semgrep#1093]
Can semgrep pattern match on Arbitrary file types? Or does it _have_ to be java/c/go code?

i.e. find X pattern in *.txt files or something like that?

**Comment by mschwager** [comment]
Hi @asad-awadia,

I'd like to understand your question a bit better. Which of the following are you trying to achieve:

1. Semantic code search on files with an extension different from the standard extension? E.g. `.txt` files that contain Python code.
2. Simple text search on something like a `.txt` file?

We do not currently support (1), but I think it would be a useful feature. If you're looking for (2), then we can achieve this with the [`pattern-regex`](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#pattern-regex) operator. For example:

```
$ cat test.yaml 
rules:
- id: arbitrary-file
  pattern-regex: 'foo\('
  message: 'Arbitrary file'
  languages: [python] # Placeholder for required 'languages'
  severity: ERROR
```

```
$ cat test.txt 
foo(1, 2, 3)
```

```
$ semgrep --config test.yaml test.txt
running 1 rules...
test.txt
severity:error rule:arbitrary-file: Arbitrary file
1:foo(
```

Note that `test.txt` must be explicitly specified for `semgrep` to consider the file - using something like `--include "*.txt"` does not currently work. If you'd like to run this over many `.txt` files then something like the following should work:

```
$ semgrep --config test.yaml $(find /path/to/directory -name "*.txt")
```

Currently, the `--include` flag only filters files it's already considering as opposed to adding additional files. Your question makes me realize that it would be useful to have a flag that adds additional files matching the glob as well. Hope this is helpful :+1:

**Comment by mschwager** [comment]
Actually, now that I think about it, explicitly specifying files should work for (1) too. E.g. doing semantic code search using something like [`pattern`](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#pattern). For example, building on the example above:

```
$ cat test.yaml 
rules:
- id: arbitrary-file
  pattern: foo(...)
  message: 'Arbitrary file'
  languages: [python]
  severity: ERROR
```

```
$ semgrep --config test.yaml test.txt 
running 1 rules...
test.txt
severity:error rule:arbitrary-file: Arbitrary file
1:foo(1, 2, 3)
```

Or again, we can use `find` to explicitly specify many `.txt` files:

```
$ semgrep --config test.yaml $(find /path/to/directory -name "*.txt")
```

**Comment by asad-awadia** [comment]
@mschwager thank you for such a detailed response!

I am looking to do semgrep rules over code/languages that are not supported - such as Bazel build files and proto files - with my own custom rules

so `.bazel` and `.proto` which will have the bazel 'code' and proto 'code' respectively

**Comment by mschwager** [comment]
> @mschwager thank you for such a detailed response!
> 
> I am looking to do semgrep rules over code/languages that are not supported - such as Bazel build files and proto files - with my own custom rules
> 
> so `.bazel` and `.proto` which will have the bazel 'code' and proto 'code' respectively

In that case you'll have to use `pattern-regex` with simple text searching over those files for now. As mentioned above you can use a configuration like the following:

```
$ cat test.yaml 
rules:
- id: arbitrary-file
  pattern-regex: 'foo\('
  message: 'Arbitrary file'
  languages: [python] # Placeholder for required 'languages'
  severity: ERROR
```

And run `semgrep` like so:

```
$ semgrep --config test.yaml $(find /path/to/directory -name "*.bazel")
```

```
$ semgrep --config test.yaml $(find /path/to/directory -name "*.proto")
```

Eventually we will support a better way to specify these extensions (tracking in #1099), but that should work for now. We may also officially support Bazel and Proto files in the future with standard `pattern` functionality, but it's not currently on our roadmap.

Hope this clears everything up! Do you have any other questions?

**Comment by asad-awadia** [comment]
@mschwager 
one last question - I am trying to learn how to write the rules and the grammar for the rules - do you have any tips on how to get a feel of it? I tried the live editor but still kind of difficult

eg. I am trying to write a rule where if a certain function `foo` is called without a certain argument `timeout` - I want it to get upset

i.e. `foo(x=1, y=2, timeout=3)` should not alert 
but `foo(x=1, y=2)` should alert

can something like this be done?

**Comment by minusworld** [comment]
@asad-awadia 👋 

We have a few good starting points, but we recognize that helping people know where to get started needs a little work... 😅 

For starters, we have a rule in Semgrep's registry that does this for Python's `requests` module. Taking a look here should help you get started:
https://semgrep.live/r?q=python.requests.best-practice.use-timeout.use-timeout

We also have documentation that might be useful, though it's a little bit buried on the GitHub page:
https://github.com/returntocorp/semgrep/tree/develop/docs

And lastly, we have https://semgrep.live/learn, which will be updated in a just few days to help people get the hang of writing rules. Look for it later this week! :)

**Comment by mschwager** [comment]
> @asad-awadia wave
> 
> We have a few good starting points, but we recognize that helping people know where to get started needs a little work...

Don't forget about this great new addition: [Writing Rules](https://github.com/returntocorp/semgrep/blob/develop/docs/writing_rules/examples.md)

On top of that, I'd recommend these two pieces of documentation most for getting started:

* [Configuration Files](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md)
* [Pattern Features](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md)

If you have any other questions, or suggestions on where we can improve let us know!

**Comment by asad-awadia** [comment]
Thank you so much - I will read through!
