### ISSUE TITLE
Pattern searching '#include' doesn't work in C

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1095]
Similar to other languages, it would be great if we supported C's "import" functionality using '#include'. Currently, it looks like we can't even parse a pattern like '#include $X':

```
$ cat test.c 
#include <stdio.h>
#include <string.h>
#include "local.h"

int main() {
   printf("Hello, World!");
   return 0;
}
```

```
$ semgrep -l c -e '#include $X' test.c
...
  File "semgrep/semgrep/rule_lang.py", line 278, in parse_yaml_preserve_spans
    f"Something went wrong parsing Yaml (expected a YamlTree as output): {PLEASE_FILE_ISSUE_TEXT}"
Exception: Something went wrong parsing Yaml (expected a YamlTree as output): An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://semgrep.dev
```

It looks like we're failing before even reaching `semgrep-core`. Maybe @rcoh knows what's going on.

**Comment by rcoh** [comment]
Can you see what happens on my branch that fixes the none issue? Will debug when I get online this morning

**Comment by rcoh** [comment]
As I suspected, `#include` is being interpreted as a YAML comment :roll_eyes: will fix
