### ISSUE TITLE
Python false positive not when considering imported module

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1096]
Let's say I'm looking for unsafe usage of the `yaml.load` function. This comes from the [`yaml` module](https://pyyaml.org/wiki/PyYAMLDocumentation). We'd write a pattern like `yaml.load(...)` and run it against code like:

```python
import yaml

yaml.load(filename)
```

However, this also considers variables named `yaml` calling their `load` method. E.g.

```python
from other_yaml_module import YAML

yaml = YAML()
yaml.load(filename)
```

```
$ python -m semgrep -l python -e 'yaml.load(...)' test.py 
test.py
4:yaml.load(filename)
```

We should ensure that the module is imported when considering the full module path of something like `yaml.load`. Note that the module path can also be arbitrarily deep, like:

```python
import os.path.join

os.path.join('foo', 'bar')
```

**Comment by aryx** [comment]
What about
import yaml
...
yaml.load(...)

Would that be good enough?

**Comment by mschwager** [comment]
That would work for shallow modules, but not easily specified for deeper modules. E.g. for `os.path.join` we'd need 3 patterns:

```
import os
...
os.path.join(...)
```


```
from os import path
...
path.join(...)
```


```
from os.path import join
...
join(...)
```

There's also the inverse where we **no longer** want to detect something based on imports. Like if we're trying to detect the builtin [`eval`](https://docs.python.org/3/library/functions.html#eval), but it's been "imported over":

```
from other_module import eval
...
eval(...)
```

None of this is urgent, but they're FPs worth considering.

**Comment by aryx** [comment]
@mschwager can you link to semgrep.dev examples of what does not currently work?

**Comment by mschwager** [comment]
> @mschwager can you link to semgrep.dev examples of what does not currently work?

- https://semgrep.dev/s/DJRv/
- https://semgrep.dev/s/Wgyo/

**Comment by mschwager** [comment]
Another edge-case from GitLab (https://gitlab.com/gitlab-org/gitlab/-/issues/331452): `__import__`.

E.g. https://semgrep.dev/s/qr1b/
