### ISSUE TITLE
Add functionality to include additional file extensions to targets

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1099]
Currently, the `--include` flag filters targets based on the specified argument instead of adding them. E.g. if we specify `languages: [java]` we filter targets based on the `.java` extension, we then filter targets again based on the `--include` flag. This doesn't really make any sense since we've already done the initial filtering.

It makes more sense for `--include` to be additive. E.g. if for some reason you have Java code with the `.txt` extension you can specify `--include "*.txt"` to also consider those files. This also allows us to use `pattern-regex` over arbitrary file extensions instead of having to use a hack like in #1093: `$(find /path/to/directory -name "*.ext")`.

This is also odd for using `--include` on a directory like `--include additional-directory/` when you could just include that directory in the list of targets like `semgrep --config sem.yaml additional-directory/`. 

Let's make this workflow easy!

**Comment by brendongo** [comment]
Does this work if the config file has rules for multiple languages? i.e. If you have some config that has python and javascript rules and want to run the javascript rules on .ts files

**Comment by brendongo** [comment]
Either way I do agree it does make more sense for --include to be additive since right now it replicates target functionality.

**Comment by brendongo** [comment]
Maybe we might also need a mechanism that allows uses to say treat this extension as this type of file?

**Comment by Isaac0616** [comment]
> Maybe we might also need a mechanism that allows uses to say treat this extension as this type of file?

I like this approach.
It allows per rule customization.

**Comment by mschwager** [comment]
Unassigning myself - https://github.com/returntocorp/semgrep/pull/1774 didn't go through.
