### ISSUE TITLE
Support for Kotlin language

### ISSUE THREAD

**Issue by asm0dey** [semgrep/semgrep#1118]
**Is your feature request related to a problem? Please describe.**
Please, add support for Kotlin language. It's evolving in JVM ecosystem, but has deficiency on static analysis tools.

**Comment by dlukeomalley** [comment]
@asm0dey Updating here - we're looking at Kotlin as a nearer term language addition. I'm working with @DrewDennison and @aryx on specific dates, likely Q4.

**Comment by asm0dey** [comment]
Thanks for update!

**Comment by SPoint42** [comment]
What did you need to help ?

**Comment by aryx** [comment]
@mjambon can you add kotlin to ocaml-tree-sitter-lang so I can start to write the skeleton and maybe people can start contribute.

**Comment by aryx** [comment]
https://github.com/fwcd/tree-sitter-kotlin seems to be the tree-sitter we want.

**Comment by aryx** [comment]
@SPoint42 @asm0dey can you look at the tree-sitter-kotlin link and check if the grammar looks up to date with the recent versions of Kotlin, or do you know a better repository with the kotlin grammar in tree-sitter format?

**Comment by SPoint42** [comment]
I'm not familiar with tree-sitter. I could help to try to parse some kotlin sources files or execute and/or write query for semgrep kotlin indeed

**Comment by dimsuz** [comment]
I also have access to a few rather large kotlin codebases (android apps) and can check how parser works on them.

**Comment by SPoint42** [comment]
any progress  ? or Estimate Time to have something ?

**Comment by aryx** [comment]
It's on our Q4 roadmap, so maybe in november.

**Comment by aryx** [comment]
Unless we get many customers requesting Kotlin.

**Comment by brownierin** [comment]
I'm also interested in Kotlin support.

**Comment by oreza** [comment]
me too

**Comment by DrewDennison** [comment]
update on this: @colleend is actively working on kotlin support! We hope to have it in alpha this month. Thanks for all the enthusiasm!

**Comment by colleend** [comment]
We have currently shipped Kotlin as 'experimental' in Semgrep v.38! There's still some work to do before metavariables and ellipsis are fully functional, but tagging people who have liked this issue as a heads up @findjigar @asm0dey @rashadsookram @dimsuz @SPoint42 @starsep @radnair @traw @eoftedal @IndexOverflow

Some PRs that have been pushed:
[2288](https://github.com/returntocorp/semgrep/pull/2288)
[2226](https://github.com/returntocorp/semgrep/pull/2226)

**Comment by aryx** [comment]
We now need examples of rules people would like to write for kotlin! Anybody?

**Comment by SPoint42** [comment]
At least the rules at  https://find-sec-bugs.github.io/

I've implemented and add some code examples to checks. If you consider the kotlin implementation stable, I could help and tests

**Comment by aryx** [comment]
@colleend do you think you could port our java findsec bugs rule to Kotlin?

**Comment by dimsuz** [comment]
We have rules:

* detect if lambda is more than 2 lines long and has "it" inside. Suggest replacing it with explicit parameter name
* detect if function with primitive arguments is called without supplying their names for readability. Example: `hello(5, null, false)` Suggestion: `hello(count = 5, title = null, showDescription = false)`
* detect if file has `package com.example.domain.test`, but is _not_ located in folder `com/example/domain/test`

 you can also get a lot of rule ideas from the [Detekt](https://github.com/detekt/detekt) project (static analyzer for Kotlin)

**Comment by colleend** [comment]
yes! I can port findsec bugs to Kotlin 😄  

Detekt seems to have some great rule ideas -- thanks for the input!

**Comment by SPoint42** [comment]
The best for security is findsecbugs. Detekt only see some "style"/"lint" .

**Comment by ievans** [comment]
Kotlin is now officially in [beta](https://semgrep.dev/docs/language-support/), so I'm closing this issue -- please create new issues for any Kotlin-specific bugs!
