### ISSUE TITLE
Default matching output is confusing; no separation and weird line order

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1120]
Here is what I get with
semgrep --config contrib/nodejsscan/header_cors_star.yaml contrib/nodejsscan/header_cors_star.js
in semgrep-rules:

<pre>running 2 rules...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|2/2
<font color="#4E9A06">contrib/nodejsscan/header_cors_star.js</font>
<font color="#C4A000">severity:warning rule:contrib.nodejsscan.express_cors: Access-Control-Allow-Origin response header is set to &quot;*&quot;. This will disable CORS Same Origin Policy restrictions.</font>
<font color="#4E9A06">15</font>:    <b>var y = 1;</b>
<font color="#4E9A06">16</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">17</font>:<b>    var x = &apos;*&apos;;</b>
<font color="#4E9A06">18</font>:<b>    //sgrep bug - https://github.com/returntocorp/sgrep/issues/512</b>
<font color="#4E9A06">19</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">20</font>:<b>    res.writeHead(200, { &apos;Access-Control-Allow-Origin&apos;: &apos;*&apos; });</b>
<font color="#4E9A06">21</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">22</font>:<b>    res.set(&apos;access-control-allow-origin&apos;, &apos;*&apos;);</b>
<font color="#4E9A06">23</font>:<b>    //do not match - sgrep bug -rewrite-rule</b>
<font color="#4E9A06">24</font>:<b>    res.set(&apos;Access-Control-Allow-Origin&apos;, &apos;google.com&apos;);</b>
<font color="#4E9A06">25</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">26</font>:<b>    res.set(&apos;Access-Control-Allow-Origin&apos;, &apos;*&apos;);</b>
<font color="#4E9A06">27</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">28</font>:<b>    res.set({</b>
<font color="#4E9A06">29</font>:<b>        &apos;Content-Length&apos;: 123,</b>
<font color="#4E9A06">30</font>:<b>        &apos;access-control-allow-origin&apos;: &apos;*&apos;,</b>
<font color="#4E9A06">31</font>:<b>        &apos;ETag&apos;: &apos;12345&apos;</b>
<font color="#4E9A06">32</font>:<b>    })</b>
<font color="#4E9A06">33</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">34</font>:<b>    res.writeHead(200, { &apos;Access-Control-Allow-Origin&apos;: &apos;*&apos; })</b>
<font color="#4E9A06">35</font>:
<font color="#4E9A06">36</font>:<b>    res.set(&apos;access-control-allow-origin&apos;, x);</b>
<font color="#4E9A06">17</font>:    <b>var x = &apos;*&apos;;</b>
<font color="#4E9A06">18</font>:<b>    //sgrep bug - https://github.com/returntocorp/sgrep/issues/512</b>
<font color="#4E9A06">19</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">20</font>:<b>    res.writeHead(200, { &apos;Access-Control-Allow-Origin&apos;: &apos;*&apos; });</b>
<font color="#4E9A06">21</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">22</font>:<b>    res.set(&apos;access-control-allow-origin&apos;, &apos;*&apos;);</b>
<font color="#4E9A06">23</font>:<b>    //do not match - sgrep bug -rewrite-rule</b>
<font color="#4E9A06">24</font>:<b>    res.set(&apos;Access-Control-Allow-Origin&apos;, &apos;google.com&apos;);</b>
<font color="#4E9A06">25</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">26</font>:<b>    res.set(&apos;Access-Control-Allow-Origin&apos;, &apos;*&apos;);</b>
<font color="#4E9A06">27</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">28</font>:<b>    res.set({</b>
<font color="#4E9A06">29</font>:<b>        &apos;Content-Length&apos;: 123,</b>
<font color="#4E9A06">30</font>:<b>        &apos;access-control-allow-origin&apos;: &apos;*&apos;,</b>
<font color="#4E9A06">31</font>:<b>        &apos;ETag&apos;: &apos;12345&apos;</b>
<font color="#4E9A06">32</font>:<b>    })</b>
<font color="#4E9A06">33</font>:<b>    // ruleid:express_cors</b>
<font color="#4E9A06">34</font>:<b>    res.writeHead(200, { &apos;Access-Control-Allow-Origin&apos;: &apos;*&apos; })</b>
<font color="#4E9A06">35</font>:
<font color="#4E9A06">36</font>:<b>    res.set(&apos;access-control-allow-origin&apos;, x);</b>
<font color="#4E9A06">20</font>:    <b>res.writeHead(200, { &apos;Access-Control-Allow-Origin&apos;: &apos;*&apos; });</b>
<font color="#4E9A06">22</font>:    <b>res.set(&apos;access-control-allow-origin&apos;, &apos;*&apos;);</b>
<font color="#4E9A06">26</font>:    <b>res.set(&apos;Access-Control-Allow-Origin&apos;, &apos;*&apos;);</b>
<font color="#4E9A06">28</font>:    <b>res.set({</b>
<font color="#4E9A06">29</font>:<b>        &apos;Content-Length&apos;: 123,</b>
<font color="#4E9A06">30</font>:<b>        &apos;access-control-allow-origin&apos;: &apos;*&apos;,</b>
<font color="#4E9A06">31</font>:<b>        &apos;ETag&apos;: &apos;12345&apos;</b>
<font color="#4E9A06">32</font>:<b>    })</b>
<font color="#4E9A06">34</font>:    <b>res.writeHead(200, { &apos;Access-Control-Allow-Origin&apos;: &apos;*&apos; })</b>
<font color="#4E9A06">6</font>:<b>app.options(&apos;*&apos;, cors())</b>
</pre>

**Comment by aryx** [comment]
see the 6:app.options at the very end, or 20: just after 36:
At least they should be separated.

**Comment by mschwager** [comment]
I think this got done with @ievans's https://github.com/returntocorp/semgrep/pull/2082 PR. Can we close?

**Comment by ievans** [comment]
Yup from me!
