### ISSUE TITLE
Print number of files that were successfully/unsuccessfully parsed

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1126]
In large projects there will often be a few files that fail to parse, despite the overwhelming majority being successfully parsed. Users may be confused if they see a few parse errors and no results. To remedy that let's include some information on files that successfully/unsuccessfully parsed.

Currently the output is something like:

```
$ semgrep --exclude 'bad-symlinks' --config "https://semgrep.live/p/javascript" ~/r2c/echelon-backend/analysis/analyzers/r2c/transpiler/src/tests/testdata/
using config from https://semgrep.live/p/javascript. Visit https://semgrep.live/registry to see all public rules.
excluding files:ig...
- bad-symlinks
running 10 rules...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|10/10
3 file(s) failed to parse: ~/r2c/echelon-backend/analysis/analyzers/r2c/transpiler/src/tests/testdata/all-parse-failure/bad.js, ~/r2c/echelon-backend/analysis/analyzers/r2c/transpiler/src/tests/testdata/bad-file/bad.js, ~/r2c/echelon-backend/analysis/analyzers/r2c/transpiler/src/tests/testdata/dialects/es9.js
Run with --verbose to see parse errors
Run with --strict to exit with non-zero exit code when errors exist
```

At the end we could include something like: `Successfully parsed VVV/YYY (ZZ%) files and failed to parse WWW/YYY (UU%)`

If a user sees we parsed 99.9% of files with no findings they'll be more confident in the analysis.

**Comment by dlukeomalley** [comment]
> If a user sees we parsed 99.9% of files with no findings they'll be more confident in the analysis.

Big +1 to this! Something like could do the trick (focusing on the success rate instead of the failure rate):

```bash
98% (105/107) files parsed successfully
```

**Comment by pabloest** [comment]
+1 to this. I ran 196 Semgrep rules on a small repo today and Semgrep chewed through it very quickly. There were no parse errors, but it ran so quickly I wondered what happened, if Semgrep found anything, how many files it scanned, etc.

**Comment by ievans** [comment]
This is done now, though we don’t print the percentage. Feel free to reopen!
