### ISSUE TITLE
non-ASCII character support in golang

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1140]
Can semgrep support special characters?
https://semgrep.live/WAvL

**Comment by DrewDennison** [comment]
yes and @mjambon I thought your unicode fix addressed this?

**Comment by mjambon** [comment]
Ah, it's because Go string literals use backticks or double quotes. The following example works: https://semgrep.live/9A5z

**Comment by dgryski** [comment]
Still broken for Unicode characters though:

https://semgrep.live/Abd4?version=develop

https://play.golang.org/p/r4YaC5waxdl

**Comment by DrewDennison** [comment]
yeah thanks @dgryski reopening

**Comment by aryx** [comment]
@mjambon can you generate ocaml-tree-sitter-lang/golang :)
I guess it's time for Go to do the switch too.

**Comment by DrewDennison** [comment]
ah we missed `rune` literal when reading https://golang.org/ref/spec#String_literals switching to https://github.com/tree-sitter/tree-sitter-go will fix this and other open go parse bugs

**Comment by mjambon** [comment]
@dgryski @ghbren oops, my mistake. I didn't know about rune literals. We'll work on a fix.
