### ISSUE TITLE
Adding support for PHP

### ISSUE THREAD

**Issue by TmmmmmR** [semgrep/semgrep#1143]
**Describe the solution you'd like**
We would love to use/run semgrep against PHP code.

**Comment by aryx** [comment]
Do you have example of rules you would like to write and examples of codebase you would like to process?
This can help us to test the support for PHP.

**Comment by rezen** [comment]
A good place for vulns to test against https://github.com/digininja/DVWA/tree/master/vulnerabilities


- SQLi https://github.com/digininja/DVWA/blob/master/vulnerabilities/sqli/source/low.php#L8
- Exec - https://github.com/digininja/DVWA/blob/master/vulnerabilities/exec/source/low.php#L10
- File Inclusion - https://github.com/digininja/DVWA/blob/master/vulnerabilities/fi/index.php#L36
  - I'm not sure how semgrep handles variables defined in other files

**Comment by aryx** [comment]
@clintgibler who keeps tracks of vulnerable-on-purpose repos

**Comment by rezen** [comment]
@aryx do you mean https://owasp.org/www-project-vulnerable-web-applications-directory/? @kingthorin

**Comment by aryx** [comment]
Should work now. You can start writing PHP rules.
The live editor should list soon PHP as one of the language options.
