### ISSUE TITLE
[HCL] constant propagation support for locals

### ISSUE THREAD

**Issue by alex** [semgrep/semgrep#1147]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to use the full power of sgrep with terraform (HCL) files. I was just plauged by regular grep not being able to find:

```
locals {
  data_science = "data-science"
}
resource "aws_s3_bucket" "athena_output_data_science" {
  bucket        = "prefix-${local.data_science}"
}
```
when searching with `grep "prefix-data-science"`, which `sgrep` would hopefully be able to accomplish

**Comment by ievans** [comment]
@alex thanks for this issue! FYI, we are in the midst of switching to tree-sitter as the basis for all parsers. Do you know of any tree-sitter grammars for HCL? I found https://github.com/awilkins/tree-sitter-terraform with a bit of googling, but I'm not sure if it is still maintained (perhaps @awilkins knows?)

**Comment by awilkins** [comment]
Sadly, I didn't get very far implementing it - I've stopped using Atom.

Would it make it simpler to convert the file into the JSON format of HCL first?

**Comment by adzuci** [comment]
I'm new to `semgrep` and `tree-sitter` grammars, but I was looking into what https://github.com/fugue/regula does with OPA policies and was curious if running semgrep rules on the json plan output might make sense in some situations.

**Comment by ievans** [comment]
@awilkins thanks for commenting!

cc @adzuci. Since semgrep now has support for JSON, I think running on the JSON representation of HCL files may make some sense. 

Here's an example with an IAM policy: https://semgrep.dev/lBr5

**Comment by aryx** [comment]
update: there is a new matching engine inside semgrep called spacegrep. This can be used to match terraform.
@minusworld and @mjambon added this new feature.

However this will not do the kind of constant propagation you rely on your example.
Still, spacegrep could help other queries.

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
related work: https://github.com/tfsec/tfsec

**Comment by clintgibler** [comment]
@mitchellh recently [created a grammar for HCL](https://github.com/mitchellh/tree-sitter-hcl): https://github.com/mitchellh/tree-sitter-hcl

> There is a HUGE corpus of real world examples by browsing the top modules in our registry. Modules follow an enforced Git structure so you can find examples in the “example” dir, sources in the root, etc. 

https://registry.terraform.io/browse/modules

[Example to find examples](https://twitter.com/mitchellh/status/1407442665654738945)

**Comment by mafrosis** [comment]
What would be necessary steps to implement/support a new tree-sitter grammar for semgrep? There's huge value for me in helping to get this issue over the line - I'll be happy to contribute

**Comment by emjin** [comment]
That would be amazing! To start, take a look at https://github.com/returntocorp/semgrep/blob/develop/doc/SEMGREP_CORE_CONTRIBUTING.md#adding-support-for-a-language, which gives an overview of what you need to do. Also, feel free to connect with us in the [community slack](https://r2c.dev/slack) or post in #dev-discussions whenever you have questions.

**Comment by MichaHoffmann** [comment]
Hey, i also wrote a HCL parser concurrently to @mitchellh :  https://github.com/MichaHoffmann/tree-sitter-hcl. It is currently used in https://github.com/nvim-treesitter/nvim-treesitter.

It can also handle template interpolations and heredoc templates ( not yet template directives, but i'm slowly working on it ). Is this of interest to anyone here?

**Comment by aryx** [comment]
Sure it is of interest to us. How does it compare to the one of mitchellh? Is is strictly better because it can parse more things more precisely?

**Comment by MichaHoffmann** [comment]
> Sure it is of interest to us. How does it compare to the one of mitchellh? Is is strictly better because it can parse more things more precisely?

Well 'strictly better' may be a little strong, but it can parse template interpolations correctly. There is still some stuff missing ( template directives ) but its slowly getting completed. I also employ fuzzing to ensure its stability and it is actively used in `neovim-treesitter`. I also crawled a corpus of ~1.5k HCL files from github and included them in the test suite to make sure that it does not fail on real world input.

**Comment by mitchellh** [comment]
Looks “strictly better” than mine to me! Which is great 😌 I didn’t set out to make mine super feature rich, I was only aiming for “good enough” so that my HCL files weren’t totally useless haha. I never did templating and skipped a few features so if you’re committed to reaching full feature coverage then that is awesome!

**Comment by aryx** [comment]
@MichaHoffmann we will then base semgrep for terraform on your tree-sitter-hcl. String interpolation is important for semgrep users. However we have one problem with your grammar with those lines:
```
// TODO
    template_directive: $ => choice(
      //$.template_for,
      //$.template_if,
    ),
```
This causes our OCaml code generation to generate errors because there is a choice with nothing in it.
Would you mind modify grammar.js and add some more explicit TODOs like
```
template_directive: $ => choice(
      '%{if TODO',
      '%{for TODO',
      //$.template_for,
      //$.template_if,
    ),
```
which at least will not crash our ocaml-tree-sitter-semgrep.

**Comment by aryx** [comment]
PR here: https://github.com/MichaHoffmann/tree-sitter-hcl/pull/7 @MichaHoffmann

**Comment by MichaHoffmann** [comment]
Hey @aryx

Thank you for the PR, i just merged,  generated the parser and released  https://github.com/MichaHoffmann/tree-sitter-hcl/releases/tag/v0.5.0.

**Comment by aryx** [comment]
Ok, there is now alpha support for HCL at least, so I'll rename the issue to just talk about what remains to be done: the constant propagation part of locals {}.
Maybe @IagoAbal can fix that.

**Comment by aryx** [comment]
:wave:

**Comment by IagoAbal** [comment]
Ideally we can tweak the translation to make things easier. Right now sections are translated as records. We could translate the `locals` section differently, as a block of assignments, and then constant propagation should work. The caveat would be that the order of the local definitions would matter, whereas using a record the order does not matter.
