### ISSUE TITLE
Parse TypeScript in Tree-Sitter

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1148]
Add TypeScript support to Semgrep, via tree-sitter.

Steps:

- [x] Tree-sitter grammar for TS
- [x] Fix tree-sitter grammar missing functionality
- [x] Fill out TypeScript tree-sitter CST -> pfff JavaScript AST boilerplate (after this we can match ts using js rules) -- expected 2020-09-04
- [x] Create testing framework for TypeScript
- [x] Make TSX work

Acceptance criteria:
- [x] Parse more than 95% of pure ts

-----------

### Downscoping
- No safe dereference operator

**Comment by aryx** [comment]
@mjambon you can reference this issue in your PR.

**Comment by dlukeomalley** [comment]
For those following along, this work is currently in progress! 💪

**Comment by aryx** [comment]
I think this works now.
