### ISSUE TITLE
Semgrep doesn't appear to match strings in parentheses

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1154]
**Describe the bug**
Python has that weird behavior where it will automatically concatenate strings separated across lines. When using parentheses, Semgrep appears not to match.

**To Reproduce**
This matches: https://semgrep.live/Ew6L?stepByStep=1
And when I add in parentheses, this does not match: https://semgrep.live/AbKL

**Comment by dlukeomalley** [comment]
@minusworld What's your take on the priority of this issue?

**Comment by minusworld** [comment]
@dlukeomalley Medium or Low -- I don't think it happens frequently.

**Comment by nbrahms** [comment]
It looks like this works in https://semgrep.live/AbKL?

**Comment by nbrahms** [comment]
> It looks like this works in https://semgrep.live/AbKL?

As of 0.12.0

**Comment by dlukeomalley** [comment]
Indeed it does appear to work! Closing.
