### ISSUE TITLE
Feature: Add in a top-level key 'extensions' that specifies file extensions to scan instead of languages.

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1155]
**Is your feature request related to a problem? Please describe.**
Since we have `pattern-regex`, I want to scan arbitrary files.

1) We can reach feature parity with regex scanners for languages we don't yet support by making it easy to tell Semgrep not to parse a language but simply to run a regex.
2) We can start scanning non-standard languages such as configuration files and HTML templates now.

**Describe the solution you'd like**
I would like to have a top-level key, `extensions`, or something similar, that will pick up all files with that extension.

Use cases:
1) Scan files using `pattern-regex` for languages we don't support yet, like C# or Rust.
2) Scan files that aren't even programming languages, like configuration files or HTML templates.

**Comment by ievans** [comment]
supportive, suggest `file-extensions` to make less ambiguous

**Comment by brendongo** [comment]
You can probably just use the existing paths key. https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#paths
```
rules:
  - id: eqeq-is-bad
    pattern: $X == $X
    paths:
      include:
        - "*.jinja2"
```

**Comment by brendongo** [comment]
And maybe adding `any` or `all` as a language that doesn't do any extension filtering?

**Comment by minusworld** [comment]
Sounds good to me! 👍

**Comment by dlukeomalley** [comment]
Is this a dup of #1099?

**Comment by nbrahms** [comment]
This seems like a good first issue

**Comment by Isaac0616** [comment]
Add another use case.
We have config files `xxx.avsc` which is also the json files that we would like to parse and apply json rules.

**Comment by dlukeomalley** [comment]
@Isaac0616 If a file is known to be of a specific type (ignoring its suffix), you can explicitly pass it to Semgrep and indicate that you want the rule run. I did this locally with a "dummy" pattern:

```
$ semgrep -e "..." -l "json" test.abc
```

You can also do this with patterns, see @mschwager's comments here: https://github.com/returntocorp/semgrep/issues/1093#issuecomment-647604210

**Comment by Isaac0616** [comment]
I see. It is good to know that it works when explicitly specifying files.
However, it would still be nice to have this feature implemented so that something like
```
    paths:
      include:
        - "*.avsc"
```
would easily work in the CI.
As @minusworld said, it is important for reaching feature parity with regex based tool.
In addition, I think not parsing a file also paves the road to the feature of file name (only) matching rules.
btw, I wonder have you considered the file name matching rule?

**Comment by minusworld** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/1584.
