### ISSUE TITLE
semgrep 0.12.0 is extremely slow compared to 0.10.1 when matching multiple rules in multiple files

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#1156]
**Performance issue**
For some reasons, probably due to individual matching of files in 0.12.0, it appears that semgrep is much slower than 0.10.1

```
$ semgrep --version
0.10.1
```

`$ time semgrep -f ~/Code/njsscan/njsscan/rules/semantic_grep/ ~/Downloads/dvna-master/`

```
real	0m21.668s
user	0m9.579s
sys	0m2.495s
```

```
$ semgrep --version
0.12.0
```
```
$ time semgrep -f ~/Code/njsscan/njsscan/rules/semantic_grep/ ~/Downloads/dvna-master/
running 73 rules...
```
```
real	6m33.271s
user	6m10.971s
sys	0m9.231s
```

Source Repo: https://github.com/appsecco/dvna
Rules: https://github.com/ajinabraham/njsscan/tree/master/njsscan/rules/semantic_grep

**Comment by brendongo** [comment]
Looks like in 0.10.1 semgrep fails to parse https://github.com/appsecco/dvna/blob/master/public/assets/jquery-3.2.1.min.js and reports a TimeoutError. Semgrep 0.12.0 fails to parse as well but fails to parse 73 times. When running semgrep with `--exclude '*.min.js'` the performance between 0.10.1 and 0.12.0 is actually comparable. Going to find a way to cache parsing errors like this so it doesn't repeat work

**Comment by brendongo** [comment]
Keeping this open until I verify fix works but fix should be out on next release.

**Comment by brendongo** [comment]
Verified fix. Timeouts are cached so we don't timeout per rule.

**Comment by ajinabraham** [comment]
@brendongo Is this available in the latest version published to pypi?

**Comment by ajinabraham** [comment]
Just so your comment in slack that it will be published tomorrow
