### ISSUE TITLE
JS `var $X =1` should match global variable declarations

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1157]
https://semgrep.live/8G5q fails to match but https://semgrep.live/L1e9 works.

**Comment by nbrahms** [comment]
@DrewDennison I actually don't think we should match global variable declarations with `var ...`, as `var` specifically indicates the local scope.

I think you want to match with https://semgrep.dev/l0ZE/?version=0.20.0.

Please close this out if this matches your use case.

**Comment by DrewDennison** [comment]
yep lgtm. Thanks!
