### ISSUE TITLE
Python ParseErrors (lambda)

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#1161]
**Describe the bug**
`lambda (x, y): x` is a valid Python 2 statement (invalid in Python 3).

**To Reproduce**
https://semgrep.live/zdZn

**Expected behavior**
No error.

**Comment by Isaac0616** [comment]
`lambda (x): x` is also valid in Python 2.

**Comment by ievans** [comment]
@Isaac0616 -- thanks for filing this; looks like a duplicate of https://github.com/returntocorp/semgrep/issues/994 -- will tag that as external-user and track there!
