### ISSUE TITLE
Python ParseErrors (whitespace at the last line)

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#1163]
**Describe the bug**
In theory, a whitespace only line at the last line would not trigger error.

**To Reproduce**
https://semgrep.live/2Zgr

**Expected behavior**
No error.

**Comment by ievans** [comment]
@Isaac0616 thanks for filing this! It looks to me like like it is a duplicate of https://github.com/returntocorp/semgrep/issues/312 -- I'll close this issue to consolidate, but it is still something we'd like to fix.
