### ISSUE TITLE
Support diff-aware scanning

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1166]
Refer to https://github.com/returntocorp/bento/blob/master/bento/target_file_manager.py

A `--compare-ref` or similar flag should be added which takes a `git` reference. Semgrep should then scan only files that changed since that reference (as a performance optimization), and report only issues that are not present in the given ref but are present now.

**Comment by brendongo** [comment]
With #nosem ignore do we want to bring over the run twice and only show the different results or is it enough to show results in modified files?

**Comment by underyx** [comment]
I think we still want to run twice to be able to port semgrep-action to use this. Also, otherwise, this would be just a performance improvement feature.

**Comment by underyx** [comment]
Take care not to port this bug from Bento: https://github.com/returntocorp/bento/issues/336

**Comment by dlukeomalley** [comment]
@brendongo Any additional context you can add here after chatting with Po-Ning and Brianna? I can get more customers for you if we need more data points!

**Comment by brendongo** [comment]
After discussions we found that while diff aware logic is useful in the CI workflow, knowing how to parse PRs and figure out the base branches, head, etc. is not something that semgrep needs to know how to do. https://github.com/returntocorp/semgrep-action already has some diff aware logic, we just need to do some work to rip bento out of the action

**Comment by dlukeomalley** [comment]
Closing in favor of Semgrep Action/agent related tickets! Thanks all.

**Comment by Sjord** [comment]
[move semgrep-action functionality into semgrep · Issue #451 · returntocorp/semgrep-action](https://github.com/returntocorp/semgrep-action/issues/451)
