### ISSUE TITLE
Support more registry shorthand in --config

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1180]
**Is your feature request related to a problem? Please describe.**

Primarily, the way packs are executed is unwieldy right now. We have to recommend running

```
semgrep --config "https://semgrep.live/p/gosec"
```

instead of

```
semgrep --config p/gosec
```

I don't like how:

* Users are much less likely to be able type the first command out without looking it up
* The command takes too much space than necessary, especially on the semgrep.live UI
* It's not communicated that semgrep.live has first-class integration with the CLI for better user experience

**Describe the solution you'd like**

I'd propose adopting the shorthand specified in https://github.com/returntocorp/semgrep/issues/1179

| Prefix               | Examples                              |
|--------------------|---------------------------------------|
| `p/` Pack  | `p/gosec`<br>`p/underyx:custom-pack`    |
| `r/` Registry query | `r/python.flask.security.rule-id`<br>~~`r/python.*.security`~~ (wildcard support will be a separate issue)<br>`r/python`<br>`r/python.acmecorp:acme-api.security` |
| `s/` Snippet          | `s/aRsT`<br>`s/underyx:rule-name`     |

**Comment by ievans** [comment]
Hey, we did this! Closing, cc @underyx
