### ISSUE TITLE
parse error for generics in Java

### ISSUE THREAD

**Issue by asadasivan** [semgrep/semgrep#1184]
https://semgrep.live/nJvr
**Issue**: Java parse error
**Description**:
I recently ran semgrep against some code in java related to one of our product and I encountered parsing error. The error is due to the usage of < > in java interface. Below is a sample code to reproduce the issue: 
```
public interface TestMapper extends Tester <com.test.TestItem, TestItem> {
   ..... 
}
```
The following rule id triggers the parsing error: id: formatted-sql-string

**Comment by dlukeomalley** [comment]
Thank you for filing this issue @asadasivan. @aryx @ievans Any thoughts on next steps or a fix for this issue?

**Comment by aryx** [comment]
Yes the parsing heuristics to parse generics in the Java parser is not smart enough to accept this case.
We could extend the heuristic, which could help parse this case but sometimes may introduce regression for other files (it's a heuristic, not an algorithm). The right fix is to switch to the tree-sitter-java parsing which is probably more reliable but that may take some times (maybe a month).

**Comment by dlukeomalley** [comment]
Thanks @aryx for the comments. @asadasivan Is this a hard blocker for you and your use of Semgrep? I want to choose the right timeline for a fix.

**Comment by asadasivan** [comment]
Based on my research, I see a lot of codebases that uses similar format
which causes the parser to fail for the entire project. Hence, it seems to
be a show stopper for us. What's the timeline look like?

--Arun

**Comment by dlukeomalley** [comment]
> which causes the parser to fail for the entire project

@asadasivan Can you share the command you're using to run Semgrep and its version (`$ semgrep --version`)? 
By default Semgrep should run on as many files as possible and output the following when parse errors are encountered:

```sh
Run with --verbose to see parse errors
Run with --strict to exit with non-zero exit code when errors exist
```

Are you getting 100% parse errors on projects?

**Comment by asadasivan** [comment]
I ran the following command: semgrep --config
~/Desktop/semgrep-rules/custom_ruleset <project-name>. I even ran with
verbose and that's when I found out that the error was caused due to char
"<". I need to check a couple of other projects to see if it follows a
similar format. For the project, I ran I would say around 90% contains
parse errors. I certainly understand that it will take time to fix. One
thing I need to check is to see how it handles java type casting EX:
1. public void feed(List<Animal> animals)
2. List<Animal> animals = new ArrayList<>();


--Arun

**Comment by asadasivan** [comment]
I checked and it looks like public void feed(List<Animal> animals) throws
parsing error. The current version of semgrep used is 0.12.0.

--Arun

**Comment by dlukeomalley** [comment]
@ievans @aryx After your Java discussion can you update us here on next steps?

@asadasivan What version of Java are you analyzing? We're currently deciding how to best support Java moving forward and whether we'll address these issues one-off or move to an alternative parser that better supports new Java features.

**Comment by ievans** [comment]
@asadasivan: I discussed this with @aryx and we think that we can get these issues resolved comprehensively fairly soon (by switching to the tree-sitter parser). Stay tuned.

**Comment by asadasivan** [comment]
Thanks for the update. Looking forward to it.

--Arun

**Comment by ievans** [comment]
cc @asadasivan : work is starting on the upgraded Java parser this week in https://github.com/returntocorp/semgrep/issues/1257 if you'd like to track!

**Comment by asadasivan** [comment]
Hello Isaac,

Thanks for the update. Looking forward to testing it out once the fix is
ready.

Thanks,
Arun

**Comment by aryx** [comment]
This should work now! Thx for the bug report. Switching to tree-sitter-java fixed the issue.

**Comment by dlukeomalley** [comment]
Using the develop docker image through semgrep.live I can confirm this code now parses: https://semgrep.live/nJvr?version=develop

Thanks @aryx !
