### ISSUE TITLE
Java: ParseError

### ISSUE THREAD

**Issue by saaspeter** [semgrep/semgrep#1189]
**Describe the bug**
I semgrep java project, got below error, the java project is based on JDK8

"errors": [
    {
      "data": {
        "check_id": "ParseError",
        "path": "***.java",
        "start": {
          "line": 57,
          "col": 41
        },
        "end": {
          "line": 57,
          "col": 42
        },
        "extra": {
          "message": "Syntax error",
          "line": "        Set<String> enabeledMapper = new<String> HashSet();"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 26,
          "col": 15
        },
        "end": {
          "line": 26,
          "col": 16
        },
        "extra": {
          "message": "Syntax error",
          "line": "\tprivate List<@NotNull TestPanelist> testlists;\r"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 36,
          "col": 18
        },
        "end": {
          "line": 36,
          "col": 19
        },
        "extra": {
          "message": "Syntax error",
          "line": "    private List<@NotNull String> test_admin;"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 70,
          "col": 18
        },
        "end": {
          "line": 70,
          "col": 19
        },
        "extra": {
          "message": "Syntax error",
          "line": "    private List<@NotNull String> events;"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 45,
          "col": 28
        },
        "end": {
          "line": 45,
          "col": 29
        },
        "extra": {
          "message": "Syntax error",
          "line": "    public <T> TestContacts(int aa, int bb, String cc, List<TestProfile> testprofiles, List<T> testusers) {"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 639,
          "col": 50
        },
        "end": {
          "line": 639,
          "col": 51
        },
        "extra": {
          "message": "Syntax error",
          "line": "    public void flushTestDataByIds (List < String > ids) {"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 36,
          "col": 108
        },
        "end": {
          "line": 36,
          "col": 109
        },
        "extra": {
          "message": "Syntax error",
          "line": "\tdefault <T> List<T> getCalendarEvents(Calendar calendar, CalendarResource calendarResource) {\r"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 23,
          "col": 23
        },
        "end": {
          "line": 23,
          "col": 24
        },
        "extra": {
          "message": "Syntax error",
          "line": "        ACCESSTOKEN(0){\r"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    },
    {
      "data": {
        "check_id": "ParseError",
        "path": "****.java",
        "start": {
          "line": 14,
          "col": 24
        },
        "end": {
          "line": 14,
          "col": 26
        },
        "extra": {
          "message": "Syntax error",
          "line": "    String featureIds()[] default {};"
        }
      },
      "message": "SemgrepCoreRuntimeErrors"
    }
  ]

**Environment**
JDK 8 project

So does semgrep fully support jdk8 gramma?  especially:  java annotated parameter and java generics

Thanks & Regards

**Comment by dlukeomalley** [comment]
Thanks for filing @saaspeter. Is it possible to provide a minimal repro via a [semgrep.live editor](https://semgrep.live/editor) snippet and pattern for us to debug?

**Comment by saaspeter** [comment]
hi @dlukeomalley 

below is the related bugs, each is a different gramma checking error.

https://github.com/returntocorp/semgrep/issues/1194
https://github.com/returntocorp/semgrep/issues/1195
https://github.com/returntocorp/semgrep/issues/1196
https://github.com/returntocorp/semgrep/issues/1197
https://github.com/returntocorp/semgrep/issues/1198

semgrep is a greater tool, your team did a very good tool, I like it, hope it can become better and better and more popular.

Thanks

**Comment by dlukeomalley** [comment]
Thank you for the tickets @saaspeter. I'll chat with the team today about when we can tackle these.

**Comment by ievans** [comment]
cc @saaspeter : work is starting on the upgraded Java parser this week in https://github.com/returntocorp/semgrep/issues/1257 if you'd like to track!

**Comment by saaspeter** [comment]
thank you, waiting for the new release  :)

**Comment by aryx** [comment]
This should work now.
