### ISSUE TITLE
Write CI documentation for Jenkins

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1190]
**Is your feature request related to a problem? Please describe.**

Our CI integration docs have many providers but are missing Jenkins.

**Describe the solution you'd like**

I think Jenkins might have a more complicated configuration than just committing a YAML file, and these docs would be more complex than others? Or maybe that changed in the past couple years.

**Comment by dlukeomalley** [comment]
@underyx Is this an external request and/or near term needed?

**Comment by underyx** [comment]
I assumed it was only cause it appears on r2c.dev

**Comment by dlukeomalley** [comment]
Good eye. Note that there is a distinction in what we support as part of the OSS project and what we spend time supporting for our commercial users. I'll follow-up with you in person to talk through the distinction and how to communicate that clearly on our websites and project.

**Comment by mschwager** [comment]
https://github.com/returntocorp/semgrep/blob/develop/docs/integrations.md#jenkins
