### ISSUE TITLE
run pre-commit hook without Docker

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1200]
cc @underyx 

Now that semgrep is pip installable, we should be able to run the pre-commit hook via a pip install rather than requiring docker.

Also the instructions semgrep.live are missing a `v` in front of the revision.

**Comment by mschwager** [comment]
One downside here is we won't be able to run `pre-commit` with the bleeding edge changes on `develop`. Perhaps we use Docker for `develop` and dogfood that internally, and offer the `pip` package externally as the default/paved road.

**Comment by brendongo** [comment]
Good point @mschwager do we care about the experience of running cutting edge develop as a pre-commit hook locally or just checking that it doesnt break anything? We can run another pre-commit-config in CI that includes running semgrep-develop docker image if that is the case.

**Comment by ievans** [comment]
@mschwager @brendongo tbh I'm not sure we care about testing that, can probably do the cheap thing for now

**Comment by ievans** [comment]
This was closed in https://github.com/returntocorp/semgrep/pull/1401
