### ISSUE TITLE
CI: cache opam dependencies

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1204]
**Is your feature request related to a problem? Please describe.**

CI is slower than it could be.

**Describe the solution you'd like**

We'd like to cache most opam packages that semgrep-core depends on. This includes dependencies of pfff, ocaml-tree-sitter, and semgrep-core. Once installed with opam, all the ocaml libraries and compilers reside under `~/.opam`. Caching this folder would save build time. It would be ideal if the cache (provided by Github Actions or something else) could be refreshed once a week or so, such that we don't end up with stale versions of packages after a while. @mjambon can help with the opam/ocaml side of things. @mschwager knows more about Github Actions.

**Describe alternatives you've considered**

The solutions that were considered are:
* Having a dockerfile for building a base image with the opam packages pre-installed, and uploading this to dockerhub. This wouldn't automatically refresh like a proper cache.
* Relying on Github Actions' caching features. This is what @mschwager will try.

**Comment by mjambon** [comment]
We currently build 3 ocaml projects separately (pfff, ocaml-tree-sitter, semgrep-core). Their dependencies are or can be installed with a command like `opam install --deps-only .`, where the last argument is the root folder, which contains a *.opam file that contains the dependencies.

`semgrep-core/semgrep.opam` contains external dependencies but also lists `pfff` as a dependency. This prevents us from running `opam install --deps-only` for semgrep-core before installing pfff. A simple way is to just extract the external dependencies we want to cache and installing them in a first step. e.g. semgrep.opam contains:

```
depends: [
  "dune"

  "ocamlfind"
  "num"
  "ocamlgraph"
  "json-wheel"
  "conf-perl"
  "yaml"
  "grain_dypgen"
  "uucp"
  "uutf"
  "menhir"
  "parmap"
  "dune-glob"
  "pfff"
]
```

We would have a preliminary build step that installs all dependencies except pfff:
```
opam update  # somewhat slow, fetches latest package info, like 'apt update'
opam install -y dune ocamlfind num ocamlgraph json-wheel conf-perl yaml grain_dypgen uucp uutf menhir parmap dune-glob
```

Duplicating the dependency list isn't great (especially when there are version constraints) but it's relatively simple. I don't know a better solution.

**Comment by mschwager** [comment]
Unassigning myself incase someone else has time to work on this before I do.

**Comment by brendongo** [comment]
Looks like we now use a docker image with most the dependencies installed and most builds/tests finish in 5 minutes or less. @mjambon is this good to close

**Comment by aryx** [comment]
Also pfff is now using dune so things should be easier.
