### ISSUE TITLE
Display what files semgrep will be invoked on

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1208]
Under --debug flag, it would be helpful to print the paths that semgrep is being invoked on, to build confidence that the tool has actually run over the targeted files.

**Comment by aryx** [comment]
you can do export SEMGREP_CORE_DEBUG=1 to display the files being processed.

**Comment by aryx** [comment]
This might be an easy way to start learning the python part of semgrep.
@brendongo or @mschwager can probably help if you need.

**Comment by ievans** [comment]
go away stale bot

**Comment by aryx** [comment]
with --debug we get the list of files being processed.
