### ISSUE TITLE
Make semgrep's "chdir" usage more resilient

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1215]
Semgrep's usage within Docker combined with our `chdir` call caused for a difficult to track down bug. The related fixes were:

- https://github.com/returntocorp/semgrep-rules/pull/696
- https://github.com/returntocorp/semgrep-app/pull/165

Along with https://github.com/returntocorp/semgrep/pull/1192 for the original change.

The issue was our Github Action calls `make test`: https://github.com/returntocorp/semgrep-rules-test-action-develop/blob/master/entrypoint.sh, which runs this `test` target: https://github.com/returntocorp/semgrep-rules/blob/develop/Makefile. This was failing on the 2nd validate call on the `c` directory.

The failure was due to the `chdir` call in `semgrep/config_resolver.py` when run in a Docker environment. Initially the `/src` directory doesn't exist because the volume hasn't been mounted, then on the first validate call it avoid the `chdir` because it doesn't exist. Next the version caching code creates the `/src` directory. Then the next validate call sees that that directory does exist and calls `chdir`. This moves the script from the correct location such that it can no longer find the rules.

We could confirm this behavior with the following:

```
/github/workspace # ls /src
ls: /src: No such file or directory
/github/workspace # semgrep --validate --config=./python .
Configuration is valid - found 119 valid configuration(s) and 0 configuration error(s).
/github/workspace # ls /src
/github/workspace # semgrep --validate --config=./c .
Configuration is invalid - found 0 valid configuration(s) and 1 configuration error(s).
unable to find a config; path `c` does not exist (since you are running in docker, you cannot specify arbitrary paths on the host; they must be mounted into the container)
Please fix the above errors and try again.
```

If possible, we should make this `chdir` call more resilient. I see a few options:

- Remove it all together, if possible (this may play poorly with rule ID rewriting)
- Un`chdir` somewhere later in the script. This feels potentially fragile, what if we error out or have an exception? What if we fail to `chdir` correctly? The plus side is this is fairly straightforward, but there may be gotchas.
- Others?

**Comment by DrewDennison** [comment]
I like the idea of removing the chdir and having the rule ID remove a base path from the config dir / cwd

**Comment by Sjord** [comment]
See also [#2123: Semgrep changing current directory causes unexpected file resolving behaviour](https://github.com/returntocorp/semgrep/issues/2123).

**Comment by ievans** [comment]
This commit got reverted, so the issue should be re-opened. See https://github.com/returntocorp/semgrep/pull/3732 for discussion

**Comment by Sjord** [comment]
@ievens That link doesn't contain a discussion about reverting the commit. See also #3125 and #3134.

I got bitten by this bug again today. I am running semgrep-action in a docker. If `/src` exists, semgrep will `chdir` to it, even though the source files are in the current directory.

This results in error messages like "File not found: somefile.py", even though "somefile.py" definitely exists in the current directory.

**Comment by ievans** [comment]
Thanks @Sjord. I added this to tech-debt label. The good news is, we plan to merge semgrep-action into Semgrep proper. cc @brendongo for consideration of this issue when that work begins.

**Comment by emjin** [comment]
cc @brendongo since that work has begun

**Comment by ievans** [comment]
@brendongo cc on this for the conversion / possible change of behavior in the semgrep action -> semgrep port

**Comment by aryx** [comment]
@spencerdrak not sure if this issue is still valid, but closing since it's very old.
