### ISSUE TITLE
Semgrep 0.14 only showing first parse error

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1221]
In Semgrep 0.14.0, it seems to only report the first parsing error. There are other files with parsing errors, and the parsing error changes across runs. Also, it seem that the parsing error now only shows the filename instead of the full path.
For my monorepo I can't tell which __init__.py has the parse error.

Running with `--verbose` does not show all parse errors.

**Comment by dlukeomalley** [comment]
Reported by @ghbren as well: https://github.com/returntocorp/semgrep/issues/1246#issue-655460703

**Comment by aryx** [comment]
Yep, got the problem also. semgrep-core returns 9 parse errors on a project
but semgrep just reports one. Even with -json.
