### ISSUE TITLE
[Java] Import prevent to use direct name

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1225]
Consider the following Java code:

```java
import java.security.MessageDigest;

class Hash {

    public final String algorithm = "MD5";

    public static void main(String[] args) {
        MessageDigest md = MessageDigest.getInstance(algorithm);
    }
}
```

We're attempting to use our Java `final` propagation to detect MD5 usage. The following pattern works:

```
$ semgrep -l java -e '$MD.getInstance("MD5");' test.java 
test.java
8:        MessageDigest md = MessageDigest.getInstance(algorithm);
```

But this pattern does not:

```
$ semgrep -l java -e 'MessageDigest.getInstance("MD5");' test.java
```

I believe this pattern will be more accurate because the call must come from the `MessageDigest` module, whereas the first pattern could be any module calling `getInstance`.

@aryx @mjambon any thoughts?

**Comment by aryx** [comment]
I agree it should match, but I don't think it is related to constant propagation as the title suggest says. I think it's a more
general problem with "qualifiers" that seems to not match here.

**Comment by aryx** [comment]
Works now that I've fixed the aliasing vs direct match.
See https://semgrep.dev/s/GRK2/
