### ISSUE TITLE
Support function return types in golang + java for local functions

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1227]
Support local functions such as `divide` in https://semgrep.live/DrewDennison:test-go-types

To make Semgrep types more useful, we need to support type signatures from imports (at least standard library imports) as seen in the example above given that we have `f, err := os.Open` and other common idioms

**Comment by disconnect3d** [comment]
Is this issue still valid? Go return types seems to work, although, there is a bug with them: https://semgrep.dev/s/disconnect3d:go-func-return-types-bug (shall we create another GitHub issue for it?)

I bet that `$RETTYPES` should match only functions with a single return type, similarly to what `($SOMEARG $SOMETYPE)` does.

**Comment by brendongo** [comment]
@disconnect3d Probably better to open a new github issue for that

Will look into if this ticket is closable.

**Comment by disconnect3d** [comment]
@brendongo moved to https://github.com/returntocorp/semgrep/issues/1757

**Comment by aryx** [comment]
Is this still an issue @DrewDennison ?
