### ISSUE TITLE
Parse error with valid Go code

### ISSUE THREAD

**Issue by dgryski** [semgrep/semgrep#1230]
The following Go code fails to parse:

```
package main

import (
	"fmt"
	"github.com/google/go-cmp/cmp"
)

func main() {

	var a map[string]map[string]uint64

	if want, have := map[string]map[string]uint64{
		"a": {"x": 1},
		"b": {"x": 1},
	}, a; !cmp.Equal(want, have) {
		fmt.Println(cmp.Diff(want, have))
	}

}
```

Running semgrep with one of my rules produces the following error:

```
running 1 rules...
warn: parse error
  --> parse-bug.go:16
16 | 		fmt.Println(cmp.Diff(want, have))
   |                                    ^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse parse-bug.go as go

Warnings exist. Run with `--strict` to turn warnings into errors.
```

**Comment by dlukeomalley** [comment]
Thanks for filing a ticket @dgryski. Queuing this up to discuss with @DrewDennison and @aryx tomorrow.

Confirmed on semgrep.live: https://semgrep.live/Re3E/

**Comment by nbrahms** [comment]
AFAICT, yacc is interpreting the first set of braces as the IF body, rather than the conditional statement. Solving this with an LL(1) parser is not super obvious here.

**Comment by aryx** [comment]
Yes, the Go Grammar is not an LALR(1) grammar (the one supported by Yacc), and so I have some parsing hacks to go around that in lang_go/parsing/parsing_hacks_go.ml. There are heuristics in this file to deal with those complex if condition
that contains braces. We need to extend those heuristics to handle the example of damian, or switch to tree-sitter for Go too.

**Comment by nbrahms** [comment]
@aryx What's a good way to get started on extending these heuristics?

**Comment by dgryski** [comment]
@nbrahms https://github.com/returntocorp/semgrep/issues/1140 seems to suggest switching to Go tree-sitter package, which I guess removes the need for heuristics and will probably solve all open Go parsing issues, including this one.

**Comment by nbrahms** [comment]
@dgryski I agree. Aside from blocking parsing bugs that crop up while that work is underway, it probably makes sense to punt issues like this 👌 .

**Comment by nbrahms** [comment]
@aryx Did the Go tree-sitter work land? It looks like the semgrep link here is still failing, even on develop.

**Comment by aryx** [comment]
nope, not yet. I was fixing ruby and Go matching bugs, and trying to fix the perf regressions of ajin.
Hopefully I can finish the Go tree-sitter this week or early next week.
