### ISSUE TITLE
Missing semgrep-files/semgrep-core during `pip install` with --no-binary

### ISSUE THREAD

**Issue by bored-engineer** [semgrep/semgrep#1245]
**Describe the bug**
At LinkedIn we import/rebuild packages into an internal artifact mirror before they can be used. 
When completing this process with semgrep (`0.12.0`) an error occurs when referencing files in semgrep-core:
```
Copying semgrep.egg-info to /<snip>/venv/lib/python3.7/site-packages/semgrep-0.12.0-py3.7.egg-info
running install_scripts
Installing semgrep script to /<snip>/venv/bin
writing list of installed files to '/tmp/pip-record-5kxp1g0t/install-record.txt'
error: can't copy '/tmp/pip-install-415o5olw/semgrep-files/semgrep-core': doesn't exist or not a regular file
```
The package does not build from source when `--no-binary :all:` option is used. It appears the `build_wheel` command references a path that does not exist.

**To Reproduce**
Our internal process can be roughly simulated as follows:
```bash
cd path/to/some/tmp/dir
python3.6 -m venv venv # using the lowest supported version of Python for this package
source ./venv/bin/activate
pip install --no-build-isolation --no-binary :all: wheel==0.31.1   # pip-18.1 and setuptools-40.x are already in this venv
pip install --no-build-isolation --no-binary :all: semgrep==0.12.0
...
error: can't copy '/tmp/pip-install-bsvk10ic/semgrep-files/semgrep-core': doesn't exist or not a regular file
...
```
Upgrading to the latest versions of setuptools, pip and wheels results in the same behavior:
```bash
pip install --no-build-isolation --no-binary :all: --upgrade setuptools
pip install --no-build-isolation --no-binary :all: --upgrade pip
pip install --no-build-isolation --no-binary :all: wheel
pip install --no-build-isolation --no-binary :all: semgrep==0.12.0
...
error: can't copy '/tmp/pip-install-muc4z84h/semgrep-files/semgrep-core': doesn't exist or not a regular file
...
```

**Expected behavior**
The `semgrep` package can be installed without using existing pre-built binary wheels.

**Comment by mschwager** [comment]
Hi @bored-engineer,

It looks like our `.whl` packages are working correctly, but our `.tar.gz` packages are not:

```
$ unzip -l semgrep-0.14.0-cp36.cp37.cp38.py36.py37.py38-none-manylinux1_x86_64.whl | grep semgrep-core || echo "Nothing"
 13612792  2020-07-08 04:40   semgrep-0.14.0.data/scripts/semgrep-core
```

```
$ tar --list -f semgrep-0.14.0.tar.gz | grep semgrep-core || echo "Nothing"
Nothing
```

Thanks for bringing this to our attention! We'll look into it and get back to you as soon as possible. In the mean time, you could use our [Docker runtime](https://github.com/returntocorp/semgrep#installation) if you'd like to continue testing out `semgrep` while we look into this.

**Comment by brendongo** [comment]
@bored-engineer semgrep-core is built using ocaml and we haven't included all that in the source dist on pypi yet. To get you unblocked though, it is possible to build semgrep from source. The following steps effectively reproduce how we craft the whls.

```
opam init
opam switch create ocaml-base-compiler.4.10.0
opam install ./pfff
cd semgrep-core
opam install --deps-only -y .
opam exec -- make all
cd ../semgrep
PRECOMPILED_LOCATION=../semgrep-core/_build/default/bin/Main.exe python3 setup.py bdist_wheel
ls dist/
```

**Comment by dlukeomalley** [comment]
@brendongo @bored-engineer With the removal of sdist from the pypi release are we able to make progress now?

@bored-engineer Up for jumping on r2c.dev/slack to debug or chat more synchronously? Excited to get you unblocked.
