### ISSUE TITLE
Semgrep does not print out all parser errors

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1246]
**Describe the bug**

If there are multiple files with parser errors, then semgrep only prints out parser error with one of the files.

**To Reproduce**

try running semgrep from a directory with 2 files that have invalid syntax, semgrep will only print out parser error with 1 file.

**Expected behavior**
print out all parser errors

**Screenshots**

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

local build using 0.14.0

**Comment by dlukeomalley** [comment]
Thank you filing @ghbren! Merging this with #1221. CC @brendongo
