### ISSUE TITLE
specify constraints on metavariables outside of patterns (e.x. non-equality)

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1253]
Right now we enforce that metavariables are equal, but there is no way to add more constraints on top of this to the metavar matching.

For instance, in many cases it would be helpful to specify
* that $X and $Y are non-equal
* constraint on the literal text of the metavariable (Somewhat related to #1217). 
* algebraic constraints on type

**Comment by clintgibler** [comment]
+1 this would be great.

I've wanted a number of times to be able to express:
* $X is a variable (that is, *not* a string, int, double, etc. primitive data).

**Comment by ievans** [comment]
@clintgibler #1217 is done! 

I'm going to close this particular issue as "not specific enough." I think we might have enough validation to build something for algebraic constraints on type, but we can open that as a separate issue.
