### ISSUE TITLE
Convert tree-sitter Java CST to generic AST

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1257]
The goal is to replace the existing Java parser with the one generated by tree-sitter via ocaml-tree-sitter. Depends on https://github.com/returntocorp/ocaml-tree-sitter/issues/66.

**Comment by aryx** [comment]
actually we just have to convert it to the Java AST in pfff; and from that we can just reuse
the java_to_generic.ml already in pfff.
