### ISSUE TITLE
Internally test ruby support, port semgrep examples from Python/Js to Ruby

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1269]
See the matrix.md file.
See also semgrep-core/tests/python/*.sgrep and what could be ported to ruby.
I've started porting some examples in semgrep-core/tests/ruby/ but we could do far more.

**Comment by aryx** [comment]
Maybe start porting Brakeman rules.

**Comment by aryx** [comment]
right now semgrep-rules/ruby is empty :) the only ruby tests are basic tests in semgrep-core/tests/ruby (but those are useful to test the core patterns possibilities).

**Comment by mschwager** [comment]
@aryx Is this done? See also https://github.com/returntocorp/enterprise/issues/272

**Comment by aryx** [comment]
the semgrep-core/tests/ruby/  is not bad now. I'll mark this as done.
