### ISSUE TITLE
Metavariables don't propagate across pattern-regex functionality

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#1273]
Metavariable information is not propagated across pattern-regex functionality. So in this example:
```
patterns:
  - pattern-inside: |
      var app = express();
      ...
      app.$METHODNAME($REQUESTPATH, ...);
  - pattern-regex: 'app.(all|post)\(.*'
```
(in live editor [here](https://semgrep.live/2Z95/)), `$METHODNAME` and `$REQUESTPATH` are not found. In cai, running collect with this rule results in `KeyError: 'metavars'`.

**Comment by aryx** [comment]
You want metavariable-regexp maybe?
