### ISSUE TITLE
Support string wildcards in various javascript imports

### ISSUE THREAD

**Issue by kncdev132** [semgrep/semgrep#1274]
## Problem
I want to be able to detect if a js import path contains a specific keyword.
Ex. if keyword = "my_target_str" and we have the import in our code:
`import foo from '../my_target_str/views/foo/bar';`
we'd want this to report an error.

## Potential Solution
Following up from my discussion with @ievans it sounds like we may be able to achieve this via a regex style pattern such as:
`- pattern: import $X from "=~/.*my_target_str.*/"`

**Comment by DrewDennison** [comment]
@KieranCairney thanks for filing the issue. I agree with Isaac's solution but I'm trying to gather data on what would intuitively match your mental model. Can you write out what you would ideally see?

For example my take on this would be:

```
pattern: import $X from $Y
condition:
  $Y: /.*my_target_str.*/
```

**Comment by kncdev132** [comment]
Hey @DrewDennison, that example is a totally reasonable way of implementing it to me.

**Comment by kncdev132** [comment]
To provide a bit more context, here is a pseudo example of the cases we'd like to cover: https://semgrep.live/LjyY/

We want to catch anyone importing a specific module in our code. However, we've realized a wildcard string may produce false positives if another library references the same name (see test case 18 in my example). Despite us not particularly caring about this false positive, others may require something more powerful such as regex to only match for relative paths or an absolute path that begins with the target string (in this case "bar").

For our use case, either the wildcard or regex solutions should both suffice.

**Comment by ievans** [comment]
Related-ish: https://github.com/returntocorp/semgrep/issues/285

**Comment by kncdev132** [comment]
Hey folks, we're curious what a loose timeline would be for feature support of this as we're trying to decide on what tool to use for a required task in our backlog, thanks!

**Comment by ievans** [comment]
@KieranCairney thanks for checking -- we're thinking it will ship in 0.17 in one week (we release every Tuesday). Would that work for you all?

**Comment by ievans** [comment]
Desired solution is https://github.com/returntocorp/semgrep/issues/1217 I think cc @brendongo @mschwager

**Comment by kncdev132** [comment]
Sounds great, looking forward to trying it out. Thanks @ievans!

**Comment by nbrahms** [comment]
@ievans I just tried https://semgrep.live/3Zle/?version=develop, but alas, we don't seem to be performing the matches on the filename correctly yet.

cc. @colleend , who I know already fixed this issue for similar AST nodes (arising from Go imports).

**Comment by nbrahms** [comment]
> @ievans I just tried https://semgrep.live/3Zle/?version=develop, but alas, we don't seem to be performing the matches on the filename correctly yet.
> 
> cc. @colleend , who I know already fixed this issue for similar AST nodes (arising from Go imports).

Color me wrong here. The following matches:
  https://semgrep.live/BjRx/?version=develop&stepByStep=1

However, I'm having trouble getting the metavariable regex to work:
  https://semgrep.live/Dk3d/?version=develop

cc. @mschwager for thoughts.

**Comment by mschwager** [comment]
> > @ievans I just tried https://semgrep.live/3Zle/?version=develop, but alas, we don't seem to be performing the matches on the filename correctly yet.
> > cc. @colleend , who I know already fixed this issue for similar AST nodes (arising from Go imports).
> 
> Color me wrong here. The following matches:
> https://semgrep.live/BjRx/?version=develop&stepByStep=1
> 
> However, I'm having trouble getting the metavariable regex to work:
> https://semgrep.live/Dk3d/?version=develop
> 
> cc. @mschwager for thoughts.

Currently `metavariable-regex` is only a [child operator](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#schema). Including a parent `patterns` looks like it fixes the issue: https://semgrep.live/0b3B/?version=develop

**Comment by nbrahms** [comment]
> > > @ievans I just tried https://semgrep.live/3Zle/?version=develop, but alas, we don't seem to be performing the matches on the filename correctly yet.
> > > cc. @colleend , who I know already fixed this issue for similar AST nodes (arising from Go imports).
> > 
> > 
> > Color me wrong here. The following matches:
> > https://semgrep.live/BjRx/?version=develop&stepByStep=1
> > However, I'm having trouble getting the metavariable regex to work:
> > https://semgrep.live/Dk3d/?version=develop
> > cc. @mschwager for thoughts.
> 
> Currently `metavariable-regex` is only a [child operator](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#schema). Including a parent `patterns` looks like it fixes the issue: https://semgrep.live/0b3B/?version=develop

Right on!

**Comment by nbrahms** [comment]
@KieranCairney I'm going to close this issue as it looks like we probably support your needs here.

We'll release this in 0.17, but please feel free to play with https://semgrep.live/0b3B/?version=develop in the meantime.

Also please do reopen this ticket if you run into problems.

Best,
Nathan

**Comment by mschwager** [comment]
Also, if you'd like to try out `metavariable-regex` locally before the next release you can follow these instructions: https://github.com/returntocorp/semgrep/issues/1217#issuecomment-663032218

**Comment by kncdev132** [comment]
Thanks all! I was able to test it out and seems to be what we're looking for. However, I'm curious about a particular false positive it seems like:
line 12 - https://semgrep.live/Wrzy/?version=develop
Demo of the same regex in metavariable working as expected: https://regex101.com/r/FONidm/1

**Comment by ievans** [comment]
@KieranCairney, actually two things going on:

1. because your top-level key is `patterns-either`, you are ORing the results of the metavariable-regex filter. You want a patterns-either at the top-level, and then two subkeys (`patterns`) which will and the `pattern` and `metavariable-regex`. This is super not intuitive and we're working on making it better.

So in fact in your example, it's currently matching anything -- the regex doesn't matter.

2. If you print out $Y in the message field, you'll see that it is matching the quotes -- so the full expression matched is `'../bar'`. Thus regex needs to take into account the starting `'`

Fixed example: https://semgrep.live/rx46

@mschwager @nbrahms this is a great example of how tricky this can be to debug; @KieranCairney we're definitely going to work on making this a better experience in the future.

**Comment by kncdev132** [comment]
Thanks for the clarifications Isaac, I was able to get a demo working now. Looking forward to 0.17!

**Comment by ievans** [comment]
@KieranCairney great! I realized I forgot to deeplink the `develop` version that has the unreleased changes. https://semgrep.live/rx46?version=develop :)
