### ISSUE TITLE
Semgrep autofix eats brackets []

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1285]
https://semgrep.live/r650/ Based on this example, this issue is still not really fixed for brackets.

![image](https://user-images.githubusercontent.com/1408472/87517856-70636400-c6ba-11ea-97ac-96089d902a36.png)

(Basically the brackets disappear upon being replaced, does some especially nasty stuff on JSON objects)

_Originally posted by @rtpg in https://github.com/returntocorp/semgrep/issues/841#issuecomment-658604192_

**Comment by rtpg** [comment]
I haven't landed a simple repro but I think I've seen commas disappear too, which makes me think that regex special symbols are getting chewed up in the autofix code.

**Comment by minusworld** [comment]
We have another autofix capability that uses regular expression replacement: https://github.com/returntocorp/semgrep/blob/develop/docs/experimental.md#autofix-using-regular-expression-replacement

This tends to be less magical than the regular `fix` key, but it works more-or-less as expected. Does that work in this contextX?

**Comment by dlukeomalley** [comment]
@minusworld Good suggestion. Assuming it is acceptable in this context, I think this is still a bug for us to track with `fix`.

**Comment by aryx** [comment]
Works better now. The brackets are correct.
Now there's issue with the hash and its commas, but we will need to switch to the generic
pretty-printer to solve this.
