### ISSUE TITLE
New option flag: When scanning an explicit file, enforce that the file extension matches the rule being checked.

### ISSUE THREAD

**Issue by fitbitkfoster** [semgrep/semgrep#1288]
**Is your feature request related to a problem? Please describe.**
I encountered parsing errors as semgrep was attempting to parse a non-python file as python.
If a file is explicitly passed, semgrep will attempt to parse it in the language specified in the config. If instead you use `semgrep .`, it will automatically only grab files with the extension associated to the language specified in the rule. 

**Describe the solution you'd like**
My feature request is that a flag can be specified so that scanning an explicit file performs validation that the file extension matches the language specified in the rule.

**Describe alternatives you've considered**
* scan the directory and not the file, but this would have a performance impact due to scanning more files than intended.
* check the file extension in my own code, and split out my config files based on language.

**Additional context**
`semgrep --config=foo ./my-python-script-but-no-py-extension should still work`, so adding this as a flag might suit both requirements.

**Comment by brendongo** [comment]
Semgrep will try to not parse files with known extensions (i.e. it wont try to parse a .js file as a python file) but it does not know what to do with files with an unknown/non-existent extension. 

Is there a reason you are explicitly passing in the non-python file?

**Comment by fitbitkfoster** [comment]
This was occurring on a `.h` file extension:
`{"timestamp": "2020-07-15T20:04:36.316077Z", "level": "WARNING", "line": 41, "path": "/app/fitbit/security/stitches/log/__init__.py", "message": "semgrep: Could not parse exercise_model.h as python"}`

We scan all of our newly changed files using semgrep, regardless of the extension.
Our config files are also not split based on the language they apply to (i.e. our config file contains rules that apply to various languages, not just python). 

We'd need to refactor our code to work around this to:
1. Only scan files matching supported extensions
2. Associate the file extension with the right configuration file (e.g. `.py` with a python specific config file). This means we might have the same rule in multiple config files if it applies to more than one language.

**Comment by brendongo** [comment]
Oh I see. A quick-fix while we think through this workflow would be potentially calling semgrep with `--exclude *.h` if there are just a limited set of file extensions in your codebase that runs into this issue.

Hmm does it make sense to count .h files as C files @aryx?

**Comment by aryx** [comment]
Yes .h should be considered C files
