### ISSUE TITLE
Improve error message when running `pip install semgrep --no-binary :all:`

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1295]
We currently package the semgrep-core binary in a wheel. Installing from a sdist works only if you bring your own semgrep-core. 

We should print some instructions on how to build or download semgrep-core instead of failing with `error: can't copy '/tmp/pip-install-415o5olw/semgrep-files/semgrep-core': doesn't exist or not a regular file` as mentioned in https://github.com/returntocorp/semgrep/issues/1245. Or investigate a way to get rid of the error altogether.

**Comment by javixeneize** [comment]
Hi

Has the new python been released? Im still having this problem

Thanks

**Comment by brendongo** [comment]
We havent fixed this ticket yet but if you are seeing this message it means you are trying to install semgrep on a system that is not currently supported (i.e. not manylinux or osx compatible)

**Comment by mschwager** [comment]
After https://github.com/returntocorp/semgrep/pull/2326 we now see the following:

```
$ python -m pip install semgrep --no-binary :all:
Collecting semgrep
  Downloading semgrep-0.39.1.tar.gz (74 kB)
    ...
      File "/tmp/pip-install-vkt0hu6s/semgrep_ac307aa38c6143848c4e6533cd4701e1/setup.py", line 64, in find_executable
        f"Could not find '{exec_name}' executable, tried '{env_name}' and system '{exec_name}'"
    Exception: Could not find 'semgrep-core' executable, tried 'SEMGREP_CORE_BIN' and system 'semgrep-core'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Is that sufficient @underyx?

**Comment by underyx** [comment]
Good enough for me!
