### ISSUE TITLE
Ruby Divide By Zero Parsing

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1298]
**Describe the bug**
Semgrep does not find any instances of divide by zero corresponding to the pattern $X / 0. Some examples that semgrep misses are 0/0, 1/0, etc.

**To Reproduce**
https://semgrep.live/gEl5/??version=develop

**Expected behavior**
Would expect that the pattern matches 0/0, 1/0, foo/0 in the semgrep live code.

**Comment by brendongo** [comment]
FYI probably want this link instead: https://semgrep.live/gEl5/?version=develop

From dumpling the AST it looks like the pattern is not including the 0 in the tree?

Part of Pattern for $X / 0 that refers to denominator
```
            "Arg": {
              "L": {
                "Int": [
                  "",
                  "()"
                ]
              }
```

Same part when parsing ruby code:
```
                                                "Arg": {
                                                  "L": {
                                                    "Int": [
                                                      "0",
                                                      "()"
                                                    ]
                                                  }
```

**Comment by brendongo** [comment]
Might be an easy fix @aryx @nbrahms?

**Comment by nbrahms** [comment]
cc. @mjambon
