### ISSUE TITLE
:= and = considered equivalent in golang

### ISSUE THREAD

**Issue by dgryski** [semgrep/semgrep#1300]
https://semgrep.live/pZKZ

The rule `if $A, $B := ... ; $B { ... }` shouldn't match the construct `if d, err = foo(); d { ... }`

This also happens with 0.15.0.

**Comment by dgryski** [comment]
There's a weird interplay with `:=` and `=` in the rule.  My guess is the current parser which transforms `if a, b := foo(); b { ... }` into `a, b := foo(); if b { ... }` has an issue with ... something?

**Comment by ievans** [comment]
cc @aryx for thoughts?

**Comment by aryx** [comment]
It's because go_to_generic.ml transform short variable declarations in regular assignments. := is converted into =. I thought
that would allow $X = $B to also match x := b, which users would want, but if that's not the case, if people do not want that "code equivalence" I can remove it.

**Comment by dgryski** [comment]
Notice in my example, `$B` is the second metavariable in the assignment but it's matching `d` which is the first variable in the assignment.

**Comment by dgryski** [comment]
As for equivalence, given that using `:=` instead of `=` (or vice versa) can be a source of bugs, it's probably a good to be explicit about and let the rule author decide in their case if they're equivalent or not.

**Comment by aryx** [comment]
This should work now on develop

**Comment by dgryski** [comment]
There's still the issue with the wrong metavariable being matched: https://semgrep.live/w8WY/?version=develop ($A vs $B in the if check)

**Comment by aryx** [comment]
It now works on develop!
