### ISSUE TITLE
Parse error on Java @interface annotation type declaration

### ISSUE THREAD

**Issue by zythosec** [semgrep/semgrep#1303]
**Describe the bug**
Java files sometimes have a multi-line comment header at the top of the file. Tools such as Eclipse, IntelliJ, etc. automatically add these when creating new Java files (often a Copyright Block).

Error below:
```bash
warn: parse error
  --> Type.java:1
1 | /***************************************************************************
  |
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse Type.java as java
```

**To Reproduce**
Create a Java file and place this block at line 1:
/***************************************************************************
Comment Here
 **************************************************************************/
Run semgrep

**Expected behavior**
No parse error

**Environment**
```bash
docker run --rm -v "${PWD}:/src" returntocorp/semgrep --verbose --config=https://semgrep.live/c/p/java
```

**Comment by dlukeomalley** [comment]
Thank you for filing @zythosec! @aryx Is this another one solved by your tree-sitter tree migration? 

CC @nbrahms @DrewDennison

**Comment by aryx** [comment]
This is very weird. I'm pretty sure our Java parser handle /* comments spread on multiple lines. It's used in every projects
and the java parser parses 99.9% of the popular github projects.

**Comment by ievans** [comment]
@aryx I'm pretty sure there is a regression in the error reporting on ranges and we are incorrectly reporting span positions. We had another javascript bug where it reported 1:1 but was definitely not there. @brendongo can you look into that?

@zythosec can you provide a full reproduction here or on https://semgrep.live/editor?

**Comment by zythosec** [comment]
@ievans I realized from another bug I reported that the error using Docker locally reports line 1 error even if the error is not on that line. I will work on getting you a reproduction on semgrep live of the actual error today.

**Comment by zythosec** [comment]
@ievans Here you go: https://semgrep.live/RGgE/ Let me know if you need any more information. Thanks!

**Comment by zythosec** [comment]
Also, I'm happy to change the title of this issue once it's diagnosed. 😸

**Comment by aryx** [comment]
Should work now. I've also changed the title of the issue. Thx for the bug report!

**Comment by ievans** [comment]
thanks @zythosec I'm going to file the parser reporting location as a separate issue!

**Comment by dlukeomalley** [comment]
@ievans Do you have a ticket we can reference or link to from here? Thanks for filing!
