### ISSUE TITLE
JavaScript Function Signature Destructuring Parse Error

### ISSUE THREAD

**Issue by zythosec** [semgrep/semgrep#1306]
**Describe the bug**
JavaScript function signature with deep destructuring fails to parse.

**To Reproduce**
https://semgrep.live/Gxe2/

**Expected behavior**
No parse error

**Environment**
semgrep.live and locally using docker:
`docker run --rm -v "${PWD}:/src" returntocorp/semgrep --verbose --config=https://semgrep.live/p/javascript`

**Comment by nbrahms** [comment]
Fixed in 0.16
