### ISSUE TITLE
semgrep ignores code to analyze is /src exists

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1308]
Ran into this incredible Heisenbug while packaging an application that uses semgrep. Semgrep was not running on my specified path because of this code:

```
    if SRC_DIRECTORY.exists():
        os.chdir(SRC_DIRECTORY)
```

Desired behavior: semgrep doesn't cd into /src unless some specific env flag is used

from https://github.com/returntocorp/semgrep/commit/41774067786783f28c6ff70c985ef21da73c7c3f but also earlier cc @DrewDennison @mschwager

**Comment by mschwager** [comment]
This may be a dupe of #1215

**Comment by ievans** [comment]
Indeed, let's discuss there
