### ISSUE TITLE
Being able to call semgrep from a C# program (C# library to interact with semgrep)

### ISSUE THREAD

**Issue by gfs** [semgrep/semgrep#1309]
**Is your feature request related to a problem? Please describe.**
This looks like an interesting project and I primarily develop in C#, particularly lots of pattern matching things in the security space, so I'd be interested in a C# library.

**Describe the solution you'd like**
A modern C# semgrep implementation.

**Describe alternatives you've considered**
I could call out to the command line but the overhead of a process call is pretty high.

**Comment by ievans** [comment]
Hey @gfs, thanks for filing an issue. We've had a number of non-Python implementers use the subprocess approach; since you can invoke semgrep with a config file that can have as many rules as you like, usually you can express everything in a single invocation. Would that change your view on the viability of alternatives, or are there some other constraints that you all have? (I.e., needing to make queries conditional)

**Comment by gfs** [comment]
For some more context Our DevSkim project is regex based CLI and IDE for Visual Studio so we can't guarantee the deploy environment will have python.

**Comment by aryx** [comment]
What guarantees do you have on the deploy environment? Can you use binaries? Is it Windows only or Linux/macOS must also be supported? I guess docker is too much overhead?

**Comment by brendongo** [comment]
@gfs our ubuntu-generic install script installs a self contained binary that doesn't need python. See https://github.com/returntocorp/semgrep/releases/download/v0.15.0/semgrep-v0.15.0-ubuntu-generic.sh

**Comment by gfs** [comment]
For CLI and library we have no guarantees about deployment environment other than that it can run .NET Core 3.1.

For the Extension we would know we are on windows but the engine itself is in in the library.

Docker would indeed be too much overhead and we can't guarantee the deployment has docker as anyone can install this.

-------- Original Message --------

**Comment by gfs** [comment]
@brendongo Thanks! I think this doesn't solve this problem for me, as the experience I really need is seamless to the end user- who can't be expected to do any more configuration than add a NuGet package, but that's a good reference to know.

**Comment by aryx** [comment]
The only solution i see then is porting the python part of semgrep to Ironpython (is it still a thing) and the ocaml part toF# (great language too) to solve your issue.

**Comment by gfs** [comment]
IronPython seems to still be being developed. They just released .net standard/core support a few months ago. 

https://ironpython.net/

**Comment by aryx** [comment]
I think the best solution for now is to run semgrep as an external program. You can use the docker image if that helps reduce the burden to install the semgrep binary.

**Comment by gfs** [comment]
Thanks Aryx,

That isn't a feasible solution for us right now, we are not aiming to change the actual user experience (require a user to have docker and configure it), the current install process is just to grab a NuGet, but I appreciate the workaround idea.
