### ISSUE TITLE
Parse error spans not reported correctly

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1314]
There is a regression in the error reporting on ranges and we are incorrectly reporting span positions. 

Example: https://semgrep.live/RGgE/ thanks @zythosec

**Comment by minusworld** [comment]
@ievans Can you verify whether this is still an issue? I cannot infer from the semgrep.live example what the issue is.

**Comment by ievans** [comment]
AFAICT it looks fine, closing
