### ISSUE TITLE
golang package declaration can't be used as pattern

### ISSUE THREAD

**Issue by denisa** [semgrep/semgrep#1315]
https://semgrep.live/pZNk

```
error: invalid pattern
  --> .sgrep.yml:4
4 |   - pattern-not: package hacknews
  |                  ^^^^^^^^^^^^^^^^
Pattern could not be parsed as a Golang semgrep pattern
```

ps
my goal is to enforce go package dependency.
For (a bad) example, if my project has the packages:
`internal/persistence`
`internal/business`
`internal/rest`

I want semgrep rules to enforce
`internal/persistence` depends on no other internal packages
`internal/business` might depends on `internal/persistence`
`internal/rest` might depends on `internal/business`

**Comment by ievans** [comment]
Thanks @denisa, this is definitely a bug we'd like to fix
