### ISSUE TITLE
Add support for constant propagation in C

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1317]
Pulling from #1316.

Test: `semgrep-core/tests/c/equivalence_constant_propagation.c`

```
const char* PASSWORD = "password";

int main(int argc, char *argv[]) {
    const char* inner_password = "password";

    //ERROR: match
    foo("password");
    //ERROR: match
    foo(PASSWORD);
    //ERROR: match
    foo(inner_password);
}
```

**Comment by ievans** [comment]
https://semgrep.dev/s/ievans:c-dataflow and https://semgrep.dev/s/eLKl are all working. @IagoAbal is semgrep-core/tests/c/equivalence_constant_propagation.c enabled as a test in the core? Closing this issue in favor of the super issue https://github.com/returntocorp/semgrep/issues/1645
