### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by aimichal** [semgrep/semgrep#1327]
Page 3 of https://semgrep.live/learn ("2a. The ellipsis operator") has a typo.

> Your pattern should look like this:
> 
> logging.info(get_user(...) + " logged in.")

That should not have a trailing period.

Copy/pasting this example doesn't work ("No matches"):

> <img width="1384" alt="image" src="https://user-images.githubusercontent.com/19393950/88216749-65588880-cc12-11ea-8385-53a47e129000.png">

But without the trailing `.` it works:

> <img width="1384" alt="image" src="https://user-images.githubusercontent.com/19393950/88216765-6be70000-cc12-11ea-9635-65f1266f7c15.png">

**Comment by ievans** [comment]
thanks for the bug report @aimichal ! @minusworld, want to take a look at fixing?

**Comment by aimichal** [comment]
The typo is still on https://semgrep.live/learn.

Can someone please re-open? (Or LMK where the code for the /learn site is, because I couldn't find it -- I can submit a PR too.)

**Comment by chmccreery** [comment]
Thanks for following up! Taking care of this now
