### ISSUE TITLE
Semgrep Extension for Visual Studio Code

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1329]
I'd like to have Semgrep scan my code as I write it in Visual Studio Code. I specifically want VS Code, but I've heard other users express interest in other editors (Sublime, Eclipse, IntelliJ, vim/emacs, etc.).

> Would also love to see some plugin support for editors.

> Are you considering a flake8 extension like bandit for easy adoption (in CI and in VS Code)?

**Describe the solution you'd like**
A Semgrep extension hosted in the VS Code Marketplace.

**Describe alternatives you've considered**
I've also considered running this as a pre-commit hook, which Semgrep already supports. I'd prefer to have the results appear as I develop, rather than at commit time though.

**Comment by ievans** [comment]
Alpha at https://github.com/returntocorp/semgrep-vscode

**Comment by underyx** [comment]
Happy to announce that the above project has been officially released at https://marketplace.visualstudio.com/items?itemName=semgrep.semgrep today!

Currently it supports showing Semgrep findings in-editor, and also adds a command that suggests patterns based on code you have selected in the editor.

Excited to hear feedback at https://github.com/returntocorp/semgrep-vscode/issues/new!
