### ISSUE TITLE
[Ruby alpha] simple x.y pattern not finding any results

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#1333]
**Describe the bug**
trying to match a simple `object.method` pattern and it's not finding anything

**To Reproduce**
https://semgrep.live/1QXQ/?version=develop

**Expected behavior**
all 3 occurrences of the pattern should be found

**Environment**
semgrep.live `develop`

**Comment by DrewDennison** [comment]
@dee-see thanks for the bug report. We should definitely match this case
