### ISSUE TITLE
Parse f-string self documenting expression in Python

### ISSUE THREAD

**Issue by paul-nameless** [semgrep/semgrep#1339]
**Describe the bug**
```
1 file(s) failed to parse: tg/models.py
ParseErrors:
--> Failed to parse tg/models.py:389 as python
        log.info(f"removing msg {msg_ids=}")
                                        ^
= note: If the code is correct, this could be a semgrep bug -- please help us fix this by filing an an issue at https://semgrep.dev
Run with --strict to exit with non-zero exit code when errors exist
```

**To Reproduce**
Run `semgrep --verbose --config=https://semgrep.live/c/p/python .` with string formatting `f"removing msg {msg_ids=}"`.

**Expected behavior**
not fail with parse error

**Screenshots**

**Environment**
local build

**Comment by ievans** [comment]
minimal reproduction on the live editor: https://semgrep.live/l48j/

thanks @paul-nameless for the report!

**Comment by brendongo** [comment]
For context: https://docs.python.org/3/whatsnew/3.8.html#f-strings-support-for-self-documenting-expressions-and-debugging
