### ISSUE TITLE
Move typed metavariables from experimental to official support

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1348]
We currently document [typed metavariables](https://github.com/returntocorp/semgrep/blob/develop/docs/experimental.md#typed-metavariables) under experimental features. If there's nothing major blocking its official support let's do it! To accomplish this I see a few things we have to do:

- Move the documentation from experimental to [Pattern Features](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#pattern-features-1)
- Ensure we have appropriate coverage in `semgrep-core/tests/` for all supported languages and ideally automatically analyze and include this information in our cheatsheet/test matrix generation
- Stretch goal: #1344 - since C is officially supported and a natural fit for typed metavariables it'd be great to include this as well
- Anything else?

cc @aryx @emjin

**Comment by aryx** [comment]
Yep, sounds like a good plan.
