### ISSUE TITLE
[Javascript] Parse error with deconstructed arrow function expression parameters

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#1350]
**Describe the bug**
Object deconstruction in the parameters of an arrow function seems to cause the parser some problems, see repro

**To Reproduce**
https://semgrep.live/kbjP

**Expected behavior**
No parse error

**Comment by aryx** [comment]
@nbrahms do you think you could fix that?
We can switch to tree-sitter-javascript, but we may still have to correctly "compile" those pattern to ast_js.ml.

**Comment by brendongo** [comment]
Fixed in 0.16.0: https://semgrep.live/kbjP?version=0.16.0
