### ISSUE TITLE
[Javascript] Parse error with nullish coalescing operator (??)

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#1351]
**Describe the bug**
The `??` operator doesn't seem to be supported, though I wonder if that's a bug or simply a matter of it being too recent?

**To Reproduce**
https://semgrep.live/xygL/

**Comment by dee-see** [comment]
Same with `a?.b` https://semgrep.live/O9ZL/

**Comment by aryx** [comment]
We could handle ?? by switching to the tree-sitter javascript parser (should not take too long),
because it's apparently handled at https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js 
but I don't see any grammar rule for "?." in it. Is it a very recent Javascript feature? What's the syntax and semantic?

**Comment by dee-see** [comment]
I saw it used here https://github.com/elastic/kibana/blob/master/src/plugins/discover/public/application/angular/discover.js#L821 but they might be using some sort of non-standard compiler because I can't find any documentation about it. In other languages it's usually called safe navigation or "elvis operator". Nevermind about that one!

`??` exists for real though https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator :)

**Comment by dee-see** [comment]
Seems like `?.` is supported by my browser's console though.

This didn't raise any exception

```javascript
x = null; console.log(x?.b);
```


Ah seems like it's a proposition here: https://github.com/tc39/proposal-optional-chaining

So no need to parse that just yet.

**Comment by aryx** [comment]
As soon as we switch also to tree-sitter for the javascript parser the ?? should work.

**Comment by aryx** [comment]
Yep, this works with develop docker image.
