### ISSUE TITLE
JavaScript NoTokenLocation Error on empty catch binding (catch () {})

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#1352]
**Describe the bug**
https://semgrep.live/gEz0/

**To Reproduce**
https://semgrep.live/gEz0/

**Expected behavior**

**Screenshots**

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
Obviously we should return an error on your example, but
what do you want your pattern which uses catch($ERR) to match code that does have anything in the catch 
with catch {}.
If you want it to match, what should contain $ERR then?

**Comment by ghbren** [comment]
I don't want the pattern to match code with stuff inside `catch`.  I'm trying to catch empty `catch` blocks.

> Obviously we should return an error on your example

Sorry if I'm missing something, but why would this be an error?  The pattern is valid and the js code is valid.

**Comment by aryx** [comment]
sorry, typo, "we should NOT return an error on your example".

**Comment by aryx** [comment]
This will work in the mean time: https://semgrep.live/ExAe/
I'll try to add try { ... } catch (...) { }
