### ISSUE TITLE
Performance Regression from https://github.com/returntocorp/semgrep/pull/1061

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1360]
**Describe the bug**
It looks like we introduced a 30% performance regression with this PR

**To Reproduce**

```
git clone git@github.com:ajinabraham/njsscan.git
cd njsscan
git checkout bc50a3159cf8feb1f2261a1237c3893a1a9c36fc
cd ..
git clone git@github.com:bkimminich/juice-shop.git
cd juice-shop
git checkout 928fbacff98c9a99e77d5de655459bea70caf44e
pip3 install semgrep==0.16.0
```

Make and install semgrep-core at bc55bea (this PR)
```
time semgrep --config njsscan/njsscan/rules/semantic_grep juice-shop/frontend
```
takes 133 seconds on my machine

Make and install semgrep-core at 3613b50 (commit right before this PR) takes 100 seconds on my machine

**Comment by aryx** [comment]
Too complicated to debug, happened a long time ago. I investigated a bit back in the day but could not find the issue.
I don't think it's high-prio, we can spend a better time by profiling what we have and changing core matching algorithm (especially for foo(); ...; bar(); type of patterns).
