### ISSUE TITLE
Semgrep on JuiceShop stalling on three.js

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1361]
**Describe the bug**
Running `time semgrep -f ~/Code/njsscan/njsscan/rules/semantic_grep/ ~/Downloads/juice-shop-master/` takes forever but running `time semgrep -f ~/Code/njsscan/njsscan/rules/semantic_grep/ ~/Downloads/juice-shop-master/ --exclude three.js` takes 90 seconds.

It looks like parsing step is only taking 0.5 seconds to parse three.js so this is stalling in the match step.

Rules: https://github.com/ajinabraham/njsscan/tree/master/njsscan/rules/semantic_grep
Source: https://github.com/bkimminich/juice-shop

**Expected behavior**
- If there are problematic files we should respect the semgrep-core timeout flag and report a timeout instead of hanging indefinitely.
- We should also be able to match three.js in a reasonable amount of time so maybe we have a bug in the matching code

**Environment**
Exists on 0.16.0

**Comment by brendongo** [comment]
From slack: @aryx is going to have semgrep-core respect the timeout flag in the matching step and return a timeout error as a stop gap while we look into the root cause

**Comment by aryx** [comment]
We can probably close this one. At least it does not stall anymore.

**Comment by DrewDennison** [comment]
@aryx see https://returntocorp.slack.com/archives/C6A1GN4P3/p1603390422139900 (this is a regression)

**Comment by mschwager** [comment]
Related #1981?

**Comment by DrewDennison** [comment]
Fixed by https://github.com/returntocorp/semgrep/pull/2045. @DrewDennison to test
