### ISSUE TITLE
SEMGREP_CORE_DEBUG=1 does not work anymore with semgrep

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1365]
as explained in CONTRIBUTING.md, one way to debug semgrep-core from semgrep is to run
export SEMGREP_CORE_DEBUG=1 and if you do:
pipenv run semgrep -f ../semgrep-core/tests/PERF/ajin.yaml ../semgrep-core/tests/PERF/three.js

will get some debugging output from semgrep-core. There is also SEMGREP_CORE_PROFILE.
However this does not work anymore. My guess is that semgrep now redirect the stdout and stderr of semgrep
but this is really annoying to debug things for me.

Can we get a special option or have -v let stderr message from semgrep-core to reach the terminal?

**Comment by aryx** [comment]
the pb seems to come from:
            core_run = sub_run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
commenting stderr=... get the previous behavior, but would be nice to have an option for that.

**Comment by brendongo** [comment]
With the PR above logs are visible when setting the ENV variable and invoking semgrep with --verbose
