### ISSUE TITLE
semgrep.live bug report: Valid C function doesn't parse

### ISSUE THREAD

**Issue by karthick-gururaj** [semgrep/semgrep#1366]
https://semgrep.live/gEDK

The following (valid) C function gives a compile error:

    int foo(char *str) {
    //    while (*str && (*str != ':')) -> works
        while (*str && *str != ':')
        {
            str++;
        }   
       return 0;
    }

Code is valid as per gcc.

**Comment by dlukeomalley** [comment]
Thank you @karthick-gururaj for filing this bug. We'll track it as part of our general C improvements. Is this blocking your workflow or Semgrep experiments?

**Comment by karthick-gururaj** [comment]
Thanks @dlukeomalley - no, not blocking.

**Comment by ievans** [comment]
Confirmed fixed in v.38, probably earlier actually
