### ISSUE TITLE
New -timeout and -max_memory semgrep CLI flags

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1368]
Those flags are available in semgrep-core but not currently surfaced in semgrep.

**Comment by mschwager** [comment]
@sabihb was interested in picking off some `semgrep` tasks - this would be a great introductory issue.

To flesh the task out a bit more: `semgrep` (the Python code) calls out to `semgrep-core` via `subprocess`. This includes passing relevant information to `semgrep-core` via CLI flags. This task will be to create new `semgrep` CLI flags and pass the relevant information to the `semgrep-core` CLI flags.

**Comment by aryx** [comment]
@brendongo actually implemented yesterday the --timeout
