### ISSUE TITLE
Fix Golang newline inconsistencies

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1370]
Originally noticed in this comment: https://github.com/returntocorp/semgrep/pull/1357#issuecomment-663603212

In Go a newline introduces hidden semicolons. This ends up creating inconsistencies when patterns do or do not include a newline at the end of the pattern. This is especially noticeable when using a file vs. a CLI flag as the pattern input since files tend to include newlines whereas CLI arguments do not. Let's make this behavior more consistent by fixing up these inconsistencies :+1:

**Comment by dlukeomalley** [comment]
@mschwager @nbrahms This might help first time rule writers for Go. Shall we queue it up for this sprint?

**Comment by mschwager** [comment]
> @mschwager @nbrahms This might help first time rule writers for Go. Shall we queue it up for this sprint?

Let's do it! I just added it :+1:
