### ISSUE TITLE
#define causes parse error

### ISSUE THREAD

**Issue by karthick-gururaj** [semgrep/semgrep#1377]
https://semgrep.live/Gx4z

The code snippet below doesn't parse:

    #define FOO
    int i = 0;

I reduced it to the snippet above from a much bigger file. This bug means `semgrep` can't run on any real-life C code base.

**Comment by mschwager** [comment]
Hi @karthick-gururaj,

I'd expect Semgrep to at least parse the above example, even if it can't derive semantic meaning from preprocessor statements yet. From my testing it looks like Semgrep correctly parses macros like `#define FOO 1`, but fails with `#define FOO`. We'll track this as a C parser bug on our end :+1:. Is this blocking Semgrep usage on your end?

Thanks again for bringing all these issues to our attention!

**Comment by karthick-gururaj** [comment]
@mschwager - thanks! Yes, this one is a blocker for me.

**Comment by ievans** [comment]
Also working as of v.38, probably fixed earlier. Checked at https://semgrep.dev/s/Gx4z
