### ISSUE TITLE
--test-ignore-todo doesn't work

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#1386]
**Describe the bug**
Semgrep in test mode reports errors on lines annotated with todos

**To Reproduce**
See
https://github.com/returntocorp/semgrep-rules/pull/746/checks?check_run_id=921258601

**Expected behavior**
Semgrep should not error in this case.

**Comment by mschwager** [comment]
Do we really need this behavior in Semgrep itself? Could we instead just comment out the ignored tests inline or move a file to e.g. `.TODO` instead of `.py`? It's less maintenance burden for us and less custom syntax for users to learn vs. using builtin language features they'll already know.

**Comment by nbrahms** [comment]
cf. https://github.com/returntocorp/semgrep-rules/pull/746. Not optimizing for the long term here, but right now we can't commit certain changes without breaking CI. Let's unblock ourselves on that first.

**Comment by aryx** [comment]
Does not sound like a program analysis issue. Removing from our board.

**Comment by mschwager** [comment]
@nbrahms is this task still relevant? Can you give reproduction steps inline here? On your Github Action link I'm seeing "The logs for this run have expired and are no longer available."

Now that our [rule testing is publicly documented](https://semgrep.dev/docs/writing-rules/testing-rules/) we should ensure this flag/functionality works as expected.

**Comment by mschwager** [comment]
This flag works in my testing:

```
$ python -m semgrep --test /tmp/todo/
running 1 rules...
ran 1 rules on 1 files: 2 findings
1 yaml files tested
check id scoring:
================================================================================
(TODO: 1) /tmp/todo/pdb.yaml
	✖ python-debugger-found                                        TP: 2 TN: 2 FP: 0 FN: 1
	test: /tmp/todo/pdb.py, expected lines: [2, 5, 8], reported lines: [2, 5]
================================================================================
final confusion matrix: TP: 2 TN: 2 FP: 0 FN: 1
================================================================================
```

```
$ python -m semgrep --test --test-ignore-todo /tmp/todo/
running 1 rules...
ran 1 rules on 1 files: 2 findings
1 yaml files tested
check id scoring:
================================================================================
(TODO: 1) /tmp/todo/pdb.yaml
	✔ python-debugger-found                                        TP: 2 TN: 1 FP: 0 FN: 0
================================================================================
final confusion matrix: TP: 2 TN: 1 FP: 0 FN: 0
================================================================================
```

Feel free to re-open if you see an issue.
