### ISSUE TITLE
Support for JUnit XML format as output

### ISSUE THREAD

**Issue by nightwatchcyber** [semgrep/semgrep#1388]
Would love to see an option to get output as JUnit XML, since many CI/CD tools support this out of the box. This can be done via this module:
https://github.com/kyrus/python-junit-xml

**Comment by dlukeomalley** [comment]
@nightwatchcyber Thanks for filing this feature request. Is there a specific CI/CD system you have in mind? I'm curious to dig into the workflow a little further and figure out what "good" looks like for delivering this kind of feature.

**Comment by nightwatchcyber** [comment]
The two systems I was thinking of is Circle-CI and Gitlab:
https://circleci.com/docs/2.0/collect-test-data/
https://docs.gitlab.com/ee/ci/junit_test_reports.html

In particular, Brakeman added JUnit support specifically because of Circle-CI:
https://github.com/presidentbeef/brakeman/pull/1453

**Comment by dlukeomalley** [comment]
Thank you for the links and supportive of adding this. Is it something you'd be willing to contribute with some guidance from one of the maintainers?

**Comment by nightwatchcyber** [comment]
I can take a look at that. I was thinking of doing this in a similar way existing SARIF reporting is implemented.

**Comment by dlukeomalley** [comment]
@brendongo @underyx Any recommended starting points or context to share with @nightwatchcyber?

**Comment by nightwatchcyber** [comment]
I have made a first stab at this here:
https://github.com/nightwatchcyber/semgrep

However, I am running into some weird issues with Tox. Maybe someone from the core team can help me?

**Comment by nbrahms** [comment]
👋 Hi @nightwatchcyber . Sure thing; I'll give updates on the PR itself.

**Comment by nbrahms** [comment]
Actually, can you start by making a PR against `returntocorp/semgrep`? It'll be easier to debug there :)

**Comment by nightwatchcyber** [comment]
Created:
https://github.com/returntocorp/semgrep/pull/1495

**Comment by mschwager** [comment]
Assigning this to @DrewDennison since he's assigned to the associated PR.

**Comment by minusworld** [comment]
Merged in https://github.com/returntocorp/semgrep/pull/1720. Released in Semgrep 0.25.0.
