### ISSUE TITLE
Semgrep returns ambiguous error when pattern key includes non-string YAML

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1394]
As mentioned in https://github.com/returntocorp/semgrep/issues/1337
this works https://semgrep.live/5PXl/?version=develop
but not this https://semgrep.live/Gxl1/?version=develop

Not sure why, an edge case of YAML syntax.
At least we should give a better error message. Right now it just says "Error" without any information.

**Comment by nbrahms** [comment]
It works with: https://semgrep.live/kWxK/?version=develop, or by putting the content in quotes.

Broadening this to improving error message.

**Comment by nbrahms** [comment]
Probably related to, and fixed by, https://github.com/returntocorp/semgrep-app/issues/307
