### ISSUE TITLE
Add Ruby repositories to QA testing

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1397]
In an effort to gain more confidence in our Ruby support we should include some Ruby repositories in our QA testing process. This will confirm our parsing support, Ruby rules in semgrep-rules, and prevent regressions.

Related Ruby efforts:

- https://github.com/returntocorp/enterprise/issues/251
- https://github.com/returntocorp/enterprise/issues/270
- https://github.com/returntocorp/enterprise/issues/272
- https://github.com/returntocorp/semgrep-rules/issues/726
- https://github.com/returntocorp/semgrep/issues/1269

**Comment by brendongo** [comment]
Repos used in QA testing are in https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/public_repos.py

https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/qa/test_public_repos.py will need to be modified to run ruby rules. Right now it only does python go and javascript

**Comment by minusworld** [comment]
We also have benchmarking for Ruby rules on `semgrep-rules`.

https://github.com/returntocorp/semgrep-rules/blob/develop/tests/performance/.test_public_repos.yaml

**Comment by mschwager** [comment]
Re-opening since we reverted this change due to failing tests: https://github.com/returntocorp/semgrep/runs/946554625
