### ISSUE TITLE
Remove tests from pypi pacakage

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1399]
It looks like python tests are being unnecessarily included in python package. We should remove them.

**Comment by underyx** [comment]
Not against this, but I'll note that this is not an obvious design decision and there's some disagreement on whether tests should be packaged: https://www.mail-archive.com/twisted-python@twistedmatrix.com/msg12242.html

**Comment by underyx** [comment]
Oh, actually, that thread was about where in the directory structure tests should go.

For packaging questions I normally defer to @hynek's judgement and practices. He happens to have a blog post on this: https://hynek.me/articles/testing-packaging/

The post does not seem to say anything about including test files in the package. However I just checked the latest release of `attrs`, and it seems like he included `tests/` in that package. I think we should keep including them as well.

**Comment by brendongo** [comment]
>If a guy called glyph tries to tell you that you should put your tests into your package: just keep walking, he’s wrooong!

Looks like they don't want tests in the package?

**Comment by hynek** [comment]
That’s about where you put your tests in your project hierarchy. Not whether or not you put it into an sdist. I don’t feel strongly about putting tests into wrists but people kept complaining so I add them.

**Comment by brendongo** [comment]
Good to know! If some people care about having tests in a package, might as well keep it. Closing.
