### ISSUE TITLE
JSON pattern matching bug

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#1404]
**Describe the bug**
The pattern `{"key1": $X}` will match the entire object instead of the part of `"key1"`.

**To Reproduce**
https://semgrep.live/d78Y/?version=develop

**Expected behavior**
Should match only the part of `"key1"`

**Comment by mschwager** [comment]
Hi @Isaac0616,

Thanks for bringing this to our attention. I'm still new to the idea of using Semgrep for JSON search, so I don't have a good feel for its JSON use-cases and the ergonomics of patterns yet. I took a look at the Python equivalent for `dict`s and it appears to have similar behavior, except that it requires a `...`: https://semgrep.live/D8kj/?version=develop. That is, it matches the whole `dict` object, not just the key.

That's not to say that your approach is wrong, I'm just wondering how we can best design the ergonomics of JSON search in Semgrep, and what the primary use-cases are. Could you provide a few examples of patterns you'd like to search for in JSON?

One I could imagine is searching a `package.json` for a React dependency with something like this:

`pattern: "dependencies": { ..., "react": ..., ...}`

In your situation above, is `$X` going to be re-used, or is a placeholder for _anything_? Would `...` work just as well?

**Comment by Isaac0616** [comment]
My specific use case is detecting modification of an attribute of a secret key.
For example,
```
{
    "SECRET_KEY1": {...},
    "SECRET_KEY2": {
        "create_date": ...,
        "bytes": ....,
        "distribution": [...],
        "gen": "manual",
    },
    "SECRET_KEY3": {...},
}
```
I want to know if someone modify the `"gen"` of the `"SECRET_KEY2"` to something else.
(`$X` in my example can be `...`.)
Because the pattern has to be a complete json, I have to specify something like `{"SECRET_KEY2": ...}` (with bracket).
I can understand why it match the entire object, but what I really want is a way to match the part of the key only.
Maybe something like `"SECRET_KEY2": ...`, but it is not currently a valid pattern.

My instinct for the rule is like
```
patterns:
    - pattern-inside: |
        "SECRET_KEY2": ...
    - pattern: |
        "gen": ...
```
I think make `{..., "key": ..., ...}` match the entire object and `{"key": ...}` match only the key also makes sense to me.

**Comment by mschwager** [comment]
Thanks for the use-cases, they're really helpful in formulating how to think about the ergonomics here. I see two ways to determine a good JSON interface here, 1.) come up with use-cases and make sure we can use patterns to find them, and 2.) look to patterns in other languages (e.g. Python) to frame how we think about the problem. With that, I'll use a mix of these below to come up with a game plan for JSON search. Let me know if the following looks reasonable to you.

**Use-case: searching for existence of a key or key/value in a file.**

```
pattern: "private": ...
```

Similar to:

```
pattern: variable_name = ...
```

Or:

```
pattern: "private": true
```

**Use-case: searching for a key/value in, or missing from, an object, or a value in a list.**

I'd imagine the pattern would look something like:

```
patterns:
    - pattern-inside: "dependencies": { ... }
    - pattern: "react": ...
```

Similar to:

```
patterns:
    - pattern-inside: |
        def getDependencies(...):
            ...
    - pattern: dependencies = ...
```

Or:

```
patterns:
    - pattern-inside: "dependencies": { ... }
    - pattern-not: "react": ...
```

Or: 

```
patterns:
    - pattern-inside: "roles": [ ... ]
    - pattern: "admin"
```

**Use-case: searching for an object that meets, or is missing, certain criteria.**

Specific object with a specific key/value.

```
patterns:
    - pattern-inside: {"isAdmin": true, ...}
    - pattern: "has2fa": false
```

Or, specific object missing a specific key:

```
patterns:
    - pattern-inside: {"isAdmin": true, ...}
    - pattern-not: "has2fa": ...
```

With this implementation we could search for your use-case with something like:

```
patterns:
    - pattern-inside: "SECRET_KEY2": { ... }
    - pattern: "gen": $GEN
    - metavariable-regex:
        metavariable: $GEN
        regex: '(?!"manual")'
```

Are there any other obvious use-cases I'm missing here? cc @aryx @mjambon

**Comment by brendongo** [comment]
For key/value in use case:

Would it make more sense to do something like 
```
pattern: "dependencies": {..., "react": ..., ...}
```
instead of a pattern-inside and pattern?

**Comment by mschwager** [comment]
> For key/value in use case:
> 
> Would it make more sense to do something like
> 
> ```
> pattern: "dependencies": {..., "react": ..., ...}
> ```
> 
> instead of a pattern-inside and pattern?

Yup, I think that's another way to specify it, similar to how `pattern-inside` and `pattern` can be interchangeable in certain situations in other languages. The reason I broke it out into multiple patterns with `pattern-inside` was to disambiguate the `pattern-not` case. I.e if we consider this case:

```
patterns:
    - pattern-inside: "dependencies": { ... }
    - pattern-not: "react": ...
```

We can't simply move that to:

```
pattern-not: "dependencies": {..., "react": ..., ...}
```

In this case would it mean that 1.) we didn't find a `dependencies` key, or 2.) we didn't find a `react` key underneath `dependencies`? I could imagine rule authors would want to split these two cases out.

In your example it should be fine to consider those patterns equivalent. I was just highlighting that we'll likely want to support both ways of specifying that general pattern :+1:

**Comment by aryx** [comment]
We could allow 'key: value' semgrep pattern, just like we currently accep full expression/statement/statements pattern; that way, we would just return the matched field.

**Comment by aryx** [comment]
an alternative would be to improve the editor code highlighter as suggested also by @lvh to highlight differently code really matched and code matched by "..." (explicit or implicit "..." here).

**Comment by mschwager** [comment]
Moving this from the customers board. Checked with @Isaac0616 and they are not blocked so removing it from the active sprint.

**Comment by mschwager** [comment]
After thinking about this a bit more, I think this comment (https://github.com/returntocorp/semgrep/issues/1404#issuecomment-667254293) mostly gets it right, except for one thing: the patterns should look more like valid JSON. E.g.

```
pattern: {"private": ...}
```

```
patterns:
    - pattern-inside: {"dependencies": { ... }}
    - pattern: {"react": ...}
```

```
patterns:
    - pattern-inside: {"roles": [ ... ]}
    - pattern: ["admin"]
```

```
patterns:
    - pattern-inside: {"isAdmin": true, ...}
    - pattern: {"has2fa": false}
```

This is a bit more verbose, but it makes patterns look more like the language itself, like our other languages.

We could probably follow YAML's lead here since JSON and YAML should be mostly interchangeable, and we now have a working YAML implementation. cc @emjin

**Comment by aryx** [comment]
You can now write a pattern like key1: $VALUE.

What is confusing maybe is that { key1: $VALUE} has implicit ellipsis, and we should remove that.

**Comment by Shusanta** [comment]
@aryx  can you show an example, trying this but its not working

**Comment by Shusanta** [comment]
this doesn't work when i do {[enum.field]: $VALUE}
