### ISSUE TITLE
Support Gitlab SAST artifact output

### ISSUE THREAD

**Issue by chgg-kboberg** [semgrep/semgrep#1409]
**Is your feature request related to a problem? Please describe.**
My employer is a Gitlab shop and a requirement for integration into our SAST pipeline is the ability to "speak Gitlab" and leverage e.g. in-line merge request vulnerability scan results.

**Describe the solution you'd like**
A semgrep flag that generates Gitlab-formatted JSON output: https://docs.gitlab.com/ee/user/application_security/sast/#reports-json-format

**Describe alternatives you've considered**
Go wrapper around semgrep leveraging the Gitlab reporting module for properly formatted output?  Probably more work than just implementing Gitlab object schema though.

**Comment by dee-see** [comment]
Related issue from the other side: Make GitLab support the SARIF output format (which semgrep supports, but isn't exclusive to semgrep) https://gitlab.com/gitlab-org/gitlab/-/issues/118496

**Comment by dlukeomalley** [comment]
This issue is spiritually related to #1388. Tagging here to link the two tickets for those who implement.

**Comment by dlukeomalley** [comment]
@chgg-kboberg - Given your Semgrep Action PR, are we good to close this issue?

**Comment by chgg-kboberg** [comment]
Yes, we can close this.
