### ISSUE TITLE
Change names of semgrep directories

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#1411]
Having `semgrep/semgrep/semgrep` can get confusing.

Idea discussed on slack:
> We could change the 2nd, or 3rd semgrep - it can definitely get confusing. We could move the 2nd to something like semgrep-py and/or move the 3rd under a src directory and use setup.py's package_dir functionality.

**Comment by underyx** [comment]
This blog post recommends nesting under `src/`: https://hynek.me/articles/testing-packaging/

**Comment by nbrahms** [comment]
Half-finished on https://github.com/returntocorp/semgrep/pull/1423, but CI is being a blocker here.

**Comment by nbrahms** [comment]
This was too high an effort bar, so killing this task for now.
