### ISSUE TITLE
Ruby pattern-not not removing matches

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1414]
**Describe the bug**
In Ruby, pattern-not does not actually remove a match. In the example, I have tested that the pattern-not matches the line that is commented #should not match, but it does not accurately remove the match. 

**To Reproduce**
https://semgrep.dev/colleend:create_with

**Comment by nbrahms** [comment]
It looks like the returned match range is missing a character; my suspicion is that the match ranges differ by this last character and hence are not equal.

**Comment by nbrahms** [comment]
Hmm, color me wrong here. It looks like our subtraction logic is just broken here for some reason:

![image](https://user-images.githubusercontent.com/2490631/89337480-d99e1d80-d64f-11ea-9565-53996e513378.png)

**Comment by colleend** [comment]
huh interesting, it does seem like subtraction is wrong in this case. It seems that subtraction works in other cases, though (like in this case: https://github.com/returntocorp/semgrep-rules/blob/develop/ruby/lang/security/bad-deserialization.yaml).

**Comment by colleend** [comment]
investigated this further, so the subtraction is working fine, but the call to _run_core_command in the python wrapper is actually returning an extra range match to 196-269.

**Comment by mschwager** [comment]
After talking with @colleend, it looks like this is likely the same issue as https://github.com/returntocorp/semgrep/issues/1006.

**Comment by colleend** [comment]
Yep, it seems like its the exact same problem:
[<PatternMatch id=.1 range=<Range start=50 end=96 vars={'$PARAMS': '69c3bd562924235d62bc3792745edea5', '$FUNC': 'dbe8ad76e3d6b7b5729b7caed5572032'}>>,
 <PatternMatch id=.1 range=<Range start=222 end=295 vars={'$PARAMS': '8d942a149bade9e4a6f9252f0073a3dc', '$FUNC': 'dbe8ad76e3d6b7b5729b7caed5572032'}>>,
 <PatternMatch id=.0 range=<Range start=222 end=295 vars={'$PARAMS': '69c3bd562924235d62bc3792745edea5', '$FUNC': 'dbe8ad76e3d6b7b5729b7caed5572032'}>>]

**Comment by colleend** [comment]
Talked to @nbrahms , changing one of the metavariable's name to PARAMA instead of PARAM results in correct behavior. We've decided to not change API for now, but want to propagate more debugging information about metavariable matching to the user (warn when there are two params of the same name, and range matching of metavars).

**Comment by nbrahms** [comment]
To summarize here, it looks like we got bit by our metavariable-matching API.

Per our documentation, this is the "expected" behavior (although perhaps not expected by us!): Metavariables in AND composition are enforced to be identical; in this case the two `$PARAM` variables referenced different AST nodes.

Suggestions I discussed with @colleend to address this:
A. Include metavariable nodes in debugging steps
B. Highlight metavariable nodes in matches
C. Add a warning banner to the pattern editor re. metavariable matching when metavariable names are reused
D. Rethink our metavariable matching API

IMO, A is a pretty obvious win. B and C have some utility, and are not terribly difficult to implement. D is probably a much longer term effort.

**Comment by nbrahms** [comment]
cc. @chmccreery @dan5382 for design thoughts

**Comment by nbrahms** [comment]
cf. #1470

**Comment by nbrahms** [comment]
I'm going to close this issue since the problem itself is resolved.

Let's create issues for the follow-up work that we want to perform.

**Comment by chmccreery** [comment]
I should probably know this, but how do you get the Step-by-step debugging enabled? I found it in the toolbar, but nothing on my screen changes. Also worth noting that I couldn't figure it out, so we may want to make this more discoverable too?

**Comment by mschwager** [comment]
> I should probably know this, but how do you get the Step-by-step debugging enabled?

My understanding is that this is the output underneath the cheatsheet: "Debugging step-by-step." Although I just tested it and it looks like this section under the cheatsheet is visible regardless of if the "Debugger" is enabled under Tools, so maybe I'm misunderstanding something.

Regardless, I agree that we should improve this, because I ran into the exact same issue/thought. I enabled the "Debugger", nothing in the UI changed, and I didn't know where I should be looking or if anything changed.

**Comment by chmccreery** [comment]
@mschwager and everyone else- what do you think about putting the debugger above the cheatsheet instead of below, still collapsed by default, but open-able either by clicking on it or by selecting it in the tools bar?

**Comment by mschwager** [comment]
> @mschwager and everyone else- what do you think about putting the debugger above the cheatsheet instead of below, still collapsed by default, but open-able either by clicking on it or by selecting it in the tools bar?

I would make it either collapsible XOR enabled in the tools bar. Having both feels unnecessary :+1:

I'd have a slight preference to a simple collapsible row if we expect external users to use this functionality to support their pattern writing, and a preference for hiding it in the tools bar if we expect the primary consumers to be internal.

**Comment by chmccreery** [comment]
Ok, I like this idea. Moving discussion to slack :)
