### ISSUE TITLE
Parse error when running taint analysis

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1425]
I've lightly modified the basic taint tests provided in `semgrep-core`.

Modified `semgrep-core/data/basic_tainting.yml`:

```yaml
rules:
  - id: classic
    mode: taint
    pattern-sources:
      - source(...)
      - source1(...)
    pattern-sinks:
      - sink(...)
      - sink1(...)
      - eval(...)
    pattern-sanitizers:
      - sanitize(...)
      - sanitize1(...)
    message: A user input source() went into a dangerous sink()
    languages: [python, javascript]
    severity: WARNING
```

Modified `semgrep-core/tests/TAINTING/tainting.py`:

```python
def foo():
    x = 'test string format {}'.format('foo')
    a = source1()
    if True:
        b = a
        b = sanitize1()
    else:
        b = a
    sink1(b)
```

It looks like we're specifically having parse troubles under taint mode:

```
$ python -m semgrep --config semgrep-core/data/basic_tainting.yml semgrep-core/tests/TAINTING/tainting.py
running 1 rules...
warn: parse error
  --> tainting.py:2
2 |     x = 'test string format {}'.format('foo')
  |         ^^^^^^^^^^^^^^^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse tainting.py as python

Warnings exist. Run with `--strict` to turn warnings into errors.
```

If I run a non-taint rule against that Python code there's no parse error. I double checked, the `format` line is valid Python code:

```
In [14]: x = 'test string format {}'.format('foo')                                                      
In [15]: x                                                                                              
Out[15]: 'test string format foo'
```

cc @aryx @mjambon @chmccreery

**Comment by mschwager** [comment]
Seeing similar errors without any `.format` calls:

```
$ python -m semgrep --config taint-test.yaml ~/r2c/sgrep-rules/python/django/security/injection/sql/sql-injection-using-raw.py 
running 1 rules...
warn: parse error
  --> sql-injection-using-raw.py:41
41 |   user_age = Person.objects.filter(user_name=user_name).first()
   |              ^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse sql-injection-using-raw.py as python

Warnings exist. Run with `--strict` to turn warnings into errors.
```

Using rule:

```yaml
rules:
- id: taint-id
  mode: taint
  pattern-sources:
    - request.$W.get(...)
    - request.$W(...)
    - request.$W[...]
    - request.$W
  pattern-sinks:
    - $MODEL.objects.raw(...)
  message: A user input source() went into a dangerous sink()
  languages: [python]
  severity: WARNING
```

I'm not sure that taint analysis is ready for primetime, as @aryx has been alluding to.

**Comment by mschwager** [comment]
Seeing similar parse errors for Javascript:

```
$ python -m semgrep --config semgrep-core/data/basic_tainting.yml semgrep-rules/javascript/express/security/express-phantom-injection.js
running 1 rules...
warn: parse error
  --> express-phantom-injection.js:7
7 |     const instance = await phantom.create();
  |                      ^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse express-phantom-injection.js as javascript

Warnings exist. Run with `--strict` to turn warnings into errors.
```

**Comment by nbrahms** [comment]
It's really weird that these are showing up as parse errors, as apparently `pfff` is able to parse the files just fine.

cc. @brendongo for thoughts on why the error is mislabeled.

**Comment by dkasak** [comment]
I'm getting

```
running 2 rules...
  0%|                                                                                                                                                   |0/2
unexpected non-json output while invoking semgrep-core:


An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
```

with the example rule from this issue, or really with any example I've been able to think of.

This is on semgrep v0.24.0.

**Comment by aryx** [comment]
@IagoAbal here is the task I mentioned during the standup. It's just lots of little things to fix 
in pfff/lang_generic/analyze/CFG_build.ml (look at the raise Todo),  and AST_to_IL.ml
(see the calls to todo()).

Let me know if you need more help. The main thing to understand is IL.ml, the linearized/normalized version of AST_generic.ml that is more convenient to work on from a static analysis perspective.

**Comment by IagoAbal** [comment]
OK I'll take a look (this may take some time).

**Comment by IagoAbal** [comment]
@mschwager these errors should be gone after PR returntocorp/pfff#341, I have tried your first example with semgrep@develop and it worked fine. Could you re-try your examples and let me know if you get any more errors? Note that we still don't have proper support for those constructs, and you will get warnings about that, but now the taint analysis will at least run and it can give you some alarms.

**Comment by mschwager** [comment]
Confirmed, no longer seeing these parse errors :tada:
