### ISSUE TITLE
Generics in Java Sources Causing Matching Issues

### ISSUE THREAD

**Issue by nnamon** [semgrep/semgrep#1439]
**Describe the bug**

The use of generics in a function signature appears to affect detection.

The following class is semgrepped against:

```java
public class Cls
{
	public UserData deserializeObject(InputStream receivedFile) throws IOException, ClassNotFoundException {
        // ruleid:object-deserialization
        ObjectInputStream in = new ObjectInputStream(receivedFile);
        return (UserData) in.readObject();
    }

	public <T extends UserData> T deserializeObjectStealth(InputStream receivedFile) throws IOException, ClassNotFoundException {
        // ruleid:object-deserialization
        ObjectInputStream in = new ObjectInputStream(receivedFile);
        return (UserData) in.readObject();
    }
}
```

With the pattern from the `find-sec-bugs` rules: `new ObjectInputStream(...);`

Only the deserialization instance in the function `deserializeObject` is matched but the one in `deserializeObjectStealth` is not.

**To Reproduce**

A snippet of the bug can be seen here: https://semgrep.dev/nnamon:generics_bug_report

**Expected behavior**

Lines `ObjectInputStream in = new ObjectInputStream(receivedFile);` in both `deserializeObject` and `deserializeObjectStealth` are matched.

**Screenshots**

N/A

**Environment**

Tested with version 0.17.0 from `brew install semgrep` and on semgrep.dev

**Comment by colleend** [comment]
Making the parser_java.mly change that fixes this issue leads to at least 3 more shift-reduce errors. @aryx do you have any suggestions?

**Comment by aryx** [comment]
For some reasons the body of the second method has no AST ...

**Comment by aryx** [comment]
ok there's a big ast_todo in parser_java.mly on the grammar rule for generic methods. That explains it :+1:

**Comment by colleend** [comment]
ah I see now! that does indeed explain it 👍
