### ISSUE TITLE
using semgrep pip package as a dependency

### ISSUE THREAD

**Issue by javixeneize** [semgrep/semgrep#1452]
Hi

Is there any documentation on how to use semgrep as a dependency in python? It is, which service you need to call to run the scan, etc...

As explained in the previous issue, im trying to build a Flask API that enables semgrep as a service, and i would like to call the service needed to run the scan

Thanks

**Comment by dlukeomalley** [comment]
@javixeneize Unfortunately we don't have formal documentation yet. The API is firming up so we’ll write documentation soon and in the meantime there are decent doc strings. @brendongo and I can help answer any questions.

For examples of how the package is used, see Ajin's use of Semgrep in libsast: 

https://github.com/ajinabraham/libsast/blob/3ed4428e505382476cd1d9a85ade640a89a2fa9f/libsast/core_sgrep/helpers.py#L32-L41

**Comment by E1200411** [comment]
basically i need to understand whats the method needed to make it work. At the moment in trying to call it via subprocess and its not great.
I have seen Ajin's code. This man is always involved in cool things, eh? MobSF, NodeJSScan... ;) Im checking his code and im not understanding how you need to send the list of targets.

The parameter sent is as follows:

target=[pt.as_posix() for pt in paths]

But, what is paths expected to be? a list of string? like ['mydir/path1', 'mydir/path2']? a path?

I have tried both sending a list of strings or the current path (pathlib.Path(__file__).parent.absolute()) but none of them are working

Thanks

**Comment by javixeneize** [comment]
basically i need to understand whats the method needed to make it work. At the moment in trying to call it via subprocess and its not great.
I have seen Ajin's code. This man is always involved in cool things, eh? MobSF, NodeJSScan... ;) Im checking his code and im not understanding how you need to send the list of targets.

The parameter sent is as follows:

target=[pt.as_posix() for pt in paths]

But, what is paths expected to be? a list of string? like ['mydir/path1', 'mydir/path2']? a path?

I have tried both sending a list of strings or the current path (pathlib.Path(file).parent.absolute()) but none of them are working

Thanks

**Comment by brendongo** [comment]
You will want to call this function: https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/semgrep_main.py#L251
and pass it in a path to the config file and a list of paths that you would pass when calling semgrep from the command line.

**Comment by javixeneize** [comment]
Thanks. This is the method im calling, but i dont know whats the expected format for the list of paths. Do you have an example you can share?

Thanks

**Comment by brendongo** [comment]
```
from semgrep.semgrep_main import invoke_semgrep
from pathlib import Path

config = Path("some_config.yaml")
targets = [Path(".")]

invoke_semgrep(config, targets)
```
should work

**Comment by javixeneize** [comment]
Thanks! Just one last thing, can you accept my LinkedIn connection please? I need to speak with you about something please. Thanks ;)

**Comment by dlukeomalley** [comment]
@javixeneize Done! We can also go back and forth via email: luke@r2c.dev

**Comment by javixeneize** [comment]
Hi @brendongo 

It doesnt work as expected.. I have this error when calling invoke

RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by javixeneize** [comment]
Fixed it... i need to call it from a main function
```
from semgrep.semgrep_main import invoke_semgrep
from pathlib import Path

config = Path("some_config.yaml")
targets = [Path(".")]

if __name__ == '__main__':
    invoke_semgrep(config, targets)
```

**Comment by javixeneize** [comment]
Last question, when i want to load an external config file, the syntax is 

semgrep --config "https://semgrep.dev/p/findsecbugs"


How would i need to do it calling invoke_semgrep directly? 
Im trying config = Path("https://semgrep.dev/p/findsecbugs"), but when getting inside the semgrep library, i am calling a service, resolve_config which has the following code:

    elif config_str in RULES_REGISTRY:
        config = download_config(RULES_REGISTRY[config_str])
    elif is_url(config_str):
        config = download_config(config_str)

RULES_REGISTRY is {'r2c': 'https://semgrep.live/c/p/r2c'}, so its not getting there, but it also returns that is_url(config_str) is false. 

This is_url method returns true or false based on this:

return all([result.scheme, result.netloc])

The parsing it does with that url is:

ParseResult(scheme='https', netloc='', path='/semgrep.dev/p/findsecbugs', params='', query='', fragment='')

So, it returns false and doesnt download those rules.

Is this a bug?

EDIT: I know what happens now. When sending it as a path, it removes the first '/', so i need to send it as a string.

Thanks

**Comment by brendongo** [comment]
Yes sending as a string will work for urls
