### ISSUE TITLE
warn: parse error(Javascript file) 

### ISSUE THREAD

**Issue by nuc13us** [semgrep/semgrep#1454]
There is some issue when trying to parse a valid Javascipt File 

```
➜  semgrep --config=https://semgrep.live/c/p/javascript . --autofix         
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
using config from https://semgrep.live/p/javascript. Visit https://semgrep.live/registry to see all public rules.
running 9 rules......
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|9/9
warn: parse error
  --> ErrorCorrectionModal.js:1
1 | import React from 'react';
  | 
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse ErrorCorrectionModal.js as javascript

no files modified.
Warnings exist. Run with `--strict` to turn warnings into errors.


```
Any possible way to ignore this kind errors and scan rest of the files.

**Comment by dlukeomalley** [comment]
@nuc13us My understanding is that the behavior of Semgrep already is to warn and continuing scanning the rest of the files unless `--strict` is used. Do you expect results in another file that are not being returned?

**Comment by nuc13us** [comment]
@dlukeomalley No, i don't think it is scanning rest of the files because when i try to remove that particular file(ErrorCorrectionModal.js) as per the above example and try to scan again it says parse issue in some other file.

**Comment by aryx** [comment]
which version are you using? There was a bug in previous semgrep version where we were just displaying the first error. @brendongo

**Comment by nuc13us** [comment]
I was using older version of semgrep(0.14.0). After using updated version issue is fixed.
Thanks a lot @aryx
