### ISSUE TITLE
Semgrep doesn't warn if yaml rules contain unexpected values e.g. due to missing whitespace

### ISSUE THREAD

**Issue by disconnect3d** [semgrep/semgrep#1460]
When we include a `-pattern-not:` instead of `- pattern-not:` as `rules[patterns]` key in the multi-pattern yaml semgrep rules, it will not be treated as a `pattern-not`.

The screenshots below show an example of that from the semgrep tutorial.

**Screenshots**
![image](https://user-images.githubusercontent.com/10009354/89531228-2f113080-d7f0-11ea-98cb-7f5c4a05dafe.png)

vs

![image](https://user-images.githubusercontent.com/10009354/89531285-43edc400-d7f0-11ea-8b8c-bb7ef1bd1332.png)

**What can we do**
This could be ignored, as that (most likely) comes from the yaml parser itself. However, semgrep could validate all the resulting yaml and warn if there is something unexpected?

**Comment by underyx** [comment]
Thinking we should replace our homegrown simple schema validation code with jsonschema.

**Comment by nbrahms** [comment]
Fixed in 0.21
