### ISSUE TITLE
Error out when multiple rules use the same rule 'id'

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1474]
Based on conversations in https://github.com/returntocorp/semgrep/pull/1302, I believe Semgrep should error out as early as possible when presented with multiple rules using the same rule `id`.

**Comment by dlukeomalley** [comment]
@mschwager If we move our naming to the proposal `<org>.<pack>:<rule>` do we think this is necessary? Is there value in multiple rules having the same name?

**Comment by mschwager** [comment]
> @mschwager If we move our naming to the proposal `<org>.<pack>:<rule>` do we think this is necessary?

Yes, I believe so. `<org>.<pack>:<rule>` can still run into multiple rules with the same identifier. If the same organization puts multiple rules with the same ID in the same pack, then there will be overlap. Regardless, this is fundamentally a Semgrep problem, not a semgrep.dev problem. Semgrep doesn't know about `org` or `pack`, it just sees a string identifier that really shouldn't be re-used.

> Is there value in multiple rules having the same name?

I would take a look at https://github.com/returntocorp/semgrep/pull/1302 - there's a lot of discussion around the advantages and disadvantages of the different approaches. The TL;DR from my perspective is that any minuscule benefit we get from allowing multiple rules with the same ID is far outweighed by this behavior breaking the expectations of any downstream application we have to deal with now or in the future (e.g. Gitlab, Github Actions, anything relying on JSON keys, anything relying on SARIF output, etc). As far as I can tell there isn't a single static analysis/linter tool that allows or performs rule ID re-use.

**Comment by aryx** [comment]
@nbrahms can json-schema specify those constraints?

**Comment by aryx** [comment]
@nbrahms bump

**Comment by mschwager** [comment]
Still a thing

**Comment by aryx** [comment]
With @emjin semgrep support for YAML we wrote a semgrep rule to check for those double ids (in the same rule though).
Then if the dir/filename is part of the full id, that should be enough.
