### ISSUE TITLE
Can't use `from` as a variable in JavaScript

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#1475]
**Describe the bug**
`from` is treated as a keyword, even when we're not in an import directive.

**To Reproduce**
https://staging.semgrep.dev/l4v6/

**Expected behavior**
Should be able to use `from` in expressions

Found while debugging #710

**Comment by aryx** [comment]
I don't even get a clear parse error message. I just got "semgrep error" without any information.

**Comment by nbrahms** [comment]
Looks to be fixed in 0.21
