### ISSUE TITLE
Return all matches on the same line with different metavariables.

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1478]
**Describe the bug**
Semgrep filters out duplicate matches that are on the same line when I would expect it to return multiple findings based on my query.

For example, if I do something like `$FUNC(..., $KWARG=$VALUE, ...)` in Python, I would expect it to return all variations of $FUNC, $KWARG, and $VALUE. However, Semgrep only returns one finding. See https://semgrep.dev/2Lxr/ for an example. I would expect this to return `name` and `description`, but I only get `description`.

I suspect that `semgrep-core` returns all these values but that it gets filtered out by https://github.com/returntocorp/semgrep/blob/1de14e0f028298c387d15f8ba495d016a6e14958/semgrep/semgrep/core_runner.py#L482-L495.

**Comment by aryx** [comment]
cc @DrewDennison

**Comment by nbrahms** [comment]
FWIW, I think this is because semgrep stops exhaustively matching after an AST node has at least one match, so it's just returning the first thing that matches (in this case, description).

This feels a bit more like a feature request to me?

**Comment by aryx** [comment]
I turned on the step-by-step debugger and semgrep-core returns all the matches, so this is the semgrep python wrapper that does the wrong thing here @nbrahms . It should return multiple matches given the metavariables have different values (and the message then is different each time).

**Comment by aryx** [comment]
keep
