### ISSUE TITLE
Print only filename / matching

### ISSUE THREAD

**Issue by xmo-odoo** [semgrep/semgrep#1482]
**Is your feature request related to a problem? Please describe.**
Currently when matching e.g. a class definition (filtered on a class attribute), semgrep will print the entire class body. I couldn't find any way to suppress this. This is annoying when using semgrep as a grep, in order to find interesting pieces of code interactively: knowing where the interesting matches are is useful, seeing the entirety of them less so.

**Describe the solution you'd like**
A way to provide an output format / pattern even using the CLI would be nice.

**Describe alternatives you've considered**
An option to suppress the printing of the match, or to suppress the display of whatever matched "wildcard" ellipsis (only display the lines which had "captured" matches) would also work fine I think.

**Comment by dlukeomalley** [comment]
Thanks for filing this @xmo-odoo. For the output, do you have an example of what you'd like the output to look like? Would you want to see just the filename (similar to grep's `-l` flag) or supplemental information line number and/or column for all matches within the file?

**Comment by xmo-odoo** [comment]
@dlukeomalley supplemental information would be great, but in fairness matching grep's output would probably be closer to people's expectations, especially if the option has the same name as grep's.

**Comment by dlukeomalley** [comment]
Do you want this to match grep's behavior of displaying the filename only or every match Semgrep finds, just without the code snippet?

**Comment by xmo-odoo** [comment]
Either would work, I'd go with what's simpler for you. My use case is finding "interesting" bits of code in a fairly large codebase, so just knowing that a given file is "interesting" is useful, knowning that there are specific locations in specific files is slightly more useful but not *necessary* if it's harder to implement.

**Comment by dlukeomalley** [comment]
Closing based on discussion in #2082
