### ISSUE TITLE
Use `Accept: text/yaml` header instead of User-Agent to get rules as YAML

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1483]
We currently have semgrep.dev return the YAML of rules when the User-Agent is `semgrep/*`. This is a very magical way to go about it, and is [difficult to explain](https://r2c-community.slack.com/archives/CK86BJ5DW/p1597138641145400?thread_ts=1597136269.145300&cid=CK86BJ5DW).

Instead of making assumptions based on client, we could just explicitly support returning YAML if the client asks for YAML with `Accept: text/yaml`.

- Then other clients could ask for YAML without masking their user-agent
- Semgrep CLI could request formats other than YAML
- And in general this feels like the right thing to do

**Comment by dgryski** [comment]
Is this sufficiently documented / stable that a standalone Go (or whatever) service could be used to serve rules standalone on-prem?

**Comment by underyx** [comment]
@dgryski sorry, no, we don't have a stable spec yet!

**Comment by dgryski** [comment]
A proxy could also handle the boiler plate for https://github.com/dgryski/semgrep-go/issues/10

**Comment by DrewDennison** [comment]
@dgryski this is solved. Please let me know if the header fails for you
