### ISSUE TITLE
Correctly parse multiple declarations with chained =

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#1491]
**Describe the solution you'd like**
When there is a line in the code like `a = b = 0`, I would like to be able to find the pattern `a = 0` in the code 

**Describe alternatives you've considered**
There doesn't seem to be another way to find this.

**Additional context**
[Here's](https://semgrep.dev/xxYy/) a short example.

**Comment by nbrahms** [comment]
Hi @sabihb... just to double-check, do you want to detect `a=0` (per your issue comment) or `b=0` (per your semgrep.dev link) in this code? 

It looks like the latter is just a bug in how we parse Python and straightforwardly solvable.

**Comment by sabrinabrogren** [comment]
My mistake, I meant the former (`a=0`). I didn't realize `b=0` also wasn't working. Is that a related issue or should I make a separate ticket?
