### ISSUE TITLE
Ruby pattern parsing of "def" throws error.

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1494]
**Describe the bug**
When searching for the pattern "def" in the code, semgrep throws an error.

**To Reproduce**
https://semgrep.dev/d7g0/

**Expected behavior**
Expect that there is no error and that ruby will match pattern "def".

**Comment by colleend** [comment]
Seems like this is the case for every language. @nbrahms do you think this is a necessary fix/feature?

**Comment by aryx** [comment]
Yes semgrep is not grep, so you need to provide full expression/statement/declaration as a pattern.
For example you can't search for 'if true' because this is not a valid statement. 'if true { ... }' is.
Same for definition, you need 'def $F(...): ... end'

**Comment by aryx** [comment]
We might provide a better error message though.
Actually I think that's in the editor, this problem is one of the suggested fix.
