### ISSUE TITLE
Takes more than 5 seconds to parse large js files

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1496]
**Describe the bug**
Many repos contain either minified vendored code (jquery.js), webpacked bundles, or just large javascript files (See https://github.com/signalapp/Signal-Desktop). Semgrep timeout when trying to parse these large files (matching a complex pattern will surely take even more time).

**Expected behavior**
Either semgrep skips these large files by default and mentions them to the user or we are able to quickly parse them.

Many of the tests in https://github.com/returntocorp/semgrep/blob/develop/semgrep/tests/public_repos.py#L264 fail because of this

**Comment by minusworld** [comment]
Similar to https://github.com/returntocorp/semgrep/issues/1125

**Comment by aryx** [comment]
I've removed the 5s timeout and Signal-desktop seems to parse at 100% correctly, so let's close that.
It's still slow, but it parse the 189 files in 40s
