### ISSUE TITLE
Fails to Parse Python2 file with mix of spaces and tabs and try

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1498]
**Describe the bug**
Semgrep is unable to parse python files with spaces and tabs used as indentation with a try/except

**To Reproduce**
Run semgrep on https://github.com/dropbox/DropboxBusinessScripts/blob/master/Sharing/reports/getCollaborationReport.py

**Expected behavior**
Semgrep should parse this correctly

**Comment by aryx** [comment]
Can you reduce to a simpler test case?
Also https://stackoverflow.com/questions/2034517/pythons-interpretation-of-tabs-and-spaces-to-indent#:~:text=It%20is%20best%20%E2%80%94%20necessary%20in,'use%202%20spaces'.)&text=Never%20mix%20tabs%20and%20spaces. says code should not mix tabs and spaces no?

**Comment by dlukeomalley** [comment]
@brendongo @aryx Were you able to reach consensus on whether this was a bug or invalid code?

**Comment by brendongo** [comment]
Python3 disallowed mixing but I think in Python2 it was fine

**Comment by aryx** [comment]
@brandonspark can you check whether this is still an issue now that we've switch to tree-sitter for Python?
I think there are maybe 20 Python issues we could close now :)

**Comment by brandonspark** [comment]
@aryx Indeed, we can parse the given example now.
