### ISSUE TITLE
Docker image fails to create cache directory in source path

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#1502]
**Describe the bug**
When running the docker image, the following error can appear:

```
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/semgrep/cli.py", line 319, in cli
    if not is_running_latest():
  File "/usr/local/lib/python3.7/site-packages/semgrep/version.py", line 102, in is_running_latest
    latest_version_str = _get_latest_version(version_cache_path)
  File "/usr/local/lib/python3.7/site-packages/semgrep/version.py", line 92, in _get_latest_version
    version_cache_path.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.7/pathlib.py", line 1268, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/src/.cache'
```

**To Reproduce**
https://github.com/returntocorp/semgrep/runs/977180789

**Expected behavior**
IMO, I do not expect the Docker image to modify the file contents of anything on the host environment's path.

Note that this blocks release of 0.19

**Comment by mschwager** [comment]
>  IMO, I do not expect the Docker image to modify the file contents of anything on the host environment's path.

We need to modify a file on the host's filesystem to support version check caching. The ephemeral nature of Docker containers means we have no good place to store information across runs (named volumes are an option, but this increases the complexity of the Docker command users will run). We can obviously disable version checking and/or version check caching in Docker environments, but I think the check is just as useful in the Docker environment as anywhere else. And, similar to any other environment, if you'd like to disable this functionality you can use `docker run returntocorp/semgrep --disable-version-check`.

Longer term, we'll likely want to recommend that if you're going to run the Docker container with the host's root user then you pass `-u $(id -u):$(id -g)`.
