### ISSUE TITLE
Allow choosing rules based on severity

### ISSUE THREAD

**Issue by reeyaa** [semgrep/semgrep#1509]
This would allow a user to choose which rule severity - `ERROR`, `WARNING` or `INFO` they would like to report findings on. For example, a user would only want to report findings that have severity `ERROR`. This could be added as an optional command line argument that can be configured by the user. By default, semgrep would use all the rules regardless of the severity rating.

Without this option, users would have to manually discard and re-add rules with a certain severity they do not/do want to report.

I imagine the outcome of this so be allowing a parameter called `severity` that could take different values such as:
`semgrep --severity ERROR ...` to only report bugs called by rules which have the severity `ERROR`

**Comment by minusworld** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/2133. Available in Semgrep 0.33.0
