### ISSUE TITLE
Unable to do case-insensitive matching in Java

### ISSUE THREAD

**Issue by nightwatchcyber** [semgrep/semgrep#1514]
**Describe the bug**
Unable to do case-insensitive matching in Java

**To Reproduce**
My test case here:
https://semgrep.dev/nightwatchcyber:regex_case_insensitive_match

Based on:
https://semgrep.dev/editor?registry=java.lang.security.audit.crypto.desede-is-deprecated

**Expected behavior**
Ability to match with case-sensitivity flags normally used in Java ("{?i}" or "/i")

**Screenshots**

**Environment**
Live Editor

**Comment by aryx** [comment]
Right now we use the OCaml regexp syntax, which is not great and does not support /i.
We could switch to the PCRE (the one used in Perl) which is better and support /i and /m.
@ievans what do you think?

**Comment by aryx** [comment]
I wonder if switching to another regexp engine would break many semgrep-rules @minusworld ?

**Comment by nbrahms** [comment]
Hi @nightwatchcyber ... 

Can you confirm that https://semgrep.dev/2L8L/ works for you? Over time we are working to deprecate the OCAML-based Regex syntax and replace it with `metavariable-regex`.

I'm going to close this issue out; please reopen it if you find yourself still blocked.

**Comment by nbrahms** [comment]
> I wonder if switching to another regexp engine would break many semgrep-rules @minusworld ?

@aryx cf. https://github.com/returntocorp/semgrep/issues/688

**Comment by nightwatchcyber** [comment]
@nbrahms your solution works for me, thank you!

**Comment by aryx** [comment]
Should work now! You can use /i for case-insensitive search.
