### ISSUE TITLE
Support matching arbitrary JSX attributes regardless of containing element

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1515]
**Is your feature request related to a problem? Please describe.**

There doesn't appear to be a way to specify a pattern like `<$ANY dangerous=...>`. We would like to match the following code where `dangerouslySetInnerHTML` is an HTML attribute set to a javascript object of the form `{__html: ...}`:

```
dangerouslySetInnerHTML = {{__html: ...}}
```

**Describe the solution you'd like**

Add a syntax for matching any JSX element. For example:
```
<$ELT attr={ $JS }>
```

**Describe alternatives you've considered**

Not sure. Just `attr={ $JS }` would be interpreted as a javascript assignment. We don't want that.

**Additional context**

Originally reported by Brianna Ren on r2c Community Slack channel. https://app.slack.com/client/TKABHD886/threads

**Comment by aryx** [comment]
Next time it would be nice if you could add a link to a semgrep.live example showing the issue.
