### ISSUE TITLE
Parse ?? operator in js

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1518]
**Describe the bug**
Semgrep unable to parse ?? operator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator

**To Reproduce**
 https://semgrep.dev/1L8G/

**Expected behavior**
See doc link above

**Comment by mjambon** [comment]
This will be supported when we switch to the tree-sitter implementation.

**Comment by nbrahms** [comment]
Duplicate of #1351

**Comment by aryx** [comment]
This works now! no more parse error.
