### ISSUE TITLE
Parse ?. in javascript

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1519]
**Describe the bug**
Semgrep unable to parse operator chaining in javascript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**To Reproduce**
https://semgrep.dev/9Rrr/

**Expected behavior**
See doc above

**Comment by mjambon** [comment]
linking to https://github.com/tree-sitter/tree-sitter-javascript/issues/134

**Comment by nbrahms** [comment]
@brendongo Is this JavaScript, Flow, or TypeScript? IIRC, `?.` is not supported in JavaScript.

**Comment by brendongo** [comment]
Out on Node14 apparently

**Comment by aryx** [comment]
I think it's a proposed extension not yet approved. @mjambon knows more.

**Comment by aryx** [comment]
This still does not work.

**Comment by aryx** [comment]
And it's not supported yet by the tree-sitter-javascript

**Comment by aryx** [comment]
So @mjambon we now need to update ocaml-tree-sitter-lang with the latest javascript grammar and hope we don't have too many modifications to do?

**Comment by mjambon** [comment]
The first task is to check that it works with typescript. Yesterday I saw failed tests in tree-sitter-typescript. Not sure if Max fixed them  on the javascript side or if it the typescript grammar extension has to be updated to reflect new rules in javascript. Also I'm working on semgrep for tsx support at the moment, let's try to minimize conflicts.

**Comment by aryx** [comment]
This works with ?develop
