### ISSUE TITLE
"??=" in parser.c is a C trigraph, should be escaped

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1523]
This is a tree-sitter code generation bug reported at https://github.com/tree-sitter/tree-sitter/issues/714

Severity: breaks the C# parser on some platforms (on which platform where did you see the error @nbrahms ?).

**Comment by ievans** [comment]
@mjambon https://github.com/tree-sitter/tree-sitter/issues/714 is closed, is this still relevant?

**Comment by nbrahms** [comment]
Closing as stale
