### ISSUE TITLE
Fix failing CI performance test

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#1537]
Let's not normalize failure. We should fix the failing test in https://github.com/returntocorp/semgrep/runs/1003359080 or remove it from our system.

**Comment by mschwager** [comment]
https://github.com/returntocorp/semgrep/pull/1536 should do the trick.

**Comment by mschwager** [comment]
Pending closing on successful build here: https://github.com/returntocorp/semgrep/commit/74044fed28aad7215c63469531724f5d702c70be

**Comment by mschwager** [comment]
It's green!
