### ISSUE TITLE
The pattern `"..." "..."` matches Python f-strings

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#1539]
**Describe the bug**

Sometimes we want to detect unintended implicit string concatenation, such as in [`python/lang/correctness/common-mistakes/string-concat-in-list`](https://github.com/returntocorp/semgrep-rules/blob/050d472c84adcf8fb8a4cee89e87345ad99f3453/python/lang/correctness/common-mistakes/string-concat-in-list.yaml).

This currently fires on `f"foo"` as well, which is not intended.

**To Reproduce**

https://semgrep.dev/7gY2/

**Expected behavior**

- Fire on `"a" "b"`
- Don't fire on `f"ab"`
- Fire on `f"a" f"b"`

**Environment**

0.20.0 on semgrep.dev

**Comment by nbrahms** [comment]
@underyx @aryx I'm wondering if this is actually a good use for Semgrep or not.

I'd expect Semgrep to treat `"a" "b"` and `"ab"` as semantically equivalent, and hence not distinguish between the two ever.

Is it reasonable to just declare this use case out-of-scope?

IMO this should just be handled by Black.

**Comment by nbrahms** [comment]
@aryx @underyx thoughts on closing as wont-fix?

**Comment by mjambon** [comment]
Closing this based on @nbrahms arguments above.

**Comment by underyx** [comment]
If we decide that Semgrep shouldn't detect this, please remove the referenced rule: https://github.com/returntocorp/semgrep-rules/blob/develop/python/lang/correctness/common-mistakes/string-concat-in-list.yaml
