### ISSUE TITLE
[Python] Rule analysis does not keep track of function name as metavariable across patterns

### ISSUE THREAD

**Issue by TrustMeIm0xDolphin** [semgrep/semgrep#1540]
**Describe the bug**
Semgrep does not keep track of function name as metavariable across patterns

**To Reproduce**
Using the following python file as an example:

```
def unsafe(request):
    code = request.POST.get('code')
    print("something")
    do_eval(code)

def do_eval(code):
    eval(code)
```
And the following YAML rule:

```
rules:
- id: user-eval
  patterns:
    - pattern: |
        $V = request.$W.get(...)
        ...
        $F($V)
    - pattern: |
        def $F(..., $V, ...):
          ...
          eval($V)
```

This combination returns no results

**Expected behavior**
Expected semgrep to identify the pattern

**Environment**
Happens on `semgrep.dev` and using semgrep on ubuntu (installed via pip)

**Comment by minusworld** [comment]
Hey @Emi1305, Semgrep doesn't support this example just yet.

`- pattern` clauses that are under `patterns` are implicitly AND'ed together. This means that the pattern matches when both of these patterns are met in the same range. They don't match if they're in the same file but in different locations.

```
$V = request.$W.get(...)
...
$F($V)
```

```
def $F(..., $V, ...):
    ...
    eval($V)
```


[Here's an example](https://github.com/returntocorp/semgrep-experiments/blob/master/precise-xss-flask-experiment/xss_match/try_xss_match.py) of doing something similar to what you're trying to do. We are considering mainlining the ability to "chain" Semgrep rules together, but for now you'll have to use something like a script to glue the results together.

lmk if you have any questions!
