### ISSUE TITLE
Python f-string detected as implicit string concatenation

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1544]
This was initially found as a false positive for this rule: https://github.com/returntocorp/semgrep-rules/blob/develop/python/lang/correctness/common-mistakes/string-concat-in-list.yaml. The rule looks for this pattern: `'["..." "...", ...]'`.

We can see that there isn't a false positive with regular string literals:

```
$ cat test.py 
l = ["foo"]
```

```
$ python -m semgrep --lang python --pattern '["..." "...", ...]' test.py
```

However, when we use an f-string we get a false positive:

```
$ cat test.py 
foo = "foo"
l = [f"{foo}"]
```

```
$ python -m semgrep --lang python --pattern '["..." "...", ...]' test.py 
2:l = [f"{foo}"]
```

Note that this correctly catches the f-string implied concatenation:

```
$ cat test.py 
foo = "foo"
l = [f"{foo}" "bar"]
```

```
$ python -m semgrep --lang python --pattern '["..." "...", ...]' test.py 
2:l = [f"{foo}" "bar"]
```

We should fix the 2nd case where an f-string is detected as an implicit string concatenation.

**Comment by underyx** [comment]
Is this a duplicate of https://github.com/returntocorp/semgrep/issues/1539?

**Comment by mschwager** [comment]
Yup, you're too quick!
