### ISSUE TITLE
Report basic statistics when run with no flags

### ISSUE THREAD

**Issue by disconnect3d** [semgrep/semgrep#1562]
It would be nice if Semgrep reported a number of INFO/LOW/WARN/ERROR findings when its simply run with `semgrep [-f <config>]`, probably as the last line it prints out.

It seems some statistics are displayed when `--json` is invoked thx to https://github.com/returntocorp/semgrep/pull/302, but that's not very convenient.

The proposed solution would make it more convenient to develop rules based on big codebases.

**Comment by ievans** [comment]
Other suggestions I've heard for the default output:

* the # of files, # of bytes, or # of lines of code processed. This can be useful if you run and think that you're scanning a lot of code, but it's actually mostly under a `.gitignore`.

**Comment by ievans** [comment]
@disconnect3d can you share more about your reasoning for this? I'm trying to decide whether to put it in the default output or behind a flag like `--verbose`

**Comment by disconnect3d** [comment]
@ievans Sure! I sometimes develop/adjust rules on big codebases and I want to be certain that a given change to reduce false positives did not exclude any true positives. Same for the opposite: if I change a rule to be more general, I want to know right away if I hit more results.

**Comment by ievans** [comment]
@disconnect3d for that, is it sufficient to just report # of findings, or is the INFO/WARN/ERROR count meaningful to you?

**Comment by disconnect3d** [comment]
The `# of findings` would be sufficient for my needs, though I bet the `INFO/WARN/ERROR` would be (more) interesting for running Semgrep on CI/CD in order to e.g. fail on errors but also display info/warn findings?

**Comment by ievans** [comment]
Closed in #1732, cc @underyx for the suggestion about putting this into semgrep-action (the CI integration!)
