### ISSUE TITLE
"Package" in go not working with ellipses.

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1569]
**Describe the bug**
"package" parses. 

However, adding an ellipses such as the case in:
https://semgrep.dev/Nxwy/
does not work.

**Comment by colleend** [comment]
hmm @aryx is there a way to tell whether this parser_error comes from parser_go.mly or go_to_generic.ml?

**Comment by aryx** [comment]
The error (and backtrace) should be different. You can try pfff -lang go -dump_pattern /path/to/gofiles.sgrep 
to dump pattern files.
If it's not a pattern, you can use -parse_go which will not call go_to_generic, or -dump_go which will just dump the Go AST. To exercise also go_to_generic you can use -dump_ast which will dump the generic AST.
