### ISSUE TITLE
Ruby Squiggly Heredoc Weirdness

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1580]
**Describe the bug**
Semgrep is having trouble parsing squiggly heredoc with disabled interpolation

**To Reproduce**
https://semgrep.dev/3e8K/ doesnt work. 
Removing ~ to make it a regular heredoc results in a different error: https://semgrep.dev/Qw6Z/
Removing the interpolation disabling on line 4 https://semgrep.dev/4Bl5/?version=develop results in parsing correctly

fwiw I'm not sure if nested interpolation canceling is even valid ruby.

Real life code: https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/query_methods.rb#L46

**Comment by aryx** [comment]
Some examples now work, but the first semgreplive link still does not parse correctly.

**Comment by aryx** [comment]
We could probably report this bug on the tree-sitter-ruby repo for this one.

**Comment by mschwager** [comment]
Might be the same as https://github.com/returntocorp/semgrep/issues/2098 and https://github.com/tree-sitter/tree-sitter-ruby/issues/140.

**Comment by aryx** [comment]
This now correctly parses, but the AST for it seems wrong.

**Comment by aryx** [comment]
I've created another issue for the CST/AST problem:
