### ISSUE TITLE
Weird behavior with ruby lambdas

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1581]
**Describe the bug**
Reports parse error when running over this code: https://semgrep.dev/GRyq/

```
module ActionDispatch
  module Routing
    class Mapper
      class Constraints < Routing::Endpoint
        attr_reader :app, :constraints

        SERVE = ->(app, req) { app.serve req }
        CALL  = ->(app, req) { app.call req.env }
      end

      class Scope
        def each
          node = self
          until node.equal? NULL
            yield node
            node = node.parent
          end
        end

      end
    end
  end
end
```

**To Reproduce**
In the original file https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/routing/mapper.rb removing the lambdas just causes semgrep to report an error in a different place. In the supplied reproduction, semgrep no longer reports any error but running ocaml-tree-sitter on this file reports a failure to parse.

**Environment**
Uses ocaml-tree-sitter 8a02100689750d1d0b96daa1407b27c01a1f5fa8

**Comment by mjambon** [comment]
I confirm the problem. It looks like a transformation that we apply to the grammar causes the parser to fail. I started a branch for this: https://github.com/returntocorp/ocaml-tree-sitter/tree/ruby-error

I will handle this later.

**Comment by brendongo** [comment]
Forgot to add to the issue but removing the each function also results in semgrep reporting no parse errors: https://semgrep.dev/D8yP/

**Comment by aryx** [comment]
works now on develop: https://semgrep.dev/s/GRyq?version=develop
