### ISSUE TITLE
[Ruby] Indentation with dot access functions

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1582]
**Describe the bug**
Semgrep unable to parse https://semgrep.dev/Rryq/
the error goes away when the call is in a single line: https://semgrep.dev/Ajy2/
but also interestingly goes away when a different line is deleted/commented out: https://semgrep.dev/B2yA/

For posterity:
```
describe "with" do
  it "should support basic WITH" do
    select_manager = comments.project(Arel.star).with(users_as)
                      .where(comments[:author_id].in(users_top.project(users_top[:id])))
  end

  it "should support WITH RECURSIVE" do
    recursive_term = Arel::SelectManager.new
    recursive_term.from(comments).project(comments_id, comments_parent_id).where(comments_id.eq 42)
  end
end
```

**Comment by aryx** [comment]
We may need to update to the latest tree-sitter-ruby which got a few updates recently.

**Comment by aryx** [comment]
works on develop! https://semgrep.dev/s/Rryq?version=develop
