### ISSUE TITLE
Parse Error Ruby Lambda

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1583]
**Describe the bug**
Fails to parse two lambdas in a row: https://semgrep.dev/WeW2/

**To Reproduce**
When either lambda is commented out the code parses correctly.

Potentially related to #1581

**Comment by aryx** [comment]
This now works on develop, thx to martin recent update to the latest tree-sitter.

**Comment by aryx** [comment]
see https://semgrep.dev/s/WeW2?version=develop
