### ISSUE TITLE
Output JSON for test arg

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1592]
```bash
semgrep --test --json --config <rules> <files>
```

```json
{
   "results": {
       "nodejsscan.no-xss": {
            "triggers": 8,
            "found": [{"path": "rel/path/to/file", "start": {"line": 30, "col": 3}}],
            "expected": [{"path": "rel/path/to/file", "start": {"line": 30, "col": 3}}],
            "pass": true
        }
    },
   "all_pass": false
}
```

**Comment by aryx** [comment]
?

**Comment by aryx** [comment]
Can someone document what this is is about?

**Comment by mschwager** [comment]
@aryx https://github.com/returntocorp/semgrep/pull/1665 provides some good context here.

Basically, TL;DR is @ajinabraham, and likely other users, would like to be able to programmatically analyze our `--test` output. To achieve this we're making the `--test` flag respect the `--json` output option.
