### ISSUE TITLE
Provide a working Dockerfile for building on alpine

### ISSUE THREAD

**Issue by SPoint42** [semgrep/semgrep#1594]
The current dockerfile to build semgrep, seems buggy. I could not build an docker image with it. 
there is a strang git pull in the 16th line and the opam switch also failed 

Tests on a Windows 10 host

**Comment by underyx** [comment]
@brendongo I see that you reviewed the Dockerfile's current iteration. Could you maybe shed some light on this `git pull` in there?

Here's a thread from our community Slack with more context about the question: https://r2c-community.slack.com/archives/CK86BJ5DW/p1598433513061100

**Comment by brendongo** [comment]
What error are you getting when trying to build the docker file? Not entirely sure what you're trying to do. The Dockerfile already builds on alpine.

**Comment by SPoint42** [comment]
I use this dockerfile : https://raw.githubusercontent.com/returntocorp/semgrep/develop/Dockerfile

and have this 

``` ---> edffa82661af
Step 4/38 : USER opam
 ---> Using cache
 ---> 262183352470
Step 5/38 : WORKDIR /home/opam/opam-repository
 ---> Using cache
 ---> 2d931ee45af7
Step 6/38 : RUN git pull && opam update && opam switch create 4.10.0+flambda
 ---> Running in b166461d0d9f
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection refused
```
When I try to exclude the pull 

```
 ---> 262183352470
Step 5/38 : WORKDIR /home/opam/opam-repository
 ---> Using cache
 ---> 2d931ee45af7
Step 6/38 : RUN opam update && opam switch create 4.10.0+flambda
 ---> Running in 8667f0bbc4d0

<><> Updating package repositories ><><><><><><><><><><><><><><><><><><><><><><>
[default] no changes from git+file:///home/opam/opam-repository
[ERROR] No compiler matching '4.10.0+flambda' found, use 'opam switch list-available' to see what is available, or use '--packages' to select packages explicitly.
The command '/bin/sh -c opam update && opam switch create 4.10.0+flambda' returned a non-zero code: 5

```

**Comment by brendongo** [comment]
Looking into what the dockerfile will look like without the git pull but in the mean time it looks like you might be running this with a proxy or without network access.

**Comment by SPoint42** [comment]
There is no proxy between me and internet

**Comment by brendongo** [comment]
Working on updating the base image so the git pull is unnecessary.

Not sure why your local docker build is unable to connect to github.com. https://github.com/npm/npm/issues/6285 looks like other people had similar problems due to ports (TCP 9418) being blocked.

**Comment by brendongo** [comment]
Update: the base image we use in the dockerfile right now interacts with the opam package repos using git (relevant: https://opam.ocaml.org/doc/Usage.html#opam-repo) we're going to switch over to an image that doesn't use a git backed opam repository in the next week or two. However there are other operations in the dockerfile that require git (updating semgrep submodules) so you might still run into issues if the port is indeed blocked in your network.

**Comment by mschwager** [comment]
Closing in favor of #1636. When that is complete a Alpine Dockerfile should be trivial.
