### ISSUE TITLE
String capture groups return 0 characters

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#1609]
I’m running an issue where I want to extract ruby key names and put them into a message, but the message comes back as blank. This appears to happen with any string.

Repo: https://semgrep.dev/s/QwJQ/
Repo 2: https://semgrep.dev/s/P9PW/

**Comment by aryx** [comment]
@IagoAbal do you want to have a try at this issue?

**Comment by nbrahms** [comment]
This appears to also be an issue with Go: https://semgrep.dev/s/OkbB

**Comment by aryx** [comment]
It is a todo in parse_treesitter_helper.ml combine_tokens function.

**Comment by aryx** [comment]
The go example now works (with develop).
Tackling the ruby examples now.

**Comment by aryx** [comment]
Works with develop now.
