### ISSUE TITLE
[Ruby] "Hash" syntax equivalence

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1614]
**Describe the bug**
This syntax:
```ruby
db.query({:a => b}, ...)
```

is equivalent to this syntax:
```ruby
db.query(a: b, ...)
```

However, it does not match: https://semgrep.dev/s/0gPv/
Nor can we match using `a: b` syntax explicitly: https://semgrep.dev/s/Kd97/

**Comment by aryx** [comment]
I think that recent Ruby versions will remove this equivalence.
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by jonatanmurga** [comment]
> **Describe the bug**
> This syntax:
> ```ruby
> db.query({:a => b}, ...)
> ```
> 
> is equivalent to this syntax:
> ```ruby
> db.query(a: b, ...)
> ```
> 
> However, it does not match: https://semgrep.dev/s/0gPv/
> Nor can we match using `a: b` syntax explicitly: https://semgrep.dev/s/Kd97/
>

**Comment by aryx** [comment]
there are lots of blog posts indicating this is actually a bad practice, and that ruby 2.7 warns about using the hash syntax
and ruby 3.0 will forbid it, so probably better to not encourage it.
