### ISSUE TITLE
Match TypeScript Types

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#1632]
- [x] Add type nodes to pfff JavaScript AST
- [x] Convert pfff js type nodes to pfff generic type nodes
- [x] Generate pfff type nodes from tree-sitter parser
- [x] Handle complex types, not just single identifier types like "int" on tree-sitter-side
- [x] Handle the same on pfff side in ast_js_build.ml

**Comment by mschwager** [comment]
I [added a comment here](https://github.com/returntocorp/semgrep/pull/1664#issuecomment-690383254), but perhaps it'd be better served on this issue:

> It looks like we're adding [typed metavariable](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#typed-metavariables) support for Typescript. Should we update the docs?

**Comment by aryx** [comment]
good enough for now
