### ISSUE TITLE
Typos on semgrep.dev/learn

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1639]
Typos:
- 2d Missing space `patternrequests.get()`
- 4a `inlcude`
- 5c missing space `withString.equals()`
- 6c missing space `normalpattern`

**Comment by chmccreery** [comment]
https://github.com/returntocorp/semgrep-app/pull/509

**Comment by ekse** [comment]
One more:
- 6c missing space `onlyhttp.ResponseWriter.Write()`

**Comment by chmccreery** [comment]
fixed on semgrep-app
