### ISSUE TITLE
support for capturing the output of ellipsis operators $...

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1644]
We've seen a number of applications where matching an arbitrary number of decorators is difficult (cc @clintgibler @minusworld)

Perhaps we could use the ellipsis operator with $ to capture a sequence, eg:

```
@$...
def foo():
    ...
    bar($...)
```

would match

```
@prop1
@prop2 
def foo():
    bar(a, b, c)
```

and bind metavars:
$A1 = prop1
$A2 = prop2
$B1 = a, $B2 = b, $B3 = c

cc @aryx for implementation thoughts

**Comment by dgryski** [comment]
I can see this making the rule and matching syntax a bit clunkier without more powerful constructs.  Maybe it'll make sense to default to python rules in that case, but at the very least you'll want something like awk's `NF` to indicate the end of the list and be able to count backwards.

**Comment by aryx** [comment]
Right now we have $X to match a full single element (an expression, a statement), and '...' to match a sequence of elements (arguments, parameters, statements). In some languages you can even use ...$X to match a rest parameter. It might make sense then to also provide $X... (the opposite of ...$X) to match a sequence of elements and store the result in a "Sequence metavariable" $X.

**Comment by aryx** [comment]
We could also use ...$X, but this would prevent us to match specifically rest parameter, so maybe $X... is safer.

**Comment by aryx** [comment]
to avoid conflicts with existing constructs.

**Comment by chgg-kboberg** [comment]
+1 to this request, I have a use case this would be great for (credential leaks in format strings)

**Comment by mschwager** [comment]
Here were my musings on this type of functionality: https://github.com/returntocorp/semgrep/issues/744

I'm not sure if this can be generally implemented for many language constructs in many languages, but it'd be great to capture variadic language elements and output them in a structured way for post-processing.

**Comment by ievans** [comment]
Keep open

**Comment by aryx** [comment]
This is mostly done. We have now $...X for most languages for calls and statements

**Comment by aryx** [comment]
Not yet for parameters or decorators

**Comment by ievans** [comment]
@aryx @minusworld is $...X documented on semgrep.dev/docs?

**Comment by aryx** [comment]
I don't think so. Also we could extend the cheatseet autogeneration to look for metavar_ellipsis_args.sgrep (and later for also _params, and _stmts)

**Comment by ievans** [comment]
I'll make an issue for the docs, and close this one.

**Comment by ievans** [comment]
Note we didn't implement binding new metavariables corresponding to every item. I'll let someone create a new issue or re-open this one if there's a lot of interest.

**Comment by mschwager** [comment]
> Also we could extend the cheatseet autogeneration to look for metavar_ellipsis_args.sgrep (and later for also _params, and _stmts)

Yeah, we should do this, and probably make it a requirement for GA languages so users know where they can expect it :+1:
