### ISSUE TITLE
Add tsx support (jsx syntax for typescript)

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1647]
This is part of the effort to support typescript in semgrep. Unlike jsx for javascript, tsx is not 100% compatible with typescript. Tree-sitter has a slightly different grammar for it.

Much of this work involves figuring out how to reconcile the code generated by ocaml-tree-sitter separately for ts and tsx. If possible, we'd use a single `CST.ml` file (type for the CST) for both the ts parser and the tsx parser, as well as a single boilerplate file that translates the CST to the js/ts AST.

Relevant documentation: https://www.typescriptlang.org/docs/handbook/jsx.html

**Comment by aryx** [comment]
We can close that no? Seems done to me.

**Comment by mjambon** [comment]
:+1:
