### ISSUE TITLE
JS Parse Failures while Trying to parse SpiderMonkey jit-test suite

### ISSUE THREAD

**Issue by mgaudet** [semgrep/semgrep#1689]
**Describe the bug**

There are a variety of JS parse failures (of which #1688 is one) when parsing the spidermonkey jit-test suite. 

**To Reproduce**

Acquire the [jit-test directory](https://searchfox.org/mozilla-central/source/js/src/jit-test/tests) from [mozilla-central](https://firefox-source-docs.mozilla.org/contributing/contribution_quickref.html?highlight=clone#clone-the-sources); then run 

```
semgrep -e 'function $FUNC(..., ...$MORE) { ... }' -l javascript js/src/jit-test/tests/
```

(replacing the path as appropriate) 

[Semgrep JS Parse bugs.txt](https://github.com/returntocorp/semgrep/files/5241892/Semgrep.JS.Parse.bugs.txt) is the output from my run. 

**Expected behavior**
All tests parse. 

**Environment**

pip-installed binary.

**Comment by aryx** [comment]
Yes, those test suites expose all the edge cases in Javascript but I don't think we'll have the time to fix
all of those. We currently focus our energy on real code. Note that we now use tree-sitter-javascript
to parse javascript code, so feel free to report parsing bugs to them.
