### ISSUE TITLE
Documentation in learn/6 wrong on ellipsis and keyword argument mix

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1700]
**Describe the bug**

This problem is either in your tutorial (https://semgrep.dev/learn/6) or in the core code itself.

Section "2d. The ellipsis operator: before and after" states:
```
Similarly, requests.get(timeout=30, ...) only matches if timeout=30 is the first argument.
```
But when I use `requests.get(timeout=30, ...)` it matches all 3 cases:
```
requests.get("https://semgrep.dev", stream=True, timeout=30)
requests.get(timeout=30, url="https://semgrep.dev")
requests.get("https://semgrep.dev", timeout=30, stream=true)
```

**To Reproduce**
Visit the above URL and try the example.

**Expected behavior**
Only the middle line should match.

**Screenshots**
<img width="984" alt="image" src="https://user-images.githubusercontent.com/6817500/93721154-d2b96480-fb42-11ea-9f96-28db7bf818b4.png">

**Environment**
semgrep.dev

**Comment by aryx** [comment]
Well, the issue here is that the pattern mix '...' and keyword argument, and keyword argument can be matched in any order. If you do foo(1, ...), then indeed this will match only if 1 is the first argument, but foo(kwd=1,...) will match also when the keyword argument is later.

**Comment by msorens** [comment]
Thanks! I thought I had seen that keywords could be in any order, as you say, but I am learning so I assumed the tutorial was also telling the truth. 😁 Thanks for clarifying!
