### ISSUE TITLE
Rules appearing multiple times on "All Rules" web page

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1701]
**Describe the bug**
Isolating the rule picker to "none" for language (https://semgrep.dev/r?lang=none&sev=ERROR,WARNING,INFO&tag=dgryski.semgrep-go,security,java-spring,java-stdlib,js-node,nodejsscan,owasp,dlint,correctness,best-practice,maintainability,performance,compatibility)
shows many duplicates. The image shows just a few examples, but there are more.

**To Reproduce**
Visit the above URL review the list.

**Expected behavior**
Each entry should appear exactly once in the list.

**Screenshots**
<img width="753" alt="image" src="https://user-images.githubusercontent.com/6817500/93722121-5c6c3080-fb49-11ea-8448-8c0ce7314c77.png">

**Environment**
semgrep.dev

**Comment by dlukeomalley** [comment]
@msorens This is a confusing UI on our end. Upon expanding the rules by clicking the `...` they are actually different. We're going to update the UI to make this clearer and we've have marked this `blocked` until we discuss it further and have some mocks to test. Up for looking at some mocks when they're ready?

**Comment by msorens** [comment]
Sure thing; thanks!

**Comment by dlukeomalley** [comment]
@msorens Closing this for now. We no longer use the `...` to hide rule names and have some additional changes on staging that should land this week (CC @ievans @brendongo) ✌️
