### ISSUE TITLE
Looks like "js" category has snuck in accidentally on rule picker page

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1702]
**Describe the bug**
I was wondering why there are both `javascript` and `js` categories. Checking them individually, there are many rules for `javascript` but just a single rule for `js`, leading me to believe it was meant to be included in the former. 

**To Reproduce**
Visit the rule picker page. https://semgrep.dev/r?lang=js&sev=ERROR,WARNING,INFO&tag=dgryski.semgrep-go,security,java-spring,java-stdlib,js-node,nodejsscan,owasp,dlint,correctness,best-practice,maintainability,performance,compatibility

**Expected behavior**
Should not have a `js` language choice.

**Screenshots**
<img width="863" alt="image" src="https://user-images.githubusercontent.com/6817500/93722258-60e51900-fb4a-11ea-9309-fb4ed2c1817c.png">

**Environment**
semgrep.dev

**Comment by dlukeomalley** [comment]
Thanks for filing @msorens and for the detailed tickets (all of them 🙏 ). Queuing this up.
