### ISSUE TITLE
Category selections confusing until the "aha" moment

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1703]
**Is your feature request related to a problem? Please describe.**

The categories on the rule picker page are divided into two camps: language-specific (e.g. dgryski.semgrep-go, js-node, java-spring, etc.) and language-agnostic (owasp, best-practice, correctness, and so forth). The problem is that whatever language you have selected, all categories are enabled, which makes for a confusing UX. 

If I select just the java language what should happen if I select the js-node category? Sure, in that scenario it is obvious: there will be no rules listed. But that took me a little while to realize because that is not typically how one will work. One arrives at the page with _everything checked_. So coming in fresh, then, say I uncheck all languages except java. Now I still have all categories checked so I have a long list of rules. Now if I uncheck js-node, has that done anything? No way to tell without counting the list with it checked, then unchecked.

On nomenclature: knowing which categories are language-agnostic or language-specific is much less obvious becuase there is no naming convention--you have to hunt for the language name in the category. It might be at the end (dgryski.semgrep-go), the start (java-stdlib), or carefully hidden in the middle (nodejsscan). 

Finally, it would be nice to be able to check or uncheck all items in a section. As a new user, for example, I think what I tried to do is something a lot of folks would: try to see what rules are available when I select just one category for one language. There is a lot of un-checking involved! 🤷 

**Describe the solution you'd like**

Several small things could improve the UX dramatically:
1. For the current selection, show a count of rules on the page.
2. Disable language-specific categories for languages that are not selected.
3. Bonus: disable language-agnostic categories, too, if there happen to be none available for any of the selected languages.
4. Adopt a convention for naming categories, e.g. `<language>-<item>`.
5. Provide a checkbox next to the section (see image) so you can check or uncheck all items in that section.

**Screenshots**
<img width="866" alt="image" src="https://user-images.githubusercontent.com/6817500/93723511-ddc8c080-fb53-11ea-801e-042df3626433.png">

**Comment by dlukeomalley** [comment]
@msorens Do you feel this ticket has been resolved or is outstanding given the UI changes on Semgrep App?

![image](https://user-images.githubusercontent.com/605906/108290533-76845c00-7145-11eb-82f0-17769dab8cc8.png)

**Comment by msorens** [comment]
@dlukeomalley (1) and (5) have clearly been addressed and have made it much more friendly--thanks for those! I would still suggest that (2) and (3) -- which are really the same item -- would be a useful UX improvement.

**Comment by dlukeomalley** [comment]
@msorens Agreed! I'm tracking this as a follow-up with the title "Semgrep Registry users can only select categories with 1+ result when filtering". If I may, I'd like to close this specific ticket for now and use what I've filed privately to address the remaining items. Is that ok? 🙏
