### ISSUE TITLE
Select rules and get config URL on Semgrep.dev

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1704]
**Describe the bug**
I have looked throughout your website but have been unsuccessful in figuring out how to apply a set of selected community rules. Starting here, I see how to use a specific named set, like `r2c` or `gosec`.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/6817500/93723980-14083f00-fb58-11ea-8748-cad77ec1dd51.png">

Clicking the header there takes me to the Rulesets tab, and selecting a specific ruleset like `gosec` shows how to use that ruleset:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/6817500/93724016-6cd7d780-fb58-11ea-94ec-9a78065723bd.png">

But if I go over to the All Rules tab--which seems to provide a nice filtering mechanism to get a selected subset of rules--what do I do once I applied some filters? It tells me (as shown) to "...just pass a config argument". OK, what argument? How do I formulate it?

<img width="863" alt="image" src="https://user-images.githubusercontent.com/6817500/93724037-9bee4900-fb58-11ea-9a55-540824fb4492.png">

I observe that if I open up a single rule, then select "semgrep CLI" from the very bottom, I get info on how to scan with that single rule:
<img width="655" alt="image" src="https://user-images.githubusercontent.com/6817500/93724088-fa1b2c00-fb58-11ea-8bda-d4926ad0e419.png">

But surely there must be a way to construct a configuration using all the filtered rules on the page to then scan with those selected rules? 

---

Side note: The use of `--config` is not even mentioned in the output of `semgrep --help`:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/6817500/93724192-b4129800-fb59-11ea-82fc-4de720bc5b0d.png">

**Comment by dlukeomalley** [comment]
@msorens Thanks for the detailed issue! Right now there is not a generally available way to select multiple rules from the registry to run locally. We're working on this now, it's a clear deficiency.

A few ideas come to mind, curious your thoughts:

1. Add support for a Semgrep config file that works similar to npm's `package.json`, specifying named rules and rulesets to download from the registry when Semgrep runs. This is loosely defined in #1054 
2. Add a "download rules" button to the UI to generate a rules yaml file to save
3. Allow for creating temporary or named rulesets from the registry UI
4. Other?

For the `semgrep --help`, the help output shows the short-hand for `--config`, which is `-f CONFIG`. I found it confusing as well when I was looking for an answer to your question. Do you think the help message should be changed to `--config`?

I've also filed some internal tickets to improve the copy on semgrep.dev/rulesets.

**Comment by msorens** [comment]
Thanks, @dlukeomalley ! From my limited (but growing) knowledge, any of 1, 2, or 3 sound quite reasonable when running semgrep locally. Probably slight preference to 1 or 3 since those would always have the "latest" version of the rule available.

Note that I have not yet looked at using semgrep in CI--which is my ultimate goal--so if any of those three would work better in CI, that would be my preference.

**Comment by msorens** [comment]
Regarding the `semgrep --help`, that is my mea culpa. I just looked again, and I see that, yes, in the itemized list it shows `-f CONFIG, --config CONFIG`. I simply did not see that yesterday. But there is a lot of text there. So I am good with leaving that as is. (In the usage line, you are already being consistent by using the short-hand for other flags, so that one should stay `-f`.)
