### ISSUE TITLE
[typescript] Probable bug in parsing

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1713]
**Describe the bug**

Running semgrep on my large-ish code base yielded these remarkably few probable parsing problems--nice job, folks!

These files compile cleanly and are currently running in production so, as far as I know, they should be parsable.
```
warn: parse error
  --> data-bags.requests.ts:1
1 | import { Injectable } from '@angular/core';
  | 
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse data-bags.requests.ts as ts

warn: parse error
  --> cookbook-details.component.ts:1
1 | import { Component, OnInit, OnDestroy } from '@angular/core';
  | 
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse cookbook-details.component.ts as ts

warn: parse error
  --> entities.ts:1
1 | import {
  | 
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse entities.ts as ts
```

**To Reproduce**

My codebase is open source so you can go right to, well, the source: https://github.com/chef/automate/tree/master/components/automate-ui
 

**Expected behavior**
No parsing errors.

**Environment**
Version 0.24.0

**Comment by mjambon** [comment]
Thanks for the report, @msorens. I'll look into this.

**Comment by aryx** [comment]
With the better error reporting I now get those parse error locations:
```
warn: parse error
  --> entities.ts:20
20 |   readonly [id: string]: T;
   |             ^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse entities.ts as ts

warn: parse error
  --> data-bags.requests.ts:20
20 |   : Observable<DataBagDetailsSuccessPayload> {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse data-bags.requests.ts as ts

Warnings exist. Run with `--strict` to turn warnings into errors.

```

**Comment by aryx** [comment]
This can help in the futur to provide more information on the kind of constructs we do not parse well, which also makes it
easier to create simpler test file showing the issue (minimal test case).

**Comment by msorens** [comment]
Some additional feedback: I just upgraded from 0.24 to 0.26 and I am seeing errors on the same two files as you show @aryx , but they are different errors !?!

```
warn: parse error
  --> data-bags.requests.ts:1
1 | import { Injectable } from '@angular/core';
  | 
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse data-bags.requests.ts as ts

warn: parse error
  --> entities.ts:1
1 | import {
  | 
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse entities.ts as ts

```

**Comment by aryx** [comment]
yes the latest code for better error location is not yet in the release, it will be in 0.27

**Comment by msorens** [comment]
Just to be explicit, with 0.27.0 I am now seeing the revised error messages @aryx indicated. However, those files are all valid code, so those errors should not be present.

**Comment by mjambon** [comment]
@msorens a number of fixes are coming for typescript but still need integration work. They will become available most likely in the semgrep release two weeks from now. This includes:

* more complete typescript syntax support ([list of typescript errors](https://github.com/returntocorp/ocaml-tree-sitter/issues/115), [list of tsx errors](https://github.com/returntocorp/ocaml-tree-sitter/issues/118))
* tolerating local errors. Even with a parsing error, most of the file will remain searchable by semgrep.

**Comment by aryx** [comment]
Let's keep this open until we double check that the new release really fix the issue.

**Comment by aryx** [comment]
Unless this is already working with the develop version @mjambon ?

**Comment by dlukeomalley** [comment]
@aryx @mjambon This appears to still not parse. I ran a subset of the rules on one of the problematic files via Semgrep.dev:

❌ 0.27.0: https://semgrep.dev/s/GRBn/?version=0.27.0
❌ develop: https://semgrep.dev/s/GRBn/?version=develop

**Comment by aryx** [comment]
Can we close this now?

**Comment by mjambon** [comment]
This is now fixed:
```
warn: parse error
  --> entities.ts:20
20 |   readonly [id: string]: T;
   |             ^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse entities.ts as ts
```
This is fixed too:
```
warn: parse error
  --> data-bags.requests.ts:20
20 |   : Observable<DataBagDetailsSuccessPayload> {
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse data-bags.requests.ts as ts
```

It's all good now, already released.
