### ISSUE TITLE
Clean Way to Download Rule Packs

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#1714]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to download rule packs, like `DanHatesNumbers.ruby-rules` and `r2c-security-audit`.
I'd like to be able to compare rule-packs, to see which ones are simply subsets, supersets, and unique rules between them, or rules that have been modified. e.g. I want to be able to compare rule packs.

If I download the YAML, I can compare them with `vimdiff` or I can grep out the rule ids, sort them, and diff them.

**Describe the solution you'd like**

A button to download a rule pack's YAML, identical to  what the `semgrep` CLI tool will use.

**Describe alternatives you've considered**

I found I could download the config of a pack by adding a `/c/` before the `/p/`, e.g. `https://semgrep.dev/p/DanHatesNumbers.ruby-rules` becomes `https://semgrep.dev/c/p/DanHatesNumbers.ruby-rules`. 

**Additional context**

No.

**Comment by ben-elttam** [comment]
https://r2c-community.slack.com/archives/CK86BJ5DW/p1600705062035800?thread_ts=1600654541.021900&cid=CK86BJ5DW
> This is a bit of a hack, but you can call our backend API directly: https://semgrep.dev/api/pack/eslint-plugin-security, e.g.

**Comment by dlukeomalley** [comment]
@ben-elttam May I close this ticket given the use of `https://semgrep.dev/c/p/<ruleset>`?

**Comment by ben-elttam** [comment]
@dlukeomalley yes, I'll close this ticket.
