### ISSUE TITLE
[PHP] no support for ... between statements

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1715]
See https://twitter.com/dandr3ss/status/1308273733740589056

**Comment by aryx** [comment]
works now: https://semgrep.dev/s/NxRn/?version=develop

**Comment by erwanlr** [comment]
Was there a regression ?

Line 14 should match in the example you gave above, but does not.

Edit: Seems like to be a visual thing, as the match is on line 6

**Comment by aryx** [comment]
Line 14 matches, but it's really Line6 to Line14 that is the match. It's because we return all the lines that match a pattern, and here
the pattern has the form A ... B and so we return all the lines between A and B (including A and B), hence the yellow matching color going until Line 14.

**Comment by erwanlr** [comment]
Yep, I noticed that after playing around xD

I would suggest to have a match output like `Line 6-14:` in such case ;)

Thanks for the clarification :)
