### ISSUE TITLE
JavaScript metavariable matching objects seems to swallow commas/colons in resulting match text

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#1723]
**Describe the bug**
When matching the arguments to a function call in JavaScript, certain characters, specifically colons and commas, appear to not be included in the metavariable match.

The pattern `func($ARG)` when run on

```javascript
func({"arg1": "bar", "arg2": "bar"});
```

Returns: `{"arg1""bar""arg2""bar"}`.

**To Reproduce**
https://semgrep.dev/s/clintgibler:javascript-matching-object-args-swallows-punctuation

**Expected behavior**
I would expect that `$ARG` includes the full text of matched arguments, including colons, commas, and key/values.

My specific use case for this is I want to use semgrep to extract this first argument object, parse the match as JSON, and then extract some of the keys/values for subsequent analysis via post processing with another script.

Because the matched metavariable text does not include the punctuation, it is not valid JSON, thus what I'm aiming to do is not currently possible. 

**Environment**
Running current version of semgrep in semgrep.dev - 0.24.0.

**Comment by aryx** [comment]
yep, always been like that. Commas are not stored in the AST

the generic AST is half a CST; it's a bit messy, but we keep tokens when the range would be incorrect without them (hence we keep (), {} around expression or statements, but we don't care about commas)

**Comment by clintgibler** [comment]
More context from @aryx:

> We need to call the pretty printer on what is matched by the metavariable. The pretty printer is supposed to insert the commas; We need that for the autofix feature

> The pretty printer is incomplete though; it was started by Emma for the pattern-from-code synthesizer.

**Comment by aryx** [comment]
Maybe Emma has some ideas to fix that.
Maybe when we return the abstract_content to the semgrep-python wrapper we could call the pretty-printer,
so we would get the right columns.

**Comment by aryx** [comment]
This now works thx to @brendongo fix where the python wrapper does not use abstract_content anymore but
extract the content from the range from the file directly (it has also some issues, like it deletes newlines in the matched code which can have bad implications, but that's another problem).
