### ISSUE TITLE
Java pattern error for String value

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1742]
- id: sfs.java.cors.getOrigin-in
  patterns:
    - pattern-either: 
      - pattern: |
          String $VAL = $REQUEST.getHeaders().getOrigin()
          ...
          $RES.addHeader("=~/access-control-allow-origin/i", $VAL);
  message: |
    Permissive CORS policy will allow a malicious application to communicate with the victim application in an inappropriate way, leading to spoofing, data theft, relay and other attacks.
  fix: |
    
  severity: WARNING

Why this rule is not valid?

**Comment by brendongo** [comment]
Looks like you are missing a semicolon after getOrigin: https://semgrep.dev/s/Kd2Y/
