### ISSUE TITLE
Docker image for CI not behaving as expected

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1743]
**Describe the bug**
I am trying to hook up semgrep to our Buildkite CI system, in particular running semgrep in the [docker buildkite plugin](https://github.com/buildkite-plugins/docker-buildkite-plugin).

But the particulars of the CI system are **not** the issue: after having problems trying to hook it up there, we then tried just using your docker container directly and still found the same issues.

**To Reproduce**

Here you will see that it is apparently not seeing any arguments being provided to semgrep:
```
$ docker run -it --rm --init --volume $(realpath .):/workdir --workdir /workdir returntocorp/semgrep:latest \
/bin/sh -e -c $'semgrep --error --config https://semgrep.dev/p/r2c .'

usage: semgrep [-h] [-g | -f CONFIG | -e PATTERN] [-l LANG] [--validate]
               [--strict] [--exclude EXCLUDE] [--include INCLUDE]
               [--no-git-ignore] [--skip-unknown-extensions]
               [--dangerously-allow-arbitrary-code-execution-from-rules]
               [-j JOBS] [--timeout TIMEOUT] [--max-memory MAX_MEMORY]
               [--timeout-threshold TIMEOUT_THRESHOLD] [-q]
               [--no-rewrite-rule-ids] [-o OUTPUT] [--json] [--debugging-json]
               [--junit-xml] [--sarif] [--test] [--test-ignore-todo]
               [--dump-ast] [--error] [-a] [--dryrun] [--disable-nosem] [-v]
               [--version] [--force-color] [--disable-version-check]
               [target [target ...]]
semgrep: error: argument -e/--pattern: expected one argument
```
And in this variation we attempted to use semgrep directly as the entry point rather than the shell: 
```
$ docker run -it --rm --init --volume $(realpath .):/workdir --workdir /workdir returntocorp/semgrep:latest \
'semgrep --error --config https://semgrep.dev/p/r2c .'

No config given and .semgrep.yml was not found. Try running with --help to debug or if you want to download a default config, try running with --config r2c
```

**Expected behavior**
Either of the commands above should run successfully. Or maybe not? Looking for your guidance here to get this to work.

**Comment by underyx** [comment]
Heya! I responded on Slack, but I'll just post the answer here as well for you:

> It seems like the issue might be that we set `ENTRYPOINT semgrep` on the docker image, which means that anything you set as your command will be by default used as arguments to the semgrep CLI
>so, instead of say
>
>```
>docker run returntocorp/semgrep /bin/sh -e -c $'semgrep --error --config https://semgrep.dev/p/r2c .'
>```
>
>you’d just write
>
>```
>docker run returntocorp/semgrep --config https://semgrep.dev/p/r2c .
>```
>
>I omitted your other flags for the sake of simplicity, but all those flags should work just as well.

**Comment by underyx** [comment]
Issue resolved as per Slack 🙃
