### ISSUE TITLE
semgrep-core -target_file doesn't allow trailing newline.

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#1746]
The argument of the `-target_file` option of `semgrep-core` contains a list of files.
```
$ semgrep-core -lang javascript -rules_file rules -target_file target
{"error":"unknown exception","message":"Unix.Unix_error(Unix.ENOENT, \"stat\", \"\")"}
```
The `target` file contains just one file path ended with a newline. The error message shows that semgrep-core tries to read the file named `""`.

**Comment by aryx** [comment]
Why this problem suddenly occured? Did something changed in the way the semgrep-python wrapper calls semgrep-core? It used to work fine.

**Comment by aryx** [comment]
Does a user have the issue?

**Comment by mjambon** [comment]
The user was me. I was trying to reproduce an error and simplify the input, but it was failing mysteriously because my text editor would add a trailing newline. I'll be more specific next time.
