### ISSUE TITLE
Findings work without imports

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1747]
There is no findings
https://semgrep.dev/s/6W3Y/

But if i delete impots, it works
Why?
https://semgrep.dev/s/ol6d/

**Comment by brendongo** [comment]
Function calls in Semgrep patterns need to be fully specified: https://semgrep.dev/s/pGoJ/ 
Looks like our documentation did not include this info. Sorry for the confusion. Added a ticket to update our docs.
