### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by dekadentno** [semgrep/semgrep#1751]
**Is your feature request related to a problem? Please describe.**
It is not possible to write rules for `.vue` files.

**Describe the solution you'd like**
Ability to write rules for `.vue` files. Vue.js has its own file extension for writing components and because of that I assume it has to be treated as a separate language.

**Describe alternatives you've considered**
I'll try to make a maneuver using [paths](https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#limiting-a-rule-to-paths), as a suggestion from @ievans (thanks)

**Additional context**
I am willing to implement rules and submit them as a PR that are a [security concern](https://vuejs.org/v2/guide/security.html) in Vue.js, but it's currently not possible because semgrep ignores `.vue` files.

**Comment by aryx** [comment]
Is there somewhere some documentation of the syntax of those .vue files? Do they contain just javascript code?

**Comment by dekadentno** [comment]
> Is there somewhere some documentation of the syntax of those .vue files? Do they contain just javascript code?

Most Vue.js apps are written as [Single File Components (SFCs)](https://vuejs.org/v2/guide/single-file-components.html). SFCs can have a `template` tag for the html, `script` tag for the javascript and the `style` tag for the css, as it can be seen on the image below:
![vue sfc](https://vuejs.org/images/vue-component.png)
In rarer cases, Vue components can be written in `.js` files, where the html is written as a [template literal](https://vuejs.org/v2/guide/components.html) (basically, as a string), but such way is not usual for medium and large scale apps.

**Comment by aryx** [comment]
And what kind of check you want to do on those .vue files? Do you just want (1) the ability for semgrep Javascript pattern
to apply on the <script>...</script> content or you also want the pattern to (2) match what is inside the template between
the {{ }}? Or do you want also the ability to (3) look for html pattern in the template?

(1) should be pretty easy, (2) is more difficult, (3) even more difficult.

**Comment by dekadentno** [comment]
> And what kind of check you want to do on those .vue files? Do you just want (1) the ability for semgrep Javascript pattern
> to apply on the <script>...</script> content or you also want the pattern to (2) match what is inside the template between
> the {{ }}? Or do you want also the ability to (3) look for html pattern in the template?
> 
> (1) should be pretty easy, (2) is more difficult, (3) even more difficult.

Most [security concerns](https://vuejs.org/v2/guide/security.html) regarding Vue.js are injection related and occurable in the `template` part of the SFC. So I'm afraid that the answer is (3).
But still, it's not impossible that, in the future, some security concerns will be possible in the `script` part of the SCF as well :worried: 
Also, an another important question is regarding the existing javascript related rules and their usage in `.vue` files (as in, will it be possible for those rules to detect issues in `.vue` files?)

**Comment by aryx** [comment]
> will it be possible for those rules to detect issues in .vue files?

Well if we implement (1) (and (2)) then yes all the existing javascript rules could be applied to the javascript-part of the .vue
(what is inside <script>...</script> and between {{ ... }} in the template part).

**Comment by dekadentno** [comment]
> > will it be possible for those rules to detect issues in .vue files?
> 
> Well if we implement (1) (and (2)) then yes all the existing javascript rules could be applied to the javascript-part of the .vue
> (what is inside <script>...</script> and between {{ ... }} in the template part).

Thank you for your time and quick replies @aryx 

I understand that everything mentioned regarding Vue.js is a really big and time consuming task. And I understand that things are not trivial as they are for e.g. angular. 

Vue.js grew rapidly in popularity over the last few years and at this very moment it's certainly the most popular frontend framework out there. It would be really nice to consider supporting rules for Vue.js in the future 🙂

**Comment by aryx** [comment]
Is there a way to call a tool on .vue file and get the resulting pre-processed .js file? Could you just use that?

How other tools like editors, language servers, linters, etc. handle .vue files? They have special code to recognize
the <template> {{ <script> tags? Do they call a vue "preprocessor? How do they relate things found on the pre-processed file to the original file?

**Comment by dekadentno** [comment]
> Is there a way to call a tool on .vue file and get the resulting pre-processed .js file? Could you just use that?
> 
> How other tools like editors, language servers, linters, etc. handle .vue files? They have special code to recognize
> the {{ <script> tags? Do they call a vue "preprocessor? How do they relate things found on the pre-processed file to the original file?


Vue uses the official [vue-template-compiler](https://github.com/vuejs/vue/tree/dev/packages/vue-template-compiler#readme) to precompile Vue files, you should check it out.
Also, there are some unofficial tools that can do the trick like 
- [vue-sfc-parser](https://github.com/ktsn/vue-sfc-parser)
- [parser](https://github.com/vuedoc/parser) 
- [vue-parser](https://github.com/prograhammer/vue-parser)
- [vue-eslint-parser](https://www.npmjs.com/package/vue-eslint-parser) - maybe he best bet in this case

Hope I answered your question.

**Comment by aryx** [comment]
:wave:

**Comment by dekadentno** [comment]
The stale bot reminded me to inform you about the `vue-template-compiler` I mentioned in one of the comments.  :)

A new version of Vue.js is out and it is using some new packages, like the [compiler-sfc](https://www.npmjs.com/package/@vue/compiler-sfc) for parsing single file components (.vue files). 

Vue.js 3 is mostly backwards compatible with Vue.js 2, but it has an additional approach for writing single file components.

Hope this info can help you in any way.

@aryx

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
Ok apparently there is a tree-sitter binding for vue. 
@dekadentno would you mind trying the playground here: https://ikatyang.github.io/tree-sitter-vue/ to check how mature the tree-sitter parser is? If you copy some of your code in the playground, do you see errors reported?

The tree-sitter-vue README says it supports Vue v2.6.0 Template Syntax . Is it recent enough?

**Comment by dekadentno** [comment]
> Ok apparently there is a tree-sitter binding for vue.
> @dekadentno would you mind trying the playground here: https://ikatyang.github.io/tree-sitter-vue/ to check how mature the tree-sitter parser is? If you copy some of your code in the playground, do you see errors reported?
> 
> The tree-sitter-vue README says it supports Vue v2.6.0 Template Syntax . Is it recent enough?

Hey @aryx, looks like it works well, I've tested it a lot, but it only supports parsing the template part of the component; the `script` and `style` will still remain uncovered by the parser, but it's a start. Glad to see this issue is still alive!

**Comment by aryx** [comment]
FYI we're planning to remove support for Vue in 1.93.0.
