### ISSUE TITLE
[typescript] Attempting to parse file in multiple languages--but not typescript

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1762]
**Describe the bug**

Valid typescript exists in this two-line file called test.d.ts:
```
import * as $protobuf from "protobufjs";

export namespace foo { }
```

Issues:
(a) Semgrep does not think it is valid typescript, but it is.
(b) Semgrep tries to parse it in several languages even though the file extension is `.ts`.
(c) Apparently semgrep does **not** try to parse it in typescript even though the file extension is `.ts` (!).

According to [this slack thread](https://r2c-community.slack.com/archives/CK86BJ5DW/p1601480840088700), I am told that semgrep should only be parsing based on the file extension, so this behavior seems quite odd.

**To Reproduce**

```
$ semgrep --error --config https://semgrep.dev/p/r2c  test.d.ts 
downloading config...
running 79 rules...
100%|███████████████████|79/79
warn: parse error
  --> test.d.ts:1
1 | import * as $protobuf from "protobufjs";
  |             ^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse test.d.ts as javascript

warn: parse error
  --> test.d.ts:1
1 | import * as $protobuf from "protobufjs";
  |             ^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse test.d.ts as java

warn: parse error
  --> test.d.ts:1
1 | import * as $protobuf from "protobufjs";
  |             ^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse test.d.ts as python

warn: parse error
  --> test.d.ts:1
1 | import * as $protobuf from "protobufjs";
  |             ^^^^^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse test.d.ts as go
```

**Expected behavior**
Successful parsing only as TypeScript.

**Environment**
```
$ semgrep --version
0.24.0
```

**Comment by brendongo** [comment]
Hi @msorens! If a directory is passed to semgrep it will crawl the files and use extensions to figure out the language of a file. If the file is passed directly to semgrep it scans it with all rules.

There actually also aren't any typescript rules in that rulepack.
