### ISSUE TITLE
Equivalence javascript to find open redirect does not work

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1765]
Why equivalence does not work? 

https://semgrep.dev/s/d7y6/

**Comment by dvyakimov** [comment]
The same:
https://semgrep.dev/s/ZWyW/

**Comment by mschwager** [comment]
Hi @dvyakimov,

Note that equivalences are an [experimental feature](https://github.com/returntocorp/semgrep/blob/develop/docs/experimental.md#equivalences), so there may be bugs. I've reduced your example to a more minimal test case: https://semgrep.dev/s/QwxJ/. I noticed a few things to consider here:

* You must specify `var $URL` as `var {$URL}` if this is what you're expecting.
* Semgrep will automatically handle `var` <-> `const` equivalences for you, so the `const` in the first example is fine.
* It looks like the `$FUNC.get(...) <==> this.request.$FUNC` equivalence is indeed not working as expected.

cc @aryx would you expect the above equivalence to work?

**Comment by dlukeomalley** [comment]
Hello, the `equivalences` experimental feature was deprecated in 0.56.0. Closing this ticket as a result 🙏
