### ISSUE TITLE
Make "this" as $FUNC (javascript)

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1766]
Semgrep does not classify "this" as a parameter ($FUNC), which is why you have to create another rule with autocorrect ($FUNC->this).
https://semgrep.dev/s/nePd/
Moreover, equivalence does not work to solve this issue
https://semgrep.dev/s/ErN5/

**Comment by mschwager** [comment]
This looks like a bug to me - I would expect `$THIS` to match `this`. E.g. this works: https://semgrep.dev/s/4BoL/, but this doesn't: https://semgrep.dev/s/P9x3/.

@aryx are we treating `this` as a special case? Is there a reason `$THIS` won't match `this`?

**Comment by aryx** [comment]
this is treated specially in the AST (It's an IdSpecial (This), but I don't understand why $THIS does not match it. $THIS should match any expression, including IdSpecial expressions.
