### ISSUE TITLE
import not matching what's expected

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1771]
**Describe the bug**

 https://semgrep.dev/s/KdNY/ fails to match the expected lines

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:  https://semgrep.dev/s/KdNY/

**Expected behavior**

`$X` should include the full path or there should be a way to match the fully qualified import path

`$X` is just matching `a` in `import a.auth`

**Comment by mschwager** [comment]
See also: https://github.com/returntocorp/semgrep/issues/975#issuecomment-681014485

**Comment by aryx** [comment]
I knew you would comment matt :)

**Comment by mschwager** [comment]
> I knew you would comment matt :)

Hah, that's what I'm here for!

**Comment by DrewDennison** [comment]
more context: https://r2c-community.slack.com/archives/GVB6L4HHC/p1601592049009200

**Comment by aryx** [comment]
Ok I think I've figured it out! Should be able to fix that soon as well as many related import and aliasing issues.

**Comment by aryx** [comment]
This works now on develop: https://semgrep.dev/s/KdNY/?version=develop
