### ISSUE TITLE
CORS accept in python - flask does now find

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1784]
CORS(app, resources={$KEY: {"origins": "*"}})
does not find pattern
https://semgrep.dev/s/8xXg/

**Comment by mschwager** [comment]
Hi @dvyakimov,

You need to specify the full module path of the function call, e.g. include `flask.ext.cors`. See: https://semgrep.dev/s/gpPR/

In fact, we've already noticed this missing in our documentation, so we're going to improve our docs: https://github.com/returntocorp/semgrep/issues/1748
