### ISSUE TITLE
$_GET should not be considered a metavariable in PHP

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#1790]
https://semgrep.dev/s/4BoZ

**Comment by rezen** [comment]
An important note, all variables in PHP are prefixed with `$`. `$_GET` specifically is a **superglobal**. Being able to escape variables will be important with PHP. 

- https://www.php.net/manual/en/language.variables.superglobals.php
- https://www.php.net/manual/en/language.variables.variable.php

**Comment by aryx** [comment]
this now works on develop: https://semgrep.dev/s/Okpb/?version=develop
