### ISSUE TITLE
--test: separate out test and pattern files

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1796]
Allow semgrep yaml files and test files to be in separate directories

**Comment by ajinabraham** [comment]
It would be useful to separate test files and rule files https://github.com/semgrep/rules-nodejsscan/tree/with_tests/rules
especially when packing and updating rules dynamically.

Can we have support for `python -m semgrep --quiet --json --test --rules <rules> --src <source_code>`

**Comment by ievans** [comment]
@colleend We'll need to think about this a bit with the changes we're making to load examples into the registry

**Comment by DrewDennison** [comment]
@ajinabraham yay! Can you please confirm the changes @mschwager made in #2221 work for your needs and if not, please reopen. It should roll out in our release next week.
