### ISSUE TITLE
Parse error on  '!old_scope.key? "type"'

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1819]
Our `jekyll` QA repository recently introduced a commit that broke Ruby parsing.

Relevant CI job: https://github.com/returntocorp/semgrep/pull/1814/checks?check_run_id=1242449418

The QA repository has since been moved to expected failure: https://github.com/returntocorp/semgrep/commit/687a87c23fe226a2b11bce0b2d63348ea35e18a0

I created this issue to track this parsing error. Let's fix the parsing bug and re-enable the QA repository :+1:

**Comment by aryx** [comment]
This now works after https://github.com/returntocorp/semgrep/pull/2060
