### ISSUE TITLE
Runtime stats are not quite accurate

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1825]
**Describe the bug**
Two issues with the number of findings being reported.

(a) When I run semgrep on my entire code base it reports 13 findings but I only count 12:
https://buildkite.com/chef-oss/chef-automate-master-verify/builds/14196#3fb5498f-9a8c-4bab-ba99-95c6b32eb6b8
Expected: 12 findings

(b) I then added a few ignore flags (`//nosem`) and made no other changes. It still reports 13 finding but now I only count 8:
https://buildkite.com/chef-oss/chef-automate-master-verify/builds/14198#300d1713-b7c5-494d-83e4-626d2a496eab
Expected: 8 findings

**To Reproduce**
(1) Download our repo (it is open source): https://github.com/chef/automate
(2) Run semgrep from the repo root:
```
semgrep --config https://semgrep.dev/p/r2c-ci --exclude third_party --exclude *_test.go --exclude *.pb.go
```

**Environment**
semgrep version 0.27.0

Language distribution in my code base:
![image](https://user-images.githubusercontent.com/6817500/95927105-c192fa80-0d72-11eb-91e1-9cbeb75bd21c.png)

**Comment by ievans** [comment]
Thanks for this @msorens and the clear reproduction steps. @brendongo -- I think you'd have the best context here regarding how the target manager works, want to take a look?

**Comment by brendongo** [comment]
This is cause the stat line is computed from semgrep-core invocation and nosem ignores are performed after. IMO we should not be having CoreRunner report stats and instead have output compute them as necessary. https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/semgrep_main.py#L223

**Comment by msorens** [comment]
@brendongo Just wanted to point out that that might not be the entire explanation. Your explanation covers case (b) but not case (a) I should think.

**Comment by brendongo** [comment]
Hmm I think (a) is a problem with our UI

```

/go/src/github.com/chef/automate/components/automate-deployment/pkg/airgap/bundle_creator.go
--
  | severity:warning rule:go.lang.security.decompression_bomb.potential-dos-via-decompression-bomb: Potential DOS via zip bomb attack. You cau use `io.CopyN()` to prevent it. Refer to https://bomb.codes/ to learn more about this attack and other ways to mitigate it.
  | 103:	gzipReader, err := gzip.NewReader(resp.Body)
  | 104:
  | 105:	if err != nil {
  | 106:		return errors.Wrap(err, "Failed to download hab binary. Could not open gzip")
  | 107:	}
  | 108:
  | 109:	tarReader := tar.NewReader(gzipReader)
  | 110:	for {
  | 111:		hdr, err := tarReader.Next()
  | 112:		if err == io.EOF {
  | 113:			break
  | 114:		}
  | 115:
  | 116:		if err != nil {
  | 117:			return errors.Wrap(err, "Failed to unpack archive")
  | 118:		}
  | 119:
  | 120:		if hdr.Typeflag == tar.TypeReg {
  | 121:			if hdr.FileInfo().Name() == "hab" {
  | 122:				_, err := io.Copy(w, tarReader)
  | 123:				if err != nil {
  | 124:					return errors.Wrap(err, "Could not untar hab binary tarball")
  | 125:				}
  | 126:				return nil
  | 127:			}
  | 128:		}
  | 129:	}
  | 109:	tarReader := tar.NewReader(gzipReader)
  | 110:	for {
  | 111:		hdr, err := tarReader.Next()
  | 112:		if err == io.EOF {
  | 113:			break
  | 114:		}
  | 115:
  | 116:		if err != nil {
  | 117:			return errors.Wrap(err, "Failed to unpack archive")
  | 118:		}
  | 119:
  | 120:		if hdr.Typeflag == tar.TypeReg {
  | 121:			if hdr.FileInfo().Name() == "hab" {
  | 122:				_, err := io.Copy(w, tarReader)
  | 123:				if err != nil {
  | 124:					return errors.Wrap(err, "Could not untar hab binary tarball")
  | 125:				}
  | 126:				return nil
  | 127:			}
  | 128:		}
  | 129:	}
```

There are actually two findings here but the UI doesn't clearly separate them

**Comment by brendongo** [comment]
Opened https://github.com/returntocorp/semgrep/issues/1866 to track the UI ugliness and we can use this ticket to track fixing the nosem not being reflected on stats
