### ISSUE TITLE
[Java] Match only function signatures or class header

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#1827]
**Is your feature request related to a problem? Please describe.**

Changes were made to PFFF to resolve https://github.com/returntocorp/semgrep/issues/1756.
In Slack Yoann mentioned
> I now need to allow this for other languages, and to allow to match class header, not just function header

This GH issue is to track that progress.

For example in Java I want to write rules that match annotations and report the class name and method name and parameters but not the method's body.

Currently, in Semgrep 0.27.0, the pattern must end in `{ ... }` to be a valid rule (a complete Java statement). This causes semgrep to output the method's body as it is part of the match.

**Describe the solution you'd like**
Rules that can match just the  class/method, ignoring the body - explicitly just outputting something like `className.methodName(type param1)`.

**Describe alternatives you've considered**
Rules that match method body `{ ... }`, and then getting far more output than desired.

**Additional context**
https://r2c-community.slack.com/archives/CK86BJ5DW/p1601648328110700?thread_ts=1601470717.076100&cid=CK86BJ5DW

**Comment by dlukeomalley** [comment]
Thanks for filing this issue @ben-elttam - adding some tags so we can triage and track moving forward. CC @aryx @DrewDennison
