### ISSUE TITLE
Flag to set acceptable rule level for non-zero exit code

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1833]
**Is your feature request related to a problem? Please describe.**
Semgrep rules have a level field that can be Warning or Error or Info it would be nice if there was a way to tell semgrep to only have a non-zero exit code for errors for example.

**Describe the solution you'd like**
Something like `semgrep --error-level=WARNING`

**Comment by aryx** [comment]
My only concern is that using the word error and warning together seems counterintuitive (in --error-level=WARNING).
Maybe --fail-level=WARNING?
We overload a bit the term "error", same with --error, when really it's about an exit return code to make CI fail.

**Comment by aryx** [comment]
nobody else asked for it ... closing.
