### ISSUE TITLE
Support more expressive paths syntax

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#1834]
**Is your feature request related to a problem? Please describe.**
Semgrep supports path include/exclude with the Python glob syntax.
https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#paths
The examples given in the doc are 
```
- "*.jinja2"
- "*_test.go"
- "project/tests"
- project/static/*.js
```
There is no way to specify something like js files in all subdirectories of `project/static`.

**Describe the solution you'd like**
One potential solution is using regex as the pattern (`project/static/.*[.]js$`).

**Describe alternatives you've considered**
Not sure how useful in general, other ideas are
* support anding the paths (`project/static` and `*.js`)
* syntax to match arbitrary level of directories (`project/static/**/*.js`)

**Comment by aryx** [comment]
I like **/*.js, it's in many shells now.

**Comment by underyx** [comment]
Hey @Isaac0616, we're trying to decide where to place this on our roadmap. Could you give us some idea of how important this feature would be for you?

**Comment by Isaac0616** [comment]
There are not a lot (`dir/` and `*.ext` cover most cases), but I encountered several times during migrating some rules we used to use regex to include/exclude files.
Not super urgent, but it helps reduce false positives.

**Comment by karoun** [comment]
This seems pretty important, since otherwise there's no easy way (that I can tell) to specify "file of type within subdirectory" without using `*`s for every possible file depth.

```yaml
# What I want
- "foo/**/*.txt"

# What I can do
- "foo/*.txt"
- "foo/*/*.txt"
- "foo/*/*/*.txt"
```

**Comment by clintgibler** [comment]
I also think that being able to do `**` in path inclusions/exclusions would be quite useful 👍

**Comment by fproulx-boostsecurity** [comment]
👍 👍 👍 on this, this is super useful to exclude any findings in says `**/migrations/*` for `typescript`
