### ISSUE TITLE
[typescript] Class properties/declarations not recognized

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1846]
**Describe the bug**
In this sample (https://semgrep.dev/s/P9oE/) observe that only line 10 is matched, when it should also include line 5:
![image](https://user-images.githubusercontent.com/6817500/96213243-60635680-0f2d-11eb-9dd4-a810a2a8501f.png)

If I modify the rule to look for the _expression_ rather than the full _declaration_, then it does match line 5 as well:
![image](https://user-images.githubusercontent.com/6817500/96213236-580b1b80-0f2d-11eb-8974-5768ca38b858.png)

**To Reproduce**
https://semgrep.dev/s/P9oE/

**Expected behavior**
Should be able to match class declarations.

**Environment**
Version 0.27.0

(Priority for me: nice to have but not urgent)

**Comment by dlukeomalley** [comment]
@aryx @mschwager @DrewDennison Added some labels, do you feel this is a bug or enhancement?

**Comment by mschwager** [comment]
This looks like a bug to me. Unless I'm misunderstanding something about JS/TS, both lines are assignments, so I would expect the `$VAR =` pattern to catch both.

**Comment by aryx** [comment]
What is this construct? It's an assignment in the middle of class definition? In JS you can have properties, methods, what is this construct? and what is this variable with a $ at the end?

**Comment by aryx** [comment]
If you use the "Dump AST" you can see one possible reason. This thing is parsed as a FieldDef, but
your pattern is assignment. We do some special thing to allow x = a; to match declaration like int x = a; in some languages but we don't do it here for JS/TS, I think because people didn't want that sometimes.
We can revise that back.

**Comment by msorens** [comment]
@aryx 

> What is this construct?

 The construct is defining a property of the class.

> what is this variable with a $ at the end?

The dollar sign at the end is not significant at all for your purposes; just a [Finnish naming convention](https://medium.com/@benlesh/observables-and-finnish-notation-df8356ed1c9b) for Observables.

**Comment by aryx** [comment]
works on ?develop now.

**Comment by msorens** [comment]
Just tested the same sandbox above (semgrep.dev/s/P9oE) and the behavior is unchanged; still not finding the first occurrence.

**Comment by aryx** [comment]
works on develop https://semgrep.dev/s/P9oE?version=develop
Should be in the next release.
