### ISSUE TITLE
Return "value propagation" in JSON output

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1849]
Building on our [constant propagation](https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#constants), it would be useful to also return the value the constant holds.

Consider the following rule and code:

```yaml
rules:
- id: value-propagation
  message: Test value propagation
  severity: ERROR
  languages: [python]
  pattern: print($X)
```

```python
CONST = 42

def func():
    print(CONST)
```

Running with `--json` gives the following output:

```
$ python -m semgrep --config /tmp/test.yaml /tmp/test.py --json | python -m json.tool
running 1 rules...
ran 1 rules on 1 files: 1 findings
{
    "results": [
        {
            "check_id": "tmp.value-propagation",
            "path": "/tmp/test.py",
            "start": {
                "line": 4,
                "col": 5
            },
            "end": {
                "line": 4,
                "col": 17
            },
            "extra": {
                "message": "Test value propagation",
                "metavars": {
                    "$X": {
                        "start": {
                            "line": 4,
                            "col": 11,
                            "offset": 34
                        },
                        "end": {
                            "line": 4,
                            "col": 16,
                            "offset": 39
                        },
                        "abstract_content": "CONST",
                        "unique_id": {
                            "type": "id",
                            "value": "CONST",
                            "kind": "Global",
                            "sid": 1
                        }
                    }
                },
                "metadata": {},
                "severity": "ERROR",
                "lines": "    print(CONST)"
            }
        }
    ],
    "errors": []
}
```

The `abstract_content` key tells us the literal code token in the metavariable. It'd be very useful to also receive the value of that token if constant propagation occurred. In this case, something like `"abstract_value": 42`. I can see both the code token and its value being useful to the caller, so we'll likely want a new key in the output.

This will be useful for things like `metavariable-regex`, `metavariable-comparison`, and other applications that build on the JSON output of Semgrep.

**Comment by aryx** [comment]
abstract_content does not contain the code token :) it contains the name of the expression, here the constant named 'CONST'

**Comment by aryx** [comment]
if you do print (($X : int_literal)) maybe you will get the right value in $X.

**Comment by IagoAbal** [comment]
Is this issue still relevant once we are planning to handle rules inside semgrep-core?

**Comment by aryx** [comment]
Well we still need to handle that correctly in semgrep-core, to modify how we do metavariable-regex, and metavariable-comparison to possibly use the propagated constant.

**Comment by aryx** [comment]
Also at some point we may need to modify how we report a match for a pattern because we may also want to indicate not only the match but also the point where the constant was defined, so the user can better understand why we thing this match let's say foo(42).

**Comment by mschwager** [comment]
> Is this issue still relevant once we are planning to handle rules inside semgrep-core?

I believe so. This feature request is most relevant for downstream applications building on, for example, Semgrep's JSON output, not for use within Semgrep itself. For example, let's say you're aggregating an application's HTTP routes:

```python
UPLOAD_PATH = "/api/upload"

@route(UPLOAD_PATH, "POST")
def upload(request):
    ...
```

And your pattern is something like `@route($PATH, $VERB)`. Perhaps you're trying to do some analysis on routes, and it would be useful to gather their path and verb information. This example is a bit contrived, but it gives some rough motivation.

> This will be useful for things like `metavariable-regex`, `metavariable-comparison`, and other applications that build on the JSON output of Semgrep.

As these operators have developed, I think the requested functionality will be less useful for operators like `metavariable-regex` and `metavariable-comparison`, and will be most valuable for downstream applications :+1:

**Comment by clintgibler** [comment]
I was just talking with a paying customer today who wanted this functionality. Not saying that this is a high priority issue that should be done ASAP, just as a +1 to the value of this. I'd also like this functionality personally.

Agree with @aryx, probably we'd want to return the name of the variable in addition to its value. Maybe something like `abstract_content` and `abstract_value`? 🤷 

From the user:

> It can be difficult to know when constant propagation has occurred vs an unmatched expression generating a match by itself. It would be good to get some kind of strong affirmation that constant propagation was driving the match.

**Comment by nbrahms** [comment]
> I was just talking with a paying customer today who wanted this functionality. Not saying that this is a high priority issue that should be done ASAP, just as a +1 to the value of this. I'd also like this functionality personally.
> 
> Agree with @aryx, probably we'd want to return the name of the variable in addition to its value. Maybe something like `abstract_content` and `abstract_value`? 🤷
> 
> From the user:
> 
> > It can be difficult to know when constant propagation has occurred vs an unmatched expression generating a match by itself. It would be good to get some kind of strong affirmation that constant propagation was driving the match.

@clintgibler I don't think this ticket and the user request are related? Constant propagation isn't driving the match here. It would if the pattern were `print(42)`.

**Comment by IagoAbal** [comment]
We need to decide on a priority for this and maybe add it to Q4 plan if needed.
