### ISSUE TITLE
[typescript] Support for "implements" keyword is incomplete

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1850]
**Describe the bug**
This sample (https://semgrep.dev/s/Jq0Z/) illustrates that #1753 (Support matching on "implements") is incomplete. The red X cases are incorrect.

**Additional Info**

**To Reproduce**
https://semgrep.dev/s/Jq0Z/

**Expected behavior**
Multiple implemented interfaces must be supported.

**Screenshots**
<img width="242" alt="image" src="https://user-images.githubusercontent.com/6817500/96286394-275ecc80-0f95-11eb-894c-aac1a83d2210.png">

**Environment**
Semgrep 0.27.0

(Priority for me: somewhat important)

**Comment by DrewDennison** [comment]
@aryx this seems to be a matching / type bug. Tagging you for an investigation

**Comment by aryx** [comment]
This works on develop: https://semgrep.dev/s/Jq0Z/?version=develop
Should be in 0.28 that we release today.
