### ISSUE TITLE
Internal error matching conditionals when empty

### ISSUE THREAD

**Issue by vortfu** [semgrep/semgrep#1856]
semgrep fails with an internal error when using a pattern of `if ( $X ) $Y;` if the PHP code being scanned contains an empty conditional, e.g.

```
(semgrep) bash-3.2$ cat semgrep-parse-error-007.php
<?php

if ( true ) {
	// intentionally left blank
}

(semgrep) bash-3.2$ semgrep-core -version
semgrep-core version: v0.27.0-78-gb909212, pfff: 0.42

(semgrep) bash-3.2$ semgrep --version
0.27.0

(semgrep) bash-3.2$ semgrep -l php -e 'if ( $X ) $Y;' semgrep-parse-error-007.php 
an internal error occured while invoking semgrep-core:
	unknown exception: (Failure
  "NoTokenLocation Match returned an empty list with no token location information; this may be fixed by adding enclosing token information (e.g. bracket or parend tokens) to the list's enclosing node type. exn while processing semgrep-parse-error-007.php for rule 0.-, with metavar $Y, close location = {\"line\":3,\"col\":1,\"offset\":7}")
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
```

**Comment by sabrinabrogren** [comment]
Hello @vortfu, thank you for the detailed issue! I’m going to move this to our backlog for now since PHP is still in alpha, and we’re focusing on solidifying Ruby and Typescript before moving forward. Please let us know if this issue is blocking for you, and we can chat about a fix or workaround!

**Comment by mschwager** [comment]
Looks like we're still seeing this: https://semgrep.dev/s/weKN/

**Comment by ievans** [comment]
Still an issue in 0.38

**Comment by emjin** [comment]
It parses on develop! I'm not sure if this is meant to match or not @ievans @aryx, though we should probably open a separate issue. (It matches in other languages too)

**Comment by aryx** [comment]
Yep I think your recent fix emma on ast_php.ml fixes that.
Closing :)

**Comment by aryx** [comment]
works on develop: https://semgrep.dev/s/weKN/?version=develop
Should be in the next release.
