### ISSUE TITLE
Finish integrating spacegrep

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1858]
- [x] Ensure binary is available in all installation mediums
- [x] Integrate off-by-one fixes
- [x] Get spacegrep/spacecat to under 100MB

**Comment by minusworld** [comment]
<strike>https://github.com/returntocorp/semgrep/pull/1853</strike>

and

<strike>https://github.com/returntocorp/semgrep/pull/1848</strike>

**Comment by underyx** [comment]
@minusworld could you track fixing/working around https://github.com/returntocorp/semgrep/pull/1862/commits/e5670ed176e18a6927fea85d2a82212b5d272806 as part of this?

**Comment by minusworld** [comment]
If we run `strip` on `spacecat` and `spacegrep`, we can shave off 1MB. 🤷‍♂️

**Comment by brendongo** [comment]
Fyi: https://github.com/returntocorp/semgrep/issues/1864#issuecomment-714722346 we might be able to increase our pypi limit.

**Comment by minusworld** [comment]
I'm calling this closed since it is working in 0.29.
