### ISSUE TITLE
Confusing output when multiple findings in same file

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1866]
**Describe the bug**
When semgrep finds multiple findings of the same rule on the same file it outputs them without clear delineation between the findings.

This has led to some confusion: https://github.com/returntocorp/semgrep/issues/1825#issuecomment-713722239

**To Reproduce**
Run any semgrep rule the fires twice on a file

**Expected behavior**
At least include whitespace between the findings or even reprint the rule and message header.

**Comment by dlukeomalley** [comment]
Closing in favor of https://github.com/returntocorp/semgrep/issues/1990
