### ISSUE TITLE
TS Parsing failing on juice-shop

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1867]
**Describe the bug**
typescript is failing on juice-shop

https://github.com/returntocorp/semgrep/pull/1806/checks?check_run_id=1232600832
ERROR message: Could not parse index.d.ts as ts
Semgrep.dev example: https://semgrep.dev/s/nezO/

'https://github.com/bkimminich/juice-shop
ERROR message: Could not parse user.service.ts as ts
Semgrep.dev example: https://semgrep.dev/s/ErEA/

**To Reproduce**
The following PR resulted in testing TS in QA repositories. https://github.com/returntocorp/semgrep/pull/1806/checks?check_run_id=1232600832 is available for more detail. 

**Expected behavior**

**What is the priority of the bug to you?**
P1 -- will be adding this to xfail repositories.

**Comment by mjambon** [comment]
This issue needs to be split into two since there are two different errors.

**Comment by mjambon** [comment]
We should not try parse the `.d.ts` files since our parser doesn't support them and they're only type definitions, which are of little to no interest for semgrep users. I don't know if scanning was fixed to exclude those files.

**Comment by mjambon** [comment]
The other error is this:
![image](https://user-images.githubusercontent.com/343265/121582955-853c9a80-c9e4-11eb-8977-ea6f34374e6c.png)

I'll check this when the typescript upgrade everyone is waiting for is ready.

**Comment by colleend** [comment]
I can split this issue into two 👍 . 

Here are the two new issues:
https://github.com/returntocorp/semgrep/issues/3335
https://github.com/returntocorp/semgrep/issues/3336

**Comment by milanwilliams** [comment]
Closing this issue, as it's covered by the above two new issues.
