### ISSUE TITLE
Can't use ellipsis after import in Java

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1873]
Example: https://semgrep.dev/s/D8Lj?version=develop

**Comment by aryx** [comment]
@colleend want to have a look?

**Comment by ben-elttam** [comment]
From my digging (in semgrep.live) this is what I have noticed in terms of behaviour.

If pattern is `import spark.Spark;` then dumping the pastern AST there is one.

<details><summary>Pattern AST</summary>

```json
{
  "import spark.Spark;\n": {
    "S": {
      "DirectiveStmt": {
        "ImportFrom": [
          "()",
          {
            "DottedName": [
              [
                "spark",
                "()"
              ]
            ]
          },
          [
            "Spark",
            "()"
          ],
          null
        ]
      }
    }
  }
}
```

</details>


But if pattern is

```
import spark.Spark;
...
```

Then the pattern AST is `{}` (an empty object). I'd expect the AST to be similar to the above but with some ellipse in addition.

<details><summary>Ellipse AST</summary>

```json
{
  "...\n": {
    "E": {
      "Ellipsis": "()"
    }
  }
}
```

</details>

**Comment by aryx** [comment]
This now works on develop: https://semgrep.dev/s/D8Lj?version=develop
