### ISSUE TITLE
Add support for `--message` and maybe also --fix

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#1885]
**Is your feature request related to a problem? Please describe.**

I want to be able to run `semgrep --e '$X'  --message '$X is a expression'`

**Comment by DrewDennison** [comment]
cc @daghan

**Comment by dlukeomalley** [comment]
@DrewDennison @daghan Thanks for filing this feature request! I wanted to learn a little more about your workflow to scope the feature. Where and when do you find yourself reaching for Semgrep and desiring a `--message` argument? Thank you! :)

**Comment by aryx** [comment]
Note that many people "abuse" the message to display code information and explore a codebase (especially ben on r2c-community), so I could see a use case for them.
they just want to display for example all the class in a project and use a pattern like -e 'class $A { ... }' --message 'found class $A'

**Comment by aryx** [comment]
Of course they can define the same via a local rule file in yaml, but the -e --message is shorter.

**Comment by DrewDennison** [comment]
@aryx yep it's exactly what you described so `-e` works and now `-msg` + `-json` allows for using semgrep as a tool to pipe to other tools without needing to break out yaml

**Comment by aryx** [comment]
We could also support -fix as mentioned in #840 ?

**Comment by aryx** [comment]
@mschwager just added a feature to generate a template from a pattern #2562 so this should be good enough.
