### ISSUE TITLE
Update Performance Baseline

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#1886]
**Is your feature request related to a problem? Please describe.**
We are now parsing and scanning ts files, which leads to 10% increase in semgrep 0.17.0 baseline performance. 

**Describe the solution you'd like**
We should update the baseline performance to be 0.29.0 and change the allowed deviation back to 5% once 0.29.0 is released.

**Comment by aryx** [comment]
This is high-pri because all our CI tests are red because of the perftests failure.

**Comment by aryx** [comment]
@brendongo could you fix it or find the person responsible for this CI test.
It's causing all our PRs to be red :+1:

**Comment by colleend** [comment]
I can try to tackle this! Might not push it until next week though (due to code freeze)
