### ISSUE TITLE
nosem behavior in Python

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#1888]
**Describe the bug**
`// nosem` in Python appears to work to disable semgrep on a line.

**To Reproduce**
https://dev.semgrep.dev/s/3eWg/

**Expected behavior**
The line should still be flagged.

**What is the priority of the bug to you?**
P2 (regular bug that should get fixed)

**Comment by aryx** [comment]
Python use #, not //
https://dev.semgrep.dev/s/4B0g/

**Comment by aryx** [comment]
🤦

**Comment by aryx** [comment]
https://gph.is/g/Zdb5AgD

**Comment by aryx** [comment]
How do I include gifhy directly in github? Github forbids gifs?

**Comment by sabrinabrogren** [comment]
I'm confused, shouldn't it give a parse error because I used `//` instead of `#`?

**Comment by sabrinabrogren** [comment]
Oh wait no, `//` is a thing in Python, it does floor division. So it shouldn't be a parse error, but it shouldn't ignore the finding like it does in the example. I'll edit the ticket...

**Comment by sabrinabrogren** [comment]
https://dev.semgrep.dev/s/P9LN/ Another interesting example. Is it intentional that you just can't use the string `nosem` or it'll disable semgrep?

**Comment by brendongo** [comment]
@aryx https://dev.semgrep.dev/s/5WK6/ doesn't run in python but we parse it without issue somehow :D

**Comment by brendongo** [comment]
Nvm see // floor division above
