### ISSUE TITLE
Matching multiple imports in Go

### ISSUE THREAD

**Issue by bflad** [semgrep/semgrep#1897]
## Description

It does not seem possible to match multiple imports in Go. For example, we want to report if a Go source file contains multiple imports matching certain patterns.

Example: https://semgrep.dev/s/D8nj?version=develop

```go
package main

import (
  "a"
  "b"
)

func main() {}
```

## Attempted Patterns

Pattern could not be parsed as a Golang semgrep pattern:

```
import (
  "a"
  ...
  "b"
)
```

No matches:

```
import (
  "a"
  "b"
)
```

No matches:

```
import ("a")
...
import ("b")
```

No matches:

```
import ("a")
import ("b")
```

No matches:

```
import "a"
...
import "b"
```

No matches:

```
import "a"
import "b"
```

This pattern:

```
import "b"
```

Matches all of these lines (not just `"b"` line):

```
import (
  "a"
  "b"
```

**Comment by ievans** [comment]
Hi @bflad thanks for sharing the full progression of things you tried, that's quite helpful feedback for us...though I imagine frustrating for you.

The answer here involves promoting from the single semgrep pattern to combining two patterns, though we could certainly change the Semgrep pattern syntax and I'd be happy to discuss. But to verify what I think is the solution, does https://semgrep.dev/s/WenA do what you want?

**Comment by bflad** [comment]
Hi @ievans 👋  Thank you for the very quick response! Interesting, I wouldn't have thought to try `pattern-inside` there. It seems to work in the simple reproduction case with hardcoded import paths.  

For the real world case, some additional context might be helpful -- we are looking to check multiple imports matching a prefixed pattern with a lot of potential combinations (https://github.com/aws/aws-sdk-go/tree/master/service). Trying to match via regular expressions doesn't appear to work as expected in that case (https://semgrep.dev/s/Kdnd/) or in general (https://semgrep.dev/s/4Bqx/) . Happy to file as a separate feature request though. 👍 

Thanks again for the initial help!

**Comment by ievans** [comment]
Yes, that's indeed a bug--regex ought to work in the imports. https://semgrep.dev/s/P9np cc @aryx thoughts?

If you want to work around it, there's an alternative syntax for regex that ought to work--`metavariable-regex`. Here's a javascript example of a similar concept that illustrates the use : https://semgrep.dev/s/rx46

Having to break out that extra syntax is a little uglier than it should be though, so we should just fix this.

**Comment by dlukeomalley** [comment]
@bflad @ievans Thank you for the discussion and debugging. Tickets for the regex issues would be much appreciated.

With those filed, is it appropriate to close this issue given the `metavariable-regex` suggestion and/or the rule strategy @ievans provided?

**Comment by bflad** [comment]
Sorry for the slow response, `metavariable-regex` wasn't working with multiple imports in Go when I briefly tried it the other night. I'll circle back to providing a link that shows that later today and filing the regular expression issue.

**Comment by bflad** [comment]
Okay after retrying this today, it is working with `metavariable-regex` in the below example. 👍 Adding an ellipsis between the import statements causes significant processing delays in my real world testing, but we enforce import ordering via other means so not a concern for us.

```go
package main

import (
  "fmt"

  "github.com/aws/aws-sdk-go/service/accessanalyzer"
  "github.com/aws/aws-sdk-go/service/acm"
)

func main() {
  fmt.Println("hello world")
}
```

```yaml
  patterns:
    - pattern: |
        import ("$X")
        import ("$Y")
    - metavariable-regex:
        metavariable: '$X'
        regex: '"github.com/aws/aws-sdk-go/service/[^/]+"'
    - metavariable-regex:
        metavariable: '$Y'
        regex: '"github.com/aws/aws-sdk-go/service/[^/]+"'
```

I'll close this out as there is a workaround for my situation. Thank you for all your help.

**Comment by aryx** [comment]
the regexp in import now works thx to https://github.com/returntocorp/semgrep/pull/2017
