### ISSUE TITLE
Can't find dangerouslySetInnerHTML in React

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1900]
Still have a question about how can i find some text in JSX.

Last ticket: #1791 

How can i write some regexp to find JSON.stringify in dangerouslySetInnerHTML?
https://semgrep.dev/s/Jqnj

**Comment by dlukeomalley** [comment]
@dvyakimov I gave this a go using `pattern-inside` to find `<script>` tags that use `dangerouslySetInnnerHTML` AND contain `JSON.stringify`. Does this look like what you want to match? 

https://semgrep.dev/s/pGO0/
