### ISSUE TITLE
Update semgrep-agent in Python Package Index with release cadence

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1909]
**Is your feature request related to a problem? Please describe.**
I want to use semgrep-agent via the Python Package Index (https://pypi.org/) (rather than your docker image) for my CI purposes. The reason is so that I can properly pass in the token secret.

**Describe the solution you'd like**
Need the semgrep-agent package kept up to date.

**Comment by DrewDennison** [comment]
hey @msorens is this still needed for you? If so, would you mind letting me know your prioritization? 🙏

**Comment by msorens** [comment]
Since I resolved issues with using the recommended channel (the semgrep-agent docker image) I no longer need this. Thanks for checking!

**Comment by DrewDennison** [comment]
awesome, thanks for the update
