### ISSUE TITLE
Semgrep with multiple configs only uses the last one.

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#1912]
**Describe the bug**
Semgrep with multiple configs only uses the last one.

**Screenshots**
![image](https://user-images.githubusercontent.com/2374948/97504723-b0cab300-1934-11eb-947a-3519c5e738a6.png)

**What is the priority of the bug to you?**
P2

**Environment**
pip install, v0.29.0

**Comment by dlukeomalley** [comment]
Thank you @minusworld for filing the ticket. I tested locally with v0.29.0 and it does look like this is an issue. 

To reproduce I:
1. Created `bad.py` and `bad.go` with issues `p/python` and `p/gosec` would find. 
2. I ran `p/python` and `p/gosec` individually on my codebase and confirmed that both found issues in their respective languages
3. I ran with both rulesets and confirmed that only the last ruleset ran.
4. I tried variations of the command as well:

```sh
semgrep --config p/python --config p/gosec
semgrep --config p/python p/gosec
```
