### ISSUE TITLE
Equivalences cause Java parse errors

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#1919]
https://semgrep.dev/s/l0OG?version=develop

Error with rule with `equivalences` feature:

```
semgrep -f crossorigin.yml  --verbose --debug  crossorigin.java
loaded 1 configs in 0.08496356010437012
running 1 rules from 1 config crossorigin.yml
running 1 rules...
Running rule rest-CrossOrigin...

...ran on 1 files
semgrep ran in 0:00:00.112049 on 1 files
findings summary: 0 warning
semgrep warn: parse error
  --> crossorigin.java:1
1 | @RestController
  |
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse crossorigin.java as java

ran 1 rules on 1 files: 0 findings
1 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

If `equivalences` feature is commented out, or removed, then the parse error on the java file goes away. It seems the error is a bit of a red herring as it is complaining about the java source, but modifying the rule (`.yml`) makes the difference.

I know the feature is experimental, hopefully this bug report helps.

**Comment by underyx** [comment]
Thanks for the report! We have filed it in our backlog for when we shift our focus to experimental features 🙌

**Comment by dlukeomalley** [comment]
> I know the feature is experimental, hopefully this bug report helps.

Always, thank you @ben-elttam and thank you @underyx. I've added a few labels for tracking.

**Comment by dlukeomalley** [comment]
Closing this ticket as the `equivalences` key was deprecated in 0.61.0.
