### ISSUE TITLE
Error in CLI version, but not Web version

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#1920]
I have a working rule in web version:
https://semgrep.dev/s/6WRL

But at same time error in CLI version:
<img width="585" alt="Снимок экрана 2020-10-29 в 13 06 30" src="https://user-images.githubusercontent.com/34271513/97554265-90a7fc00-19e7-11eb-8f40-ae6d114964ed.png">
0.29.0 version

**Comment by underyx** [comment]
<img width="482" alt="Screenshot 2020-10-29 at 11 23 35" src="https://user-images.githubusercontent.com/1060436/97556039-3011c280-19d9-11eb-80ff-9290dac607a0.png">

Could you share a screenshot of this working on the web UI? I see the above error on your link, which is the same as the CLI returns.

**Comment by dvyakimov** [comment]
Sorry. You are right 👍 
Previously, an error in the rules was highlighted with a red rim.

**Comment by underyx** [comment]
Yes, thanks to your report I've filed an internal bug report to fix the error highlighting on the website! That really is an issue.
