### ISSUE TITLE
Ellipsis operator parse error in C member assignment

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#1923]
I would expect something like `$VAR->$MEMBER = ...;` to work in C:

https://semgrep.dev/s/X2K4/

**Comment by ben-elttam** [comment]
Similarly ellipse operator `...` doesn't work for matching arbitrary RHS of assignment https://semgrep.dev/s/y6wR. Intended behaviour achieved via `pattern-regex` https://semgrep.dev/s/4PQ5.

**Comment by aryx** [comment]
Adding it to parser_cpp.mly is tricky, so probably easier to start to use tree-sitter-cpp instead
and add it to semgrep-cpp/grammar.js in ocaml-tree-sitter.
