### ISSUE TITLE
Semgrep Core sets file as "NO FILE INFO YET" when failing to parse C code

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#1925]
**Describe the bug**
When running on invalid C code semgrep is unable to parse semgrep-core output. It assumes that 
the path field in a LexicalError is a path to a file but instead it is the string "NO FILE INFO YET"

**To Reproduce**
Locally run `semgrep --config s/eryd` on the following target:

foo.c
```
# this is invalid code
int x = 1
```

**Expected behavior**
Should report as a parseerror

**Comment by mschwager** [comment]
See our other `NO FILE INFO YET` issues too:

- https://github.com/returntocorp/semgrep/issues/1817
- https://github.com/returntocorp/semgrep/issues/1412
- https://github.com/returntocorp/semgrep/issues/275

We should at least return a more helpful error - something that the user can use to fix the problem or take additional action.

**Comment by aryx** [comment]
Note that the code is invalid in your example because you use python style comment # xxx on a C file.
It causes a lexical error (not a parse error), which causes then the No File info Yet.

**Comment by mschwager** [comment]
@aryx Can we output something more descriptive than `NO FILE INFO YET`? That would be very helpful for debugging.

EDIT: Looking at https://github.com/returntocorp/semgrep/commit/a288fcc4a85cd2dc453c37248ca67299f8111cde more closely, it looks like we shouldn't get `NO FILE INFO YET` anymore?

**Comment by aryx** [comment]
Ok but what? I can put "Bug in lexer, you forgot the call to complete_parse_info somewhere"

**Comment by mschwager** [comment]
> Ok but what? I can put "Bug in lexer, you forgot the call to complete_parse_info somewhere"

I think the problem is that we're putting `NO FILE INFO YET` in the output `path` key. Then, when the Python code tries to use `path`, it blows up because this file doesn't exist. E.g.

```c
# this is invalid code
int x = 1
```

```
$ python -m semgrep --pattern '$X == $X' --lang c /tmp/test.c 
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
...
FileNotFoundError: [Errno 2] No such file or directory: 'NO FILE INFO YET'
```

The `semgrep-core` output is:

```
ipdb> pp output_json
{'errors': [{'check_id': 'LexicalError',
             'end': {'col': 1, 'line': -1},
             'extra': {'line': 'NO LINE',
                       'message': 'Lexical error: unrecognised symbol, in '
                                  'token rule:#'},
             'path': 'NO FILE INFO YET',
             'start': {'col': 0, 'line': -1}}],
 'matches': [],
 'stats': {'errorfiles': 1, 'okfiles': 0}}
```

Notice `'path': 'NO FILE INFO YET'` - this makes the Python code blow up because it assumes `path` is an existing file. Shouldn't `semgrep-core` know that the `path` is `/tmp/test.c` here?

**Comment by mschwager** [comment]
https://github.com/returntocorp/semgrep/pull/1999!
