### ISSUE TITLE
[Semgrep Editor] Adding a generic HTTP servlet code to the existing sample java code

### ISSUE THREAD

**Issue by bobby-lin** [semgrep/semgrep#1933]
**Is your feature request related to a problem? Please describe.**
Currently, I have to search code sample on HTTP servlet when I am writing a new rule from scratch in Semgrep editor.

**Describe the solution you'd like**
Add a generic HTTP servlet code to the existing sample java code. This will be useful for writing a rule that involves the request and response.

**Comment by dlukeomalley** [comment]
Thank you for filing this @bobby-lin! Do you have an HTTP servlet snippet that would be a good fit?
