### ISSUE TITLE
Homebrew Error

### ISSUE THREAD

**Issue by evandrix** [semgrep/semgrep#1942]
**Describe the bug**

> Error: Failed to import: /usr/local/Homebrew/Library/Taps/returntocorp/homebrew-semgrep/HomebrewFormula/semgrep.rb
> semgrep: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
> Please report this issue to the returntocorp/semgrep tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
>   /usr/local/Homebrew/Library/Taps/returntocorp/homebrew-semgrep/HomebrewFormula/semgrep.rb:17

**To Reproduce**
`brew update && brew upgrade && brew cleanup`

**Expected behavior**
successfully install without reporting any errors/warnings

**Screenshots**
N.A.

**What is the priority of the bug to you?**
P0

**Environment**

- OS: 64bit Mac OS X 10.15.7 19H2
- `brew --version`

> Homebrew 2.5.8
> Homebrew/homebrew-core (git revision 38af0; last commit 2020-11-01)
> Homebrew/homebrew-cask (git revision a4f6174; last commit 2020-11-01)

**Comment by dlukeomalley** [comment]
Thanks for filing this issue @evandrix. I'll chat with the team first thing Monday about it and circle back with an update for you.

@brendongo @underyx Tagging you two for awareness, I think you have the most expertise here.

**Comment by brendongo** [comment]
Hi I think you possibly installed a develop version of semgrep in the past with `--devel` but brew has recently deprecated that option. You can likely fix this by running `brew uninstall semgrep && brew install semgrep`

**Comment by nbrahms** [comment]
Hi @evandrix,

Can you confirm if the proposed fix above works for you?

Much thanks

**Comment by evandrix** [comment]
oh yes, it works! thanks
