### ISSUE TITLE
Semicolon matching and autofix

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1948]
**Describe the bug**
This is, I believe, just a usability issue. 

As shown there is a double-semicolon in the autofix output (4).
That occurs because my `pattern` (1) is including a semicolon so I naturally included a semicolon in the `fix` (2) as well.
But now look at what was matched (3) -- it does not include the semicolon! Since the match did not include it, the double semicolon stems from the unmatched semicolon that is still there, not being replaced, plus the semicolon in the fix.

And that brings us to should the semicolon be removed from the fix (3)? At first glance, it is "obviously yes". But then there is a consistency problem. If I remove the semicolon from the pattern the code does not even parse! So if the semicolon is required in the pattern it is hard to make an argument that it must not be included in the fix.

The workaround for this, of course, is:

**statement terminators/separators should be omitted from the fix _at the boundaries_** 

Is that really what you wanted or expected?

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/6817500/97812440-36e94100-1c36-11eb-8782-b823c47117a2.png">

**To Reproduce**
https://semgrep.dev/s/6WXK/

Note: This sample actually contains 3 bugs; filing separately.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
P2

**Environment**
semgrep 0.29.0

**Comment by mschwager** [comment]
Hi @msorens,

I agree, this seems odd. cc @aryx if the semi-colon is included in the pattern shouldn't it be matched in the code? E.g. https://semgrep.dev/s/OkXL/ shouldn't we match all of `foo(5);` instead of just `foo(5)`?

**Comment by aryx** [comment]
Thx @mschwager for simplifying the problem. Indeed, the issue is that because of the ASI (automatic semicolon insertion)
done in JS/TS, when we parse a pattern like 'foo(...);' we are not sure if the user originally wanted to
write the expression pattern 'foo(...)' or the exrp-statement pattern 'foo(...);', and right now we were just assuming the first and removing the semicolon from the pattern. I can fix that.

**Comment by aryx** [comment]
The other issue is that the generic AST didn't store certain semicolons in the AST such as the one for return/break/continue.
I can fix that too. After that the code above should match the right range, and the autofix should work better because we would delete the right range of text.

**Comment by aryx** [comment]
Works now correctly on develop: https://semgrep.dev/s/6WXK/?version=develop
