### ISSUE TITLE
[Javascript] support export-default-from JS extension

### ISSUE THREAD

**Issue by chgg-kboberg** [semgrep/semgrep#1950]
**Describe the bug**
Semgrep fails to parse Javascript when file contents are a single "export" statement:

`export default from './SomeComponent';`

**To Reproduce**
https://semgrep.dev/s/2Lor

**Expected behavior**
This is valid Javascript and should parse.

**Screenshots**
N/A

**What is the priority of the bug to you?**
P2.  This is a "warn" semgrep error that is not exposed in normal operation and not scanning a single-line file is not impactful.

**Environment**
Discovered using official binary locally, reproduces in semgrep.dev.

**Comment by aryx** [comment]
Seems to be a Javascript extension.
https://github.com/tc39/proposal-export-default-from

**Comment by aryx** [comment]
Is this feature supported by most browsers and by nodejs?

**Comment by aryx** [comment]
Tracked here now: https://github.com/tree-sitter/tree-sitter-javascript/issues/154

**Comment by mjambon** [comment]
We need more details on the status of this javascript extension before implementing anything. See activity at https://github.com/tree-sitter/tree-sitter-javascript/issues/154
