### ISSUE TITLE
Support for Scala

### ISSUE THREAD

**Issue by izar** [semgrep/semgrep#1953]
Scala is growing as a choice in high-performance computing environments and data science, offering both OO and functional approaches. Developers would highly benefit from support in semgrep.

**Comment by dlukeomalley** [comment]
Thank you @izar for the tracking ticket and request! We'll look for more +1s here and start the conversation 👍

**Comment by aryx** [comment]
Looks like there is a tree-sitter grammar for it: https://github.com/tree-sitter/tree-sitter-scala

@izar it would be great if you could evaluate whether the tree-sitter-scala parser is good and can parse correctly
a big percentage of your code.

**Comment by izar** [comment]
Will do. Thanks!

**Comment by dlukeomalley** [comment]
Still relevant and of interest, thank you stale-bot! Adding `priority:high` to appropriately track the desire by us all for Scala support.

**Comment by dlukeomalley** [comment]
It's starting to happen! From @mjambon on the [Semgrep Slack](https://r2c-community.slack.com/archives/CK86BJ5DW/p1613776847298700):

> Hey all. As a preliminary step toward supporting Scala in semgrep, we set up the files to get started: https://github.com/returntocorp/ocaml-tree-sitter/pull/161
>
> * This relies on the tree-sitter-scala project for parsing: the parsing success rate is currently 83%, so it would need some love to get closer to 100%. The Scala grammar is well documented, which will help a lot.
> * For support in semgrep, we'll need to map the Scala parse tree (CST) to the generic AST used by semgrep. This is the other big piece of work that will be needed.
>
> Scala is one of a few languages on our roadmap. Let us know if you're particularly interested in it!

**Comment by avirtuos** [comment]
+1 would love to see Scala support added so we can make semgrep our one and only tool for custom rule based static analysis. We presently have non-trivial portions of our applications in java, python, scala with small but growing population of RUST as well.

**Comment by aryx** [comment]
Do you have examples of rules for Scala you would like to write?

**Comment by aryx** [comment]
Alpha support for Scala should be available in the next release.
Let us know about parsing or matching bugs by creating issues.

**Comment by avirtuos** [comment]
When is the next release date? I am just wrapping up our first set of java
rules with semgrep and will allocated time to experiment with scala in the
next few weeks.


Anthony Virtuoso
mobile: 201.575.3435

**Comment by aryx** [comment]
We release every week on tuesday usually

**Comment by dinvlad** [comment]
Are there any updates on when it will be added to Alpha? Thanks!

**Comment by mmcqd** [comment]
Hey all who were interested in this, Scala feature support has reached (almost) Beta with the release of Semgrep 0.74.0! It's not technically full Beta yet, because we're still in the process of adding Scala rules to the semgrep-rules repo, but the parse rate is now above 99%. Feel free to start writing your own Scala rules, and reporting any bugs you find.
