### ISSUE TITLE
Metavariables don't work for class/interface keywords in Java

### ISSUE THREAD

**Issue by chgg-kboberg** [semgrep/semgrep#1955]
**Describe the bug**
Metavariables don't work for class or interface identifiers in Java.  The following pattern should work, but throws an unparseable exception on semgrep.dev:
```
@JsonTypeInfo(...)
public $IDENTIFIER $STRUCT {
...
}
```

**To Reproduce**
https://semgrep.dev/s/B2oR

**Expected behavior**
Metavariables for class/interface identifiers should work correctly.

**What is the priority of the bug to you?**
This is a P1 and aligned with quarterly goals for language hardening (to my understanding)

**Environment**
semgrep.dev

**Comment by nbrahms** [comment]
Hi @chgg-kboberg ,

Thanks for filing this.

As a workaround, would https://semgrep.dev/s/D8pG/ work for you?

**Comment by chgg-kboberg** [comment]
@nbrahms this workaround will work in the interim, the metavariable behavior would just be useful to cut down on the number of duplicated rules (this use case already has a lot of edge/corner cases that require multiple similar rule definitions).

**Comment by aryx** [comment]
I don't think we can allow metavariables to match some keywords. That would lead to grammar ambiguities where we could not know what you want to match (maybe we could make it work for this precise example, but we could not generalize it; for example you cant use a metavariable to represent a if or for or while or do to factorize things; it leads to many grammar ambiguities). There's a reason keywords are reserved identifiers ... they allow to make parsing unambiguous.

Moreover, the rules for what can be inside an interface and inside a class are different.

Maybe equivalences https://semgrep.dev/docs/experiments/#equivalences could help in factorizing rules (buy it's an experimental feature, so there's many limitations currently).

**Comment by aryx** [comment]
Note that the pattern is actually already hard to read/parse for me as a human when I see public $IDENT $STRUCT { ... }
