### ISSUE TITLE
Missing ASI when parsing a semgrep pattern

### ISSUE THREAD

**Issue by hexagonrecursion** [semgrep/semgrep#1960]
I am trying to match this
```js
foo(function (r) {bar(r)})
```

I tried this pattern https://semgrep.dev/s/6WGK/
```js
foo(r => {bar(r)})
```

Got:
Pattern could not be parsed as a Javascript semgrep pattern
Run with docker image: 0.29.0

I did find a pattern that works, but I don't understand why the first one did not.

https://semgrep.dev/s/olPX/
```js
foo(r => {bar(r);})
```

**Comment by mschwager** [comment]
Hi @hexagonrecursion,

Thanks for the report. It looks like Semgrep unnecessarily requires a `;`. This looks like a JS parsing bug to me, I'll move this to the correct board and notify the appropriate team.
