### ISSUE TITLE
if semgrepignore was used to ignore paths, mention as part of output

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1964]
Users probably won't be aware that semgrep respects .gitignore by default -- this can result in users thinking that semgrep is broke/doesn't scan subfolders.

Proposal: if gitignore was used to ignore paths, mention as part of output

Expanded proposal: if _any_ source was used to ignore paths, explain what it was (eg `ignored paths from .semgrepignore and .gitignore`)

cc @brendongo

**Comment by ievans** [comment]
Keep.

**Comment by ievans** [comment]
@brendongo now that we display the number of scanned files this seems less important. What do you think?

**Comment by ievans** [comment]
cc @mjambon who has been thinking about output along these lines

**Comment by emjin** [comment]
Should we change the "semgrep skips .gitignored files by default" behavior now that we have a `.semgrepignore`? imo should be removed entirely and controlled only by the `.semgrepignore`

**Comment by xmo-odoo** [comment]
> Should we change the "semgrep skips .gitignored files by default" behavior now that we have a `.semgrepignore`? imo should be removed entirely and controlled only by the `.semgrepignore`

Respecting .gitignore (`.ignore` as wel as it was "standardised" as an application-agnostic ignore file) seems like it remains a good idea to me: odds are if the project has things ignored in git they don't want to process them in any way. Hence tools like ripgrep [also respecting ignore files by default](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#automatic-filtering).

Though it could be useful to provide terser flags for disabling filtering? e.g. as the link indicates riprep has flags for individual filtering features, but it also has the "unrestricted" (`-u`) flag which progressively disables more filtering, so `rg -u` will skip ignorefiles, `rg -uu` will skip ignorefiles and process hidden files, and `-uuu` will skip ignorefiles, proces hidden files, and process binary files.

I have not checked how semgrep reacts to hidden or binary files, so those may or may not be useful.

**Comment by ievans** [comment]
Fixed in https://github.com/returntocorp/semgrep/pull/4518. @xmo-odoo I like that a lot -- want to open a new issue for -u/uu/uuu flags like ripgrep has?
