### ISSUE TITLE
Semgrep not supporting nested functions.

### ISSUE THREAD

**Issue by svganesh** [semgrep/semgrep#1967]
Semgrep does not support grep in nested functions. 

I want to check if make_transaction() is getting called in any of the child nested functions. Please help. Thanks!
https://semgrep.dev/s/wpEd

**Comment by mschwager** [comment]
Hi @svganesh,

Semgrep will find nested functions, but it appears that your pattern is not matching what you expect in the example code. For example, the following pattern finds the nested function: https://semgrep.dev/s/KdP5/. Looking at your example code, I think we will need some more complex logic to find what you're looking. The following should work: https://semgrep.dev/s/q6E7/. As you can see, this rule makes use of `pattern-either` and `patterns`. I'd recommend looking at Semgrep's [rule syntax](https://semgrep.dev/docs/writing-rules/pattern-logic/) to learn more.

Hope this helps - feel free to re-open if you have additional questions :+1:
