### ISSUE TITLE
typescript parse error on conditional types: a extends b ? c : d

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1969]
https://semgrep.dev/s/erNL

**Comment by mjambon** [comment]
tree-sitter-typescript will have to support [conditional types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html). See https://github.com/tree-sitter/tree-sitter-typescript/issues/82

Test in the typescript sandbox: https://www.typescriptlang.org/play?#code/C4TwDgpgBMULxQM7AE4EsB2BzKEAewEGAJolAEYD2lANhAIYZQD8UGArgLbkQpQBcSVJiwAoIA

**Comment by ievans** [comment]
(This is not an internal user)

@mjambon seems fixed, can you confirm?

**Comment by ievans** [comment]
Looked on desktop and seems good, closing as fixed

**Comment by mjambon** [comment]
Thank you Isaac. Yes, it was fixed in tree-sitter-typescript (https://github.com/tree-sitter/tree-sitter-typescript/issues/82) and the fix is now in semgrep.
