### ISSUE TITLE
typescript support for 'this' in user-defined type guards

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#1970]
https://semgrep.dev/s/vZE0

**Comment by mjambon** [comment]
It looks like [user-defined type guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) are supported by tree-sitter-typescript but `this` isn't accepted as a variable in `this is T`. Filed at https://github.com/tree-sitter/tree-sitter-typescript/issues/96.
