### ISSUE TITLE
semgrep.dev corrupts pattern switching from "advanced" to "simple"

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1971]
**Describe the bug**
Semgrep.dev is not corrupting pattern when moving from "advanced" to "simple"

Here is one example that causes switching to "simple" just by starting the Share process.
![semgrep-share-issue (1)](https://user-images.githubusercontent.com/6817500/98279279-88ebd880-1f4e-11eb-8e5f-a2491881fe65.gif)

However, it is not really related to sharing per se. The same problem occurs if you just select the "Simple" tab.

When you press "Run" you will see you get very different results between the two.

**To Reproduce**

Use this pattern
```
rules:
- id: observables-from-select-or-pipe-not-ending-with-dollar-sign
  patterns:
  - pattern-regex: '\w+\s*(:.+?)?=.*?(select|pipe)'
  - pattern-either:
    - pattern-inside: $VAR = $EXPR.select(...);
    - pattern-inside: $VAR = $EXPR.pipe(...);
  - pattern-not-inside: $VAR = d3.select(...);
  message: |
      Observable variable should end with a dollar sign.
```
and this sample code
```
  fetchParameterizedPerms$ = this.actions$.pipe(
    ofType(UserPermsTypes.GET_PARAMETERIZED),
    mergeMap((action: GetUserParamPerms) => this.requests.fetchParameterized(action.payload).pipe(
      map((resp: UserPermsResponsePayload) => new GetUserParamPermsSuccess(resp.endpoints)),
      catchError((error: HttpErrorResponse) => of(new GetUserParamPermsFailure(error))))));
```

**Expected behavior**
Either stay in advanced (if cannot map to simple), or map without corruption.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
===> P1

**Environment**
v 0.29.0

**Comment by chmccreery** [comment]
@msorens thanks for the detailed bug report- I will jump on this right away

**Comment by chmccreery** [comment]
Fixed by https://github.com/returntocorp/semgrep-app/pull/1059
