### ISSUE TITLE
[typescript] Incorrect match being flagged

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#1972]
**Describe the bug**
First, sorry for such a non-specific title above. Please rename to something more useful.

A couple things going on here.

Pattern:
```
rules:
- id: observables-from-select-or-pipe-not-ending-with-dollar-sign
  patterns:
  - pattern-regex: '\w+\s*(:.+?)?=.*?(select|pipe)'
  - pattern-either:
    - pattern-inside: $VAR = $EXPR.select(...);
    - pattern-inside: $VAR = $EXPR.pipe(...);
  - pattern-not-inside: $VAR = d3.select(...);
  message: |
    Observable variable should end with a dollar sign.
```
Test code
```
  fetchParameterizedPerms$ = this.actions$.pipe(
    ofType(UserPermsTypes.GET_PARAMETERIZED),
    mergeMap((action: GetUserParamPerms) => this.requests.fetchParameterized(action.payload).pipe(
      map((resp: UserPermsResponsePayload) => new GetUserParamPermsSuccess(resp.endpoints)),
      catchError((error: HttpErrorResponse) => of(new GetUserParamPermsFailure(error))))));
```

Observations:
(a) Running on semgrep.dev (reporting 0.29.0) shows a match on line 3 (the `mergeMap`) but that is not correct; it should not flag a match. 
(b) Running locally with v0.29.0 (`semgrep -f $SEMGREP_DIR`) on my own box, it correctly shows no error.
(c) Having just upgrade to v0.30.0, running locally now (incorrectly) flags a match.

My hunch: Since this broke with the release of 0.30.0, I believe semgrep.dev is really using 0.30.0 even though it claims to be on 0.29.0.

**To Reproduce**
As above

Wondering why I did not provide a link to the semgrep.dev sandbox? Because of https://github.com/returntocorp/semgrep/issues/1971

**Expected behavior**
1. Semgrep.dev should be noting v0.30.0.
2. Code and pattern above should not be flagging a match.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
===> P2

**Environment**
v0.29.0 and v0.30.0

**Comment by mschwager** [comment]
Hi @msorens,

My JS/TS knowledge is not great, but is this what you're looking for: https://semgrep.dev/s/l0gE? The [`metavariable-regex`](https://semgrep.dev/docs/writing-rules/pattern-logic/#metavariable-regex) operator is particularly useful here.

**Comment by msorens** [comment]
@mschwager Nice! Using `metavariable-regex` is (a) a cleaner solution and (b) works correctly with my data. So I will update my code accordingly and that gets me quite unblocked. Thanks!

(Note, however, that does not change the fact that my original rule worked in 0.29 and now fails in 0.30, so there is still a bug there, no?)

**Comment by mschwager** [comment]
Huh, weird. I'm seeing the same behavior on all of the following:

- https://semgrep.dev/s/6WK1/?version=0.29.0
- https://semgrep.dev/s/6WK1/?version=0.30.0
- And running your original rule/snippet against 0.29.0 and 0.30.0 locally

Since we have a working rule for your use-case I'm going to suggest we keep moving forward! Let us know if you see this again :+1:
