### ISSUE TITLE
Bug - Python - Issue handling f-strings with date formatting

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#1987]
**Describe the bug**
The parser can't handle f-strings with date formatting that have `/`.

**To Reproduce**

```bash
$ cat test.py
import datetime

print(f"{datetime.datetime.now():%Y/%m/%d}")
$ semgrep -e '$X == $X' -l py  --verbose
semgrep warn: parse error
  --> test.py:3
3 | print(f"{datetime.datetime.now():%Y/%m/%d}")
  |                                    ^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse test.py as py
```

**Expected behavior**
It should handle them properly.

**Screenshots**

**What is the priority of the bug to you?**
P2

**Environment**
0.300 on macOS installed with brew.

**Comment by mschwager** [comment]
Hi @j-martin,

Thanks for the report - this looks like a bug in our Python parser. I've included this on program analysis board and will notify the relevant parties :+1:
