### ISSUE TITLE
semgrep-core errors on symlinks

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2005]
Running against: https://github.com/mapbender/mapbender-starter

```
$ python -m semgrep --pattern '$X == $X' --lang php /tmp/mapbender-starter/ --verbose
an internal error occured while invoking semgrep-core:
	unknown exception: (Sys_error
  "/tmp/mapbender-starter/application/bin/doctrine.php: No such file or directory")
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
```

That file is a symlink:

```
$ ls -alh mapbender-starter/application/bin/doctrine.php 
lrwxrwxrwx 1 user user 39 Nov 10 10:20 mapbender-starter/application/bin/doctrine.php -> ../vendor/doctrine/orm/bin/doctrine.php
```

We should either: A.) follow symlinks in `semgrep-core`, or B.) resolve symlinks in Python before passing them to `semgrep-core`.

**Comment by mschwager** [comment]
Or C.) ignore symlink files in Python before passing them to `semgrep-core`. Symlinks seem like an annoyance in a static analysis context because the reported lines and such will be for the linked file, not the linker. If the linked file is also in the repository then we'll analyze it anyway (unless there's an edge-case like the linker has the correct extension and the linked does not).

@brendongo thoughts?

**Comment by ievans** [comment]
+1 to (C) @mschwager . This seems like a normal convention for unix-y tools, see ripgrep discussion https://github.com/BurntSushi/ripgrep/issues/692 and dumb-jump https://github.com/jacktasia/dumb-jump/issues/344
