### ISSUE TITLE
Decorators for TypeScript

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#2011]
**Is your feature request related to a problem? Please describe.**
Decorators are proposed feature for JS
https://github.com/tc39/proposal-decorators

and is also marked as experimental feature for TS
https://www.typescriptlang.org/docs/handbook/decorators.html

but they are widely used already in modern Typescript frameworks

```typescript
@Get()
async findAll() {
  throw new HttpException({
    status: HttpStatus.FORBIDDEN,
    error: 'This is a custom message',
  }, HttpStatus.FORBIDDEN);
}
```

https://docs.nestjs.com/exception-filters

**Describe the solution you'd like**
I think there is no need to implement it for JS at the moment but would be very helpful to have opportunity to use decorators in patterns for TypeScript like this

```
@Module(...)
class $CLASS {...}
```

```typescript
import { Module } from '@nestjs/common';
import { CatsController } from './cats.controller';
import { CatsService } from './cats.service';

@Module({
  controllers: [CatsController],
  providers: [CatsService],
})
export class CatsModule {}
```
https://semgrep.dev/s/kWoP/

**Comment by mjambon** [comment]
@aryx decorators are supported by the tree-sitter-javascript and tree-sitter-typescript grammars. We could use them to parse the pattern or we could add the feature to the pfff parser.

**Comment by mjambon** [comment]
@inkz thank you for the detailed report!

**Comment by aryx** [comment]
Actually they were not always put in the AST in tree-sitter-typescript. I've fixed that too.

**Comment by inkz** [comment]
Thanks for quick update! :+1:

**Comment by aryx** [comment]
works on develop: https://semgrep.dev/s/kWoP/?version=develop
