### ISSUE TITLE
Add Support for Setting Temporary Directory To A Location That Is Not World Readable

### ISSUE THREAD

**Issue by antitree** [semgrep/semgrep#2018]
**Is your feature request related to a problem? Please describe.**
When running semgrep locally, portions of the files it scans (ast cache) are stored in a world readable /tmp directory. This is likely fine for single user systems and CI/CD but in cases where I'm trying not to expose, for example, customer source code, it's seems like a risk. There does not appear to be any way to override this temp path. 

Process execution: 
```
user   207558  0.0  0.3  98700 44940 pts/4    S+   10:04   0:00 semgrep-core -lang go -rules_file /tmp/tmpvaeuhqs5 -j 4 -target_file /tmp/tmp_m4h6ps7 -use_parsing_cache /tmp/tmplyqohgka -timeout 0 -max_memory 0
user   207559 75.7  3.8 503036 465196 pts/4   R+   10:04  70:40 semgrep-core -lang go -rules_file /tmp/tmpvaeuhqs5 -j 4 -target_file /tmp/tmp_m4h6ps7 -use_parsing_cache /tmp/tmplyqohgka -timeout 0 -max_memory 0
```

Temp cache file permissions:
```
.rw-rw-r--   5.6k user 11 Nov 10:00  ffa15929daf2ab59590e3037e76ae0ba.ast_cache
.rw-rw-r--    667 user 11 Nov 10:00  ffb9e11a78b8c0e20a543557002dbe65.ast_cache
.rw-rw-r--    30k user 11 Nov 10:00  ffbef1bf725273799e2eae87ebd5d1e6.ast_cache
.rw-rw-r--    175 user 11 Nov  9:59  ffc1a704d3fd9debeb78831be3128961.ast_cache
.rw-rw-r--    14k user 11 Nov 10:00  ffd7f822dc345755124d3de9e3d3102a.ast_cache
```

**Describe the solution you'd like**
Add support for an argument that lets you set the temp file location or use a temp file location somewhere in the user's default home directory. This would allow execution to stay within the confines of the user account.

**Comment by mschwager** [comment]
Hi @antitree,

We use the [`tempfile`](https://docs.python.org/3/library/tempfile.html) library for choosing our temporary cache directory. It supports setting the directory via the [`TMPDIR`](https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir) environment variable. I just tested this functionality with the following command and it worked for me:

```
$ TMPDIR=~/tmp/ python -m semgrep ...
```

Can you confirm?

**Comment by antitree** [comment]
Works for me. Thanks!
