### ISSUE TITLE
spacegrep fails on files without read permission

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2043]
Spacegrep, when scanning for files, tries to open regular files or directories even if it doesn't have the permission to to do. This results in the following exception:
```
$ spacegrep x -d /tmp
Fatal error: exception Sys_error("/tmp/not-your-business: Permission denied")
...
```
Instead, such files should be ignored with a warning, similarly to how binary files are ignored. The `--force` option could apply here as well and cause files without read permission to not be ignored.

**Comment by dan5382** [comment]
@aryx I am assuming we can close this. Please update and reopen if I am wrong.
