### ISSUE TITLE
Install spacecat command

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2047]
The spacecat companion command to spacegrep was removed from the install bundle to save some space. Instead, we ship a single executable named `spacegrep` that serves both as `spacegrep` and `spacecat`, depending on the name of the command (argv[0]). For a proper installation with pip or brew, all we need is install an executable named `spacecat` that's a link to or a copy of the `spacegrep` executable.

Spacecat is [mentioned in the docs](https://semgrep.dev/docs/experiments/generic-pattern-matching/) so we should fix this or edit the docs.

**Comment by brendongo** [comment]
Closed by https://github.com/returntocorp/semgrep-docs/pull/185
