### ISSUE TITLE
Autofix loses fidelity by adding and subtracting characters

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2051]
**Describe the bug**
Two errors and one conundrum in the attached sandbox:

### The errors
(1) Lost a space from both matches.
(2) Gained an extra closing parenthesis--but only from one of the two matches!

### The conundrum
I understand why my two fragments of code are semantically equivalent and matched by the pattern. However, I was actually trying to write a rule to match just the first one; i.e., I only want to match the explicit `return`, so I could then use autofix to convert to the form of the second one. Can that be done?

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/6817500/99196846-b18c8300-2743-11eb-8358-20f3c0714ff8.png">

**To Reproduce**
https://semgrep.dev/s/GRPq/

**Expected behavior**
Autofix should maintain fidelity.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
P2

**Environment**
v0.31.0 and v0.31.1

**Comment by brendongo** [comment]
@mjambon I'm not too sure but I think our parsed typescript code loses the parenthesis around the returned dictionary on line 2? Is something like this a job for spacegrep?

**Comment by mjambon** [comment]
reopening

**Comment by emjin** [comment]
Reopening--I do mean to take a look at this.

**Comment by nmote** [comment]
The autofix part of this has been fixed by #7686. Autofix should no longer mess up parentheses. I'm closing this because the autofix misbehavior seemed to be the primary issue here. However, feel free to open another issue about the matching equivalence between the two arrow function styles if that is still important to you.
