### ISSUE TITLE
Change `none` to `regex` to clarify that these are regex-only rules

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#2056]
Alias `none` to mitigate breaking downstream changes

**Comment by aryx** [comment]
Can you explain more the issue? Can you give more context? I have no idea where we we currently accept 'none'.

**Comment by minusworld** [comment]
![image](https://user-images.githubusercontent.com/2374948/99546096-ecbccb00-296a-11eb-9b4d-a1a0287eaaff.png)

![image](https://user-images.githubusercontent.com/2374948/99546147-fd6d4100-296a-11eb-982d-031b62e5bc30.png)
