### ISSUE TITLE
javascript timeout errors on Signal-Desktop WASM autogenerated code

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2078]
**Describe the bug**
Semgrep times out running rules against three large files in Signal desktop:

```
ine@imbp4 ~/D/r/t/Signal-Desktop (development)> cat libtextsecure/libsignal-protocol.js | wc -l
   25286
ine@imbp4 ~/D/r/t/Signal-Desktop (development)> cat components/mp3lameencoder/lib/Mp3LameEncoder.js | wc -l
   46699
ine@imbp4 ~/D/r/t/Signal-Desktop (development)> cat js/Mp3LameEncoder.min.js | wc -l
   46699
```

**To Reproduce**

$ git clone https://github.com/signalapp/Signal-Desktop
$ time semgrep --config=r/javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector Signal-Desktop

**Expected behavior**
I think Semgrep should be able to parse a 25K LoC file and run a rule in <30 sec.

**What is the priority of the bug to you?**
Timeouts are correctly reported as of v.32, so marking as low-pri.

**Environment**
Semgrep v.32

**Comment by aryx** [comment]
v32.0 probably solves that

**Comment by DrewDennison** [comment]
@ievans there is now a 30s timeout. Can you retry with latest?

**Comment by ievans** [comment]
Thanks @DrewDennison. As of v.32 we now timeout successfully and have only three files that we fail on! I'll edit the issue to reflect

```
time semgrep --config=r/javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector
using config from https://semgrep.dev/r/javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 1 rules...
Warning: 1 timeout error(s) in libtextsecure/libsignal-protocol.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
Warning: 1 timeout error(s) in components/mp3lameencoder/lib/Mp3LameEncoder.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
Warning: 1 timeout error(s) in js/Mp3LameEncoder.min.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
js/views/recorder_view.js
severity:warning rule:javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector: User controlled data in a `$(...)` is an anti-pattern than can lead to XSS vulnerabilities
20:      $(window).on('blur', this.onSwitchAwayBound);
83:      $(window).off('blur', this.onSwitchAwayBound);

js/views/whisper_view.js
severity:warning rule:javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector: User controlled data in a `$(...)` is an anti-pattern than can lead to XSS vulnerabilities
73:          const $el = $(el);
ran 1 rules on 697 files: 3 findings
11 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

**Comment by aryx** [comment]
progress!

**Comment by aryx** [comment]
Is this a dupe?

**Comment by ievans** [comment]
No, https://github.com/returntocorp/semgrep/issues/2102 is tracking the fact that we don't terminate, ever; this is tracking the fact that some small-to-medium size files have timeouts.

**Comment by aryx** [comment]
Still an issue on 0.40

```
running 1 rules...
Warning: 1 timeout error(s) in js/Mp3LameEncoder.min.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
Warning: 1 timeout error(s) in components/mp3lameencoder/lib/Mp3LameEncoder.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
Warning: 1 timeout error(s) in components/protobuf/dist/ProtoBuf.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
Warning: 1 timeout error(s) in libtextsecure/libsignal-protocol.js when running the following rules: [javascript.jquery.security.audit.jquery-insecure-selector.jquery-insecure-selector]
ran 1 rules on 811 files: 0 findings
10 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

**Comment by aryx** [comment]
I've investigated a bit and the problem is that the 4 timeout occurs in file containing WASM code using a tons of local variables.
Then pattern like 
function (...,$Z,...) {
  ...
  $Y = <... $Z ...>;
  ...
}
just takes forever because they can match at too many places.

**Comment by aryx** [comment]
The wasm code seems pretty regular, like:
// EMSCRIPTEN_START_ASM
var asm = (function(global, env, buffer) {
  'use asm';

so  maybe we could have a preprocessing phase where we skip such code; in any case the code does not contain any "regular" variables from the user I think.

**Comment by aryx** [comment]
BTW the failures are not on small-medium size file. I had to compress the offending file to not get the
check_large_file pre-commit error.

**Comment by minusworld** [comment]
@ievans Would you still consider this medium priority?

**Comment by aryx** [comment]
ping @ievans should we add special code to not process WASM autogenerated code?

**Comment by ievans** [comment]
@aryx I wouldn't do that. I think as long as we have a reasonable timeout that means we won't parse these giant files, we are fine.

**Comment by aryx** [comment]
Ok so I'll close this issue then. People can add those autogenerated file to their semgrep ignore.
