### ISSUE TITLE
Document supported languages, and what file extensions will be considered for each language

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2079]
If I run semgrep with --lang=typescript or --lang=ts, how do I know what files will be considered? Specifically, will .tsx be considered as part of typescript?

My suggestions:
- semgrep CLI should show supported language tags under --help and link to documentation for details on which file extensions are mapped under each language
- perhaps update https://semgrep.dev/docs/status/ to link to that documentation about lang tag -> file extension as well?

**Comment by DrewDennison** [comment]
@mschwager I believe you did this already? Ok if I close out?
