### ISSUE TITLE
javascript-pattern-bug: detect presence of validate function

### ISSUE THREAD

**Issue by IgorSasovets** [semgrep/semgrep#2095]
Hello team!

First of all, thanks for this great project. It is really awesome and helps a lot! I have an issue with the JS pattern that I use to check presence of validation in a function. The reason is that semgrep does not detect matches when I pass pattern
```
return $FUNC.validate(...)
```
But when I use pattern
```
return $FUNC.$SRV(...)
```
it works correctly.

Here is a link to the sample:
https://semgrep.dev/s/B2A2

Thanks in advance!

**Comment by aryx** [comment]
You need to remove the 'return' in the pattern.
This is because return foo.bar() will not match code like return foo.bar().then().after().morestuff().
because those are not the same thing. Internally this is parsed as
return ((((foo.bar() ) . then()) . after () ) . morestuff () )

If you remove the return, and just use $FUNC.validate(), then we will match this expression anywhere, including
deeply nested in the return above.

**Comment by aryx** [comment]
cc @DrewDennison and @nbrahms who are interested in those kinds of limitations.

**Comment by IgorSasovets** [comment]
Hello @aryx ! Thank you for the answer. I have one more question and any help or thoughts on that would be highly appreciated. Yes, I can confirm the removing `return` from pattern resolves the issue. I want to match more complex pattern. Please see https://semgrep.dev/s/pGzL . For now, I am not able to do this. The next step will be to add more deep inspection using semgrep. Main goal of this deep inspection is to detect functions that have parameters validation before their usage in requests to a database. I expect to achieve something like below:
```
- pattern-either: 
      - pattern: |
          $FUNC.validate({$OPT1, $OPT2}, $VAL_NAME)
          .then($VALID => {
               $MODEL.find({$OPT1: $VALID.$OPT1, $OPT2: $VALID.$OPT2});
          })
          ...
    - pattern-inside: |
        function $FOO($OPT1, $OPT2) {
          ...
        }
```
Any suggestions or ideas would be highly appreciated

**Comment by aryx** [comment]
I think it's because of a current limitation on metavariable matching a field name or a variable/parameter.
See https://github.com/returntocorp/semgrep/issues/1930

**Comment by aryx** [comment]
Right now unfortunately you have to rewrite your pattern as: https://semgrep.dev/s/ne7G/

**Comment by IgorSasovets** [comment]
Hello @aryx ! Thanks for the suggestion

**Comment by dlukeomalley** [comment]
@aryx @DrewDennison Are you tracking work here? I'm cleaning up our misc. issue boards and wanted to confirm it's on your radar versus the boards I help manage.

**Comment by aryx** [comment]
closing. There's another issue tracking the metavariable matching fields and variables at the same time.
