### ISSUE TITLE
Handle spacegrep timeouts cleanly

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2099]
Currently spacegrep takes a `--timeout` option. If the spacegrep job times out, it fails with a non-zero exit code and prints just `"\ntimeout\n"` on stderr. I'm pretty sure semgrep doesn't understand this as a timeout since spacegrep is supposed to produce well-formed json.

What we want:

* Make the necessary changes such that a spacegrep timeout is reported as a timeout by the semgrep wrapper rather than an unknown error.
* Add a test to check for this behavior.

What this likely involves:

* Finding a test case that times out (after 1 second, which is the minimum timeout we can set). This could be done probably with a pattern containing multiple `...`.
* Modifying the signal handler in spacegrep to produce json. This is tricky do to due to the asynchronous nature of signal handlers. See code and comments in pfff or semgrep-core for this.
* This should not require major changes, if any, in the semgrep wrapper.

**Comment by aryx** [comment]
Note though that's it's very unlikely you get any timeout in spacegrep :)
We use timeout in semgrep because the performance of X ... Y is very very bad, but really we should optimize it.

**Comment by mjambon** [comment]
@aryx here's one case where spacegrep is slow. The target has only 504 lines and matching the pattern `$A ... $B ... $C ... foo` takes 38 seconds:
```
$ wc -l LICENSE 
504 LICENSE

$ time spacegrep '$A ... $B ... $C ... foo' -d LICENSE

real	0m37.873s
user	0m37.865s
sys	0m0.005s
```

**Comment by aryx** [comment]
Good test case
