### ISSUE TITLE
Semgrep fails to parse C code with `#ifdef` mid function call

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#2104]
**Describe the bug**

Semgrep does not appear to parse function calls with an `#ifdef` in the middle of it, or perhaps because it's in the middle of a string.

```c
SOME_FUNC(
    setexpr,
    "some text",
    "more text\n"
    "other text"
#ifdef CONFIG_REGEX
    "\n"
    "even more text"
#endif
);
```

**To Reproduce**
https://semgrep.dev/s/clintgibler:c-ifdef-mid-function-call

**Expected behavior**
I would expect this to parse.

**Screenshots**

**What is the priority of the bug to you?**
P2

This bug was encountered by a user during a C code audit they were trying to do.

**Comment by aryx** [comment]
The problem is is that ifdef can cut anywhere, and so the C parser in pfff currently handles a few cpp idioms,
but it's impossible to handle all of them.
See https://link.springer.com/content/pdf/10.1007/978-3-642-00722-4_9.pdf for more information.

**Comment by aryx** [comment]
This now works in the command-line.
```
(semgrep) pad@yrax:~$ semgrep -l c -e 'SOME_FUNC(...)' semgrep/tests/c/misc_ifdef_strings.c 
semgrep/tests/c/misc_ifdef_strings.c
5:  SOME_FUNC(
6:    setexpr,
7:    "some text",
8:    "more text\n"
9:    "other text"
10:#ifdef CONFIG_REGEX
11:    "\n"
12:    "even more text"
13:#endif
14:  );
ran 1 rules on 1 files: 1 findings
1 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

**Comment by aryx** [comment]
We still need to improve the CLI to say instead "1 file could not be *fully* analyzed"
tracked here: https://github.com/returntocorp/semgrep/issues/2186
We also need to update the web UI to display the match even if there was a partial parse error in the file
tracked here: https://github.com/returntocorp/semgrep-app/issues/1214

but at least the semgrep program now returns a match in this file, even if the ifdef caused a partial parse error (that tree-sitter-c was able to recover from).

**Comment by fropert** [comment]
Unsure if it's the same issue but the following simplified code from real-world with #define in a function fails to parse:
```
#include <inttypes.h>

int main(void)
{
    #define MAX_ENTRIES 42
    uint64_t foo = 10;
    printf("foo: /%"PRIu64"\n", foo);
    return 0;
}
```

**Comment by jynik** [comment]
@fropert IIRC, the `#` in the `#define` technically is supposed to be the first character on the line according to the C standard (89? 99?), isn't it? (I thought GCC and LLVM required such at least, but could be wrong.)

Is this the source of the failure, or was it a copy-paste error in creating the issue?
