### ISSUE TITLE
Metavariable match around Cyrillic characters causes crash with UnicodeDecodeError

### ISSUE THREAD

**Issue by Mariia-Kovtun** [semgrep/semgrep#2111]
Running semgrep rules caused UnicodeDecodeError:

`Traceback (most recent call last):`
  `File "/home/user/.local/bin/semgrep", line 8, in <module>
    sys.exit(main())`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/__main__.py", line 19, in main
    cli()`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/cli.py", line 379, in cli
    semgrep.semgrep_main.main(`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/semgrep_main.py", line 223, in main
    rule_matches_by_rule, debug_steps_by_rule, semgrep_errors, num_targets = CoreRunner(`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 532, in invoke_semgrep
    findings_by_rule, debug_steps_by_rule, errors, num_targets = self._run_rules(`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 500, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/core_runner.py", line 424, in _run_rule
    findings_for_rule, debugging_steps = evaluate(`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/evaluation.py", line 376, in evaluate
    message = interpolate_message_metavariables(rule, pattern_match)`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/evaluation.py", line 396, in interpolate_message_metavariables
    metavar, pattern_match.get_metavariable_value(metavar)`
  `File "/home/user/.local/lib/python3.8/site-packages/semgrep/pattern_match.py", line 82, in get_metavariable_value
    value = file.read(length)`
  `File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)`
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

This issue appeared several times during scanning. Some sample snippet that can cause an error:
[test.txt](https://github.com/returntocorp/semgrep/files/5583772/test.txt) (Originally it was a java file).

Used command:
_semgrep --config config.yml test.java_
It can be any rules in the config file.

Running _dos2unix_ command to files fix this behaviour, but it was expected that semgrep can handle unicode symbols without errors.

0.29 version of semgrep was used, upgrade to 0.32 hasn't changed the situation.

**Comment by underyx** [comment]
I just ran this command:

```sh
$ curl --location https://github.com/returntocorp/semgrep/files/5583772/test.txt > test.java && semgrep -f p/java test.java --strict --verbose
using config from https://semgrep.dev/p/java. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 28 rules...
100%|██████████████|28/28
ran 28 rules on 1 files: 0 findings
```

Using v0.32.0. Could you verify that the same exact command gives you an error? It might after all be related to the rules that you run. The traceback seems to fail at a part of the code that runs after a match is found.

**Comment by underyx** [comment]
Yep, managed to reproduce with this:

```sh
$ curl --location https://github.com/returntocorp/semgrep/files/5583772/test.txt > test.java && semgrep -l java -e '$X' test.java --strict --verbose
Traceback (most recent call last):
  File "/Users/underyx/.local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/cli.py", line 397, in cli
    semgrep.semgrep_main.main(
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 226, in main
    rule_matches_by_rule, debug_steps_by_rule, semgrep_errors, num_targets = CoreRunner(
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/core_runner.py", line 535, in invoke_semgrep
    findings_by_rule, debug_steps_by_rule, errors, num_targets = self._run_rules(
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/core_runner.py", line 503, in _run_rules
    rule_matches, debugging_steps, errors, rule_targets = self._run_rule(
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/core_runner.py", line 428, in _run_rule
    findings_for_rule, debugging_steps = evaluate(
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/evaluation.py", line 375, in evaluate
    message = interpolate_message_metavariables(rule, pattern_match)
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/evaluation.py", line 395, in interpolate_message_metavariables
    metavar, pattern_match.get_metavariable_value(metavar)
  File "/Users/underyx/.local/pipx/venvs/semgrep/lib/python3.9/site-packages/semgrep/pattern_match.py", line 80, in get_metavariable_value
    value = file.read(length)
  File "/Users/underyx/.pyenv/versions/3.9.0/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

And after loading the file in vscode, converting line endings from CRLF to LF, and re-running, I successfully get results.

**Comment by underyx** [comment]
Did some investigatin' and found that the bug is in this snippet of code:

```python
start_offset = self.metavars[metavariable]["start"]["offset"]
end_offset = self.metavars[metavariable]["end"]["offset"]
length = end_offset - start_offset

with open(self.path) as file:
    file.seek(start_offset)
    value = file.read(length)
```

There's a misalignment somewhere between the reported metavar start, and how Python reads the file an utf-8 encoded text.

### Text as it appears in file

```
43 |     * ррр
44 |     */
45 |     private
```

### Bytes as Python repr

```
b' * \xd1\x80\xd1\x80\xd1\x80\r\n     */\r\n    private'
```

### Mapping between the two

(The `•` character is used for padding when multiple characters of the bytes representation maps to one decoded unicode character. Also, I replaced regular spaces with non-breaking spaces, cause GitHub removes consecutive ones in inline code blocks.)

| Format        | Text  |
| ------------- | ----- |
| decoded       | ` * •••••••р•••••••р•••••••р••\n     */••\n    private` |
| encoded       | ` * \xd1\x80\xd1\x80\xd1\x80\r\n     */\r\n    private` |
| metavar match | `                       ^ starts here                 ` |
| metavar match | `            but probably meant to start here? ^      ` |

## Possible issue

I think Semgrep-core might be counting CRLF line breaks as one byte? The misalignment above is 23 characters, and the match is probably meant to start on line 45. That's almost double the misalignment. @aryx does any of this seem to make sense to you? Could you tell me what Semgrep-core is supposed to report as metavar match offsets? Currently I'm just wildly guessing :D

<img src="https://user-images.githubusercontent.com/1060436/100094298-15582f80-2e59-11eb-83bc-2ffe2376aad2.png" alt="image" width="400">

**Comment by aryx** [comment]
It's possible we report wrong byte location in semgrep-core if the file contains unicode character. @mjambon you remember the unicode hack you did? with Unicode.UTF8.asciify? Any chance this might affect byte location?

**Comment by underyx** [comment]
Thanks for checking on that. @brendongo in the meantime, how do you think we could fail more gracefully here?
