### ISSUE TITLE
Quickstart on Docker hub uses old code volume

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#2124]
**Describe the bug**

[This page on docker hub](https://hub.docker.com/r/returntocorp/semgrep) says:

> $ docker run --rm -v "${PWD}:**/home/repo**" returntocorp/semgrep --help

This should be

> $ docker run --rm -v "${PWD}:**/src**" returntocorp/semgrep --help

Since the repo was changed from /home/repo to /src in PR #1192.

**Comment by ievans** [comment]
Nice catch @Sjord, I updated the Dockerhub page to fix!
