### ISSUE TITLE
Unexpected non-json output while invoking semgrep-core

### ISSUE THREAD

**Issue by KrishnaTejaJ** [semgrep/semgrep#2128]
**Bug Description**
Error message: "Unexpected non-json output while invoking semgrep-core:\n\n\nAn error occurred while invoking the semgrep engine" is the output while applying python semgrep rule to a cloned repo(https://github.com/python/cpython) 

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/s/KrishnaTejaJ:log-level3

**Expected behavior**
Should output a json file with all the logging classes specified.

**Error Result**
`{"results": [], "errors": [{"type": "SemgrepError", "code": 2, "message": "unexpected non-json output while invoking semgrep-core:\n\n\nAn error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep"}]}`

**What is the priority of the bug to you?**
P1 (important to fix or quite annoying)

**Environment**
Local Build

**Comment by DrewDennison** [comment]
@KrishnaTejaJ I think I was able to fix it with https://github.com/returntocorp/semgrep/pull/2182. Could you please let me know if that fixes it for you and you are unblocked or if there is something else weird with your local build env

**Comment by DrewDennison** [comment]
the decoding bug was blocking me from reproducing your results with 0.33 but then I got 
![image](https://user-images.githubusercontent.com/1011067/101110367-7640df80-359e-11eb-805b-3e575fcd3bc4.png)

locally which is what I believe you are looking for

**Comment by KrishnaTejaJ** [comment]
@DrewDennison Can you be a bit more elaborate on how exactly I get the result locally?

**Comment by DrewDennison** [comment]
hi @KrishnaTejaJ when you say "environment: Local Build" are you building from source or are you installing via pip?

I did

```bash
git clone https://github.com/python/cpython
cd cpython
semgrep --version
semgrep --config KrishnaTejaJ:log-level3 --json
```

**Comment by KrishnaTejaJ** [comment]
I used pip, but yeah the steps you mentioned did it for me. Thank you!

**Comment by DrewDennison** [comment]
awesome, glad to know this worked for you and thanks again for the bug report
