### ISSUE TITLE
Matches to "fake" token nodes crash Semgrep

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#2152]
**Describe the bug**
Any time there is a match to an AST node that is missing token information, Semgrep will crash irrecoverably.

**To Reproduce**
This can be demonstrated on older versions of Semgrep (e.g. 0.28) by matching, e.g., an expression metavariable to an fstring. In 0.22, attempting to match an empty tuple will also crash as the AST is missing the tuple parends.

**Expected behavior**
These instances are either skipped in matching, or Semgrep recovers from the error and continues matching.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
ok, found a fix, will submit a PR ASAP
