### ISSUE TITLE
[Ruby] Unable to parse certain trailing commas in arguments

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#2157]
@minusworld @aryx Filing this issue with a more generic title as I'm less familiar with Ruby, please feel free to update / modify

The following Ruby code only parses 2/3 cases:

```ruby
#this works
Group.where(
         bob:'alice',
         resource_id_or_key: team.id.to_s,
      )
      
#this also works
Group.where(
         resource_type:'team',
         resource_id_or_key: team.id.to_s
      )      

# this barfs
Group.where(
         resource_type:'team',
         resource_id_or_key: team.id.to_s,
      )
```

Reproduction: https://semgrep.dev/s/l0nL

**Comment by aryx** [comment]
Ruby allows trailing commas in arguments? @clintgibler ?

**Comment by aryx** [comment]
Apparently it does, and looks like the tree-sitter-ruby grammar accepts those trailing commas.
Weird.

**Comment by aryx** [comment]
cc @mjambon

**Comment by mjambon** [comment]
I submitted a fix in the tree-sitter-ruby grammar (https://github.com/tree-sitter/tree-sitter-ruby/pull/137). When it's merged, we'll have to update our repos to propagate the change.

**Comment by aryx** [comment]
Nice job martin. I still don't understand why the modifications to the lexer you did can solve the problem here, or why the parser was working on the first 2 cases but not the last one? There's even a trailing comma in the first example; why this parses but not the last one? This is mystery to me.

**Comment by mschwager** [comment]
Fix was merged into tree-sitter, we're no longer blocked!

**Comment by underyx** [comment]
just tagging you @mjambon about the above ^ 🙌

**Comment by dlukeomalley** [comment]
@mjambon Any updates on updating tree-sitter for this?
