### ISSUE TITLE
Max line length for any finding

### ISSUE THREAD

**Issue by devd** [semgrep/semgrep#2159]
**Is your feature request related to a problem? Please describe.**
In a minified JS file, showing the "matched line" will basically mean the whole file is printed. This is pretty painful to navigate around. And since every match in the file is a new finding, the whole file is printed again and again.

**Describe the solution you'd like**
Ideally, I would like to only show the matched section (the part that semgrep highlights/bolds) if its small and the whole line is >200chars. And if matched section is also massive, then semgrep just says "redacted due to length". A CLI flag can then allow enabling this display.

**Describe alternatives you've considered**
Another option is just default to never showing any line output > 200 chars and saying "Redacted".
 
**Additional context**

**Comment by ievans** [comment]
👍 an easy change and a good one. If someone wants to take this on, you'll be touching most of the same paths as in #2082.

**Comment by ievans** [comment]
go away stale bot

**Comment by ankush** [comment]
I can work on this if no one is working on it.

**Comment by ievans** [comment]
@ankush sounds great! I can review your PR once it's ready.

**Comment by ankush** [comment]
@ievans please review the linked PR ^
