### ISSUE TITLE
Our docker push is broken

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2171]
Our docker push is broken: https://github.com/returntocorp/semgrep/actions/runs/398772129
<img width="1275" alt="Screen Shot 2020-12-03 at 11 19 38 AM" src="https://user-images.githubusercontent.com/409041/101056886-0f490980-3551-11eb-964c-418b9bb425f7.png">

Failed attempt to fix: https://github.com/returntocorp/semgrep/pull/2168

labelling as priority medium b/c it's blocking release to a customer

> https://github.com/GabLeRoux/github-actions-examples/blob/e0468ce2731b08bd8b1f7cd09d0b94c541310693/.github/workflows/secret_based_conditions.yml looks like what we want

**Comment by brendongo** [comment]
Taking a look

**Comment by brendongo** [comment]
Fixed by https://github.com/returntocorp/semgrep/pull/2181
