### ISSUE TITLE
[Ruby] & operator not working in patterns

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#2179]
https://semgrep.dev/s/neZG

Hello team! It seems like semgrep doesn't match anything with the `&` operator.

Pattern: `$A & $B`
Test code: `1 & 3`

Fun fact, matching `... & ...` causes an error in the parsing of the pattern and not just a "no match". I tried with `+` and `|` and those operators seemed to work.

**Comment by dee-see** [comment]
Some precision

- `$A & $B` parses but does not match
- `... & ...` does not parse
- `$A + $B` parses and matches
- `... + ...` does not parse
- `$A | $B` parses and matches
- `... | ...` parses and matches

**Comment by dee-see** [comment]
https://semgrep.dev/s/7gXv/ 

Another interesting behavior

`... && ...` will match both lines:

```
1 & 2
1 && 2
```

It works well with `|` vs `||` however

**Comment by dlukeomalley** [comment]
@aryx @mjambon Tagging you two as the usual suspects here for Ruby parsing :)

**Comment by aryx** [comment]
This now works on develop: https://semgrep.dev/s/neZG?version=develop

**Comment by dee-see** [comment]
Thanks @aryx ! This still fails however https://semgrep.dev/s/Kd4j/?version=develop

**Comment by aryx** [comment]
yes we might have restrict where '...' can appear in Ruby to just function calls or a few other places because of grammar
ambiguities. In the mean time you can always use metavariables like $_X & $_Y

**Comment by dee-see** [comment]
Alright, this fix is good enough for my current use case anyway. Thanks!
