### ISSUE TITLE
Multi-line autofix indents should align

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2183]
**Describe the bug**
Consider this `fix` block of the rule:
```
  fix: |
    const retval = $COLLECTION.find($ITEM => $EXPR);
    return retval !== undefined ? retval : $DEFAULT_EXPR;
```

A first attempt at a multi-line autofix looks somewhat askew--notice the second line of the fix has no indent; it is just left-justified:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/6817500/101120317-2d8b2580-35a2-11eb-97e2-05a6be41a985.png">

I understand why that occurs: autofix is actually not applying _any_ indents, not even to the first line. It just puts the first line of the replacement where the first line of the original text was.
So that led me to guess that the following would be an appropriate workaround:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/6817500/101120882-96bf6880-35a3-11eb-8584-040f2fc97bfb.png">
Notice that here I added an additional indent in the `fix` block, and that is copied verbatim as part of the fix, giving correct indentation. But that only works for code that happens to be indented at this specific number of spaces, and that is not known a priori.

**To Reproduce**
Here it is in the sandbox (https://semgrep.dev/s/8xjJ/) but you cannot see the problem there. You can only see it on the command-line (or in an actual fixed file).

**Expected behavior**
Multi-line fix should try to honor indents.
(There may still be some edge cases where this comes out odd--perhaps fixing an expression in the middle of a line, but I still think this would be an improvement.)

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
**P2 -- regular bug**

**Environment**
semgrep 0.32.0

**Comment by aryx** [comment]
The right fix really is to rely on an refmt like tool to reformat the file after program transformation.
There are lots of hacks in Coccinelle to try to indent correctly the autofixed code.
