### ISSUE TITLE
Better message for partial parsing errors

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2186]
**Is your feature request related to a problem? Please describe.**

Tree-sitter has some powerful error-recovery mechanism where a mistake in a file (or a programming language
feature not yet handled by the grammar) does not cause the whole file to fail; Instead tree-sitter tries its best
to parse what it can and to return a valid AST semgrep can work on.

Unfortunately, currently semgrep wrongly says it was not able to parse 1 file, even though it finds match in it.

See for example https://semgrep.dev/s/clintgibler:c-ifdef-mid-function-call?version=develop
if you copy the source in a file and run in the command-line semgrep you'll get:
```
(semgrep) pad@yrax:~$ semgrep -l c -e 'SOME_FUNC(...)' semgrep/tests/c/misc_ifdef_strings.c 
semgrep/tests/c/misc_ifdef_strings.c
5:  SOME_FUNC(
6:    setexpr,
7:    "some text",
8:    "more text\n"
9:    "other text"
10:#ifdef CONFIG_REGEX
11:    "\n"
12:    "even more text"
13:#endif
14:  );
ran 1 rules on 1 files: 1 findings
1 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

**Describe the solution you'd like**

The last line should be instead
```
1 file could not be fully analyzed; run with ...
```

Maybe it could be useful to return a different kind of error when we know it was a partial parse error.
Maybe the JSON returned by semgrep could be a PartialParseError instead of ParseError.

Still, an easy fix is probably to just change the message to "could not be _fully_ analyzed".
If a file can not parse at all, the sentence is still true :)

**Describe alternatives you've considered**

**Additional context**

**Comment by aryx** [comment]
cc @mjambon again.

**Comment by aryx** [comment]
Ping

**Comment by mjambon** [comment]
Oops, sorry, my email filters were set up incorrectly so this got buried. I'll look into it.

**Comment by dan5382** [comment]
@nbrahms any update on this or link to a related ticket?

**Comment by ievans** [comment]
@dan5382 why did this get closed?

**Comment by IagoAbal** [comment]
The message has already changed since this issue was opened, now Semgrep will say:

> found problems analyzing 1 file; run with ...

If you then pass `--verbose` you can see the parse error.

```
% cat foo.js 
x = x + 1

foo {

% semgrep -l js -e 'x' --verbose foo.js
semgrep warn: parse error
  --> foo.js:3
3 | foo {
  | ^^^^^
= help: If the code appears to be valid, this may be a semgrep bug.
Could not parse foo.js as javascript

foo.js
1:x = x + 1
--------------------------------------------------------------------------------
1:x = x + 1
ran 1 rules on 1 files: 2 findings
found problems analyzing 1 file; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed cleanly
```

Is this enough to close this issue?

**Comment by aryx** [comment]
:wave:

**Comment by brandonspark** [comment]
It sounds like we report partial parsing in the CLI now. Can this issue be closed?
