### ISSUE TITLE
Add 'key_value' detection to Ruby patterns

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2189]
Consider the following Ruby code:

```
options = { key1: 41, key2: 42, key3: 43 }
options[:key2]  # => 42
```

Similar to other languages like Python and JS, it'd be nice to search for patterns on Ruby's [`Hash`](https://docs.ruby-lang.org/en/2.0.0/Hash.html) object:

```
$ python -m semgrep --pattern '{..., $KEY: $VALUE, ...}' --lang ruby semgrep-core/tests/ruby/metavar_key_value.rb
ran 1 rules on 1 files: 0 findings
```

**Comment by aryx** [comment]
A semgrep.live link would be even better :)

**Comment by aryx** [comment]
example: https://semgrep.dev/s/D8vv/
