### ISSUE TITLE
Add gathering of 'parse.pct' metrics for additional languages

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2190]
A language's parse rate is now used to determine its maturity (alpha/beta/GA): https://semgrep.dev/docs/status/.

With this in mind, it would be very helpful to have parse rate information for all supported languages. This allows us to determine the maturity tier for each language. Parse rate information by language can be found here: https://dashboard.semgrep.dev/metrics.

My understanding is that we don't have parse rate information for languages like PHP and Python because these are `pfff` based languages, not `tree-sitter`. I see two options for gathering parse rate information for **all** languages:

1. Use `tree-sitter` for all languages
1. Support parse rate gathering in `pfff` languages

I don't have strong feelings about either of these solutions, or even a different solution, but it would be very helpful to have parse rates automatically measured for each language.

**Comment by mjambon** [comment]
Currently, the stats are gathered using scripts in ocaml-tree-sitter for historical reasons. For each language, there's a list of file extensions and a list of public git repos (and an optional list of private git repos). Each repo is cloned if needs to be and then scanned by the parser for the language, which dumps a file containing error counts. The second part (in python) is to upload the numbers to the semgrep dashboard.

A good rewrite might consist in:
* have semgrep-core do the scanning of a target repo for a language and dump a json file containing the essential counts. Maybe it can run on all the repos at once, avoiding the need to merge the counts.
* have a single python script that takes care of (1) downloading the git repos, (2) launching semgrep-core, (3) reading the json dump and posting it to the semgrep dashboard.

**Comment by aryx** [comment]
I can add the semgrep-core option to parse a repo and outputs parsing stats for it.
semgrep-core -lang X -parsing-stats <dir>
which can output a JSON with {total_lines: <int>, lines_with_errors: <int>, etc. files_with_timeout: <int>, etc.)

**Comment by mschwager** [comment]
> I can add the semgrep-core option to parse a repo and outputs parsing stats for it.
> semgrep-core -lang X -parsing-stats
> 
> which can output a JSON with {total_lines: , lines_with_errors: , etc. files_with_timeout: , etc.)

That would be great :+1:

**Comment by aryx** [comment]
where is the code to manage parsing stats in ocaml-tree-sitter @mjambon ? did you define a few types in OCaml for it already? Just looking for a starting point to do something similar for pfff in semgrep-core.

**Comment by aryx** [comment]
Ok I think my part is done. You can now do 
semgrep-core -lang go -json -parsing_stats /path/to/go/repo 2>/dev/null
and it will print on stdout some JSON info about total line count and error line count for this go project.

**Comment by aryx** [comment]
from slack, copy pasted here:
"actually we also need to reports parsing stats not just of tree-sitter CST parsing but also conversion to the generic AST, which is really what matters.
For example the current parsing C# stats are at 100% https://dashboard.semgrep.dev/metric/semgrep.core.c-sharp.parse.pct but in reality there are still lots of todo() in Parse_csharp_tree_sitter.ml which means most of the files actually can't be processed by semgrep."

**Comment by mschwager** [comment]
It's here!

- https://dashboard.semgrep.dev/metric/semgrep.core.php.parse.pct
- https://dashboard.semgrep.dev/metric/semgrep.core.python.parse.pct
