### ISSUE TITLE
Support typescript patterns with type assertions

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2192]
Originally requested by @msorens

Related to bug https://github.com/returntocorp/semgrep/issues/2191

Type assertions in typescript allow two syntaxes:
```
$ cat foo.ts
x = <number> 0;
y = 42 as number;
```

We get no matches when we were expecting two matches:
```
$ semgrep -e 'const $VAR = $EXPR as $TYPE;' foo.ts --lang ts
ran 1 rules on 1 files: 0 findings
```

Additionally, the angle bracket syntax is not supported in patterns. It would be good if it were, if the selected language is pure typescript and not tsx:
```
$ semgrep -e 'const $VAR = <$TYPE> $EXPR;' foo.ts --lang ts
semgrep error: invalid pattern
  --> CLI Input:1
1 | const $VAR = <$TYPE> $EXPR;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

Pattern could not be parsed as a Typescript semgrep pattern

```

**Comment by aryx** [comment]
remove the 'const' in the pattern and it will match.

**Comment by aryx** [comment]
the pattern is parsed by pfff and there we allow JSX, and the <xxx> syntax is not allowed with JSX.
Because the 2 forms are equivalent, I think it's better of we force people to use the 'as' syntax in the pattern
and allow it to match both forms (they are equivalent).

**Comment by aryx** [comment]
Closing the issue, just remove the 'const' in the pattern.
