### ISSUE TITLE
spacegrep: Add -i option to spacegrep for case-insensitive searches

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2196]
This is useful for text search in general. Spacegrep is focused on ascii support, so this option would only handle the downcasing of ascii letters.

**Comment by aryx** [comment]
We can close this no @mjambon ?
You need to use "Fixes #<issue  number>" or "Closes #<issue>" in the commit message to get github to automatically close the issue
once the related PR is merged.  "Implements #<issue>" does not close automatically the issue.
