### ISSUE TITLE
No way to match only `try {...}` block without `catch {...}` in JS/TS

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#2211]
see chat here: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1607112321088700

> https://semgrep.dev/s/underyx:handle-localstorage-errors

> can anyone help me match the last class in the code snippet here? I don’t know how to specify that my pattern is only allowed in the try block of the try-catch pair

**Comment by aryx** [comment]
you could do
try {
  ...
  <... localStorage.$METHOD(...) ...>
 ...
} catch(...) { ... }

**Comment by aryx** [comment]
but yes it would be nice to match just the try { ... } part without caring about the catch part.

**Comment by aryx** [comment]
We recently allowed partial function pattern, partial if, I guess we could add partial try.

**Comment by underyx** [comment]
we could certainly try :dancers:

**Comment by underyx** [comment]
@aryx I think your suggestion fails to parse as a pattern: https://semgrep.dev/s/9RN0/

**Comment by aryx** [comment]
you need some extra () and semicolon to parse currently:
https://semgrep.dev/s/er3R/
