### ISSUE TITLE
Matching Go switch Statements

### ISSUE THREAD

**Issue by bflad** [semgrep/semgrep#2215]
## Description

Matching `switch` statements in Go seems like it might be difficult or unsupported at the moment: https://semgrep.dev/s/kWn1

This Go code exercises a few styles of `switch` for playing:

```go
package main

import (
	"fmt"
	"runtime"
	"time"
)

func main() {
	os := runtime.GOOS

	switch os {
	case "darwin":
		fmt.Println("OS X.")
	case "linux":
		fmt.Println("Linux.")
	default:
		// freebsd, openbsd,
		// plan9, windows...
		fmt.Printf("%s.\n", os)
	}

	var i interface{}
	i = 10
	
	switch i.(type) {
	case string:
		fmt.Println("interface is a string.")
	default:
		fmt.Printf("interface is not a string: %T\n", i)
	}

	switch t := i.(type) {
	case int:
		fmt.Printf("interface is an int: %d\n", t)
	default:
		fmt.Printf("interface is not an int: %T\n", t)
	}

	now := time.Now()

	switch {
	case now.Hour() < 12:
		fmt.Println("Good morning!")
	case now.Hour() < 17:
		fmt.Println("Good afternoon!")
	default:
		fmt.Println("Good evening!")
	}
}
```

Attempting any of the following generic rule patterns always returns:

> Pattern could not be parsed as a Golang semgrep pattern

```
switch ... { ... }
```

```
switch ... {
...
}
```

```
switch $CONDITION { $BODY }
```

## References

- https://semgrep.dev/docs/status/
- https://golang.org/ref/spec#Switch_statements

**Comment by aryx** [comment]
Because of some grammar conflicts when using ... inside switch, you'll have to use 'case ...' to express an ellipsis inside
switch, for example:
```
switch $COND {
case ...
}

should match any switch.

**Comment by bflad** [comment]
Thank you for the quick response, @aryx!
