### ISSUE TITLE
Cannot use on Windows 10 Entreprise

### ISSUE THREAD

**Issue by righettod** [semgrep/semgrep#2230]
**Describe the bug**

I cannot execute it on a Windows 10 Enterprise 64 bits system with Python 3.7.4.

**To Reproduce**

Install the tool and try to scan a file via ` semgrep -e '[RULE]' --lang=php **`

**Expected behavior**

The analysis result.

**Screenshots**

![image](https://user-images.githubusercontent.com/1573775/101825672-3776d080-3b2e-11eb-91be-5f45d3bb8c16.png)

![image](https://user-images.githubusercontent.com/1573775/101825768-612ff780-3b2e-11eb-98f5-de90d30e9d62.png)

**What is the priority of the bug to you?**

P2

**Environment**

Installation of the last release via pip.

**Comment by underyx** [comment]
Yay, thanks for following up from the meetup Dominique!

**Comment by mschwager** [comment]
Is this for native Windows support, or WSL? WSL should work, so that would be a bug if so - for native Windows we've been tracking in https://github.com/returntocorp/semgrep/issues/1330.

**Comment by righettod** [comment]
@mschwager It's for native support.
However usage of the docker image is a way until it is available natively.
@underyx  You are welcome, it was a great and cool event 😃

**Comment by mschwager** [comment]
> @mschwager It's for native support.
> However usage of the docker image is a way until it is available natively.

Great, thanks for the clarification. I'm going to close this one in favor of #1330.

**Comment by righettod** [comment]
Ok thank you very much.
