### ISSUE TITLE
Ruby: Road to GA

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2231]
We're very close to Ruby GA support! By our [language maturity definitions](https://semgrep.dev/docs/status/#maturity-definitions) we've achieved the **feature support** and **ruleset count** goals. Feature support can be seen in the feature matrix, and we have the following rulesets:

* [`/p/ruby`](https://semgrep.dev/p/ruby)
* [`/p/minusworld.ruby-on-rails-xss`](https://semgrep.dev/p/minusworld.ruby-on-rails-xss)

All that's left is improving our Ruby parse rate from `99.793%` -> `99.9%+`. Fortunately there have been quite a few improvements upstream in the [Ruby tree-sitter repository](https://github.com/tree-sitter/ruby-tree-sitter). The following bugs should be fixed once we pull in the latest upstream changes:

* https://github.com/returntocorp/semgrep/issues/1457
* https://github.com/returntocorp/semgrep/issues/1580
* https://github.com/returntocorp/semgrep/issues/2097
* https://github.com/returntocorp/semgrep/issues/2098
* https://github.com/returntocorp/semgrep/issues/2157

The following is not an upstream fix, but is something we're definitely capable of fixing:

* https://github.com/returntocorp/semgrep/issues/1868

Once these are fixed we can re-run our parse rate calculations. Hopefully all these fixes put us over the `99.9%` threshold.

cc @aryx @mjambon

**Comment by mschwager** [comment]
Created some additional upstream issues for new parsing errors:

- https://github.com/tree-sitter/tree-sitter-ruby/issues/143
- https://github.com/tree-sitter/tree-sitter-ruby/issues/144
- https://github.com/tree-sitter/tree-sitter-ruby/issues/145
- https://github.com/tree-sitter/tree-sitter-ruby/issues/146

**Comment by aryx** [comment]
Thx @mschwager for filing all those parsing issues, especially because you filed them in another repository :)

**Comment by mschwager** [comment]
Ruby is GA! https://dashboard.semgrep.dev/languages
