### ISSUE TITLE
Add support for Swift

### ISSUE THREAD

**Issue by cpholguera** [semgrep/semgrep#2232]
It would be great to have Swift support, along with Kotlin support this can allow for very comprehensive static analysis of mobile apps.

**Comment by underyx** [comment]
I gave you a +1 as thanks for dropping by on our issue tracker :D

**Comment by traw** [comment]
[Tree-sitter-swift](https://github.com/tree-sitter/tree-sitter-swift) might be of some help

**Comment by fabiopires** [comment]
Hi @aryx - not sure if you can give an update on this one. Any thoughts on when this will be added?

Thank you!

**Comment by aryx** [comment]
It's not on our roadmap yet I think. We don't have any customers yet asking for it. Also the tree-sitter-switft above
has not been updated in 2 years, so this is problematic because we need an up-to-date tree-sitter grammar to get good parsing stats.
Note that people can help. In the last year a few external people added support for language like Rust, C#, Hack.

**Comment by Hupka** [comment]
Good morning! 

Recently the Tree-Sitter-Swift-Project has been moved and is now actively maintained in a different place: https://github.com/alex-pinkus/tree-sitter-swift

How much effort would it be to include support for Swift? What would be most of the effort?

**Comment by aryx** [comment]
Most of the effort is writing the Parse_swift_tree_sitter.ml which converts the Concrete syntax tree of Swift as returned by tree-sitter-swift, to the generic AST used internally in semgrep. See for example https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml which is the converter written for C#.

**Comment by aryx** [comment]
Before writing this Parse_swift_tree_sitter.ml, there are lots of small steps to do as documented here: https://semgrep.dev/docs/contributing/adding-a-language/
