### ISSUE TITLE
This docker rule should return some results

### ISSUE THREAD

**Issue by daghan** [semgrep/semgrep#2261]
**Describe the bug**
This should be a correct rule / query

https://semgrep.dev/s/daghan:docker-test???version=develop

**What is the priority of the bug to you?**
P2

**Environment**
semgrep.dev version=develop

**Comment by mschwager** [comment]
@daghan It looks like your `patterns` operators were missing `-`. E.g. https://semgrep.dev/s/olB1/?version=develop

We should definitely warn the user here, though. I'll investigate and see why that's not happening.

**Comment by mschwager** [comment]
Looks like this is a cloud app issue - closing in favor of https://github.com/returntocorp/semgrep-app/issues/1291.
