### ISSUE TITLE
Difference between report generated by semgrep and semgrep-agent

### ISSUE THREAD

**Issue by Frostweeds** [semgrep/semgrep#2264]
We are currently using semgrep to generate vulnerability reports and we have seen that there seems to be differences in-between the JSON structure generated by semgrep and semgrep-agent. For example, semgrep returns a structure of the form
```
{ results: [
     ...
] }
```
while semgrep-agent returns directly the array as the top-level struct. There is also an `extra` field which contains `metadata` in the semgrep while in semgrep-agent there is directly `metadata`, ...

Are you aware of this discrepencies and if so is it normal or a problem on our side ? We are also wondering if by any chance you have a reference schema for the report generated by the tools ?

Thanks.

cc: @xens

**Comment by mschwager** [comment]
Hi @RomainJufer,

We used to have [output](https://github.com/returntocorp/semgrep/blob/96c72584f20a00fd0f3a42b651cf8589c8aa2b13/docs/output.md) documentation, but it looks like it didn't make it to our new [docs](https://semgrep.dev/docs/) site. The old output documentation should give you an idea for the `semgrep` JSON output. However, I would not expect the `semgrep` and `semgrep-agent` JSON output to match. I'm not sure that we've put much thought into a stable JSON API output for `semgrep-agent` yet, but it's definitely something worth considering. @underyx may have more thoughts here.

**Comment by underyx** [comment]
You're right on all counts, Matt. I did also find that the output format documentation is [commented out currently in the docs](https://github.com/returntocorp/semgrep-docs/blame/main/docs/integrations.md#L244), which is probably a decision by @dlukeomalley.

The formats are different and will likely stay that way. Semgrep-agent does some processing and adds fields to aid issue deduplication, and in the process also discards some information. There is no formal schema as of yet. Would it be helpful if we bundled one? We didn't do that yet as the agent schema is flat and has only a couple keys at the moment, but if you need it, maybe now is the right time to do so.

**Comment by xens** [comment]
thanks @mschwager and @underyx for your answers. Initially we wanted to import data from the `semgrep-agent` inside DefectDojo as there's now a parser for it (https://github.com/DefectDojo/django-DefectDojo/issues/2720), but we saw the data-model differences between `semgrep` and `semgrep-agent` and we understood that only `semgrep` was supported for now inside DDJ. So as I understand we have two options:
1. create a parser for the `semgrep-agent` for DefectDojo (and yes having a formal schema would definitely be helpful for that)
2. use the SARIF data-model for both `semgrep` and `semgrep-agent` when importing data inside DefectDojo (but we might loose some data that are not in the SARIF data-model).

Let us know what you think is best.

**Comment by DrewDennison** [comment]
two asks 1) I recommend using `semgrep-agent` in DefectDojo and 2) @underyx @brendongo can we add SARIF output to semgrep-agent with the new `--opts` flag?

**Comment by dlukeomalley** [comment]
@DrewDennison Reflecting on this a bit more, I'm wondering if [Semgrep App](https://semgrep.dev) should just be able to post Semgrep CI results to DefectDojo? That takes away any manual result importing.

@xens, do you have any context/how-to knowledge on what it would look like to post Semgrep App data to DefectDojo? This would let us leverage the fanciness of Semgrep App (result deduplication, easy config, etc.) AND get you get you the data where you ultimately want to see it.

**Comment by minusworld** [comment]
@dlukeomalley Do you have any further updates on this ticket?  From this discussion, are you interested in documenting at least the Semgrep CLI output?

**Comment by xens** [comment]
@dlukeomalley regarding the DefectDojo integration it's usually a separate process in a CI/CD pipeline that takes the scanner output and sends it to DefectDojo, so basically the process would be:

1. run semgrep-agent in your pipeline and store the result as a job artifact (output format should ideally be stable)
2. the next pipeline stage or in the same one depending on your logic, the semgrep artifact is POSTed to DefectDojo (via its RESTapi)
3. DeffectDojo handles the deduplication (if needed)

You could integrate the POST-to-DefectDojo functionality inside your app but then you'll need to maintain the integration over time, and there's probably many deployment scenarios where the DefectDojo instance will not be directly reachable from the semgrep-app, that's why I think it's probably easier to focus on providing easy-to-parse and stable outputs and leave the POST-logic in the CI/CD pipelines.
