### ISSUE TITLE
[Java] "NoTokenLocation" on @Attr({})

### ISSUE THREAD

**Issue by Mandawi** [semgrep/semgrep#2272]
**Describe the bug**
"NoTokenLocation Match returned an empty list" should instead just return an empty list for that metavar. Returning an error prevents it from detecting all possible attributes in RequireScope annotation.

**To Reproduce**
https://semgrep.dev/s/J9Xd

**What is the priority of the bug to you?**
P0 because I can't run this rule without it.

**Comment by mschwager** [comment]
Hi @Mandawi,

This looks like a Java parsing bug. cc @aryx who's familiar with the relevant parts of the codebase.

**Comment by aryx** [comment]
Ok I got this.

**Comment by ievans** [comment]
@Mandawi looks like this is fixed -- you should be able to verify by running with the `@develop` docker image -- and will be going out in the next release!

**Comment by Mandawi** [comment]
Thanks for the help 👍
