### ISSUE TITLE
[C#] Parse C# semgrep pattern via tree-sitter

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2280]
We usually use pfff to parse the semgrep patterns. We now often use tree-sitter to parse the code (e.g., for Java, Go, etc.)
but up until now we were still relying on pfff the the many semgrep extensions to the grammars to parse a pattern.
With C# we don't have a C# parser, even a basic one, so we need to rely on tree-sitter to also parse the pattern.
This is the first time we do that, even though @mjambon anticipated the need before by creating the semgrep-grammars/
repository. 

We need now to:

- [x] plug the tree-sitter C# grammar in semgrep-grammars
- [x] imitate what we do in pfff with sgrep_spatch_pattern and allow to parse just expression, or statement, or declaration (we can start with just expression
- [x] support metavariable for identifiers 
- [x] support ... at a few strategic places in the grammar (we can start with just in arguments)
- [x] convert the tree-sitter CST of a pattern to the generic AST pattern (the type ASTgeneric.any).

This is related to https://github.com/returntocorp/semgrep/issues/1392

**Comment by aryx** [comment]
@mjambon do you feel you could do that or you prefer me to do it?

**Comment by aryx** [comment]
cc @colleend because we will need to do something similar for Kotlin.

**Comment by mjambon** [comment]
@aryx Happy to do it. I should be able to start today.

Point 2 ("allow to parse just expression, or statement, or declaration") is not something I'm familiar with. Maybe it will be easy, I don't know.

**Comment by mschwager** [comment]
Can we get C# to alpha support? https://semgrep.dev/docs/status/#maturity-definitions :D

**Comment by ievans** [comment]
@mjambon @aryx from my limited understanding, this is now a critical path point for Lua, C#, and Kotlin. Should we prioritize beyond priority:low?

**Comment by aryx** [comment]
I bumped to medium (given we are almost all in vacation, I don't think we can put high for now).

**Comment by aryx** [comment]
bumped to high now that everyone is back from vacation and we need that for C#, Lua, and Kotlin.

**Comment by aryx** [comment]
I don't think the grammar.js in semgrep-csharp allows statement pattern. The toplevel compilation_unit accepts
a list of declarations but not a single statement or sequence of statements. We probably need to do the same than for expr
and so maybe something like __SEMGREP__PATTERN that precedes either an expression or statement or list of statements.
@mjambon

**Comment by aryx** [comment]
Maybe we can close this issue and create a separate one for extending the kind of C# pattern we can parse.
