### ISSUE TITLE
Add auditing details regarding rules actually applied in CI scans

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2286]
**Is your feature request related to a problem? Please describe.**

When I do a semgrep run in CI, for auditing purposes one should be able to trace back not just 
(a) what files were scanned, but also
(b) what were they scanned with. 

Let me explain:

In the dashboard each project identifies its policy:
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/6817500/102517216-a1b6d600-4044-11eb-8600-dd1520206b72.png">

If I navigate to the policy, I can see the rules and rulesets defined--at the moment. 
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/6817500/102520844-ff4d2180-4048-11eb-8e6e-1534e09be932.png">

Since there is no way to know if that policy definition has changed since the last run, there is then no way to know what rules were used in the last scan.

If, on the other hand, from the dashboard I navigate to the findings, that opens my CI build:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/6817500/102518826-9e244e80-4046-11eb-858e-f46dc57a3179.png">

In here, there is some very useful information. I like the new "list of commits" being shown--that helps address my "what files were scanned" point above. 👍 

As to "what were they scanned with" it also lists the policy in the CI build above, but again, that has no history so there is no way to know if it is a reflection of what rules were actually used in this CI build.

**Describe the solution you'd like**

Part 1: The simplest solution would be to list the contents of the policy, just like you have listed the commits. Now there are some turtles at play here (as in "turtles all the way down")... one could argue that any given rule or ruleset may also have been changed, so you still do not know for sure. True, but at least this would be an improvement. Furthermore, as I understand it, all rulesets are under source control so those could technically be uniquely identified, leaving only the question of any individual rules in a policy that may or may not have been updated. I submit that it is much more likely that rules are added to a ruleset than any individual rule gets edited, so this is a reasonably comprehensive solution.

Besides the list of rules and rulesets, it would be a useful metric to include how many rules are being used. Semgrep on the command line already does this, so I assume it would be simple to have semgrep-agent report it as well. (A total for the policy would be good; a count for each ruleset would be even better.)

Part 2: Ah, but let us listen in to a hypothetical conversation:

_Manager:_ So our scans our running 509 rules on every PR; sweet! That's good coverage, right? Nice job!
_Developer:_ Well, ummm, er, that 509 rule count encompasses rules from a few different languages; our codebase being Go and TypeScript is only using some of those 509 rules.
_Manager:_ Sure, makes sense. So how many rules are we actually using?
_Developer:_ Was that the phone? Sorry, got to take this...

➡️ The recommendation here, then, rather than just saying this:
```
ruleset 1: 202 rules
ruleset 2: 42 rules
ruleset 3: 97 rules
```
It would be really nice to see something like this...
```
ruleset 1: 202 rules total (54 rules applied)
ruleset 2: 42 rules (42 rules applied)
ruleset 3: 97 rules (0 rules applied)
``` 
or even this...
```
ruleset 1: 202 rules total (54 rules applied: 50 Go, 4 TypeScript)
ruleset 2: 42 rules (42 rules applied: 21 TypeScript, 20 JavaScript, 1 Go)
ruleset 3: 97 rules (0 rules applied)
```

**Comment by mschwager** [comment]
Hi @msorens,

Thanks for the feedback, we will discuss it today :+1:

**Comment by chmccreery** [comment]
To summarize the Slack conversation we had and make GitHub the source of all truth:
- As of yesterday, all findings on semgrep.dev/manage/findings (summary tab) indicate which policy and ruleset they came from
- Also as of yesterday, semgrep-action prints out not only the policy name that it used, but also the number of rules it ran
<img width="611" alt="Screen Shot 2020-12-18 at 1 18 54 PM" src="https://user-images.githubusercontent.com/25408780/102662391-99899400-4133-11eb-84a4-a6883ae9e6d6.png">

- The frontend does not show that we are tracking different versions of policies, but as of last week we are 
- In future work (hopefully early in 2021), the frontend will also be able to show older versions of your policies, and then the links on semgrep.dev/manage/findings will actually link to the correct _version_ of the policy it ran
- We do not yet keep track of different versions of rules/rulesets, but that it also on target for early 2021 when we re-do the entire registry backend
