### ISSUE TITLE
Ruby parser doesn't handle `rescue` blocks correctly

### ISSUE THREAD

**Issue by chgg-kboberg** [semgrep/semgrep#2287]
**Describe the bug**
Ruby parser doesn't correctly handle `rescue` blocks in function definitions, e.g.

```
def $METHOD(...)
  ...
end
```
should match
```
def someFunction(foo)
  someOtherFunction()
rescue SomeClass::Error
  errorHandler()
end
```

**To Reproduce**
https://semgrep.dev/s/gpde/

**Expected behavior**
Semgrep should find a match but does not.

**What is the priority of the bug to you?**
This is a P1.  You can work around this with explicit handling of `rescue`: https://semgrep.dev/s/Qwvo/
**Environment**
semgrep.dev

**Comment by mschwager** [comment]
Hi @chgg-kboberg,

Nice find, this is quite an odd bug. It looks like we successfully match when the optional `begin`/`end` are included: https://semgrep.dev/s/3eoo/.

Following along [here](https://www.rubyguides.com/2019/06/ruby-rescue-exceptions/) it looks like they are optional like you're example specifies. cc @aryx or @mjambon for a parsing assist.

**Comment by mjambon** [comment]
From @mschwager 's example https://semgrep.dev/s/3eoo/, it looks like a parsing error because the correct `end` isn't included in the match.
![image](https://user-images.githubusercontent.com/343265/102542064-177f6980-4066-11eb-99ee-a833ff16c897.png)

(but maybe it's something else)

**Comment by aryx** [comment]
Hopefully I can work on it next week.  A  it swamped this week with backlogs.
