### ISSUE TITLE
Autofix mega issue

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2294]
I'm creating this issue to track all our autofix feedback.

As it currently stands, [`autofix`](https://semgrep.dev/docs/experiments/overview/#autofix) is an experimental feature, which means it receives limited support. However, we have set aside time in the near future for `autofix` improvements. This issue will be useful for organizing some of that work and discussing improvements.

Current `autofix` issues:

- https://github.com/returntocorp/semgrep/issues/2324
- https://github.com/returntocorp/semgrep/issues/2295
- https://github.com/returntocorp/semgrep/issues/2209
- https://github.com/returntocorp/semgrep/issues/2183
- https://github.com/returntocorp/semgrep/issues/2051
- https://github.com/returntocorp/semgrep/issues/1946
- https://github.com/returntocorp/semgrep/issues/1917
- https://github.com/returntocorp/semgrep/issues/1916
- https://github.com/returntocorp/semgrep/issues/1226
- https://github.com/returntocorp/semgrep/issues/840

cc @msorens who has provided ample, great feedback in this department, and may be interested.

**Comment by emjin** [comment]
👋

**Comment by dan5382** [comment]
@mschwager @emjin @mjambon A number of related tickets here seem to have gone stale-ish. Can we update relevancy here or is this all stale?

**Comment by ievans** [comment]
All but two of these issues have been fixed, and that one isn't autofix specific, so I'm going to close this mega-issue. Thanks @mschwager
