### ISSUE TITLE
[Go] timeout on protobuf generated code

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2296]
from:
https://r2c-community.slack.com/archives/G01FXEAJJHK/p1607345861005600

it looks like go.lang.security.audit.net.wip-xss-using-responsewriter-and-printf.wip-xss-using-responsewriter-and-printf

and in particular
```
[30.255 Info       Main.Dune__exe__Main ] raised Timeout in timeout_function for service.twirp.go
[30.255 Info       Main.Dune__exe__Main ] critical exn while matching ruleid 0..1
[30.255 Info       Main.Dune__exe__Main ] full pattern is: ...
var $T = "..."
...
$W.Write([]byte(fmt.$PRINTF($T, ...)), ...)
```

is causing some timeout on code generated by protoc-gen-twirp v5.12.0 and it's 5700 lines of code,

Maybe we can find outthere other code generated by protoc-gen-twirp so we can reproduce and try to
debug the issue on real code.

**Comment by nbrahms** [comment]
@aryx What's the priority for this issue?

**Comment by aryx** [comment]
If we can't find a public codebase that we can reproduce the timeout on, we can't easily fix it.
Also the work by @mjambon on improving semgrep performance should match perfectly here. It's a A ... B type of pattern.

**Comment by aryx** [comment]
Note that the user, Eva, used to have semgrep never finishing on some private Go repositories. With some of the fix
that went to 0.34 we actually now detect the problem (too many matches) and at least skip the rule and file and try the other stuff,
so the remaining stuff is lower priority.
