### ISSUE TITLE
Duplicates across rulesets should be eliminated

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2298]
**Describe the bug**
I recently changed a policy from one ruleset (`r2c-ci`) to multiple rulesets. Upon adding a dummy test file to trigger a finding in CI, the finding was reported twice. I have not verified, but I suspect the rule is present in two rulesets so is therefore reporting twice:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/6817500/102645668-b021f200-4117-11eb-9f99-97b380f20780.png">

**To Reproduce**
Here are the rulesets I used:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/6817500/102645936-1c9cf100-4118-11eb-9336-64c7c50fdaa9.png">

I then just added a test.py file to my repository with the contents `5 == 5`.

**Expected behavior**
Finding reported just once.

**Screenshots**
NA

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

P2 -- regular

**Environment**
v 0.35.0

**Comment by msorens** [comment]
Another data point. I was wondering why my open findings jumped from 21 to 25 just recently. I took the real output of my nightly semgrep run on my codebase, trimmed the output, and sorted to show the issue succinctly:
```
dgryski.semgrep-go.errtodo.err-todo > components/automate-deployment/pkg/a1upgrade/filemover.go:217
dgryski.semgrep-go.errtodo.err-todo > components/automate-deployment/pkg/client/deployer.go:1107
dgryski.semgrep-go.errtodo.err-todo > components/automate-gateway/gateway/services.go:1018
dgryski.semgrep-go.errtodo.err-todo > components/compliance-service/inspec-agent/runner/runner.go:339
dgryski.semgrep-go.errtodo.err-todo > components/infra-proxy-service/storage/postgres/orgs.go:181
dgryski.semgrep-go.errtodo.err-todo > components/infra-proxy-service/storage/postgres/servers.go:107
dgryski.semgrep-go.errtodo.err-todo > components/ingest-service/pipeline/publisher/bulk_publisher.go:55
dgryski.semgrep-go.errtodo.err-todo > components/session-service/server/server.go:479
dgryski.semgrep-go.errtodo.err-todo > components/teams-service/storage/postgres/postgres.go:243
dgryski.semgrep-go.errtodo.err-todo > lib/authz/project_rules_update_workflow.go:129
go.lang.security.audit.net.use-tls.use-tls > components/authn-service/server/server.go:108
go.lang.security.audit.net.use-tls.use-tls > components/authn-service/server/server.go:108
go.lang.security.audit.net.use-tls.use-tls > components/authn-service/server/server.go:108
go.lang.security.audit.net.use-tls.use-tls > components/compliance-service/compliance.go:649
go.lang.security.audit.net.use-tls.use-tls > components/compliance-service/compliance.go:649
go.lang.security.audit.net.use-tls.use-tls > components/compliance-service/compliance.go:649
go.lang.security.audit.net.use-tls.use-tls > components/ingest-service/rest/rest.go:52
go.lang.security.audit.net.use-tls.use-tls > components/ingest-service/rest/rest.go:52
go.lang.security.audit.net.use-tls.use-tls > components/ingest-service/rest/rest.go:52
go.lang.security.audit.net.use-tls.use-tls > integration/helpers/requestbin/requestbin.go:87
go.lang.security.audit.net.use-tls.use-tls > integration/helpers/requestbin/requestbin.go:87
go.lang.security.audit.net.use-tls.use-tls > integration/helpers/requestbin/requestbin.go:87
ruby.lang.security.no-eval.ruby-eval > components/automate-workflow-ctl/lib/automate_ctl/ctl.rb:33
ruby.lang.security.no-eval.ruby-eval > components/automate-workflow-ctl/lib/ctl-helpers/delivery_config.rb:23
ruby.lang.security.no-eval.ruby-eval > components/automate-workflow-ctl/lib/installer/config.rb:3
```
I am guessing that `go.lang.security.audit.net.use-tls.use-tls` appears in 3 different rulesets since each such finding is reported in triplicate.

Fallout from this issue:
(1) It is more tedious to sift through the results to mitigate issues.
(2) This is skewing the data on the analytics dashboard, and this issue is why my open findings went from 21 to 25--apparently one of the additional rulesets I recently added includes the same rule.

**Comment by DrewDennison** [comment]
@brendongo @mschwager @colleend  seems like an easy perf win to `list(set(all_rules)` and a good first task. Any of you up for knocking this out for our next release?

**Comment by hlieberman-rd** [comment]
I'll take this @DrewDennison.  PR coming in the next few.
