### ISSUE TITLE
Clearly document that metavariables match all expressions, and how to exclude array assignment

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#2305]
I don't need to capture tokens with brackets (like `$SECRET[index]='...'`). But I have to, because there is `$SECRET = '...'` that I need. 

Is it possible to capture `$SECRET = '...'`  without `$SECRET[index]='...'` ?

https://semgrep.dev/s/1Zrl

**Comment by mschwager** [comment]
Hi there,

It does seem a bit odd that `$META = "..."` catches both of the following: https://semgrep.dev/s/rdzj/

And even including a `pattern-not` doesn't remove the additional finding: https://semgrep.dev/s/b7lq/

cc @aryx for another potential Python overmatch.

**Comment by dvyakimov** [comment]
Why it's not a bug? :)

**Comment by mschwager** [comment]
I believe this likely is a bug, I just wanted to confirm with one of our PA experts before treating it as such. Regardless, we likely won't have a fix implemented and released until after the new year :+1:

**Comment by nbrahms** [comment]
@dvyakimov In Semgrep, a metavariable matches any expression. In this case, both `secret` and `secret[foo]` are expressions, so your metavariable matches both. To explicitly exclude the latter case, you'd want to use a `pattern-not` clause, as demonstrated in https://semgrep.dev/s/Q5kJ/.

I hope this helps.

I also realize we're probably lacking some documentation on this kind of use case, which likely caused the confusion here. I'll update this ticket to reflect our lack of documentation.

**Comment by nbrahms** [comment]
> And even including a `pattern-not` doesn't remove the additional finding: https://semgrep.dev/s/b7lq/
> 
This is probably really confusing, but the reason your `pattern-not` didn't work and mine (in https://semgrep.dev/s/Q5kJ/) did, is that I used a different name for the metavariable, and you got bitten by our metavariable-equivalence rules 😖

**Comment by minusworld** [comment]
@mschwager Where do you think the best place is for documenting this metavariable behavior?

**Comment by mschwager** [comment]
> @mschwager Where do you think the best place is for documenting this metavariable behavior?

Hmm, after the work on metavariable propagation, should we similarly disable metavariable matching across negation operators (`pattern-not`, `pattern-not-inside`)? The fact that these two examples have different behavior seems too counterintuitive to me: https://semgrep.dev/s/b7LE/, https://semgrep.dev/s/Q5kJ/.

Is there anywhere where we're relying on this behavior and/or intend to make use of this matching across negation?

**Comment by mschwager** [comment]
As far as docs go, this will be the place to update: [metavariable matching](https://semgrep.dev/docs/writing-rules/rule-syntax/#metavariable-matching). Note that none of the examples under that header make use of a negation operator, so perhaps this was just overlooked.

**Comment by minusworld** [comment]
> Is there anywhere where we're relying on this behavior and/or intend to make use of this matching across negation?

I found one example of what looks like intentional matching across negation patterns. I'm not sure if this is what you mean. It looks like it relies on `$INJECT` being the same in `pattern` and `pattern-not-inside` clauses.

```
typescript/react/security/audit/react-http-leak.yaml
severity:info rule:same-meta: INJECT
29:- pattern: |
30:    <$EL src={$INJECT} />
31:- metavariable-regex:
32:    metavariable: $EL
33:    regex: frame|iframe|img|input|script|audio|source|track|embed|video
34:- pattern-not: |
35:    <$EL src="..." />
36:- pattern-not-inside: |
37:    import $INJECT from "...";
```
