### ISSUE TITLE
Parse_info.NoTokenLocation on React HTML attributes with no value

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2306]
https://semgrep.dev/s/N4qn/

The offending code appears to be:

```html
<video autoPlay muted loop playsInline height="356" crossOrigin="anonymous">
  <source src={semgrepCiDemoWebm} type="video/webm" />
  <source src={semgrepCiDemoMp4} type="video/mp4" />
    This video format is not supported.
</video>
```

However, if I change this code to the following then everything works as expected:

```html
<video autoPlay="" muted="" loop="" playsInline="" height="356" crossOrigin="anonymous">
  <source src={semgrepCiDemoWebm} type="video/webm" />
  <source src={semgrepCiDemoMp4} type="video/mp4" />
    This video format is not supported.
</video>
```

Note that empty attribute syntax is valid: https://html.spec.whatwg.org/multipage/syntax.html#attributes-2

**Comment by mschwager** [comment]
cc @aryx @mjambon

**Comment by mschwager** [comment]
Note, re-enable `typescript.react.best-practice.react-props-in-state.react-props-in-state` when this is fixed.

**Comment by nbrahms** [comment]
This looks to be more complicated than just parsing of jsx props:

https://semgrep.dev/s/dKjX/

is a more minimal example. Note that deleting either `<section>` will allow the rule to succeed, even if the `<video>` tag is left as is (with default-true attributes).

**Comment by nbrahms** [comment]
I'm pretty sure this is something funky with literal rendered text including "//", combined with default-true JSX attributes:

https://semgrep.dev/s/Zvgx/

Removing the `//` in the text causes the match to succeed.

**Comment by nbrahms** [comment]
https://semgrep.dev/s/ndXg/, which is semantically equivalent, also succeeds

**Comment by nbrahms** [comment]
This could be a problem:

![image](https://user-images.githubusercontent.com/2490631/103047218-a47f6280-453f-11eb-9038-964da63cc606.png)

cc. @mjambon

**Comment by mjambon** [comment]
@nbrahms's example https://semgrep.dev/s/Zvgx/ now works with or without the `//`. 

The original (big) https://semgrep.dev/s/N4qn/ still doesn't find a match. It needs simplification before we can determine what's wrong.

**Comment by mjambon** [comment]
@mschwager I'm not able to reproduce a case that works. I tried replacing this
```
<video autoPlay muted loop playsInline height="356" crossOrigin="anonymous">
```
by this
```
<video autoPlay="" muted="" loop="" playsInline="" height="356" crossOrigin="anonymous">
```
but there's still no match.

If you happen to remember what should match the pattern, that would help.

**Comment by mschwager** [comment]
> If you happen to remember what should match the pattern, that would help.

IIRC this bug was just fixing the `NoTokenLocation`, not necessarily producing a finding!
