### ISSUE TITLE
PHP pattern support for object methods

### ISSUE THREAD

**Issue by rezen** [semgrep/semgrep#2307]
For PHP Semgrep doesn't seem to support pattern matching on object methods, here is a quick sample you can try out. 

```
semgrep --version
# 0.34.0

echo '<?php $wpdb->get_var("SELECT * FROM wp_users WHERE email = $_POST['email']");' \
  | semgrep --pattern '$wpdb->$METHOD(<... $ARGS ...>)' -v --debug --lang php -
```

## Tests

| rule                                 | code                                                                         | match? |
|--------------------------------------|------------------------------------------------------------------------------|--------|
| $wpdb->$METHOD(<... $ARGS ...>)  | <?php $wpdb->$get_var("SELECT * FROM wp_users WHERE email = $_POST[email]"); | Y      |
| $wpdb->$METHOD(<... $ARGS ...>)  | <?php $wpdb->get_var("SELECT * FROM wp_users WHERE email = $_POST[email]");  | N      |
| '$wpdb->get_var(<... $ARGS ...>) | <?php $wpdb->get_var("SELECT * FROM wp_users WHERE email = $_POST[email]");  | Y      |

**Comment by mschwager** [comment]
Hi @rezen,

Interesting, that behavior does seem odd. I've created some live editor links to quickly test:

- https://semgrep.dev/s/x1d0/
- https://semgrep.dev/s/OPlR/
- https://semgrep.dev/s/eLZ0/

It does look like our object method detection is buggy here.

Please note that our [PHP support is currently in alpha](https://semgrep.dev/docs/status/) and will be best-effort. With that being said, bug reports like this are what help us improve our support! So thank you for that. Our team currently has limited availability until after the new year, but I suspect we can fix this after.

**Comment by rezen** [comment]
Glad to hear! I considered filing after Christmas, hoping no one was around 🎉 but I knew there was a risk of me forgetting so I submitted 😄
