### ISSUE TITLE
Couldn't escape '^' symbol in regexp (python)

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#2310]
Somethig wrong with symol '^' escaping in regexp
https://semgrep.dev/s/PJee

**Comment by dvyakimov** [comment]
For this moment we found a workaround:
`- pattern-where-python: "not (vars['$T'].startswith('\"^') and vars['$T'].endswith('$\"'))"`

but it will be cool to fix this issue or explain my problem

**Comment by underyx** [comment]
Hey @dvyakimov, thanks for the report! Just wanted to let you know that our team is taking time off for the holidays until January 4th, and we'll have a look at this issue then 👍

**Comment by mschwager** [comment]
Huh, looks like we have some odd behavior with the inline [string matching](https://semgrep.dev/docs/writing-rules/pattern-syntax/#string-matching) functionality.

* In Python I can match a literal `^` by backslash escaping with `\^`: https://semgrep.dev/s/kXxe/
* In Go a single `\^` escape produces a pattern parse error: https://semgrep.dev/s/wedB/
* And in Go a double `\\^` escape parses correctly, but doesn't find the expected line: https://semgrep.dev/s/x18l/

cc @aryx who may have to dig into the PCRE string matching code.

**Comment by aryx** [comment]
I think we want to use PCRE matching for the inline string matching. That should solve some problems.
