### ISSUE TITLE
semgrep fails to match sinatra route definition fragments

### ISSUE THREAD

**Issue by devd** [semgrep/semgrep#2317]
**Describe the bug**
Writing a rule to catch new routes on sinatra fails. trying to match `route $METHOD, $PATH do` fails as an invalid pattern; the pattern `route  ...` works but it kinda limits any future things I can do with meta variable matching. 

**To Reproduce**
https://semgrep.dev/s/devd:sinatra-new-route

Change the `route ...` to `route $METHOD, $PATH do` and see the error

**Expected behavior**
The line is matched and $METHOD and $PATH match correctly to the relevant method and path definitions

**What is the priority of the bug to you?**
P2

**Comment by nbrahms** [comment]
@devd Right now I don't think we support matching only a fragment of the `do...end` control block like you're writing.

Instead, you could match the complete block as so (https://semgrep.dev/s/6nJY/):

```yaml
pattern: |
    route $METHOD, $PATH do
         ...
    end
```

Alternatively, you could just write:

```yaml
pattern: route $METHOD, $PATH, $BLOCK
```

which also matches just fine.

However, putting myself in your role, I can imagine you want to just match the route definition line and not the action block itself. In this case I'd imagine you'd want to write (https://semgrep.dev/s/oxqd/):

```yaml
  patterns:
    - pattern: |
        route $METHOD, $PATH
    - pattern-inside: |
        route $METHOD, $PATH do
            ...
        end
```

This does not match (although it parses just fine).

I think fundamentally this is a request to match curried patterns. That is, any function invocation:
`f(a, b, c)` we should be able to represent in a curried form: `f(a,b)(c)`, so you want to be able to match the initial fragment `f(a, b)`.

If we turn this back into your use case here, the Sinatra route in Ruby is just syntactic sugar for:
```ruby
action = Proc.new do
    ...
end

route(:get, 'my/path', action)
```

And you would want to match with what is syntactically equivalent to:
```ruby
route($METHOD, $PATH)
```

So we can see this reduces to the curried function matching idea.

Now the question is: should we support this in Semgrep or not? For the Sinatra case it's intuitive, but I can imagine this being rather surprising in explicitly procedural languages like C or Java.

CC. @aryx @mjambon @colleend for thoughts.

**Comment by nbrahms** [comment]
As a workaround, I realized you could just write:
```yaml
  patterns:
    - pattern: |
        $PATH
    - pattern-inside: |
        route($METHOD, $PATH, $BLOCK)
```

See https://semgrep.dev/s/zvdP/

**Comment by devd** [comment]
ohh interesting. I didn't realize semgrep would be smart enough about handling the syntactic sugar (that is, I can just do `route($METHOD, $PATH, $BLOCK)`). I think for now that should be sufficient so I think you can also close this fwiw -- as you mention, it could be a feature request now and I don't believe its that necessary.

**Comment by nbrahms** [comment]
> ohh interesting. I didn't realize semgrep would be smart enough about handling the syntactic sugar (that is, I can just do `route($METHOD, $PATH, $BLOCK)`). I think for now that should be sufficient so I think you can also close this fwiw -- as you mention, it could be a feature request now and I don't believe its that necessary.

Awesome, glad to hear this works for you. Ideally Semgrep is supposed to handle syntactic sugar well (semantic equivalences after all), and we do get it right in a few cases ;) .

**Comment by aryx** [comment]
you can probably also do 'route $METHOD, $PATH, ...'
