### ISSUE TITLE
Support for properties files in generic matching

### ISSUE THREAD

**Issue by nightwatchcyber** [semgrep/semgrep#2321]
It would be nice to have support for searching properties files in the generic matching. For example, a file like this:

```
# Comments
property1=foobar1a,foobar1b
property2=foobar2a;foobar2b
property3=foobar3a
```

There are several issues preventing the existing mechanism from working:
1. The "..." operator spans multiple lines while in properties it should end at the end of the line.
2. The "..." operator stops are things like ";" and "," which are legal values.
3. Comments "#" should be ignored.

**Comment by dlukeomalley** [comment]
@mjambon Tagging you for context and thoughts.

Thank you @nightwatchcyber for the issue 🙏
