### ISSUE TITLE
Parser doesn't handle either C attributes or Macros Quite right 

### ISSUE THREAD

**Issue by PhillipNordwall** [semgrep/semgrep#2323]
**Describe the bug**
I am getting inconsistent behavior when using attributes and macros, where C code that parses fine with clang and gcc doesn't quite work with semgrep. But it is a bit inconsistent. See the code examples in the reproducers listed. They should have similar behavior but don't.

I originally ran into this with https://github.com/freebsd/freebsd-src/blob/main/usr.bin/xinstall/xinstall.c
but my example is much more trimmed down.

**To Reproduce**
https://semgrep.dev/s/PhillipNordwall:Odd_break_in_test_code_01
https://semgrep.dev/s/PhillipNordwall:Odd_break_in_test_code_02

**Expected behavior**
I would expect the error to be near the macro usage, or consistent on both the test code above

**What is the priority of the bug to you?**
P2

**Environment**
Ran local, but verified with semgrep.dev

**Comment by dlukeomalley** [comment]
Thank you @PhillipNordwall for filing the detailed ticket. Queued up to chat about this with the team this week.

**Comment by aryx** [comment]
Sorry for our late reply, but semgrep does not use internally gcc or clang; it parses the code as-is, which has some advantages (it is usually faster to not analyze all the included files like gcc/clang do, it does not require to know how to build files (which -I and -D to use), but is limited.
The C parser in semgrep recognizes some of the cpp idioms, but not all of them.

**Comment by mjambon** [comment]
@aryx here's a series of simpler examples. They differ only by the body of the macro `A`, which is not used.

ok https://semgrep.dev/s/wxxN:
```
#define A (42)

int zero(int i __attribute__ ((__unused__)))
{
        return 0;
}
```
parse error https://semgrep.dev/s/kLLO/:
```
#define A ()

int zero(int i __attribute__ ((__unused__)))
{
        return 0;
}
```
parse error https://semgrep.dev/s/xYY0:
```
#define A []

int zero(int i __attribute__ ((__unused__)))
{
        return 0;
}
```
ok https://semgrep.dev/s/O11R/: 
```
#define A {}

int zero(int i __attribute__ ((__unused__)))
{
        return 0;
}
```
parse error https://semgrep.dev/s/e440/:
```
#define A }

int zero(int i __attribute__ ((__unused__)))
{
        return 0;
}
```
None of the parse errors above are expected.
