### ISSUE TITLE
Support more complex auto-fixes with multiple fixes embedded in different parts of the pattern

### ISSUE THREAD

**Issue by aantn** [semgrep/semgrep#2324]
I would like to implement a rule that identifies potential optimizations in Python where the user can use a set instead of a list for membership tests. For various reasons (see below) it is very difficult to impement an autofix for such a rule today.

Here is an example of code that can be optimized:

```
# creation
whitelist = list()

# initialization
for i in range(1000):
    whitelist.push(i)

# lookups in loop
for i in some_iterator:
    if i in whitelist:
        something()
```

There are two possible fixes for this code. The first fix is:
```
# creation
whitelist = set()           # this was changed

# initialization
for i in range(1000):
    whitelist.add(i)        # this was changed

# lookups in loop
for i in some_iterator:
    if i in whitelist:
        something()
```

The second fix is:
```
# creation
whitelist = list()

# initialization
for i in range(1000):
    whitelist.push(i)

whitelist = set(whitelist)   # this was added

# lookups in loop
for i in some_iterator:
    if i in whitelist:
        something()
```

I would like to write a fix that looks something like this. (Note that I've added some pattern-not-inside conditions here which aren't necessary for fix 2 as opposed to fix 1, but they help illustrate some issues later on.)
```
rules:
- id: use_set_not_list
  patterns:
    - pattern-not-inside: |
        ...
        ... = $X[...]
        ...
    - pattern-not-inside: |
        ...
        $X[...] = ...
        ...
    - pattern-not-inside: |
        ...
        ... = $X[...]
        ...
    - pattern-inside: |
        $X = list($INIT)
        ...
        for $Y in $Z:
            ...
            ... = <... ... in $X ...>
    - pattern: |
        for $Y in $Z:
            $...CONTENTS
  fix: |
        $X = set($INIT)
        for $Y in $Z:
            $...CONTENTS
```

Today you can't capture a block like I do with $...CONTENTS 

There are really fourfundamental challenges here:
1. Autofix replaces an entire pattern but what I really want to do is insert new content above an existing part of the pattern. i.e. use something like $...CONTENTS. I can't use a regex here for multiple reasons - e.g. if I tried searching for `for $Y in $Z:` then that could backfire if there were two such embedded loops.
2. There is only one autofix per rule but what I really want is multiple autofixes.
3. The whole logic for fixes is tightly coupled to the logic of matching, but sometimes you want to match according to one pattern and then fix according to different logic. (According to another pattern?)
4. For the first suggested fix I actually want to apply different fixes to different parts of the pattern. Even if multiple fixes on the same pattern were supported, this wouldn't be possible because part of what needs replacing is inside the `pattern-inside` block. There are multiple `pattern-inside` blocks so it is unclear how you would support attaching fixes to a `pattern-inside` block. (Is the issue with #1699 similar or is that fundamentally a different issue?) It seems to me that pattern-inside is generally awkward for stuff like this and it would be simpler to fix this if there was block like `pattern-sequences` which you could use here like this:
```
rules:
- id: use_set_not_list
  pattern-sequence:
    # match creation
    - pattern: |
        $X = list($INIT)
    # match initialization
    - patterns:
      - pattern:|
        ...
      - pattern-not: |
        ...
       $X[...] = ...
        ...
      - pattern-not: |
        ... = $X[...]
    # match lookup in loop
    - pattern: |
        for $Y in $Z:
            ...
            ... = <... ... in $X ...>
```

The advantage here is that you have three clear sequential parts of the pattern and it would be easier to specify conditions on each one and apply different fixes to each part.

**Comment by mschwager** [comment]
Hi @aantn,

[`autofix`](https://semgrep.dev/docs/experiments/overview/#autofix) is currently an experimental feature, so support will be limited. However, we are planning on improving its functionality in the near future, and we're tracking that in https://github.com/returntocorp/semgrep/issues/2294. I'll include this issue there :+1: 

Thank you for the very comprehensive write-up :)

**Comment by aantn** [comment]
Yes, understood. I don't expect support for this.

**Comment by xmo-odoo** [comment]
I don't know if it's strictly related to this, but it's a bit similar to this bit:

> Autofix replaces an entire pattern but what I really want to do is insert new content above an existing part of the pattern. i.e. use something like $...CONTENTS. I can't use a regex here for multiple reasons - e.g. if I tried searching for for $Y in $Z: then that could backfire if there were two such embedded loops.

autofix currently doesn't support or understand ellipsis, and not all ellipsis can be replaced by metavars, so given a pattern like:
```
          var $X = require("something");
          ...
          $X.foo(...)
```
i'm not sure there's a way to create an autofix, I don't think there's a way to match varargs to a metavariable, let alone "an arbitrary amount of code", is there?

**Comment by xmo-odoo** [comment]
oh god why enable this thing?

**Comment by xmo-odoo** [comment]
fucking hell and how do I reopen this exactly?
