### ISSUE TITLE
ruby: explain how to match any string template (originally filed as a bug)

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2331]
**Describe the bug**

User expects the semgrep pattern `"..."` to match a ruby string written as `"Hello, #{name}!"` (string interpolation) but it doesn't match in the current version of semgrep.

**To Reproduce**

https://semgrep.dev/s/zvyP/

**Expected behavior**

It should match because it seems natural due to usage of double quotes to delimit the string template.

**Screenshots**

![image](https://user-images.githubusercontent.com/343265/103695106-d71e5780-4f50-11eb-97c7-0fda1c9a4b29.png)

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

**Comment by nbrahms** [comment]
@mjambon I think we mean `"..."` to explicitly mean a "constant string", so it shouldn't match in this case. That way we can realistically write rules that, e.g., allow hard-coded SQL strings, but not interpolated SQL strings.

**Comment by mjambon** [comment]
@nbrahms makes sense.

It's a question of documentation, then. Wherever the `"..."` syntax is presented, the reason for matching only constant strings should be explained. I suggest adding a commented example in here:

![image](https://user-images.githubusercontent.com/343265/103696320-01711480-4f53-11eb-9d85-6a6739864dcc.png)

**Comment by minusworld** [comment]
@colleend Is it possible to make a semgrep-core test for this and get it into a cheatsheet as well?

**Comment by colleend** [comment]
yep, we can add to the strings tests 👍

**Comment by mschwager** [comment]
Similarly, we don't match Python f-strings with a string literal: https://semgrep.dev/s/9ole/

**Comment by fcsonline** [comment]
As a workaround, I was able to match an interpolation in a string with this combination of patterns:

```yaml
  patterns:
    - pattern: I18n.t(<... $X ...>)
    - pattern-not: I18n.t("...")

```

**Comment by mjambon** [comment]
The solution here is to use a deep expression as @fcsonline showed above ^. I see that the cheatsheet now covers the case of `"Hello, #{name}!"` not being matched by `...`. Closing!
