### ISSUE TITLE
Ability to upvote or downvote rules to crowdsource data

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#2339]
**Is your feature request related to a problem? Please describe.**
Requested by an external user, who is running other people's rules and feeling the need to create overrides for some noisy rules.

**Describe the solution you'd like**
Some kind of way to communicate which rules are too noisy and crowdsource that type of information 

**Describe alternatives you've considered**
We could auto-detect this somehow like with our fix-rate feature but looking at rules one by one and across all users.

**Additional context**
See number 5 in this issue https://github.com/returntocorp/semgrep/issues/2332

**Comment by dlukeomalley** [comment]
I can't wait to put global fix-rate data on rulesets and rules as part of the registry 🎉
