### ISSUE TITLE
[C#] add tests to reach "alpha" maturity level

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2345]
I think the main blocker is to handle sequence of statements in C# semgrep pattern.

**Comment by aryx** [comment]
we are at 97% parsing stats, so above the 90% required by https://semgrep.dev/docs/status/#maturity-definitions

**Comment by aryx** [comment]
related work I did for lua: https://github.com/returntocorp/semgrep/pull/2344

**Comment by Sjord** [comment]
This issue is still relevant and should be prioritized.
