### ISSUE TITLE
Configure files to match when running semgrep on a directory

### ISSUE THREAD

**Issue by becojo** [semgrep/semgrep#2348]
**Is your feature request related to a problem? Please describe.**

I'm running rules that apply to `ruby` and Semgrep does not match Ruby code contained `Gemfile` when it's ran on a directory. It appears to only look at files with the `.rb` extension. 

**Describe the solution you'd like**
I'd like to have the option to configure what files should be matched for a given language. 

For my purpose, I'd like semgrep to see files from this glob pattern `Gemfile, *.gemspec, *.rb` as Ruby code. 

**Describe alternatives you've considered**

It's possible to get the results by running semgrep and providing the path to the Gemfile (ie: `semgrep -f rules.yml Gemfile`) but it won't detect the file in the current directory by simply running `semgrep -f rules.yml`.

**Additional context**

**Comment by mschwager** [comment]
Hi @Becojo,

Unfortunately, we don't have a great, built-in mechanism for achieving this, but a little help from `find` should do the trick:

```
$ echo '1 == 1' > foo/bar/Gemfile
$ echo '1 == 1' > foo/bar/test.rb
$ echo '1 == 1' > foo/bar/test.gemspec
$ tree foo/
foo/
└── bar
    ├── Gemfile
    ├── test.gemspec
    └── test.rb

1 directory, 3 files
```

```
$ semgrep -l ruby -e '$X == $X' $(find /tmp/foo \( -name "*.rb" -o -name "*.gemspec" -o -name "Gemfile" \))
/tmp/foo/bar/Gemfile
1:1 == 1

/tmp/foo/bar/test.gemspec
1:1 == 1

/tmp/foo/bar/test.rb
1:1 == 1
ran 1 rules on 3 files: 3 findings
```

Does this work for you? Note we have an existing issue to either make `--include` additive, or add new functionality for this behavior: https://github.com/returntocorp/semgrep/issues/1099

**Comment by becojo** [comment]
I'd prefer the additive includes. I'll close this in favor of #1099.
