### ISSUE TITLE
PHP Class in pattern results in parsing error

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#2356]
**Describe the bug**
When using `class $Class` or `class SomeThing` in a pattern, it results in an invalid pattern error

**To Reproduce**
https://semgrep.dev/s/gLpR

**Expected behavior**
There should be a match

**What is the priority of the bug to you?**
P1

**Environment**
semgrep.dev and semgrep cli 0.35.0 on MacOSX (installed via brew)

**Notes**
- Using a pattern like `pattern: public function __destruct() { ... }` also produces a parsing error. Seems like to be related to the `public` keyword
- There is an extremely weird behaviour when trying to match functions/methods, see https://semgrep.dev/s/Q5wJ which won't have any match, but then adding `...` before any `function __` (ie `... function __toString() { ... }`) will result in one match

**Comment by mschwager** [comment]
https://semgrep.dev/s/gLpR?version=develop works! This fix will go out in the next release.

**Comment by aryx** [comment]
Also works with the new release: https://semgrep.dev/s/gLpR?version=0.38.0
