### ISSUE TITLE
R Support

### ISSUE THREAD

**Issue by zythosec** [semgrep/semgrep#2360]
**Is your feature request related to a problem? Please describe.**
Add support for the [R](https://www.r-project.org/about.html) programming language

**Additional context**
R provides a wide variety of statistical (linear and nonlinear modelling, classical statistical tests, time-series analysis, classification, clustering, …) and graphical techniques, and is highly extensible. It used frequently for data science and packages such as [R-Shiny](https://shiny.rstudio.com/) are used to build complete web applications, so it would be useful to identify any vulnerabilities that could arise.

**Comment by zythosec** [comment]
FYI I've started this work in my forks of semgrep-grammars and ocaml-tree-sitter.

**Comment by underyx** [comment]
Wow, that's wonderful news! We're happy to help you along the way if there's anything you need.

I was curious so I looked and found that [lintr](https://github.com/jimhester/lintr) exists thus far for static analysis for R. I also found a formatting tool but not much else. I wonder how prevalent static analysis is in the R ecosystem currently 🤔

**Comment by zythosec** [comment]
Thanks! [tree-sitter-r](https://github.com/r-lib/tree-sitter-r) exists so R was pretty straight forward to add. The only other static analysis tool I could find was within R itself, [CodeDepends](https://cran.r-project.org/web/packages/CodeDepends/vignettes/intro.html), so I'm not sure how prevalent it is either.

**Comment by ievans** [comment]
This is super exciting @zythosec! I also wanted to mention that a good number of the people adding new languages are on Slack (https://r2c.dev/slack) if you ever have any urgent questions or want to talk about design decisions for new language additions.

**Comment by aryx** [comment]
@zythosec I think we're done with refactoring semgrep, pfff, and ocaml-tree-sitter to make it easier for external contributors to add languages. Let us know if you need some help with the new code organization and flow.

**Comment by keithdouglas** [comment]
Any news on this idea? I've had trouble starting this sort of thing up myself and was glad to find this. I have had my R users complain that lintr is just not useful - and yet we want to adopt static code analysis for security purposes for all our languages, so I was hoping maybe semgrep would help. If there's a way to get an update so I can try building rules (rather than flailing/failing to get started with tree-sitter, etc.) I'd be happy to my hands at contributing those to help everyone out.

**Comment by aryx** [comment]
Done @keithdouglas . It should be part of the next release of semgrep. You should be able to start to write
rules for R! You can then contribute them to our semgrep-rules repository, for other to benefit from your rules.

**Comment by keithdouglas** [comment]
Excellent, thanks for your work on this! I will be bringing this up with my colleagues.

**Comment by aryx** [comment]
We're now at 99.9% correct parsing! https://dashboard.semgrep.dev/metric/semgrep.core.R.parse.pct
