### ISSUE TITLE
Find classes extends in JavaScript

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#2369]
**Is your feature request related to a problem? Please describe.**
Unable to find classes in JavaScript that extends specific class:

https://semgrep.dev/s/4xBZ/

```javascript
class Test1 extends MyClass {

  constructor() {
    this.x = 1;
  }

}
```

```
class $NAME extends MyClass {
    ...
}
```

while this feature works for TypeScript: https://semgrep.dev/s/PJ9E/

**Comment by tvfmmfvt** [comment]
New .. hi .. relieving :

JavaScript extends usu via explicit sted _of_ global namespaces, variables bound only ish within closures .

Skip the math,

ref JavaScript Patterns, oreilly, first for antipatterns it's a soup actually

Typescript has a rigorous type system.

**Comment by aryx** [comment]
What is this spam comment above?

Edit: deleted

**Comment by aryx** [comment]
The dump of the AST is "null" when in Javascript mode, and correct when in typescript mode. Not sure what's going on.
At least it should say parse error if we return a null AST.

**Comment by mjambon** [comment]
Note that the tree-sitter parser for javascript works:

```
$ cat toto.js 
class Test1 extends MyClass {}
```

```
$ ./parse-javascript toto.js
program
| declaration
|   class_declaration
|   | "class"
|   | identifier
|   | class_heritage
|   |   "extends"
|   |   expression
|   |   | identifier
|   | class_body
|   |   "{"
|   |   "}"
|   | automatic_semicolon
---
|   | Decl
|   |   Class_decl
|   |   | class
|   |   | Test1
|   |   |   | extends
|   |   |   |   Choice_this
|   |   |   |   | Id
|   |   |   |   | MyClass
|   |   |   "{"
|   |   |   "}"
|   |   |   ""
total lines: 2
error lines: 0
error count: 0
success: 100.00%
```

**Comment by nbrahms** [comment]
Fixed in current Semgrep
