### ISSUE TITLE
Track metavariable from aliased import in JS/TS

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#2382]
Currently unable to use metavar from `import * as $X from 'foobar'` in other patterns
example:

https://semgrep.dev/s/yddd
code
```javascript
import * as session from 'express-session';
session({})
```
rule
```
  - pattern: |
      $SESSION(...)
  - pattern-inside: |
      import * as $SESSION from 'express-session';
      ...
```
does not find anything (both TypeScript and JavaScript)

but able to tackle it when inside one pattern:
https://semgrep.dev/s/rddA
```
  - pattern: |
      import * as $SESSION from 'express-session';
      ...
      $SESSION(...)
```

**Comment by aryx** [comment]
If it works when inside one pattern, might be a semgrep-python issue when comparing metavars from different match?
@nbrahms ?

**Comment by inkz** [comment]
one more example that is not related to import aliases but have same issue with metavars matching:
https://semgrep.dev/s/7oo4/

code:
```javascript
import { Injectable, HttpService } from '@nestjs/common';

@Injectable()
export class AppService {
  constructor(private fetcher: HttpService) {}

  getSmth(): any {
    return this.fetcher.gets('http://localhost:3000/');
  }
}
```

the idea is to track call to injected service of HttpService type
works as one pattern:
https://semgrep.dev/s/Ekko/
```
  class $CN {
      constructor($HTTP: HttpService) {
          ...
      }

      $FN(...) {
        ...
        this.$HTTP.get(...);
        ...
      }
  }
```

does not work when split to `pattern-inside`+`pattern`
https://semgrep.dev/s/7oo4

```
    - pattern: |
        this.$HTTP.get(...);
    - pattern-inside: |
        class $CN {
            constructor($HTTP: HttpService) {
                ...
            }
            ...
        }
```

**Comment by Isaac0616** [comment]
@inkz @aryx Any updates on this issue?
I found that the problem in the first example is that the value of `$SESSION` is `'express-session'` when invoking and `session` when importing.
See https://semgrep.dev/s/8y4J.

Given that #285 was closed, what is the best way to find out a function call from a module?
Is there something similar to Python rule like `path.to.module.function(...)`
I want to write a rule like
```
  - id: dont-use-unsafeRedirect
    pattern-either:
      - patterns:
        - pattern-inside: |
            import * as $BROWSER from "modules/core/browser"
            ...
        - patterns:
          - pattern: $BROWSER.unsafeRedirect(...);
          - pattern-not: $BROWSER.unsafeRedirect("...");
      - patterns:
        - pattern-inside: |
            import {unsafeRedirect} from "modules/core/browser"
            ...
        - patterns:
          - pattern: unsafeRedirect(...);
          - pattern-not: unsafeRedirect("...");
    message: *unsafe_redirect_explanation
    languages: [typescript, javascript]
    severity: WARNING
```
However, the first `patterns` doesn't work because of the same problem.

**Comment by aryx** [comment]
👋

**Comment by ievans** [comment]
keep

**Comment by ievans** [comment]
@inkz this appears to be fixed now? https://semgrep.dev/s/yddd finds line 3

**Comment by inkz** [comment]
@ievans yes, all examples are working now. I believe it is safe to close.
