### ISSUE TITLE
--max-lines-per-finding does not work for json output

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#2387]
If I hide results of code I use `--max-lines-per-finding`

`semgrep --config s/weeX  --max-lines-per-finding 2`

But how can I hide results in JSON ? A piece of code feel up a lot of space in the file, although I need only to get the beginning and end of the function.

`semgrep --config s/weeX --json -o /path/to/path-semgrep.json --max-lines-per-finding 2`

**Comment by brendongo** [comment]
Hi @dvyakimov the `--max-lines-per-finding` is mostly intended just for the plain text output. Are you able to do some post processing of the json output. Something like this should remove all the lines fields from the json:

```
semgrep --config s/weeX --json | jq 'del(.results | .[].extra.lines)' > /path/to/path-semgrep.json
```

**Comment by dvyakimov** [comment]
Okay, thank you! But if you make it on your side, it will be much faster! :)
