### ISSUE TITLE
Add exit code meaning to documentation

### ISSUE THREAD

**Issue by dvyakimov** [semgrep/semgrep#2392]
Could you publish error list ?

I use semgrep as semantic analysis for my tool. I have installed semgrep inside the container as CLI. At some moment, he gave me 7 error code back, but I didn't find a description of the code until I found out that I was mistaken in the rule.

**Comment by brendongo** [comment]
Yeah looks like our docs are a little stale there. Will track updating that page in the docs with this issue.

For now this file might be useful https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/error.py#L18

**Comment by brendongo** [comment]
PR to update here: https://github.com/returntocorp/semgrep-docs/pull/75

**Comment by brendongo** [comment]
Exit codes are in docs: https://semgrep.dev/docs/cli-usage/
