### ISSUE TITLE
Azure Pipelines CI support

### ISSUE THREAD

**Issue by markchristensen-sl** [semgrep/semgrep#2398]
**Is your feature request related to a problem? Please describe.**
[Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/?view=azure-devops) isn't listed as a Semgrep CI [standalone provider](https://semgrep.dev/docs/integrations/).

**Describe the solution you'd like**
Instructions or support for integrating with Azure Pipelines.

**Additional context**
Using a Microsoft Hosted Ubuntu build agent, I'm able to successfully install Semgrep using a command line task. However, when running Semgrep --config=p/r2c-ci (path to SourcesDirectory), it doesn't find any files: ran 119 rules on 0 files: 0 findings

**Comment by jithurjacob** [comment]
It is working fine for me please check your path given.

**Comment by markchristensen-sl** [comment]
I'm using the following task:

```
- task: CmdLine@2
  inputs:
    script: |
      python3 -m pip install setuptools
      python3 -m pip install wheel
      python3 -m pip install semgrep
      export PATH="/home/vsts/.local/bin:$PATH"
      semgrep --config=p/r2c-ci $(Build.SourcesDirectory)
```
Using the [Sample ASP.NET Core application for Azure Pipelines](https://github.com/MicrosoftDocs/pipelines-dotnet-corel) in a source repo, Semgrep recognizes the files contained in Build.SourcesDirectory: ran 119 rules on 13 files: 0 findings

When using the same task in other pipelines with different custom code source repos, Semgrep reports running on zero files.

**Comment by jithurjacob** [comment]
@markchristensen-sl  - 

> I'm using the following task:
> 
> ```
> - task: CmdLine@2
>   inputs:
>     script: |
>       python3 -m pip install setuptools
>       python3 -m pip install wheel
>       python3 -m pip install semgrep
>       export PATH="/home/vsts/.local/bin:$PATH"
>       semgrep --config=p/r2c-ci $(Build.SourcesDirectory)
> ```
> 
> Using the [Sample ASP.NET Core application for Azure Pipelines](https://github.com/MicrosoftDocs/pipelines-dotnet-corel) in a source repo, Semgrep recognizes the files contained in Build.SourcesDirectory: ran 119 rules on 13 files: 0 findings
> 
> When using the same task in other pipelines with different custom code source repos, Semgrep reports running on zero files.

I didn't understand what you meant by using the same task in other pipelines. The output shown for the pipeline you have shown seems to be working. Did you try with --verbose flag to see if the path being scanned is as expected?

**Comment by markchristensen-sl** [comment]
I'm running Semgrep in two pipelines: one using the Sample ASP.NET as a source, and another custom .NET Core app. Both run Semgrep using $(Build.SourcesDirectory) as the source path, but only the Sample ASP.NET one recognizes the files.

I have used the --verbose Semgrep flag and added a pipeline variable, System.Debug=true, but neither return details for this issue.

**Comment by DrewDennison** [comment]
hi @markchristensen-sl thanks for opening an issue and we can work on our documentation in https://github.com/returntocorp/semgrep-docs or if you got this working, please feel free to make a PR to that repo and we'll happily merge it in

I wanted to see if you were still having the issue above or if you had worked around it? If so, feel free to ping me on our [community slack](https://r2c.dev/slack) and hopefully we can figure out what's up with the paths. Perhaps it's a relative vs absolute path issue?

**Comment by markchristensen-sl** [comment]
Hi, Drew. I did get it working and will proceed to close out this issue, thanks for checking in on this!

**Comment by DrewDennison** [comment]
@markchristensen-sl that's awesome to hear thanks!
