### ISSUE TITLE
Java not matching short type names

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#2400]
**Describe the bug**
In Java, Semgrep doesn't match the short name for a type when the FQN is used.

**To Reproduce**
https://semgrep.dev/s/Avv6

**Expected behavior**
expect to match lines 5,7,10 but it only matches 7 and 10. 

**What is the priority of the bug to you?**
Unknown (user reported)

**Environment**
v.37

**Comment by aryx** [comment]
If you wrote new ArrayList, how do we know which one you actually want? How do we know it's the java.util one? there could be another one in another library?
At least when you search for java.util.ArrayList we find the FQ one, and also the aliased one, but here you want the reverse, that is if you didn't specify much, here just new ArrayList, then you want semgrep to find all the possible one?

**Comment by libre-man** [comment]
But the other way around (specifying `java.util.ArrayList`) also doesn't work: https://semgrep.dev/s/DooW

**Comment by aryx** [comment]
Yes this one definitely sounds like a bug; we should manage the aliasing do at the first line when you imported the class.

**Comment by aryx** [comment]
This works on develop now: https://semgrep.dev/s/DooW?version=develop
