### ISSUE TITLE
Typed metavariables in Go doesn't match constants

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#2401]
**Describe the bug**
Constants are not matched when using typed metavariables in Go

**To Reproduce**
https://semgrep.dev/s/emjin:go-string

**Expected behavior**
Expected first two to both match

**What is the priority of the bug to you?**
Unknown, user bug

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by dlukeomalley** [comment]
@emjin @aryx @DrewDennison - What's the relatively priority of this issue and is it on-deck to be addressed? From the reporter on Slack:

> Hi, thanks a lot for an answer and the issue creation! I think, for some cases it is a significant impediment in writing rules on Go.

**Comment by aryx** [comment]
I think it is the next bug in the todo list of emma.
