### ISSUE TITLE
matching an "if" statement in C requires an extraneous terminating semicolon behind the statement metavariable

### ISSUE THREAD

**Issue by smcpeak** [semgrep/semgrep#2426]
https://semgrep.dev/s/ndqb?version=develop

In semgrep, to match an "if" statement, one uses the pattern "if ($E) $S;".  Note the final semicolon.  If the semicolon is omitted from the match expression, then semgrep says, "Pattern could not be parsed as a C semgrep pattern".

I think the semicolon should not be part of this match expression.  In C, some statements (such as an expression statement or a return statement) end in a semicolon, while other statements (such as a brace-enclosed compound statement or an "if" statement) do not.  In the quoted match expression, if "$S" were a complete statement, then the final semicolon would properly be interpreted as an unconditional empty statement following the conditional.

Note that semgrep will successfully match a statement like "if (1) {}", which has no semicolon, when using the quoted match expression above.

I think the syntax to match an "if" statement should be "if ($E) $S", with no semicolon.

**Comment by aryx** [comment]
I might have done that because of some grammar ambiguity ...

**Comment by aryx** [comment]
:wave:
