### ISSUE TITLE
java - constant propagation is broken in try/catch blocks

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [semgrep/semgrep#2435]
Looks like intra-procedural constant propagation is broken in Java when match is inside `try` / `catch` block!
https://semgrep.dev/s/fproulx-boostsecurity:java-const-propag-in-try-catch

**Comment by IagoAbal** [comment]
Thanks for reporting @fproulx-boostsecurity, I will take a look (fairly soon) !

**Comment by IagoAbal** [comment]
This is related to #1425, as of now we ignore try-catch-finally blocks. We log a warning, but the warning is not displayed by default. I'll see if it's easy to add support for try-catch-finally or otherwise I'll add some partial support.

**Comment by IagoAbal** [comment]
PR returntocorp/pfff#387 should make your example work. It adds partial support for try-catch-finally, the CFG isn't really the proper one yet... it assumes that only the last statement of body will throw an exception (if any).

**Comment by IagoAbal** [comment]
Fixed@develop: https://semgrep.dev/s/fproulx-boostsecurity:java-const-propag-in-try-catch?version=develop
Please reopen if I missed something!
