### ISSUE TITLE
Custom rule proclaimed "not found" when navigating from policy

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2436]
**Describe the bug**
Selecting a newly added rule in my policy to navigate to the semgrep sandbox worked fine--except for the error pop-up. That is, it did navigate to and open the rule correctly--so the error pop-up is, err, well erroneous.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/6817500/105416926-aea08980-5bef-11eb-9eb2-3204fc5aceee.png">

**To Reproduce**
As shown.

**Expected behavior**
No error pop-up

**Screenshots**
Above

**What is the priority of the bug to you?**
P2 - regular bug

**Environment**
Above

**Comment by dlukeomalley** [comment]
Thanks for filing @msorens Marked `priority:low` given the P2 status, though suspect it's a quick fix. Curious what @sabihb @underyx think who are on support this week w.r.t. how to fix / repro.

**Comment by underyx** [comment]
@msorens

```
    EditorMenu: Save snippets to policies case-sensitively

    Snippet IDs (e.g. c7Pa) only work when used case-sensitively.
    Named aliases also don't disallow mixed-case.
    However, we were lowercasing these IDs/names upon addition anyway, just
    like we do it for rules and rulesets.
```

Just committed this ⬆️

Sadly we lost the exact name of your snippet when it was saved to a policy,
so you should remove and readd it to your policy next week to never encounter this error again!

**Comment by msorens** [comment]
You just said to remove and re-add to the policy, but I do not seem to be able to access the rule at all, even typing it directly into the URL bar of the browser. Should I be able to, or do I have to re-enter the rule from scratch?

**Comment by msorens** [comment]
Ended up re-creating it from scratch and all is well.

**Comment by underyx** [comment]
> You just said to remove and re-add to the policy, but I do not seem to be able to access the rule at all, even typing it directly into the URL bar of the browser. Should I be able to, or do I have to re-enter the rule from scratch?

You should be able to do that, see other discussion. I think maybe you were using the wrong casing: the policy wasn't aware of the correct casing of your snippet name, so couldn't like you to it correctly.
