### ISSUE TITLE
Opening a rule in semgrep sandbox should maintain the name

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2437]
**Describe the bug**
Navigating to a rule in the browser, e.g. https://semgrep.dev/s/msorens:combinelatest-not-combining, should populate the name field, too. User should not have to re-type the name after editing it in order to save it again.
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/6817500/105419200-2a500580-5bf3-11eb-88c6-bacc44be26d1.png">

I suspect the first response here will be "that is the way it is designed", to wit: it facilitates the user quickly entering new rules, one after the other, preventing the user from overwriting some previous rule because it effectively resets the name field. While I agree that is a useful mode to operate in, I think both are important to avoid user errors and frustration.

One way to achieve a compromise is an approach that I think Jira uses. Next to the <kbd>Save</kbd> button add a checkbox labeled "Create more rules". Should be unchecked by default. Then, the name field should reset IFF the box is checked.

Here is how it plays out for the edit scenario:
1. Enter the URL in the browser, then rule opens in the semgrep sandbox, the checkbox is unchecked, the name field has the name.
2. User edits the rule and presses <kbd>Save</kbd>.
3. Rule is overwritten with changes -- job done!

And in the let's-enter-a-bunch-of-rules scenario:
1. Enter a new rule, check the box, press <kbd>Save</kbd>.
2. Name field is reset, box remains checked, other fields are not reset (allowing the user to leverage their previous rule if desired).
3. User edits the previous rule text, may or may not enter a name, presses <kbd>Save</kbd>.
4. New rule is created; does not overwrite previous rule -- job done!

**To Reproduce**
1. Create a custom rule.
2. Save the rule with a name.
3. Press refresh in the browser or open a new browser window and paste the URL.

**Expected behavior**
Name field should be populated so <kbd>Save</kbd> will "do the right thing"™️ when editing an existing rule.

**Screenshots**
Above

**What is the priority of the bug to you?**
Perhaps a P1; but I could live with a P2, too.

**Environment**
Above

**Comment by DrewDennison** [comment]
YUP! I actually want to follow the git forking model and track the provenance for rules. Also queuing for an editor focused sprint cc @adamberman

**Comment by ievans** [comment]
Go away stale bot

**Comment by ievans** [comment]
shhh
