### ISSUE TITLE
Report "unit test results" in semgrep sandbox 

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2439]
**Is your feature request related to a problem? Please describe.**
I am enamored over the idea of being able to create semgrep rules in the editor/sandbox and effectively have unit tests right there on the same page. This is great when a human is there to examine the page and say, "yes, these are the matches I expected".

But what I would really like to see when you press "Run" besides reporting the matches and the fixes, it also reports success and failure of any properly annotated "unit tests". Here is one possible way to introduce annotations:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/6817500/105420116-a72faf00-5bf4-11eb-8334-ac3abcf3e101.png">

With that, the user does not have to waste any brain cells, looking at the code examples and seeing if all the reported matches and fixes are the correct ones.

**Comment by mschwager** [comment]
![](https://zombiesruineverything.files.wordpress.com/2013/07/morph1.jpg)

What if I told you... we already support that! https://semgrep.dev/s/KlW6/

Note the "All tests pass" on the right :+1: 

These tests follow the same conventions as the [CLI testing functionality](https://semgrep.dev/docs/writing-rules/testing-rules/).

**Comment by msorens** [comment]
Perfect reply, @mschwager !! 😁 
(@ievans posted the same comment in slack but without Morpheus to back him up.)

Copying my reply from there here as well:
I was not aware of this!! That does get us part of the way there!
(a) It validates the matches and non-matches.
(b) It does not validate the autofixes.
Since autofix is still experimental, though, let's say ruleid gets three-quarters of the job done.

However, the UX needs some improvement. In fact, it took me a couple trials to realize that `ruleid` was checking both matches and non-matches, meaning both its presence and its absence was being checked at the right places--very cool! However, that is not being communicated to the user at all: when it says "1 test failed" one has no clue whether a check is surplus or lacking, nor where the error emanated from.

**Comment by msorens** [comment]
Reflecting further on this, I wondered:

_Should I have been aware of this cool feature?_ Well, not without having pored over all the docs (which I did) and remembered it (which I did _not_). Because the semgrep sandbox gives no hint that this exists... unless you already know to use it.

Hmm, so _could I have been aware of it?_ Yes, with not too much work, I believe. The semgrep sandbox is a graphical user interface... so just add a few buttons...
<img width="709" alt="image" src="https://user-images.githubusercontent.com/6817500/105441818-343b2e00-5c1e-11eb-82f0-b8f701360ab1.png">

Each of these buttons could add a simple template, or interpolate something a little more clever.  <kbd>Positive</kbd>, for example, could add this generic text to the "Test Code" input field:
```
// ruleid: typescript.rxjs.best-practice.combineLatest-not-combining
// Type your matching code example here
```
or, for this example, could even use the pattern:
```
// ruleid: typescript.rxjs.best-practice.combineLatest-not-combining
combineLatest([$SINGLE_EXPRESSION])
```

**Comment by mschwager** [comment]
Nice, thanks for all the great feedback! I agree, there's no real way to discern this functionality, and there should be. At the very least we should document this cloud app functionality, then we could have the editor include something like "Did you know you can test editor rules inline in code?" -> link to docs. Having a nice UI for this in the editor would be more desirable, but ultimately more effort too.

**Comment by DrewDennison** [comment]
@msorens as always, thank you for the detailed feedback and writeup! We're planning an editor revamp so I'll save this issue for an editor sprint if that's ok with you? cc @adamberman who might be interested in this discussion too
