### ISSUE TITLE
Mechanism to pass arbitrary flags from python wrapper down to semgrep-core

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#2443]
semgrep-core exposes a number of flags to modify behavior of matching like `-max_match_per_file`. In majority of use cases none of these extra flags are necessary but there are edge cases like https://github.com/returntocorp/semgrep/issues/2411#issuecomment-764824110 that would benefit from being able to use them. Instead of having to wire up the python wrapper with every flag exposed by semgrep-core we should have something similar to https://github.com/returntocorp/semgrep-action/pull/169 something like --core-opts "--foo --bar"

**Comment by aryx** [comment]
semgrep-core can use the SEMGREP_CORE_EXTRA environment variables to pass extra arguments.

**Comment by aryx** [comment]
but yes I like this --core-opts.
I think we can keep --timeout in the wrapper too, but maybe we could already move --max_memory to a --core-opts?

**Comment by DrewDennison** [comment]
would like to pass a proper data structure down to the core from python with the full rules and all the config options. Or we could continue the work to remove python altogether

**Comment by emjin** [comment]
@brendongo Is this something you're still interested in?
