### ISSUE TITLE
Timeout with `java.lang.security.audit.crlf-injection-logs.crlf-injection-logs` on ~7k line Java file

### ISSUE THREAD

**Issue by gdamoreira** [semgrep/semgrep#2445]
**Describe the bug**
We are using semgrep in our development pipeline to prevent security vulnerabilities and bugs in our code base. In one of our commits we faced with an unexpected error that couldn't be solved without manually skipping the semgrep phase. The error happens when we run "p/r2c-security-audit" rules over a specific file in our code base. The file have 7455 lines and the error only occurs on `java.lang.security.audit.crlf-injection-logs.crlf-injection-logs` rule. After removing this rule semgrep runs normally.

**To Reproduce**
Just run the command:
`semgrep --config "p/r2c-security-audit" ExampleErrorClass.java`
[ExampleErrorClass.java.zip](https://github.com/returntocorp/semgrep/files/5856847/ExampleErrorClass.java.zip)

**Expected behavior**
The expected result was semgrep runs without any error and without any issues found.

**Screenshots**
<img width="1787" alt="semgrep-error" src="https://user-images.githubusercontent.com/4054210/105510842-71132d80-5ccf-11eb-9bb1-afca96aac616.png">

**What is the priority of the bug to you?**
P0 (blocking your adoption of Semgrep or workflow)

**Environment**
Python 3.9.0
Semgrep 0.38.0
macOS Catalina 10.15.7

**Comment by ievans** [comment]
Hi @gdamoreira -- thanks for reporting this! tagging @aryx or @mjambon to look at the timeout issue.

In the meantime, can you clarify how this is blocks your workflow? My expectation would be that this is printed as a warning and not an error, and that it doesn't change the output status code (unless you are running with `--strict`). When you say "without any error and without any issues found", is your concern that you want semgrep to run without any warnings, or are you trying to run with the --strict flag but can't because of this issue?

**Comment by aryx** [comment]
Also the issue title contains "unspecified error" but the error seems pretty clear: it's a timeout with one of the rule. Or is the use of timeout unclear in this context?

**Comment by gdamoreira** [comment]
Hi @ievans and @aryx, I tried to run locally to get this information, and I suppose in local environment the error is different from our CI server.

I could reproduce the problem using Semgrep Live.

The error can be reproduced using this link:
https://semgrep.dev/s/b7re

Just for curiosity, we could fix that problem updating python and semgrep to latest version and put --timeout flag.

Thank you.

**Comment by nbrahms** [comment]
This may be related to #2411, but on a different rule

**Comment by underyx** [comment]
1. Related but not relevant here: I'll create an internal issue to improve the error message on semgrep.dev
2. @inkz could you check if there are performance improvements to make to the offending rule? https://github.com/returntocorp/semgrep-rules/blob/develop/java/lang/security/audit/crlf-injection-logs.yaml
3. We're shipping a release with experimental opt-in performance improvements this week, @mjambon could you test the linked snippet with the new caching? If majorly improves performance could you provide instructions here for @gdamoreira to be able to try as well?

**Comment by nbrahms** [comment]
Here's the output of the core:

```
./_build/default/cli/Main.exe -timeout 10 -rules_file tmprnc31dlz -lang java ExampleErrorClass.java
{"matches":[],"errors":[{"check_id":"Timeout","path":"ExampleErrorClass.java","start":{"line":1,"col":1},"end":{"line":1,"col":1},"extra":{"message":"Timeout: with ruleid 0..19","line":"package com.example;"}}],"stats":{"okfiles":0,"errorfiles":1}}
```

**Comment by nbrahms** [comment]
@gdamoreira I've updated the rule to improve its performance by ~3x in the attached PR.

However, please note that you may still see timeouts on larger Java files. If you do, you may need to either:
- Exclude the file from checking
- Increase the timeout using the `--timeout` flag (its default is 30 seconds)
- Disable the timeouts altogether using `--timeout 0`

Hope this helps, and thanks for submitting your issue and helping us to improve Semgrep!
