### ISSUE TITLE
Using the inheritance tree, semantic on-the-fly analysis

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2451]
Inspired by https://blog.includesecurity.com/2021/01/ruby-static-analysis-custom-rules-breakman-vs-semgrep.html
which mentions few false positives in semgrep vs brakeman when matching classes inheriting from a certain class.
Right now 'class $A extends Foo {}' will work only if the code contains a direct inheritance to Foo.
But we would really want any class that indirectly inherits from Foo.

In theory this requires a global analysis, which is not really the spirit of local per-file semgrep matching,
but in practice people often calls semgrep on a set of files, and often on the whole project, in which
case we could as we process files remembers somewhere the inheritance tree and relaunch semgrep in a second
pass on the files that might benefit from an inheritance tree.

Semantic!

**Comment by aryx** [comment]
cc @nbrahms @mschwager

**Comment by aryx** [comment]
Note that a current workaround is to (ab)use metavariable-regexp and look if you inherit from something that ends
with *Controller.

**Comment by clintgibler** [comment]
Whoa, this is super cool! 🎉  Looking forward to seeing what we can build with this 👍

**Comment by aryx** [comment]
well, this is an issue, not a pull request, so it's not yet implemented :)

**Comment by aryx** [comment]
still a nice feature to have

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
👋

**Comment by aryx** [comment]
This is now supported by DeepSemgrep.
