### ISSUE TITLE
Go: metavariables do not work for captured variables with captured  + captured in closures

### ISSUE THREAD

**Issue by problame** [semgrep/semgrep#2452]
I want to write a semgrep rule for the following (problematic) Go code:

```go
package foo

import "fmt"

func f(x func ()) {
	go x()
}

func foo(ch chan int) {

	for i := range ch {
		f(func() {
			fmt.Println(i)
		})
	}
}
```

The rule should match if the loop variable `i` in the `for` clause is captured by the closure's body.

My attempt:

```
for $I := range ... {
  ...
  f(func(...) {
    ...
    fmt.Println($I)
    ...
  })
  ...
}
```

(Link: https://semgrep.dev/s/W8OA )

This seems to work.
But if we correct the Go code by shadowing the loop variable with a local variable (a common pattern), the rule still matches.

```go
package foo

import "fmt"

func f(x func ()) {
	go x()
}

func foo(ch chan int) {

	for i := range ch {
                i := i // copy i into a loop-body-local variable so that the closure captures a reference to it instead of the loop variable
		f(func() {
			fmt.Println(i)
		})
	}
}
```

**Expected behavior**

Semgrep probably needs to understand the semantics of Go closure captures and Go shadowing.

Also, I have not found a way to express "variable used anywhere in function body".
I would have expected that the following pattern works, but it doesn't:  `func(...) { <... $I ...> }`  

**What is the priority of the bug to you?**
First time I use semgrep, so no pressure.

**Environment**
Official binary from pip.

**Comment by aryx** [comment]
Thx for the bug report! Yep, seems like we don't recognize correctly i :=. So the := always declare a new variable?

**Comment by aryx** [comment]
A related issue involving := recently: https://github.com/returntocorp/semgrep/issues/2440

**Comment by problame** [comment]
> Unlike regular variable declarations, a short variable declaration may redeclare variables provided they were originally declared earlier in the same block (or the parameter lists if the block is the function body) with the same type, and at least one of the non-blank variables is new. As a consequence, redeclaration can only appear in a multi-variable short declaration. Redeclaration does not introduce a new variable; it just assigns a new value to the original. 

https://golang.org/ref/spec#Short_variable_declarations

**Comment by problame** [comment]
(That section omits the possibility to *shadow* variables in child scopes, though, much like you can do in C:

```c
#include <stdio.h>

int main() {
    int i = 23;
    {
        int i = 42;
        printf("%d\n", i); // 42 
    }
    printf("%d\n", i); // 23
}
```

```go

package main

import "fmt"

func main() {
    i := 23
    {
        i := 42
        fmt.Println(i) // 42
    }
    fmt.Println(i) // 23
}
```

**Comment by aryx** [comment]
@IagoAbal want to take a look at this? A bug in Naming_AST.ml probably (which needs some love ...).
