### ISSUE TITLE
PHP - Inconsistent behaviour of wildcard matches in nested statement

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#2453]
**Describe the bug**
Wildcard matches (...) fail to properly work in a nested statement (such as foreach and if) in PHP.

For example, the pattern:
```
$VARS = $_GET[$KEY];
...
foreach ($VARS as $VAR) {
  ...
  do_something($VAR);
  ...
}
```

Will not match the code
```php
$stacks = $_GET['p'];
foreach ($stacks as $value) {
  do_something($value);
}
```

But will match
```php
$stacks = $_GET['p'];
foreach ($stacks as $value) {
  $a = 'a';
  do_something($value);
}
```

**To Reproduce**
https://semgrep.dev/s/Kl8d

**Expected behavior**
Line 3 should match

**What is the priority of the bug to you?**
P0

**Comment by erwanlr** [comment]
Not sure if also related to this issue:

https://semgrep.dev/s/rdk0

```
$VAR = $_GET[$KEY];
...
do_something($VAR);
```

Will not match
```php
if (isset($_GET['q'])) {
  $page2 = $_GET['q'];
}
do_something($page2);
```

To match it, the pattern would need to be like below, but then produces too many matches
```
...
$VAR = $_GET[$KEY];
...
do_something($VAR);
```

**Comment by erwanlr** [comment]
Another one: https://semgrep.dev/s/N487 which is even weirder, as no match will be found at all with a pattern like `pattern: do_something(...);`

Let me know if I should open different issue reports for those

**Comment by emjin** [comment]
For the last one (https://semgrep.dev/s/N487), the discrepancy is because one of the else bodies is empty. Not sure if we'd want to update the behavior to be more intuitive, but https://semgrep.dev/s/ydXO should get you want you want in the meantime.

**Comment by erwanlr** [comment]
Thanks @emjin, however for the last one, the pattern in the linked semgrev dev was not the one I talked about for some reason (I guess I was testing things).

https://semgrep.dev/s/nd9Z

What I meant with this one is that `pattern: do_something(...);` will not match:

```php
if (isset($_GET['q'])) {
  // ruleid:issue
  do_something($_GET['q']);
} else {
  $a = 'a';
}
```

But will match

```php
if (isset($_GET['q'])) {
  $a = 2;
  // ruleid:issue
  do_something($_GET['q']);
} else {
  $a = 'a';
}
```

However, if `pattern: do_something(...)` is used, both will match but that's not a real case scenario here (as I need the `;` in a multi line pattern or semgrep raises a parsing pattern error)

**Comment by emjin** [comment]
Ah, that is weird indeed! It seems to be related to your other problem, so hopefully fixing one will fix the other. Looking into it.

**Comment by emjin** [comment]
The first and third (https://semgrep.dev/s/Kl8d and https://semgrep.dev/s/nd9Z) are working on develop now---you can check by going to tools and then selecting "use develop docker image". Those fixes will go out in the next release. 

Your second one (https://semgrep.dev/s/rdk0) is less directly related. Your pattern isn't expected to match, because in
```
if (isset($_GET['q'])) {
  // ruleid:issue
  $page2 = $_GET['q'];
}
do_something($page2);
```
the two lines are in different scopes. The pattern that will match this is https://semgrep.dev/s/DoeG/?version=develop. However, this was broken earlier and only works on develop.

Hope this solves your issue! Thanks for reporting!

**Comment by erwanlr** [comment]
Thank you for the fix!

Even though I understand the scope thing, using a pattern-inside will produce false positive, matching statements from two different functions for example, ie https://semgrep.dev/s/1Zk1/?version=develop
