### ISSUE TITLE
Negation not working with subexpressions

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2457]
In https://semgrep.dev/s/zv91
we should not report match to os.environ when part of a larger expression that matches the pattern-not.

**Comment by aryx** [comment]
I'm actually currently working on reimplementing the boolean composition logic in the core,
and I'm not finished yet with negation, but the semantic I have I think would not report
the other (wrong) matches semgrep is currently returning.
A and not B should filter all matches in A that are included (range-wise) in one of the range of B.

**Comment by aryx** [comment]
cc @nbrahms @ievans

**Comment by nbrahms** [comment]
I think the user here just wants `pattern-not-inside`.

I'd propose just removing `pattern-not` since it never gives us anything over `pattern-not-inside`.

**Comment by ievans** [comment]
Big +1, please do that as part of this transition. Ticket is: https://github.com/returntocorp/semgrep/issues/1218

**Comment by minusworld** [comment]
Waiting until pattern logic gets merged into semgrep-core to make any progress here.

**Comment by aryx** [comment]
@nbrahms actually as I said in https://github.com/returntocorp/semgrep/issues/1218 we can't merge pattern-not: and pattern-not-inside: :( I've found some examples where the behavior must be different :(

**Comment by mschwager** [comment]
I think https://github.com/returntocorp/semgrep-docs/pull/129 may close this out.

**Comment by colleend** [comment]
We can close this issue as we are not currently merging pattern-not and pattern-not-inside and documentation currently differentiates between the two.
