### ISSUE TITLE
Investigate failure report from M1 / ARM64

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#2466]
**Is your feature request related to a problem? Please describe.**
Make sure semgrep works in ARM docker containers. @ajinabraham noticed Semgrep failed to run on a M1 Mac

**Comment by brendongo** [comment]
Duplicate of https://github.com/returntocorp/semgrep/issues/2432 ?

**Comment by underyx** [comment]
@DrewDennison @ajinabraham can we get a more detailed report of how it failed? Did x86 emulation not work correctly?

**Comment by aryx** [comment]
possible related issue discussed on slack: https://r2c-community.slack.com/archives/CK86BJ5DW/p1617739952157800

**Comment by aryx** [comment]
closing, duplicate of #2432
