### ISSUE TITLE
PHP - Unable to match function defined in class with simple pattern

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#2470]
**Describe the bug**
Having a pattern such as `function __destruct() { ... }` against the function definition in a class, yields no match. Also using visibility keywords such as `public`, `private` etc in the pattern (ie `public function __destruct() { ... }` results in a pattern parsing error.

**To Reproduce**
https://semgrep.dev/s/8yR7

**Expected behavior**
The pattern should match against code like

```php
class Test {
  function __destruct() {
    // do something
  }

  private function other() {
    // do something else
  }
}
```

**What is the priority of the bug to you?**
P2. The current workaround is to use a pattern such as `class $CLASS { function __destruct() { ... } }` but then the whole class will be returned as a match

**Comment by underyx** [comment]
Thanks for the report @erwanlr! I've added an alpha label to this issue for technical correctness, but I know we're thinking of graduating PHP in the near future and so I'll be bringing up this issue at our team meeting this PST morning.

**Comment by underyx** [comment]
Hey, I owe you an update. We have not decided yet on working towards graduating PHP, so this issue is going in the low-priority backlog.
