### ISSUE TITLE
SARIF format for output report

### ISSUE THREAD

**Issue by damiencarol** [semgrep/semgrep#2479]
**Is your feature request related to a problem? Please describe.**
Want to have the ouput as a SARIF file. https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html

**Describe the solution you'd like**
When I use -o option, have a -sarif option to export the file as SARIF format like:

```
semgrep -sarif -o ./test.sarif my_src/
```

**Additional context**
https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html

**Comment by underyx** [comment]
Note that it's `--sarif` with two dashes instead of one.

**Comment by damiencarol** [comment]
Will try. thanks for the feedback

**Comment by underyx** [comment]
I'll assume that solves the problem, so closing this issue. Feel free to reopen if I'm wrong!
