### ISSUE TITLE
Allow Semgrep to run over multiple (concatenated) files

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#2484]
**Is your feature request related to a problem? Please describe.**
I recently encountered a bug that I would like to write a rule for, to prevent this bug from occurring again
Our alembic database migration scripts need to occur in one, linear, path.
Therefore, we want to prevent a PR from going in if its down_revision already
exists in another file in the codebase. This can happen very easily if two engineers
are working in parallel on code changes that require database migrations.

**Describe the solution you'd like**
If we could concatenate all of the files in one directory to run some rules, then 
the rule for this would just look like
```
down_revision = $X
...
down_revision = $X
```

**Describe alternatives you've considered**
Perhaps this is possible by running over all of the files without concatenating them

**Additional context**
https://returntocorp.slack.com/archives/C6A1GN4P3/p1612210457393400

**Comment by mschwager** [comment]
I think you can achieve this by taking input from `stdin` with `-`:

```
$ find migrations/ -type f | xargs cat | semgrep -e 'op.add_column(...)' -l python -
```

**Comment by chmccreery** [comment]
@mschwager that is cool, but doesn't port easily over to `semgrep-app` and what I really would like is a way to write this type of rule to run on PR's right before they get merged, as they are likely not out of date until after-review or the author would catch it.

**Comment by mschwager** [comment]
Hmm, it sounds like we're talking about two different solutions:

1. A first-party Semgrep solution, like a CLI flag.
2. A "third-party" solution, like some Bash-fu.

For (1), I know @aryx is working on some multi-file analysis to look at class hierarchies. That could be helpful here, but it may be a while before this functionality is surfaced/mature. We could add a CLI flag that simply concatenates all the files it receives, but I'm not sure that's much better than what I posted above :thinking: 

For (2), I think the above command with a local repository rule could work.

> ... but doesn't port easily over to semgrep-app ...

Could you elaborate on this? With a local repository rule and an arbitrary Github Action command I think the above should work. I guess it depends on where you are on the polish vs. expediency of this functionality.

> ... what I really would like is a way to write this type of rule to run on PR's right before they get merged, as they are likely not out of date until after-review or the author would catch it.

I'm not totally following here either. This sounds like a Github Action distinction to me, or at least a `semgrep-action` one, not a Semgrep distinction. Are you thinking multiple Semgrep runs based on the Github Actions job event type?

**Comment by chmccreery** [comment]
Yep, sorry that wasn't very clear. I am down to wait for multi-file analysis, and @aryx asked me to file this as an issue just to keep track of it. It isn't an urgent need, just a 'this would be nice to support, if we can' type thought.

We could, of course, do this through `semgrep-action` as some complicated workaround, but I filed the issue thinking that I would love for us to support this functionality, rather than "I need this rule and we should work around our system to create it". Does that make sense? Sorry that wasn't clear in the original description.
