### ISSUE TITLE
DRY out "unit tests" in live editor

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2487]
**Is your feature request related to a problem? Please describe.**
Here is a typical rule with unit tests in the live editor: https://semgrep.dev/s/msorens:observable-not-ending-with-dollar-sign
The very obvious thing here is that the lengthy rule id (`typescript.rxjs.best-practice.observable-not-ending-with-dollar-sign`) needs to be repeated over and over.
<img width="485" alt="image" src="https://user-images.githubusercontent.com/6817500/106537205-be04ba00-64ae-11eb-8f58-3cd6a4a0166a.png">

**Describe the solution you'd like**
Would be nice to be able to provide a short hand for that so instead of having to write these...
```
// ruleid: typescript.rxjs.best-practice.observable-not-ending-with-dollar-sign
// ok: typescript.rxjs.best-practice.observable-not-ending-with-dollar-sign
```
I could just use these...
```
// ruleid: RULE
// ok: RULE
```

That is, use the literal keyword "RULE" (or `*RULE*` or `$$rule` or `this` or `%` or ... does not matter to me) to indicate the rule defined on the current page.

**Comment by mschwager** [comment]
Hey @msorens,

That is a bit cumbersome. We could even just use `// ruleid` and `// ok` :thinking:

I'll track this as an enhancement in the editor :+1:
