### ISSUE TITLE
Disambiguate between semgrep ellipsis and preexisting ellipsis operator in language

### ISSUE THREAD

**Issue by Ruin0x11** [semgrep/semgrep#2493]
Lua has a variadic argument operator (`...`) which expands to the set of variadic arguments in a function. It is used like this:

```lua
local function foo(...)
  for i = 1, select("#", ...) do
    print(i, select(i, ...))
  end
end
```

The problem is that this conflicts with semgrep's ellipsis operator. I was trying to write a rule that matched the following:

```lua
Draw.text("foo", 0, 0, {255, 0, 255})
```

To do this I wrote the pattern:

```
Draw.$X(..., {...}, ...)
```

But this does not match the example. If I write this, it works:

```
Draw.$X(..., {..., ..., ...}, ...)
```

But now the problem is that it won't match code like `{255, 0, 255, 128}`, which I want to match also. The only way around this is to duplicate every rule for every additional entry in the table I want to check for, like `{..., ..., ..., ...}`.

What is actually happening is a pattern like `{...}` will literally match the following Lua code:

```lua
local function foo(...)
   return {...}
end
```

I can potentially see the uses of this. The question is, can something be added to disambiguate between these two operators? It might have to be a special-case syntax addition to the Lua grammar that's used, or it could be something inside semgrep itself.

**Comment by mschwager** [comment]
Hi @Ruin0x11,

Nice catch! I know Python has an [`Ellipsis`](https://docs.python.org/dev/library/constants.html#Ellipsis) object as well - I wonder if there are similar issues. Since Lua is still in the experimental phase I'm going to mark this as lower priority. cc @aryx who knows more about these things than I do, and may be able to help out :)

**Comment by aryx** [comment]
The place where you can use ... in Python (I think mostly in types) are different than the place where semgrep is using so we didn't have the problem in Python.

**Comment by DrewDennison** [comment]
My thinking here is what we ask the user to `$FOO...` for metavars where it is ambiguous and have strict mode that always asks for the `$FOO...` syntax

**Comment by Ruin0x11** [comment]
This is still an issue.

**Comment by DrewDennison** [comment]
@aryx still an issue or did you solve in PHP and Hack?
