### ISSUE TITLE
import $VAR metavariable does not match entire import path

### ISSUE THREAD

**Issue by sfc-gh-cdai** [semgrep/semgrep#2502]
**Describe the bug**
when typing the pattern ```import $VAR```, the metavariable $VAR matches only the last portion of the import path, not the entire import path. 

**To Reproduce**
Here's an example:
https://semgrep.dev/s/oxN6/

**Expected behavior**
Would expect to match the entire path. In the example given, I would expect the pattern to match both of the example imports.

**What is the priority of the bug to you?**
P1 -- would like to have this fixed so that we can write some rules for snowflake 👍 

P.S: this is @colleend with snowflake account 😎

**Comment by ievans** [comment]
hi @sfc-gh-cdai -- thanks for filing an issue! It looks like the link to the editor you sent is empty -- can you click the "share" button before copying the link? that should generate a short url permalink. Thank you!

**Comment by clintgibler** [comment]
Also relevant: https://github.com/returntocorp/semgrep/issues/975

**Comment by mschwager** [comment]
> Also relevant: #975

Good catch, I see that the first line considers `$CRYPTO_LIB` as `CryptoCipherFactory`, and the second line as `BouncyCastleProvider`, so it appears to be the same issue as Python imports. cc @aryx who's been thinking about this for a while.

**Comment by aryx** [comment]
Note that an alternative is also to use import $PACKAGE.$ENTITY;
which will match import org.com.bar.MyList; with $PACKAGE bound to org.com.bar and $ENTITY to MyList.

With the PR above, import $LIB; now also match and $LIB is bound to the FQN (fully qualified name) org.com.bar.MyList.
