### ISSUE TITLE
Error with 'git submodule update --init --recursive'

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2513]
I made submodule changes within the `ocaml-tree-sitter` repo, which is itself a submodule of semgrep. If you do `git submodule update --init`, everything is fine, but with the `--recursive` flag git gets confused and produces a message like this:
```
git submodule update --init --recursive
error: submodule git dir '/home/martin/semgrep/.git/modules/ocaml-tree-sitter/modules/lang/semgrep-grammars/src/tree-sitter-c-sharp' is inside git dir '/home/martin/semgrep/.git/modules/ocaml-tree-sitter/modules/lang/semgrep-grammars'
fatal: refusing to create/use '/home/martin/semgrep/.git/modules/ocaml-tree-sitter/modules/lang/semgrep-grammars/src/tree-sitter-c-sharp' in another submodule's git dir
Failed to clone 'lang/semgrep-grammars/src/tree-sitter-c-sharp'. Retry scheduled
```
Solution that worked for me:
```
rm -rf '.git/modules/ocaml-tree-sitter/modules/lang/semgrep-grammars'
```
There may be other quirks, depending on the state of your development tree. Please reach out for help on our [community Slack](https://r2c.dev/slack).

**Comment by aryx** [comment]
Seems like we managed to update with your fix.
Let's close this.

**Comment by underyx** [comment]
Yay, thanks for pointing to a fix! In my case, I also had to run `git submodule deinit -f --all` before removing the directory.
