### ISSUE TITLE
Semgrep unable to analyse file with non-ascii chars (UnicodeEncodeError: 'ascii' codec can't encode characters)

### ISSUE THREAD

**Issue by xerxesb** [semgrep/semgrep#2514]
**Describe the bug**
When I run semgrep using the standard `r2c-ci` rules, the runner fails and reports a python exception

**To Reproduce**
I've narrowed the issue down to a single file in our repo. We use the JSON Editor js module, and semgrep crashes when trying to parse it.
https://cdnjs.cloudflare.com/ajax/libs/json-editor/2.5.2/jsoneditor.min.js

```
(.env) root@f3bfa60c6257 /workspaces/server/pages/js (master) $ semgrep --config=p/r2c-ci jsoneditor.min.js 
using config from https://semgrep.dev/p/r2c-ci. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 119 rules...
100%|#########################################################################################################################################################################################################################################################################################################################################################################################################|119/119
Traceback (most recent call last):
  File "/usr/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/semgrep/__main__.py", line 17, in main
    cli()
  File "/usr/lib/python3.6/site-packages/semgrep/cli.py", line 451, in cli
    severity=args.severity,
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/usr/lib/python3.6/site-packages/semgrep/output.py", line 260, in managed_output
    output_handler.close()
  File "/usr/lib/python3.6/site-packages/semgrep/output.py", line 407, in close
    print(output, file=self.stdout)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 32865-32867: ordinal not in range(128)
(.env) root@f3bfa60c6257 /workspaces/server/pages/js (master) $ 
```

**Expected behavior**
I expected it to process the file and return the result from the analysis

**What is the priority of the bug to you?**
P2 (regular bug that should get fixed)
It's annoying but I don't intend to analyze minified libs that we consume....at least not yet.

**Environment**
Docker env based on `ubuntu-1804`

**Comment by mschwager** [comment]
Hi @xerxesb,

> Docker env based on ubuntu-1804

Can you describe your environment further? Are you sure you're running the latest version of Semgrep?

I'm unable to reproduce on Ubuntu 18.04 when running via a Docker environment and Python pip-installed environment:

```
$ wget https://cdnjs.cloudflare.com/ajax/libs/json-editor/2.5.2/jsoneditor.min.js
$ docker run -v '/tmp/jsoneditor.min.js:/tmp/jsoneditor.min.js' returntocorp/semgrep:0.39.1 --config=p/r2c-ci /tmp/jsoneditor.min.js
...
$ echo $?
0
$ python -m semgrep --config=p/r2c-ci /tmp/jsoneditor.min.js
...
$ echo $?
0
```

**Comment by xerxesb** [comment]
Hi @mschwager,

I just noted a small mistake in my original report. The URL of the file should actually be:
https://cdnjs.cloudflare.com/ajax/libs/json-editor/2.5.2/jsoneditor.min.js

However even the URL above and the one I originally provided both fail with the same error (only difference is the character position).

Some more information about my env:
* Semgrep version == 0.39.1
* Python version == 3.6.9
* O/S
  > $ uname -a
  > Linux f3bfa60c6257 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  > 
  > $ cat /etc/os-release 
  > NAME="Ubuntu"
  > VERSION="18.04.5 LTS (Bionic Beaver)"
  > ID=ubuntu
  > ID_LIKE=debian
  > PRETTY_NAME="Ubuntu 18.04.5 LTS"
  > VERSION_ID="18.04"
  > HOME_URL="https://www.ubuntu.com/"
  > SUPPORT_URL="https://help.ubuntu.com/"
  > BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  > PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  > VERSION_CODENAME=bionic
  > UBUNTU_CODENAME=bionic
* Docker image
  > FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.0

Hopefully that's enough of a start...Let me know if there's other information you think would help.

**Comment by mschwager** [comment]
> Docker image
> FROM nvidia/cuda:11.0-cudnn8-devel-ubuntu18.04

Interesting, I was eventually able to reproduce on this Docker image. The key insight ended up being:

Locally for me:

```
$ python -c 'import sys; print(sys.stdout.encoding)'
UTF-8
```

From your Docker image:

```
$ python3.6 -c 'import sys; print(sys.stdout.encoding)'                             
ANSI_X3.4-1968
```

Running the following command successfully completes for me in the Docker container:

```
$ PYTHONIOENCODING=utf-8 semgrep --config=p/r2c-ci /tmp/jsoneditor.min.js
```

Note that we do set this encoding in our officially provided [`Dockerfile`](https://github.com/returntocorp/semgrep/blob/develop/Dockerfile). Is there a reason you're not using this Docker image? I can add an `encode('utf-8')` call to our outputting functionality, which should clear this up, but generally we encourage users to use officially released artifacts :+1:

**Comment by mschwager** [comment]
Adding `encode('utf-8')` won't work because of our output coloring and other formatting :/

I could always wrap the `print` in a `try`/`except UnicodeEncodeError` and recommend setting `PYTHONIOENCODING=utf-8` if you see this error :thinking:. Does that sound reasonable?

**Comment by xerxesb** [comment]
> Interesting, I was eventually able to reproduce on this Docker image. 

See that surprises me. I wouldn't have imagined nvidia needing to change the default encoding in their image...? I decided to run a quick test using the originating ubuntu 18.04 image...
> docker run -t -d ubuntu:bionic
> docker exec awesome_bohr apt update
> docker exec awesome_bohr apt install python3 -y  --no-install-recommends
> docker exec awesome_bohr /usr/bin/python3 -c 'import sys; print(sys.version); print(sys.stdout.encoding);'
>  3.6.9 (default, Oct  8 2020, 12:12:24)
>  [GCC 8.4.0]
>  ANSI_X3.4-1968

I fully grant that I might be misunderstanding it, but it looks like the base image has a default encoding set to `ANSI_X3.4-1968`, so I'm surprised I haven't seen this reported before (I would have expected plenty of others working off the same base image)


> Is there a reason you're not using this Docker image?

I simply followed the instruction in the README which indicated I could use it as a pip module. :) I'd intended to add it to our dev pip dependencies and part of our test/analyse ci steps.

I think I could readily change our build env to have `PYTHONIOENCODING=utf-8` defined. Shouldn't be an issue for me.

**Comment by mschwager** [comment]
> I fully grant that I might be misunderstanding it, but it looks like the base image has a default encoding set to `ANSI_X3.4-1968`, so I'm surprised I haven't seen this reported before (I would have expected plenty of others working off the same base image)

It does seem odd that the Ubuntu base image doesn't use `UTF-8`. Especially since I'm using Ubuntu OS and that is what I get.

> I simply followed the instruction in the README which indicated I could use it as a pip module. :) I'd intended to add it to our dev pip dependencies and part of our test/analyse ci steps.

Ahh, I see, that makes sense. I suspect most Semgrep Docker users are using our official image, but I agree that we should cover `pip` installation wherever we can :+1:. https://github.com/returntocorp/semgrep/pull/2535 should at least point people in the right direction in the future :)

> I think I could readily change our build env to have `PYTHONIOENCODING=utf-8` defined. Shouldn't be an issue for me.

Great! Thanks again for the report.

**Comment by v-p-b** [comment]
I stumbled upon this issue after trying to analyse files with latin2 encoding. In my case Semgrep didn't thrown an exception, just reported 0 matches for even trivially matching patterns (I think this is worse, because one can't tell that something is wrong). 

I tried setting PYTHONIOENCODING as suggested above, but it didn't help.

**Comment by bchicken69** [comment]
For those who face the error, you can change line 831 of C:\Users\urusername\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\semgrep\config_resolver.py to the following. I believe the UnicodeEncodingError happens because it detected the encoding as Windows cp1252. 

**Before**
https://github.com/semgrep/semgrep/blob/7b3932dfd0fa1861500e97a4bb8683a59b88af59/cli/src/semgrep/config_resolver.py#L831

**After**
`
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as fp:
`
