### ISSUE TITLE
"..." does not match string literals in Typescript imports or exports

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#2523]
**Describe the bug**
Pretty much what the title says. I'd expect `'./foo/Bar'` and `'otherString'` to be matched by the pattern: `"..."`.
~~~typescript
export * from './foo/Bar';

import { fooBar } from 'otherString'
~~~

**To Reproduce**
https://semgrep.dev/s/clintgibler:typescript-import-export-string-literals

**What is the priority of the bug to you?**
P2 (regular bug that should get fixed)?

**Comment by aryx** [comment]
The pattern "..." assumes that you are looking for a string _expression_. Here it's not an expression but a module name, which
has a different category internally. One of those cases where semgrep is not like grep.

**Comment by aryx** [comment]
We could disambiguate and allow import { ...} from "..."; or export * from "..."
or maybe allow a partial 'from "..."', but none of those currently work for different kinds of reasons.

**Comment by DrewDennison** [comment]
perhaps related to #2551
