### ISSUE TITLE
Java fails to parse when `$` in identifiers

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#2528]
**Describe the bug**
It appears that `$`'s can appear in several places in Java source code that currently causes Semgrep to fail to parse the file, including:
* In enum names
* In imports
* Probably other places

**To Reproduce**
https://semgrep.dev/s/clintgibler:java-dollarsigns-parse-bugs

**Expected behavior**
I would expect this file to parse.

**What is the priority of the bug to you?**
P2 (regular bug that should get fixed)?

**Comment by aryx** [comment]
tracked here: https://github.com/tree-sitter/tree-sitter-java/issues/62

**Comment by aryx** [comment]
This is allowed indeed: https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html according to the spec, even though
such legacy identifiers are discouraged, or should be present only in generated code.

**Comment by aryx** [comment]
But your file contains a syntactical error with a missing semicolon at the second line.
With it the file parses fine (because the Java pfff parser handles correctly those identifiers).
See https://semgrep.dev/s/dKJQ/

**Comment by aryx** [comment]
Then your pattern $X does not match all of those identifiers, because $X is parsed as a expression metavariable, and will only
match expressions.

**Comment by aryx** [comment]
Closing as semgrep actually currently parses this file (even though the tree-sitter-java parser does not).
