### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by zain-CSsol** [semgrep/semgrep#2533]
Hello, i installed semgrep locally on desktop computer with python having following configurations

1. HP ProBook
2. RAM (16GB)
3. Processor Core i5 (7th Gen)
4. Python 3.7

to download the config file i issued the following command highlighted in the semgrep official website [here](https://semgrep.dev/p/ci)

**semgrep --config "p/ci"**

at first it tried to download the config file but then aborted the download and following error occured
**OSError: [WinError 193] %1 is not a valid Win32 application**

The screenshot of the complete problem is attached

![image](https://user-images.githubusercontent.com/77674107/107506416-dcaa3580-6bbf-11eb-9889-2a95a24a8b8e.png)

**Comment by mschwager** [comment]
Hi there @zain-CSsol,

Thanks for opening this ticket. Native Windows is currently unsupported, we're tracking this request in #1330. We should definitely make this more clear when running `semgrep` on Windows. `semgrep` does work on WSL, are you able to run it there?

**Comment by zain-CSsol** [comment]
Thanks a lot for your concern, no till now i haven't tested on WSL, but i am definitely going to test it on WSL to test the behavior.

**Comment by Anthony-Mckale** [comment]
had same issue on local git-bash or cmd windows, but works for me in wsl2 (ubuntu vm)

my setup

1) installed the ws2 ubuntu vm from here = https://docs.microsoft.com/en-us/windows/wsl/install-win10

2) modified my .bashrc to take my standard windows python out of the mix and added "/home/local/.local/bin" which is where the python3 cli pip apps will be installed

3) then installed python 3.8 and pip on ubuntu using apt

```
sudo apt install software-properties-common
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.8
sudo apt install python3-pip

local@DESKTOP-xxx:/home$ python3 --version
Python 3.8.5
local@DESKTOP-xxx:/home$ which python3
/usr/bin/python3
local@DESKTOP-xxx:/home$ pip --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
```



4) after that semgrep worked a treat when installed via pip
```
local@DESKTOP-xxx:/mnt/c/dev/repos/xxx$ pip install semgrep
Collecting semgrep...
local@DESKTOP-xxx:/mnt/c/dev/repos/xxx$ semgrep --config=p/ci
using config from https://semgrep.dev/p/ci. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 135 rules...
...
ran 135 rules on 1 files: 0 findings
```
