### ISSUE TITLE
Selecting rule to disable in a policy shows mutiple copies

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2537]
**Describe the bug**
<img width="828" alt="image" src="https://user-images.githubusercontent.com/6817500/107546404-2aec1400-6b81-11eb-9476-4989a104615d.png">

Additional note: I had seen this a couple months ago and it was fixed shortly after I reported it.

**To Reproduce**
Open a policy.
Add a ruleset ("r2c-bug-scan").
Select the "Add a disabled rule".
Enter a search expression ("incorrect-default-permission").

**Expected behavior**
Found rule appears many times; should just appear once.

**Screenshots**
Above

**What is the priority of the bug to you?**
P2 -- regular bug

**Environment**
dashboard

**Comment by chmccreery** [comment]
I looked into this- it is coming from us having multiple rules inside of the yaml file here: https://github.com/returntocorp/semgrep-rules/blob/develop/go/lang/correctness/permissions/file_permission.yaml

I will separate them out in a semgrep-rules PR

**Comment by chmccreery** [comment]
Fixed by https://github.com/returntocorp/semgrep-rules/pull/1119

**Comment by chmccreery** [comment]
Thanks @msorens for filing! Unfortunately, these seem to be coming from bugs in our semgrep-rules repo, where multiple rules have been created using the same id, so fixing them is a manual process. Please let us know if you see this again. This particular one should hopefully be fixed and out to production in the next day or two. 

@dlukeomalley when we make registry 2.0 we can enforce a uniqueness constraint 😉 
AND once yaml is a supported language, we can write a Semgrep rule for this 😄 😄 😄

**Comment by dlukeomalley** [comment]
@chmccreery I hear you loud and clear 🙏  In the interim, should we keep this issue open or closed?

**Comment by chmccreery** [comment]
Let's leave it open until returntocorp/semgrep-rules#1119 (above) gets merged
