### ISSUE TITLE
Add unit tests for metavariable bindings

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#2551]
We've seen regressions with what strings get bound to metavariables.

This occurs most frequently when binding entity names in imports, and seems to differ across languages.

Suggestion is to write a quick unit test suite for these bindings for each GA and beta language.

**Comment by DrewDennison** [comment]
@colleend this seems relevant for #2578 is this something you are able to tackle? It seems part of the language feature matrix work you did as part of the language graduation spec

**Comment by colleend** [comment]
I can do this, but I probably won't get to this until next week.

**Comment by nbrahms** [comment]
go away stale bot
