### ISSUE TITLE
Deep expression operator doesn't cover object/dict initialization

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2552]
From https://github.com/returntocorp/semgrep-rules/issues/1098.

Looking at the following behavior:

- Works: https://semgrep.dev/s/5QZD/
- Doesn't work: https://semgrep.dev/s/Geby/
- Doesn't work: https://semgrep.dev/s/Ro5g/

Do we expect the deep expression operator to work in this way?

**Comment by aryx** [comment]
The one fixing this issue needs to remove some todook: in semgrep-rules in useless-assign.js

**Comment by mschwager** [comment]
Looks like this is fixed with the recent deep expression operator changes!

**Comment by mschwager** [comment]
https://github.com/returntocorp/semgrep-rules/pull/1293 :tada:
