### ISSUE TITLE
Add support for typed metavariables in Typescript

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#2564]
**Is your feature request related to a problem? Please describe.**
We support typed metavariables for statically typed languages like Java and Go. Typescript is a dynamically typed language (though it has more guarantees than Javascript), but it would be nice to have!

**Comment by aryx** [comment]
relevant slack conversation: https://r2c-community.slack.com/archives/G01FXEAJJHK/p1613403370002000

**Comment by DrewDennison** [comment]
@aryx my vote is to lump into the LSP work but defer to you and @emjin on if this is easy cc @nbrahms

**Comment by aryx** [comment]
I don't think it would be too hard to do what we have for Java and Go given we use the AST generic for that, so it should work for Typescript for the type-annotated variables. In any case, LSP or not we need to extend the typescript/javascript grammar to support the typed metavariable syntax, so this will be needed anyway later.
