### ISSUE TITLE
Support for 32 bit architecture (compile semgrep-core for 32bits machines)

### ISSUE THREAD

**Issue by domainController** [semgrep/semgrep#2565]
**Describe the bug**
Cannot run semgrep without always running into the same error:

OSError: [Errno 8] Exec format error: '/usr/local/lib/python3.6/dist-packages/semgrep/bin/semgrep-core'

![semgrep](https://user-images.githubusercontent.com/58897196/108051283-9da63500-7042-11eb-9820-6c054bc7a1e5.png)
 started by examples from 

**To Reproduce**
A simple install in my case.
I wonder if it's due to the fact I run a 32-bit CPU. I have sucessfully uninstalled the related pip package and reinstalled it bymaking sure I have no permissions file warning as seen during my previous initial install but did not change it.

**Expected behavior**
Same outputs as I see in the REPL

**Screenshots**
Here is a screenshot of my install
![semgrepinstall](https://user-images.githubusercontent.com/58897196/108052344-e27e9b80-7043-11eb-84ca-e8177d9a41be.png)

**What is the priority of the bug to you?**
P2
**Environment**
Local, Ubuntu, Bash, i686 (see uname -a output in first reported screenshot)

**Comment by aryx** [comment]
Yep, probably because we internally use a binary, semgrep-core, which is compiled for 64bit archi.
Can you do $ ldd /usr/local/lib/python3.6/dist-packages/semgrep/bin/semgrep-core
Can you execute this file in bash?

**Comment by domainController** [comment]
Thank you for your prompt reply Yoan. Here is my output. 
![ldd](https://user-images.githubusercontent.com/58897196/108060372-b0266b80-704e-11eb-9117-8e75acdf16cd.png)

**Comment by aryx** [comment]
What happens when you try to execute the binary? You also get an error?
We could try to build a semgrep-core binary for x86-32; we also need to produce one for the new apple M1-ARM architecture; but it's still low priority right now unfortuntately.

**Comment by domainController** [comment]
Oops my bad . Installing Docker for a 32-bit machine do not solve the issue and outputs the exact same error. I did read the issue about M1-ARM architecture. This is good news. Using a remote  AWS machine and your REPL for the moment . 

![exec_semgrepcore](https://user-images.githubusercontent.com/58897196/108080251-8f1e4480-7067-11eb-82c5-61ca0642740b.png)

**Comment by DrewDennison** [comment]
related to #2252

**Comment by aryx** [comment]
Should we move this to the backlog @DrewDennison ?
It's low priority no?

**Comment by ankush** [comment]
Facing same error but only with py3.7 and not with py3.8. Both installed on same machine. but managed by pyenv.

**Comment by raianul** [comment]
any update? any work around? suffered lot.

**Comment by brendongo** [comment]
Hey @pranto157 releasing a version that works on 32-bit architecture is not a priority for us right now. Workaround would be to try and build semgrep from source? https://semgrep.dev/docs/contributing/semgrep-core-contributing/#building-semgrep-core
