### ISSUE TITLE
semgrep.dev bug report

### ISSUE THREAD

**Issue by daghan** [semgrep/semgrep#2578]
https://semgrep.dev/s/GeX6?stepByStep=1

This code should have matched  "box". I don't understand why.

**Comment by colleend** [comment]
thanks for filing the issue! The metavariable actually seems to match the entire string, quotes included. This should work:
https://semgrep.dev/s/0QPw/?stepByStep=1

**Comment by DrewDennison** [comment]
@colleend can you update the documentation please to clarify this and use these links as examples? @mschwager what's your thoughts on what `metavar-regex` API? Should we clarify that you have to include `"` in your regex or do you want to ask semgrep-core to return just the bits inside the string?

**Comment by colleend** [comment]
I can update the documentation. personally, I think having semgrep-core return the bits inside the string is more intuitive.

**Comment by daghan** [comment]
The semgrep debugger didn't show what metavariable $BOX (in this above link) matched. I think regex is a very frequent use-case for people and a regex debugger would be super nice

**Comment by colleend** [comment]
closing because documentation has been merged!
