### ISSUE TITLE
Metavariable equivalence across pattern clauses with deep expressions don't work as expected

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#2593]
**Describe the bug**
While working on https://github.com/returntocorp/semgrep-rules/issues/954, I encountered an issue where metavariable equivalence wasn't working across `pattern-inside` and `pattern` clauses when the deep expression operator <... $THING ...> was used.

**To Reproduce**
You can see that it works as expected when in one large pattern clause: https://semgrep.dev/s/8xe7/?stepByStep=1

However, it does not work when splitting this across `pattern-inside` and `pattern` clauses: https://semgrep.dev/s/gpzn/?stepByStep=1

It does, however, work when there are no subexpressions in the actual code: https://semgrep.dev/s/ydlA/?stepByStep=1

**Expected behavior**
I would expect the rule in https://semgrep.dev/s/gpzn to match the test case at the end of the file at the following line: `r = os.system('wget %s -O "%s"'%(url, fpath))`

**What is the priority of the bug to you?**
P2

**Comment by mschwager** [comment]
Seems similar to https://github.com/returntocorp/semgrep/issues/2548 and https://github.com/returntocorp/semgrep/issues/1699. Generally, it seems our metavariable logic is scattered and incomplete in the Python code. We should try to solve this in a general manner in the codebase so we aren't hunting and pecking for bugs in many different locations.

**Comment by aryx** [comment]
Note that I'm currently porting the Python code to ocaml, so that semgrep-core can process a whole rule and do better optimisations.

**Comment by emjin** [comment]
Now that the Python code is ported, is this fixed?

**Comment by brandonspark** [comment]
Seems that the metavariables do unify now, the https://semgrep.dev/s/gpzn Playground example now produce a match at `r = os.system('wget %s -O "%s"'%(url, fpath))`
