### ISSUE TITLE
Semgrep report errors count  by severity

### ISSUE THREAD

**Issue by ademar59** [semgrep/semgrep#2594]
**Is your feature request related to a problem? Please describe.**

I would have in the output the errors count by severity
I try do do that but the report is not standardized to count all severity:<level> 

**Describe the solution you'd like**
i would have a clearest report at the end of scan

current:
ran 34 rules on 5 files: 17 findings

desired:
ran 34 rules on 5 files: 17 findings
3 error
12 warning
2 info

**Comment by colleend** [comment]
Thanks for your input! We'll definitely consider this when moving forward with our work.
