### ISSUE TITLE
Language support for YAML

### ISSUE THREAD

**Issue by marcelocarlos** [semgrep/semgrep#2601]
**Is your feature request related to a problem? Please describe.**

Not exactly, but my main interest/plan to use a semgrep would be to analyse IaC, such as kubernetes definitions. I can see HCL is being already tracked (https://github.com/returntocorp/semgrep/issues/1147) and hopefully available soon, however, I couldn't find references to YAML. I could obviously get away with converting it to JSON, but I believe having native support to YAML would simplify things as well as encourage contributions and growth of rules for kubernetes and other yaml-based solutions.

**Describe the solution you'd like**

Language support for YAML. I found a tree-sitter https://github.com/ikatyang/tree-sitter-yaml for YAML which might help to speed things up a bit.

**Describe alternatives you've considered**

I tried using the generic parser (spacegrep) but it has proven to be fairly difficult to work with YAML for more complex rules. Converting YAML to JSON was better, but still not ideal since it requires conversion of files before checking them.

**Additional context**

I'd love to see semgrep making IaC resources first class citizens and having YAML + HCL would be a fantastic start to allow people to contribute and add new rules to it. Being able to use the same solution for programming languages checks as well as IaC would be absolutely fantastic!

Thank you for the great work so far! 👍

**Comment by aryx** [comment]
Yep YAML is on our roadmap for Q1 2021. Cc @DrewDennison

**Comment by emjin** [comment]
Hey! @marcelocarlos I was wondering if you had specific examples you had in mind for yaml patterns that you could share. Our first priority is to implement yaml for semgrep in a way that is helpful to the people who want it. Thanks!

**Comment by marcelocarlos** [comment]
Hi @emjin, thanks for getting in touch.

What I have in mind is running checks for kubernetes definitions, such as checking if certain labels are defined in the template, if cpu/memory limits are set and within certain ranges, if a `securityContext` is defined and contains `runAsNonRoot: true` in it, etc. Basically, being able to cover rules/patterns to ensure kubernetes definitions follow best practices for pods, services, deployments, etc.

**Comment by aryx** [comment]
@marcelocarlos could you try to write those checks using an imaginary semgrep syntax for YAML?
That way we have concrete examples to follow.

**Comment by fproulx-boostsecurity** [comment]
Any chance this might ship in next release of `semgrep` ?
So many great IaC (Kubernetes, etc..) opportunities.

**Comment by aryx** [comment]
depends on the kinds of rules you want to write. Right now we still have limited support for ellipsis or metavariables in the pattern.
Do you have example of rules? That would helps us a lot for setting the right priority.
Just semgrep.dev link to hypothetical IaC yaml rules would help us a lot.

**Comment by aryx** [comment]
I think @emjin is mostly done, so alpha support for YAML should make it to the next release!

**Comment by emjin** [comment]
We've released YAML support! https://semgrep.dev/s/Ppb3
