### ISSUE TITLE
[Python] Constant tracking do not follow assignment operators

### ISSUE THREAD

**Issue by mab0te** [semgrep/semgrep#2616]
**Describe the bug**
It appears that the constant tracking feature for python is not aware of assignment operator. The result of a match differs depending on whether a (not so) constant is modified using a simple assignment or an assignment operator.

This results in false negatives where some values are considered constant when they really are not.

Being pretty new to semgrep, it is possible that I am missing something. Do not hesitate to tell me. However, the reproduction scenario appears minimal enough to indicate their is indeed something going wrong here.

**To Reproduce**
Using an assignment and an operator.
https://semgrep.dev/s/0Q2j
Using an assignment operator:
https://semgrep.dev/s/W8R2

**Expected behavior**
At least, both analysis (with an assignment and a assignment operator) should return the same result. Would also be better if both return an issue.
I would personally prefer the feature returning a false positive on the simple assignment case (eg. the normal behavior without tracking) over false negatives that could hide security issues.

**What is the priority of the bug to you?**
Would say P1. feel free to change my mind.

**Environment**
Tested on semgrep.dev and a local pip install version 0.40.0

**Comment by aryx** [comment]
@IagoAbal can you have a look?

**Comment by IagoAbal** [comment]
This works when the code is inside a function https://semgrep.dev/s/zvWd/.
But your example should work too, I'll investigate why it doesn't.

**Comment by IagoAbal** [comment]
Oh ok, I see why. It's a bug in the basic flow-insensitive constant propagation pass. It does not take assign-operators into account, so it believes `s` is a global constant. This analysis only works for global variables, that's why the bug disappears when you put the code into a function making `s` local.
