### ISSUE TITLE
read timeout on downloading the semgrep config

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2620]
```
pad@yoanns-mbp xxx % semgrep --config=p/security-audit 
using config from https://semgrep.dev/p/security-audit. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
Failed to download config from https://semgrep.dev/p/security-audit: HTTPSConnectionPool(host='semgrep.dev', port=443): Read timed out. (read timeout=10)
no valid configuration file found (1 configs were invalid)
```
This happens more and more often. This is really annoying because some CI jobs can fail because of this flakyness.

**Comment by chmccreery** [comment]
Shall we just change timeout=10 to timeout=15 or timeout=20 [here](https://github.com/returntocorp/semgrep/blob/7b5f5271fb50156c3543e904f49d5daa75acddbf/semgrep/semgrep/config_resolver.py#L401)? Or is the goal to make sure we are more reliable within the 10-second window?

**Comment by aryx** [comment]
yep, maybe we can try that first, and see if things are less flaky with a bigger timeout.

**Comment by brendongo** [comment]
I think this might also happen less often once we split out the registry service so it's more responsive

**Comment by chmccreery** [comment]
Ok, put up the shortest PR ever 😄
