### ISSUE TITLE
[MacOS] semgrep-core now uses libpcre but is not linked statically in macOS

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2624]
from https://r2c-community.slack.com/archives/CK86BJ5DW/p1614169938012300

Starting from semgrep 0.40, semgrep-core internally uses libpcre but now the binary is
linked dynamically with it, which then fails for some users who don't have libpcre installed.

```
pad@yoanns-mbp bin % pwd         
/usr/local/lib/python3.9/site-packages/semgrep/bin
(semgrep) pad@yoanns-mbp bin % otool -L semgrep-core
semgrep-core:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
	/usr/local/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.12.0)
(semgrep) pad@yoanns-mbp bin % 
```

We need to link pcre statically!

**Comment by aryx** [comment]
This might help; Another ocaml tool has a similar issue with pcre: https://github.com/comby-tools/comby/issues/89

**Comment by aryx** [comment]
@mjambon wrote: @yoann (r2c) I think the problem is that we don't have a check for this in place. If I understand correctly, the main issue is that Darwin doesn't allow full static linking. We can statically link third-party libraries like pcre or tree-sitter but not the libc implementation (something like this). @brendon (r2c) achieved static linking of libtree-sitter by some hack that we'd have to repeat for libpcre and any other C library in the future.
(also I don't have a mac, that's why Brendon will be more helpful)."

**Comment by brendongo** [comment]
Taking a look now

**Comment by brendongo** [comment]
Yeahp uninstalled pcre from my machine and was able to reproduce

**Comment by brendongo** [comment]
We do have a test that verifies the static linking on MacOS https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/build-tests.yml#L61 I'll look into it but I suspect pcre might be installed on the github action machine?

**Comment by brendongo** [comment]
Verified pcre comes preinstalled in Github action mac runners https://github.com/returntocorp/semgrep/runs/1972699180?check_suite_focus=true#step:4:1

**Comment by brendon** [comment]
Not @brendon ;)

**Comment by aryx** [comment]
did pip3 install semgrep
and verified otool -L does not return libpcre anymore for semgrep-core! Closing.
