### ISSUE TITLE
pypi dist installs a package called `tests`

### ISSUE THREAD

**Issue by richvdh** [semgrep/semgrep#2633]
**Describe the bug**

After I `pip install semgrep`, I have a package called `tests` in my virtualenv. 

I'm aware of the debate about whether or not to include tests in your sdist, and take no particular view on that, but if you're going to do it, please don't put them in the top level of the dist. I feel like cluttering the package namespace in this way is incorrect.

**To Reproduce**

```
$ pip install semgrep
$ python -c "import tests.conftest"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rav/work/synapse/env3/lib/python3.8/site-packages/tests/conftest.py", line 13, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Expected behavior**

semgrep's tests should not be installed in the root of the package namespace.

**What is the priority of the bug to you?**

P2

**Comment by richvdh** [comment]
Related: https://github.com/returntocorp/semgrep/issues/1399

**Comment by richvdh** [comment]
Bump

**Comment by richvdh** [comment]
> (you can always reopen it later).

this doesn't appear to be true: I don't seem to have permission to reopen it.

Anyway, this is still a problem. The reason I care is that it means that, if I install `semgrep` into the virtualenv for my dev environment, the tests for my own project no longer work.

**Comment by priv-kweihmann** [comment]
+1 - tests are still being installed - To my understanding that is just a side effect of using `setuptools.find_packages()` - I guess changing it to `setuptools.find_packages(exclude=("tests",))` should already do the trick.

**Comment by priv-kweihmann** [comment]
Anyone wanna take this? Basically this is super prone to collisions with various other packages.

**Comment by richvdh** [comment]
Having to bump this every few weeks is pretty annoying.

**Comment by DMRobertson** [comment]
Not an expert, but would guess that https://github.com/returntocorp/semgrep/blob/7e3fe901c5e768138b2f8c3b8a9282f390cdb8df/semgrep/setup.py#L148 could be changed to an explicit list, or else one [could pass](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#using-find-or-find-packages) `exclude=["tests"]` to `find_packages` as a list of excluded packages.

**Comment by ievans** [comment]
(added planned-project so stale bot will go away)

I do agree it's pretty obnoxious but sadly still low-priority compared to other issues for the team. @brendongo will probably get to eventually but we would welcome a PR if someone wants to beat us to it
