### ISSUE TITLE
Elucidate delayed CI errors when spacegrep changes

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2635]
Problem: when the output of spacegrep changes meaningfully and we don't update the expected output in our test suites, we should get an error in CI. Apparently we don't get these errors at the time of the pull request that introduces the changes, but they pop up in later, in unrelated pull requests.

How to reproduce (tentatively):
1. change (temporarily) the contents of the `lines` field in the json output that spacegrep passes to semgrep
2. make a fake pull request
3. see whether the tests fails. If they pass, there's something wrong; that's what we need to fix

**Comment by aryx** [comment]
Yep, got biten by this too.

**Comment by mjambon** [comment]
.

**Comment by aryx** [comment]
cleaning old issues.
