### ISSUE TITLE
Go parsed with pfff does not do nested statement matching

### ISSUE THREAD

**Issue by sfc-gh-cdai** [semgrep/semgrep#2636]
**Describe the bug**
Files parsed by _pfff_ do not catch a pattern in a nested under multiple Go functions if you use just the ellipsis. For instance, in this link:
https://semgrep.dev/s/weAA/
there should be a match on line 10, but semgrep does not show that there is a match.

However, a file parsed by _tree-sitter_ will indeed catch this pattern. Without the package and import specification, a Go file is parsed by tree-sitter (I think) and the following does match:
https://semgrep.dev/s/x1BL/

**Expected behavior**
Would expect both links to match on the _makeApiHandlerContext_ function. 

**What is the priority of the bug to you?**
P1

**Comment by aryx** [comment]
nice commit sha1 :) offdead :)

**Comment by colleend** [comment]
thanks for doing this so quickly!! 🙏  🙏 🙏
