### ISSUE TITLE
PHP parse error catching multiple exceptions using '|'

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#2650]
Repro: https://semgrep.dev/s/BkrA/

It looks like catching multiple exceptions using the `|` operator was included in PHP 7.1.0: https://www.php.net/manual/en/language.exceptions.php

**Comment by mschwager** [comment]
Hmm, looks like we're still having issues when there are multiple `catch` statements: https://semgrep.dev/s/owJ6/

**Comment by aryx** [comment]
works now
