### ISSUE TITLE
Upload rules jsonschema to schemastore

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#2654]
Apparently uploading to https://www.schemastore.org/json/ would give us autocompletion support for free in

>IntelliJ IDEA
PhpStorm
PyCharm
Rider
RubyMine
Visual Studio 2013+
Visual Studio Code
Visual Studio for Mac
WebStorm
JSONBuddy

**Comment by aryx** [comment]
but not monaco?

**Comment by underyx** [comment]
@aryx Visual Studio Code is built on monaco so we'll figure out a way to use this.

**Comment by underyx** [comment]
Done via https://github.com/SchemaStore/schemastore/pull/1494
