### ISSUE TITLE
unofficial macports package is only packaging only semgrep-core

### ISSUE THREAD

**Issue by cptcanuck** [semgrep/semgrep#2668]
**Describe the bug**

Example command does not work: semgrep -e '$X == $X' --lang=py path/to/src

'--lang' is not a command line option

semgrep -e '$X == $X' --lang=py  path/to/code
semgrep: unknown option '--lang=py'.

**To Reproduce**
run the command in the README

**Expected behavior**
README command should work

**Screenshots**

**What is the priority of the bug to you?**
P4

**Environment**
port install of semgrep

**Comment by ievans** [comment]
@cptcanuck what's the output of `semgrep --version`? It works fine for me on `0.41.1`.

I suspect that somehow you are actually invoking `semgrep-core` and not the `semgrep` CLI wrapper.

**Comment by cptcanuck** [comment]
hmm - I can't use --version either.

`> semgrep --version
semgrep: unknown option '--version'.`

but -version does:

`> semgrep -version
semgrep-core version: v0.14.0-0-g49b51d9, pfff: 0.38`

looks like you were right - I wonder how I get that sorted!  I used port to install - 

`> port info semgrep
semgrep @0.14.0 (devel)

Description:          semgrep is like grep but for code: it is a tool for easily detecting and preventing bugs and anti-patterns in your codebase. It combines the convenience of grep with the
                      correctness of syntactical and semantic search.
Homepage:             https://github.com/returntocorp/semgrep

Fetch Dependencies:   git
Build Dependencies:   ocaml, opam, pkgconfig
Platforms:            darwin
License:              LGPL-2.1
Maintainers:          Email: herby.gillot@gmail.com, GitHub: herbygillot
                      Policy: openmaintainer`

I'll find a better way to work with semgrep - docker looks more appetizing if it works!

Thanks much for getting me sorted!

**Comment by ievans** [comment]
Thanks @cptcanuck! The port isn't maintained by the semgrep maintainers, looks like it was done by @herbygillot

@brendongo looks like they packaged semgrep, but potentially only semgrep-core, for Macports and unfortunately it hasn't been updated at our weekly release pace (understandably). Want to contact the maintainer listed above and ask them for their thoughts on how to proceed?

**Comment by cptcanuck** [comment]
Thanks @ievans - just found semgrep via the SEDaily podcast and it fits my role nicely.  Gives me confidence when the community is as helpful and nice as this!

**Comment by kaldown** [comment]
✗ semgrep --version
0.41.1

```
@bp.route('/', methods=['GET'])
def all_theories():
    theories = db.session.query(Theory).filter(Theory.enabled==True).all()
    print('test')
    return theories
```

all 3 lines are "broken", but 
```
semgrep --config=p/ci --lang=py api/theory.py

sing config from https://semgrep.dev/p/ci. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 119 rules...
100%|█119/119
ran 119 rules on 1 files: 0 findings
```

why is that 0 findings?

**Comment by ievans** [comment]
@kaldown would you mind creating a separate issue? I'm going to change this to say "macports packaging only semgrep-core"

**Comment by kaldown** [comment]
@ievans done, https://github.com/returntocorp/semgrep/issues/2686
