### ISSUE TITLE
Doesn't show errors as in README

### ISSUE THREAD

**Issue by kaldown** [semgrep/semgrep#2686]
**Describe the bug**
I don't see any errors nor warnings.

**To Reproduce**
```
# theory.py
@bp.route('/', methods=['GET'])
def all_theories():
    theories = db.session.query(Theory).filter(Theory.enabled==True).all()
    print('test')
    return theories
```
```
$ semgrep --config=p/ci --lang=py api/theory.py

sing config from https://semgrep.dev/p/ci. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 119 rules...
100%|█119/119
ran 119 rules on 1 files: 0 findings
```

**Expected behavior**
Any error out of a 3:
- `print` statement
- query in controller
- not serialized object in controller

**What is the priority of the bug to you?**
I guess it is P2. Since I'm just trying to understand what's a beast `semgrep` is :D

**Environment**
```
✗ semgrep --version
0.41.1
```
from pip (same with docker)

**Comment by aryx** [comment]
@mschwager @minusworld are we missing some rules? Or should we update the README?

**Comment by brendongo** [comment]
Hi @kaldown sorry looks like this issue might have fallen through the cracks. Looking now

**Comment by brendongo** [comment]
The 3 errors you listed above are not actually in the `p/ci` rules. See https://semgrep.dev/p/ci for all the rules included there.

If we run a rule looking for `print(...)` like here: https://semgrep.dev/s/L0Nn  by running `semgrep --config https://semgrep.dev/s/L0Nn  theory.py` I get the following output: 

```
using config from https://semgrep.dev/s/L0Nn. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 1 rules...
theory.py
severity:warning rule:my_pattern_id: Match found
5:    print('test')
ran 1 rules on 1 files: 1 findings
```

**Comment by kaldown** [comment]
Thank you @brendongo, I just tried to follow the example from documentation.

Now you make it clear

**Comment by brendongo** [comment]
No worries. Closing this issue as solved then :D
