### ISSUE TITLE
semgrep.dev bug report

### ISSUE THREAD

**Issue by kaeii12** [semgrep/semgrep#2687]
https://semgrep.dev/s/x15g

**Comment by aryx** [comment]
@kaeii12 can you refine your example with actually parseable code. The target code part is not valid Javascript.
and the pattern part contains weird code like /alert.

**Comment by kaeii12** [comment]
First of all, thank you for your warning. I tried something for
experimental purposes.
I will be reviewing your application for one of my graduate courses,
but I know very little about static code analysis. I wonder if there
are any documents that you can give as webinar or pdf to find out
about the program. thank you. to your interest


Yoann Padioleau <notifications@github.com>, 4 Mar 2021 Per, 14:25 tarihinde
şunu yazdı:

**Comment by emjin** [comment]
If you're looking for an overview of semgrep, you can try https://semgrep.dev/docs/ or go through the tutorial at https://semgrep.dev/learn. You can also watch one of our presentations of semgrep, like [this one](https://www.youtube.com/watch?v=pul1bRIOYc8) from the Bay Area OWASP Meetup! Hope that helps!

**Comment by kaeii12** [comment]
thanks for information emma

Emma Jin <notifications@github.com>, 4 Mar 2021 Per, 18:28 tarihinde şunu
yazdı:
