### ISSUE TITLE
Non-string Regex

### ISSUE THREAD

**Issue by yoav-lavi** [semgrep/semgrep#2692]
**Is your feature request related to a problem? Please describe.**
I think it would be very useful to be able to set a Regex for expressions / code and not just strings. This would reduce the amount of times where you need to specify multiple patterns and allow more powerful matching.
As an example, if I want to match a (non legacy, ignoring `var`) TS / JS variable definition, I need to specify two cases - 
`const $VARIABLE ...` and `let $VARIABLE ...`. Ideally, I'd prefer to specify one case with a Regex `/(const|let)/ $VARIABLE ...` since otherwise I'd need to copy the rest of the rule as well.

**Describe the solution you'd like**
Allow Regex matching for syntax other than strings

**Describe alternatives you've considered**
The alternative is copying the pattern multiple times

**Comment by aryx** [comment]
Actually for javascript if you use 'var' we also match it to let and const. See https://semgrep.dev/s/Ekqe/

**Comment by aryx** [comment]
We also added the ability for user to define their own "equivalences", see https://semgrep.dev/docs/experiments/overview/#equivalences but it's still in beta

**Comment by mschwager** [comment]
Also note that anything you can capture in a metavariable you can use [`metavariable-regex`](https://semgrep.dev/docs/writing-rules/rule-syntax/#metavariable-regex) on. This includes variable names, expressions, basic statements, etc.
