### ISSUE TITLE
AST Selectors

### ISSUE THREAD

**Issue by yoav-lavi** [semgrep/semgrep#2693]
**Is your feature request related to a problem? Please describe.**
It would be very useful to be able to specify a semantic token which isn't a specific textual representation of code to match syntax. For example, an AST selector (either full or a simplified token representing one, e.g. `{{IfStatement}}`, `{{CallExpression}}` `{{FunctionDeclaration}}` etc.)

**Describe the solution you'd like**
A set of AST selectors or similar tokens allowing to match syntax. Adding operations on these would also be convenient (e.g. `:not`). Since you already use Tree Sitter this should be possible. (See ESLint example)[https://eslint.org/docs/developer-guide/selectors].
This would be an "advanced feature" in the sense that simple textual selectors are still available, it would just be an additional option.

**Describe alternatives you've considered**
The alternative is matching the syntax directly which isn't always possible or convenient

**Comment by aryx** [comment]
Not sure I follow what you want. The main goal of semgrep is to hide how things are represented internally (the precise name of AST nodes) and use the concrete syntax developers already know.

> The alternative is matching the syntax directly which isn't always possible or convenient

can you give more concrete examples? Right now if you want to match an IfStatement, just write 'if($E) ...',
same for calls or function declarations.

**Comment by yoav-lavi** [comment]
@aryx 
1. I'm suggesting this as an optional syntax addition, not as a replacement for the current syntax. It should not make it more complicated than it currently is to define rules
2. In a case where you want to match something that doesn't have a specific textual representation (e.g. calling an arbitrary function) not having AST selectors means you can't represent it with the current tools. If I wanted to say define a rule for cases where a function is called and there's no semicolon after, it'd either be awkward or impossible with the current syntax (`()` but not `();` wouldn't work since `()` can be things other than a function call)
