### ISSUE TITLE
[Java] can't parse enum class patterns

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2715]
https://semgrep.dev/s/zvrW

**Comment by IagoAbal** [comment]
The problem seems to be the ellipsis.

**Comment by IagoAbal** [comment]
This pattern works

```
enum $A { ; ... }
````

We just need to tweak the grammar and allow omitting the `;`.

**Comment by IagoAbal** [comment]
Should be fixed by returntocorp/pfff#399.
