### ISSUE TITLE
typescript parsing bug: support 'variable as keyof Interface<SomeType>;'

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#2736]
https://semgrep.dev/s/Avq8

verified as parsing correctly in TS4.0

Possibly fixed by https://github.com/tree-sitter/tree-sitter-typescript/pull/138?

**Comment by nbrahms** [comment]
@underyx Do you know the user's priority?

**Comment by mjambon** [comment]
It was fixed in the tree-sitter grammar. Needs upgrade in semgrep.

**Comment by mjambon** [comment]
The fix will be in semgrep 0.56 due this week.
