### ISSUE TITLE
typescript parsing bug: trailing comma after tuple element objects in an interface declaration

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#2738]
https://semgrep.dev/s/Do6o

Verified to compile correctly in TS4.0

**Comment by nbrahms** [comment]
@underyx Do you know the user's priority?

**Comment by mjambon** [comment]
Tracked at https://github.com/tree-sitter/tree-sitter-typescript/issues/143

**Comment by mjambon** [comment]
The fix will be in semgrep 0.56 due this week.
