### ISSUE TITLE
Produce a human-readable performance report from the output of --json-time

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2744]
Semgrep now has a `--json-time` option that dumps one duration per pair (rule, target). On real code bases, this is a lot and it's not human-readable.

Let's create a script that takes this json output and produces a human-readable report. This report might include things like:
* total matching time
* total matching time per rule
* total matching time per target
* or only top 10 slowest targets by matching time
* or only top 10 slowest rules by matching time
* same as above but divided by the number of lines in the target
* other?

Parsing time is also probably useful, but it's complicated to obtain since we cache the AST, which should be cheaper than full parsing but also has its cost. We could report the total time spent by semgrep (not semgrep-core) on each target, and subtract the matching time. This would give us the time spent on "other things than matching", which could be substantial.

**Comment by aryx** [comment]
sounds like a good start
