### ISSUE TITLE
Golang Ellipsis in Return Types

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#2746]
**Describe the bug**
Semgrep fails to parse when the ellipsis is used in Golang function return types specification. 

**To Reproduce**
https://semgrep.dev/s/Gevp/

**Expected behavior**
Would expect that the pattern parses and that the function test would be matched.

**What is the priority of the bug to you?**
P2

**Comment by aryx** [comment]
some discussions about possible implementations: https://r2c-community.slack.com/archives/C01LNF69F9B/p1622066772009400

**Comment by zabbal** [comment]
The corresponding issue is still open so the ticket is still relevant.
