### ISSUE TITLE
Java 12 Switch Statements

### ISSUE THREAD

**Issue by weibrian** [semgrep/semgrep#2753]
**Describe the bug**
Errors when parsing java 12 [enhanced switch statements ](https://openjdk.java.net/jeps/325)

**To Reproduce**
Code that looks something like: 
```
int i = switch (c) {
    case 'a' -> 420;
};
```

**Expected behavior**
does not have a parse error

**Screenshots**
Link: [https://semgrep.dev/s/Lw5r](https://semgrep.dev/s/Lw5r)

**What is the priority of the bug to you?**
P2, but really not important to me

**Environment**
Installed using brew install semgrep on macOS 11.2.1

**Comment by aryx** [comment]
created an issue upstream in tree-sitter-java.

**Comment by aryx** [comment]
@emjin maybe it's related to the record extension of Java we are planning to add.
