### ISSUE TITLE
The message contains a truncated expression during substitution

### ISSUE THREAD

**Issue by dgryski** [semgrep/semgrep#2763]
**Describe the bug**

The message contains a truncated expression during substitution:

"use w.Write(b[:n) instead of io.WriteString when b[:n is []byte"

**To Reproduce**

Playground link: https://semgrep.dev/s/BkKW/

**Expected behavior**

The $VAR replacement should include the trailing `]` character.

**What is the priority of the bug to you?**
P3: minor cosmetic issue, although it might affect applying auto-fix suggestions.

**Comment by mschwager** [comment]
Hey @dgryski,

Thanks for the heads up. I suspect `semgrep-core` has a off-by-one error on the range returned for the metavariable. cc @aryx

**Comment by aryx** [comment]
@emjin want to take a look? probably some missing tokens in the AST somewhere got lost along the way.
