### ISSUE TITLE
Need to be able to annotate rule disablements

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2779]
**Is your feature request related to a problem? Please describe.**
I have found it necessary to disable certain rules (from otherwise useful rulesets) due to them either being:
(a) "not a problem" in my code base
(b) comes down to a matter of style
(c) a rule that does not make sense
(d) a faulty rule
At the time I make that election I know the reason, but the next time I go to look at my policy, or if someone else is looking, that knowledge is gone.

<img width="589" alt="image" src="https://user-images.githubusercontent.com/6817500/111651506-86827080-87c3-11eb-9fdc-67bb902532f7.png">

**Describe the solution you'd like**
Need some way to add an annotation or comment to each disabled rule.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by dlukeomalley** [comment]
Copying from Semgrep Slack ([here](https://r2c-community.slack.com/archives/CK86BJ5DW/p1616081908009700?thread_ts=1616081632.009200&cid=CK86BJ5DW)):

> Thank you Michael. I’m so torn on this feature, mostly because I want to kill the idea of rulesets in policies and move to a flat list of rules in policies. This is motivated by a few reasons: rulesets are proving confusing to folks, if you want to move a rule from one policy to another it’s not clear how to do that, and we’re gearing up to start recommending relevant rules based on your codebase and past findings.
>
> IF we removed rulesets and made it a flat list, I still think this feature is useful, but from a slightly different angel: when making changes to a policy there could/should be a “commit” step in which a message is left explaining the change. Major difference here is you wouldn’t see that a specific rule was disabled (because it would no longer show up in the policy), BUT you would see a log of changes.
>
> What do you think? :smile:

**Comment by chmccreery** [comment]
@dlukeomalley where do we go from here? This seems to me like sprint/product work more than bug fixing, can we remove from Customers/on-call board?
