### ISSUE TITLE
Regex matching fails with literal backticks

### ISSUE THREAD

**Issue by ropnop** [semgrep/semgrep#2780]
**Describe the bug**
Semgrep regex will not find matches within backticks, making rule creation for Javascript template strings impossible

**To Reproduce**
https://semgrep.dev/s/Kl7P

**Expected behavior**
I would like to match the JS template string with variable expansion in line 1, but not line 2. 

**What is the priority of the bug to you?**
P2. String expansion with tainted variables are an issue we want to use semgrep to identify

**Comment by mschwager** [comment]
Similar issue: https://github.com/returntocorp/semgrep/issues/2486

But I agree, I would expect the [regex string matching](https://semgrep.dev/docs/writing-rules/pattern-syntax/#string-matching) to work inside backticks in Javascript :+1:

**Comment by emjin** [comment]
Would it be sufficient to make either of the latter two patterns in https://semgrep.dev/s/we5x work instead?

**Comment by ropnop** [comment]
Sure! The end result I need is to flag string templates with variables and distinguish them from just backticked strings with no variables. Regex was the solution I was trying, but i'd be happy if either of the latter two worked instead

**Comment by aryx** [comment]
Yes, you cant use regexp for that. The regexp can't see the $ in the backticked string, because internally those are transformed in an expression.

**Comment by aryx** [comment]
@emjin fixed the underlying request, but the title of the issue itself is a wontfix I think.

**Comment by emjin** [comment]
You can use this https://semgrep.dev/s/DJwy/?version=develop to match what you want on develop now!
