### ISSUE TITLE
Javascript parsing error: export * as name1 from …;

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2781]
**Describe the bug**
Javascript parsing error: `export * as name1 from …;`

**To Reproduce**
https://semgrep.dev/s/dKGP

**Expected behavior**
No parsing error.

**What is the priority of the bug to you?**
P1

**Comment by Isaac0616** [comment]
Some reference:
https://github.com/tc39/proposal-export-ns-from
https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export (search "Draft ECMAScript® 2O21")

**Comment by aryx** [comment]
seems related to https://github.com/returntocorp/semgrep/issues/1950
I wonder if we could fix both at the same time

**Comment by aryx** [comment]
oh there's also https://github.com/returntocorp/semgrep/issues/1995

**Comment by dlukeomalley** [comment]
Thank you @Isaac0616, queuing this up for our support team to look into this week and get back to you with thoughts/fix ETA.

**Comment by mjambon** [comment]
Tracked at https://github.com/tree-sitter/tree-sitter-javascript/issues/172

**Comment by nbrahms** [comment]
Fixed in https://github.com/tree-sitter/tree-sitter-javascript/pull/180

**Comment by nbrahms** [comment]
@mjambon Has this tree-sitter parser been integrated? We still seem to be getting a parse error in current Semgrep.

**Comment by mjambon** [comment]
@nbrahms yes, the tree-sitter integration was done, so we can now parse a target program successfully:
```
$ semgrep-core -lang js -dump_ast <(echo 'export * as someIdentifier from "someModule";')
Pr(
  [DirectiveStmt(
     {d_attrs=[]; 
      d=OtherDirective(("ReExportNamespace", ()), [Str(("someModule", ()))]); })])
```
However, it's not supported as a pattern, since we use the pfff parser for this:
```
$ semgrep-core -lang js -dump_pattern <(echo 'export * as someIdentifier from "someModule";')
/tmp/semgrep-core-67b76d-63:1:0: Fatal error: Parsing.Parse_error
...
```

**Comment by mjambon** [comment]
@nbrahms we should reopen this issue if you confirm that we're getting a parse error on a target.
