### ISSUE TITLE
Policy view should check whether disabled rules still exist

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#2782]
**Describe the bug**
When a disabled rule from a ruleset has been deleted in the ruleset, that needs to be reflected when viewing the policy. As shown I opened the policy then opened the set of disabled rules for a ruleset.

<img width="322" alt="image" src="https://user-images.githubusercontent.com/6817500/111728680-9d0fe280-882a-11eb-87ea-ed124a489837.png">

Selecting the rule attempts to open up that rule in the repository view, but in this case:
<img width="973" alt="image" src="https://user-images.githubusercontent.com/6817500/111728210-a77dac80-8829-11eb-83a2-ed7acfc33971.png">

**To Reproduce**
1. Add a ruleset to a policy.
2. Disable a rule from that ruleset.
3. Delete the rule from the underlying ruleset.
4. Return to the policy view again.
5. Open the disabled list for the ruleset.
6. Select the disabled rule (now non-existent rule).

**Expected behavior**
One possible scenario:
When a policy is opened, the system scans any disabled rules to see if there are any that no longer exist.
If any found, emit a notification on the screen, directing the user to take action, which would always be to open the given ruleset and remove the disabled rule.

Of course, if a scan finds some non-existent rules, they could be removed without user intervention, but I think it is much more prudent to let the user be involved to raise awareness.

**Screenshots**
Above

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?
P2 -- does not really hurt anything

**Environment**
Policies view

**Comment by dlukeomalley** [comment]
@minusworld @dan5382 @adamberman - I'm increasingly becoming a fan of stopping the use of rulesets in policies, choosing instead to just add all the rules from a ruleset to a policy and making it easy within a policy to manage them. Is this something we can include as part of the Dashboard > Policy work we're pursuing these next few weeks?

**Comment by chmccreery** [comment]
@dlukeomalley where do we go from here? This seems to me like sprint/product work more than bug fixing, so I am removing from customers board/on-call work. Please add it back if you disagree.

**Comment by dlukeomalley** [comment]
Sounds good @chmccreery!

@msorens I'm interested in tackling this work with two upcoming projects: versioned rules, getting rid of rulesets. Are you ok with me either closing this ticket and/or merging it with my internal tracking ones?

**Comment by msorens** [comment]
As we have discussed, I am on board with getting rid of rulesets. Seems like this issue would still be applicable at the policy level though, no? 
OK with me to handle this as you see fit.

**Comment by chmccreery** [comment]
Maybe what @dlukeomalley was thinking was we may no longer have a thing called "overrides" if policies are just a flat list of rules - to disable a rule, you would remove the rule instead of "disabling" it inside a ruleset.

**Comment by dlukeomalley** [comment]
> Maybe what @dlukeomalley was thinking was we may no longer have a thing called "overrides" if policies are just a flat list of rules - to disable a rule, you would remove the rule instead of "disabling" it inside a ruleset.

Exactly. You wouldn't have anything to override in a world that doesn't support depending on / inheriting from a ruleset. I imagine you'd just remove the rule from your policy. If we take this approach, I'd expect to provide a policy history so you can see how it has changed over time.

I'm still wrestling with how users will add related rules in the registry to their policy. Without rulesets, are people just adding all rules that match a search criteria (with r2c providing some preset searches in place of existing rulesets)? What happens when new rules matching that criteria are added to the registry (or removed)?

**Comment by chmccreery** [comment]
I have been wondering about this ^ too, but it seems to me like a great opportunity for r2c, after writing and vetting new rules, to just email users on a semi-regular cadence with "new rules we recommend for you" based off of which rules they are running right now. This seems like a pretty easy recommendation system to create, given that the rules are already tagged with languages, frameworks, bug-classes, etc.

**Comment by dlukeomalley** [comment]
+1, and we could also take the Craigslist "Saved Search" feature as inspiration (i.e. subscribe to a search query and get notified when new results match your query).
