### ISSUE TITLE
Semgrep is exits with error code 2 without further details

### ISSUE THREAD

**Issue by arjunkhunti-crest** [semgrep/semgrep#2784]
While scanning the [addonfactory-ucc-generator](https://github.com/splunk/addonfactory-ucc-generator) repository with semgrep v0.43.0 execution gets terminated with error code 2. 

**Command used for execution**
```bash
semgrep --config="p/r2c-ci" --config="p/r2c-security-audit" --config="p/bandit" --strict --verbose --timeout=0 --junit-xml -o semgrep-scan.xml
```

**Attachment:**

![image](https://user-images.githubusercontent.com/69838413/111776964-a192d480-88d8-11eb-859d-ceb8eb9b72fe.png)

**Steps to reproduce:**
```bash
pip3 install semgrep==0.43.0
git clone https://github.com/splunk/addonfactory-ucc-generator.git
semgrep --config="p/r2c-ci" --config="p/r2c-security-audit" --config="p/bandit" --strict --verbose --timeout=0 --junit-xml -o semgrep-scan.xml
```

**Comment by bt-nia** [comment]
Without `--verbose`, there's no output here? I think I have the same behaviour in one of my internal repos with these 3 (and more) rulesets in place.

**Comment by mschwager** [comment]
Hmm, I wonder if this is the same as https://github.com/returntocorp/semgrep/issues/2784, but with `--junit-xml` instead of `--sarif`. I'll investigate :+1: 

EDIT: Oops, I meant https://github.com/returntocorp/semgrep/issues/2748, 2748 <-> 2784 :confused:

**Comment by nbrahms** [comment]
Thanks for the contribution @arjunkhunti-crest ! I'm assuming that this issue is now closed? If it is not, please reopen. 🙇
