### ISSUE TITLE
Typescript parsing error: typeof const_array[number]

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2790]
**Describe the bug**
Encountered a typescript parsing error in our codebase.
It seems to be the usage of creating types from values in an array.

**To Reproduce**
https://semgrep.dev/s/eLRX

**Expected behavior**
No parsing error.

**What is the priority of the bug to you?**
P1

**Comment by mschwager** [comment]
Thanks for the heads up! cc @mjambon

**Comment by mjambon** [comment]
Tracked at https://github.com/tree-sitter/tree-sitter-typescript/issues/141

**Comment by mjambon** [comment]
In the latest version of the tree-sitter-typescript grammar, this is no longer reported as a parse error, but it is parsed incorrectly.

**Comment by mjambon** [comment]
The fix will be in semgrep 0.56 due this week.
