### ISSUE TITLE
Typescript parsing error: readonly modifier in angle brackets

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2792]
**Describe the bug**
Typescript parsing error: readonly modifier in angle brackets.

**To Reproduce**
https://semgrep.dev/s/7oLv

**Expected behavior**
No parsing error.

**What is the priority of the bug to you?**
P1

**Comment by mjambon** [comment]
Hey @Isaac0616. The snippet in https://semgrep.dev/s/7oLv is:
```typescript
const values: readonly string[] = ["a", "b", "c"];
Array<readonly string[]>;
```
The second line is just a type expression, which is invalid in this position, [as seen in the typescript playground](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAbgQwDYFcCmEBcMBOaEAm4SAnjNDgJZgDmA2gLowC8MdARAuwDQzsBGPPsHYMA3ACgAgjhwISAHjyFiZCtXoMAfJKA). The following would be valid:
```typescript
type Strings = Array<readonly string[]>;
```
~~Semgrep is fine with the above (https://semgrep.dev/s/8nk4/), but [the typescript playground doesn't like it](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwM5QLxQIL3gEMQAeeCQgEwHtkAbEKdBFVAPgG4AoIA), giving this error:~~
> ~~'readonly' type modifier is only permitted on array and tuple literal types.~~

Edit:
I made a mistake above (forgot `[]`). I can't produce an error with the current version of semgrep. The following works fine:
```typescript
type Strings = Array<readonly string[]>;
```
The following (https://semgrep.dev/s/gJGy/) is fine too:
```typescript
const values: Array<readonly string[]> = ["a", "b", "c"];
```
