### ISSUE TITLE
`semgrep --test` a yaml file

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2799]
**Is your feature request related to a problem? Please describe.**
Currently, `semgrep --test` doesn't allow a yaml file to be the test file even the rules and test files are separated.
For example, `semgrep --test --config rules/ tests/` will ignore `x.yaml` in the following dir structure.
```
project/
  rules/
    x.yml
  tests/
    x.py
    x.yaml
```
The current workaround is using other file extensions for the generic patterns, but I think once the yaml language rule is supported (#2601), we need some way to support it.

**Describe the solution you'd like**
I can see that semgrep will confuse if both rules and tests with yaml/yml extension are in the same directory.
Not sure what's the best solution.
Maybe use special extension that semgrep would treat it as yaml during testing.

**Comment by aryx** [comment]
We could maybe add somewhere a is_semgrep_yaml() function to differentiate a regular yaml file from a semgrep yaml file.
@mschwager what do you think?
A problem though is that we started to write semgrep rules on semgrep rules thx to the yaml support in semgrep, so sometimes we actually need to process a semgrep rule yaml file as a target file :)

**Comment by mschwager** [comment]
Yup, we can add some additional logic to differentiate in this special case. A few quick thoughts:

- We could support a new extension like `.test.yaml` which supersedes existing logic, e.g. `foo.yaml` and `foo.test.yaml`
- We could add an additional flag like `--test-yaml` - not ideal, it'd be nice to generalize
- We could require the configuration and tests to be in different directories for YAML - not ideal, another special case

**Comment by aryx** [comment]
I like option 1.

**Comment by fproulx-boostsecurity** [comment]
I like the idea of `foo.test.yaml`. It does not make yaml a special case as much as having to use a different flag....
