### ISSUE TITLE
[Javascript] Can't use ellipsis in body of lambda

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2802]
https://semgrep.dev/s/x1Ke

If you replace ... by $XXX it works, but ... generates a parse error.
reference conversation: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1616512805025200?thread_ts=1616429605.020000&cid=C018NJRRCJ0

**Comment by aryx** [comment]
You can overcome the limitation by using a metavariable, so I've put low priority for now.

**Comment by aryx** [comment]
@emjin want to look at this?

**Comment by emjin** [comment]
I can take a look! I have a couple issues I would want to get to first

**Comment by aryx** [comment]
hmm actually I think it's a small fix; I'll do it.

**Comment by aryx** [comment]
I'm making a new release today, so better to get this fix in before

**Comment by aryx** [comment]
weird, does not seem to work in the playground.

**Comment by aryx** [comment]
just docker which took time to get the latest develop.
