### ISSUE TITLE
Constant propagation causes =~"//" string matching to match assigned variable

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#2805]
**Describe the bug**
To be honest, I'm not sure if this is a bug to be fixed, or just unintuitive behavior. It was surprising to me as a user.

If you have a pattern like `"=~/http:///"` and are matching code like:

~~~python
a = "http://example.com"
~~~

The pattern will match that line **twice**, once for the right hand side string AND (the surprising part) the variable assigned, `a`. 

This caused me to believe Semgrep was duplicating results, though this constant propagation is perhaps intended behavior.

**To Reproduce**
https://semgrep.dev/s/clintgibler:http-leak-source-code

**Expected behavior**
I expected only the right hand side, `"http://example.com"` to match, but based on how constant propagation works, the current behavior might be the "correct behavior."

I created this issue to track this behavior because I think it's unintuitive for users, but I don't know if we want to "fix" it 🤷 

**Screenshots**

**What is the priority of the bug to you?**
P2

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by IagoAbal** [comment]
It's a known issue and when this happens inside a function is quick to fix https://semgrep.dev/s/DJyq/, so I' ll do soon. It's trickier to fix for the global const-propagation.
