### ISSUE TITLE
Allow multiple rules to be triggered by the same line in test files.

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2806]
**Is your feature request related to a problem? Please describe.**
Sometimes, different rules will be triggered by the same line.
However, we are not able to comment two `ruleid: ` on the same line.
We can try to avoid it by changing the test code, but it would be more convenient to comment multiple rule ids.

This happens when we have two rules to catch similar things.
One is for a more generic case.
The other is for a more specific case with more actionable message.

**Describe the solution you'd like**
Maybe we can allow a comma separated list of rule ids like `# ruleid: id-a, id-b` or be able to comment in multiple lines like
```
# ruleid: id-a
# ruleid: id-b
target
```

**Comment by Isaac0616** [comment]
Found that there used to be another issue (#753)

**Comment by minusworld** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/2923

**Comment by minusworld** [comment]
@Isaac0616 - I ended up doing comma-separated since that was a bit easier to implement. Please let us know if it works as expected. Thanks! 👍 🙏

**Comment by Isaac0616** [comment]
Thanks! I will check it out.
