### ISSUE TITLE
matching Ruby's backticks

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#2826]
1) \`...\` - does not match backticks with variables like: \`foo #{bar}\`
https://semgrep.dev/s/YgKD/

2) \`...#{...}...\` - will srictly match backticks with only one `#{...}`
https://semgrep.dev/s/6rWW/

It makes it impossible to match backticks without knowing how many `#{...}` are used beforehand.

Even though backticks in Ruby and JS/TS are slightly different things, I as a user would expect similar behaviour while matching them:

```
`...` - match any backticks e.g. `hello world`, `foo #{bar}`

`...#{...}...` - match any backticks with one or more #{...} inisde and regardless of its position e.g. `foo #{bar}`, `#{bar} foo #{buzz}`
```

**Comment by aryx** [comment]
@emjin maybe your recent fix for Javascript could work for Ruby too?

**Comment by emjin** [comment]
Looks like it doesn't :(
