### ISSUE TITLE
[YAML] cheatsheets for YAML

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2830]
See the sidebar on the right at
https://staging.semgrep.dev/s/JqoR/

We miss many tests in semgrep-core showing how to write patterns for YAML.
Of course YAML is not really a programmnig language, so many of those tests are hard to write for YAML,
but maybe there are a few we can do.

**Comment by aryx** [comment]
Note that JSON also has the same problem. Maybe we need another set of tests files for InfrastructureAsCode languages.

**Comment by emjin** [comment]
Closing because the tests are too hard to write for YAML; we should have another set of test files
