### ISSUE TITLE
Performance issue with `metavariable-regex`

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2835]
**Describe the bug**
It is not necessary a bug.
I am trying to scan a very large json config file with generic pattern.
If I use the pattern:
```
patterns:
    - pattern-inside: |
        "SYMM_KEY": {
            ...
        }
```
It is very performant and returns the result with in a second.
However, if I try use the following pattern for better extensibility
```
patterns:
  - pattern-inside: |
      "$SECRET_NAME": {
          ...
      }
  - metavariable-regex:
      metavariable: "$SECRET_NAME"
      regex: "SYMM_KEY"
```
It would take several minutes.
I am guessing that it becomes so slow because it has to invoke regex matching in Python many times.
Not sure whether it can be improved.

In addition, I tried to specified the the `--timeout` argument, but it didn't seem working.

**Comment by aryx** [comment]
Can you attach this big .json file, so we can troubleshoot and reproduce easily?
A link to semgrep.dev would be ideal.

**Comment by aryx** [comment]
We're actually in the process of transferring some of the logic from Python to OCaml, so this could be a case where semgrep-core could handle really faster than semgrep.

**Comment by Isaac0616** [comment]
Let me find a reproducible example.
The original json contains some sensitive information.

**Comment by Isaac0616** [comment]
I generate a json file with
```
import json

config = {
    f"key{i}": {
        "config1": "value1",
        "config2": "value2",
        "config3": "value3",
    } for i in range(1000)
}
print(json.dumps(config, indent=2))
```

The rule
```
    patterns:
      - pattern-inside: |
          "$SECRET_NAME": {
              ...
          }
      - metavariable-regex:
          metavariable: "$SECRET_NAME"
          regex: "key999"
```
would be more than 10 times slower than
```
pattern-inside: |
  "key999": {
      ...
  }
```
on my machine.

If the json file is larger, the performance difference would be larger.

semgrep.dev: https://semgrep.dev/s/9q0R

**Comment by aryx** [comment]
Ok, this kind of things should go faster once we shipped the new experimental matching engine.
If you use semgrep --experimental on the command-line, you'll see this test goes from 5s to 0.5s.

**Comment by aryx** [comment]
BTW, you should be able to use 'json' instead of 'generic' once I fix https://github.com/returntocorp/semgrep/issues/2914

**Comment by aryx** [comment]
Note that I've fixed things so that you can also use the 'json' language instead of 'generic' for your example:
https://semgrep.dev/s/bDge?version=develop

**Comment by Isaac0616** [comment]
@aryx Is the progress of experimental matching engine tracking somewhere?
I am pretty excited about this feature.

**Comment by aryx** [comment]
On Thu, Apr 22, 2021 at 6:00 AM poning ***@***.***> wrote:

> @aryx <https://github.com/aryx> Is the progress of experimental matching
> engine tracking somewhere?
> I am pretty excited about this feature.
>

Going through my email backlog ... yes it's tracked somewhere, it's also now
the default mode, so your example should go faster now with 0.56.
