### ISSUE TITLE
Typescript parsing error: ({ foo }: { foo: number })

### ISSUE THREAD

**Issue by bard** [semgrep/semgrep#2841]
**Describe the bug**

Typescript parsing error: function declaration with argument destructuring

**To Reproduce**

https://semgrep.dev/s/GWRG/

**Expected behavior**

No parsing error.

**What is the priority of the bug to you?**

P2

**Comment by underyx** [comment]
For the record, I verified the provided sample compiles correctly in TypeScript 4.x

**Comment by aryx** [comment]
I have a hard time myself "parsing" this code mentally.

**Comment by bard** [comment]
For the record: I realized this only happens in type declarations, where the argument destructuring brings little value anyway, and replacing `<{ report: ({error}: { error: Error }) => void }>`  with  `<{ report: (args: { error: Error }) => void }>`  is perfectly fine. Initially, it appeared that argument destructuring wasn't parsed in function definitions either, but that's not the case. As such, I've edited the description to reflect the lower importance.

**Comment by underyx** [comment]
Thanks for the update @bard! I'll update the priority label accordingly.

**Comment by nbrahms** [comment]
> I have a hard time myself "parsing" this code mentally.

https://semgrep.dev/s/B4y7/ is a simpler expression of the issue.

**Comment by mjambon** [comment]
Tracked at https://github.com/tree-sitter/tree-sitter-typescript/issues/144

**Comment by mjambon** [comment]
https://semgrep.dev/s/B4y7/?version=develop

The fix will be in semgrep 0.56 due this week.
