### ISSUE TITLE
[Javascript] import * as $BROWSER from xxx does not bind correctly $BROWSER

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2846]
**Describe the bug**
See https://semgrep.dev/s/KWdj/

$BROWSER is bound to 'browser' in one case and 'module/core/browser' in the other preventing
both metavariables to be unified.

It would also be good to find a way to describe both cases without using pattern-either. How to
qualify the call to unsafeRedirect from "modules/core/browser" in one way and match all the possible variations,
like we do for Python?

**What is the priority of the bug to you?**
P2 (regular bug that should get fixed)?

**Comment by aryx** [comment]
For reference, origin of the discussion: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1616770539056600

**Comment by brendongo** [comment]
I think this works as expected.
