### ISSUE TITLE
[Go] support for `select` blocks and matching cases inside of those

### ISSUE THREAD

**Issue by hex0punk** [semgrep/semgrep#2847]
**Is your feature request related to a problem? Please describe.**
Currently, there is no clean way to write a pattern for this:

```go
func request() {
    c := make(chan int)
    for i := 0; i < 5; i++ {
        i := i
        go func() {
            select {
              case c <- i:
              default:
            }
        }()
    }
}
```

**Describe the solution you'd like**
I am interested in finding where the channel send occurs, but because it occurs as a `case` inside of a `select` block, there is no way to detect that in semgrep without getting a `Pattern could not be parsed as a Golang semgrep pattern` error

I would like to specify a pattern like this 

```yml
  pattern: |
    go func(...) {
      ...
      select {
        case $CHANNEL <- $VAR
      }
      ...
    }(...)
    ...
```

or even this 

```yml
    go func(...) {
      ...
      case $CHANNEL <- $VAR
      ...
    }(...)
    ...
```

to detect where data is sent to a go channel as a `case` inside `select` blocks 

**Describe alternatives you've considered**
This won't work where channel sends occur as `case`s

```yml
rules:
- id: test
  pattern: |
    go func(...) {
      ...
      $CHANNEL <- $VAR
      ...
    }(...)
    ...
  message: |
    test
  severity: WARNING
```

**Additional context**
This is a very common concurrency pattern in go

**Comment by aryx** [comment]
I think this is better (which you suggested on slack): 
```
rules:
- id: test
  patterns:
  - pattern: |
        go func(...) {
          ...
          select {
             ... 
             case $CHANNEL <- $VAL
             ...
          }
          ...
        }(...)
        ...
  message: test
  languages: [go]
  severity: WARNING
```

**Comment by hex0punk** [comment]
> I think this is better (which you suggested on slack):
> 
> ```
> rules:
> - id: test
>   patterns:
>   - pattern: |
>         go func(...) {
>           ...
>           select {
>              ... 
>              case $CHANNEL <- $VAL
>              ...
>           }
>           ...
>         }(...)
>         ...
>   message: test
>   languages: [go]
>   severity: WARNING
> ```

yep, agreed

**Comment by ievans** [comment]
hi @hex0punk, thanks so much for creating an issue! can you share the relative priority of this for you -- is it blocking your adoption of semgrep (p0), a significant problem to using semgrep for you (p1), or a minor annoyance (p2)?

playground link: https://semgrep.dev/s/Nr4L

**Comment by hex0punk** [comment]
> hi @hex0punk, thanks so much for creating an issue! can you share the relative priority of this for you -- is it blocking your adoption of semgrep (p0), a significant problem to using semgrep for you (p1), or a minor annoyance (p2)?
> 
> playground link: https://semgrep.dev/s/Nr4L

for sure! 

**Priority**: (p2)
**Reason**: not a significant problem at the moment, just working on new semgrep rules while I have time. It _is_ a common pattern in go though.

**Comment by aryx** [comment]
link https://semgrep.dev/s/nqqg/

**Comment by aryx** [comment]
This works now on develop: https://semgrep.dev/s/nqqg/?version=develop
Note that you need to use 'case ...' inside a select/switch, and not just '...' because
of ambiguities otherwise in the grammar.
