### ISSUE TITLE
typescript: tainting:  Deep-expression operator not allowed in pattern-sources

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#2849]
****Describe** the bug**
Trying to use deep-expression patterns results in a parser error (the pattern is considered invalid). This works fine for other languages (e.g. Python).

**To Reproduce**
https://semgrep.dev/s/e4LR/

**Comment by aryx** [comment]
Seems to work actually: https://semgrep.dev/s/Q85d/
Does not seem to work at the toplevel, but it does not really make sense to use <... location.href ...> at the toplevel; just remove
the <... ...> and it would work the same.

**Comment by IagoAbal** [comment]
Hmm, this does work in Python however, you can write a top-level deep-expression pattern: https://semgrep.dev/s/Wggj/.

I wanted to propose using

```yaml
    pattern-sources:
      - <... location.href ...>
```

 in #2787 since that would at least make one of the inline examples work, but the pattern is considered invalid.

**Comment by aryx** [comment]
yes maybe the python grammar allows toplevel deep-expr pattern, but as I said, they are useless; The only use of the deep-expr pattern is when it's not at the toplevel but inside a stmt or expression; otherwise just use the location.href and it will be equivalent.

**Comment by IagoAbal** [comment]
I understand it's useless when given to Semgrep directly, but
```yaml
    pattern-sources:
      - location.href
 ```
is not equivalent to
```yaml
    pattern-sources:
      - <... location.href ...>
 ```
In the former case it only matches a RHS that is exactly `location.href`, whereas using deep-expression patterns you can match `location.href` against any subexpression of the RHS.

**Comment by IagoAbal** [comment]
See example from #2787:

```typescript
    // NOT WORKING - Mutate before use
    const c = location.hash + "bbb";
    // todoruleid: typescript.nestjs.security.test-taint-mode
    return React.createElement("a", { href: c });
```
We can make this example work in other ways, but one workaround would be to use deep-expression patterns. Not sure how useful they would be in general.

**Comment by aryx** [comment]
oh I see, then it's the code handling pattern-sources: that we need to fix.

**Comment by IagoAbal** [comment]
If it is desirable to make the pattern in `pattern-sources:` match against any subexpression, then I could give it a try myself.

**Comment by mjambon** [comment]
It this just a matter of tweaking the syntax extension of tree-sitter-typescript for semgrep?

**Comment by aryx** [comment]
For JS/TS we actually still use the pfff parser for the pattern.
And yes we could tweak the grammar to allow toplevel <... ...>, but as I said, it does not make much sense to use <... ...> at the toplevel, so I'd rather fix pattern-sources: instead.

**Comment by IagoAbal** [comment]
I took a quick look, I see two choices:

1. Read `pattern-source` as a deep-expr pattern even if it's not. So just read the pattern and then wrap it in a `DeepEllipsis`.
2. Use `Semgrep_generic.check` instead of `Semgrep_generic.match_e_e` to match `pattern-source`s.

Choice 1 is easier to implement.

What do you think? Any better way to fix this that I missed?

Also, I guess this is only desirable for `pattern-source`?

**Comment by aryx** [comment]
ok, let's go with 1. for now. I wrote this code a long time ago, so I don't really remember it.

**Comment by IagoAbal** [comment]
PR #2881 effectively fixes this problem, although it does it in a different way than it was proposed here. I'm closing the issue but please reopen if you disagree.
