### ISSUE TITLE
[Benchmark] make sure the different SemgrepVariant return the same findings

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2852]
Probably need to pass --json to semgrep and then make sure the result finding sets are equal to the base (the std SemgrepVariant).

**Comment by aryx** [comment]
@mjambon is pretty busy this week with being OnCall so if @emjin you could implement it that would be great.

**Comment by mjambon** [comment]
I didn't do it initially under the assumption that the correctness of semgrep was tested elsewhere. New bugs could still show up here, so this sounds like a good idea.
