### ISSUE TITLE
Automatically detect deeply-chained calls on objects through assignment

### ISSUE THREAD

**Issue by fasiha** [semgrep/semgrep#2859]
## Is your feature request related to a problem? Please describe.
As described on [Slack](https://r2c-community.slack.com/archives/CK86BJ5DW/p1617137770088500), the pattern
```yaml
- pattern: pandas.DataFrame(...).index.set_value(...)
```
works great on code where this entire chain is present, but does not work if it's broken by assigning to variables, e.g., the above rule can't catch
```python
df = pd.DataFrame(x)
ix = df.index
ix.set_value(a, b, c)
```

## Describe the solution you'd like
It would be wonderful if the pattern `pandas.DataFrame(...).index.set_value(...)` can recognize when the call chain is broken by simple assignment, perhaps in line with #2783?

## Describe alternatives you've considered
The current workaround would be *two* additional rules that use separate `pattern-inside`, specifically,
```yaml
- pattern-inside: |
    $DF = pandas.DataFrame(...)
    ...
    $DF.index.set_value(...)
```
and
```yaml
- pattern-inside: |
    $DF = pandas.DataFrame(...)
    ...
    $IX = df.index
    ...
    $IX.set_value(...)
```
As the length of the chain expands, combinatorially-more separate rules are required 😞.

**Comment by aryx** [comment]
thx @fasiha, great issue.

**Comment by IagoAbal** [comment]
This is another case for symbolic propagation.

**Comment by IagoAbal** [comment]
@fasiha please try
```
options:
  symbolic_propagation: true
```
and let me know how does it work!

Here is your original example, now working: https://semgrep.dev/s/1znD?version=develop
