### ISSUE TITLE
Make homebrew PRs from returntocorp, not from a personal account

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2862]
Currently, the release process automatically make a PR to update the semgrep package for homebrew. This PR comes from https://github.com/brendongo/homebrew-core rather than https://github.com/returntocorp/homebrew-core. The latter would allow the person in charge of the release to push manual fixes to the PR without Brendon.

Assigning to @brendongo because he knows this best but maybe someone else can do it.

**Comment by mjambon** [comment]
I made this change to our CI job in charge of creating the homebrew-core: https://github.com/returntocorp/semgrep/pull/2861/commits/2b89c60787c818db4fb43ecbcc3323f328898875

I expect this to make the PR from returntocorp/homebrew-core allowing every r2c member to make fixes. I don't know if it works.

**Comment by brendongo** [comment]
@mjambon afaict that change will make the job open a PR TO the returntocorp/homebrew-core not FROM that repo :D

**Comment by mjambon** [comment]
oh I see, from this example:
```
    # Optional, defaults to homebrew/core
    tap: USER/REPO
```
I didn't know what a "tap" was :-(

I had a quick look at both [dawidd6/action-homebrew-bump-formula](https://github.com/dawidd6/action-homebrew-bump-formula/blob/master/main.rb) and [bump-formula-pr.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/dev-cmd/bump-formula-pr.rb) and I can't say I understand what's going on in there.

Maybe ask how to do this at https://github.com/dawidd6/action-homebrew-bump-formula/issues ?

**Comment by brendongo** [comment]
Update: opened an issue on homebrew/brew to see if opening a PR from an org is a feature they would support me adding to brew https://github.com/Homebrew/brew/issues/11143

**Comment by brendongo** [comment]
With https://github.com/returntocorp/semgrep/pull/3003 the PR is made from our org fork of homebrew-core instead of my personal fork so should be editable by the semgrep maintainers.
