### ISSUE TITLE
Add mechanism to get Semgrep progress logs when it runs forever

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#2863]
**Is your feature request related to a problem? Please describe.**
I'd like to get a debug log of Semgrep to inspect when Semgrep crashes or times out. Right now the OCaml core supports logging to a file, but there's no way to tell the Python wrapper to forward the necessary flags to the core to turn on logging.

**Describe the solution you'd like**
Either:
- log by default to some file (e.g. `.semgrep.log`)
- add a flag to turn on logging
- add an environment variable to turn on logging

**Comment by chmccreery** [comment]
@nbrahms I see this has moved around a lot for the past month - is this still high-priority? Is it now being treated as sprint work? Do you want to take it?

**Comment by aryx** [comment]
With #3522 at least we can see debugging logs as we go on stderr, so I think it closes this issue too.

**Comment by aryx** [comment]
just using semgrep --debug should now do the right thing and displays things as semgrep-core goes.
