### ISSUE TITLE
Upgrade junit-xml -> junit-xml-2

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2865]
The issue is that "junit-xml source is not available in PyPI for v1.9". See the original suggestion and patch at: https://github.com/Homebrew/homebrew-core/pull/73902#issuecomment-806632065

**Comment by mschwager** [comment]
We have this dependency for what seems like ~100 lines of boilerplate dict -> XML conversion ([`TestCase`](https://github.com/kyrus/python-junit-xml/blob/master/junit_xml/__init__.py#L364)). It's also seen 1 commit in the last 18 months or so, which isn't particularly reassuring. Another option I'd be supportive of is removing this dependency in favor of a function we write (or mostly copy). Less dependencies, less problems :+1:

**Comment by mschwager** [comment]
cc @dtrodrigues

**Comment by brendongo** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/2895
