### ISSUE TITLE
Invalid SARIF: invocation should be a child of run

### ISSUE THREAD

**Issue by simon-engledew** [semgrep/semgrep#2867]
**Describe the bug**

According to the SARIF spec, `invocation` should be the child of a `run`:

https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10540933

Currently `build_sarif_output` is nesting it at the root of the document, which is producing SARIF which does not conform to the specification:

https://github.com/returntocorp/semgrep/blob/9a73a142dccfa281999418510843886c3d260c71/semgrep/semgrep/output.py#L309

**To Reproduce**

This can been seen by uploading the [test SARIF output](https://github.com/returntocorp/semgrep/blob/9a73a142dccfa281999418510843886c3d260c71/semgrep/tests/e2e/snapshots/test_check/test_sarif_output/results.sarif) to the online [SARIF validator](https://sarifweb.azurewebsites.net/Validation).

![image](https://user-images.githubusercontent.com/14410/113304853-532efe00-92fa-11eb-8c2d-dece6348a31b.png)

**Expected behavior**

Invocation should be moved up a couple of lines into the run section. :+1: :heart:

**What is the priority of the bug to you?**

P2 (regular bug that should get fixed).

**Comment by ievans** [comment]
@underyx want to take a look? seems like an easy fix. @simon-engledew would be happy to accept a PR from you as well if you're up for it!

**Comment by simon-engledew** [comment]
@ievans No problem, done! :+1:

**Comment by underyx** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/2888

Thanks a lot for the contribution @simon-engledew! We try to publish a release every Tuesday, so this might even go live later today 🙃
