### ISSUE TITLE
Request: support import equivalences for JavaScript

### ISSUE THREAD

**Issue by ahmsec** [semgrep/semgrep#2882]
**Is your feature request related to a problem? Please describe.**
The Semgrep docs describe equivalences for imports, however it appears that this feature isn't supported for JavaScript. 
https://semgrep.dev/docs/writing-rules/pattern-syntax/#imports

**Describe the solution you'd like**
Support import equivalences for JavaScript. For example, it would be nice if the pattern `child_process.execSync(...)` would match the following code. 
```
const { execSync } = require('child_process');
let ls = execSync("ls");
```

**Describe alternatives you've considered**
N/A

**Additional context**
Slack discussion: https://r2c-community.slack.com/archives/CK86BJ5DW/p1617312859106300
This issue may potentially be related: https://github.com/returntocorp/semgrep/issues/2846

**Comment by aryx** [comment]
After those PRs, semgrep will handle aliasing of functions imported via require() or import/from.

**Comment by aryx** [comment]
This works now on develop: https://semgrep.dev/s/kLwz/?version=develop
