### ISSUE TITLE
Enforce consistent formatting by using ocamlformat instead of ocp-indent on our OCaml repos.

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2884]
We need to:
* identify the configuration we need (preferably a standard, conservative style with minimal tweaks)
* check that we're getting satisfying results when running ocamlformat on our code
* use it instead of ocp-indent in the pre-commit hook

**Comment by mschwager** [comment]
Can we close this out after https://github.com/returntocorp/semgrep/commit/be6984f4f5cf7ff57998f35eaaebb45445f95c74?

I also don't see any additional `ocp-indent` usage:

```
$ rg --hidden ocp-indent
.ocp-indent
1:# See https://github.com/OCamlPro/ocp-indent/blob/master/.ocp-indent for more

spacegrep/.ocp-indent
1:# See https://github.com/OCamlPro/ocp-indent/blob/master/.ocp-indent for more
```

```
$ rg --hidden ocamlformat
.pre-commit-config.yaml
100:  # Reformat OCaml code (ml, mli) with ocamlformat if ocamlformat is
101:  # present. If ocamlformat is missing, this step will succeed.
103:  # installing opam and ocamlformat.

.github/workflows/lint.yml
18:    # Custom image provides 'ocamlformat', needed to check ocaml code

.git/FETCH_HEAD
51:11294641078ea31c86bbed805bd8bbf80d7f06e1	not-for-merge	branch 'ocamlformat-preview' of github.com:returntocorp/semgrep
52:e1df68f29759f5c29187a0f12b27e3ae25564139	not-for-merge	branch 'ocamlformat-sparse' of github.com:returntocorp/semgrep

scripts/lint-ocaml
10:if $(ocamlformat --version > /dev/null 2>&1); then
11:  ocamlformat --inplace --enable-outside-detected-project "$@"
14:*** ocamlformat was not found. ***
16:If you wish to re-indent OCaml code, you must install ocamlformat, which is
19:  $ opam install ocamlformat

semgrep-core/src/core/ast/Lang.ml
67:[@@ocamlformat "disable"]

semgrep-core/dev/dev.opam
12:  "ocamlformat" {= "0.15.0" }  # used by the pre-commit hook
```

Can we remove the `.ocp-indent` files?

**Comment by mjambon** [comment]
I rely on ocp-indent to indent code when editing. Ocamlformat is now set up to run as pre-commit hook. However, I don't know how to set up ocamlformat during live editing, and I'm not sure I want this either. Ocp-indent really just indents the current line, it doesn't do a full reformatting like ocamlformat.

**Comment by mjambon** [comment]
ocp-indent supports a [global configuration file at `~/.ocp/ocp-indent.conf`](https://www.typerex.org/ocp-indent.html). Maybe I should use that instead.

**Comment by mjambon** [comment]
I'm leaving this issue open because we've only transitioned to ocamlformat for the semgrep repo. Other major r2c repos containing  ocaml source code are pfff and ocaml-tree-sitter. I'm in no rush to add ocamlformat to those due to lack of frustration and motivation...
