### ISSUE TITLE
Finish Parse_ocaml_tree_sitter.ml

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2885]
We'd like to use some of the features of OCaml that have been added over the last 10 years or so, such as [`type id = private int`](https://ocaml.org/manual/privatetypes.html). Currently we're blocked because semgrep doesn't support them and we use semgrep on our own code base, resulting in semgrep errors during CI.

Alternatively we could:
* tolerate semgrep parsing failures
* not run semgrep at all on our OCaml code
* not use any recent OCaml syntax (current situation)

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
Done! (in time for the OCaml workshop 2021).
