### ISSUE TITLE
Typescript parsing error: parameter destructuring function type

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2900]
**Describe the bug**
Function type with parameter destructuring like `({ x }: { x: number }) => number` would cause parsing error.
The semgrep editor example was a simplified version of the code I encountered.

**To Reproduce**
https://semgrep.dev/s/KWy6

**Expected behavior**
No parsing error.

**What is the priority of the bug to you?**
P1

**Comment by mjambon** [comment]
@nbrahms I created the `needs-upgrade` label for those fixes in tree-sitter grammars that need to be propagated to semgrep. This is to indicate that the issue shouldn't be closed.

**Comment by mjambon** [comment]
The fix will be in semgrep 0.56 due this week.
