### ISSUE TITLE
TypeScript parsing error: `export type { SomeThing };`

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2901]
**Describe the bug**
semgrep fail to parse the TypeScript: `export type { SomeThing };`
The reproduce example was copied from https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html.

**To Reproduce**
https://semgrep.dev/s/Yg4Q/

**Expected behavior**
No parsing error.

**What is the priority of the bug to you?**
P1

**Comment by nbrahms** [comment]
Fixed after merge and integration of https://github.com/tree-sitter/tree-sitter-typescript/pull/145

**Comment by mjambon** [comment]
The fix will be in semgrep 0.56 due this week.
