### ISSUE TITLE
Search by partial function name

### ISSUE THREAD

**Issue by zx8** [semgrep/semgrep#2907]
Apologies if this is already possible, I went through the docs and couldn't find an example of how to do this.

I want to be able to search by _partial_ function name for when I'm doing large scale refactoring to e.g. standardise function names across my entire codebase, for example:

```go
func foobar() string {
  return "baz"
}
```

It would be great if I could somehow search for all functions starting with `fo`, containing `oba`, ending with `ar`, etc.

**Comment by underyx** [comment]
I believe [`metavariable-regex`](https://semgrep.dev/docs/writing-rules/rule-syntax/#metavariable-regex) might do what you want! See an example here: https://semgrep.dev/s/okbn/

**Comment by zx8** [comment]
That'll do the trick... Thank you! 🙂
