### ISSUE TITLE
Generic pattern matching on function calls (understanding parenthesis)

### ISSUE THREAD

**Issue by sabrinabrogren** [semgrep/semgrep#2911]
**Describe the bug**
With generic pattern matching, it seems that multiline functions aren't correctly parsed when the arguments to those functions also have parenthesis.

**To Reproduce**
https://semgrep.dev/s/xY9P

**Expected behavior**
The match should include the whole function (highlighting on lines 34-36 should go down to line 38).

**What is the priority of the bug to you?**
P2 (regular bug that should get fixed)

**Comment by aryx** [comment]
I think you reached a core limitation of generic/spacegrep. It works on ispacing/ndentation, it does not really understand the program,
so it does not really understand parenthesis either.

**Comment by mjambon** [comment]
A solution is to use indentation in the pattern:
```
linear-gradient(
  ...
)
```
https://semgrep.dev/s/GW9n/

So you get fewer false positives but you may get false negatives if the code uses a weird indentation. The following matches ok:
```
background: linear-gradient(
  0deg,
  rgba(255, 255, 255, 0.2),
  rgba(255, 255, 255, 0.2)
)
```
but this doesn't match:
```
background: linear-gradient(
  0deg,
  rgba(255, 255, 255, 0.2),
  rgba(255, 255, 255, 0.2)
  )
```
--> https://semgrep.dev/s/R8OK

**Comment by mjambon** [comment]
Adding indentation to the pattern always makes it more specific. That's the best we can do given how spacegrep works.

I'm labeling this as a documentation issue. Task:
* add an example to the cheatsheet demonstrating the use of a indented pattern

**Comment by sabrinabrogren** [comment]
Thanks for taking a look @aryx and @mjambon, that makes a lot of sense. I'll take another shot at making this rule work!

**Comment by mjambon** [comment]
@sabihb I see the error message "A gradient between the same two colors is just a solid color." I suppose you want a pattern like `linear-gradient($ANY, $COLOR, $COLOR)` but this won't work with spacegrep because the metavariables can only capture single words (alphanumeric sequences).

Maybe a workaround is to enumerate the different ways to specify a color:
```
linear-gradient(
  ...,
  $NAME,
  $NAME
)
```
or
```
linear-gradient(
  ...,
  rgba($R, $G, $B, $A),
  rgba($R, $G, $B, $A)
)
```
or
```
linear-gradient(
  ...,
  #$HEX,
  #$HEX
)
```
etc.
