### ISSUE TITLE
Getting semgrep-core in pipenv

### ISSUE THREAD

**Issue by fasiha** [semgrep/semgrep#2929]
## Describe the bug
Forgive me, I'm not sure if this should be a bug issue or a feature request issue, it's more of a request for pointer to documentation—I see [here](https://github.com/returntocorp/semgrep/tree/develop/semgrep#semgrep-cli-development) that
> When installed via pipenv, semgrep-core is not installed. Bring your own semgrep core.

I'm running into this when attempting to build a [conda recipe](https://github.com/conda-forge/staged-recipes/pull/14494#issuecomment-817081522) for semgrep:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-s63hqcyn/setup.py", line 85, in <module>
        src = find_executable(binary_env, binary_name)
      File "/tmp/pip-req-build-s63hqcyn/setup.py", line 73, in find_executable
        raise Exception(
    Exception: Could not find 'semgrep-core' executable, tried 'SEMGREP_CORE_BIN' and system 'semgrep-core'
```
when attempting to build on Linux and macOS, presumably because Conda is building semgrep inside a virtual environment. I'm sure I'm just not looking properly but I couldn't find documentation on how to obtain the semgrep-core binary inside an environment like this.

([Link to Slack thread](https://app.slack.com/client/TKABHD886/CK86BJ5DW/thread/CK86BJ5DW-1617835797.177000) where we've been talking about this.)

## To Reproduce
My [conga-forge PR](https://github.com/conda-forge/staged-recipes/pull/14494#issuecomment-817081522) includes links to the CI logs. I can dig into what the CI is trying to do to get more details if needed.

## Expected behavior
I'm expecting there's some way to make the semgrep-core binary available. Would it be an operating system-level install (apt-get, etc.)? Or is there another PyPI package that I can depend on to make this binary available?

## What is the priority of the bug to you?
We're attempting to integrate semgrep in our JupyterLab workflow, and the first requirement for our build system is getting a conda recipe for semgrep, so we're blocking on that.

## Environment
The conda recipe imports the most recent semgrep release on PyPI, 0.46.0, and its dependencies.

**Comment by mschwager** [comment]
Ahh, yeah I've encountered this before. If you're installing from source you'll need to bring your own `semgrep-core` and `spacegrep` binaries. If they're in a non-standard location you can use `SEMGREP_SKIP_BIN` to proceed with the installation as long as they're available in the `PATH` for `semgrep` to use post-installation. So something like the following:

```
$ SEMGREP_SKIP_BIN=true python -m pipenv install --dev
```

I need to update our docs with this information :+1: 

Although, looking at the Conda PR (https://github.com/conda-forge/staged-recipes/pull/14494), is there a reason you're manually installing from the `.tar.gz` release artifact? That won't provide the `semgrep-core` and `spacegrep` binaries, so you'll either need to [build those manually](https://github.com/returntocorp/semgrep/blob/develop/doc/README.md#semgrep-core-development) or download them in addition to the tarball. The [`.whl` release artifacts](https://pypi.org/project/semgrep/#files) also include the binaries.

This [README](https://github.com/returntocorp/semgrep/blob/develop/semgrep/README.md) is outdated and should be removed in favor of [this one](https://github.com/returntocorp/semgrep/blob/develop/doc/README.md).

**Comment by fasiha** [comment]
> Although, looking at the Conda PR ([conda-forge/staged-recipes#14494](https://github.com/conda-forge/staged-recipes/pull/14494)), is there a reason you're manually installing from the `.tar.gz` release artifact? That won't provide the `semgrep-core` and `spacegrep` binaries, so you'll either need to [build those manually](https://github.com/returntocorp/semgrep/blob/develop/doc/README.md#semgrep-core-development) or download them in addition to the tarball. The [`.whl` release artifacts](https://pypi.org/project/semgrep/#files) also include the binaries.

Thank you @mschwager!! I will look into how to make the conda recipe pull the wheel instead of the tarball, which is how `grayskull` the PyPI→conda recipe generator seems to work.

**Comment by mschwager** [comment]
@fasiha heads up: [this README](https://github.com/returntocorp/semgrep/blob/develop/semgrep/README.md) has been removed in favor of our [docs here](https://github.com/returntocorp/semgrep/blob/develop/doc/README.md). Thanks for catching this!

I'll leave this issue open until https://github.com/conda-forge/staged-recipes/pull/14494 is in just in case there's anything else necessary on our end :+1:

**Comment by fasiha** [comment]
Small question: at [ocaml-tree-sitter/scripts/install-tree-sitter-lib line 64](https://github.com/returntocorp/ocaml-tree-sitter/blob/8f2515c1ccbacff797c8d884379f8219658cc5fd/scripts/install-tree-sitter-lib#L73): `sudo make install` fails both on Linux CI ([log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=304533&view=logs&j=6f142865-96c3-535c-b7ea-873d86b887bd&t=22b0682d-ab9e-55d7-9c79-49f3c3ba4823)) and Windows. Any tips on how you deal with this, at least Linux, where I don't have control over the CI image? (Windows is a manual build right now, I can edit the script 😅.)
