### ISSUE TITLE
Add support for "nosem" comments in generic mode

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2932]
Questions to answer before working on this:
* What kind of annotations are supported when using specific languages with the semgrep-core matching engine?
* What component takes care of identifying and silencing matches containing a nosem annotation?
* Are the same requirements applicable to spacegrep (generic mode)?

What we can do within spacegrep includes:
* Filter out matches based on some condition e.g. do they contain the word "nosem"?
* Take an option to specify the filter e.g. a list of words (or even a proper spacegrep pattern) whose presence invalidates a match.

Keep in mind that spacegrep is a single parser, and has no notion of a comment. The simple solution that's also easy to remember for a semgrep user is "a line containing the word `nosem` will not be matched by semgrep". The consequence of this rule is that a multi-line match containing the word `nosem` anywhere in any of the matched lines will be filtered out. If we try to match the pattern `foo()`, the following matches will be rejected:
```
foo() // nosem
```
```
foo() + bar() <!-- nosem -->
```
```
foo( // nosem
)
```
```
foo(
) // nosem
```
```
nosem(foo())
```
The following would still match:
```
// nosem
foo()
```
```
foo()
// nosem
```
```
foo() +
bar() # nosem
```

Since spacegrep doesn't recognize comments, it is actually easy to break a pattern by inserting a comment, without special support for nosem annotations. For example, the pattern `foo()` will not match the following code:
```
foo(/**/)
```
It won't match this either:
```
foo(//
)
```
Such "match-breaking" comments can already be used to defeat spacegrep.

**Comment by minusworld** [comment]
This may be relevant: https://github.com/returntocorp/semgrep/pull/2574

I believe that `nosem` comments do not work with regex-only rules, though.

**Comment by mschwager** [comment]
I thought, per https://github.com/returntocorp/semgrep/pull/2574, `nosem` does work in generic mode?

Anyway, https://github.com/returntocorp/semgrep/pull/2973, adds support for `pattern-regex` rules.

**Comment by mjambon** [comment]
So yes, nosem is supported in generic mode. I haven't looked into the implementation, which is in the python wrapper.

Here's what works and doesn't work:

![image](https://user-images.githubusercontent.com/343265/115765966-3cf5ea00-a35c-11eb-903b-8df7a3a281d5.png)

https://semgrep.dev/s/plDe

**Comment by mjambon** [comment]
I think this will work in most cases, so I'm making this issue low priority.

At some point, we should improve this and document it, for the generic mode at least. This is why I leave the issue open.

[I just realized `nosem` was deprecated, so I'm now referring to it as `nosemgrep`]

I suggest:
* in generic mode, treat any line containing the word `nosemgrep` or the word `nosemgrep` followed by a colon and a comma-separated list of rule IDs as a valid nosemgrep directive. Why: the string "nosemgrep" won't occur as part of valid code by accident.
* update the [documentation](https://semgrep.dev/docs/ignoring-findings/) to be specific about multiline matches. Something like "if any matched line contains a nosemgrep annotation, then the match will be ignored". It should be noted it can introduce subtle behavior when combining matches with `pattern-not-inside` and other combinators when matches overlap partially and only some of them contain a nosemgrep annotation. Perhaps the documentation should show a warning about potential complex behavior and that's it.

**Comment by mschwager** [comment]
> Here's what works and doesn't work ...

To try and disambiguate `nosem` functionality from random `nosem` strings in code, e.g. `func_nosemblance_of_reality(arg)`, we currently require a space before the keyword. E.g. this example works as expected: https://semgrep.dev/s/2bgr/

It's a bit of a shortcoming, or at least a trade-off, that allows it to support arbitrary languages at the cost of semantic comment meaning.

**Comment by mjambon** [comment]
Requiring a space is not an awful trade-off, but I think we should be able to support `//nosem` (without a space).

Zero-width assertions are supported by python regexps and by libpcre, so we could have a simple regexp that ensures that the string `nosem` is not part of a larger word. The [baked-in shortcut is `\b`](https://www.regular-expressions.info/wordboundaries.html) e.g. `\bnosem\b` but otherwise we could pick which characters delimit words ourselves using using a lookahead or a lookbehind assertion.

**Comment by IagoAbal** [comment]
Any updates on this @mjambon @mschwager ? Still relevant?

**Comment by mjambon** [comment]
It's a nitpick and not a problem for a single user. I think it's fine to close it.
