### ISSUE TITLE
Ruby Interpolated Strings Matching

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#2949]
**Describe the bug**
If you assign a Ruby interpolated string to a variable and attempt to match that assignment, semgrep does not detect a match. 

**To Reproduce**
https://semgrep.dev/s/zkLl/

**Expected behavior**
There are no matches, but I would expect the pattern to match the first line in the target.

**Comment by emjin** [comment]
I think this is a duplicate of https://github.com/returntocorp/semgrep/issues/2826? Not that I've gotten around to it, but I can take a look

**Comment by colleend** [comment]
awesome! and yep, seems like the same issue

**Comment by mschwager** [comment]
Fixed by https://github.com/returntocorp/semgrep/pull/2967
