### ISSUE TITLE
Invalid SARIF file: invocation is missing required property executionSuccessful

### ISSUE THREAD

**Issue by becojo** [semgrep/semgrep#2954]
**Describe the bug**
The SARIF report that semgrep generates is missing the required boolean property `executionSuccessful` on invocation objects. The invocation objects currently only contain the `toolExecutionNotifications` property.

```
      "invocations": [
        {
          "toolExecutionNotifications": []
        }
      ]
```

**To Reproduce**

1. Create an empty SARIF report:
```
semgrep -e '...' -l python --sarif --output report.sarif
```
2. Upload it on https://sarifweb.azurewebsites.net/Validation

3. View the validation errors:

![image](https://user-images.githubusercontent.com/172889/115059230-3ecf3180-9eb4-11eb-8a4f-e43f645800a0.png)

**Expected behavior**
The SARIF report should be valid.

**What is the priority of the bug to you?**
P2

This is preventing semgrep from being used with Github's code scanning:

![image](https://user-images.githubusercontent.com/172889/115059391-7f2eaf80-9eb4-11eb-97ce-2d1653dd1a1b.png)

**Environment**

Mac OS. Semgrep is installed with pip.

```
> semgrep --version
0.47.0
```

**Comment by colleend** [comment]
Thanks for filing this issue! We currently aren't putting much points into supporting SARIF output right now, but it will be on our roadmap Q2. We'll get to this issue then!

**Comment by mschwager** [comment]
Looks like this should be fixed by https://github.com/returntocorp/semgrep/pull/2983. Feel free to re-open if you're still having issues :+1:
