### ISSUE TITLE
Eliminate sudo from the build

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2956]
Various people are annoyed by the need for `sudo` to build semgrep. I know it's used to install libtree-sitter. I don't think it's used for anything else but we need to check.

* [Build for Conda](https://github.com/conda-forge/staged-recipes/pull/14494#issuecomment-820837740)
* [Build for Windows](https://github.com/returntocorp/semgrep/issues/1330)

**Comment by aryx** [comment]
maybe max can help?

**Comment by mschwager** [comment]
Looking at the `sudo` usage, here's the tail end of the `make` command:

```
ar rcs libtree-sitter.a lib/src/tree_cursor.o lib/src/stack.o lib/src/get_changed_ranges.o lib/src/lexer.o lib/src/subtree.o lib/src/language.o lib/src/node.o lib/src/parser.o lib/src/query.o lib/src/tree.o
cc  -shared -Wl,-soname,libtree-sitter.so.0 lib/src/tree_cursor.o lib/src/stack.o lib/src/get_changed_ranges.o lib/src/lexer.o lib/src/subtree.o lib/src/language.o lib/src/node.o lib/src/parser.o lib/src/query.o lib/src/tree.o  -o libtree-sitter.so.0.0
ln -sf libtree-sitter.so.0.0 libtree-sitter.so
ln -sf libtree-sitter.so.0.0 libtree-sitter.so.0
```

And here's `sudo make install`:

```
install -m755 libtree-sitter.a '/usr/local/lib'/libtree-sitter.a
install -m755 libtree-sitter.so.0.0 '/usr/local/lib'/libtree-sitter.so.0.0
ln -sf libtree-sitter.so.0.0 '/usr/local/lib'/libtree-sitter.so.0
ln -sf libtree-sitter.so.0.0 '/usr/local/lib'/libtree-sitter.so
install -d '/usr/local/include'/tree_sitter
install -m644 lib/include/tree_sitter/*.h '/usr/local/include'/tree_sitter/
install -d '/usr/local/lib/pkgconfig'
sed -e 's|@LIBDIR@|/usr/local/lib|;s|@INCLUDEDIR@|/usr/local/include|;s|@VERSION@|0.6.3|' \
    -e 's|=/usr/local|=${prefix}|' \
    -e 's|@PREFIX@|/usr/local|' \
    tree-sitter.pc.in > '/usr/local/lib/pkgconfig'/tree-sitter.pc
```

Naturally this command will need `sudo` because it's performing `install` on root-owned portions of the filesystem. My question is: can we avoid the `make install` altogether? We have the resultant libraries we need (`libtree-sitter.a` and `libtree-sitter.so.0.0`). Can we put these in a constant, user-owned location, and link against that location?

EDIT: above output from https://app.circleci.com/pipelines/github/returntocorp/ocaml-tree-sitter/662/workflows/5500c989-795d-482b-8fca-ed434a960725/jobs/690

**Comment by mjambon** [comment]
@mschwager ocaml-tree-sitter's `configure` script writes the values of `TREESITTER_INCDIR` and `TREESITTER_LIBDIR` environment variables into files `config.sh` (for bash scripts) and `config.mk` (for makefiles). It seems this config is not taken into account by `scripts/install-tree-sitter-lib`, but maybe that's what we should do. Something like this:
```bash
# assumes we're running this from the ocaml-tree-sitter's repo root

config=$(pwd)/config.sh
if [[ -e "$config" ]]; then
  . "$config"
else
  error "Missing file '$config'. Did you forget to run './configure'?
fi
```

**Comment by mjambon** [comment]
.

**Comment by mjambon** [comment]
I think the issue here is that we don't know where to install libraries if we're not allowed to install them as root. Please advise.

**Comment by mjambon** [comment]
This was freshly merged. Let me know if there are build issues. `make setup` is necessary to build the tree-sitter library and put it in the right place.
