### ISSUE TITLE
Semgrep playground seems to show results in the benchmark program

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2979]
**Describe the bug**
Semgrep playground seems to show results in the benchmark program.
In addition, executing the pattern `$ANY` would result in the following error message.
> Could not parse benchmark-target.py as python

**To Reproduce**
https://semgrep.dev/s/rAwJ
https://semgrep.dev/s/yzrA

**Expected behavior**
Only show the results of the test code

**Screenshots**
![Screen Shot 2021-04-21 at 5 30 05 PM](https://user-images.githubusercontent.com/2806164/115638435-4719d900-a2c7-11eb-9d83-5fba260895ea.png)
![Screen Shot 2021-04-21 at 5 32 31 PM](https://user-images.githubusercontent.com/2806164/115638604-952edc80-a2c7-11eb-9b8f-9996b7fe9b0e.png)

**Comment by Isaac0616** [comment]
Actually, the second one seems to be a separated issue, so I filled #2980.

**Comment by colleend** [comment]
Thanks for filing this issue! I've also noticed that the playground has this error, and filed it separately in a private repository. Thanks for catching this and bringing this to our attention 👍 

Replicate of https://github.com/returntocorp/semgrep-app/issues/2326
