### ISSUE TITLE
semgrep fails to parse empty yaml file

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2981]
**Describe the bug**
semgrep will through the parse error if the target yaml file is empty.

**To Reproduce**
Can't not reproduce in the playground.
Can reproduce by `semgrep --verbose --pattern 'test:' --lang yaml empty.yaml`

**Expected behavior**
No error.
It seems that other languages (at least Python) won't throw error for the empty file.

**What is the priority of the bug to you?**
P2

**Environment**
semgrep 0.48.0 on MacOS

**Comment by colleend** [comment]
Thanks for filing this issue! We'll solve this issue as soon as possible, although because it is low priority it may take us some time.
