### ISSUE TITLE
Python parsing error: f-string + multiple colons

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2982]
**Describe the bug**
It is a corner case.
`f"{td:%Y-%m-%d %H:%M}"` cause parsing error at the second colon where `td` is `datetime` object.
(Similar code `"{td:%Y-%m-%d %H:%M}".format(td=td)` won't).

**To Reproduce**
https://semgrep.dev/s/Nr9N

**Expected behavior**
No error.

**Priority** 
P1

**Comment by colleend** [comment]
Thanks for filing this issue! Would you happen to know what priority this bug is for you?

**Comment by Isaac0616** [comment]
It is not super common for us, so probably P1.
