### ISSUE TITLE
Support break/continue in the IL

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2986]
Right now we don't handle correctly code using break or continue in our dataflow analysis. 
We need to extend AST_to_IL.ml to handle those constructs.

Here is a simple break.c file:
```
int foo() {

  int x = 0;
  while(true) {
    x = 1;
    if (x > 2)
      break;
  }
  return x
}
```
If you do semgrep-core -dump_il break.c
you'll see some Todo for this construct:

```
...
[{ s =
                    (FixmeStmt (IL.ToDo,
                       (S
                          { s = (Break ((), LNone, ())); s_id = 5;
                            s_use_cache = false; s_backrefs = None;
                            s_bf = None })
                       ))
                    }
                   ],
                 []))
...
```
Instead we need to convert those constructs in extra labels and Goto (see IL.ml).

**Comment by aryx** [comment]
👋

**Comment by aryx** [comment]
This was actually done @mmcqd right?

**Comment by IagoAbal** [comment]
That's right, PR #3925 closes this.
