### ISSUE TITLE
spacegrep error when parsing a markdown file

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#2987]
**Describe the bug**
spacegrep encounters an error when parsing the markdown file in issue https://github.com/returntocorp/semgrep/issues/2985.

**To Reproduce**
1. ❌  This is the original issue with a reduced pattern for easier debugging. This fails: https://semgrep.dev/s/ljGo/
2. ✅  Removing a big chunk of the markdown file works: https://semgrep.dev/s/YgJd/
3. ❌  Removing each line until it fails, this is the point at which it fails: https://semgrep.dev/s/qrWO/
4. ❌  Removing a big chunk from the top half does not work: https://semgrep.dev/s/6rPK/
5. ✅  Extremely minimal file, only two lines: https://semgrep.dev/s/ok3X/
6. ❌  Minimal version with the "offending" line from (3) above: https://semgrep.dev/s/zkZn/

My hypothesis include:
1.  Might be some kind of timeout behavior, and certain lines take a while to parse.
2. Might be related to backticks, which are in abundance and I haven't seen used extensively in spacegrep documents

**What is the priority of the bug to you?**
P2

**Comment by minusworld** [comment]
Also, I tested this locally on the CLI (version 0.48.0) and it fails for the listed examples

**Comment by YakDriver** [comment]
Our team is anxiously awaiting this! Thanks for your work on it.
