### ISSUE TITLE
Homebrew package: check that we install a compatible version of libtree-sitter

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#2989]
Regarding the use of homebrew's package to install libtree-sitter (runtime library linked against `semgrep-core`), [I wrote](https://github.com/returntocorp/semgrep/pull/2969#issuecomment-825128090):

> This is fine iff this installs the correct version of libtree-sitter, the one that matches what we used to generate the tree-sitter parsers. This is currently `0.19.4`. It might work with past and future bugfix releases (`0.19.x`). It wouldn't work with `0.18`.
>
> The tree-sitter version we need is currently set in [this script](https://github.com/returntocorp/ocaml-tree-sitter/blob/e5bbdda167c9eba5fb60fb71d58120a1ec7bf276/scripts/install-tree-sitter-lib#L7). We could move this version ID to its own file if that helps.

This issue is for following up on the pull request mentioned above, which has already been merged and might work just fine until tree-sitter release `0.20.0`.

**Comment by brendongo** [comment]
Oh good to know. I'll see if we can pin the dependency somehow

**Comment by mjambon** [comment]
If we can't pin a version, we should ask the [tree-sitter project](https://github.com/tree-sitter/tree-sitter) folks what they think we should do.

**Comment by brendongo** [comment]
Going to close for now. Looks like we rely on tree-sitter being a very specific version.
