### ISSUE TITLE
Python import alias

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#2992]
**Describe the bug**
Not sure whether it is a bug, intended behavior, or should be a feature request.
For the pattern `import $X.function`, `$X` will only match one level of modules.
For example, it matches `import x.function` but not `import x.y.function`.
In contrast, for the pattern `$X.function(...)`, `$X` would match multiple level of modules.
For example,
```
from x.y import function
import x.y.function

x.y.function()
function()
``` 
#1771 seems to be a relevant ticket.

**To Reproduce**
https://semgrep.dev/s/yz3A

**Expected behavior**
A way to match any level of modules.

**Comment by colleend** [comment]
Thanks for filing this issue! There has definitely been discussion about "import $X.function" matching cases such as "from x.y import function", and we agree that this makes sense. Another relevant ticket comment is https://github.com/returntocorp/semgrep/issues/975#issuecomment-681014485. This would be a nice feature to have, although it's not currently high priority.
