### ISSUE TITLE
Typescript `export default` classes not matched

### ISSUE THREAD

**Issue by ahmsec** [semgrep/semgrep#2993]
**Describe the bug**
Semgrep fails to match a TypeScript class declaration that's prefixed by `export default`. On the other hand, Semgrep does match if the prefix is just `export`, or if there's no export prefix.

**To Reproduce**
https://semgrep.dev/s/ahmsec:ts_export_default_not_detected

**Expected behavior**
It should be possible to construct a Semgrep rule that matches a TypeScript class declaration that's prefixed by `export default`. 

**Screenshots**
N/A

**What is the priority of the bug to you?**
P2

**Environment**
semgrep.dev

**Comment by mjambon** [comment]
The fix will be in semgrep 0.56 due this week.

For a preview, see https://semgrep.dev/s/ahmsec:ts_export_default_not_detected?version=develop
