### ISSUE TITLE
Doesn't find files when running in docker

### ISSUE THREAD

**Issue by kenptr** [semgrep/semgrep#2994]
**Describe the bug and repro**

Run semgrep with:

`docker run --rm -it --entrypoint sh -v $PWD:/app -w /app returntocorp/semgrep:latest`

Inside the container:

```
/app $ semgrep --config=p/typescript
using config from https://semgrep.dev/p/typescript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 29 rules...
100%|██|29/29
ran 29 rules on 0 files: 0 findings

/app $ ls 
README.md apps libs package.json ...
```

**Expected behavior**

Work the same way when running locally:

```
❯ semgrep --config=p/typescript
using config from https://semgrep.dev/p/typescript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 29 rules...
<many errors>
ran 29 rules on 246 files: 34 findings
2 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

**What is the priority of the bug to you?**
P0  - wanted to use it in Gitlab CI.

**Environment**

- macos, Big Sur 
- Docker Desktop 3.2.2
- `$ docker run --rm -it returntocorp/semgrep:latest --version`    =>  0.48.0

**Comment by mschwager** [comment]
Semgrep does some interesting magic when inside Docker, see also: https://github.com/returntocorp/semgrep/issues/1215.

If you're using a non-standard (i.e. not `/src`) volume location you'll have to set the `SEMGREP_SRC_DIRECTORY` as well. Thanks for the great reproduction steps, I just tested your commands and it works as expected with that environment variable set:

```
$ docker run --rm -it --entrypoint sh -e SEMGREP_SRC_DIRECTORY=/app -v $PWD:/app -w /app returntocorp/semgrep:latest
/app $ semgrep -l python -e '$X == $X' test.py
test.py
2:    print(1 == 1)  # This is a comment
ran 1 rules on 1 files: 1 findings
```

Another option would be leveraging the standard `/src` location, if possible:

```
$ docker run --rm -it --entrypoint sh -v $PWD:/src -w /src returntocorp/semgrep:latest
/src $ semgrep -l python -e '$X == $X' test.py
test.py
2:    print(1 == 1)  # This is a comment
ran 1 rules on 1 files: 1 findings
```

**Comment by kenptr** [comment]
I've tried suggestion, seems like it's the correct way. Although it's not running rules in my case, not sure what can be the problem. `--verbose --debug` doesn't show anything meaningful:

```
/app $ semgrep --config=p/typescript -v --debug --include apps --include libs
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
trying to download from https://semgrep.dev/p/typescript
using config from https://semgrep.dev/p/typescript. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
loaded 1 configs in 0.7708187103271484
running 29 rules from 1 config remote-url_0
including files:
- apps
- libs
running 29 rules...
Running rule typescript.react.security.react-controlled-component-password.react-controlled-component-password...

(and it gets stuck here for many many minutes)
```

Does anyone saw this kind of behavior?

Update: When I run it locally, it works as expected

**Comment by mschwager** [comment]
@kenptr do you happen to have a code file we can reproduce the slow behavior in? Some of our Javascript/Typescript rules have slower performance than we'd like, so you may be hitting a pathological code path. `react-controlled-component-password` seems like a relatively simple rule, so I wouldn't expect performance to be that bad.

> Update: When I run it locally, it works as expected

Docker IO can slow Semgrep down considerably vs. running locally, especially on macOS systems. Is there a reason you're trying to run Semgrep in Docker instead of running locally?

**Comment by mschwager** [comment]
Closing out, feel free to re-open if you notice any additional issues.
