### ISSUE TITLE
[Java] can't parse nested annotations patterns

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#2996]
https://semgrep.dev/s/nqvY

**Comment by aryx** [comment]
At least you can abuse is-inside and write it as: 
https://semgrep.dev/s/E57N/
original slack discussion: https://r2c-community.slack.com/archives/CK86BJ5DW/p1619428973330600

**Comment by nbrahms** [comment]
@aryx Do you have user prioritization for this ticket?

**Comment by aryx** [comment]
there's a workaround for it, so I guess low priority.

**Comment by aschilling** [comment]
The workaround works. Thanks for that. Nevertheless, I support this issue, because as soon as it comes to negation of rules, even in this simple case, one pattern is much easier to negate than a combination of two patterns.

**Comment by aryx** [comment]
so @emjin and @chmccreery you're on this right?
