### ISSUE TITLE
Editor Examples can leak into each other

### ISSUE THREAD

**Issue by leonard84** [semgrep/semgrep#2999]
https://semgrep.dev/s/8n8N

Example `Finding Route in Java Application`, is affected by previous selected examples.
![grafik](https://user-images.githubusercontent.com/1151511/116115887-d4d83880-a6ba-11eb-948a-f4e9349f1dc8.png)

![grafik](https://user-images.githubusercontent.com/1151511/116116111-110b9900-a6bb-11eb-9a30-b9c4707e1c7b.png)

To reproduce select `Semgrep vs grep` and then  `Finding Route in Java Application`, see in `advanced` that `id` and `message` is from the previous example.

**Comment by mschwager** [comment]
Hi there @leonard84,

I'm currently unable to reproduce by visiting "Semgrep vs grep" then "Finding Route in Java Application." Are you still seeing this issue?

**Comment by leonard84** [comment]
It seems to have been fixed in the meantime.

**Comment by ievans** [comment]
I think there is a subtle race condition here that has to do with switching examples before the run result is returned from the server. @DrewDennison I've seen it as well, though it's difficult to reproduce.
