### ISSUE TITLE
[Python] NoTokenLocation exception on matched code

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3007]
https://semgrep.dev/s/ok60

**Comment by aryx** [comment]
to reproduce:
semgrep-core -e '$ANY' -pvar '$ANY' benchmark-target.py

**Comment by IagoAbal** [comment]
These issues were fixed by https://github.com/returntocorp/semgrep/pull/3613. I still get an error with the Playground but I cannot reproduce it locally:
> Could not parse target.py as python

**Comment by emjin** [comment]
Appears fixed.
