### ISSUE TITLE
[JavaScript] Matching variables in loop declaration

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#3010]
have issues with matching variables inside loop declarations
for example if I need to catch for loop with `i = 0` like
```javascript
for (let i = 0; i < 100; i++) {
  console.log(i)
}
```

patterns like this:
```
for ($X = 0;...) {
  ...
}
```

```
for ($X = 0) {
  ...
}
```

```
for (...,$X = 0,...) {
  ...
}
```
do not work
https://semgrep.dev/s/gJB0/

**Comment by aryx** [comment]
This works: https://semgrep.dev/s/Q8RZ/
You can't just use 1 semicolon, because for requires 2. 
Then you need 'let $X = 0' right now. We could do like for regular declaration and also match assignments for those, but it's not the case currently.

**Comment by inkz** [comment]
@aryx got it! thanks :+1:
