### ISSUE TITLE
language:yaml handling of regex matching against quoted/unquoted strings?

### ISSUE THREAD

**Issue by dnwe** [semgrep/semgrep#3014]
**Describe the bug**

👋 Hi, and thanks for all your hard work on semgrep! It's a great tool. I just recently noticed that `language: yaml` support was available and was testing it out. I'm aware the language support via YAML parser is alpha, but thought I'd raise this anyway just to check it's a known issue.

It was not clear how we should write a `language:yaml` rule that can correctly match against a string value regardless of whether or not it has been quoted

**To Reproduce**

For example, I'd expect [no-fractional-cpu-limits.yaml](https://github.com/returntocorp/semgrep-rules/blob/develop/yaml/kubernetes/best-practice/no-fractional-cpu-limits.yaml) to match regardless of whether the cpu value is unquoted, single-quoted or double-quoted.

Interestingly, if all three variants appear then all three are correctly matched by the rule:
https://semgrep.dev/s/3A1K/

However, if only the two quoted variants appear then nothing matches at all:
https://semgrep.dev/s/4yg5/ 

Similarly, unquoted by itself matches correctly:
https://semgrep.dev/s/PpGz/

But quoted by itself does not match:
https://semgrep.dev/s/58n0/

**Expected behavior**

I'd expect the `cpu` value to consistently match regardless of the quoting in the YAML input

**Screenshots**

N/A

**What is the priority of the bug to you?**
P2

**Environment**
semgrep.dev

**Comment by mschwager** [comment]
Hi there @dnwe,

Thanks for the heads up! I think we could improve this rule by using the inline [string matching](https://semgrep.dev/docs/writing-rules/pattern-syntax/#string-matching) syntax. When I use this syntax all your code variants are caught as expected: https://semgrep.dev/s/1ndv/. Would you be interested in submitting a fix to [`no-fractional-cpu-limits`](https://github.com/returntocorp/semgrep-rules/blob/develop/yaml/kubernetes/best-practice/no-fractional-cpu-limits.yaml) in [`semgrep-rules`](https://github.com/returntocorp/semgrep-rules)?
