### ISSUE TITLE
Can source releases on GitHub include all source in submodules?

### ISSUE THREAD

**Issue by fasiha** [semgrep/semgrep#3020]
**Is your feature request related to a problem? Please describe.**

It would be nice if the "Source code" downloads on the GitHub releases page (zip and tar.gz) included all submodules bundled (ocaml-tree-sitter, pfff, all the `tree-sitter-lang`s, etc.). This would make these zip/tarball much more useful to me, since I'd have everything I need to build Semgrep (other than upstream dependencies) in a single file.

**Describe the solution you'd like**

I'd like the zip and tarball to include all the source code that live in git submodules.

**Describe alternatives you've considered**

Right now, I have no choice but to clone the repo and checkout a release tag and run `git submodule --init` to get the complete sources.

**Additional context**

Package managers like Conda prefer single tarballs with checksums rather than Git repos, for security and stability reasons.

Some enterprise networks also block cloning from GitHub while allowing downloading of released zip/tarballs.

Thanks for considering 🤝! Sorry if this was already an issue 🙇, I searched but didn't see anything directly related to this.

**Comment by aryx** [comment]
@mjambon is working on refactoring things related to submodule. Maybe this can help.

**Comment by mjambon** [comment]
From looking into [release.yml](https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml), we're not doing anything special to make a clean source release. Maybe @brendongo or @mschwager can confirm.

If so, we could definitely build a tarball containing all the in-house sources. We might have to consolidate the current steps that fetch the sources into a single script (`git submodule update ...` + custom script used to install the ocaml-tree-sitter runtime + maybe the sources of libtree-sitter in the correct version).

**Comment by mschwager** [comment]
> Maybe @brendongo or @mschwager can confirm.

Yup, it seems reasonable to me to make a full source release available :+1: 

I'm not familiar with everything involved in the OCaml build process, so I'd defer to others on that.

**Comment by mjambon** [comment]
Great. I don't mind doing it at some point. Not sure when. My queue of incoming tasks is full.

**Comment by mjambon** [comment]
.
