### ISSUE TITLE
Upgrade to lsp 1.5 or any version compatible with ocaml 4.12

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3026]
This blocks the upgrade to ocaml 4.12. See [details](https://github.com/returntocorp/ocaml-layer/pull/5#issuecomment-830492540).

**Comment by mjambon** [comment]
btw lsp 1.6.0 was released yesterday. We might as well upgrade to that. See https://github.com/ocaml/ocaml-lsp/tags

**Comment by aryx** [comment]
I think I'll remove the dependency to lsp for now. It's not really used.
We can restore it later and update to 1.6.0 if we really need it.

**Comment by aryx** [comment]
Hmm, I can update to lsp 1.3.0, seems to allow ocaml 4.12.0
(updating to 1.6.0 leads to compilation error I don't want to fix now).

**Comment by mjambon** [comment]
I think you could ask the ocaml-lsp folks to respect semver and increment the major version number whenever they break backward compatibility.

**Comment by aryx** [comment]
We could, but I think the lsp-client has a very low priority for them; most of the LSP protocol is supported by the lsp-server, but the lsp-client supports only a few LSP calls; Their priority is not helping people like me abuse LSP but instead improving the OCaml lsp-server.
