### ISSUE TITLE
typescript: `import ... from "lodash"` doesn't parse as a pattern

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#3030]
See here: https://semgrep.dev/s/1nlv

I expected to be able to match both `import { sortBy } from "lodash";` and `import _ from "lodash";` by placing a `...` that could match either the simple variable name, or the destructuring expression with the braces. Instead, I get a parse error.

The logical alternative of `import $NAME from "lodash"` doesn't match the variant with curly braces which is understandable, but annoying that I have to write out two patterns.

**Comment by mjambon** [comment]
A single-pattern solution is to use empty braces:
```typescript
import {} from "lodash";
```
https://semgrep.dev/s/z9Yd/

Not sure how to make this obvious or if there's a place in the documentation for this.
