### ISSUE TITLE
Provide an option to not create a file when zero output

### ISSUE THREAD

**Issue by anantshri** [semgrep/semgrep#3034]
Running semgrep cli with `-o` option creates a file irrespective of output length. 
Ideally a file should be created if some output is present. I understand this might be default behaviour. I would suggest adding a specific switch `-no-blank-file` in to cover a scenario for zero length files.

This is especially useful for cases where semgrep runs in batch mode or via automation.

**Comment by mschwager** [comment]
Hi there @anantshri,

Thanks for creating this issue. Would a workaround like the following work for you?

```
$ python -m semgrep -e '$X == $X' -l python -o out.txt /tmp/test.py
ran 1 rules on 1 files: 0 findings
$ [ -s out.txt ] || rm out.txt
```

This will only delete `out.txt` if it's empty.

I have two concerns with adding another output flag: 1) we already have a dozen or so flags which affect Semgrep's output, and this seems like a very niche use-case, so I'd like to avoid the continued proliferation of minor output tweaks, especially if there's a simple workaround, and 2) an empty file does communicate some information: that there were no findings. If we don't write an empty file then it's not so clear whether outputting failed, there were no findings, etc.

What do you think?
