### ISSUE TITLE
unknown option -lang while downloading rules

### ISSUE THREAD

**Issue by Silur** [semgrep/semgrep#3039]
System: `Linux 5.11.10-arch1-1 #1 SMP PREEMPT Fri, 26 Mar 2021 00:11:29 +0000 x86_64 GNU/Linux`
Semgrep: 0.49.0 (pip)

installed freshly as per the [official docs](https://semgrep.dev/docs/getting-started/) with:

```bash
# For macOS
$ brew install semgrep

# For Ubuntu/WSL/Linux/macOS
$ python3 -m pip install semgrep

# To try Semgrep without installation run via Docker
$ docker run --rm -v "${PWD}:/src" returntocorp/semgrep --help
```
First problem with this is that running `semgrep` after installing with `python -m pip` as a regular user, the binary won't have write permission to __/usr/lib/python3.9/site-packages/semgrep/bin/semgrep-core__. Either fix the doc and explicitly ask for root permission, or install _semgrep-core_ rules into the user local directory.

## Main issue
After fixing permissions for rule, downloading, running `semgrep --config=p/ci $(pwd)` in a source dir results with the following:
```bash
sing config from https://semgrep.dev/p/security-audit. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 245 rules...
 34%|█████████████████████████████████████████████████████████▌                                                                                                                |83/245
semgrep-core exit code: 127
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---

--- end semgrep-core stdout ---
--- semgrep-core stderr ---
unknown option -lang
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
```

**Again, `which semgrep` returns only one binary, which is indeed 0.49.0 !!**
Besides it assuming a wrong version (I have checked both user and system-wide pip for duplicate versions, and also pacman), the _"unknown option -lang"_ is the main cause of the crash.

**Comment by mschwager** [comment]
> First problem with this is that running semgrep after installing with python -m pip as a regular user, the binary won't have write permission to /usr/lib/python3.9/site-packages/semgrep/bin/semgrep-core. Either fix the doc and explicitly ask for root permission, or install semgrep-core rules into the user local directory.

This depends on how you use `pip` in your environment. `pip install` provides the `--user` flag for exactly this use-case. Then, if you include `~/.local/bin/` in your `$PATH`, you will be able to run `semgrep` without root permissions. On the other hand, you can always use `sudo pip install` if you don't mind using root permissions. Rather than assume a particular `pip` workflow we provide the most general installation instructions, and let the user decide on specifics based on their environment.

> ... the "unknown option -lang" is the main cause of the crash.

Hmm, that's an interesting error I haven't seen before. I wonder if our `semgrep-core` and `spacegrep` binaries are getting mixed up. `spacegrep` doesn't have the `-lang` flag, but I'd expect a different error message:

```
$ ./semgrep/semgrep/bin/spacegrep -lang test
spacegrep: unknown option `-l'.
Usage: spacegrep [OPTION]... [PATTERN] [FILE]
Try `spacegrep --help' for more information.
```

It's weird that `semgrep` made it through `34%` of the rules before hitting `unknown option -lang` - I would expect that at the very beginning. Based on the `pip` issues at the beginning, I suspect this may be a faulty installation.

If you re-install `semgrep` with the following, do you still see the same issue?

```
$ sudo pip install --force-reinstall semgrep  # Or use --user if you'd like
```

cc @aryx or @mjambon on how we may get `unknown option -lang` from `semgrep-core`.

**Comment by mjambon** [comment]
@mschwager I don't see how we can get the message `unknown option` out of `semgrep-core`, `spacegrep`, `python3`, or `semgrep` itself. I'm glad we're printing the exit code, and the contents of stdout and stderr in case of an error, but we should also print the command that was executed. Without it, it's hard to guess. That's something for us to fix.

@Silur the fact that it's happening in the middle of a run is interesting. I can only suggest you use strace to print the calls to exec* from semgrep. Something like this:

```
$ strace -f -e trace=/exec semgrep --lang py -e x setup.py
execve("/home/martin/.local/share/virtualenvs/semgrep-JT-h3F_l/bin/semgrep", ["semgrep", "--lang", "py", "-e", "x", "setup.py"], 0x7ffff6a4f810 /* 61 vars */) = 0
strace: Process 217454 attached
[pid 217454] execve("/bin/sh", ["/bin/sh", "-c", "uname -p 2> /dev/null"], 0x7ffe4535c918 /* 61 vars */) = 0
strace: Process 217455 attached
[pid 217455] execve("/usr/bin/uname", ["uname", "-p"], 0x55a02d230fc8 /* 61 vars */) = 0
[pid 217455] +++ exited with 0 +++
[pid 217454] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=217455, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid 217454] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=217454, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
strace: Process 217456 attached
[pid 217456] execve("/home/martin/semgrep/semgrep/semgrep/bin/semgrep-core", ["/home/martin/semgrep/semgrep/sem"..., "-lang", "py", "-json", "-rules_file", "/tmp/tmpvovj7ulp", "-j", "4", "-target_file", "/tmp/tmphfap3wpj", "-use_parsing_cache", "/tmp/tmpd2nfib2_", "-timeout", "30", "-max_memory", "0"], 0x7ffe4535c918 /* 61 vars */) = 0
strace: Process 217457 attached
[pid 217457] +++ exited with 0 +++
[pid 217456] --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=217457, si_uid=1000, si_status=0, si_utime=0, si_stime=0} ---
[pid 217456] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=217456, si_uid=1000, si_status=0, si_utime=10, si_stime=1} ---
ran 1 rules on 1 files: 0 findings
+++ exited with 0 +++
```

This should tell us what command was execed before the crash.

**Comment by aryx** [comment]
Note that when you pass the -debug flag to semgrep-core (or set SEMGREP_CORE_DEBUG=1), semgrep-core will display how it was called.

**Comment by Silur** [comment]
Using `strace` (neither `--debug` nor the env var seemed to work? I see that something injects the `-lang` param. Note that I'm actually trying to run a scan on a golang repository now (but I don't specify the language).
```
$ strace -f -e trace=/exec python -m semgrep --config=p/ci $(pwd) --debug
[ ... omitted ... ]
execve("/usr/lib/python3.9/site-packages/semgrep/bin/semgrep-core", ["/usr/lib/python3.9/site-packages"..., "-lang", "go", "-json", "-rules_file", "/tmp/tmp205uooc7", "-j", "8", "-target_file", "/tmp/tmp21ayqkww", "-use_parsing_cache", "/tmp/tmpu1p76u4m", "-timeout", "30", "-max_memory", "0"], 0x7ffeda1293c0 /* 79 vars */) = 0

**Comment by Silur** [comment]
Just tried the same with a toplevel `semgrep` (without `python -m ...`), which results in the same call structure for `semgrep-core`
