### ISSUE TITLE
[segfault issue] Automatically create a tarball to reproduce a semgrep-core crash (was: print the semgrep-core command)

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3044]
When semgrep-core terminates abnormally, we should print the command with instructions on how to reproduce. This includes:
1. Keep the input files around (in particular, keep temporary files)
2. Print the semgrep-core (or spacegrep) command line.
3. Print environment variables relevant to semgrep or semgrep-core.

Recent issues #3039 and #3043 highlight this need.

Since semgrep passes input files to semgrep-core in smaller batches, running semgrep-core on just one batch should be much faster than the original semgrep job and should help narrow down the problem.

**Comment by mjambon** [comment]
This is half-done by https://github.com/returntocorp/semgrep/pull/3057 which now prints the semgrep-core command and the rule name. Passing `--verbose` to `semgrep` now also shows the verbose log from semgrep-core, which should be useful for troubleshooting.

The logged semgrep-core command by itself is of limited value because the semgrep-core command relies on temporary files which are deleted upon exit. This deletion is a rather nice property, implemented in python with a context manager, and I don't think we should fight it.

A more promising direction to help reproduce the problem may be to make a copy of the input files and create a `repro.tar.gz` bundle if a semgrep-core job fails. It looks like we do something similar in [`test.py`](https://github.com/returntocorp/semgrep/blob/f493c0f30e6bcd84bc8eaa8eab62948b0ce90fd9/semgrep/semgrep/test.py#L391-L401). Here's what a semgrep-core command looks like:
```
/home/martin/semgrep/semgrep-core/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmpbl17clhz -j 4 -target_file /tmp/tmp2ju3g8nu -use_parsing_cache /tmp/tmp0jlfy01f -timeout 30 -max_memory 0
```
So we should probably make a copy of the rules file and of the target file. We'd omit the parsing cache because it's a folder than contains many files, which are big, will be regenerated, and have a lower chance of being problematic than the other input files.

**Comment by brendongo** [comment]
External ask: https://r2c-community.slack.com/archives/CK86BJ5DW/p1622147935097300

**Comment by aryx** [comment]
people end up doing binary search on their repo to find which file is causing some errors ... Not good.
Why --debug does not output the file being processed?

**Comment by aryx** [comment]
The slack link above has great context on what we should do.

**Comment by emjin** [comment]
Planned

**Comment by emjin** [comment]
Now that we can reproduce scans locally, this seems resolved
