### ISSUE TITLE
RFC: deprecate and remove user-defined 'equivalences' functionality

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3049]
https://semgrep.dev/docs/experiments/overview/#equivalences

This functionality has went mostly unused for a year+. In order to reduce our maintenance burden let's deprecate and remove it. We'll always have the git history if we'd like to revive it at a later date.

**Comment by underyx** [comment]
I think this would’ve solved many people’s complaints about how they have to copy-paste variants of the same patterns when writing rules, I’d probably have recommended its use if I knew I about the feature

**Comment by mschwager** [comment]
Some additional context:

> It is a nice feature. I wonder if we can provide approximately the same functionality for users through builtin equivalences and taint? Most of the user-defined equivalences I see in rules are just describing a list of sources and sinks. Of course there are a few that aren't, like dict.get and dict[...], but I think the vast majority are. I think with some user input on how they'd like to describe this type of functionality we could revive it at a later date. The spirit of the functionality is definitely right, I wonder if the ergonomics are a bit off?

> I thought user-defined equivalence would be useful for matching over artihmetic expressions where you can write the same thing in many different ways because of the communtatitivity and associactivity of those operators, but nobody write rules for that :slightly_smiling_face: there's no security bugs in arithmetic expressions.

> Integer overflow! But we don't have many people writing C rules yet :)

> I think this would’ve solved many people’s complaints about how they have to copy-paste variants of the same patterns when writing rules, I’d probably have recommended its use if I knew I about the feature

> Yeah I think the spirit of the functionality is right, but the ergonomics may be a bit off. That and we have quite a few bugs: https://github.com/returntocorp/semgrep/issues?q=is%3Aissue+is%3Aopen+label%3Apattern%3Aequivalence. Really we can only support so much experimental functionality at a time, and after a certain point we should either promote things to more official support, or remove them

**Comment by aryx** [comment]
subscribe

**Comment by mschwager** [comment]
To start, I'm thinking of adding some kind of [`DeprecationWarning`](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) when we detect `equivalences` use. We could then warn about the deprecation for 2-4 releases, link to this issue in the message, give users some time to voice their concerns, then remove the functionality from the Python interface if there are minimal objections.

**Comment by aryx** [comment]
sounds good to me.

**Comment by dlukeomalley** [comment]
This feature has been deprecated 🙏
