### ISSUE TITLE
Fix dependencies for comby for upgrading to ocaml 4.12

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3062]
This is for [upgrading semgrep to use ocaml 4.12](https://github.com/returntocorp/semgrep/issues/3027).

The docker build for the opam packages used by semgrep fails with the [following error](https://app.circleci.com/pipelines/github/returntocorp/ocaml-layer/59/workflows/85aa26db-2967-4606-9a65-27ecbd8b47f9/jobs/39):
![image](https://user-images.githubusercontent.com/343265/117510595-34e3a000-af41-11eb-97fc-e9b5a5579fe4.png)

**Comment by aryx** [comment]
The main issue is that pfff is using ppxlib 0.15.0 and it does not work with ocaml 4.12, so I need
to update to ppxlib 0.20.0
