### ISSUE TITLE
Detect Missing Good Controls/Best Practices

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#3064]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to detect missing best practices.

**Describe the solution you'd like**
A feature request or please enlighten me if this already exists.

Can we have certain patterns that semgrep look for matches in all of the given files. if the pattern is not found in any of the files, semgrep should trigger an alert. This is useful to detect lack of explicit best practices.
Example: In case of android, There are best practices like enable certificate pinning/transparency, detecting root etc. I want semgrep to scan my code base and alert me if the best practices pattern is not found anywhere.

**Additional context**
njsscan currently do this by negating and removing the detection results from semgrep
https://github.com/ajinabraham/njsscan/blob/a5feb3b3dbe03436e246f0160aac7bf1a40276ee/njsscan/njsscan.py#L49

Native semgrep support for this will be helpful for common users.

**Comment by Strajk** [comment]
This would be great to re-open 🙏 found a few similar related discussions:

https://github.com/returntocorp/semgrep/issues/2438
https://semgrep.slack.com/archives/C018NJRRCJ0/p1679908257170229
https://semgrep.slack.com/archives/C018NJRRCJ0/p1671208230318809
https://semgrep.slack.com/archives/C018NJRRCJ0/p1651158551630879
https://semgrep.slack.com/archives/C018NJRRCJ0/p1620501053106300
