### ISSUE TITLE
A false negative of SQL injection which seems can be simply fixed

### ISSUE THREAD

**Issue by enochii** [semgrep/semgrep#3065]
**Describe the bug**
A false negative of SQL injection in a golang web example. It seems that it can be simply fixed.

**To Reproduce**
Here is the link to reproduce: [link](https://semgrep.dev/s/enochii:false-negative-of-sql-injection)

**Expected behavior**
To my knowledge, the sql query marked in the screenshot below should be reported as a potential vulnerability.

![image](https://user-images.githubusercontent.com/33364190/117658518-683a5f00-b1cd-11eb-96ef-337d0f5cc001.png)

It seems that it can be simply fixed by adding one line here:

https://github.com/returntocorp/semgrep/blob/9a73a142dccfa281999418510843886c3d260c71/perf/bench/r2c-rules/golang.yml#L30

added line:
```yaml
    - pattern: $OBJ.Exec("..." + ...) # added line
```

as showed [here](https://semgrep.dev/s/enochii:false-negative-of-sql-injection):

![image](https://user-images.githubusercontent.com/33364190/117659518-9ff5d680-b1ce-11eb-9fbc-50ec8df921cd.png)

By adding the new line, the sql injection is now detected:

![image](https://user-images.githubusercontent.com/33364190/117659851-07138b00-b1cf-11eb-9806-fc6090bab17e.png)

By the way, semgrep is really a excellent tool! I'm new to semgrep and don't know whether this change will bring any false positive. A possible false positive can be like below, though it seems not make much sense. Also we can add rule to exclude it?

```go
db.Exec("INSERT INTO users(username, password) VALUES(" + "USER_NAME, PASSWORD")
```

Hope it helps in some way~

**What is the priority of the bug to you?**

P2(regular bug that should get fixed)

**Environment**
using semgrep.dev.

**Comment by emjin** [comment]
Thanks for reporting this issue in such detail! For organizational purposes, I copied this to semgrep-rules, and I'll close the issue here. You can follow along https://github.com/returntocorp/semgrep-rules/issues/1277
