### ISSUE TITLE
Python 'except ...' misses 'except $EXC as $EX'

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3066]
I would expect `except ...` to match something like `except CustomException as ex`: https://semgrep.dev/s/ZeG7/

Vs https://semgrep.dev/s/nqyG/

**Comment by mschwager** [comment]
Looks like the same for bare `except`: https://semgrep.dev/s/70wv/

**Comment by chmccreery** [comment]
🎉 thanks for reserving for us @emjin!
