### ISSUE TITLE
Multiline auto-fix indentation is wrong

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#3070]
**Describe the bug**
If a user inputs an autofix that is multiple lines, all lines after the first are indented on an absolute basis rather than relative to the first line. 

**To Reproduce**
`semgrep --config https://semgrep.dev/s/chmccreery:autofix-multiline --autofix --disable-nosem --skip-unknown-extensions --dryrun`

^ Run the above command in /semgrep repository (or create a test repo and copy-paste the test code from https://semgrep.dev/s/chmccreery:autofix-multiline

**Expected behavior**
If an autofix is multiple lines long, and are left-aligned with respect to one another, I expect them to be inserted into the code still left-aligned. This likely means replacing all \n characters in the fix with however many spaces came before the first line. 

**Screenshots**

<img width="1111" alt="Screen Shot 2021-05-10 at 2 58 06 PM" src="https://user-images.githubusercontent.com/25408780/117729746-221ad680-b1a0-11eb-9a8f-284c91a35c66.png">

**What is the priority of the bug to you?**
P1

**Environment**
semgrep version 0.50.1 (note that autofix in the playground is completely independent from autofix in semgrep). This ticket is specifically to fix the CLI autofix behavior.

**Comment by mschwager** [comment]
[`textwrap.dedent`](https://docs.python.org/3/library/textwrap.html#textwrap.dedent) might help here.

**Comment by chmccreery** [comment]
Cool, I didn't know about that function! I actually think we might want `textwrap.indent` but same idea 😄

**Comment by aryx** [comment]
In the long term, I think people should run their autoformating tool (prettier, gofmt, rustfmt, etc.) on the autofixed code.
We can definitely try to indent a bit better for some easy cases, but it might be complicated to handle correctly for all posible autofixing.

**Comment by chmccreery** [comment]
@aryx that is a good point - I was mostly thinking about python, where indentation can influence the logic of the code. Are any other languages like that? Maybe this is python-specific 🤔 

My expectation (for python) would be that the indentation of the autofix is all done relative to the first line of the autofix, and that the absolute indentation of the first fixed line matches the absolute indentation of the first replaced line.

**Comment by aryx** [comment]
Scala and haskell are indentation sensitive too

**Comment by ievans** [comment]
@chmccreery is this still a bug? I can't reproduce with:

`semgrep --config https://semgrep.dev/s/semgrep-examples:autofix --autofix --disable-nosem --skip-unknown-extensions --dryrun` on semgrep itself anymore.

**Comment by chmccreery** [comment]
Yes, still a bug.

Unfortunately it looks like named snippets are broken right now... but if you use https://semgrep.dev/s/ByGx you should be able to see this bug still.

**Comment by gordonwoodhull** [comment]
I've been working around this with an outside awk script, but it became a bottleneck, so I tried the same strategy in `autofix.py`.

Turns out a two-line fix here

https://github.com/returntocorp/semgrep/blob/edc97505c6e999e675ad171eeee1c690ab2e7a99/semgrep/semgrep/autofix.py#L79-L82

will do it. Too hacky?

```python
   indent = re.match('\\s*', lines[start_line]).group()
   fix = fix.replace('\n', '\n' + indent)
 ```

**Comment by brendongo** [comment]
@gordonwoodhull seems fine :D if you open a PR with this change + inline comment on what it's for + a test we will appreciate it!
