### ISSUE TITLE
Enspeeden Gitlab eslint.direct-object-detection

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3077]
This rule is 10x slower than all the other rules from Gitlab. Let's make it fast so that Gitlab users have a better experience:

https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/blob/main/rules/eslint.yml#L751

"Faster" in this case might mean that it runs in under 10 seconds on a modern Mac on returntocorp/semgrep-app.

**Comment by brendongo** [comment]
Other numbers that might be relevant:
- Running above rule on our private semgrep-app repo takes 8 minutes without optimizations
- running above rule on same repo with optimizations takes 35 seconds
- For context running the other 92 rules in that rules repo takes 70 seconds without opttimizations

**Comment by mschwager** [comment]
I wonder if we could speed this up with something like:

```yaml
  patterns:
    - pattern: $O[$ARG]
    - pattern-not: $O["..."]
    - pattern-not-inside: |
        $ARG = [$V];
        ...
        $O[$ARG]
    - pattern-not-inside: |
        $ARG = $V;
        ...
        $O[$ARG]
```

I think tightening the bounds on the `pattern-not-inside`s should speed things up. In my quick testing on `semgrep-app` the before/after is:

```
real	5m45.649s
user	6m58.732s
sys	0m5.394s
```

```
real	0m14.273s
user	0m27.280s
sys	0m3.010s
```

Looks like a 15x speedup?

**Comment by mschwager** [comment]
Since `pattern-inside` and `pattern-not-inside` are inclusive the results should be the same.

**Comment by brendongo** [comment]
Nathan didn't update the issue: he made a PR https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/merge_requests/33/diffs

**Comment by aryx** [comment]
What does enspeeden mean?

**Comment by mschwager** [comment]
With the deep expression improvements from https://github.com/returntocorp/semgrep/pull/3083 we still see a ~15x speedup:

```yaml
patterns:
  - pattern: $O[$ARG]
  - pattern-not: $O["..."]
  - pattern-not-inside: |
      $ARG = [$V];
      ...
      <... $O[$ARG] ...>
  - pattern-not-inside: |
      $ARG = $V;
      ...
      <... $O[$ARG] ...>
  - metavariable-regex:
      metavariable: "$V"
      regex: "[0-9]+"
      metavariable: "$ARG"
      regex: "[^0-9]+"
```

```
real	0m15.490s
user	0m32.243s
sys	0m2.968s
```

**Comment by aryx** [comment]
yes but note that the semantic of the deep expression operator in a statement position might not be what you expect; it will just match deeply in expression statements, e.g. foo(stuff);.
It will not match code where $O[ARG] is inside a return, or the condition of an if, or a throw.

**Comment by aryx** [comment]
We could extend the engine to do something special when the deep expression operator is used like that, in which case
we could also run it inside a return, or throw, or just on the conditional part of an if/while/etc.

**Comment by aryx** [comment]
(I'm waiting for develop to use our latest fix so I can show you examples in the playground)

**Comment by aryx** [comment]
See https://semgrep.dev/s/plg3/?version=develop
(it actually works for the return, because we already do a special thing in Generic_vs_generic, but does not work for
throw or if or other).

**Comment by mschwager** [comment]
> yes but note that the semantic of the deep expression operator in a statement position might not be what you expect; it will just match deeply in expression statements, e.g. foo(stuff);.
> It will not match code where $O[ARG] is inside a return, or the condition of an if, or a throw.

I think this is fine for now. Gitlab is saying this rule is already better than its `eslint` equivalent, so I think we're fine on the accuracy front. The bigger concern is speed, and these deep expression improvements have given us a nice 15x speedup.

FYI here's the code they're testing against:

```javascript
function foo(someVar, obj)
  two = 2
  three = [3]
  six = {s: 6}
  string = "key"
  someObjVar = {s: someVar}
  someArrVar = [someVar]

  // Negatives
  value = obj.whyNot
  value = obj['1']
  value = obj[two]
  value = obj[three[0]]
  value = obj[six.s]
  value = obj[six['s']]
  value = obj[string]
  value = obj[7]

  // Positives
  value = obj[someVar]
  value = obj[someObjVar.s]
  value = obj[someObjVar['s']]
  value = obj[someArrVar[0]]
}
```

And their initial tests: https://gitlab.com/gitlab-org/gitlab/-/issues/322193#note_529810615

Since our constant propagation improvements we've also removed the `False Positive: value = obj[string]` FP :tada:

**Comment by nbrahms** [comment]
Please see the updated MR on Gitlab's side. @emjin and I managed to find this pattern instead:

```
    patterns:
      - pattern: $O[$ARG]
      - pattern-not: $O["..."]
      - pattern-not: "$O[($ARG: float)]"
```

However, note that typing information is not extracted from propagated metavariables; @emjin will work on that now.

**Comment by mschwager** [comment]
> However, note that typing information is not extracted from propagated metavariables

Looks like this is also the case for `$O["..."]`. Using your rule vs. the one above also reintroduces the FP `value = obj[string]`.

cc @emjin can we also add constant propagation for constant string object references like `$O["..."]`?

**Comment by nbrahms** [comment]
> What does enspeeden mean?

Make more fast :)

**Comment by nbrahms** [comment]
> > However, note that typing information is not extracted from propagated metavariables
> 
> Looks like this is also the case for `$O["..."]`. Using your rule vs. the one above also reintroduces the FP `value = obj[string]`.
> 
> cc @emjin can we also add constant propagation for constant string object references like `$O["..."]`?

Might be a q for @IagoAbal

**Comment by IagoAbal** [comment]
> can we also add constant propagation for constant string object references like $O["..."]?

This should be fixed now.

**Comment by mschwager** [comment]
Closing this out as Gitlab accepted our improved `eslint.detect-object-injection` rule recommendation that used bounded `pattern-not-inside`'s: https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/blob/main/rules/eslint.yml.
