### ISSUE TITLE
[javascript] Deep expressions don't work in expression statement position

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3078]
**Describe the bug**
https://semgrep.dev/s/DJL2/

**Expected behavior**
Matches code

**What is the priority of the bug to you?**
P0 affects speed of Gitlab eslint.detect-object-injection

**Comment by mschwager** [comment]
I had a similar thought here: https://github.com/returntocorp/semgrep/issues/1804

The key insight was:

> I'm guessing the issue is that <... thing ...> can only match an expression, not a statement.

Supporting this may fundamentally change how the deep expression operator works. I'm not entirely sure if that's a problem or not. Perhaps we could key off of the `;` to determine if it's an expression or statement, but then again, `;` are optional in JS :man_shrugging:

**Comment by IagoAbal** [comment]
Parse error on `<... $O[$ARG] ...>`:
> Parse_mini_rule.InvalidPatternException("no-id", "<... $O[$ARG] ...>\n", "js", "Parsing.Parse_error")

**Comment by mschwager** [comment]
I think is more related to how the deep expression operator fundamentally works than a object reference issue, i.e. https://semgrep.dev/s/WgPy/

**Comment by IagoAbal** [comment]
The parser error at least may be fixable in Pfff, since we use Pfff to parse JS/TS patterns. It seems that it doesn't accept deep expressions in the same places as other parsers (like Python's) do accept them.

**Comment by aryx** [comment]
Note that this is just a parsing fix. It just allows <... whatever ...>; in an statement position (actually an expression statement position).

**Comment by aryx** [comment]
this <... whatever ...>; will not match if whatever is in an if/while conditional, or part of a return statement.

**Comment by IagoAbal** [comment]
@aryx I'm not sure if I understood you correctly but after this fix I get this:
```
$ cat a.sgrep 
$ARG = [$V];
...
<... $O[$ARG] ...>;
$ cat a.js
function foo() {
    //ERROR: match
    a = [2];
    b = 1;
    return foo(b[a]);
}
$ bin/semgrep-core -lang js -f a.sgrep a.js
a.js:3
     a = [2];
     b = 1;
     return foo(b[a]);
```
It seems to work inside a `return` and also tried successfully inside a `while` loop.

**Comment by aryx** [comment]
yep, but not for throw or if. I commented here: https://github.com/returntocorp/semgrep/issues/3077#issuecomment-839815402
