### ISSUE TITLE
[typescript] element-reference expression matches array type

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3087]
**Describe the bug**
Element-reference expression patterns match array types.

**To Reproduce**
https://semgrep.dev/s/wxrx/?version=develop

**Expected behavior**
Expressions should not match types.

**Comment by mjambon** [comment]
This got fixed with the typescript parser upgrade. Compare https://semgrep.dev/s/wxrx/?version=develop with https://semgrep.dev/s/wxrx/?version=0.55.1 (unwanted match on type in `tc8`).
