### ISSUE TITLE
False positive errors reported for some files

### ISSUE THREAD

**Issue by alinbalutoiu** [semgrep/semgrep#3096]
**Describe the bug**
The tests for one of our semgrep rules report false positive errors on some files.

**To Reproduce**
The rules and test code can be found here: https://semgrep.dev/s/58l6

Test with `semgrep` versions `v0.41.0` (and above).

**Expected behavior**
Expecting semgrep to not report a false positive.

When checking with semgrep `v0.40.0` (and previous versions) everything works as expected.
```bash
$ docker run --rm -v `pwd`/test-semgrep:/test-semgrep returntocorp/semgrep:0.40.0 --config /test-semgrep --strict --error /test-semgrep/main.go
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
running 1 rules...
ran 1 rules on 1 files: 0 findings
```

With version `v0.41.0`:
```bash
$ docker run --rm -v `pwd`/test-semgrep:/test-semgrep returntocorp/semgrep:0.41.0 --config /test-semgrep --strict --error /test-semgrep/main.go
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
running 1 rules...
ran 1 rules on 1 files: 1 findings
/test-semgrep/main.go
severity:error rule:test-semgrep.wrong-err-check: Did you mean to check err instead of err?

28:    } else {
29:        random1, err = somethree("x", "y", "z")
30:        if err != nil {
31:            return
32:        }
33:    }
```

It's interesting that if you remove a single character from the comment on line 4, semgrep passes.
Not sure yet exactly what causes it to fail.

**What is the priority of the bug to you?**
Is this a P0 (blocking your adoption of Semgrep or workflow), P1 (important to fix or quite annoying), P2 (regular bug that should get fixed)?

P1

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

The bug happens when using semgrep.dev and the official docker images.

**Comment by ievans** [comment]
@alinbalutoiu does this still happen for you on v.62? feel free to re-open if so

**Comment by alinbalutoiu** [comment]
@ievans it seems that it got fixed in the recent releases. Thanks! 👍
