### ISSUE TITLE
Running with `--strict` does not report results

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3099]
**Describe the bug**
The help text for `--strict` implies that it enforces validation on the rules file. However, it also appears to affect the behavior of results even when the rule file is valid.

```
➜  frontend git:(develop) ✗ semgrep --config="r/typescript.react.security.audit.react-missing-noopener.react-missing-noopener" --disable-nosem

using config from https://semgrep.dev/r/typescript.react.security.audit.react-missing-noopener.react-missing-noopener. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 1 rules...
src/r2components/ExternalLink.tsx
severity:warning rule:typescript.react.security.audit.react-missing-noopener.react-missing-noopener: Missing 'noopener' on an anchor tag where target='_blank'. This could introduce
a reverse tabnabbing vulnerability. Include 'noopener' when using target='_blank'.

... snipped ...
[Shortened a long line from output, adjust with --max-chars-per-line]
-------- [hid 2 additional lines, adjust with --max-lines-per-finding] ---------
ran 1 rules on 244 files: 1 findings
8 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
➜  frontend git:(develop) ✗ semgrep --config="r/typescript.react.security.audit.react-missing-noopener.react-missing-noopener" --disable-nosem --strict
using config from https://semgrep.dev/r/typescript.react.security.audit.react-missing-noopener.react-missing-noopener. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 1 rules...
found 'nosem' comment with id 'typescript.react.security.audit.react-missing-noreferrer.react-missing-noreferrer', but no corresponding rule trying 'typescript.react.security.audit.react-missing-noopener.react-missing-noopener'
```

**Expected behavior**
I'd expect Semgrep to behave the same way in both cases given the help text. Semgrep should only error if the rule file is invalid when running with `--strict`. This should not change the behavior of Semgrep assuming that the file is valid.

**What is the priority of the bug to you?**
P1

**Comment by minusworld** [comment]
From @brendongo:

> I suspect this is cause the place where --strict is raising in lack of nosem happens while we are iterating over rules and the raise skips everything else. A fix would be to catch the raise into a var, keep working, and then at the end raising if that var is set

**Comment by minusworld** [comment]
This is definitely happening because of raising an exception while processing `nosem`s. Based on the description of this CLI flag, I would not expect this behavior. I would expect there to be some other flag which triggered this behavior, such as `--nosem-strict` or something.

```
def rule_match_nosem(rule_match: RuleMatch, strict: bool) -> bool:
    ... snipped ...
            message = f"found 'nosem' comment with id '{pattern_id}', but no corresponding rule trying '{rule_match.id}'"
            if strict:
                raise SemgrepError(message
    ... snipped ...
```

**Comment by minusworld** [comment]
@mschwager @brendongo Do you know if there is a reason for keeping this behavior under `--strict`?

**Comment by brendongo** [comment]
It does make sense for a `--strict` to be strict here and error when there are unused ignores (we do need to update the help text though). I believe that's how other tools work. And keeping it in strict reduces the need for yet another flag :D
