### ISSUE TITLE
Upgrade typescript grammar (May 2021)

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3102]
Depends on the javascript grammar upgrade https://github.com/returntocorp/semgrep/issues/3101

Minimum tree-sitter-typescript version: 4c20b54

Target delivery date: end of May (end of current month)

**Comment by azuline** [comment]
Any update? Running into a non-trivial number of parsing failures which have been flagged as fixed in tree-sitter.

**Comment by mjambon** [comment]
It's in progress and I still haven't finished.

**Comment by mjambon** [comment]
@azuline the typescript upgrade is done, it will in the next weekly release of semgrep. :tada: Thank you for your patience! It was a lot of changes, and we're still figuring out how to handle these upgrades faster.

**Comment by azuline** [comment]
Thanks!! I'm really excited to be able to run semgrep on ts codebases with far fewer/no parsing problems!
