### ISSUE TITLE
auto-inserted 'else' branch in ocaml AST

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3105]
**Describe the bug**

Either this shouldn't match or the [rules that detect useless `else`s](https://semgrep.dev/r/ocaml.lang.best-practice.ifs.ocamllint-useless-else) should be removed.

```
$ cat toto.ml
if true then huge
$ semgrep-core -lang ml -e 'if $COND then $BODY else ()' toto.ml
toto.ml:1
 if true then huge
```
^ should not match because there's no `else` in the source code.

Same code in the live editor (fails due to [something else at the moment](https://github.com/returntocorp/semgrep-app/issues/2518)):
https://semgrep.dev/s/J3nk

**Comment by aryx** [comment]
But why do we have this bug now? What is the PR that broke this?

**Comment by mjambon** [comment]
This started showing up with the ocamlformat reformat. First I thought it was due to semgrep only checking files that changed so I didn't look further.

**Comment by aryx** [comment]
I think it's fixed now.
