### ISSUE TITLE
[Kotlin] semgrep crashes when parsing some files in my projects

### ISSUE THREAD

**Issue by karling1989** [semgrep/semgrep#3108]
when I use semgrep to parse my projects,
the semgrep crashes and it gives me this error:

could anyone help me how to fix this issue?
[sem_log.txt](https://github.com/returntocorp/semgrep/files/6477579/sem_log.txt)

===============================================================
errors\":[{\"check_id\":\"FatalError\",\"path\":\"/tmp/targets/kotlin/Bandhook--master/app/src/main/java/com/antonioleiva/bandhookkotlin/repository/AlbumRepositoryImpl.kt\",\"start\":{\"line\":1,\"col\":1},\"end\":{\"line\":1,\"col\":1},\"extra\":{\"message\":\"Fatal Error: (Failure \\\"not implemented\\\")\",\"line\":\"/*\"}},{\"check_id\":\"FatalError\",\"path\":\"/tmp/targets/kotlin/Bandhook--master/app/src/main/java/com/antonioleiva/bandhookkotlin/repository/ArtistRepositoryImpl.kt\",\"start\":{\"line\":1,\"col\":1},\"end\":{\"line\":1,\"col\":1},\"extra\":{\"message\":\"Fatal Error: (Failure \\\"not implemented\\\")\",\"line\":\"/*\"}}],\"stats\":{\"okfiles\":2,\"errorfiles\":2}}\n\n--- end semgrep-core stdout ---\n--- semgrep-core stderr ---\nSome constructs are not handled yet\nCST was:\nOriginal backtrace:\nRaised at file \"stdlib.ml\", line 29, characters 22-33\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 798, characters 18-40\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 1491, characters 11-34\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 621, characters 27-54\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 838, characters 25-48\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 1679, characters 26-43\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 2129, characters 19-35\nCalled from file \"list.ml\", line 92, characters 20-23\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 2128, characters 8-156\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 2153, characters 16-35\n\nSome constructs are not handled yet\nCST was:\nOriginal backtrace:\nRaised at file \"stdlib.ml\", line 29, characters 22-33\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 798, characters 18-40\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 1491, characters 11-34\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 621, characters 27-54\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 838, characters 25-48\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 1679, characters 26-43\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 2129, characters 19-35\nCalled from file \"list.ml\", line 92, characters 20-23\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 2128, characters 8-156\nCalled from file \"src/parsing/tree_sitter/Parse_kotlin_tree_sitter.ml\", line 2153, characters 16-35\n\n\n--- end semgrep-core stderr ---\nAn error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep"

**Comment by colleend** [comment]
Thanks for filing this issue! Seems like there's code in `AlbumRepositoryImpl.kt` that hasn't yet been translated from our tree-sitter CST to the generic AST. If this code is able to be shared, would you mind sharing it? 

If not, I can take a look at the errors and dig into this a little more! 

Also, if you would like to run semgrep ignoring this specific kotlin file, you can use the `--exclude=*AlbumRepositoryImpl.kt` flag!

As a side note: Kotlin support is experimental, so we won't put too many support hours into it. Thanks for your patience 🙏

**Comment by karling1989** [comment]
Thank you for your response!
When I exclude the .kt files, the error above disappears,but another error ocurred.
Could you please help me to figure it out? Thanks very much!

================================
{"results": [], "errors": [{"type": "SemgrepError", "code": 2, "level": "error", "message": "semgrep-core failed: unparseable json output\nrule ID: 'rules.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-evaluate-code-injection'\nsemgrep-core exit code: -11\nsemgrep-core command: /usr/local/lib/python3.6/site-packages/semgrep/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmpmmiyqkj6 -j 8 -target_file /tmp/tmpmka6wjge -use_parsing_cache /tmp/tmppf_e8hox -timeout 30 -max_memory 0\nunexpected non-json output while invoking semgrep-core:\n--- semgrep-core stdout ---\n--- end semgrep-core stdout ---\n--- semgrep-core stderr ---\n--- end semgrep-core stderr ---\nAn error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep"}]}

**Comment by colleend** [comment]
hmmm interesting, from this error message it seems like `semgrep-core's` output can't be loaded as json, which we need for further processing. Would you mind sharing your rules file and target file, along with the command you used to run semgrep?

Thanks for your patience in this matter 😄

**Comment by karling1989** [comment]
The rule I am using is from the rules registry.
the command I ran is:
======================
semgrep -f ../rules/semgrep-rules-develop/javascript/puppeteer/security/audit/puppeteer-goto-injection.yaml --json -o ./result/output_semgrep.json /tmp/targets/

and I got this error:
============================
running 1 rules...
{"results": [], "errors": [{"type": "SemgrepError", "code": 2, "level": "error", "message": "semgrep-core failed: unparseable json output\nrule ID: 'rules.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection'\nsemgrep-core exit code: -11\nsemgrep-core command: /usr/local/lib/python3.6/site-packages/semgrep/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmp2mx5x7xp -j 8 -target_file /tmp/tmpwdfvc7bv -use_parsing_cache /tmp/tmp8o7o8i7e -timeout 30 -max_memory 0\nunexpected non-json output while invoking semgrep-core:\n--- semgrep-core stdout ---\n--- end semgrep-core stdout ---\n--- semgrep-core stderr ---\n--- end semgrep-core stderr ---\nAn error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep"}]}

**Comment by colleend** [comment]
What do you get if you run the command without the `--json` and `-o` flags? Would you also mind running the command with the `--debug` flag to get more clarity on what's happening?

**Comment by karling1989** [comment]
This time, the command I ran is:
===========================
semgrep --debug -f ../rules_backup_2/semgrep-rules-develop/javascript/puppeteer/security/audit/puppeteer-goto-injection.yaml /tmp/targets/

and I got this error:
==============================
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
loaded 1 configs in 0.11691498756408691
running 1 rules from 1 config ../rules_backup_2/semgrep-rules-develop/javascript/puppeteer/security/audit/puppeteer-goto-injection.yaml_0 
running 1 rules...
Running rule rules_backup_2.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection...
semgrep-core failed: unparseable json output
rule ID: 'rules_backup_2.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection'
semgrep-core exit code: -11
semgrep-core command: /usr/local/lib/python3.6/site-packages/semgrep/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmp7fmy_t_5 -j 8 -target_file /tmp/tmpmsw8u7e3 -use_parsing_cache /tmp/tmphwg2z90x -timeout 30 -max_memory 0
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---
--- end semgrep-core stdout ---
--- semgrep-core stderr ---
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

**Comment by colleend** [comment]
hmm, seems like it's having trouble with one of the tmp files -- this error is most likely because we can't successfully parse one of the files in /tmp. Would you try running semgrep with '-v' verbose flag so we can figure out which file it can't parse? After that we can look into what the file is. `/tmp/tmpmsw8u7e3` isn't an actual file in your directory, right?

**Comment by aryx** [comment]
hmm an exit code of -11 might be a segmentation fault.

**Comment by karling1989** [comment]
Thanks for your response!
This time the command I ran is:
============================
semgrep -v --debug -f ../rules_backup_2/semgrep-rules-develop/javascript/puppeteer/security/audit/puppeteer-goto-injection.yaml /tmp/targets/

and I got this error:
================================
Version cache expired: 1621907795:1621994402.7777445
A new version of Semgrep is available. Please see https://github.com/returntocorp/semgrep#upgrading for more information.
loaded 1 configs in 0.11352205276489258
running 1 rules from 1 config ../rules_backup_2/semgrep-rules-develop/javascript/puppeteer/security/audit/puppeteer-goto-injection.yaml_0 
running 1 rules...
Running rule rules_backup_2.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection...
--- semgrep-core stderr [rule 'rules_backup_2.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection'] ---
Fatal error: out of memory
--- end semgrep-core stderr [rule 'rules_backup_2.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection'] ---
semgrep-core failed: unparseable json output
rule ID: 'rules_backup_2.semgrep-rules-develop.javascript.puppeteer.security.audit.puppeteer-goto-injection'
semgrep-core exit code: -11
semgrep-core command: /usr/local/lib/python3.6/site-packages/semgrep/bin/semgrep-core -lang javascript -json -rules_file /tmp/tmpw58ytt5e -j 8 -target_file /tmp/tmp95xagse_ -use_parsing_cache /tmp/tmpdr4mo80q -timeout 30 -max_memory 0
unexpected non-json output while invoking semgrep-core:
--- semgrep-core stdout ---
--- end semgrep-core stdout ---
--- semgrep-core stderr ---
Fatal error: out of memory
--- end semgrep-core stderr ---
An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

**Comment by colleend** [comment]
hmm, @aryx would you happen to have any context as to why there would be an "out of memory" error?

**Comment by aryx** [comment]
If you have a rule and a test file i can
Reproduce the error locally yes

**Comment by aryx** [comment]
Should work better now that Kotlin has been promoted to GA.
Reopen if it's still an issue.
