### ISSUE TITLE
c lang support

### ISSUE THREAD

**Issue by yum7777** [semgrep/semgrep#3111]
Hi.

I am looking for a tool to appreciate the c language.

I'm thinking of paid support.

I looked at the c language rules. The content seems to be less than the other rules.

How much c language support is there in semgrep?

Can I get enough performance if I purchase it now? Compared to other companies.

**Comment by daghan** [comment]
Hi @yum7777, do you mind joining our slack channel (r2c.dev/slack) so we can talk about current and upcoming work on C?

**Comment by mschwager** [comment]
Just to follow up on our existing C support, it's currently in **alpha** status. Our [supported languages](https://semgrep.dev/docs/status/) docs have more information on what this means :+1:

**Comment by mschwager** [comment]
Closing out - feel free to re-open if you have any more questions!
