### ISSUE TITLE
Your example doesn't work on Playground

### ISSUE THREAD

**Issue by Besnn** [semgrep/semgrep#3118]
Trying to execute the code in [this example](https://semgrep.dev/s/B47A) from the *Writing Rules* section of the docs gives the following error:
```Could not parse pattern:
All collection items must start at the same column at line 2, column 3:

- id: is-comparison
  ^^^^^^^^^^^^^^…
```
which is weird considering the embedded version works and there seem to be no inconsistencies in the rule definition.  

[Link to embedded version](https://semgrep.dev/docs/writing-rules/overview/)

**Comment by underyx** [comment]
Thanks for the report! I think the issue is that we take

```yaml
  message: |
    'is' is for reference equality, not value equality! Use `==` instead!
```

and try to shorten the YAML by converting that into

```yaml
  message: 'is' is for reference equality, not value equality! Use `==` instead!
```

but since the message starts with a single quote it becomes invalid YAML.

I will let others on the team schedule a fix.

**Comment by brendongo** [comment]
The yaml conversion also breaks this example:
```
rules:
- id: get-value
  pattern: "message: $A"
  message: Value $A
  severity: WARNING
```

Converting to simple then back to advanced (or sharing) removes the quotes around pattern which breaks the rule

**Comment by brendongo** [comment]
Updated the example to bypass this quote stripping and will track the quote stripping bug internally.

**Comment by brendongo** [comment]
Docs should be updated in a sec with the new example that doesnt break in playground. Thanks for filling @Besnn!
