### ISSUE TITLE
Matching Go "any function that accepts an argument that is a function" does not work

### ISSUE THREAD

**Issue by dottedmag** [semgrep/semgrep#3119]
**Describe the bug**

`func $FUNC(..., $ARG func(...), ...)` does not match any function that accepts a function.

**To Reproduce**

https://semgrep.dev/s/okdx/

**Expected behavior**

This match should match any function definition that accepts a function as one of the arguments.
**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

Docker image, version 0.51.0

**Comment by aryx** [comment]
you need to use a metavariable for the return type, func(...) $T, otherwise it will match only function that do not return anything.

**Comment by aryx** [comment]
And also you need to name the parameter in the function, because it is named in the pattern, otherwise it will not match either.
