### ISSUE TITLE
[JS] Dictionary matching yield inconsistent results

### ISSUE THREAD

**Issue by sk-** [semgrep/semgrep#3120]
**Describe the bug**
Matching JS dictionaries yield unexpected results, for example the pattern `{}` is equivalent to `{...}`, the pattern `{...$X}` matches anything and the pattern `{x: $X}` also matches any dictionary with that key.

Note that this is different to what happens in Python. (#1003 could be related)

**To Reproduce**
```js
a = {};
a = {...x};
a = {...x, ...y};
a = {...x, y: z};
a = {...x, z: 3, ...y}
a = {x: 1};
a = {x:1, y:2};
```

https://semgrep.dev/s/2bP8 (note that the test code gets overwritten when you load it up)

**Expected behavior**
- Pattern `{}` should only match the empty dictionary `{}`
- Pattern `{...$X}` should only match dictionaries of the form `{...anotherDict}`
- Pattern `{x:$X}` should only match dictionaries with just the key `x`

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep Playground and 0.48.0 installed via homebrew.

**Comment by IagoAbal** [comment]
@sk- for now you can use:
```
options:
  implicit_ellipsis: false
```
on each rule where this behavior is a problem, eventually it should become the default.
