### ISSUE TITLE
Use constant propagation with typed metavariables

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3122]
It would be awesome if we could combine two of our most powerful operations: constant propagation and typed metavariables.

This snippet highlights the desired behavior: https://semgrep.dev/s/XLKN/?version=develop

Note the `$O[($ARG : float)]` not matching `value = obj[two]`.

This would be particularly helpful for Gitlab's `eslint.detect-object-injection` rule: https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/blob/main/rules/eslint.yml.

**Comment by aryx** [comment]
cc @emjin @IagoAbal

**Comment by emjin** [comment]
hmm we already should have that---I'll investigate.

**Comment by IagoAbal** [comment]
@mschwager Is the intention here to filter out arguments of type `float` regardless of whether they are constant or not?
```
- pattern-not: "$O[($ARG : float)]"
```
E.g. given `x + 3.141592` where `x` is an user input, you could infer that expression to have type `float` but it's not constant. Should it be filtered out?

**Comment by mschwager** [comment]
> @mschwager Is the intention here to filter out arguments of type float regardless of whether they are constant or not?

Hmm, good point! I believe the intention is only to filter if it's constant. Maybe this issue is effectively the same as https://github.com/returntocorp/semgrep/issues/3085 and we should close it. What do you think?

**Comment by emjin** [comment]
The issue still stands right? Because `two` is a constant when referenced.

Regardless, I actually think Nathan mentioned that filtering out all floats makes sense for this rule. Since we're concerned about object injection, indexing into an array wouldn't be a problem. I am very much not an expert on this, though

**Comment by mschwager** [comment]
> Regardless, I actually think Nathan mentioned that filtering out all floats makes sense for this rule. Since we're concerned about object injection, indexing into an array wouldn't be a problem.

Ahh, yeah, I agree here. I think that's right!

**Comment by emjin** [comment]
Hm, @IagoAbal this looks like it's still a constant propagation problem. My pattern is `$O[($ARG : float)]`. When my target is

```
function foo(someVar, obj) {
  let two = 2
  value = obj[two]
}
```

it matches. But when it's

```
function foo(someVar, obj) {
  two = 2
  value = obj[two]
}
```

it doesn't.

**Comment by IagoAbal** [comment]
Looking into it!

**Comment by IagoAbal** [comment]
Actually constant propagation works in both cases, it's type inference that it doesn't. You can see this by looking at the output of `semgrep-core -lang js -constant_propagation <file>`. From what I can see in Naming_AST we only annotate variables with types when the variables are explicitly declared, and in the case of `two = 2` the variable is being implicitly declared.

**Comment by IagoAbal** [comment]
@mschwager is it crucial to fix these false positives?
```
  value = obj[three[0]]
  value = obj[six.s]
  value = obj[six['s']]
```
Or is it enough to remove the `value = obj[two]` false positive to close this issue?

**Comment by mschwager** [comment]
> @mschwager is it crucial to fix these false positives?
> 
> ```
>   value = obj[three[0]]
>   value = obj[six.s]
>   value = obj[six['s']]
> ```
> 
> Or is it enough to remove the `value = obj[two]` false positive to close this issue?

Nope, those ones aren't important, just `value = obj[two]` :+1:
