### ISSUE TITLE
ruby: string constant propagation doesn't seem to work with double quotes and embedded newlines

### ISSUE THREAD

**Issue by aegarbutt-stripe** [semgrep/semgrep#3127]
**Describe the bug**
Given the pattern:
```
  patterns:
    - pattern-either: 
      - pattern: |
          foo(...)
    - pattern-not: |
        foo("...")
```
 and the code:
```
a = foo(data)
a = foo("foo: bar")

const_str1 = "foo: bar"
a = foo(const_str1)

const_str2 = 'foo: bar'
a = foo(const_str2)

const_str3 = "foo: bar\n"
a = foo(const_str3)

const_str4 = 'foo: bar\n'
a = foo(const_str4)
```

The call to `foo(data)`  **and** `foo(const_str3)` both match, but none of the other calls.

**To Reproduce**
https://semgrep.dev/s/aegarbutt-stripe:ruby-string-with-newline

**Expected behavior**
I expect only `foo(data)` to match.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by brendongo** [comment]
@aegarbutt-stripe do you mind updating the issue with examples (preferably on our live editor)

**Comment by aegarbutt-stripe** [comment]
(Apologies for the early submit)

**Comment by aegarbutt-stripe** [comment]
(and I'm aware that \n in the single-quoted string is not a newline.)
