### ISSUE TITLE
String Regex Matching Not working on Generic Pattern Matching

### ISSUE THREAD

**Issue by abhinavbansal19961996** [semgrep/semgrep#3132]
**Describe the bug**
String Regex Matching Not working on Generic Pattern Matching.

I have my test.yml YML file as below for generic pattern matching::
rules:
- id: my_pattern_id
  pattern: template-name=$A
  message: Semgrep found a match
  severity: WARNING

I have my test.txt file as:
template-name=typescript-template
typescript-sdsd=0.1.0

Now i want to put something in the pattern such that i get the value after equal in metdata i.e. i want to get this value "typescript-template". This value can be anything like "typescript-web-template" etc

I tried writing regular expresison but it doesnt work and then i wrote above pattern but somehow its stopping before - sign.
Can someone pls check why this simple use case is not working?

semgrep  --config=test.yml test.txt

**Comment by brendongo** [comment]
Hi @abhinavbansal19961996! One of the simplifying assumptions that generic pattern matching makes is that it treats special characters as token delimiters.

We also have a yaml language in alpha right now so it still have pretty rough edges

**Comment by brendongo** [comment]
I'm not too familiar with `=` syntax in yaml but for example the rule:
```
rules:
- id: get-value
  pattern: "message: $A"
  message: Value $A
  severity: WARNING
```

would match 
```
message: hello
```

**Comment by abhinavbansal19961996** [comment]
umm hmm.. ANy workaround on how to solve the above use case and catch just this part **typescript-template** in a  .txt file? We are moving towards semgrep instead of grep in our project.

**Comment by brendongo** [comment]
Hmm is the intention to do a regex match on the value of `template-name` and only firing if it matches a certain regex or is the intention to fire whenever template-name is set to something?

**Comment by abhinavbansal19961996** [comment]
Ok Exact scenario is like this:
I have 1000 .txt files with 2 lines
template-name=ANYTHING
typescript-sdsd=ANYTHING


Now I want to use semgrep yml rules to catch just that ANYTHING part and store it in 1000 rows with 2 columns in my excel sheet giving template name and typescript-sdsd.

So looking to use SEMgrep for parsing above txt file and get just that ANYTHING PART.

**Comment by brendongo** [comment]
Hmm I think this is something I would just use regular grep for. Something like this should get you what you want:

`find . -type f -name "*.txt" -print0 | xargs -0 grep 'template-name' | awk '{sub(/=/," ")}1' | awk '{print $2}'`
