### ISSUE TITLE
No centralized place for nosemgreps

### ISSUE THREAD

**Issue by saltycoder** [semgrep/semgrep#3153]
**Is your feature request related to a problem? Please describe.**
There is no way to track and determine why a rule was ignored for a finding.

**Describe the solution you'd like**
It would be nice to have a static file to place all nosemgrep ignores in.  In addition to the nosemgrep annotation, having the ability to add a comment to why the nosemgrep was added would allow folks to quickly review/audit why nosemgreps were put in place.

**Describe alternatives you've considered**
An alternative approach is to have the developers place a comment along with the nosemgrep comment within the code. However, this would lead to unwanted large comment blocks within the code.  In addition, a new tool would need to be created to retrieve the nosemgrep comment, along with the comment from the developer.

**Additional context**

**Comment by dlukeomalley** [comment]
Re-opening, based on discussion in #3521
