### ISSUE TITLE
Constant Propagation leads to False Positives in java.lang.correctness.eqeq.eqeq in 0.52.0

### ISSUE THREAD

**Issue by TomMD** [semgrep/semgrep#3155]
**Describe the bug**

```
root@a7069e90ecc4:/# mkdir test
root@a7069e90ecc4:/# cd test
root@a7069e90ecc4:/test# curl -LO https://raw.githubusercontent.com/apache/solr/af64b96ece2b81bdad8e1a5d03e6041cc0a21312/solr/core/src/test/org/apache/solr/cloud/TestPullReplica.java
... snip ...
root@a7069e90ecc4:/test# semgrep --config=p/ci TestPullReplica.java
using config from https://semgrep.dev/p/ci. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 135 rules...
... snip ...
TestPullReplica.java
severity:error rule:java.lang.correctness.eqeq.eqeq: `replicaJetty == replicaJetty` or `replicaJetty != replicaJetty` is always true. (Unless the value compared is a float or double).
To test if `replicaJetty` is not-a-number, use `Double.isNaN(replicaJetty)`.

280:    if (replicaJetty != null) {
ran 135 rules on 1 files: 1 findings
root@a7069e90ecc4:/test# sed -n 280p TestPullReplica.java
    if (replicaJetty != null) {
```

**To Reproduce**
See above

**Expected behavior**
Semgrep should not report a bug in this case - it should be silent.

**What is the priority of the bug to you?**

- [X] P2: regular bug that should get fixed

**Environment**
This was in a docker image with semgrep 0.52.0 pip installed.

**Comment by brendongo** [comment]
For convenience: https://semgrep.dev/s/0nYr

Looks like the constant null value is being propagated and we think the statement is `null != null`

**Comment by brendongo** [comment]
Really the spirit of the rule is finding  an == that is always true so I think we want the rule to run without constant propagation or have a way to determine if a constant that was propagated is always or sometimes that value? cc: @minusworld @colleend 

Or is this just a bug with constant propagation since the null value should probably not be propagated given the setter in the for loop?

**Comment by emjin** [comment]
@IagoAbal What's the status of this?

**Comment by IagoAbal** [comment]
I will dig into this today.

**Comment by IagoAbal** [comment]
This is due to an incomplete AST-to-IL translation, will fix.
