### ISSUE TITLE
C# tests are broken

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3161]
Looks like we're getting parse errors on some of our C# tests: https://github.com/returntocorp/semgrep/runs/2631102847?check_suite_focus=true

Also confirmed here:

```
$ cat semgrep-core/tests/csharp/metavar_call.cs | docker run --rm -i returntocorp/semgrep:0.52.0 -e '$X == $X' -l csharp -
ran 1 rules on 1 files: 0 findings
1 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

**Comment by IagoAbal** [comment]
OK I see, it's a parsing warning that I missed and it was not caught by semgrep-core tests.
