### ISSUE TITLE
$...BODY not working for Go

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#3170]
https://semgrep.dev/s/L0bG is not matching for @dgryski but if you use `...` in place of `$...BODY` it matches. He needs to capture the function body for autofix.

See: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1621623452029300 for more context

**Comment by aryx** [comment]
This works now: https://semgrep.dev/s/L0bG?version=develop
Might want to use gofmt on the autofixed code though ...
