### ISSUE TITLE
[playground] says parse error in pattern when the parse error is in the rule

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3174]
**Describe the bug**

**To Reproduce**
If I put a parse error in the rule, for example I use ruleS instead of rules at the beginning,
and then I click run, it says there's a parse error in the pattern (which is not correct; the parse error is in the rule).

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x ] P2: regular bug that should get fixed

**Comment by aryx** [comment]
would be fixed by using a better yaml parser. cc @emjin

**Comment by aryx** [comment]
Also what's wrong with:
```
rules:
  - id: logging
    languages:
      - java
    message: Match found for logging
    patterns:
        - pattern-inside: |
          import java.util.logging.$F;
          ... 
        - pattern: $G.setLevel(...);
    
```

**Comment by emjin** [comment]
I believe this is fixed by my hack project
