### ISSUE TITLE
Ruby matches don't include the closing parenthesis for function calls

### ISSUE THREAD

**Issue by aegarbutt-stripe** [semgrep/semgrep#3178]
**Describe the bug**
In ruby, parentheses are optional for function calls. Semgrep already knows how to match both with and without parentheses. For example, the pattern:

```
foo($...ARGS)
```

will match either of:
```
foo abcd
foo(efgh)
```

Unfortunately, the semgrep match doesn't include the closing parenthesis in its match. This is somewhat problematic in the case of trying to write automatic fixes.

Trying to write an autofix, if i use:
```
fix: bar($...ARGS)
```

the suggested fix will be:
```
bar(abcd)
bar(efgh)) # <-- Extra trailing parenthesis
```

If instead I use:
```
fix: bar($...ARGS
```

the suggested fix will be:
```
bar(abcd # <-- Missing trailing parenthesis
bar(efgh)
```

**To Reproduce**
https://semgrep.dev/s/pl8d/

**Expected behavior**
I can accommodate the presence or lack of parentheses in auto-fixes.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

Fixing this would make autofixes much more capable.

**Environment**
Both semgrep.dev and a local build

**Comment by aryx** [comment]
should work now

**Comment by aryx** [comment]
We correctly match the closing paren now, see https://semgrep.dev/s/2b7B/?version=develop

**Comment by aegarbutt-stripe** [comment]
🎉
