### ISSUE TITLE
Differentiate tagged template literals

### ISSUE THREAD

**Issue by CGamesPlay** [semgrep/semgrep#3187]
**Is your feature request related to a problem? Please describe.**
In TypeScript libraries like [Prisma](https://www.prisma.io/), you can execute raw, unescaped SQL using a function like `prisma.$executeRaw` (I doubt this feature is specific to Prisma or even SQL, but it's what I'm attempting to detect against now). TypeScript (JavaScript) provides a syntax to safely use these functions with escaped user input, namely: tagged template literals. Consider the following:

```typescript
async function getUserById(id: number) {
  // Solution 1: unsafe, allows SQL injection
  await prisma.$executeRaw("SELECT * FROM users WHERE id = " + id);
  // Solution 2: safe: properly escapes the value
  await prisma.$executeRaw`SELECT * FROM users WHERE id = ${id}`;
  // Solution 3: unsafe, allows SQL injection
  await prisma.$executeRaw(`SELECT * FROM users WHERE id = ${id}`);
}
```

The problem is that solutions 2 and 3 produce identical ASTs in semgrep, so you cannot write a pattern that differentiates them.

**Describe the solution you'd like**
The ASTs need to be different somehow, and there needs to be a pattern syntax which allows a user to detect solution 3 and report it as an error.

**Describe alternatives you've considered**
I haven't been able to find any way to write a pattern that catches this error.

**Additional context**
```
$ semgrep --version
0.52.0
```

**Comment by CGamesPlay** [comment]
Wow. Astounding turnaround time. Thank you.

I briefly reviewed the commit which resolves and I did have one note, which I don't believe affects this issue but which may be relevant for future issues:

```typescript
// This is a function call with a single string argument
foo(`a${b}c`)
// This is a function call with N+1 arguments, where N is the number of interpolated values
foo`a${b}c`
// Technically it's syntactic sugar for the following
foo(['a', 'c'], b)
```

Properly representing this may be useful for more detailed rules, although again my request is satisfied.

Thanks again for the amazing turnaround time.

**Comment by aryx** [comment]
thanks for the explanation, I've added a note about it in pfff/lang_js/parsing/ast_js.ml
