### ISSUE TITLE
echo not supported as pattern-sinks in PHP taint mode

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3191]
**Describe the bug**
echo is not supported as a `pattern-sinks` in taint mode in PHP

**To Reproduce**
https://semgrep.dev/s/DJWq

**Expected behavior**
Line 6 and 9 in the playground linked above should match and not result in `Semgrep exited with an unspecified error`

**What is the priority of the bug to you?**
P0: blocking your adoption of Semgrep or workflow

**Comment by aryx** [comment]
I think it's because taint-mode currently restricts source/sinks/sanitizers to expressions, but echo is a statement.

**Comment by aryx** [comment]
In the long term we want to specify a source/sink by any pattern (expr, stmt, parameter, etc.) and be also able to specify a source/sink by a formula (a conjonction of pattern-inside with a pattern for example, and with a metavariable-regexp even).

**Comment by erwanlr** [comment]
Please also consider casting (ie `(int) $_GET['x'];`) in pattern-sanitizers, so far I've been unable to handle them (I think because it's a statement and not an expression as well)

**Comment by aryx** [comment]
hmm no Cast should be expressions, but you need to remove the trailing semicolon to get an expression.

**Comment by aryx** [comment]
Can we close this @IagoAbal ? Should work now?

**Comment by IagoAbal** [comment]
Not yet, since making `echo` an expression in the parser introduced conflicts I will now try converting the pattern after the fact. I'll handle this today.
