### ISSUE TITLE
[JS] Add support for private class fields

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3192]
JS/TS supports special [private class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields) syntax, but it looks like we can't parse it yet: https://semgrep.dev/s/WgkZ/

**Comment by mschwager** [comment]
Another example from the MDN page: https://semgrep.dev/s/0n7q/

**Comment by aryx** [comment]
Is it an official extension or just in mozilla js engine?
We should report the bug in tree-sitter-javascript then.

**Comment by mschwager** [comment]
> Is it an official extension or just in mozilla js engine?
> We should report the bug in tree-sitter-javascript then.

Looks like they're a part of the [ECMA standard](https://stackoverflow.com/questions/22156326/private-properties-in-javascript-es6-classes), and are available in [most implementations](https://github.com/tc39/proposal-class-fields#implementations).

**Comment by zbuc** [comment]
I created https://github.com/tree-sitter/tree-sitter-javascript/issues/176 to report this to tree-sitter

**Comment by aryx** [comment]
Thx a lot @zbuc

**Comment by zbuc** [comment]
The fix has been merged to tree-sitter-javascript 🎊

**Comment by aryx** [comment]
good job @zbuc ! Now we need to pull the latest version of tree-sitter-javascript. @mjambon is usually the one doing that but this might take some time because he is in the middle of big refactorings for integarting javascript and typescript in semgrep.

**Comment by mschwager** [comment]
Hey @mjambon, are there any updates here? I know @zbuc is still eager to get this fix. Since it's been fixed upstream in tree-sitter is it just a matter of updating the grammar now? I.e. will this be sufficient for a fix: https://github.com/returntocorp/semgrep/issues/3350?

**Comment by mjambon** [comment]
This is now merged, it will be in the next semgrep release (0.59).
