### ISSUE TITLE
b && c does not match a && b && c 

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3198]
**Describe the bug**
In PHP, `pattern: "!check1($VAR) && !check2($VAR)"` or even `pattern: <... !check1($VAR) && !check2($VAR) ...>` do not match something like `if (!check3($stuff) && !check1($stuff) && !check2($stuff)) {`, but matches `if (!check1($stuff) && !check2($stuff) && !check3($stuff)) {`

Don't know if it's a regression or not, but I am pretty sure it was working in at least a previous version of semgrep

**To Reproduce**
https://semgrep.dev/s/1n75

**Expected behavior**
Would expect both pattern to match the expression where `check3()` is before the actual statement to match

**What is the priority of the bug to you?**
P1: important to fix or quite annoying

**Comment by aryx** [comment]
yes it's because && is left associative, so a && b && c is parsed as (a && b) && c, which is not matched by b && c.

**Comment by aryx** [comment]
We should handle specially those binary operators.
cc @IagoAbal

**Comment by aryx** [comment]
that's where user-defined equivalences could be useful ... to define the associativity, commutatitivity and distributivity of certain operators.

**Comment by IagoAbal** [comment]
> We should handle specially those binary operators.

Do you mean that we should have those equivalences built into the matching engine?

**Comment by aryx** [comment]
yep. I don't think the user-defined equivalence feature could anyway  fix the issue.

**Comment by IagoAbal** [comment]
I wonder what exactly was working in a previous version of Semgrep because we didn't have this kind of equivalence built-in. Or did you wrote some user equivalence for that?

**Comment by erwanlr** [comment]
My guess is that the code I tested so far was things like `if (!check3($stuff) && (!check1($stuff) && !check2($stuff))) {` which was correctly detected as it's `a && (b && c)` and then I stumbled across a `(!check3($stuff) && !check1($stuff) && !check2($stuff)`case (`(a && b) && c`) which did not match and was surprised

**Comment by IagoAbal** [comment]
@erwanlr out of curiosity, for your particular use case here, is commutative-matching desirable or undesirable?

**Comment by erwanlr** [comment]
For this case, the commutative matching (a pattern like `b && c` matching code like `(a && b) && c`) is highly desirable, otherwise I would miss matches

**Comment by IagoAbal** [comment]
@erwanlr we can do that with just associative matching. With commutativity you can make `b && c` match code like `(b && a) && c`. The thing is that `&&` is not truly commutative. In my opinion, it is useful to pretend it is commutative for code-searching purposes, but some other users have complained about this, so we may disable it by default. I will however let `&&` be associative, so `b && c` should continue matching `(a && b) && c`.

**Comment by erwanlr** [comment]
Oh, I mixed both (associative and commutative), but I just had a look at my real rule and yea for this case I would need both associative and commutative matching.

If it's creating more trouble it's fine to disable it by default, will there be an option to enable it via the rule though ?

**Comment by IagoAbal** [comment]
Thanks for confirming! There will be a way to enable it although I am not sure how it will look exactly. I will propose:
```
rules:
  - id: rule-id
    settings:
      commutative_boolop: true
    ...
```
This may change, but it should be documented.

**Comment by IagoAbal** [comment]
0.57.0 is out, finally you'll have to do:
```
rules:
  - id: rule-id
    options:
      commutative_boolop: true
    ...
```
The docs should be updated soon.
