### ISSUE TITLE
[Metachecker] detect useless pattern-either and patterns

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3203]
context: https://r2c-community.slack.com/archives/C01KY32FDAT/p1621891891043200

from @minusworld:
```
Yep, I think so - basically this rule is a best-practice for keeping YAML files smaller.
pattern-eithers with only one pattern can be removed;
patternss with only one pattern can be removed;
patternss with only a pattern-either as a direct child can be removed; pattern-either is supported as a top-level key
```

**Comment by aryx** [comment]
Note that it seems the playground sometimes automatically adds those redundant pattern-either.

**Comment by emjin** [comment]
I actually think this only happens because the playground automatically adds it. It's a weird thing to do if you're writing it yourself.
