### ISSUE TITLE
[Java] Symbolic expression propagation

### ISSUE THREAD

**Issue by 101142TS** [semgrep/semgrep#3207]
**Describe the bug**
Hello team,
Can semgrep expand the expression（Similar to three address codes）？Or is there any other tool that can help me expand the expression in Java? thx :D

**To Reproduce**

Code A and code B are semantically the same.  For code B, I just expanded the expression in code A.
code A:
```java
public final ZipEntry getNextEntry() {
        String name;
        ZipEntry nextEntry = super.getNextEntry();
        if (nextEntry == null || (name = nextEntry.getName()) == null || (!name.contains("../") && !name.contains("..\\"))) {
            return nextEntry;
        }
        throw new SecurityException(":" + nextEntry.getName());
    }
```
code B:
```java
public final ZipEntry getNextEntry() {
        String name;
        ZipEntry nextEntry = super.getNextEntry();
        if (nextEntry == null)
            return nextEntry;
        ZipEntry c = nextEntry;
        name = c.getName();
        if (name == null)
            return nextEntry;
        
        boolean b1 = !name.contains("../");
        boolean b2 = !name.contains("..\\");
        if (b1 && b2)
            return nextEntry;

        throw new SecurityException(":" + nextEntry.getName());
    }
```
The following rule matches code B well, but not code a. 
```
rules:
- id: ZipEntry
  patterns:
    - pattern: $Y = $X.getName();
    - pattern-inside: |
        (ZipEntry $X) = ...;
        ...
        (String $Y) = $X.getName();
        ...
        $Z = <... $Y.contains("...") ...>;
        if (<... $Z ...>) {
          ...
        }

        ...
  languages: 
    - java
  message: |
    match
  severity: WARNING
```

**Expected behavior**

For Java, can semgrep or other tools split expressions into unary or binary expressions?

**Comment by aryx** [comment]
cc @IagoAbal

**Comment by aryx** [comment]
maybe symbolic expression propagation could help here, but that means you would write the simpler pattern
``` 
if(<... (ZipEntry $X).getName().contains("...") ...> {
   ...
}
```
and it would match A and B because we would propagate expressions.

**Comment by 101142TS** [comment]
What is the meaning of symbolic expression? I didn't find an explanation in the document(https://semgrep.dev/docs/). Would you please write down the complete rules? Thank you very much.

**Comment by aryx** [comment]
Oh sorry, markdown issue. I've written the complete pattern above.

**Comment by aryx** [comment]
The term symbolic expression was meant for my colleague Iago; it's not documented, it's an internal term we use to discuss about certain features.

**Comment by aryx** [comment]
:wave:
