### ISSUE TITLE
Missing "message" and "severity" in the output

### ISSUE THREAD

**Issue by OlegPQ** [semgrep/semgrep#3208]
I downloaded the latest release at the moment, _semgrep-v0.53.0-osx.zip_ from https://github.com/returntocorp/semgrep/releases. Start semgrep in the following way:

`./semgrep -config ./rule.yaml -lang go ./code`

**Rule.yaml** (a simple example from the package):
```
rules:
- id: dgryski.semgrep-go.errnilcheck.err-nil-check
  patterns:
  - pattern-either:
    - pattern: |
        if err != nil {
                return err
        }
        return nil
    - pattern: |
        if err != nil {
                return $X, err
        }
        return $X, nil
  message: superfluous nil err check before return
  languages:
  - go
  severity: ERROR

```

**Output:**
```
./code/client.go:194 with rule dgryski.semgrep-go.errnilcheck.err-nil-check
 	if err != nil {
 		return err
 	}
 	return nil
```

I noticed that my output is different from the examples on the internet, there is no `message` and `severity` in the output.
Why isn't this in the output, what am I doing wrong? Is there any flag needed for this?

**Comment by aryx** [comment]
Are you using semgrep or the semgrep-core binary? Looks like the output of semgrep-core.

**Comment by OlegPQ** [comment]
You are right, semgrep-core.
The archive contained only semgrep-core and spacegrep. So I renamed semgrep-core to semgrep, didn't know they could be different and thought they are the same. So, semgrep-core cannot output the above mentioned information?

**Comment by aryx** [comment]
you can use the -json flag I think to get those information, but it's better to use the semgrep python wrapper you can install via homebrew or pypi.

**Comment by OlegPQ** [comment]
Yeap, -json works, I can see the `message`, but with this flag I cannot see the code and `severity`.

> you can install via homebrew or pypi.

That's exactly what I wanted to avoid.

There doesn't seem to be a solution.

**Comment by brendongo** [comment]
@OlegPQ you can also run from our published docker image. But for now we don't build a binary for the python wrapper around semgrep-core. 

Going to close this issue as resolved feel free to open a new one re: packaging/binaries
