### ISSUE TITLE
[Python] semgrep cannot match class code, with or without aliasing

### ISSUE THREAD

**Issue by ILoveWin32k** [semgrep/semgrep#3212]
I need to match a whole class with a pattern and not use pattern-inside to find code inside a pattern
and semgrep does not match the class code...

reproduce:
https://semgrep.dev/s/E595

expected:
  match the class
  
 result:
  matches nothing

**Comment by aryx** [comment]
Weird. This does not work either: https://semgrep.dev/s/R8Jv/

**Comment by aryx** [comment]
The problem had actually nothing to do with aliasing.
It's because $VAR = Vuln() was not matched in any order, because assign in Python inside classes
were not translated in VarDef.
