### ISSUE TITLE
Specifying multiple JSON keys requires ellipsis

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3214]
This seems odd to me:

- Doesn't work: https://semgrep.dev/s/4yAL/
- Works: https://semgrep.dev/s/Pp43/

**Comment by mschwager** [comment]
Although it works with just the two keys: https://semgrep.dev/s/B4X7/

This seems fine to WONTFIX too, it just caught me a little off guard.

**Comment by aryx** [comment]
I think we should impose '...' to express you don't care about other keys. We are not always consistent there, but
the good behavior I think should be to impose to have a '...', like we do here.

Let me know where we don't force the '...'.
I know we currently don't in JSX for attributes, but I want to fix that.
