### ISSUE TITLE
Move `perf/` into its own repository

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3231]
`perf/` is getting a lot of attention lately, but it really only has a nominal dependency on Semgrep itself.

Moving `perf/` into its own repository will let us more easily develop here, plus allowing us to more easily set up testing.

When this gets moved, `perf/` will still need to:
- work with an arbitrary version of Semgrep, so that fixes optimizations can be tested
- run regularly and report benchmarking metrics to the benchmarking endpoint

**Comment by aryx** [comment]
Are we sure we want to do that?
cc @emjin

**Comment by emjin** [comment]
I think this is a good idea; perf is separate from semgrep functionality, and that way we don't need to worry about the size of files we include
