### ISSUE TITLE
Project hash metric depends on passwords

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3232]
**Describe the bug**
The project hash should be a stable function of the project location, and not dependent on username or password.

**To Reproduce**
Run `echo $(git ls-remote --get-url) | sha256sum` in a gitlab CI multiple times

**Expected behavior**
Our metrics return the same value from run to run

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
GitLab CI

**Comment by mschwager** [comment]
Another consideration, if `git` isn't available we make the following call:

```python
project_url = manually_search_file(".git/config", ".com", "\n")
```

I suspect the `.com` search will fail for non-`.com` hosted `git` repositories, e.g. `.net`. I don't think this is a problem for `gitlab.com` cloud repositories, but may cause issues with on-prem deployments.

**Comment by squaresurf** [comment]
@mschwager heads up that https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/merge_requests/40 and https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/merge_requests/44#note_585005828 ensure that git is now available when semgrep is running in GitLab :smile:
