### ISSUE TITLE
Report number of target files that were skipped due to excessive size

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3235]
Since we started [ignoring targets over a certain size](https://github.com/returntocorp/semgrep/pull/3081), we should report how many files were skipped due to this filter.

**Comment by ievans** [comment]
More feedback on this from a user:

> We don’t know which files are scanned, which files are processed? we'd like to give a report to the development team.
> * high level view — this is the folder, this is all the files parsed (python files, js files)
> * then more granular — more specific on how many LoC are parsed, total coverage of semgrep on 80% of codebase. 100% covered.
> * as well as a logfile - why couldn’t we parse some file X?

**Comment by xmo-odoo** [comment]
Putting in a :+1: for better reporting of semgrep's files selection (at least at higher log level): in a somewhat large project I just realised semgrep skips entire files and I have no idea why. Even giving semgrep the name of the file, it reports 

    ran 135 rules on 0 files: 0 findings

As far as I can tell I don't seem to have any relevant ignore file (e.g. `rg` finds stuff in that file just fine). I'm completely stumped.

Running with `-v`, it does report that

> No .semgrepignore found. Using default ignores rules

but the "default ignores rules" don't seem documented in `--help` or semgrep.dev, and I found no flag to skip them.

To the extent that I can figure anything, it looks like it's ignoring anything living in a `tests` directory,

**Comment by ievans** [comment]
@xmo-odoo so sorry about that. The release notes for 0.77 explain that we now use the same default `semgrepignore` between semgrep CI and semgrep CLI, see it here: https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/templates/.semgrepignore

we'll do better about updating the output, tracking here: https://github.com/returntocorp/semgrep/issues/1964 and I'm going to ask the team to prioritize this and #1964

**Comment by xmo-odoo** [comment]
> so sorry about that. The release notes for 0.77 explain that we now use the same default `semgrepignore` between semgrep CI and semgrep CLI, see it here: [`develop`/semgrep/semgrep/templates/.semgrepignore](https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/templates/.semgrepignore?rgh-link-date=2022-01-12T20%3A09%3A07Z)
> 
> we'll do better about updating the output, tracking here: #1964 and I'm going to ask the team to prioritize this and #1964

No worries, I *did* skip the release notes so fair enough.

In case the release notes are editable, maybe a note should be made of how to resolve to the old behaviour? I assume an empty .semgrepignore would do the trick?

**Comment by emjin** [comment]
We're adding that to the docs (https://github.com/returntocorp/semgrep-docs/pull/400) and linking the docs in the `--verbose` output. Hopefully this will make it discoverable! (And yes, an empty .semgrepignore will work)

**Comment by emjin** [comment]
Fixed by @underyx!
