### ISSUE TITLE
PHP - Taint - Using sink such as require leads to semgrep error

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3245]
**Describe the bug**
In taint mode, with the PHP language, using a sink such as `require(...)` raises a semgrep error: `Pattern id from semgrep-core was missing in pattern spans.`. All other PHP inclusion sinks are also affected

**To Reproduce**
https://semgrep.dev/s/kLqz

**Expected behavior**
Semgrep should not error

**What is the priority of the bug to you?**
P2

**Comment by IagoAbal** [comment]
The main issue is that `include(...)` is not accepted as a Semgrep pattern: https://semgrep.dev/s/R812/

**Comment by IagoAbal** [comment]
> The main issue is that `include(...)` is not accepted as a Semgrep pattern: https://semgrep.dev/s/R812/

Note that the status of PHP support is alpha, and in particular `...` are not yet allowed in every place where they could make sense. But you can aways use a metevariables instead, e.g. https://semgrep.dev/s/AlR6/. However your example still doesn't work https://semgrep.dev/s/B4A9/.

**Comment by erwanlr** [comment]
Ohhhhh, so that's because of the `...` in the end :o

The search mode and metavariables regex is what I am doing currently, but it's not really maintainable to consider every (real case) possibilities (and sanitisation as well).

My example was a dummy one, but it appears to work on real case ones with the metavariable trick, so will change the priority of the issue from P0 to P2 :)

Thanks again!

**Comment by IagoAbal** [comment]
> However your example still doesn't work https://semgrep.dev/s/B4A9/.

I am not sure what happened, but it does work now. Maybe it was something wrong with the Playground.

**Comment by erwanlr** [comment]
Thanks for the update!

In the test cases (https://github.com/returntocorp/semgrep/pull/3286/files), shouldn't it be `echo "...";` instead of `echo ...;` (and same for the other `...` basically) ? Based on other patterns (like in search mode), I would not expect `echo ...;` to match `echo 'test';` but rather `echo $something;`

**Comment by IagoAbal** [comment]
`...` matches "anything", whereas `"..."` matches _any string literal_ (modulo constant propagation), so `echo ...` matches `echo 'test'` and also `echo $something`, whereas `echo "..."` matches `echo 'test'` but not `echo $something`.
