### ISSUE TITLE
Investigate GitLab SAST CI/CD timeouts

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3263]
We've found the following GitLab SAST CI jobs timing out:

- https://gitlab.com/Yrkki/cv-generator-fe/-/jobs/1280773458
- https://gitlab.com/sia-insa-lyon/dev/portailva-2/portailva-website/-/jobs/1311413602
- https://gitlab.com/gitlab-org/status-page/-/jobs/1314483231
- https://gitlab.com/gitlab-org/monitor/sandbox/splattael-status-page/-/jobs/1282811227

Let's investigate what's making them take so long to run.

**Comment by emjin** [comment]
I looked at one and it still timeouts :(
