### ISSUE TITLE
document quote-sensitive behavior in JavaScript

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3280]
Reporting on behalf of an external user. JavaScript object matching appears to be sensitive to quotes in strange ways. Eg., searching for `"$KEY": "$VALUE"` doesn't work, but searching for $KEY: $VALUE does.

`$KEY: $VALUE` matches: https://semgrep.dev/s/2b25
`"$KEY": $VALUE` matches: https://semgrep.dev/s/jNPA
`"$KEY": "$VALUE"` doesn't match: https://semgrep.dev/s/KWBd <- unexpected

We should edit documentation to explain what to expect around "$VAR". 

~I would expect that searching for "$KEY" does work and binds $KEY to the contents of the key _without_ the surrounding quotes.~

Semgrep v.0.54.0

**Comment by aryx** [comment]
yep we don't support metavariable inside strings. You can just do "..." inside strings.

**Comment by aryx** [comment]
We may accept them for keys in dictionnaries because those keys are treated specially; they are not regular strings, they
are object fields.

**Comment by ievans** [comment]
Thanks for clarifying @aryx. I think the ticket should then be to update the docs so that this behavior is clear for users

**Comment by emjin** [comment]
@ievans Is this still an issue? Looks like a relevant PR was merged.

**Comment by ievans** [comment]
agreed, verified fixed!
