### ISSUE TITLE
Implement debugging-json in semgrep-core

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3296]
This will allow us to properly turn on optimizations all

**Comment by brendongo** [comment]
Playground will run with optimizations off unless the debugger is on so not high priority anymore but still necessary before we delete old code paths

**Comment by emjin** [comment]
Still something we want to do, though perhaps in a different form

**Comment by emjin** [comment]
.

**Comment by aryx** [comment]
@zyannes was working on it during his hack week.

**Comment by aryx** [comment]
Solved! https://github.com/returntocorp/semgrep/pull/5898
