### ISSUE TITLE
`enumerate` in python confuses constant propagation

### ISSUE THREAD

**Issue by ankush** [semgrep/semgrep#3306]
**Describe the bug**
When `enumerate` is used the constant propagation isn't working as expected.

**To Reproduce**
https://semgrep.dev/s/KW5d/

rule: `$X is $X`
```python
def func():
    index = None
    for i, num in enumerate([1,2,3]):
        if num == 2:
            index = i
            break
    # ok: identical-is-comparison
    if index is None: 
        index = 4
```

**Expected behavior**
Use of `enumerate` shouldn't change the behaviour.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Reproducible in most environments.

**Comment by IagoAbal** [comment]
Thanks for the bug report! This problem was previously reported in #3155, resolved by #3254, and the fix is already in Semgrep 0.55.1.
