### ISSUE TITLE
Unexpected reported locations in 0.55.0

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3315]
**Describe the bug**
A code change resulted in different locations reported by Semgrep in 0.55.0. Need to investigate why, as this is not expected.

See https://github.com/returntocorp/semgrep/pull/3312.

https://github.com/returntocorp/semgrep-app/pull/2675/files/208152566bbeacb0e0ac88dd13f308c23fca2fcd#r647864400 is also relevant.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by minusworld** [comment]
Prior debugging suspects this to be in the Python wrapper.

Here's a snippet that reports wrong numbers:

> The semgrep output for the same pattern and target has the wrong end location:
```
$ semgrep --lang generic -e "$(cat semgrep-core/tests/generic/metavar_equality_var.sgrep)" semgrep-core/tests/generic/metavar_equality_var.generic --json | ydump
ran 1 rules on 1 files: 1 findings
{
  "errors": [],
  "results": [
    {
      "check_id": "-",
      "end": { "col": 91, "line": 4 },
      "extra": {
        "is_ignored": false,
        "lines": "    myfile = open();",
        "message": "myfile = open();\n...\nclose(myfile);",
        "metadata": {},
        "metavars": {
          "$V": {
            "abstract_content": "myfile",
            "end": { "col": 11, "line": 4, "offset": 50 },
            "start": { "col": 5, "line": 4, "offset": 44 },
            "unique_id": {
              "md5sum": "cae9896c1cfb594832dddb6657a38284",
              "type": "AST"
            }
          }
        },
        "severity": "ERROR"
      },
      "path": "semgrep-core/tests/generic/metavar_equality_var.generic",
      "start": { "col": 5, "line": 4 }
    }
  ]
}
```

^ based on this thread: https://returntocorp.slack.com/archives/C6A1GN4P3/p1623198872464500?thread_ts=1623197143.460000&cid=C6A1GN4P3

**Comment by brendongo** [comment]
Tracked down the offending PR https://github.com/returntocorp/semgrep/pull/3293
Looks like using optimizations --all by default causes this error.

**Comment by minusworld** [comment]
If it’s relevant, it goes all the way back to 0.49.0, which is when --optimizations was exposed

**Comment by minusworld** [comment]
Potentially this line? https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/src/engine/Match_rules.ml#L480

This is what spacegrep outputs on the test sample above:

```
➜  semgrep git:(develop) ✗ spacegrep --debug -d semgrep-core/tests/generic/metavar_equality_var.generic "$(cat semgrep-core/tests/generic/metavar_equality_var.sgrep)"
parse document: semgrep-core/tests/generic/metavar_equality_var.generic
match document from semgrep-core/tests/generic/metavar_equality_var.generic against pattern from <string>
pat Metavar V : doc Word 'class'
[... trimmed ...]
match from ({lnum=4, bol=40, cnum=44}, {lnum=4, bol=40, cnum=50}) to ({lnum=9, bol=110, cnum=129}, {lnum=9, bol=110, cnum=130})
semgrep-core/tests/generic/metavar_equality_var.generic:    myfile = open();
semgrep-core/tests/generic/metavar_equality_var.generic:    try {
semgrep-core/tests/generic/metavar_equality_var.generic:      foo(myfile);
semgrep-core/tests/generic/metavar_equality_var.generic:    }
semgrep-core/tests/generic/metavar_equality_var.generic:    finally {
semgrep-core/tests/generic/metavar_equality_var.generic:      close(myfile);
```

Looks like maybe the wrong `bol` is getting used? I think the right number for the `end` in this test case is 21, which can be gotten with the final entry: `cnum=130 - bol=110 + 1 => 21`. Conversely, 91 is gotten with `cnum=130 - bol=40 + 1 => 91`
