### ISSUE TITLE
[ruby] Constant propagation ignores side-effects on string object

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3316]
**Describe the bug**
Constant propagation incorrectly flags a variable as constant after it has been modified by a method call.

**To Reproduce**
https://semgrep.dev/s/4y19/

**Expected behavior**
No false positives.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by IagoAbal** [comment]
Some amount of false positives of this kind are expected since we only do intra-procedural analysis, and if we assume that _anything_ can alter the value of a variable then we would also miss many true positives. But in this particular case I think the intention to modify the variable is clear and we should handle it.

**Comment by IagoAbal** [comment]
Actually this is mainly due to AST-to-IL not recognizing a call to the `concat` method as the `Concat` operation.

**Comment by emjin** [comment]
@mmcqd Might be a good issue for you
