### ISSUE TITLE
Support for Clojure

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#3328]
**Is your feature request related to a problem? Please describe.**
Given the current state of Clojure security tools, having semgrep would be a great addition into the ecosystem.

HN Thread: https://news.ycombinator.com/item?id=24929993
CRUSH, a code review tool that could inspire some rules.
- https://jemurai.com/2020/01/15/oss-crush/
- https://github.com/Jemurai/crush

**Describe the solution you'd like**
Parsing support for Clojure and some initial rules

**Describe alternatives you've considered**
None, there is just this really low-level tool for now https://github.com/clojure/tools.analyzer

**Comment by DrewDennison** [comment]
https://github.com/sogaiu/tree-sitter-clojure and https://github.com/oakmac/tree-sitter-clojure both exist and if they have reasonable coverage. It shouldn't be too hard to add in

**Comment by aryx** [comment]
There's also https://github.com/SergeevPavel/tree-sitter-clojure and https://github.com/Tavistock/tree-sitter-clojure
Which one to choose?

**Comment by aryx** [comment]
https://github.com/sogaiu/tree-sitter-clojure seems to be the most up-to-date and maintained

**Comment by aryx** [comment]
hopefully this will help for other lisp dialects

**Comment by sogaiu** [comment]
Hi @aryx and any other interested folks,

This is just an FYI from sogaiu/tree-sitter-clojure maintainers.

We made some changes recently as described [here](https://github.com/sogaiu/tree-sitter-clojure/issues/33#issuecomment-1362363845).  The short of it is that we fixed one issue and enhanced functionality a bit.

We noticed the [`parser.c` here](https://github.com/returntocorp/semgrep-clojure/blob/main/lib/parser.c) might be a slightly older version than what we have currently (this is a guess based on noticing that it doesn't mention `sym_ns` or `sym_name`).

Our most recent efforts have those bits: https://github.com/sogaiu/tree-sitter-clojure/blob/master/src/parser.c#L109-L110

May be there is some interest in using the more recent version?

We're trying to make an effort to keep users of the grammar / parser informed about potential changes in an effort to mitigate breakage and such.  If there is interest in that sort of thing, please consider subscribing to [this issue](https://github.com/sogaiu/tree-sitter-clojure/issues/33).

Thanks!

---

P.S. As mentioned earlier in this issue, there are / have been multiple efforts for handling Clojure.  If interested in other alternatives, there are a few others listed here: https://github.com/tree-sitter/tree-sitter/pull/1980

However, at this time, as far as we are aware, other efforts are not active -- but this is partly speculation.

**Comment by aryx** [comment]
Thanks for the heads up! We usually update to the latest of a tree-sitter-xxx when they handle new constructs of the grammar,
so I don't think we gonna update now, but will keep in mind your change next time we need to update.
Oh and thanks for tree-sitter-clojure!

**Comment by aryx** [comment]
I'm gonna close @Gby56 . I think semgrep now has basic support for clojure. We can create a separate issue
for porting the rules of the existing clojure linters.

```
semgrep -l clojure -e '(foo ...)' ~/yy/tests/patterns/clojure/
Scanning 9 files.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|9/9 tasks

Findings:

  /home/pad/yy/tests/patterns/clojure/concrete_syntax.clj 
          3┆ (foo 1 2)
          ⋮┆----------------------------------------
          6┆ (foo 1
          7┆      2)
          ⋮┆----------------------------------------
         10┆ (foo 1 ; comment
         11┆      2)
          ⋮┆----------------------------------------
         13┆ (foo 2 1)


  /home/pad/yy/tests/patterns/clojure/dots_args.clj 
          3┆ (foo 1 2 3 4 5)
          ⋮┆----------------------------------------
          5┆ (foo 5)


  /home/pad/yy/tests/patterns/clojure/dots_string.clj 
          3┆ (foo "whatever sequence of chars")


  /home/pad/yy/tests/patterns/clojure/metavar_arg.clj 
          3┆ (foo 1 2)
          ⋮┆----------------------------------------
          6┆ (foo a_very_long_constant_name
          7┆      2)
          ⋮┆----------------------------------------
         10┆ (foo (unsafe()) ; indeed
         11┆      2)
          ⋮┆----------------------------------------
         14┆ (foo (bar 1 3) 2)
          ⋮┆----------------------------------------
         16┆ (foo 2 1)


  /home/pad/yy/tests/patterns/clojure/metavar_call.clj 
          3┆ (foo 1 2)
          ⋮┆----------------------------------------
          5┆ (foo 2 1)

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 1 rule on 9 files: 14 findings.

```

**Comment by sogaiu** [comment]
@aryx Thanks for the response.

Regarding:

> We usually update to the latest of a tree-sitter-xxx when they handle new constructs of the grammar, so I don't think we gonna update now, but will keep in mind your change next time we need to update.

Ah I see.  Thanks for the explanation.

Just want to make sure you understand that this update has a fix for a bug (https://github.com/sogaiu/tree-sitter-clojure/issues/21) reported by the folks at [difftastic](https://github.com/Wilfred/difftastic).
