### ISSUE TITLE
[Ruby] Strings and command shells are confused by the parser

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#3343]
**Describe the bug**

I'm looking for shell invocations and semgrep flags regular strings.

**To Reproduce**

https://semgrep.dev/s/WgJE/

**Expected behavior**

The above repro shouldn't have any matches in the `notvuln` function

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by dee-see** [comment]
Forgot to mention that the rule comes from https://github.com/returntocorp/semgrep-rules/blob/develop/ruby/lang/security/dangerous-subshell.yaml

**Comment by dee-see** [comment]
Yay, thanks team :)

**Comment by dee-see** [comment]
Hmm might have celebrated too early.

My repro in the original description now crashes with `Semgrep exited with an unspecified error` https://semgrep.dev/s/WgJE/?version=develop

@mjambon

**Comment by dee-see** [comment]
Also tagging @emjin, just realized `@mjambon` approved the MR but didn't do the implementation my bad

**Comment by emjin** [comment]
Hm, it's working for me. Can you try refreshing? Sometimes updating the docker image has a little lag, and we have to refresh 1 or more times.

**Comment by dee-see** [comment]
Indeed it works now, sorry for the false alarm. Thanks!

**Comment by mjambon** [comment]
😅
