### ISSUE TITLE
C# does not search for method attributes

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#3348]
When I specify a method attribute in a query, it is ignored:

```
semgrep --lang cs -e '[Something] public $RET $NAME() { ... }'
```

This returns all public methods. I expect it to return only methods with the "Something" attribute.

I am using semgrep 0.55.1. It seems [method attributes are already being parsed](https://github.com/returntocorp/semgrep/blob/8d6399ad897b13edb8c00a8a443771f704799ea1/semgrep-core/src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml#L2787). Does something needs to happen before these are used in the query?

**Comment by aryx** [comment]
You can save the pattern in a file foo.sgrep, and do semprep-core -lang csharp -dump_pattern foo.sgrep
to check whether the attribute in indeed in the AST.

**Comment by Sjord** [comment]
It isn't:

```
$ semgrep-core -lang csharp -dump_pattern pattern                                          
S(
  DefStmt(
    ({
      name=EN(
             Id(("$NAME", ()),
               {id_resolved=Ref(None); id_type=Ref(None); 
                id_constness=Ref(None); }));
      attrs=[KeywordAttr((Public, ()))]; tparams=[]; },
     FuncDef(
       {fkind=(Method, ()); fparams=[]; 
        frettype=Some(TyN(
                        Id(("$RET", ()),
                          {id_resolved=Ref(None); id_type=Ref(None); 
                           id_constness=Ref(None); })));
        fbody=Block([ExprStmt(Ellipsis(()), ())]); }))))
```

It seems the pattern is interpreted as local function, not as method. This makes some sense, since it isn't in a class. And local functions don't get attributes yet, because of [the attributes are in `vtodo` and not yet used](https://github.com/returntocorp/semgrep/blob/8d6399ad897b13edb8c00a8a443771f704799ea1/semgrep-core/src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml#L1702).

```
  | `Local_func_stmt (vtodo, v1, v2, v3, v4, v5, v6, v7) ->
```

I'll make a PR to handle this `vtodo`. I am pretty sure that solves this.
