### ISSUE TITLE
Upgrade TypeScript parser monthly - June 2021

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3350]
We're planning to use the typescript parser to parse javascript, so this upgrade will take care of javascript as well if everything goes according to plan.

**Comment by zbuc** [comment]
Would it be possible to pull in https://github.com/tree-sitter/tree-sitter-javascript/pull/177 as part of this? It's preventing us from using the latest semgrep versions because our codebase contains private fields. We're running semgrep v0.14.0 as a result, which has a lot of missing features.

**Comment by mjambon** [comment]
@zbuc sorry, I didn't realize you were blocked. Getting back to this now.

**Comment by mjambon** [comment]
done!
