### ISSUE TITLE
Inconsistent findings between playground and cli/docker when using metavariable to represent import alias

### ISSUE THREAD

**Issue by nafiz1001** [semgrep/semgrep#3357]
**Describe the bug**
The semgrep findings are different between the Playground and CLI/Docker when using metavariable to represent import alias.

**To Reproduce**
4 findings (2 false positives), same for "Use develop docker image" toggled on: <https://semgrep.dev/s/xedL/>
2 findings: 
```bash
git clone https://github.com/returntocorp/semgrep-rules.git
cd semgrep-rules
git checkout eba59426659d3e4a47dcd2c56d22e442c545204d
curl -LO https://github.com/nafiz1001/semgrep-rules/commit/0bbcdfc19e9bae1b9418e360b4b25d5b69c4fb18.diff
git apply 0bbcdfc19e9bae1b9418e360b4b25d5b69c4fb18.diff
sudo docker run --rm -v "${PWD}":/src returntocorp/semgrep:develop '--config=/src/go/lang/security/audit/crypto/math_random.yaml' '/src/go/lang/security/audit/crypto/math_random.go'
```

**Expected behavior**
2 findings at line 17 and 29

**Diffs**
This is my diff to introduce metavariable for import alias
```diff
diff --git a/go/lang/security/audit/crypto/math_random.yaml b/go/lang/security/audit/crypto/math_random.yaml
index 36be704a..b3565f0c 100644
--- a/go/lang/security/audit/crypto/math_random.yaml
+++ b/go/lang/security/audit/crypto/math_random.yaml
@@ -12,11 +12,11 @@ rules:
   pattern-either:
   - patterns:
     - pattern-inside: |
-        import mrand "math/rand"
+        import $MRAND "math/rand"
         ...
     - pattern-either:
-      - pattern: mrand.Int()
-      - pattern: mrand.Read(...)
+      - pattern: $MRAND.Int()
+      - pattern: $MRAND.Read(...)
   - patterns:
     - pattern-inside: |
         import "math/rand"
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
I tested it in on playground and in docker

**Comment by ievans** [comment]
@nafiz1001 We re-release docker images a lot (every merge to main branch). Can you share the tag of the image that had the issue? Right now 
https://semgrep.dev/s/xedL/?version=develop is at docker tag `4bec5b915b7b` and I only see two findings -- which is what you were hoping for!

If you did see an issue, it's probably the propagation delay of the new image making it into the playground. Will close as cannot-reproduce unless you think there's something else going on, feel free to reopen?
