### ISSUE TITLE
Ruby Regex Matching

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3372]
**Describe the bug**
Ruby regex matching does not match equating a string constant with a regex. 
In
https://semgrep.dev/s/KWj5/ 
the expectation is that the pattern will match both regex expressions.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by aryx** [comment]
Not sure if that's what the user wanted, but you can now use metavariable in regexps, and even ..., as in `foo(/.../)`

See https://semgrep.dev/s/grx0/?version=develop

**Comment by aryx** [comment]
Or https://semgrep.dev/s/Q4rZ/?version=develop
