### ISSUE TITLE
Semgrep commands are autocomplete-able

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#3373]
**Is your feature request related to a problem? Please describe.**
Autocomplete was a delightful feature in our past project [Bento](https://github.com/returntocorp/bento). It aided discoverability of commands and made the tool fast to use. This ticket is a request to provide this functionality for Semgrep, allowing me to tab autocomplete and see relevant flags and their help text as I go.

**Describe the solution you'd like**
The AWS CLI, Bento, and others do a good job of this!

**Describe alternatives you've considered**
Not providing this feature. The tool is still useful, but can be challenging to discover it's capabilities and sub options.

**Comment by emjin** [comment]
@nbrahms Closed by click?

**Comment by emjin** [comment]
.
