### ISSUE TITLE
semgrep --lang=kotlin not accepted by semgrep-core

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3392]
When trying to run a kotlin rule with language set to `kotlin`, I get the following:

> unsupported language: kotlin was accepted by semgrep but rejected by semgrep-core. An error occurred while invoking the semgrep engine; please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

cc @colleend

**Comment by colleend** [comment]
good catch, currently kotlin is supported as `kt` in semgrep-core, we can also make it support `kotlin` 👍

**Comment by aryx** [comment]
Can you fix that @colleend ? seems like a small diff.

**Comment by colleend** [comment]
can do 👍

**Comment by aryx** [comment]
just tried ```semgrep --lang=kotlin -e 'foo(...)' kotlin/```
and it works, so closing.
