### ISSUE TITLE
Browser history cache entries updated incorrectly

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#3394]
**Describe the bug**
With the new UX in the web registry, the browser history is nullified, and hence the backward/forward navigation amongst pages is lost.

**To Reproduce**
(1) Start from semgrep.dev/explore **on a new tab**, then select a ruleset:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/6817500/122684573-fafdee80-d1ba-11eb-8dc3-3bd3b457e59c.png">

(2) Observe that the URL changes and the page change is logged in the browser history:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/6817500/122684605-241e7f00-d1bb-11eb-9499-f399407bc33b.png">

(3) Scroll to the bottom and select the next page of results:
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/6817500/122684643-68aa1a80-d1bb-11eb-8999-7be46e0465ba.png">

(4) Observe that the page number correctly increments (1) then press the browser back button (2):
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/6817500/122684852-dc005c00-d1bc-11eb-82df-daa6dfef4cb8.png">

(5) Observe that the page number correctly decrements (1), the URL remains unchanged (2), but the back button is now disabled (3), indicating NO page history. I cannot get back to semgrep.dev/explore.
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/6817500/122684916-3a2d3f00-d1bd-11eb-9ed9-d73d75d0d9bb.png">

It is arguable whether the URL should update when using the page navigation bar --
<img width="204" alt="image" src="https://user-images.githubusercontent.com/6817500/122684968-92fcd780-d1bd-11eb-8819-d11f5d5ade05.png"> -- one could make a case either way -- but we should **not** be losing the prior page in the history, (the semgrep.dev/explore URL).

Note that it is important to start with a new tab in step (1), otherwise there will be prior page history and the browser back button does not become disabled in step (5). (The history problem is still there for the semgrep pages, but you won't see it in the enabled state is all.)

**Expected behavior**
Browser page navigation needs to work more intuitively.

**Screenshots**
Above.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by nbrahms** [comment]
Maybe even more minimal:

1. Open a new tab
2. Navigate to a semgrep.dev/explore
3. Click a ruleset
4. Hit the back button

You'll end up on the new tab's splash screen instead of `/explore`.

My guess at RCA is that we are incorrectly linking when clicking on the ruleset card from `/explore`.

**Comment by nbrahms** [comment]
@msorens Thanks for the issue! I've submitted a fix and it should be out within the next couple days.
