### ISSUE TITLE
Export as CSV, HTML

### ISSUE THREAD

**Issue by CityOfLight77** [semgrep/semgrep#3395]
When I scan a project I found 500+ issues and I can't see all results in terminal.
So I would like to see an option to export scan result to csv/html format

**Comment by minusworld** [comment]
Hey @CityOfLight77! Thanks for the request!

Currently, you can use the `-o` or `--output` flag to save results to a file. We support a text-based output, JSON with the `--json` flag, XML j-unit output with `--junit-xml`, and [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html) output with `--sarif`.

If you're specifically asking for CSV or HTML output, I can change the ticket title to reflect that. Thanks!

**Comment by CityOfLight77** [comment]
Yes, please change the title to export csv/html format

**Comment by Sjord** [comment]
One method to conveniently view semgrep output is to export to SARIF and then use the [SARIF viewer](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer) plugin in Visual Studio Code. There you can open the SARIF file and even navigate directly to the correct code location.

For CSV and HTML output, it would also make sense to use SARIF as intermediate. I.e. create a SARIF -> HTML converter. That way, we would only need one conversion tool that works with every code analysis tool that supports SARIF.
