### ISSUE TITLE
Take advantage of running whole rule in OCaml for speed

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3396]
There are a number of optimizations enabled by whole rule in OCaml which we can implement now. Currently, my plan is to work towards a goal of achieving 5 minute p95 runtime for r/security-audit, but I will timebox this to July 21.

https://r2c.quip.com/MKq4AAOCVzSi/Improving-whole-rule-in-OCaml

**Comment by mschwager** [comment]
Can we close this one out? :tada:

**Comment by IagoAbal** [comment]
This has been stale for a while and we have realized that our perf bottleneck is parsing. I would say this is now low priority.

**Comment by emjin** [comment]
I'm going to close this and make any performance improvements as a part of a different story. Things that may still be worth doing

- Improve -filter-irrelevant-rules 
- Cache matches between rules
