### ISSUE TITLE
semgrep-core takes 2 seconds to start up

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3397]
I ran `semgrep` and timed `semgrep-core`.

The first time I ran `semgrep`, `semgrep-core` took 2+ seconds. In subsequent runs, `semgrep-core` took 0.7 seconds (these numbers are from memory). Should investigate

**Comment by aryx** [comment]
I also got once this issue, and it's really hard to know why.
Please @emjin can you describe your enviromnent: OS, ocaml version.
semgrep-core --help should take no more than 0.1 second.

I tried strace on semgrep-core to investigate a bit, and got some weird file introspection.

**Comment by emjin** [comment]
I'm using a MacOS (Big Sur), 4.10.0

**Comment by IagoAbal** [comment]
@emjin
> The first time I ran semgrep, semgrep-core took 2+ seconds. 

Have you been able to reproduce this behavior by running `semgrep-core` directly? Could you help me reproducing this?

**Comment by emjin** [comment]
Just now, having stepped away for lunch, I ran `time semgrep-core --help`, and it took over a second. I got `semgrep-core --help  0.08s user 0.02s system 7% cpu 1.299 total`. 

The next time I ran it, I got `semgrep-core --help  0.10s user 0.03s system 97% cpu 0.133 total`.

It looks to me like the `system 7%` may be the cause? I don't know why that difference exists

**Comment by IagoAbal** [comment]
> I'm using a MacOS (Big Sur), 4.10.0

When time allows, could you upgrade to 4.10.2 and try to reproduce it? I built semgrep-core with 4.10.2 and I'm not able to reproduce this.

**Comment by emjin** [comment]
Ooh, that might have worked! I'll try again to confirm after I haven't touched the command line for a bit.

**Comment by emjin** [comment]
Yup, on 4.10.2 it doesn't happen!

**Comment by aryx** [comment]
Do we know what was fixed between 4.10.0 and 4.10.2 that fixed the issue?
I also experience slow startup time in other ocaml programs, but  it's not very deterministic. I add a new file to link in
and boom the startup goes to 2s.

**Comment by IagoAbal** [comment]
I could not find an obvious cause by looking at the release notes of 4.10.1 or 4.10.2. @aryx do you experience this with 4.10.2 on Linux?
