### ISSUE TITLE
Differing behavior under semgrep-action

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3398]
**Describe the bug**
Semgrep running under semgrep-action fires on a line of go code that doesn’t repro locally or in playground.

The rule in question: https://github.com/dgryski/semgrep-go/blob/master/badnilguard.yml

reported by @echlebek 

**To Reproduce**
https://gist.github.com/echlebek/afc24b331fc53482c05ce62da643b10a

**Expected behavior**
No match, as seen in this example: https://semgrep.dev/s/8Rny

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep-action

**Comment by nbrahms** [comment]
See https://semgrep.dev/s/grJJ

@IagoAbal looks like commutivity assumptions clash with c-style evaluation order semantics here

**Comment by ievans** [comment]
Closing in favor of https://github.com/returntocorp/semgrep/issues/3399
