### ISSUE TITLE
semgrep-core slow startup and/or slow stack trace collection and/or big binaries

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3405]
[please add details if you have any]

On Linux, with the ocaml 4.10.0, `semgrep-core` takes about 2 seconds of active CPU time to obtain a stack trace (`Printexc.get_backtrace ()`) when an exception is caught. We don't know what causes this. It can be reproduced by adding code the `Main.ml` that simply raises an exception, catches it, calls `Printexc.get_backtrace ()`, and exits.

On MacOS, a startup time of about 2 seconds was observed, but not on Linux. We don't know what might be causing this either or if it has anything to do with the stack trace collection slowness.

We suspect this may have been introduced when we started using a library, possibly something intrusive/invisible like a ppx extension.

Plan: observe what functions get called during the 2 seconds that it takes for `Printexc.get_backtrace ()` to return. The `perf` program might be useful for this.

**Comment by mjambon** [comment]
I'm not sure if this is a problem for typical use of semgrep. It could be if for example `Printexc.get_backtrace ()` is called for many files that fail to parse and that call takes a long time every time. It's possible that it's slow only the first time. More data is needed.

**Comment by mschwager** [comment]
Looks related to https://github.com/returntocorp/semgrep/issues/3397.

**Comment by aryx** [comment]
I'm being hit by this with https://github.com/returntocorp/semgrep/pull/3509
If you update to ppxlib 0.20.0, then suddenly Main.exe take more than 2s with ocaml 4.10.0 (also 4.09.1), but not 4.12.0.

**Comment by aryx** [comment]
This is on Linux.

**Comment by aryx** [comment]
By having a 2s semgrep-core startup time, the CI time goes from 4m to 40min ...

**Comment by aryx** [comment]
See the CI job here: https://github.com/returntocorp/semgrep/pull/3509

**Comment by aryx** [comment]
I don't have the problem with 4.10.2

**Comment by aryx** [comment]
cc @IagoAbal

**Comment by aryx** [comment]
if I strace semgrep-core, it looks like it's waiting 2sec in a call to
wait4(-1, ...)

**Comment by aryx** [comment]
with 4.10.2, there is also this call to wait4, but it returns immediately

**Comment by aryx** [comment]
I did a diff on the 2 strace (one with 4.10.0 and one with 4.10.2) but don't see anything that different. except one wait4 takes 2s and the other 0.1s

**Comment by aryx** [comment]
Also weird, the size of Main.exe (semgrep-core) in 4.10.0 is 178MB, in 4.10.2 it's 46MB!
With the same libraries ...

**Comment by emjin** [comment]
Woah that's really interesting, and probably relevant

**Comment by emjin** [comment]
What does `wait4` do? (Or what is it being called on, if that's the better question?)

**Comment by aryx** [comment]
according to the man page it's waiting for any children (when passed the -1 as a first argument).

**Comment by aryx** [comment]
But like I said, in 4.10.2 there's also this call to wait4, except it succeeds immediately.

**Comment by aryx** [comment]
Note that switching to 4.10.2 (or 4.12.0) improves things for Main.exe, but Main.bc (the bytecode version)
is actually worse off in recent OCaml versions. The startup time of Main.bc is 2.5s with 4.12.0

**Comment by aryx** [comment]
Also not sure if it happens to other, but I don't get anymore backtraces with ocaml 4.12.0 :(
```
 /home/pad/yy/_build/default/src/cli/Main.exe whatever
[0.120  Info       Main.Dune__exe__Main ] loaded log_config.json
[0.120  Info       Main.Dune__exe__Main ] Executed as: /home/pad/yy/_build/default/src/cli/Main.exe whatever
[0.120  Info       Main.Dune__exe__Main ] Version: semgrep-core version: v0.58.0-5-g7a11463e, pfff: 0.42
Uncaught exception:
  
  (Failure "no language specified; use -lang")

Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location
Called from unknown location

```

**Comment by aryx** [comment]
I do get the correct backtrace with Main.bc
```
./_build/default/src/cli/Main.bc whatever
[2.566  Info       Main.Dune__exe__Main ] loaded log_config.json
[2.566  Info       Main.Dune__exe__Main ] Executed as: ./_build/default/src/cli/Main.bc whatever
[2.566  Info       Main.Dune__exe__Main ] Version: semgrep-core version: v0.58.0-5-g7a11463e, pfff: 0.42
Uncaught exception:
  
  (Failure "no language specified; use -lang")

Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Dune__exe__Main.main.(fun) in file "src/cli/Main.ml", line 1504, characters 25-45
Called from Common.finalize in file "src/pfff/commons/Common.ml", line 97, characters 14-18
Re-raised at Common.finalize in file "src/pfff/commons/Common.ml", line 102, characters 4-11
Called from Common.main_boilerplate.(fun) in file "src/pfff/commons/Common.ml", line 1391, characters 12-16
Re-raised at Common.main_boilerplate.(fun) in file "src/pfff/commons/Common.ml", line 1389, characters 8-301
Called from Common.pp_do_in_zero_box in file "src/pfff/commons/Common.ml", line 1359, characters 45-49
Called from Common.finalize in file "src/pfff/commons/Common.ml", line 97, characters 14-18
Re-raised at Common.finalize in file "src/pfff/commons/Common.ml", line 102, characters 4-11
Called from Common.exn_to_real_unixexit in file "src/pfff/commons/Common.ml", line 1356, characters 6-10
Re-raised at Common.uniq_by.(fun) in file "src/pfff/commons/Common.ml", line 1330, characters 43-54
Called from Dune__exe__Main in file "src/cli/Main.ml", line 1522, characters 2-148
```
but then the startup time is 2.5sec,
argh

**Comment by aryx** [comment]
OMG ... https://returntocorp.slack.com/archives/C01NXGX2EHZ/p1626346551300100
it was because Main.exe was actually a bytecode-compiled with ocamlrun included ...
We have been shipping bytecode programs all this time!

**Comment by aryx** [comment]
Ok we still don't fully understand why things were going slow with the old Main.exe in 4.10.0, but
with a real native Main.exe, things are now better (good startup, small binary size, good backtrace), so let's close this.
