### ISSUE TITLE
Constness analysis is very slow on very large functions

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3410]
**To Reproduce**
```
parsing-stats$ ../semgrep-core/bin/semgrep-core -lang csharp -dump_named_ast lang/csharp/tmp/aspnetcore/src/Http/Routing/perf/Microbenchmarks/Matching/MatcherAzureBenchmarkBase.generated.cs
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by mjambon** [comment]
Here's how I found it:
```
cd parsing-stats
./run-lang csharp
```
You can run it for other languages and see if you get a similar problem. I just copied the `develop` branch into `parsing-stats`, which triggers a parsing-stats job for all languages in CircleCI. You [can download the log](https://app.circleci.com/pipelines/github/returntocorp/semgrep/4512/workflows/1e996a8e-dcf0-4240-85a7-fca5ee739f40/jobs/6142) if that helps.

**Comment by aryx** [comment]
please copy the offending file in semgrep-core/perf/input/lxxxx.cs so we can quickly reproduce (and maybe add it as a part
of perf regression testing, see semgrep-core/perf/run-perf-suite)

**Comment by IagoAbal** [comment]
> please copy the offending file in semgrep-core/perf/input/lxxxx.cs so we can quickly reproduce (and maybe add it as a part
> of perf regression testing, see semgrep-core/perf/run-perf-suite)

The file is part of a microbenchark for aspnetcore, the problematic function looks like this:
```
        private protected void SetupRequests()
        {
            Requests = new HttpContext[5160];
            Requests[0] = new DefaultHttpContext();
            Requests[0].RequestServices = CreateServices();
            Requests[0].Request.Method = HttpMethods.GetCanonicalizedValue("GET");
            Requests[0].Request.Path = "/account";
            Requests[1] = new DefaultHttpContext();
            Requests[1].RequestServices = CreateServices();
            Requests[1].Request.Method = HttpMethods.GetCanonicalizedValue("POST");
            Requests[1].Request.Path = "/analyze";
            Requests[2] = new DefaultHttpContext();
            Requests[2].RequestServices = CreateServices();
            Requests[2].Request.Method = HttpMethods.GetCanonicalizedValue("GET");
            Requests[2].Request.Path = "/apis";
            Requests[3] = new DefaultHttpContext();
            Requests[3].RequestServices = CreateServices();
            Requests[3].Request.Method = HttpMethods.GetCanonicalizedValue("GET");
            Requests[3].Request.Path = "/Applications";
           ... // up to Request[5159], so about ~20kLOC in total
```
Do you still want to add it to `perf/input` ?

**Comment by mjambon** [comment]
Not sure what you did eventually. An option to avoid keeping a huge file around is to shrink it so that the old constant propagation takes 5-10 seconds. We'd make the test fail if it takes over a second or so.

**Comment by IagoAbal** [comment]
Sure I can add a shrink'ed version of it. I was somewhat in doubt because it is not a realistic example, but it's not much work to add It anyways.
