### ISSUE TITLE
Add support for Java varags

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#3417]
**Is your feature request related to a problem? Please describe.**
In this example https://semgrep.dev/s/YX8W (need to quote the semgrep pattern) we are trying to match `double...`, but not `double[]`. Maybe it is possible, but we couldn't find it in the docs.

**Describe the solution you'd like**
Being able to match varargs.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by j-martin** [comment]
@aryx Tu es le meilleur!

**Comment by aryx** [comment]
merki
