### ISSUE TITLE
Some spacegrep rules are slow

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3427]
The following generic rules are consistently some of the five slowest rules in r2c-security-audit.

https://github.com/returntocorp/semgrep-rules/blob/develop/python/django/security/audit/xss/template-translate-as-no-escape.yaml
https://github.com/returntocorp/semgrep-rules/blob/develop/python/django/security/audit/xss/template-translate-no-escape.yaml
https://github.com/returntocorp/semgrep-rules/blob/develop/python/django/security/audit/xss/template-blocktranslate-no-escape.yaml

**Comment by mjambon** [comment]
Oops, I didn't see this. I created a duplicate issue: #3430
