### ISSUE TITLE
Generic mode should have a way to ignore comments

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3428]
**Is your feature request related to a problem? Please describe.**

Let's say a generic file has code like:

```
# WARNING: Do not use
#  my_terrible_api(bad_input)

ok_api(good_input)
```

This will be caught by rules that, e.g., check for `my_terrible_api(...)`.

**Describe the solution you'd like**
Semgrep should have some mechanism to ignore content in comments. Three ideas:
1. Blanket ignore content after common comment sentinels `#`, `//`, `/*` et c.
2. Map file extensions to the the comments for that extension (so generic mode starts being a little less generic).
3. Push the work to the user with a `generic-comment-token` setting, configured on a per-rule basis:
```
settings:
  generic-comment-token: '#'
```

**Comment by IagoAbal** [comment]
I believe Comby does this via idea 2, and we support Comby patterns. I don't know if that works or if we still want to add this feature to Generic mode too. We have `options:` now so we could use idea 3.

**Comment by IagoAbal** [comment]
@returntocorp/pa any comments on this? I don't know how often this is a problem, but I would be happy with solution 3.

**Comment by aryx** [comment]
cc @mjambon

**Comment by aryx** [comment]
Option 3 seems fine to me.
But in many cases people should anyway switch to the real parser instead of using generic mode.
Generic mode is a last resort solution.
We now have JSON, YAML, terraform, and martin just added recently dockerfile, so where do we still need the generic mode?

**Comment by emjin** [comment]
yarn.lock files use generic

**Comment by mjambon** [comment]
I think we could implement a comment stripper which would replace comments by whitespace before proper spacegrep parsing.

**Comment by mjambon** [comment]
@aryx 
> We now have JSON, YAML, terraform, and martin just added recently dockerfile, so where do we still need the generic mode?

I'm pretty sure there are quite a few more formats that we don't support. For example, I had to fix a problem for someone who was using it on markdown files.

**Comment by aryx** [comment]
But does markdown and yarn.lock require a comment stripper?

**Comment by mjambon** [comment]
We're not targetting markdown and yarn.lock specifically, we're targetting all the file formats that people might use. I'm confident that there will always be formats for which we don't have a dedicated parser.

(but yeah, markdown does supports html-style comments and yarn.lock supports shell-style comments)

**Comment by aryx** [comment]
Totally agree, I love generic mode, I just was wondering how important is to handle comments in the rules we need to write.
But yes if yarn.lock and markdown have comments then yep, might be important then.

**Comment by fropert** [comment]
Interested in this feature at semgrep-level to parse redis configuration. It uses '#' shell comment-style.
