### ISSUE TITLE
Ocaml exception running r/all on semgrep

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3429]
**Describe the bug**

Semgrep outputs a stderr exception representing an exception in the core:
```
--- semgrep-core stderr [rule 'c.lang.correctness.goto-fail.double_goto'] ---
(Toplevel
   (MacroTop (("SOME_FUNC", ()),
      ((), [((Arg (C (Int ((Some 1), ())))), [])], ()), (Some ()))))
PB: Ast_c_build, on semgrep-core/tests/c/misc_toplevel_macrocall.c (exn = Common.Todo)
--- end semgrep-core stderr [rule 'c.lang.correctness.goto-fail.double_goto'] ---
```

**To Reproduce**

Checkout semgrep then `semgrep --config=r/all` on semgrep.

**Expected behavior**
No output from semgrep-core.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep 0.56

**Comment by aryx** [comment]
I can't reproduce on develop.
I tried :`semgrep --config=r/all semgrep-core/tests/c/ --verbose` but I don't get any exception.

**Comment by aryx** [comment]
I do get some errors logged when running with --debug, but I get lots of stuff in those --debug output, so the logged
exception does not really stand out as more annoying than the other logs.
