### ISSUE TITLE
Slow parsing and matching with spacegrep

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3430]
Here are 3 slow rules using the generic mode (reported by @emjin ):
* https://github.com/returntocorp/semgrep-rules/blob/develop/python/django/security/audit/xss/template-translate-as-no-escape.yaml
* https://github.com/returntocorp/semgrep-rules/blob/develop/python/django/security/audit/xss/template-translate-no-escape.yaml
* https://github.com/returntocorp/semgrep-rules/blob/develop/python/django/security/audit/xss/template-blocktranslate-no-escape.yaml

What they have in common is this subpattern:
```
foo
...
...
...
...
...
...
...
...
...
...
bar
```
That's `...` repeated 10 times. This is currently the only way to allow an ellipsis to span over up to 100 lines, since a single `...` spans at most 10 lines.

The problem is that the matching engine doesn't do any caching at the moment. When `foo` matches but there's no `bar`, and there are n items following `foo`, each `...` will be matched starting from each possible position. Within the 10-line limit, the cost of matching a single `...` ellipsis is O(n) (which is an actual asymptotic complexity if line length is unbounded). The cost of matching 10 of these in a sequence is O(n^10). If there are 5 tokens per line and there are 10 remaining lines, that gives us a typical n=50. For n=50, the complexity of the matching the pattern is 50^10 times the cost of the matching the tail of the pattern (`bar`), which is a lot.

Proposal: internally collapse successive `...` into one with an increased line span limit. This changes nothing for the user, but the cost of matching 10 `...` on a block of at most 10 lines would become the same a single `...`. In blocks longer then 100 lines, the cost becomes 10*10 instead of 10^10.

**Comment by mjambon** [comment]
@emjin I haven't been able reproduce the slowness on artificial files. We already have an optimization that takes care of treating consecutive `...` as one. Do you have a target that's know to be slow for one of these rules? Preferably over 100 ms.

**Comment by emjin** [comment]
You can use `semgrep/perf/bench/gitlab/input/gitlab/locale/ko/gitlab.po`, which takes half a second to match on my machine. In general, I don't think it takes a super long time on any one file, it just takes a non-negligible amount of time for each file, which adds up.

For the gitlab repo, here is the general summary:
```
Semgrep-core timing summary:
Total CPU time: 3092.0721 File parse time: 2661.0576 Rule parse time: 2.7672 Match time: 340.6150
Slowest 5/36936 files
public/-/sp.js   ( 97KB): 2.6878
locale/ko/gitlab.po  (867KB): 2.4995
db/migrate/20181228175414_init_schema.rb   (125KB): 2.3114
locale/nb_NO/gitlab.po   (957KB): 2.1631
locale/de/gitlab.po  (901KB): 2.1487
Slowest 5 rules to run (excluding parse time)
ruby.lang.security.filter-skipping.filter-skipping:   run time 116.6463 match time 115.2064
...xss.template-translate-as-no-escape.template-translate-as-no-escape: run time 56.9146 match time 52.4358
...audit.xss.template-translate-no-escape.template-translate-no-escape: run time 50.9444 match time 46.1456
...y.audit.unknown-value-with-script-tag.unknown-value-with-script-tag: run time 48.7381 match time 48.5405
...template-blocktranslate-no-escape.template-blocktranslate-no-escape: run time 43.2233 match time 28.5322
ran 245 rules on 36936 files: 306 findings
19 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
semgrep --config=p/security-audit --enable-metrics --time 741.49s user 2293.07s system 750% cpu 6:44.27 total
```

and here is one of the spacegrep rules on the entire repo:

```
Semgrep-core timing summary:
Total CPU time: 101.7101  File parse time: 36.1046  Rule parse time: 0.0025  Match time: 49.4412
Slowest 5/36936 files
...orkspace/semgrep/perf/bench/gitlab/input/gitlab/locale/ko/gitlab.po (867KB): 0.9169
...space/semgrep/perf/bench/gitlab/input/gitlab/locale/lt_LT/gitlab.po (786KB): 0.8172
...orkspace/semgrep/perf/bench/gitlab/input/gitlab/locale/eo/gitlab.po (788KB): 0.7985
...space/semgrep/perf/bench/gitlab/input/gitlab/locale/nb_NO/gitlab.po (957KB): 0.7864
...space/semgrep/perf/bench/gitlab/input/gitlab/locale/sl_SI/gitlab.po (786KB): 0.7843
Slowest 5 rules to run (excluding parse time)
...xss.template-translate-as-no-escape.template-translate-as-no-escape: run time 65.6055  match time 49.4412
ran 1 rules on 36936 files: 0 findings
semgrep --config config-tests/template-translate-as-no-escape.yaml  --time  88.13s user 13.84s system 407% cpu 25.032 total
```

**Comment by mjambon** [comment]
Great, thanks. Maybe I'll try indexing the tokens of the target in a hash table and checking for the presence of tokens of the pattern in that table, as a preliminary step.

**Comment by IagoAbal** [comment]
Right now with `options:` we could just have one to set the number of lines that we want `...` to match.

**Comment by IagoAbal** [comment]
Have we tried removing the limitation of `...` to just 10 lines, or bumping it to 100? How did we set that limit in the first place?

**Comment by mjambon** [comment]
I picked 10 because it's easy to remember, and it's set in stone for the same reason. I think 100 seemed like too much at the time, and the ability to use `... ... ...` convinced me that 10 was the best setting.

In the current implementation (see earlier comment), a single `...` with a limit of 100 should have the same behavior and performance as 10 consecutive `...` with the standard limit of 10 lines.

I don't know what's slow here, someone would have to investigate the example provided by @emjin .

**Comment by aryx** [comment]
@mjambon is it fixed now that you can specify the limit in the options: ?

**Comment by mjambon** [comment]
@aryx yes:
* code: https://github.com/returntocorp/semgrep/issues/5211
* documentation: https://semgrep.dev/docs/writing-rules/rule-syntax/#options
