### ISSUE TITLE
Add Javascript equivalence for optional function name

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3437]
It would be helpful if the following pattern caught all 4 functions here: https://semgrep.dev/s/2RA8. Instead, we currently use 2 patterns to catch all these cases: https://semgrep.dev/s/X8ZN. This wouldn't have been so noticeable if this pattern didn't catch these 2 cases: https://semgrep.dev/s/jkDD.

My intuition for behavior here would be: `function ($REQ, $RES) {...}` catches all the above cases, and if someone uses the more specific `function $FUNC($REQ, $RES) {...}` it will only return instances where a function name is specified.

Note: this is a common pattern in many of our slowest JS rules:

```
$ rg 'function \(\$REQ, \$RES\)' -A 3
javascript/express/security/express-vm-injection.yaml
18:    - pattern-inside: function ($REQ, $RES) {...}
19-    - pattern-inside: function $FUNC($REQ, $RES) {...}
20-    - pattern-inside: function ($REQ, $RES, $NEXT) {...}
21-    - pattern-inside: function $FUNC($REQ, $RES, $NEXT) {...}
--
81:    - pattern-inside: function ($REQ, $RES) {...}
82-    - pattern-inside: function $FUNC($REQ, $RES) {...}
83-    - pattern-inside: function ($REQ, $RES, $NEXT) {...}
84-    - pattern-inside: function $FUNC($REQ, $RES, $NEXT) {...}
--
148:    - pattern-inside: function ($REQ, $RES) {...}
149-    - pattern-inside: function $FUNC($REQ, $RES) {...}
150-    - pattern-inside: function ($REQ, $RES, $NEXT) {...}
151-    - pattern-inside: function $FUNC($REQ, $RES, $NEXT) {...}
--
263:    - pattern-inside: function ($REQ, $RES) {...}
264-    - pattern-inside: function $FUNC($REQ, $RES) {...}
265-    - pattern-inside: function ($REQ, $RES, $NEXT) {...}
266-    - pattern-inside: function $FUNC($REQ, $RES, $NEXT) {...}

...
```

Being able to utilize 2 patterns here instead of 4 will speed these rules up.

**Comment by IagoAbal** [comment]
The key detail here is that `function ($REQ, $RES) { ... }` is an expression pattern (a "lambda") whereas `function $FUNC($REQ, $RES) { ... }` is a statement (function definition).

This is also a statement, that's why you need `function $FUNC($REQ, $RES) { ... }` to match it:
```
function testCtrl3(req,res) {
    // ruleid:express-path-join-resolve-traversal
   ...
}
```

So this about making a lambda pattern match a function definition.

**Comment by IagoAbal** [comment]
Please check if https://semgrep.dev/s/96L0 does the job and if it does we can probably close this issue. We should document this feature it is not already.

**Comment by mschwager** [comment]
> Please check if https://semgrep.dev/s/96L0 does the job and if it does we can probably close this issue. We should document this feature it is not already.

Yup, that did the trick!

**Comment by aryx** [comment]
yep, you can use ... for the function name.
I'll try to add it in the docs. 
I think it's only for Go and Javascript right now.
