### ISSUE TITLE
Make `--test` output easily understandable

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3445]
**Is your feature request related to a problem? Please describe.**
Right now, the `--test` output is huge. In CI, this becomes a problem because it's not immediately obvious where a failing test is.

**Describe the solution you'd like**
It would be nice if the `--test` output made it easy to understand what failed instead of trying to find the needle in the haystack. Desired features:
- easily understand which tests failed
- I don't typically care which tests passed, even when developing rules. If all tests pass, then I know I'm good 👍 
- There's a bunch of stray `Running X rules...` that show up when running `--test`. Maybe that's helpful, so maybe it could be displayed with increased verbosity.

**Comment by mschwager** [comment]
I'm supportive of this, but I'm going to pull it off support escalations since it's a "nice to have."

**Comment by emjin** [comment]
@mmcqd Relatable

**Comment by bmahe** [comment]
@aryx is this issue still valid?

**Comment by aryx** [comment]
No idea ... I'll close, somene can open it back if it's still an issue.
