### ISSUE TITLE
Line numbers within a single file

### ISSUE THREAD

**Issue by 101142TS** [semgrep/semgrep#3469]
Hello, team!  Can I specify the start and end line numbers when matching within a file? Since a file may contain many lines, one match can take a long time

**Is your feature request related to a problem? Please describe.**
User can specify the start and end line numbers when matching within a file, and match only the content between them

**Describe the solution you'd like**
semgrep -f ./test.yml ./demo.java --start-line-number 10  --end-line-number 20

**Comment by mschwager** [comment]
If you have a particular file in mind you can pipe the line range to Semgrep using target `-`, like so:

```
$ sed -n 10,20p ./demo.java | semgrep -f ./test.yml -
```

**Comment by mjambon** [comment]
@101142TS I'm closing the issue. Just let us know if @mschwager's suggestion doesn't work for you or if we misunderstood your use case.
