### ISSUE TITLE
Severity modification in the output of rule semgrep --config "p/owasp-top-ten".

### ISSUE THREAD

**Issue by Vijay1216** [semgrep/semgrep#3480]
**Is your feature request related to a problem? Please describe.**
It is not very clear whether we should mitigate the issues or not from security perspective. 

**Describe the solution you'd like**
Can we not modify the output of rule semgrep --config "p/owasp-top-ten" as Severity :high , medium ,low , informative instead of warning and error. It will be easier to understand the issues from security.

**Comment by mjambon** [comment]
Thanks for bringing that up! I pinged the security team and they're telling me it's something they've considered in the past and looking into again.

**Comment by clintgibler** [comment]
Hey @Vijay1216! Clint here on the security team. Totally agree with what you're saying. We are mostly likely going to shift from warning/error/info to Informational/Low/Medium/High/Critical in hopefully the not too distant future. 

There are a lot of rules to adjust (1,000+), and we'll need to transition the Dashboard, CI agent, Playground, and maybe other things at the same time to ensure we don't accidentally break anything that's relying on the current severity format.

So I don't have an exact timeframe for you, but hopefully over the next few months! Thanks for the feedback, much appreciated 🙏

**Comment by emjin** [comment]
Could we use Semgrep to adjust the rules? Seems like this should be a simple rule to write with an autofix.
