### ISSUE TITLE
Fixes drop Java generic parameters; no apparent way to specify correct fix

### ISSUE THREAD

**Issue by gordonwoodhull** [semgrep/semgrep#3482]
**Problem description**

I'm trying to write rules that may match Java types, and those types may or may not be generic.

If I use a single metavariable to represent the generic type with its parameters, the parameters get dropped.

Furthermore it seems to be invalid syntax to use angle brackets inside a pattern, so I can't write a more specific rule to match & fix this correctly.

**To Reproduce**
https://semgrep.dev/s/RP48

```yaml
  pattern: $TYPE $RESULT = ($TYPE)$EXPR.foo($SOURCE);
  fix: $TYPE $RESULT = ($TYPE)$EXPR.bar($SOURCE);
```

**Input:**

```java
A<int> x = (A<int>)qux.foo("hello");
```

**Expected output**

```java
A<int> x = (A<int>)qux.bar("hello");
```

**Actual output**

```java
A x = (A)qux.bar("hello");
```

I also attempted 

https://semgrep.dev/s/8RWj
```yaml
  pattern: $TYPE<$TYPEPARM> $RESULT = ($TYPE<$TYPEPARM>)$EXPR.foo($SOURCE);
  fix: $TYPE<$TYPEPARM> $RESULT = ($TYPE<$TYPEPARM>)$EXPR.bar($SOURCE);
```

But this produces the error

```
Pattern could not be parsed as a Java semgrep pattern
```

(I see the error on the command line; it just fails to match on semgrep.dev.)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

Edit: changed from blocking to annoying because I am sure we would use Semgrep for other languages, but this issue blocks us from fixing vulns in Java.

**Comment by aryx** [comment]
Hi @gordonwoodhull . Thx for the bug report. We are in the middle of a hackathon/hack-week, but I'll try to look at it
next monday.

**Comment by aryx** [comment]
Works now on develop: https://semgrep.dev/s/RP48?version=develop

**Comment by gordonwoodhull** [comment]
Cool, thanks @aryx!!
