### ISSUE TITLE
Multiple from-style imports produce incorrect findings and range

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3490]
https://semgrep.dev/s/rkDj

This appears to be producing two incorrect results:

- There are 3 findings whereas I would expect 1
- The finding range only includes the `import` statement whereas I would expect it to include the whole file

**Comment by mschwager** [comment]
It looks like the latest code is now producing 4 findings instead of 3? Whereas I'd expect 1:
- https://semgrep.dev/s/rkDj
- https://semgrep.dev/s/rkDj?version=develop

And this gives 5 findings: https://semgrep.dev/s/5J43?version=develop. So it seems the number of findings will continue to grow as the code gets larger

**Comment by mschwager** [comment]
Maybe I'm misunderstanding what's supposed to be happening with the above example, but here the `...` only produces 1 finding: https://semgrep.dev/s/owjN/, and here it produces 4: https://semgrep.dev/s/jkeA/.

**Comment by aryx** [comment]
It's normal, the ... does not have the same scope in both. In one case your pattern matches a function definition, and it will either match a full function definition or nothing. In the other case your pattern is a list of statements, and it will match a list of statements.

**Comment by mschwager** [comment]
Another case - this produces 1 finding instead of 5: https://semgrep.dev/s/65L6/ vs. 5 here: https://semgrep.dev/s/owvN/. This feels counterintuitive to me. In one scope we only produce 1 finding - the entire span of the scope. In another scope we produce multiple findings for each possible span :confused: 

> yes, an optimization is actually to look if it's used a pattern-inside, in which case we could specialize and return only the biggest finding

IMO we should aim to generalize rather than specialize. Specialization makes functionality difficult to reason about. Knowledge of one part of the system doesn't translate to other parts of the system. With that being said, per above, it makes the most sense to me to have consistent behavior for `...` across all scopes. Is there something I'm missing preventing that?
