### ISSUE TITLE
(x) => `${x}` yields unexpected match for raw-html-concat rule

### ISSUE THREAD

**Issue by JasonCubic** [semgrep/semgrep#3502]
https://semgrep.dev/s/JjOd?registry=javascript.browser.security.raw-html-concat.raw-html-concat

I have some backend code that seems to be returning a false positive for this rule.  Here is the code:  https://semgrep.dev/s/jasoncubic:false-positive-for-html-xss-in-backend-code??registry=javascript.browser.security.raw-html-concat.raw-html-concat

**Comment by mjambon** [comment]
Thank you for reporting this! It's unfortunate that we don't see which of the patterns matched. Here's the same with a simplified target program: https://semgrep.dev/s/z9WP

```js
// match (unexplained false positive)
(x) => `${x}`

// doesn't match, as expected
(y) => `${x}`
```

**Comment by mjambon** [comment]
It might be a problem with the rule itself since it's pretty long but my guess is there's a matching bug.

**Comment by minusworld** [comment]
@inkz When you come online, would you also mind investigating this from a rule perspective?

**Comment by inkz** [comment]
yep,
* this is definitely a rule problem, semgrep is doing its job :+1: , so I believe it makes sense to move this ticket to the`semgrep-rules` repo.
* We do not check strings to contain HTML code specifically, the rule just highlights everything that concatenates strings and variables regardless of the string content. It works pretty well on client-side js code, but on the server, it is going to bring lots of false positives.
* But I am pretty sure that we can update the rule using new features (HTML support, metavariable-pattern) to make it more precise.

**Comment by inkz** [comment]
cc @minusworld

**Comment by IagoAbal** [comment]
Can we close this issue? @inkz

**Comment by minusworld** [comment]
@inkz Do you think this is closed by https://github.com/returntocorp/semgrep-rules/pull/1386? Thanks for checking :)

**Comment by inkz** [comment]
@minusworld yep, new version of `raw-html-concat` rule mitigates this FP :+1:

**Comment by inkz** [comment]
@JasonCubic thank you, new version of `raw-html-concat` rule is available.
