### ISSUE TITLE
Metavariable pattern matching does not work for some language types

### ISSUE THREAD

**Issue by chgg-kboberg** [semgrep/semgrep#3531]
**Describe the bug**
Metavariable pattern matching does not work for some parsers (such as YAML).  Setting the metavariable pattern language to Python does not solve the issue (and causes Semgrep to complain that the target is not parseable as the parent type).

**To Reproduce**
https://semgrep.dev/s/RPlv

**Expected behavior**
Rule should match `jwt.decode(...)`

**Screenshots**
n/a

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by chgg-kboberg** [comment]
@ievans pointed out that you can work around this limitation by specifying Javascript as the pattern language (which works, even though the example metavariable code is Python)

**Comment by IagoAbal** [comment]
If I run semgrep-core on this, after adding `language: python`, I get:
> bug-target.yaml:1:0: Fatal Error: (Failure "Lexer_python.top_mode: empty stack")

**Comment by IagoAbal** [comment]
> @ievans pointed out that you can work around this limitation by specifying Javascript as the pattern language (which works, even though the example metavariable code is Python)

_Probably_ (haven't confirmed this is the case) because a subset of the code can be parsed as JS. The tree-sitter parsers can work with partially-correct input, they will still generate a syntax tree for the parts that are syntactically valid.

**Comment by IagoAbal** [comment]
This works for me https://semgrep.dev/s/2RWB

In your example there is an ending `}` that makes the Python front-end to fail. I believe that for Python we don't use tree-sitter so Semgrep doesn't accept inputs that contain any lexical or syntactic error.

I would say that this is not a bug, if you can confirm please close the issue. Otherwise please share another example.

**Comment by chgg-kboberg** [comment]
Confirmed, trailing bracket was an artifact of an improperly minified example snippet.  Would be nice if the parser complained in the right language (currently it says couldn't be parsed as PARENT_LANGUAGE)

**Comment by IagoAbal** [comment]
I agree we need to improve error reporting for this and other cases, opened #3547 to keep track of this issue.
