### ISSUE TITLE
CLI: Incorrect error code after running successfully and finding issues

### ISSUE THREAD

**Issue by ShaylanDias** [semgrep/semgrep#3535]
**Describe the bug**
The [CLI reference](https://semgrep.dev/docs/cli-usage/#exit-codes) states that it should exit with 1 if "Semgrep ran successfully and found issues in your code". However, the CLI exits with 0 in this case.

**To Reproduce**
To reproduce:
1. Write a rule and a file where the rule will result in an error:
rules.yml:
```
rules:
  - id: this-should-fail
    patterns:
    - pattern: return ...;
    languages:
      - javascript
    severity: ERROR
    message: This should find an error
```
Test.js
```
let x = () => {
  return "Hello!";
}
```
2. Run `semgrep --config rules.yml` and observe the error is found.
3. Run `echo $?` and observe the exit code was 0 rather than 1.

**Expected behavior**
The error code should be 1 instead of 0.

**Screenshots**
If applicable, add screenshots to help expl
![Screen Shot 2021-07-15 at 1 20 33 PM](https://user-images.githubusercontent.com/38924672/125852292-b4fd2aab-c8fe-440b-b87e-21d516e63b87.png)
ain your problem.

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Locally and in a custom Docker image.

**Comment by ShaylanDias** [comment]
Update: I've realized I need to pass the `--error flag`, but I think the docs need to be updated to match this as currently they are inconsistent

**Comment by aryx** [comment]
Closing this since you've created an issue in semgrep-docs.
Thx for reporting the inconsistency!
