### ISSUE TITLE
[Internal] investigate why benchmark circleCI jobs fails constantly

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3537]
See https://app.circleci.com/pipelines/gh/returntocorp/semgrep?branch=develop

Fortunately it seems the job pushes some of the results on our dashboard
(e.g., https://dashboard.semgrep.dev/metric/semgrep.bench.0c34.std.duration).
Still, would be nice to know why it's not terminating.

@emjin says she can't reproduce locally. Seems to happen only in CI.

**Comment by emjin** [comment]
It fails quite early on in the medium benchmarks. Last checked: failed at django
