### ISSUE TITLE
[Internal] break mutual dependency between semgrep CI and semgrep-rules CI

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#3539]
As martin wrote:
We have a CI deadlock because:

semgrep CI tests against the main branch of semgrep-rules, and
semgrep-rules CI tests against the main branch of semgrep
This would be solved by using a git submodule in semgrep pointing to the correct branch of semgrep-rules.

See for example this semgrep PR https://github.com/returntocorp/semgrep/pull/3444 mutually dependent on
this semgrep-rules PR https://github.com/returntocorp/semgrep-rules/pull/1362#event-5029680119 where currently both fails in CI because they are mutually dependent.

**Comment by aryx** [comment]
This is how we handled in the past, but it was not ideal:

"This mutual dependency issue happens rarely, so usually what I do is that I make the PR to semgrep, and in the test plan I show how a modified semgrep-rules pass with the modified semgrep
then I force merge the semgrep PR if only the semgrep-rules CI job fails
then I wait an hour that the docker develop image has been updated
and I make the PR to semgrep-rules"

**Comment by aryx** [comment]
As suggested by martin, it would be better to make semgrep-rules a submodule and remove the test that rely on the online version of semgrep-rules and instead use the rules in the submodule.

**Comment by aryx** [comment]
cc @mschwager @brendongo @minusworld

**Comment by aryx** [comment]
:wave:

**Comment by aryx** [comment]
One thing we can do during the release process, as Iago suggested, is to update the semgrep-rules submodule to
use the latest semgrep-rules. We can also run a check to transform certain todoruleid: in regular ruleid: when the engine
recognizes them correctly.

**Comment by minusworld** [comment]
I'm also happy to work with you all on this - sorry about all the trouble from last week.

From our standpoint, our main desire is that rules that make it all the way to registry are able to run on the latest released version of Semgrep that's in all the package managers. i.e., we don't want someone to try and run a rule that won't work on the most recently available version. This is what `test-latest` does on semgrep-rules, but is also what caused the issue last week.

If a submodule of semgrep-rules sounds like a huge pain, maybe now is a decent time to include a version field in semgrep rules.

In any case, I'm happy to lend help to resolve this.

**Comment by minusworld** [comment]
semgrep-rules now officially releases off of a release branch. This means that changes can be made to `develop` and will be reflected in semgrep's tests without actually releasing rules that use unreleased features. Does this sound like it resolves this issue?

**Comment by aryx** [comment]
The problem is that we still use the latest semgrep-rules in the CI of semgrep, and many times a fix in semgrep leads to finding more things, or fixing some todoruleid: in semgrep-rules, which means the CI of semgrep will fail, but we can't change semgrep-rules because it's using an old version so you can't add more ruleid: or remove some todoruleid:, so we're still blocked. Can't change semgrep, can't change semgrep-rules. What we need is the ability to change both at the same time (which would be possible in a monorepo, or if we were using semgrep-rules as a submodule of semgrep.

**Comment by IagoAbal** [comment]
This is a good candidate for a tech-debt week. It shouldn't take much time. It would solve the problem on our side. But for semgrep-rules, you will still have a situation where first your `test-develop` check fails, and then (once you update your `develop`) your `test-latest` will fail until a new Semgrep is released. Maybe `test-latest` is only needed for your release branch?

**Comment by aryx** [comment]
ok semgrep-rules is now a submodule!

**Comment by aryx** [comment]
remains to implement @IagoAbal idea:
"[iago](https://app.slack.com/team/U017K5ZH4BA)  We could then have a separate job that runs the CLI tests with the latest semgrep-rules, and that job could be optional instead of required to merge, because right now you will only see that the tests failed, and the merge is blocked."

**Comment by aryx** [comment]
closing, I thing what we have now is better and good enough to get some insurance that about not breaking things.
