### ISSUE TITLE
Properly communicate errors in semgrep-core to the CLI

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3547]
**Is your feature request related to a problem? Please describe.**
Warnings or errors raised by semgrep-core are quite often not communicated properly to the CLI, so the CLI fails with some generic error that may not be very helpful. For example, in #3531, semgrep-core reports an exception when parsing a piece of Python code, but this is reported as a YAML syntax error by the CLI.

**Describe the solution you'd like**
We should make sure that all warnings or errors raised by semgrep-core will be added to its JSON output when `-json` is given.

**Comment by aryx** [comment]
I'm done with what I wanted to do.
Feel free to take over.

**Comment by IagoAbal** [comment]
Another example of bad error communication is #3603.

**Comment by emjin** [comment]
I've done what I meant to: this now gives a better error message: https://semgrep.dev/s/BLJR/?version=4cfd20f237a9106b185d56c747215b856bca2e84
