### ISSUE TITLE
[Java]Unable to match method names

### ISSUE THREAD

**Issue by 101142TS** [semgrep/semgrep#3564]
**Describe the bug**
Unable to match method names in Java

**To Reproduce**
https://semgrep.dev/s/8RP7/

**Expected behavior**
MATCHES shows : **Intent intent = activity.getIntent();**

**What is the priority of the bug to you?**
P0

**Comment by dlukeomalley** [comment]
Hey @101142TS! Thanks for filing this bug. I modified your pattern and am able to match `activity.getIntent()`: https://semgrep.dev/s/JjPQ/

In Semgrep the pattern needs to be valid source code, so in this case to match a function call in Java the method name `getIntent` must be proceeded by `()`.

The tutorial [here](https://semgrep.dev/learn) should help explain some of these concepts better than I can do in a comment, but I can definitely answer questions!

Let me know how I can help further.
