### ISSUE TITLE
Opposite conditional matching behavior in PHP and Java

### ISSUE THREAD

**Issue by BashPrince** [semgrep/semgrep#3568]
In Java matching  conditionals with
```
if (...) { ... }
```
matches an if-block as well as an if-else-block. In PHP only the if-block is matched.
However, changing the pattern to 
```
if (...) { ... } else { ... }
```
will have the opposite behavior in either languages.

Links:
https://semgrep.dev/s/bashprince:java
https://semgrep.dev/s/bashprince:php

Not sure which one is the correct behavior, but I would think the Java version makes more sense in this case since it matches the whole block and the further specification with else makes the match more exact.

- [ ] P2: regular bug that should get fixed

Tested on semgrep.dev

**Comment by erwanlr** [comment]
Also, an `if (...) { ... }` pattern will only match the last `else if` statement when there is an `else if`: https://semgrep.dev/s/5JEW

That one is P0 for me
