### ISSUE TITLE
Named ellipses not bound in `metavariable-pattern` for JS

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3578]
**Describe the bug**
I have this pattern here: https://semgrep.dev/s/Gw6y/
I would expect this to work, matching the template string.

I suspect this has something to do with the named ellipses, because I can make this pattern here work that uses template strings: https://semgrep.dev/s/RPAg/

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep `0.59.0`

**Comment by Sjord** [comment]
This seems like an actual bug, should this be reopened? It looks similar to [Metavariables don't match in JavaScript template strings · Issue #3786 · returntocorp/semgrep](https://github.com/returntocorp/semgrep/issues/3786).
