### ISSUE TITLE
[js] literal numeric property names are not equivalent between encodings

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3579]
The key `0x1` and `1` should be equivalent.

https://semgrep.dev/s/Dwqd

**Comment by IagoAbal** [comment]
Internally, when `1` or `0x1` are used as keys, they are parsed as identifiers.

**Comment by IagoAbal** [comment]
Seems that's OK but we need to normalize these strings, so that `0x1`, `1.0` and `1` all end up represented the same way.

**Comment by IagoAbal** [comment]
#3586 should fix this, although I'm not sure if we are 100% compliant. In Semgrep `{1.:"foo", "1.":"bar"}` would trigger your rule as `1.` and `"1."` being duplicate keys. In my Firefox JS console this is not the case.

**Comment by IagoAbal** [comment]
^ cc @pad @mjambon
