### ISSUE TITLE
PHP parse error on enums

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3591]
PHP 8.1 will include `enum` support: https://stitcher.io/blog/php-enums

https://semgrep.dev/s/jkyl/

**Comment by Sjord** [comment]
[Support PHP enum when converting to generic AST by Sjord · Pull Request #5367 · returntocorp/semgrep](https://github.com/returntocorp/semgrep/pull/5367)

**Comment by aryx** [comment]
works now thx to Sjord: https://semgrep.dev/s/jkyl/?develop=true
