### ISSUE TITLE
[rust] Can't match literal macro call

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3600]
See https://r2c-community.slack.com/archives/C018NJRRCJ0/p1627052124314500?thread_ts=1626194116.277400&cid=C018NJRRCJ0

It looks like the fix for #3513 introduced a regression i.e. the pattern `println!("hello")` no longer matches.

**Comment by aryx** [comment]
Can you put a playground link? I just tried the pattern println!("hello") and it matches correctly rust code.

**Comment by aryx** [comment]
Also the linked slack thread does not contain explanation about what was wrong with my fix.

**Comment by aryx** [comment]
(Actually might be a Slack bug, because if I search for Chris Jacoby messages I found it, but in the linked thread above
this message does not appear; weird).
