### ISSUE TITLE
Parsing error for parameter calls with ()

### ISSUE THREAD

**Issue by devd** [semgrep/semgrep#3603]
**Describe the bug**

Parse error on a ruby file that accepts block as a param and calls it via ->() and the pattern has metavariables.

**To Reproduce**
https://semgrep.dev/s/AwBL/

**Expected behavior**
no parse error

**What is the priority of the bug to you?**

- [ ] P2: regular bug that should get fixed

**Comment by IagoAbal** [comment]
This seems to be due to fake tokens in the Ruby AST.
