### ISSUE TITLE
Allow local caching of rules

### ISSUE THREAD

**Issue by raghavjain3** [semgrep/semgrep#3605]
**Is your feature request related to a problem? Please describe.**
Users would like to cache rules locally in the event that the Semgrep Registry is down

**Describe the solution you'd like**
Potential Solution - A cached directory with different rules from a project (like "node_modules")

**Describe alternatives you've considered**
N/A. Have not worked on potential flows / solutions for this feature yet.

**Additional context**
Requested by several users.

**Comment by aryx** [comment]
We need also a versioning story that goes with it, so people can cache locally owasp-rules-1.0,
and update if they want to a new ruleset which will then update the local cache

**Comment by emjin** [comment]
Added to "Semgrep can run on an airplane" project

**Comment by WesleyAC** [comment]
Are there any docs for how to do this now?

I presume I can vendor the returntocorp/semgrep-rules repo somehow — it'd be nice to have some docs on how to do that in the interim while this feature is being developed.

**Comment by aryx** [comment]
I think you can just use the URL of the ruleset to download it locally.

`curl https://semgrep.dev/c/p/ocaml`
will download all the ocaml rules in one yaml file that you can then pass to --config

**Comment by WesleyAC** [comment]
Ah, that works great, thanks! Can that be added to the docs somewhere?

**Comment by aryx** [comment]
Yes we should.

**Comment by aryx** [comment]
Seems like a dupe of #3147
