### ISSUE TITLE
Option for SARIF output to include ignored findings using the suppressions property

### ISSUE THREAD

**Issue by ShaylanDias** [semgrep/semgrep#3606]
**Is your feature request related to a problem? Please describe.**
We would like visibility into Semgrep findings which have been ignored via a `nosemgrep` comment— especially for integration with other tooling which performs requires this information.

**Describe the solution you'd like**
There should be an option for Semgrep findings which are ignored through the use of `nosemgrep` comments to still show up in the SARIF output as a `result` with the `suppressions` property set to an array containing the object `{"kind": "inSource"}`. This marks them as ignored by an inline comment but keeps them in the output so they are still visible to the end user/tooling. This could be disabled by default but enabled through the CLI with a flag `--sarif-include-nosemgrep`.

**Additional context**
The [SARIF spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541171) details a `suppression` object contained within the `suppressions` property. The idea is to allow analysis tools to convey information on findings which have been "suppressed." The `"kind": "inSource"` attribute specifically refers to if the source code contains flags which remove warnings, which fits `nosemgrep` comments.
<img width="192" alt="Screen Shot 2021-07-27 at 2 40 31 PM" src="https://user-images.githubusercontent.com/38924672/127231245-54fdb44b-568e-4412-8bfe-fa777cda00f8.png">

**Comment by ShaylanDias** [comment]
After looking at the source code briefly I feel fairly confident about taking this on myself and submitting a PR. I just wanted to gauge whether or not it fits within the Semgrep design plan first.

**Comment by brendongo** [comment]
Seems like `suppressedInSource` https://docs.oasis-open.org/sarif/sarif/v2.0/csprd01/sarif-v2.0-csprd01.html#_Toc517436079  would be more appropriate here?

**Comment by ShaylanDias** [comment]
Yes, you're definitely correct—I'll update the post to reflect. I think the idea still stands though.
