### ISSUE TITLE
Double Findings

### ISSUE THREAD

**Issue by haydenplemmons** [semgrep/semgrep#3614]
**Describe the bug**
When we run semgrep in terminal on a local dir, we are getting double findings. Even if there is only one pattern, it gives 2 findings per line, usually. Sometimes, there is only one finding per line, I cannot see a pattern as to when there is double findings vs single. Also, by we I mean myself and another engineer both tried on our machines.
Also, I just updated from semgrep .57 to .59 and it still occurs.

**To Reproduce**
It does not reproduce in playground, but we reproduce it every time we scan.

**Expected behavior**
Single finding per rule or pattern.

**Screenshots**
![editedcodeoutSemgrep](https://user-images.githubusercontent.com/86074254/127195162-52088a39-a217-4170-a115-32c2dcd35562.png)
![Screen Shot 2021-07-26 at 3 17 44 PM](https://user-images.githubusercontent.com/86074254/127195206-d7e7bdd2-a6c6-4b1b-8b6a-49391b49f018.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Local scans, does not seem to be occurring in our semgrep CI.

**Comment by IagoAbal** [comment]
> Hi, not sure about top one, but mine example shows the difference:
> https://semgrep.dev/s/Gwz1?version=0.60.0 - two similar/duplicated finding for the same line
> https://semgrep.dev/s/Gwz1?version=0.56.0 - only one finding reported - correct one.

_Originally posted by @tilperion2 in https://github.com/returntocorp/semgrep/issues/3544#issuecomment-888296611_

**Comment by IagoAbal** [comment]
@aryx this seems related to #3310 as @emjin pointed out, in @tilperion2's example (https://semgrep.dev/s/Gwz1) we are returning two matches, one where `$CIPHER` is `Cipher`, and another one where it is `javax.crypto.Cipher`.

**Comment by tilperion2** [comment]
Created the same issue here, you may chose which one to close as a duplicate:
#3618 https://github.com/returntocorp/semgrep/issues/3618

**Comment by IagoAbal** [comment]
> Created the same issue here, you may chose which one to close as a duplicate:
> #3618 #3618

Oops sorry I had not seen this issue at the time I asked you to open a new one.

**Comment by IagoAbal** [comment]
@haydenplemmons can you provide an example in text format that I can use to reproduce the issue.

**Comment by IagoAbal** [comment]
OK, I think I know why you cannot see the problem in the Playground, and it's probably because you are not running against the same code. Is e.g. `XmlObject` an imported entity?  This may be a duplicate of #3618 after all.

**Comment by IagoAbal** [comment]
@brendongo could you please explore (partially) reverting returntocorp/semgrep#3310 ? I think it should be a quick-fix.  If two matches have the same range *and* different message (because the message refers to an `$MVAR`) then we should not remove duplicates. But if the messages are identical, then the user cannot see why we return several matches (and maybe does not want to!). If the users really want to see all the matches, they can use `--json` (we should not remove duplicates in that case!). What do you think?

Regarding #3279, I think the user could just write another formula: https://semgrep.dev/s/z9Qn, cc @ievans. Or, if we implement what is described above, the user just needs to include `$DEP_NAME` and `$DEP_VERSION` in the message and will also get all the different matches.

**Comment by fproulx-boostsecurity** [comment]
Hello, chiming in here
I am also seeing that after upgrading from 0.56.0 to 0.60.0.

Here's a playground:
https://semgrep.dev/s/owQX

---


I also ran using `--json` and I can see that there are slight variations in the 4 findings, vs when output as SARIF they are the same (without that AST details):

```
{"check_id":"javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret","end":{"col":46,"line":10},"extra":{"is_ignored":false,"lines":"  const jsonwt = require('jsonwebtoken')\n  const payload = {foo: 'bar'}\n  const secret = 'shhhhh'\n  const token1 = jsonwt.sign(payload, secret)","message":"Hardcoded JWT secret or private key is used.\nConsider using an appropriate security mechanism to protect the credentials (e.g. keeping secrets in environment variables).\n","metadata":{"boost-maturity":"stable","cwe":"CWE-798: Use of Hard-coded Credentials","owasp":"A2: Broken Authentication","source-rule-url":"https://r2c.dev/blog/2020/hardcoded-secrets-unverified-tokens-and-other-common-jwt-mistakes/"},"metavars":{"$JWT":{"abstract_content":"jsonwt","end":{"col":15,"line":7,"offset":167},"start":{"col":9,"line":7,"offset":161},"unique_id":{"sid":3,"type":"id"}},"$P":{"abstract_content":"payload","end":{"col":37,"line":10,"offset":287},"start":{"col":30,"line":10,"offset":280},"unique_id":{"sid":4,"type":"id"}},"$T":{"abstract_content":"token1","end":{"col":15,"line":10,"offset":265},"start":{"col":9,"line":10,"offset":259},"unique_id":{"sid":6,"type":"id"}}},"severity":"ERROR"},"path":"tests/plugins/semgrep/data/canaries/sprint15-jwt/javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret/rule.js","start":{"col":3,"line":7}}
{"check_id":"javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret","end":{"col":46,"line":10},"extra":{"is_ignored":false,"lines":"  const jsonwt = require('jsonwebtoken')\n  const payload = {foo: 'bar'}\n  const secret = 'shhhhh'\n  const token1 = jsonwt.sign(payload, secret)","message":"Hardcoded JWT secret or private key is used.\nConsider using an appropriate security mechanism to protect the credentials (e.g. keeping secrets in environment variables).\n","metadata":{"boost-maturity":"stable","cwe":"CWE-798: Use of Hard-coded Credentials","owasp":"A2: Broken Authentication","source-rule-url":"https://r2c.dev/blog/2020/hardcoded-secrets-unverified-tokens-and-other-common-jwt-mistakes/"},"metavars":{"$JWT":{"abstract_content":"jsonwt","end":{"col":15,"line":7,"offset":167},"start":{"col":9,"line":7,"offset":161},"unique_id":{"sid":3,"type":"id"}},"$P":{"abstract_content":"payload","end":{"col":37,"line":10,"offset":287},"start":{"col":30,"line":10,"offset":280},"unique_id":{"sid":4,"type":"id"}}},"severity":"ERROR"},"path":"tests/plugins/semgrep/data/canaries/sprint15-jwt/javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret/rule.js","start":{"col":3,"line":7}}
{"check_id":"javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret","end":{"col":46,"line":10},"extra":{"is_ignored":false,"lines":"  const jsonwt = require('jsonwebtoken')\n  const payload = {foo: 'bar'}\n  const secret = 'shhhhh'\n  const token1 = jsonwt.sign(payload, secret)","message":"Hardcoded JWT secret or private key is used.\nConsider using an appropriate security mechanism to protect the credentials (e.g. keeping secrets in environment variables).\n","metadata":{"boost-maturity":"stable","cwe":"CWE-798: Use of Hard-coded Credentials","owasp":"A2: Broken Authentication","source-rule-url":"https://r2c.dev/blog/2020/hardcoded-secrets-unverified-tokens-and-other-common-jwt-mistakes/"},"metavars":{"$JWT":{"abstract_content":"jsonwt","end":{"col":15,"line":7,"offset":167},"start":{"col":9,"line":7,"offset":161},"unique_id":{"sid":3,"type":"id"}},"$P":{"abstract_content":"payload","end":{"col":37,"line":10,"offset":287},"start":{"col":30,"line":10,"offset":280},"unique_id":{"sid":4,"type":"id"}},"$SECRET":{"abstract_content":"secret","end":{"col":15,"line":9,"offset":239},"start":{"col":9,"line":9,"offset":233},"unique_id":{"sid":5,"type":"id"}},"$T":{"abstract_content":"token1","end":{"col":15,"line":10,"offset":265},"start":{"col":9,"line":10,"offset":259},"unique_id":{"sid":6,"type":"id"}}},"severity":"ERROR"},"path":"tests/plugins/semgrep/data/canaries/sprint15-jwt/javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret/rule.js","start":{"col":3,"line":7}}
{"check_id":"javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret","end":{"col":46,"line":10},"extra":{"is_ignored":false,"lines":"  const jsonwt = require('jsonwebtoken')\n  const payload = {foo: 'bar'}\n  const secret = 'shhhhh'\n  const token1 = jsonwt.sign(payload, secret)","message":"Hardcoded JWT secret or private key is used.\nConsider using an appropriate security mechanism to protect the credentials (e.g. keeping secrets in environment variables).\n","metadata":{"boost-maturity":"stable","cwe":"CWE-798: Use of Hard-coded Credentials","owasp":"A2: Broken Authentication","source-rule-url":"https://r2c.dev/blog/2020/hardcoded-secrets-unverified-tokens-and-other-common-jwt-mistakes/"},"metavars":{"$JWT":{"abstract_content":"jsonwt","end":{"col":15,"line":7,"offset":167},"start":{"col":9,"line":7,"offset":161},"unique_id":{"sid":3,"type":"id"}},"$P":{"abstract_content":"payload","end":{"col":37,"line":10,"offset":287},"start":{"col":30,"line":10,"offset":280},"unique_id":{"sid":4,"type":"id"}},"$SECRET":{"abstract_content":"secret","end":{"col":15,"line":9,"offset":239},"start":{"col":9,"line":9,"offset":233},"unique_id":{"sid":5,"type":"id"}}},"severity":"ERROR"},"path":"tests/plugins/semgrep/data/canaries/sprint15-jwt/javascript.jsonwebtoken.security.jwt-hardcode.hardcoded-jwt-secret/rule.js","start":{"col":3,"line":7}}
```

---

Between 1st and 2nd findings, looks like that is extra:

```
{
  "extra": {
    "metavars": {
      "$T": {
        "abstract_content": "token1",
        "end": {
          "col": 15,
          "line": 10,
          "offset": 265
        },
        "start": {
          "col": 9,
          "line": 10,
          "offset": 259
        },
        "unique_id": {
          "sid": 6,
          "type": "id"
        }
      }
    }
  }
}
```

---

If I output the metavars in the message, that's the diff:

```
JWT: jsonwt , T: token1 , P: payload, SECRET: $SECRET
--
JWT: jsonwt , T: $T        , P: payload, SECRET: $SECRET
--
JWT: jsonwt , T: token1  , P: payload, SECRET: secret
--
JWT: jsonwt , T: $T        , P: payload, SECRET: secret

**Comment by fproulx-boostsecurity** [comment]
OK. I rewrote the rule to avoid repetition and it's much much faster anyway
https://semgrep.dev/s/fproulx-boostsecurity:owqx-v2

I think, I can handle my issues by rewriting / optimizing my 4 rules that show the behavior, but that scenario where they in fact match differently, but the message is the same (and the line span is strictly the same) .... should be de-dupped by the tool

-- 

I had a clone of an upstream community rule - will update to your new one https://github.com/returntocorp/semgrep-rules/blob/develop/javascript/jsonwebtoken/security/jwt-hardcode.yaml
