### ISSUE TITLE
Gracefully handle exit code -11

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3621]
We have had multiple users encounter semgrep-core exiting with -11, which represents a segmentation fault. When this happens, semgrep declares the output is unparseable JSON and crashes. Due to our use of temp files, it is also difficult to ask users to give us file contents to reproduce.

We should
1. Produce a better error message
2. If possible, continue running and report this as a usual error
3. Automatically or add a flag to persist temp files created by semgrep on exception to allow us to reproduce this

Example: https://github.com/returntocorp/semgrep/issues/3610

**Comment by IagoAbal** [comment]
Related to #3547. Actually it could be considered a specific example where we don't communicate errors properly. We could perhaps handle the segfault and exit providing some debug info.

**Comment by mjambon** [comment]
See also #3044.

**Comment by emjin** [comment]
Closing this now that we have a better message; the tarball is the only part that needs to be done
