### ISSUE TITLE
Incorrect Timeout

### ISSUE THREAD

**Issue by nealharris** [semgrep/semgrep#3639]
**Describe the bug**
When attempting to run `semgrep-agent` against my python project I receive an error message that says `Semgrep took longer than 1800 seconds to run; canceling this run`, even though this message is given quite quickly. Concretely:
```
$ time docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1 semgrep-agent --config p/ci       
| versions          - semgrep 0.60.0 on Python 3.9.6
| scan type         - full scan (set --baseline-ref to scan changed files only)
| environment       - running in environment git, triggering event is 'unknown'
| manage            - not logged in
=== setting up agent configuration
| using semgrep rules from https://semgrep.dev/c/p/ci
| using default path ignore rules of common test and dependency directories
| found 3910 files in the paths to be scanned
| skipping 80 files based on path ignore rules
Semgrep took longer than 1800 seconds to run; canceling this run
docker run -v $(pwd):/src --workdir /src returntocorp/semgrep-agent:v1   p/ci  0.08s user 0.03s system 0% cpu 1:11.87 total
```

**To Reproduce**
Sadly, this is in a private repository, and I haven't found a way to reproduce with a public repo.

**Expected behavior**
I would expect semgrep to either not timeout, or to take at least 1800 seconds to report an 1800 second timeout.

**Screenshots**
Not a screenshot, but see above for the output from my terminal.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker

**Comment by brendongo** [comment]
Looks like the git commands were timing out (had timeout of 60) and we just had a bad error message. Bumped up the timeout for the git commands to 500 https://github.com/returntocorp/semgrep-action/pull/345 if you try rerunning (make sure to re-pull the docker image) we can see if 500 is enough for your needs.

**Comment by nealharris** [comment]
Hey, thanks!

**Comment by brendongo** [comment]
Closing as fixed let us know if that was not the case
