### ISSUE TITLE
Show a useful stack trace for any unexpected exception

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3642]
There's a bunch of places where we have indiscriminate exception catchers that do this:
```ocaml
try
  ...
with exn -> Common.exn_to_s exn
```
which is currently the same as just turning the exception to a string with `Printexc.to_string`. When catching an exception like `Failure "not implemented"` or `Stack_overflow`, we'd like to know where the exception was raised and currently we don't know. It takes a lot of guesswork to figure out what happens, especially if this happens in a customer's log.

**Proposal**: wrap exceptions with a useful stack trace, using the [Trax library](https://github.com/mjambon/trax/blob/master/src/trax.mli). This gives the following benefits:
* the same exception can be caught and reraised several times without losing the location where it was raised originally.
* repeated locations are removed from the trace for printing, which is useful when we have many recursive calls.

**How to use it**:
1. Install the `trax` package from opam.
2. Call [Trax.wrap_with_stack_trace e](https://github.com/mjambon/trax/blob/547866568c2185ed4e1b99bcca7f23d06d4f890d/src/trax.mli#L20) to wrap the exception `e` just after catching it.
3. Use `match Trax.unwrap e with ...` to inspect an exception `e`.
4. Use `Trax.to_string e` or `Trax.print e` for printing the exception and the nicely formatted, compact trace.

**Comment by aryx** [comment]
@mjambon recently closed this with the new Exception module in pfff.
See #5567
