### ISSUE TITLE
git submodules break scan target identification for "generic" language

### ISSUE THREAD

**Issue by malexmave** [semgrep/semgrep#3660]
**Describe the bug**
Running a rule with language "general" on the [OpenHaystack](https://github.com/seemoo-lab/openhaystack) repository results in an error message `Could not open 'Firmware/Microbit_v1/blessed': [Errno 21] Is a directory: 'Firmware/Microbit_v1/blessed'`. The directory "blessed" is empty.

I set a breakpoint on [core_exception.py:106](https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/core_exception.py#L106) and the call stack indicates that the error was raised by semgrep-core, not the python wrapper (as it comes from [core_runner.py:382](https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/core_runner.py#L382), which processes the results of the binary, it seems). As I have no idea about the languages used in the core, I did not investigate it further. The problem also occurs on other rules with the "general" language selected, the rule linked below is simply one of the ones from p/security-audit that triggers it.

In search of a minimum set of files needed to reproduce the issue, I found that if you delete all visible folders (on the root of the repository level) except "Firmware" and all hidden files and folders except ".git", the error still occurs. If you delete or rename the .git folder, the error goes away, and if you restore the .git folder, it appears again - so apparently the core binaries do something inside the .git folder that has an influence on this. This is further corroborated by the fact that deleting all the contents of the .git folder also makes the error disappear, so the mere presence of the folder does not suffice to trigger the bug.

If you put a file in the previously-empty "blessed" folder, the error still occurs.

**To Reproduce**
Clone the OpenHaystack repository, (optionally) delete all visible folders except "Firmware" and all invisible files and folders except .git, and run, for example (with example output provided):
```bash
$ semgrep --config="r/python.django.security.audit.xss.template-blocktranslate-no-escape.template-blocktranslate-no-escape"
using config from https://semgrep.dev/r/python.django.security.audit.xss.template-blocktranslate-no-escape.template-blocktranslate-no-escape. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
running 1 rules...
Could not open 'Firmware/Microbit_v1/blessed': [Errno 21] Is a directory: 'Firmware/Microbit_v1/blessed'
ran 1 rules on 33 files: 0 findings
```

**Expected behavior**
I would expect there to be no results. Instead, the message above is shown. ~~Crucially, I do not know if the error has actually prevented execution of the rule on (part of) the files in the repo, or if it is simply cosmetic.~~ See first comment on this issue: the error also stops execution of the rule on the rest of the repo.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
The error occurs (at least) with the pip-installed semgrep as well as the docker container (with the command `docker run --rm -v "${PWD}:/src" returntocorp/semgrep:latest --config="r/python.django.security.audit.xss.template-blocktranslate-no-escape.template-blocktranslate-no-escape"`). I have not attempted to replicate it within the CI runner.

**Comment by malexmave** [comment]
Two addendums:
- Renaming the "blessed" folder to "cursed" makes the error go away :upside_down_face: 
- The error seems to stop execution of the rule evaluation: After the rename, my dummy rule found an additional match that it did not find before.

**Comment by mschwager** [comment]
@brendongo can you look into this? I suspect the Python code is passing a folder as a target down into `semgrep-core` :thinking:

**Comment by malexmave** [comment]
One more thing I noticed yesterday which may help narrow it down: The "blessed" folder is also hosting a git submodule. However, the error still occurs if the submodule contents have been downloaded and the folder is no longer empty.

**Comment by malexmave** [comment]
I had a bit of time on my hands and did some more debugging on this. It looks like the folder is pulled in by [target_manager.py:126](https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/target_manager.py#L126), which uses `git ls-files`. This command, when run on the parent folder of the offending folder, returns "blessed", even though it is an empty folder, likely because it hosts a git submodule. 

This seems to be a general artifact of working with submodules. To see this behavior in action, take the semgrep repository, clone it without pulling in submodules, go to `semgrep-core/src/tree-sitter-lang/` and run `git ls-files`:
```bash
semgrep/semgrep-core/src/tree-sitter-lang$ git ls-files
semgrep-bash
semgrep-c
semgrep-c-sharp
semgrep-cpp
semgrep-dockerfile
semgrep-go
semgrep-hack
semgrep-html
semgrep-java
semgrep-kotlin
semgrep-lua
semgrep-ocaml
semgrep-r
semgrep-ruby
semgrep-rust
semgrep-sqlite
semgrep-tsx
semgrep-typescript
semgrep-vue
```

Et voila, we can replicate the bug:
```bash
semgrep/semgrep-core/src/tree-sitter-lang$ semgrep --lang generic -e '$A == $A'
Could not open 'semgrep-dockerfile': [Errno 21] Is a directory: 'semgrep-dockerfile'
Could not open 'semgrep-typescript': [Errno 21] Is a directory: 'semgrep-typescript'
Could not open 'semgrep-go': [Errno 21] Is a directory: 'semgrep-go'
Could not open 'semgrep-ruby': [Errno 21] Is a directory: 'semgrep-ruby'
Could not open 'semgrep-bash': [Errno 21] Is a directory: 'semgrep-bash'
Could not open 'semgrep-kotlin': [Errno 21] Is a directory: 'semgrep-kotlin'
Could not open 'semgrep-lua': [Errno 21] Is a directory: 'semgrep-lua'
Could not open 'semgrep-sqlite': [Errno 21] Is a directory: 'semgrep-sqlite'
Could not open 'semgrep-java': [Errno 21] Is a directory: 'semgrep-java'
Could not open 'semgrep-cpp': [Errno 21] Is a directory: 'semgrep-cpp'
Could not open 'semgrep-c-sharp': [Errno 21] Is a directory: 'semgrep-c-sharp'
Could not open 'semgrep-tsx': [Errno 21] Is a directory: 'semgrep-tsx'
Could not open 'semgrep-ocaml': [Errno 21] Is a directory: 'semgrep-ocaml'
Could not open 'semgrep-hack': [Errno 21] Is a directory: 'semgrep-hack'
Could not open 'semgrep-vue': [Errno 21] Is a directory: 'semgrep-vue'
Could not open 'semgrep-c': [Errno 21] Is a directory: 'semgrep-c'
Could not open 'semgrep-html': [Errno 21] Is a directory: 'semgrep-html'
Could not open 'semgrep-r': [Errno 21] Is a directory: 'semgrep-r'
Could not open 'semgrep-rust': [Errno 21] Is a directory: 'semgrep-rust'
ran 1 rules on 19 files: 0 findings
```
If the submodule is pulled, git ls-files still only shows the folders. To recurse into the submodules, you have to pass `--recurse-submodules`, at which point the directory itself is no longer listed, only its contents. However, if the submodule has not been pulled down, the system will still list the folder hosting the submodule, even with this switch, so it is not a universal solution. Plus, not recursing into submodules seems to be desired behavior at the moment, judging from the [semgrep CLI reference for `--no-git-ignore`](https://semgrep.dev/docs/cli-usage/).

There are some workarounds involving [the use of `git grep`](https://stackoverflow.com/a/51758365/1232833) (which also does not seem to be recursing into submodules, so it at least shares that desireable property with `git ls-files`), but I do not feel confident that simply replacing the call would not result in more breakage in other places, so I will not be making a pull request. Maybe someone with more experience with the plumbing commands of git knows a way to fix this. This also explains why it only occurs for the `generic` language: It does not exclude files based on the file ending within semgreps target manager.

Hope this helps in tracking this issue down and fixing it. I have submitted a trivial attempt at fixing this by checking if the Path is a directory as a PR - if this cannot be used because it breaks other things, I hope this investigation here is still helpful in tracking things down and fixing them :).

**Comment by ievans** [comment]
Thanks for the debugging work @malexmave! I asked @brendongo to review your PR
