### ISSUE TITLE
Enable test cases via explicit file paths for https://github.com/returntocorp/semgrep-rules/commit/f569fd35478dd84fa3d917e464fa998f73f0c82c

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3662]
The `paths` key in the rule at https://github.com/returntocorp/semgrep-rules/commit/f569fd35478dd84fa3d917e464fa998f73f0c82c limits testing to a specific file path. Being able to run the `--test` suite with `path` key limitations is desirable.

**Comment by ankush** [comment]
What's expected ideal solution to this?

Test runner should just ignore the specified file patterns?
