### ISSUE TITLE
Gracefully handle weird scalars in YAML config

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3666]
Since this crashes the CLI it's difficult to post a playground snippet. The config in question is:

```yaml
rules:
- id: x
  pattern: !true
  message: hello
  languages: [js]
  severity: WARNING
```

The `pattern: !true` is causing some config validation weirdness. I'm seeing the following error:

```
$ python -m semgrep --config /tmp/test.yaml /tmp/test.js 
...
  File "~/semgrep/semgrep/semgrep/rule_lang.py", line 284, in unroll
    f"Invalid YAML tree structure (expected a list, dict, tree, int or str, found: {type(self.value).__name__}: {self.value}"
ValueError: Invalid YAML tree structure (expected a list, dict, tree, int or str, found: TaggedScalar: 
```

This crash causes the App playground to error out. We should more gracefully handle this error and tell the user how to fix it.

**Comment by ievans** [comment]
Relatedly, see @mjambon comments on https://github.com/returntocorp/semgrep-app/pull/3066

**Comment by nbrahms** [comment]
Moving to enhancement as tags are, alas, part of the YAML standard

**Comment by mjambon** [comment]
We need yaml quotes around the pattern e.g. `"!true"`. This works fine in the live editor now, see https://semgrep.dev/s/mjambon:not-true
Closing.
