### ISSUE TITLE
Elixir language support

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#3698]
https://elixir-lang.org/

https://github.com/ananthakumaran/tree-sitter-elixir

https://github.com/wingyplus/tree-sitter-elixir

**Comment by aryx** [comment]
who requested that?

**Comment by fpmosley** [comment]
I'm definitely interested in getting Elixir language support. We have a large Elixir code base at PagerDuty. 

https://www.pagerduty.com/blog/elixir-at-pagerduty/

I'm also interested in contributing to the project by helping to build in support for Elixir.

**Comment by aryx** [comment]
@fpmosley you can have a look at https://semgrep.dev/docs/contributing/adding-a-language/ for help adding a language.
The first step would be to evaluate the two tree-sitter-elixix repo above and check which one is the most complete, and then
add it to ocaml-tree-sitter-semgrep as indicated in the doc.

**Comment by underyx** [comment]
> who requested that?
> 
> 

Initially @jtormey, creator of linear-sync

**Comment by fpmosley** [comment]
@aryx Thanks! I started reviewing the contributing guidelines a couple of days ago. I'm hoping to dedicate some time later this month. 🤞

**Comment by jtormey** [comment]
In case there's opportunity to learn from prior work, Elixir has an open source static analysis tool called [Credo](https://github.com/rrrene/credo). I haven't had much of a chance to work with it, but thought it might be worth mentioning here 🙂

**Comment by aryx** [comment]
Oh good news, seems like there is now an official tree-sitter-elixir! https://github.com/elixir-lang/tree-sitter-elixir

**Comment by aryx** [comment]
It's maintained by the elixir team itself!

**Comment by aryx** [comment]
@fpmosley just following https://semgrep.dev/docs/contributing/adding-a-language/ and using the official repo  https://github.com/elixir-lang/tree-sitter-elixir should be already a good start!

**Comment by fpmosley** [comment]
@aryx Fantastic! I'll swap in the official tree-sitter-elixir repo and resume my testing. I'm already setup from testing out the two non-official ones so I should be able to get this done pretty quickly (probably in the next day or so).  I'll let you know how it goes.

**Comment by jtormey** [comment]
Elixir v1.13 has some incredible tooling improvements that should help with projects like this 👏🏻

> The focus behind Elixir v1.13 has been on tooling, mainly tooling related to code formatting, code fragments, code reflection, and code recompilation. A lot of this functionality will directly impact developers working on large codebases and provide meaningful quality of life improvements for those working on Elixir tooling and environments, such as IDEs, notebooks, etc.

https://github.com/elixir-lang/elixir/blob/master/CHANGELOG.md

**Comment by aryx** [comment]
Well their official support and taking over tree-sitter-elixir is all that we needed.

**Comment by fitzoh** [comment]
@fpmosley any updates?
Still active/interested?

**Comment by fpmosley** [comment]
@fitzoh I'm still interested. I just don't have time to actively work on it. The last thing I did was get this PR merged back in October.
https://github.com/returntocorp/ocaml-tree-sitter-semgrep/pull/260

So we have the OCaml parser for Elixir. Now we just need the additional work done to support Elixir in semgrep.

**Comment by aryx** [comment]
I've pushed a little bit with https://github.com/returntocorp/semgrep/pull/4643 but after that it still remains
to replace all the todos in Parse_elixir_tree_sitter.ml by the correct constructs from the generic AST. This is what takes time
and could use some help.

**Comment by aryx** [comment]
ok just ran some parsing stats for tree-sitter-elixir:
Line count: 729507
Line coverage: 98.428%

So not bad!

**Comment by clintgibler** [comment]
The preeminent (to my knowledge) Elixir security scanning static analysis tool: https://github.com/nccgroup/sobelow

**Comment by fpmosley** [comment]
Hey everyone. I'm back 👋 . I have some free time next week, and was thinking of jumping back in. 

> I've pushed a little bit with #4643 but after that it still remains to replace all the todos in Parse_elixir_tree_sitter.ml by the correct constructs from the generic AST. This is what takes time and could use some help.

Do you still need some help with this? I have an internal Hackweek next week and still haven't planned how I'll use my time.

**Comment by ievans** [comment]
@aryx @clintgibler is it worth marking Elixir as experimental given the progress?

**Comment by aryx** [comment]
Like I said above: "I've pushed a little bit with https://github.com/returntocorp/semgrep/pull/4643 but after that it still remains
to replace all the todos in Parse_elixir_tree_sitter.ml by the correct constructs from the generic AST. This is what takes time
and could use some help."

**Comment by aryx** [comment]
because of all those todos, the parsing stats inside semgrep will be at 0% because we never generate a generic AST from an Elixir CST returned by tree-sitter.
This is usually what takes the most time (e.g., that is what Nat is currently doing for Swift).

**Comment by fpmosley** [comment]
@aryx Thanks for the update. I was unsure if the todos were still needing to be addressed.

**Comment by houllette** [comment]
@aryx @fpmosley Killer work y'all! Just wanted to give a friendly bump on this issue since we use Elixir at Podium and also have an upcoming internal Hackweek - I'd love to purpose contributing to this as an idea to the team(s)! 

Are either of you in the midst of working on those todos in `Parse_elixir_tree_sitter.ml`? Don't wanna step on anyones toes if we jump in!

**Comment by ievans** [comment]
@houllette that's really cool to here. Are you on our slack? There is a contributing channel (https://r2c.dev/slack -> #contributing) that the program analysis team hangs out in -- will probably get you faster responses than Github comments for your hack week!

**Comment by aryx** [comment]
Let us know @houllette how went this hack week!

**Comment by aryx** [comment]
Done!
You should be able to write basic Elixir semgrep rules now.

**Comment by aryx** [comment]
@fpmosley just FYI that we're putting a bit of effort in improving our support for Elixir this and next week. Let me know if you have some feature requests, bugs, whatever that makes writing Elixir rules more pleasant.

**Comment by milanwilliams** [comment]
👋 Hello everyone!

I wanted to share an update about Semgrep's support for Elixir. As we strive to maintain top-notch support for Elixir, we've decided to move it into the Pro Engine. The reality is that improving Elixir requires a significant engineering investment from us, and this shift allows us to continue providing excellent language support in Semgrep.

Don't worry -- accessing Elixir is still a breeze! Simply log in via the CLI (`$ semgrep login`) and you're all set. Elixir, like all our Pro Engine languages, remains FREE for individuals or the first 10 contributors at your org. 

Any questions? I'm here to help. Happy coding! 🚀
