### ISSUE TITLE
Specify --json and --sarif together to get both types of output from 1 command

### ISSUE THREAD

**Issue by raghavjain3** [semgrep/semgrep#3699]
**Is your feature request related to a problem? Please describe.**
Users have to run 2 separate CLI commands to get a sarif output and json output

**Describe the solution you'd like**
Be able to use --json and --sarif in the same CLI command to output 2 files

**Describe alternatives you've considered**
Alternative now is to run 2 separate commands

**Comment by emjin** [comment]
Priority?

**Comment by raghavjain3** [comment]
> Priority?

Medium

**Comment by gabpil45** [comment]
Hi, Can we reopen this? We would like to use it to utilize the JUnit output to post it to Jenkins and the Sarif/JSON to the github API.

Thanks,
G

**Comment by ievans** [comment]
Closing as duplicate of https://github.com/returntocorp/semgrep/issues/3699, let's track there

**Comment by ahickey-sfdc** [comment]
Bumping to keep this on radar.  (would like --vim and --sarif)

**Comment by ahickey-sfdc** [comment]
Should this be tracked in https://github.com/returntocorp/semgrep/issues/3019?

**Comment by ievans** [comment]
Oops, that's what I meant to do @ahickey-sfdc. Let's track in #3019 which is the more general version of this.
