### ISSUE TITLE
Company Logo mis represented

### ISSUE THREAD

**Issue by dan5382** [semgrep/semgrep#3710]
**Describe the bug**
The company icon in the upper left-hand corner is less vibrant than it is. Not sure what happened, but it looks like transparency on the logo mark.

**To Reproduce**
Go to Semgrep.dev and look to the upper left-hand corner of your browser window.

**Expected behavior**
A clear and vibrant logo that we intended.

**Screenshots**
![image](https://user-images.githubusercontent.com/2009327/128955066-fe96c687-5445-49a0-95aa-d95122cca34a.png)

**What is the priority of the bug to you?**

- [ ] P0
It should be a quick fix, and misrepresenting our brand is def a P0 for design.

**Comment by adamboros** [comment]
merging this to already opened ticket at [Semgrep-app](https://github.com/returntocorp/semgrep-app/issues/3024)
