### ISSUE TITLE
Typescript parse error with default prop getter

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#3721]
From an internal codebase:

- Works: https://semgrep.dev/s/Gwjp/
- Doesn't work: https://semgrep.dev/s/5J5A/

I'm not sure what this Typescript ` = defaultPropGetter` feature is called, or where it's documented, but the code compiles correctly.

**Comment by mschwager** [comment]
From @nbrahms:

> Specifically, it's object destructuring with default assignment: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment and https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#prod-AssignmentElement

**Comment by aryx** [comment]
seems to work now! probably update to latest tree-sitter-typescript fixed the issue.
