### ISSUE TITLE
PHP - MetaVariable Matching Inconsistency

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3741]
**Describe the bug**
Considering the following pattern: `$VAR = $ANYTHING . $FOO . $ANYTHING_ELSE;`, with `$FOO` being a `metavariable-regex` matching `foo`

`$b = "hello" . "world" . "foo" . "world";` matches but `$c = "hello" . "world" . "foo" . "hello" . "world";` does not

**To Reproduce**
https://semgrep.dev/s/WOzy

**Expected behavior**
`$c = "hello" . "world" . "foo" . "hello" . "world";` should match the pattern

**What is the priority of the bug to you?**
P1: important to fix or quite annoying

**Comment by IagoAbal** [comment]
I guess this is just to enable associativity for `.` perhaps? That would be quick.
