### ISSUE TITLE
Taint tracking produces duplicate findings

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3742]
**Describe the bug**
Taint mode can produces duplicate findings

**To Reproduce**
https://semgrep.dev/s/WOzo

**Expected behavior**
There should not be duplicate findings

**Screenshots**
<img width="569" alt="Screenshot 2021-08-21 at 21 06 15" src="https://user-images.githubusercontent.com/1668843/130332443-fc2dfd23-85b0-4e6f-8e65-8f047887af9e.png">

**What is the priority of the bug to you?**

P1: important to fix or quite annoying

**Environment**
Semgrep.dev & CLI 0.62.0 on MacOSX (Installed via Homebrew)

**Comment by IagoAbal** [comment]
The way taint tracking works it is non-trivial to guarantee that there are no duplicates. Right now, internally, we use search-mode queries to compute the ranges of sources, sanitizers, and sinks. Then if e.g. an expression is inside a `pattern-sources` range, then we consider it a source of taint; and, if it is inside a `pattern-sinks` range, we consider it a sink. We have some mechanisms to remove duplicates, but they don't work when a single Generic "instruction" translates into multiple Dataflow IL instructions.

**Comment by IagoAbal** [comment]
Another example reported by @emjin: https://semgrep.dev/s/d0dZ/

**Comment by IagoAbal** [comment]
I will let the engine produce the duplicates and filter these duplicates at the end. Unless there are too many taint matches, it should not cause perf problems. There may be a better solution but I need to think more on it and discuss it with some colleagues.

**Comment by erwanlr** [comment]
Fine by me ;) I think the max duplicates per issue I had so far is 3

Btw, I noticed another issue (ticket linked) when trying to reduce duplicate output by adding functions such as `isset(...)` as sanitizer (which works in term of eliminating some duplicates, but then some code won't match :o)
