### ISSUE TITLE
--emacs flag doesn't include the rule's message, only code snippet

### ISSUE THREAD

**Issue by huonw** [semgrep/semgrep#3744]
**Describe the bug**

The `--emacs` flag doesn't include the human readable `message` for failing rules in its output, which makes it harder to work out what the appropriate fix is.

(Thanks for semgrep; we're using it for both security analysis and also a few custom rules to catch (non-security) mistakes/typos we keep making. Works well!)

**To Reproduce**

Run `semgrep` with the `--emacs` flag. For instance, in the semgrep-rules repo:

```shell
semgrep --emacs -c yaml/semgrep/missing-message-field.yaml yaml/semgrep/missing-message-field.test.yaml
```
```
running 1 rules...
yaml/semgrep/missing-message-field.test.yaml:3:3:warning(missing-message-field):- id: unchecked-subprocess-call
ran 1 rules on 1 files: 1 findings
```

This is showing the relevant code snippet (`- id: unchecked-subprocess-call`), but no human readable context.

**Expected behavior**

The output should include the human readable context included in the `message` field, similar to the `--vim` flag:

```shell
semgrep --vim -c yaml/semgrep/missing-message-field.yaml yaml/semgrep/missing-message-field.test.yaml
```
```
running 1 rules...
yaml/semgrep/missing-message-field.test.yaml:3:3:W:yaml.semgrep.missing-message-field:This rule does not have a message. Semgrep requires that
rules have a message. Include a message to explain what the rule does.
Consider writing a message that explains why this is an issue and
how to fix it.

ran 1 rules on 1 files: 1 findings
```

(I've filed a separate https://github.com/returntocorp/semgrep-rules/issues/1431 about the message being broken across multiple lines even with the nominally single-line `--vim` output format.)

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
macOS, semgrep installed from homebrew, version 0.61.0

**Comment by brendongo** [comment]
@underyx did you add emacs support before? I can't seem to find documentation on what format it expects linting output to look like.

**Comment by underyx** [comment]
Nope, I never heard of this flag before!

**Comment by mschwager** [comment]
The `--emacs` functionality was originally an external contribution from @Ruin0x11: https://github.com/returntocorp/semgrep/pull/2495

When implementing the `--vim` functionality I was confused by `--emacs` lack of using the rule's message. Here's the context for why it is the way it is: https://github.com/returntocorp/semgrep/pull/2705#issuecomment-791881955.

**Comment by huonw** [comment]
Thanks for digging up some history; that doesn't seem to discuss why it's missing the rule's message specifically. I don't think that's required by emacs' error message matching, for instance, here's a little experiment with GCC, which emacs is happy to consume directly in its compilation-mode:

```
$ cat foo.c
i wrote some bad syntax here
$ gcc foo.c
foo.c:1:1: error: unknown type name 'i'
    1 | i wrote some bad syntax here
      | ^
foo.c:1:9: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'some'
    1 | i wrote some bad syntax here
      |         ^~~~
foo.c:1:9: error: unknown type name 'some'
```

That is, the description is included on the 'main' line, and even code snippets.

**Comment by brendongo** [comment]
Is there some thing external we need to modify if we change `--emacs` so those using the emacs plugin(? is there a semgrep emacs plugin?) keeps working? @Ruin0x11

**Comment by huonw** [comment]
There's no plugin published in the package registered that I can find, but there is https://github.com/Ruin0x11/semgrep.el . Looking over the code, it doesn't seem to customise emacs' compilation output functionality so my sense is the answer is 'no', but @Ruin0x11 would have to confirm.

**Comment by Ruin0x11** [comment]
It should be fine to put the snippet on a new line like @huonw's example. There are many different matchers for compilation messages built into Emacs, and I just chose GCC's since it was pretty common. As long as one of the lines matches the error jumping will still work.

**Comment by FLiliequist** [comment]
Can I have a go at this issue? If I understood correctly all that is needed is to add the rule's message to the output when using the <code>--emacs</code> flag or am I missing something?

**Comment by brendongo** [comment]
yeah seems like that's all that's needed
