### ISSUE TITLE
Incorrect pattern matching - When return object is a class with an import - Results are not correct

### ISSUE THREAD

**Issue by tilperion2** [semgrep/semgrep#3748]
**Describe the bug**
Tested on of R2C reles(unrestricted-request-mapping) and found this issue:
When return class of method in pattern matching have class not as void or Java primitives, but class with import, then check is not working properly and False positive is reported. Look for 3rd reported line in example below. 

I suppose in this case return class is not correctly checker/matched in $RETURNTYPE section of the rule. 

Looks like reproduced only in lates v0.62.0

**To Reproduce**
https://semgrep.dev/s/nkx1

**Expected behavior**
Rule working correctly, imported classes in return statement are matched in a right way. 
Rules with same $RETURNTYPE should not be in results, no FP should be reported. 

Possible future improvement - Use classes with imports/real class names in semGrep.dev(https://semgrep.dev/r?q=unrestricted-request-mapping) and possibly in your tests in the code.

**Screenshots**
![image](https://user-images.githubusercontent.com/16115976/130622597-bc9898a6-d48b-4fe1-9c9c-f80706ae9a8c.png)

**What is the priority of the bug to you?**
- [ ] P1: important to fix or quite annoying

**Environment**
Latest v0.62.0

**Comment by IagoAbal** [comment]
This seems to be the commit that introduced the bug (PR #3684):
```
commit 1fd2534dbe27a4b0db79f8c997815a03eab8a70d
Author: Yoann Padioleau <pad@returntocorp.com>
Date:   Fri Aug 6 14:48:15 2021 +0200

    Refactor m_name, factorize more code (#3684)
```

**Comment by tilperion2** [comment]
Have found the same issue for **OWASP Top 10 rule** from SemGrep rulepack.
Problem still looks the same - when return object is imported class, it is incorrectly matched by pattern/pattern-not evaluation. 

See example below:
https://semgrep.dev/s/Jxdj

**Comment by IagoAbal** [comment]
cc @aryx
