### ISSUE TITLE
Pattern-either works wrong with metavariable-regex. 

### ISSUE THREAD

**Issue by tilperion2** [semgrep/semgrep#3755]
**Describe the bug**
1. When you have metavariable-regex in one of pattern-either cases/branches - it is unable to detect this case if there is no second case present in the file, even only in the comments. 

2. How is it possible that **comments** affect rule execution?

**To Reproduce**
First:
https://semgrep.dev/s/YXwD - works as desired at a first glance.
Let`s comment second either pattern
https://semgrep.dev/s/65wW - working fine as well. Fine, we have just commented coule lines
Now **REMOVE** lines for second either patten:
https://semgrep.dev/s/owox - Wrong! First pattern does not trigger anymore.

**Expected behavior**
Both cases/patterns from either expressions picked up by SemGrep. 

**Screenshots**
Looks right, but comments affecting the result:
![image](https://user-images.githubusercontent.com/16115976/130860743-f205339a-eee0-4181-af81-9b6282c67656.png)

Wrong:
![image](https://user-images.githubusercontent.com/16115976/130860797-904a0292-35e5-4514-bd89-bd6101f88842.png)

**What is the priority of the bug to you?**
- [ ] P1: important to fix or quite annoying

**Environment**
observable > v0.61.0

**Comment by emjin** [comment]
I think I know why! My suspicion is that Semgrep is incorrectly skipping this file under the belief that the string `getMd2Digest` must be present. We use a simple string search to skip files when possible. I don't know why this is going wrong, though. Here's a minimal example: https://semgrep.dev/s/96NR @aryx in case you can think of a change you made recently that would affect this
