### ISSUE TITLE
Support ellipsis in Rust `struct` items

### ISSUE THREAD

**Issue by robre** [semgrep/semgrep#3759]
https://semgrep.dev/s/N8pL

When Trying to match the following code:
```rust
struct Foo {
    bar: u32,
    baz: String
}
```

with the following pattern:
```rust
struct $FOO {
  $VAR: $TYPE,
  ...
}
```

or even just
```rust
struct $FOO {
  ...
}
```

An error "_Error parsing Rust pattern: (Failure "error parsing the pattern")_" is returned.
The pattern
```rust
struct $FOO {
  $VAR1: $TYPE1,
  $VAR2: $TYPE2
}
```
does successfully match the whole code snippet.

Am I using the ellipses wrong? I would expect each of the previous patterns to match the whole struct.

**Comment by ievans** [comment]
Rust is still under development (https://semgrep.dev/docs/status/ ) so this is probably a todo on the road to full support. Thank you for the clear write up!

**Comment by robre** [comment]
added some additional issues (#3760 #3761 #3762 #3763 #3764 #3765) by taking examples from  the rust doc https://doc.rust-lang.org/book/ and trying some patterns on them. 
If there exists some writeup on how to approach implementing fixes for issues like those I would consider trying to fix them myself, but I have not much clue about ocaml, or grammar stuff.

**Comment by emjin** [comment]
Thank you for all the issues! Currently, Rust is primarily a community effort. We'd love to have you as well! Our [docs](https://semgrep.dev/docs/contributing/contributing-code/) give an overview of the codebase, which might be a nice starting off point. There's also an existing thread where interested contributors have been chatting: https://github.com/returntocorp/semgrep/issues/1338, and if you join [our community slack](https://r2c.dev/slack) you can ask any questions you have in the contributing channel.
