### ISSUE TITLE
Autofix only outputs first line of BODY

### ISSUE THREAD

**Issue by sk-** [semgrep/semgrep#3767]
**Describe the bug**
The autofixed code will only output the first line of the matched class body.

I even tried using `$...BODY`, but that does not generate any matches, which is strange because in https://github.com/returntocorp/semgrep/issues/3170 was mentioned this was fixed. But maybe this a Python specific issue.

**To Reproduce**
https://semgrep.dev/s/8ROB

Note how `bar` (the second statement) got lost in the matched class

**Expected behavior**
The whole class body should be outputted in the autofixed code.

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

Validated the bug is present in semgrep.dev and in the version 0.63.0.

**Comment by sabrinabrogren** [comment]
Thanks for the bug report, @sk- ! It seems like there are two bugs here, one with autofix and one with ellipsis-metavariable. Autofix is an experimental feature, so just a heads up that it might take us longer to fix. I created a [separate issue for ellipsis-metavariable in Python](https://github.com/returntocorp/semgrep/issues/3771) - what priority would you say this is for you?

**Comment by ievans** [comment]
Looks fixed to me! As of 0.75 or earlier
