### ISSUE TITLE
Protect all network calls with timeout + good error message

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3769]
In the past, we've had some semgrep runs taking up to 6 hours, but would normally would take just a few minutes. See issue #3413.

To prevent jobs from taking too long without making any progress, let's set timeouts on the commands or functions that rely on the network. Examples of such operations include:

* cloning the target git repo
* fetching semgrep rules from a registry
* posting scan results
* posting telemetry data

Shell scripts (e.g. CI) can use the `timeout` command, e.g.:
```bash
$ timeout 1 sleep 2
$ if [[ $? = 124 ]]; then echo "timeout :("; fi
timeout :(
```

This task involves:
1. Identifying all the command or function calls that depend on the network.
2. Protecting all these calls with a reasonable timeout and error message.

**Comment by brendongo** [comment]
This is solved I think. At least I havent heard of 6 hour runs in a while. We actually do have timeouts and have semgrep rules that alert when network calls are made without one. And we have timeouts on shelling out to git. I think the timeouts were solved by https://github.com/returntocorp/semgrep-action/pull/444 but I don't have any proof to back up this claim.

**Comment by brendongo** [comment]
Or it was https://github.com/returntocorp/semgrep/pull/4208#pullrequestreview-798012838

**Comment by brendongo** [comment]
I think can mark this as closed
