### ISSUE TITLE
Improve uncaught exception reports

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3775]
Problems:
* Some stack traces are useless because they're incomplete or missing. This is due to exceptions being caught and turned into ordinary data without capturing the stack trace at that point.
* Uncaught exceptions are currently printed without other application-specific context: the user doesn't know what piece of input triggered the error/bug.

Recommendations:
* In general, exception catch-alls (`try ... with e -> ...`) would have to capture the stack trace or report it somehow. The [trax](https://github.com/mjambon/trax) library can be used for this, for example when an error needs to be marshaled and passed to a calling process or when we have multiple jobs running in parallel and we want to report the errors only after all the healthy jobs are done.
* Ideally, only one exception catch-all should exist, at the bottom of the call stack.
* Specific exception catchers (`try ... with Parsing_error x -> ...)`) usually don't need to capture the stack trace because we know what the exception means.
* When catching an unexpected exception, wrap it with some application-specific context: language, rule ID, target file path. These fields are not always defined but they usually are.

Task:
* review and clean up exception handling code in semgrep-core
* add context to error messages

**Comment by aryx** [comment]
This was fixed by martin's recent Exception.ml in pfff. See for example #5567
