### ISSUE TITLE
Java 15+ text blocks not supported,error parsing java classes

### ISSUE THREAD

**Issue by tilperion2** [semgrep/semgrep#3787]
**Describe the bug**
Java 15+ text blocks([link](https://www.baeldung.com/java-text-blocks)) not supported by SemGrep?  

**To Reproduce**
https://semgrep.dev/s/5JbW

**Expected behavior**
New Java specs should be supported, including new Java text blocks. 

**Screenshots**
![image](https://user-images.githubusercontent.com/16115976/131514221-7598d98b-640b-47ec-af6d-0fa06741f56b.png)

**What is the priority of the bug to you?**

- [ ] P1: important to fix or quite annoying

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by tilperion2** [comment]
Hi, any update with this issue? It should be getting more and more popular, as Java 17 already released.

**Comment by tilperion2** [comment]
@aryx, @emjin any updates for this feature request? Thanks

**Comment by aryx** [comment]
The problem is in the tree-sitter-java grammar we are using: https://github.com/tree-sitter/tree-sitter-java/blob/8a6ab8e8adb119bc35b133040077b60f6cf539ea/grammar.js#L153
We need to make the issue upstream.

**Comment by aryx** [comment]
This requires possible to extend the Java lexer in tree-sitter-java. The lexing rules for this """ and escaping seem not trivial, so this might take some time to implement this feature.
