### ISSUE TITLE
Taint mode can express cases where two sources of taint need to be present

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3790]
For AngularJS, we want to write a rule that bans `$sce.trustAsJs($scope.$INPUT)`, where both `$sce` and `$scope.$INPUT` may be aliased in various forms. Currently, it is not possible to require two sources of taint to reach a sink.

Workaround currently used is: https://semgrep.dev/s/emjin:trust-as-source

**Comment by emjin** [comment]
Alternate (probably better) solution: https://github.com/returntocorp/semgrep/issues/3207

**Comment by nbrahms** [comment]
This has been worked around
