### ISSUE TITLE
URL with self signed certificate cannot be used as repository

### ISSUE THREAD

**Issue by vdbaan** [semgrep/semgrep#3794]
**Describe the bug**
The config is stated that it can be a registry entry, a url, or a file, folder. 
When using a secure URL that uses a self signed certificate, it will not load

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
- use docker image `nwtgck/self-signed-https` as fake https server
- start the docker image 

- run `docker run --rm -v "${PWD}:/src"  returntocorp/semgrep -f https://docker.for.mac.localhost:4443/myrules --debug`

**Expected behavior**
The rules executed against the code

**Screenshots**
See screenshot
<img width="1440" alt="Screenshot 2021-09-01 at 12 49 03" src="https://user-images.githubusercontent.com/2207005/131667054-efa878bc-a176-4e98-865f-bd70ba851378.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
docker

**Comment by brendongo** [comment]
Does this work using semgrep locally (not in docker)?

**Comment by vdbaan** [comment]
Unfortunately no:

```
$ semgrep -f https://localhost:4443/myrules --debug .
trying to download from https://localhost:4443/myrules
using config from https://localhost:4443/myrules. Visit https://semgrep.dev/registry to see all public rules.
downloading config...
Failed to download config from https://localhost:4443/myrules: HTTPSConnectionPool(host='localhost', port=4443): Max retries exceeded with url: /myrules (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
running 0 rules from 0 config  (1 config files were invalid)
no valid configuration file found (1 configs were invalid)
```

When I look in the code where the config is downloaded (`config_resolver.py:394`) I see that the parameter `verify` is not used, which can be set to either False (no not verify the cert), or a pem to verify against.

**Comment by brendongo** [comment]
I'm not sure we want to support exposing such an option. For this use case can we just curl with the desired options and pass in the file to semgrep? But I might be misunderstanding this use case. @mschwager thoughts?

**Comment by mschwager** [comment]
I don't recommend disabling SSL verification in production usage. However, Semgrep uses Python `requests` on the backend for HTTP request functionality, which allows for a few options here:

1. You can sign your certificate with a CA and use that CA bundle for verification when making requests: https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification (`REQUESTS_CA_BUNDLE`).
2. You can also disable SSL verification with an environment variable: https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module (set `CURL_CA_BUNDLE` to an empty string). This would look something like `CURL_CA_BUNDLE="" semgrep -f ...`.

Obligatory, WARNING: do not disable SSL verification in production usage. This is insecure and your HTTP connections will not be safe.

**Comment by nbrahms** [comment]
Hmm, I think the user in this case should add the self-signing root to their local ssl certs. This does mean that they should not run with the docker image.

**Comment by nbrahms** [comment]
As a workaround @vdbaan , you may want to:

```sh
curl -CAfile path/to/cert https://docker.for.mac.localhost:4443/myrules > semgrep.yml
docker run --rm -v "${PWD}:/src" -f semgrep.yml returntocorp/semgrep
```

**Comment by nbrahms** [comment]
@vdbaan I know this may not be the outcome you're looking for, but I think we should probably close this as a wont-fix due to the unique security aspects involved here, and the fact that copying the repo should make things work.

Please do re-open if you disagree with my thinking here. And thanks for the report!
