### ISSUE TITLE
semgrep.dev bug report

### ISSUE THREAD

**Issue by RamiAwar** [semgrep/semgrep#3798]
https://semgrep.dev/s/34pG

**Comment by ievans** [comment]
@RamiAwar this looks like a valid core crash to me -- I'll re-open and tag @mjambon to take a look?

**Comment by RamiAwar** [comment]
Oh yeah sure, I felt like I was being a noob 😅

**Comment by emjin** [comment]
That is an awful error message, and we should definitely fix that. The problem is that you can't have a `pattern-not` without a pattern. For example, https://semgrep.dev/s/lxn6 will work without an error.

**Comment by RamiAwar** [comment]
Yes I was still exploring Semgrep for the first time, was just trying to get that to work. Ended up doing something different! Thanks for the help!
