### ISSUE TITLE
Improve error message for pattern with only a pattern-not

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#3802]
We have

```
| R.And (t, xs) ->
      let ys = Common.map_filter remove_not xs in
      if null ys then failwith "null And after remove_not"
      else Some (R.And (t, ys))
```

For a user this becomes 

![image](https://user-images.githubusercontent.com/5942585/131746595-4fd8b74a-3dc1-44b9-966c-4ebcff18e30a.png)

https://semgrep.dev/s/34pG

**Comment by emjin** [comment]
See https://github.com/returntocorp/semgrep/issues/3798

**Comment by DrewDennison** [comment]
my eyes 🙈

**Comment by emjin** [comment]
Still a thing :(

**Comment by aryx** [comment]
This has been improved:
{"code":2,"level":"error","message":"[ERROR] Rule parse error in rule asd:\n you need at least one positive term (not just negations or conditions)","rule_id":"asd","type":"Rule parse error"}

**Comment by aryx** [comment]
see #5234
