### ISSUE TITLE
[PHP] Generic with metavariable-pattern: FN & FP

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#3805]
**Describe the bug**
https://semgrep.dev/s/DwZq

- Line 7 should not match
- With a pattern of pattern: `echo baz(...);` Line 2 does not match but 5 does

**Expected behavior**
There should not be any False Positive and Negative with such basic pattern/s

**What is the priority of the bug to you?**

P0: blocking your adoption of Semgrep or workflow

**Comment by emjin** [comment]
Tagging @mjambon to see if he has any suggestions. In general, generic is going to be more limited because we aren't parsing into the AST.

**Comment by mjambon** [comment]
oh, it's a bug in our php parser or matcher. Here's a simpler example: https://semgrep.dev/s/mjambon:php-ughhh
![image](https://user-images.githubusercontent.com/343265/131901496-562d6d90-4a9e-4d2d-b1b2-a6c5f54c5631.png)

**Comment by IagoAbal** [comment]
I am no PHP expert to know if this is correct, but
```
value
```
is parsed as `echo("value")`.

**Comment by IagoAbal** [comment]
Ideally we want to restrict the matches to those attributes whose values match `"<?php ..."`. But we can't do this directly because we also need `$...TEXT` to capture the `<?php` text.

**Comment by IagoAbal** [comment]
Such as in https://semgrep.dev/s/P8RE or https://semgrep.dev/s/JjLZ, @mjambon any trick to make it match `<foo attr="value" bar="<?php echo baz($_POST['bar']); ?>" />` too ?

**Comment by mjambon** [comment]
@IagoAbal ok, I understand the ghost echo now.

I tried filtering with a regexp, and that part works: https://semgrep.dev/s/K846
The problem is that the generic mode (spacegrep) doesn't return all the possible matches. So when there are multiple attributes, the pattern `<$TAG ... $ATTR = "$...TEXT" ...>` will just match the first attribute.

**Comment by mjambon** [comment]
@erwanlr this is the best I could come up with for now: https://semgrep.dev/s/652j
i.e. a single generic pattern:
```
< ... = "<?php ... echo ... ?>" ...>
```

**Comment by IagoAbal** [comment]
I guess the real fix here is to make Spacegrep return "all possible" matches instead of just the shortest one.

**Comment by emjin** [comment]
If users just want the matches, then they might be overwhelmed with results.

**Comment by IagoAbal** [comment]
> If users just want the matches, then they might be overwhelmed with results.

Wouldn't that be an argument for not returning all the matches in Semgrep as well? IMO it's unintuitive that Spacegrep works differently than Semgrep in this respect.

**Comment by emjin** [comment]
With Semgrep, the matches are usually what the user wants, though. In generic, I feel like sometimes it's a guess. For instance what if someone matches `foo $X` against `foo 3 + foo 5`? It also seems unintuitive for this to match `foo 3`, `foo 3 +`, and `foo 3 + 5`. (Sorry if I misunderstood and this would not happen)

**Comment by IagoAbal** [comment]
To the best of my knowledge, matching `foo $X` would just return two matches: `foo 3` and `foo 5`.

But if we did the same as Semgrep, `foo ... $X` would behave as you described. That wouldn't be a very smart pattern to write, but perhaps we should be careful with `...`.

**Comment by IagoAbal** [comment]
@erwanlr what about this https://semgrep.dev/s/1G2Q ?

**Comment by aryx** [comment]
seems related to #5443

**Comment by aryx** [comment]
This works now: https://semgrep.dev/s/Ox3p
