### ISSUE TITLE
Ruby rules don't match parameter-less calls

### ISSUE THREAD

**Issue by edamamez** [semgrep/semgrep#3811]
**Describe the bug**
When writing a Ruby rule, Semgrep returns a false negative on method calls with no parameters.
(link to Slack discussion: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1630341006011600)

**To Reproduce**
https://semgrep.dev/s/brbQ

**Expected behavior**
A parameter-less call should be able to be matched.

**Screenshots**
![Screenshot of semgrep rule in ruby where foo method with no parameters doesnt match](https://user-images.githubusercontent.com/36808054/131933361-45f6a35d-bb4d-4ffd-bd8c-3bec880f47e3.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/SUP-35/ruby-rules-dont-match-parameter-less-calls.
