### ISSUE TITLE
Add invalid rule name to semgrep --validate sarif output

### ISSUE THREAD

**Issue by anuraagbaishya** [semgrep/semgrep#3816]
**Is your feature request related to a problem? Please describe.**
When using semgrep rule validator in sarif mode (`semgrep --validate --config semgrep-rules/ --sarif`) the output does not contain the name of the rule that was invalid. The non sarif version output contains the name of the rule
Eg:
```
{
    "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    "runs": [
        {
            "invocations": [
                {
                    "executionSuccessful": true,
                    "toolExecutionNotifications": [
                        {
                            "descriptor": {
                                "id": "InvalidRuleSchemaError"
                            },
                            "level": "error",
                            "message": {
                                "text": "[{'pattern': 'print(...)'}] is not of type 'string'"
                            }
                        },
                        {
                            "descriptor": {
                                "id": "SemgrepError"
                            },
                            "level": "error",
                            "message": {
                                "text": "Please fix the above errors and try again."
                            }
                        }
                    ]
                }
            ],
            "results": [],
            "tool": {
                "driver": {
                    "name": "semgrep",
                    "rules": [],
                    "semanticVersion": "0.64.0"
                }
            }
        }
    ],
    "version": "2.1.0"
}
```

We are building a system that allows users to add semgrep rules to their git repositories and the repositories are scanned against these rules. We need to inform the developers of the repository if their rules are invalid. Since this is done by automation we would prefer to use the sarif output since its structured. Since the rules will be in their own directory and there might be many rules in the repository we will likely add multiple configs to the validation run (`semgrep --validate --config semgrep-rules/rule1 --config semgrep-rules/rule2 --sarif`)

**Describe the solution you'd like**
Along with the errors in the rule which are present in the output already, the name of the rule should also be present in the output

**Describe alternatives you've considered**
We have considered using the non sarif output which has the name of the rule that is invalid. But since info will be used by automation, the non sarif version being unstructured text gets exponentially difficult to parse as more rules are validated.
Eg:
```
semgrep error: Invalid rule schema
  --> bad-rule.yml:4
4 |   - pattern:
5 |         print(...)
6 |   message: Found print() statement. Consider using a logger.

[{'pattern': 'print(...)'}] is not of type 'string'
```

**Comment by nbrahms** [comment]
Synced in https://linear.app/r2c/issue/PA-332/add-invalid-rule-name-to-semgrep-validate-sarif-output

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-359/add-invalid-rule-name-to-semgrep-validate-sarif-output.
