### ISSUE TITLE
Testing silently ignored if inside `.semgrep` directory

### ISSUE THREAD

**Issue by sim642** [semgrep/semgrep#3820]
**Describe the bug**
I have a `.semgrep` directory in my project with a bunch of rule files (e.g. `.semgrep/myrule.yml`). I decided to add corresponding rule tests (e.g. `.semgrep/myrule.ml`), but running `semgrep --test .semgrep/` totally ignores them all:
```
0 yaml files tested
check id scoring:
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
final confusion matrix: TP: 0 TN: 0 FP: 0 FN: 0
--------------------------------------------------------------------------------
```

In desperation I renamed the directory to `foo` and ran `semgrep --test foo/` and suddenly the tests actually ran.

Is there something special and undocumented about calling the rules directory `.semgrep` that prevents tests inside it from being run?

**To Reproduce**
See previous description.

**Expected behavior**
The tests run without having to rename the directory. Or at least any output about why no files were tested despite them all being there.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Version 0.64.0 installed via pip.

**Comment by nbrahms** [comment]
Synced in https://linear.app/r2c/issue/PA-331/testing-silently-ignored-if-inside-semgrep-directory

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-358/testing-silently-ignored-if-inside-semgrep-directory.

**Comment by sim642** [comment]
Ping.
