### ISSUE TITLE
OCaml pattern not found in functor

### ISSUE THREAD

**Issue by sim642** [semgrep/semgrep#3821]
**Describe the bug**
The pattern is not found inside the body of an OCaml functor while it is found from a normal module.

**To Reproduce**
https://semgrep.dev/s/N8B1/

**Expected behavior**
Patterns are also found in functors.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by nbrahms** [comment]
Synced in https://linear.app/r2c/issue/PA-330/ocaml-pattern-not-found-in-functor

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-357/ocaml-pattern-not-found-in-functor.
