### ISSUE TITLE
OCaml non-regex pattern not found if unrelated module type include present

### ISSUE THREAD

**Issue by sim642** [semgrep/semgrep#3822]
**Describe the bug**
I wrote a pattern to find wildcard OCaml exception handlers in two ways: using a pattern that directly uses `_` and another which uses a metavariable and a regex to match the `_`.
If `include` is used in an unrelated `module type` definition, then the first pattern somehow stops working, while the latter still works.

**To Reproduce**
Module type include present: https://semgrep.dev/s/kknz/ (only regex rule matches).
Module type include removed: https://semgrep.dev/s/w1BX/ (both rules match).

**Expected behavior**
Both rules match in both cases. Unrelated module type definitions should in no way affect the matching of other code. If a single module type include is present, then I can no longer rely on semgrep finding anything it seems.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by nbrahms** [comment]
Tracked in https://linear.app/r2c/issue/PA-329/ocaml-non-regex-pattern-not-found-if-unrelated-module-type-include

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-356/ocaml-non-regex-pattern-not-found-if-unrelated-module-type-include.

**Comment by sim642** [comment]
Ping.
