### ISSUE TITLE
Autofix: Issue with replacing python tuples? 

### ISSUE THREAD

**Issue by fwip** [semgrep/semgrep#3832]
Slack discussion: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1631066079031800

**Describe the bug**
Difficulty matching tuples/parenthesized expressions (?) when writing autofix rules for python. To my eyes, it appears that the trailing `)` or `,))` written in the pattern are not matched/replaced when using the autofix feature.  I would like to figure out how to either capture these in the metavariables or match&discard them.

**To Reproduce**
https://semgrep.dev/s/fwip:wip-permalink-removal

**Expected behavior**
The output should have the specified number of parentheses and remain syntactically-valid python code. 

**Screenshots**
The green arrows in this screenshot point to the part of the pattern that is not getting captured/replaced.
<img width="366" alt="Screen Shot 2021-09-07 at 7 43 05 PM" src="https://user-images.githubusercontent.com/190414/132438127-2f173c9c-e3d1-4fa8-a895-38c96d4ba213.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

semgrep.dev and local on mac via brew (version 0.64.0).

**Comment by nbrahms** [comment]
Tracked in https://linear.app/r2c/issue/PA-328/autofix-issue-with-replacing-python-tuples

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-352/autofix-issue-with-replacing-python-tuples.
