### ISSUE TITLE
PHP Arrow Functions Parsing Error

### ISSUE THREAD

**Issue by ristomcgehee** [semgrep/semgrep#3848]
Hi, we've been using Semgrep on one of our PHP repos at my company. We encountering a parsing error for the arrow function syntax that was introduced in PHP 7.4.

https://semgrep.dev/s/chrismcgehee:lambda_not_parsing

https://www.php.net/manual/en/functions.arrow.php

**Comment by ievans** [comment]
@chrismcgehee thanks for filing this issue! Could you share the relative priority to your team? is it a blocker for using semgrep (p0), a major issue you need addressed soon (p1), or a minor annoyance (p3)?

**Comment by ristomcgehee** [comment]
I'd say a p3. It's just giving a warning in our pipeline, so it's not blocking us.

**Comment by nbrahms** [comment]
Tracked in https://linear.app/r2c/issue/PA-327/php-arrow-functions-parsing-error

**Comment by jyotty** [comment]
Hello all, we started using semgrep on a large PHP application where I work and this is preventing us from getting complete coverage. So now there's a few more people in the world getting bit by this.

**Comment by aryx** [comment]
This works now! https://semgrep.dev/s/chrismcgehee:lambda_not_parsing?develop=true

**Comment by ristomcgehee** [comment]
I'm no longer getting a parsing error, which is good, but it seems arrow functions are still preventing matches in some cases. I've created https://github.com/returntocorp/semgrep/issues/5594 for this.
