### ISSUE TITLE
SemGrep does not resolve package of Java class/base class if there is no import.

### ISSUE THREAD

**Issue by tilperion2** [semgrep/semgrep#3855]
**Describe the bug**
For Java classes that extend base class in the same package, SemGrep does not resolve full class and base class name, so rules that detects full class import name will not detect this case.
This also relates to class name/full class name. See second branch in test semGrep rule below.

**To Reproduce**
https://semgrep.dev/s/grdn

**Expected behavior**
If possible, SemGrep should resolve full class name/import path, so rules that have full import path will work well. 

**What is the priority of the bug to you?**

- [ ] P1: important to fix or quite annoying

**Environment**
Latest SemGrep.

**Comment by nbrahms** [comment]
Tracked in https://linear.app/r2c/issue/PA-325/semgrep-does-not-resolve-package-of-java-classbase-class-if-there-is

**Comment by aryx** [comment]
This might work better now thx to https://github.com/returntocorp/semgrep/pull/4057

**Comment by aryx** [comment]
A bit related to https://github.com/returntocorp/semgrep/issues/3825

**Comment by tilperion2** [comment]
Looks like still reproducible.

**Comment by aryx** [comment]
The ability to know that someBaseClass resolves to com.test.someBaseClass is outside the reach of semgrep. Semgrep analyzes just one file at a time and so can't know that someBaseClass is actually defined somewhere in the same package.

**Comment by tilperion2** [comment]
Generally it possible to determine that baseClass belongs to the same package, as it is not mentioned in the imports, so we may assume that it is from the same package as current file. I think it is just a basic Java convention. 
But I understand that it may be tricky and too complex to implement in semGrep parser/linter. There may be some other conflicts with other Java system/internal packages(java.lang, etc.)

**Comment by aryx** [comment]
Yes, especially if the file contains some import foo.bar.* in which case the use of unqualified identifier can not be resolved and we can't assume they are from the current package.
