### ISSUE TITLE
Semgrep-core does not report failing pattern during parse failures

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#3860]
After https://github.com/returntocorp/semgrep/pull/3847, semgrep-cli relies on semgrep-core errror message as the message to show users.

For now during a parse failure, an error message like `"Semgrep Core WARN - Pattern parse error: In rule eqeq-is-bad: Invalid pattern for Python` is shown. It does not include details of the pattern that is invalid.

Should modify the message in the error object returned by semgrep-core to include the offending pattern

**Comment by ben-elttam** [comment]
I get `Semgrep Core ERROR - Pattern parse error: In rule blah: Invalid pattern for Javascript`, with many lines in the source yaml, many patterns this doesn't help narrow down which line is causing the problem, or what the problem is exactly.
