### ISSUE TITLE
Test directory needs to be explicitly added to path inclusions

### ISSUE THREAD

**Issue by edamamez** [semgrep/semgrep#3873]
**Describe the bug**
Hello!
If you use path inclusions (https://semgrep.dev/docs/writing-rules/rule-syntax/#limiting-a-rule-to-paths), you need to explicitly add the path to your test directory to the filter or else running them will result in a `failing due to rule id mismatch` error.

PR to update the docs here: https://github.com/returntocorp/semgrep-docs/pull/280

**To Reproduce**

1. Create a rule with a path inclusion (such as https://semgrep.dev/s/w3K0) in `semgrep/rules`
2. Create a test file in `semgrep/tests/rules` and run `semgrep --config semgrep/rules --test semgrep/tests/rules`
3. Observe the error
4. Add `semgrep/tests/rules` to the path inclusion filter and re-run
5. Observe that the test file runs as intended

**Expected behavior**
The test path shouldn't need to be explicitly added to the path inclusions. 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by mschwager** [comment]
> Create a test file in `semgrep/tests/rules` and run `semgrep --config semgrep/rules --test semgrep/tests/rules`

Do `semgrep/rules` and `semgrep/tests/rules` have the same sub-directory structure? If they don't, this can cause the rule IDs to not match up. This is laid out in more detail at the bottom of the [testing rules docs](https://semgrep.dev/docs/writing-rules/testing-rules/).

**Comment by edamamez** [comment]
Hi!
Yes, they do. It gives an error unless I add the path to the tests (`semgrep/tests/rules`, the same as the one passed to `--test`) to the path inclusion list for the rule. I can try to provide more detailed steps to reproduce if that would help 👍 !
