### ISSUE TITLE
python.lang.maintainability.useless-innerfunction.useless-inner-function

### ISSUE THREAD

**Issue by sfc-gh-sdeng** [semgrep/semgrep#3879]
**Describe the bug**
It says my inner function (`round_down_min`) is useless, but it is not.

**To Reproduce**
See https://github.com/snowflakedb/account_usage_share/pull/301/files/0764e41b42af2fb8fc8269becd13d993ff9f3159#r647779518. Give it several seconds to load. On line 366, inner function `round_down_min` is used.

**Expected behavior**
The inner function is used, so it should not make this comment.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [X] P2: annoying but not blocking me

**Comment by emjin** [comment]
I think this works now! @sfc-gh-sdeng can you check https://semgrep.dev/s/vqx4 to confirm?

**Comment by ievans** [comment]
@sfc-gh-sdeng issue looks fixed on the test case, feel free to re-open if you find any other regressions!
