### ISSUE TITLE
Python constant propagation does not resolve "raw" strings

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#3881]
**Describe the bug**
Python has this concept of "raw" strings, which are prefixed with the character `r`. See [this link](https://docs.python.org/3/reference/lexical_analysis.html#index-19) for more information.

In Python, raw strings look like this:

```python
message = r"this is a message"
```

[This issue](https://github.com/returntocorp/semgrep-rules/issues/1034) on semgrep-rules reported a false positive with a rule that is supposed to filter out constant strings (with `pattern-not-inside: return "..."`). After testing, it appears that the false positive is actually due to the raw strings. See this example in the live editor: https://semgrep.dev/s/RXkK/.

**Expected behavior**
I think it makes sense to treat raw strings like constant strings, which would let constant propagation correctly filter out the false positive in the rule from the issue listed above.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by mschwager** [comment]
We may also consider byte strings and the old unicode strings (for backward compatibility) here:

```python
message = b"foo"
message = u"bar"
```

Although byte strings are a fundamentally different type in Python, so maybe it makes sense to keep those separate :thinking:

**Comment by IagoAbal** [comment]
Minimized example: https://semgrep.dev/s/Pb9p

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-361/python-constant-propagation-does-not-resolve-raw-strings.
