### ISSUE TITLE
support fetching org-wide registry rules

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#3889]
**Motivation:** A growing number of users are using Semgrep in new environments where it is difficult to provide an org-wide auth token (editor, pre-commit). We want to avoid extra configuration friction: running just semgrep should find publicly listed rules automatically if someone has already claimed the org/project on Semgrep.dev, or semgrep —org=name can be used to explicitly set the org name.
            
An additional motivation is that we plan to open-source and merge our (currently proprietary) Semgrep CI wrapper, [semgrep-action](https://github.com/returntocorp/semgrep-action), into the main Semgrep codebase. For current semgrep-action users, this proposal obviates the deployment ID and make use of private API tokens optional.

**Implementation:** When running with rules from the Registry, Semgrep will use the git origin URL to extract an organization name (e.g., github.com/returntocorp/semgrep (http://github.com/returntocorp/semgrep) will resolve to “returntocorp”) and a hash of the project name (“semgrep” will be hashed). Semgrep will ask the Registry whether “returntocorp” has rules that have been configured to run on all the organization’s projects or for that specific project.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-353/support-fetching-org-wide-registry-rules.
