### ISSUE TITLE
Ellipsis operator in JavaScript objects without commas (ambiguity)

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#3890]
**Describe the bug**
Including an `...` in a JavaScript object works if it's added the end, but not when followed by something else.

For example, the following works: https://semgrep.dev/s/clintgibler:js-object-ellipses

```javascript
$.ajax(
  {
    'type': 'POST',
    ...
  }
)
```

This next one gives you a JS parse error: https://semgrep.dev/s/clintgibler:js-object-middle-ellipses

```javascript
$.ajax(
  {
    'type': 'POST',
    ...
    'data': { 
        'data': {
            'number': $NUM
        }
    }
  }
)
```

But this works: https://semgrep.dev/s/clintgibler:js-object-no-ellipses
```javascript
$.ajax(
  {
    'type': 'POST',
    // Note lack of `...` here
    'data': { 
        'data': {
            'number': $NUM
        }
    }
  }
)
```

This is confusing behavior to the user, because in most contexts `...` can be used to ignore arguments, statements, etc., but here it causes a parse error (but only in some cases it seems).

Open question: how can we inform users that they actually don't even a `...` in this situation, and Semgrep will do the right thing, even if there are other attributes? 🤷 

**To Reproduce**
See above links.

**Expected behavior**
I'd expect the middle example to not throw a parse error.

**What is the priority of the bug to you?**

- [X] P1: important to fix or quite annoying

This came up in a customer demo and was confusing.

**Comment by mschwager** [comment]
> This next one gives you a JS parse error: https://semgrep.dev/s/clintgibler:js-object-middle-ellipses

I've been similarly bitten by this with JSON rules. If you include a comma after the `...` it should work: https://semgrep.dev/s/5DPD/

This is somewhat frustrating, but also reasonable if you consider that `obj.method(..., k=v)` works but `obj.method(... k=v)` doesn't :man_shrugging:

**Comment by emjin** [comment]
Should we change this to `error-reporting` instead of `bug`?

**Comment by clintgibler** [comment]
@mschwager Good point, yeah the `,` makes sense, but I think is non obvious to users (and me).

Agreed @emjin, I'll update the labels.

**Comment by aryx** [comment]
It is even more problematic in JS where '...' can be used as a spread operator, and single identifier can also be used as field shorthands so when you have { a ... b } it can actually mean { a:a ...b} or { a:a ... b:b }
so forcing the comma solve the ambiguity.

**Comment by clintgibler** [comment]
@aryx Ah good point. 

Can we change this issue to instead be: Semgrep should tell you to add a comma after your `...` instead of throwing an opaque error like:

```
{"code":2,"level":"error","message":"Semgrep Core ERROR - Pattern parse error: 
In rule js-no-csrf: Invalid pattern for Typescript","rule_id":"js-no-csrf",
"spans":[{"config_end":{"col":134,"line":3,"offset":157},"config_path":["rules","0","pattern"],
"config_start":{"col":12,"line":3,"offset":35}}],"type":"Pattern parse error"}
```

**Comment by aryx** [comment]
:wave:
