### ISSUE TITLE
Docs example for matching method calls in Python fails

### ISSUE THREAD

**Issue by robintw** [semgrep/semgrep#3901]
I am trying to match a series of Python method calls. I've read the docs [here](https://semgrep.dev/docs/writing-rules/pattern-syntax/#method-calls and it says that the following should work, and match the method call in the second line:

**Pattern:** `$O.foo(). ... .bar()`
**Code:**
```
obj = MakeObject()
obj.foo().other_method(1,2).again(3,4).bar()
```

However, when run it gives an error:
```Pattern `$O.foo(). ... .bar()` could not be parsed as a Python semgrep pattern```

See https://semgrep.dev/s/pYZ0 for an example of this in the playground.

**Comment by robintw** [comment]
This error in the docs still seems to be present

**Comment by ievans** [comment]
Looks like this was fixed!
