### ISSUE TITLE
[PHP] Semgrep cannot parse `Entity::FROM` or `Constants::DEFAULT`

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3907]
Semgrep cannot parse `Something::XYZ` where `XYZ` coincides with a keyword name.

https://semgrep.dev/s/Q9wk

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-362/[php]-semgrep-cannot-parse-entityfrom-or-constantsdefault.
