### ISSUE TITLE
Sgrep seems to be matching on any conditionals with strings

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#391]
https://sgrep.live/n9Z

**Comment by ievans** [comment]
Regression introduced by https://github.com/returntocorp/sgrep/issues/229

Line #21 in https://sgrep.live/n9Z should not be marked as todo

**Comment by dlukeomalley** [comment]
Is this related? I found the behavior confusing.

```py
foo(...)
...
bar(...)
```

Now matches:

```py
foo()
if random() > 0.5:
    for i in range(10):
        bar()
```

**Comment by ievans** [comment]
@dlukeomalley that's the intended behavior of the fix to https://github.com/returntocorp/sgrep/issues/229
