### ISSUE TITLE
pattern 'x ... x' not matching in terraform

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3911]
**Describe the bug**
A pattern similar to:
```
x
...
x
```
is not matching the corresponding lines of code in terraform.

**To Reproduce**
Terraform is not yet on the playground. I ran the command:
```
python -m semgrep -l tf -e 'Action = "*" ... Resource = "*"' semgrep_repos/semgrep-rules/terraform/lang/security/iam/no-iam-admin-privileges.tf
```

where the file ```semgrep_repos/semgrep-rules/terraform/lang/security/iam/no-iam-admin-privileges.tf` contains:

```
resource "aws_iam_policy" "policy" {
   name        = "test_policy"
   path        = "/"
   description = "My test policy"

   # Terraform's "jsonencode" function converts a
   # Terraform expression result to valid JSON syntax.
   policy = jsonencode({
     Version = "2012-10-17"
     Statement = [
       {
         #ruleid: no-iam-admin-privileges
         Action = "*"
         Effect = "Allow"
         Resource = "*"
       },
     ]
   })
 }
```

**Expected behavior**
I would expect the pattern to match on the three lines below the 'ruleid' line. 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-363/pattern-x-x-not-matching-in-terraform.

**Comment by IagoAbal** [comment]
cc @aryx
