### ISSUE TITLE
parsing error in terraform nested key value pairs

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3913]
**Describe the bug**
There is a semgrep core pattern parse error for nested key value pairs. 

**To Reproduce**
Here's an example that is typed out (as semgrep.dev doesn't have tf just yet):
My config file:
```
 rules:
 - id: no-iam-admin-privileges
   patterns:
     - pattern: |
         resource $TYPE "..." {
           ...
           policy = jsonencode({
             ...
           })
           ...
         }
```

Here's the test:
```
 resource "aws_iam_policy" "policy" {
   name        = "test_policy"
   path        = "/"
   description = "My test policy"

   # Terraform's "jsonencode" function converts a
   # Terraform expression result to valid JSON syntax.
   policy = jsonencode({
     Version = "2012-10-17"
     Statement = [
       {
         #ruleid: no-iam-admin-privileges
         Action = "*"
         Resource = "*"
       },
     ]
   })
 }
```

And the command used is:
```
python -m semgrep -f no-iam-admin-privileges-tf.yaml no-iam-admin-privileges.tf
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-364/parsing-error-in-terraform-nested-key-value-pairs.

**Comment by IagoAbal** [comment]
cc @aryx
