### ISSUE TITLE
PHP, not recognizing const variables as constant strings

### ISSUE THREAD

**Issue by ristomcgehee** [semgrep/semgrep#3921]
**Describe the bug**
Hi, again. We've encountered that in PHP, Semgrep is not recognizing `const` variables as constant strings.

**To Reproduce**
https://semgrep.dev/s/chrismcgehee:php-constant-const

**Expected behavior**
Variables declared as `const` are treated the same as string literals when using `"..."` in a pattern. In the above example, line 9 should not be flagged as a match.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-369/php-not-recognizing-const-variables-as-constant-strings.

**Comment by IagoAbal** [comment]
One issue here is that `self` is being represented in Generic as `__special__self`.

**Comment by wu-s-john** [comment]
Hey everyone.

I solved the issue with the following PRs:

https://github.com/returntocorp/semgrep/pull/5022
https://github.com/returntocorp/pfff/pull/516

Please review. Let me know if I need to make any changes to my PR.

**Comment by ievans** [comment]
@chrismcgehee closing this issue -- please let us know if this isn't fixed in 0.89 :)
