### ISSUE TITLE
internal: pick up the latest semgrep-core binary when running semgrep tests

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3922]
Currently a copy of the `semgrep-core` binary is made to some folder so that pytest can find it. This is because pytest clears the environment: `PATH` is undefined when running tests, so we need a reliable path to `semgrep-core`. If we run `make` from the project root, this will first build `semgrep-core` and then make a copy using python.

Problem: running `make` from the root is slow. We recompile `semgrep-core` often, which takes a bit of time. We don't want to spend an extra 10 seconds of running python code to just make a copy of `semgrep-core`.

Acceptance criteria:
1. Building the `semgrep-core` executable shouldn't take longer than currently when we run `make` from `semgrep-core/`.
2. The `semgrep` command should automatically and instantly pick up the latest `semgrep-core` binary.

Unknowns:
* why are we using a copy rather than a symlink?
  * won't work on Windows; is it bad?
  * we need to check that brew is happy with a symlink (that could be the issue, not sure)
* could the python wrapper just look for the semgrep-core and spacegrep binaries where dune puts them? (again, the issue may be that dune creates them only as symlinks e.g. semgrep-core -> ../some/path/Main.exe

Possible solution: if copying the binaries is required, we could have the build in `semgrep-core/` make the copy. e.g. just edit the makefile and add a couple `cp` commands without calling any python.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-370/internal-pick-up-the-latest-semgrep-core-binary-when-running-semgrep.
