### ISSUE TITLE
[Terraform] assignment in arrays forbidden

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#3928]
**Describe the bug**
semgrep-core pattern parse error occurs when there is four layers of nested terraform statements with ellipsis (previously it errored on layer three :D)

**To Reproduce**
https://semgrep.dev/s/AXlB

The test case is in the link above, but semgrep playground keeps removing the pattern for some reason. The pattern is:
```
   patterns:
   - pattern:
      resource $TYPE "..." {
        ...
        policy = jsonencode({
          ...
          Statement = [
            ...
            Effect = "Deny"
            ...
          ]
          ...
        })
        ...
      }
```

**Expected behavior**
Would expect a match on line 13 of the test code instead of a parse error.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-403/terraform-errors-out-on-more-nested-ellipsis.

**Comment by aryx** [comment]
it's because you can't have assignements inside arrays.
[... a = b ...] will not work.
You need [..., {... a = b ...}, ...]
to enclose it inside an object. That's the only place where it's valid.

**Comment by aryx** [comment]
See https://semgrep.dev/s/66r1/

**Comment by aryx** [comment]
If it's a common mistake we can revisit.

**Comment by colleend** [comment]
ah I see 👍
