### ISSUE TITLE
[php] Problems with constant propagation

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#3933]
Reporting on behalf of @erwanlr who provided us with this example: https://semgrep.dev/s/krrP

1. The use of `$var` in line 5 is not recognized as constant because `$var` is a global variable and it is assigned twice, but dataflow const-prop only works inside functions. This is a known limitation that we need to fix. P2
2. ~`$var2` is also not recognized as constant, it seems that we don't recognize `.` as string concatenation. P1.~

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-407/[php]-problems-with-constant-propagation.

**Comment by IagoAbal** [comment]
The issue with `.` seems to have been solved already, and the first issue is a duplicate of #3667.
