### ISSUE TITLE
Semgrep cannot parse Entity::for , Entity::GLOBAL, Entity:: AS

### ISSUE THREAD

**Issue by thotakartheek004** [semgrep/semgrep#3954]
https://semgrep.dev/s/thotakartheek004:tracejobdata

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-418/semgrep-cannot-parse-entityfor-entityglobal-entity-as.
