### ISSUE TITLE
[PHP] Report line number of syntax errors

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#3957]
(Reporting line numbers for syntax errors would be useful for every language, I'm just facing it with PHP right now)

**Is your feature request related to a problem? Please describe.**
When there's a syntax error in the code I'm trying to scan with Semgrep, it's difficult for me to troubleshoot exactly where the error is, as I get an error message like:

```
{"code":3,"level":"warn","message":"Semgrep Core WARN - Syntax error in file target.php\n\t
`->` was unexpected","path":"target.php","type":"Syntax error"}
```

For example:

```php
    $q = Doctrine_Query::create()
        ->select('a.id, a.guid, a_t.template_id as template_id')
        ...
        ->andWhereIn('a.guid', array_keys($permissions[self::ACCTS_PARAM])); // note semicolon
        ->andWhereIn('a.guid', $account_guids);  // tries to continue the query, but above stmt finished it already
```

https://semgrep.dev/s/clintgibler:php-error-reporting

**Describe the solution you'd like**
Ideally Semgrep points me to the specific line of code where the syntax error is.

Bonus: print some helpful error message about how to fix it, something like:

> It looks like you're trying to continue this chaining clause with `->`, but you ended it with a semicolon on line N, so I didn't expect to see another `->` on line N+1. Delete the `;` on line N or start a new statement on line N+1.

But really just pointing me to the LOC would be enough for now.

**Describe alternatives you've considered**
Iteratively deleting code until I get it to work, my keyboard glistening softly in the morning light from my tears.

**Additional context**
This is based on customer provided test case code.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-419/[php]-report-line-number-of-syntax-errors.

**Comment by emjin** [comment]
hm, not sure why we aren't highlighting the file. @brendongo Maybe our changes broke the flow?

```
➜  semgrep-core git:(nathan/metric-opt-in) ✗ sc -f clint_test.sgrep clint_test.php -lang php -json
{"matches":[],"errors":[{"error_type":"Syntax error","severity":"warning","location":{"path":"clint_test.php","start":{"line":11,"col":9,"offset":397},"end":{"line":11,"col":11,"offset":399},"lines":["        ->andWhereIn('a.guid', $account_guids);"]},"message":"`->` was unexpected"}],"skipped":[],"stats":{"okfiles":0,"errorfiles":1}}
➜  semgrep-core git:(nathan/metric-opt-in) ✗ cat clint_test.sgrep 
Doctrine_Query::create()
➜  semgrep-core git:(nathan/metric-opt-in) ✗ cat clint_test.php 
<?php

function foo(HFWebRequest $request): string
{

    $q = Doctrine_Query::create()
        ->select('a.id, a.guid, a_t.template_id as template_id')
        ->from('Account a')
        ->leftJoin('a.AccountTemplates a_t ON a_t.account_id = a.id AND a_t.is_owner=0 AND a_t.template_id=' . $template->getId())
        ->andWhereIn('a.guid', array_keys($permissions[self::ACCTS_PARAM]));
        ->andWhereIn('a.guid', $account_guids);
}

?>
```

**Comment by ievans** [comment]
<img width="863" alt="Screen Shot 2022-02-19 at 8 58 57 AM" src="https://user-images.githubusercontent.com/409041/154810733-3c58da0b-381c-4c7f-bea1-1bcd3eed9718.png">

This works with --verbose and has tests on 0.82 or earlier!
