### ISSUE TITLE
[PHP] Import aliasing for PHP

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#3964]
semgrep easily tackles import aliasing when import has a name:

```php
<?php
use My\Full\Classname as Another;

$obj = new Another();
```
pattern:
```
new My\Full\Classname()
```
https://semgrep.dev/s/GOpB

works perfectly, but in a situation with imports without a name it does not work:

```php
<?php
use My\Foo\Bar;

$obj2 = new Bar();
```

pattern:
```
new My\Foo\Bar()
```
https://semgrep.dev/s/5De6/

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-422/[php]-import-aliasing-for-php.
