### ISSUE TITLE
[js] Mismatch between ellipsis behavior in expression vs statement position

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#3969]
**Describe the bug**
Ellipses in statement position, with statement delimiters, should match 0 or more statements

**To Reproduce**

Ellipses on statements:
```
✗ semgrep -e 'a; b' -l js <(echo 'a; b') 2&>/dev/null
/var/folders/zl/6kw19vqs1k1brhhjz3p0_2c40000gn/T/tmpcngpcxja
1:a; b
--------------------------------------------------------------------------------
1:a; b

✗ semgrep -e 'a; ...; b' -l js <(echo 'a; b') 2&>/dev/null
(no results)

✗ semgrep -e 'a; ...; b' -l js <(echo 'a; c; b') 2&>/dev/null
(no results)

✗ semgrep -e 'a; ...; b' -l js <(echo 'a; ; b') 2&>/dev/null
/var/folders/zl/6kw19vqs1k1brhhjz3p0_2c40000gn/T/tmpe4myhxih
1:a; ; b
--------------------------------------------------------------------------------
1:a; ; b

✗ semgrep -e 'a; ... b' -l js <(echo 'a; b') 2&>/dev/null
/var/folders/zl/6kw19vqs1k1brhhjz3p0_2c40000gn/T/tmpekgql346
1:a; b
--------------------------------------------------------------------------------
1:a; b
```

Work very differently from ellipses on expressions:
```
✗ semgrep -e 'f(a, ..., b)' -l js <(echo 'f(a, b)') 2&>/dev/null
/var/folders/zl/6kw19vqs1k1brhhjz3p0_2c40000gn/T/tmpn553wv16
1:f(a, b)
--------------------------------------------------------------------------------
1:f(a, b)

✗ semgrep -e 'f(a, ... b)' -l js <(echo 'f(a, b)') 2&>/dev/null
(no results)

✗ semgrep -e 'f(a, ... b)' -l js <(echo 'f(a, c, b)') 2&>/dev/null
(no results)
```

**Expected behavior**
Behavior of ellipses in expression position (currently: matches 0 or more nodes, delimeter required) should
match behavior of ellipses in statement position (currently: matches 0 or more nodes when _no_ delimeter, matches an empty statement when semicolon-delimited)

IMO the expression behavior is more natural.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep 0.67

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-426/[js]-mismatch-between-ellipsis-behavior-in-expression-vs-statement.
