### ISSUE TITLE
Document pattern-regex syntax precisely

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3974]
https://semgrep.dev/docs/writing-rules/rule-syntax/#pattern-regex incorrectly states that the supported syntax is the python's re module, but we actually use the pcre library or pcre-compatible syntax offered by ocaml's re libary.

Task:
* find out exactly which syntax is being used
  * must explain why https://semgrep.dev/s/mjambon:pcre-bidi-control doesn't work (the unicode character property `Bidi_Control` seems to be supported by e.g. perl and go but not by pcre)
* update the documentation:
  * briefly mention similarities and differences with other popular regexp libraries
  * link to the exact spec e.g. https://www.pcre.org/original/doc/html/pcrepattern.html

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-429/document-pattern-regex-syntax-precisely.

**Comment by 4390c336** [comment]
trying to get around it by using `\x{CODE}` is also not working : 
```
invalid regex '\\x{200E}\n': character value in \\x{} or \\o{} is too large at position 7
```

**Comment by mjambon** [comment]
I asked the question of supporting more Unicode properties such as `Bidi_Control`: https://github.com/PhilipHazel/pcre2/issues/39

**Comment by mjambon** [comment]
@4390c336 thanks for the report. Our code is missing a flag for this to work. I'll fix it, hopefully in time for this week's release (semgrep 0.72).

```ocaml
utop # let re = Pcre.regexp ~flags:[] "\\x{200E}";;
Exception:
Pcre.Error
 (Pcre.BadPattern ("character value in \\x{} or \\o{} is too large", 7)).

utop # let re = Pcre.regexp ~flags:[`UTF8] "\\x{200E}";;
val re : Pcre.regexp = <abstr>
```

**Comment by mjambon** [comment]
Regarding the support of more Unicode character properties in PCRE, I [reported the issue and Philip Hazel himself said he might take a look](https://github.com/PhilipHazel/pcre2/issues/39#issuecomment-963935118). If this gets done, there would still be a significant amount of work to get this to work with OCaml, since [pcre-ocaml uses the old PCRE API, not PCRE2](https://github.com/mmottl/pcre-ocaml/issues/10).
