### ISSUE TITLE
Bad highlighting of pattern-regex matches and/or incorrect number of matches

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3975]
**Describe the bug**

In the following example:
* There should be 3 matches corresponding to the 3 lowercase words rather than 2.
* These 3 matches should be highlighted.
* The line containing the uppercase word should not be highlighted.

https://semgrep.dev/s/mjambon:regex-highlight shows this as of semgrep 0.67.0:

![image](https://user-images.githubusercontent.com/343265/135710499-53542683-a2f4-4d50-8eef-c26ffffe477f.png)
![image](https://user-images.githubusercontent.com/343265/135710647-2151dbd9-eda6-4b19-93d2-8c30827ce3ae.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-430/bad-highlighting-of-pattern-regex-matches-andor-incorrect-number-of.

**Comment by nbrahms** [comment]
Moved to semgrep-app
