### ISSUE TITLE
Enhance the Getting Started documentation to show how to run example projects using Docker CLI

### ISSUE THREAD

**Issue by DanKaplanSES** [semgrep/semgrep#3976]
**Is your feature request related to a problem? Please describe.**
I couldn't gather what I was looking for from the documentation alone, so I decided to try `semgrep` directly to see what its output would look like. 

I'm on Windows, so I ended up using the Docker container to do so. There is a section in the middle of [Getting Started](https://semgrep.dev/docs/getting-started/#run-semgrep-locally) called "Expand for sample projects! 🎉" When you expand that, it gives you a list of commands that assume you _aren't_ using the Docker container. I had to refresh my memory on the docker command line (specifically the `-v` option) to "get started." This only took 5-10 minutes of my time, but reducing it to seconds would increase adoption for people starting from the same context as me.

**Describe the solution you'd like**
Here's what I envision as a solution. That expandable selection has tabs, one called CLI, the other called Docker CLI. Depending on which one you are viewing, the command line examples change. e.g., in the CLI tab, it'll continue to say

```bash
# juice-shop, a vulnerable Node.js + Express app
$ git clone https://github.com/bkimminich/juice-shop
$ semgrep --config p/security-audit juice-shop
```

But in the Docker CLI tab, it'll say

```bash
# juice-shop, a vulnerable Node.js + Express app
$ git clone https://github.com/bkimminich/juice-shop
$ docker run --rm -v "${PWD}/juice-shop:/src" returntocorp/semgrep --config p/security-audit /src
```

**Describe alternatives you've considered**
A quicker fix would be to have no tabs and change the above example to look like this:

```bash
# juice-shop, a vulnerable Node.js + Express app
$ git clone https://github.com/bkimminich/juice-shop
$ semgrep --config p/security-audit juice-shop
# OR
# juice-shop, a vulnerable Node.js + Express app
$ git clone https://github.com/bkimminich/juice-shop
$ docker run --rm -v "${PWD}/juice-shop:/src" returntocorp/semgrep --config p/security-audit /src
```

Alternatively, perhaps a link to the [`-v` documentation](https://docs.docker.com/storage/bind-mounts/) would suffice.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-431/enhance-the-getting-started-documentation-to-show-how-to-run-example.

**Comment by underyx** [comment]
Hey @DanKaplanSES! I'm really sorry this flew under our radar until I stumbled upon this issue just now. Your points were great and I wanted to thank you for writing such a well-considered description! I've just opened a PR to apply your second suggestion (as implementing tabs in our markdown-rendered docs sounds like a lot of effort.) Sorry about taking half a year to do this 😥
