### ISSUE TITLE
[PHP] Support for new syntax from PHP 8

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#3978]
PHP 8 has some new syntax that is currently cannot be parsed by Semgrep:

Named arguments https://www.php.net/releases/8.0/en.php#named-arguments
https://semgrep.dev/s/9rWk

Union types https://www.php.net/releases/8.0/en.php#union-types
https://semgrep.dev/s/y1L8

Match expression https://www.php.net/releases/8.0/en.php#match-expression
https://semgrep.dev/s/rY86

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-432/[php]-support-for-new-syntax-from-php-8.

**Comment by inkz** [comment]
:wave:

**Comment by inkz** [comment]
:wave:

**Comment by inkz** [comment]
:wave:

**Comment by aryx** [comment]
named arguments now work in develop thx to @Sjord work on tree-sitter-php:
https://semgrep.dev/s/9rWk?develop=true

**Comment by aryx** [comment]
match now works: https://semgrep.dev/s/rY86?develop=true

**Comment by aryx** [comment]
and union types too: https://semgrep.dev/s/y1L8?develop=true
