### ISSUE TITLE
Print Pcre exceptions properly

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3987]
Right now, exceptions raised by `Pcre` are printed by `Printexc.to_string` as e.g. `Pcre.Error(5)` which is unhelpful. Instead, we want something like `Pcre.Error(RecursionLimit)` which will save some time when investigating problems.

This can be implemented easily with [`Printexc.register_printer`](https://ocaml.org/api/Printexc.html#VALregister_printer), directly in semgrep or better, in the ocaml-pcre library. See https://github.com/mmottl/pcre-ocaml/issues/24

Marked as "user:external" because a user was reporting an uncaught pcre exception in a semgrep run in CI.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-439/print-pcre-exceptions-properly.
