### ISSUE TITLE
Catch Pcre exception raised by Eval_generic

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#3988]
**Describe the bug**

A user is getting a fatal `Pcre.Error(5)` (RecursionLimit) raised by the `Eval_generic` module, which @aryx says is used by `metavariable-comparison:`.

See also https://github.com/mmottl/pcre-ocaml/issues/24 on the topic of Pcre.

**To Reproduce**

unclear. Error doesn't show locally for the user, possibly due to the pcre library being compiled with a different default for the PCRE_ERROR_MATCHLIMIT (see https://serverfault.com/questions/408265/what-are-pcre-limits for an explanation).

**Expected behavior**

* Such an exception should not be fatal.
* Not running into such exception would be great (depends on whether the pattern is found in the target or if it's hardcoded).
* Errors should happen consistently on different platforms. (fixed by #4000)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-440/catch-pcre-exception-raised-by-eval-generic.

**Comment by mjambon** [comment]
For consistency, I suggest setting the [`limit_recursion`](https://mmottl.github.io/pcre-ocaml/api/pcre/Pcre/index.html#val-regexp) flag to some value rather than relying on a platform-specific default.

Note that some limit is desirable to avoid wasting resources due to a bad regexp and/or input.

**Comment by aryx** [comment]
Is there anything we need to do @mjambon ? Your fix is enough?

**Comment by mjambon** [comment]
@aryx I don't understand the context in which this regexp matching occurs. I vaguely heard/remember that the user was complaining that this exception was killing the whole semgrep job. I haven't checked myself. It would be good to ensure that this error is limited to just the target being parsed or matched.

**Comment by nbrahms** [comment]
Closing in favor of the Linear issue
