### ISSUE TITLE
make in sgrep_lint/ crashes on Linux

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#400]
cd sgrep_lint
make
....

Nuitka:INFO:Embedded as frozen module 'io'.
make[1]: *** [/tmp/ccRCyG1f.ltrans6.ltrans.o] Terminated
make[1]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
scons: *** [/home/pad/github/sgrep/sgrep_lint/build/sgrep.dist/sgrep] Error 1
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by brendongo** [comment]
What version of linux are you running? What is the version of nuitka?

**Comment by ievans** [comment]
@aryx is this an OOM kill?

**Comment by aryx** [comment]
pad@yrax:/etc$ cat issue
Ubuntu 18.04.4 LTS \n \l

pad@yrax:/etc$ nuitka3 --version
0.6.7
Python: 3.7.5 (default, Nov  1 2019, 19:15:52) 
Executable: /home/linuxbrew/.linuxbrew/opt/python/bin/python3.7
OS: Linux
Arch: x86_64

Maybe an OOM kill. Looks like the linker had a hard time.

**Comment by aryx** [comment]
Nuitka:INFO:Embedded as frozen module 'io'.

and taking forever with 8 cores at 99% CPU.
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                  
 9959 pad       20   0  420920 384284  19340 R  95.7  2.4   1:03.23 lto1-ltrans      

%MEM seems ok

**Comment by aryx** [comment]
and then it stopped with:
Nuitka:INFO:Colliding DLL names for libcrypto.so.1.1, checking identity of '/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib/libcrypto.so.1.1' <-> '/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1d_1/lib/libcrypto.so.1.1'.
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/Cellar/python/3.7.5/lib/libpython3.7m.so.1.0' (used by build/sgrep.dist/sgrep, build/sgrep.dist/_bisect.so, build/sgrep.dist/_blake2.so, build/sgrep.dist/_bz2.so, build/sgrep.dist/_ctypes.so, build/sgrep.dist/_datetime.so, build/sgrep.dist/_hashlib.so, build/sgrep.dist/_heapq.so, build/sgrep.dist/_json.so, build/sgrep.dist/_lzma.so, build/sgrep.dist/_md5.so, build/sgrep.dist/_opcode.so, build/sgrep.dist/_pickle.so, build/sgrep.dist/_posixsubprocess.so, build/sgrep.dist/_random.so, build/sgrep.dist/_sha1.so, build/sgrep.dist/_sha256.so, build/sgrep.dist/_sha3.so, build/sgrep.dist/_sha512.so, build/sgrep.dist/_socket.so, build/sgrep.dist/_ssl.so, build/sgrep.dist/_struct.so, build/sgrep.dist/binascii.so, build/sgrep.dist/grp.so, build/sgrep.dist/math.so, build/sgrep.dist/pyexpat.so, build/sgrep.dist/readline.so, build/sgrep.dist/select.so, build/sgrep.dist/termios.so, build/sgrep.dist/unicodedata.so, build/sgrep.dist/zlib.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/lib/libbz2.so.1.0' (used by build/sgrep.dist/_bz2.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/lib/libffi.so.6' (used by build/sgrep.dist/_ctypes.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib/libcrypto.so.1.1' (used by build/sgrep.dist/_hashlib.so, build/sgrep.dist/_ssl.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/lib/liblzma.so.5' (used by build/sgrep.dist/_lzma.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib/libssl.so.1.1' (used by build/sgrep.dist/_ssl.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/lib/libz.so.1' (used by build/sgrep.dist/binascii.so, build/sgrep.dist/zlib.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/lib/libreadline.so.8' (used by build/sgrep.dist/readline.so).
Nuitka:INFO:Included used shared library '/home/linuxbrew/.linuxbrew/lib/libncursesw.so.6' (used by build/sgrep.dist/readline.so).
Nuitka:INFO:Removing 'RPATH' setting from 'build/sgrep.dist/_bisect.so'.
Error, needs 'chrpath' on your system, due to 'RPATH' settings in used shared
libraries that need to be removed.
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by aryx** [comment]
ok, sudo apt-get install chrpath
(the error seems different this time). No idea about this chrpath dependency though.

**Comment by aryx** [comment]
it works!
but make install does not work now ... well it does stuff but I can't exec sgrep-lint.
