### ISSUE TITLE
java catch statement with wildcard matching doesn't work

### ISSUE THREAD

**Issue by jozseftiborcz** [semgrep/semgrep#4002]
I tried to write a rule to find empty catch statements in java. 
Here is the code:  https://semgrep.dev/s/y1Gk
The rule again:
```
rules:
- id: empty-catch
  pattern: |
      try {
        ...
      }
      catch (...) {
      }
  message: Catch statement is empty
  languages: [java]
  severity: INFO
```

If I replace wildcard with exact exception type in catch statement it works.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-444/java-catch-statement-with-wildcard-matching-doesnt-work.
