### ISSUE TITLE
@interface in pattern matching doesn't work

### ISSUE THREAD

**Issue by jozseftiborcz** [semgrep/semgrep#4030]
https://semgrep.dev/s/Pbve

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-473/interface-in-pattern-matching-doesnt-work.

**Comment by ievans** [comment]
@jozseftiborcz thanks for reporting. What's the priority of this to you? Is it blocking using Semgrep further, something that should get fixed routines, or a minor annoyance?

**Comment by jozseftiborcz** [comment]
I have a workaround for this: searching for interface without @. So it is prio3.

**Comment by aryx** [comment]
works now: https://semgrep.dev/s/Pbve?version=0.69.0
