### ISSUE TITLE
Correctly Tag Pypi Releases for alpine

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#4036]
We currently tag our linux pypi release with `any` platform since we want the wheel to be downloaded with alpine and manylinux platforms and there was no way at the time to tag an alpine platform.

Since then there is now a musllinux tag https://www.python.org/dev/peps/pep-0656/

We can have the wheel be uploaded as both a manylinux and a musllinux wheel and we should have the following outcomes:
- manylinux (e.g. ubuntu ) will download the manylinux wheel
- alpine will download the musllinux wheel

This frees up the `any` wheel as well and we might want to look into not publishing one so platforms we don't support (e.g. windows) will not run into the current rough edge of semgrep-core binary just not working (with a cryptic invalid binary format error) after they install.

**Comment by brendongo** [comment]
If not too difficult should also look into publishing a macosx_11_0_arm64 wheel (and a macosx 11 intel wheel)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-474/correctly-tag-pypi-releases-for-alpine.

**Comment by chasemp** [comment]
Just reporting in on desire for this, currently on M1 (ARM) MacBook and pip comes with binaries for x86/AMD unfortunately.  I can use macports but the version there is quite stale.  Thanks for all you folks do.

**Comment by brendongo** [comment]
The macports version is not maintained by us. Would recommend the homebrew version for now til we make time for this
