### ISSUE TITLE
[C] sizeof(...) not supported

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#4037]
https://semgrep.dev/s/0yXW

Semgrep complains about the rule syntax not being valid C, when trying to match a function.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-475/semgrepdev-bug-report.

**Comment by ben-elttam** [comment]
Confirmed it works as expected in returntocorp/semgrep:develop (Digest: sha256:475d6ae1f068f88c3e2ef8d9ea54b9af01ad258c75d5df00c115be48c3744714)

**Comment by aryx** [comment]
works now: https://semgrep.dev/s/0yXW?version=0.69.0
