### ISSUE TITLE
[Python] Several parsing errors with Python 3.9

### ISSUE THREAD

**Issue by yawpitch** [semgrep/semgrep#4039]
The following minimal examples all fail to parse with Syntax Error, but are valid in Python 3.9.

1. package relative import

```python
from . import foo
```

2. f-strings with # alt modifier

```python
f'{1:#b}'
```

3. f-string with a nested bang cast

```python
f"{0:{1!r}}"
```

4. use of the in-place matmul operator

```python
a @= 1
```

5. lambda with keyword-only arguments

```python
lambda *, a=0: a
````

6. [PEP-614](https://www.python.org/dev/peps/pep-0614/) decorators

```python
@False or (lambda x: x)
def f(x): pass
```

7. Use of nonlocal above PEP-614 decorator errors at nonlocal usage

```python
def a():
    name = 2
    def b():
        nonlocal name # <- error message will reference this line

@False or (lambda x: x) # <- but only if this line is present
def f(x): pass
```

Additionally, though I'm unsure if Python 2 syntax is also being actively supported, but the following also fails with a SyntaxError, but is valid Python 2 code:

```python
def d32v((x,)): pass
```

I'll leave it to you if these should be broken out into individual issues.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-477/[python]-several-parsing-errors-with-python-39.
