### ISSUE TITLE
Hacktoberfest at semgrep-rules! 👻 

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4050]
Contribute security rules for everyone to use! Check out the Hacktoberfest project at https://github.com/returntocorp/semgrep-rules/blob/develop/HACKTOBERFEST2021.md.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-478/hacktoberfest-at-semgrep-rules-👻.
