### ISSUE TITLE
Vulnerability disabled in sast-rulest.toml is still scanned by semgrep-sast job

### ISSUE THREAD

**Issue by vr333dev** [semgrep/semgrep#4060]
Hello, please see description of the issue in this Gitlab ticket: https://gitlab.com/gitlab-org/gitlab/-/issues/332636
We are hoping there is a way to disable certain issues from being scanned, in Gitlab pipelines.

Thanks

Vlad

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-481/vulnerability-disabled-in-sast-rulesttoml-is-still-scanned-by-semgrep.

**Comment by brendongo** [comment]
Hi @vr333dev we don't have control over gitlab pipeline rules and gitlab finding silencing. You might be able to ignore that line by placing a nosem comment https://semgrep.dev/docs/ignoring-findings/ or switching over to using the semgrep-action https://semgrep.dev/docs/semgrep-ci/overview/ that has more rule customization options.
