### ISSUE TITLE
[Go] import (... "foo" ...) not supported

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#4067]
https://semgrep.dev/s/5DjK

Origin: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1634223904167800

We actually don't need the ellipsis, import ("foo") should work too,
but we should also allow the (redundant) ellipsis.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-494/[go]-import-foo-not-supported.
