### ISSUE TITLE
[JS] Template strings not considered as taint sink

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4070]
**Describe the bug**
It looks like JavaScript template strings, such as `<h1>${greeting}</h1>` are not considered as a sink in taint mode.

**To Reproduce**
See https://semgrep.dev/s/WpwZ. There is a pattern (listed below) that is not highlighted.
```
- pattern: |
    `...`
```

**Expected behavior**
The template string in this example to be highlighted with the above rule.

```
app.post('/test2', async (req, res) => {
    // ruleid: raw-html-format
    res.send(`<h1>message: ${req.query.message}</h1>`);
})
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-495/[js]-template-strings-not-considered-as-taint-sink.

**Comment by mmcqd** [comment]
Closing because template strings are in fact considered as taint sinks. The bug was in the rule, not in Semgrep. Fixed rule is here: https://semgrep.dev/s/DzEj
