### ISSUE TITLE
[JS] Ability to use metavariables in template strings

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4072]
**Is your feature request related to a problem? Please describe.**
I want to be able to use metavariables in JS template strings so that I can use a ` - metavariable-*` clause on them.

This works already with Python format strings: https://semgrep.dev/s/Y895
But does not work with JS template strings: https://semgrep.dev/s/N1JA

Priority: P1

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-497/[js]-ability-to-use-metavariables-in-template-strings.
