### ISSUE TITLE
-fast skips a target that it shouldn't (bash)

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#4080]
I'm not getting matches with `-fast` for bash:

```
$ cat hello.yaml 
rules:
- id: '-'
  pattern: echo ...
  message: echo ...
  languages:
  - bash
  severity: ERROR

$ cat hello.sh
echo hello

$ semgrep-core -lang bash -config hello.yaml hello.sh
hello.sh:1 with rule -
 echo hello

$ semgrep-core -lang bash -config hello.yaml hello.sh -fast
```
^ The last command should return a match.

Here's the pattern's AST:
```
$ semgrep-core -lang bash -dump_pattern <(echo 'echo ...')
E(
  Call(
    N(
      Id(("!sh_cmd!", ()),
        {id_resolved=Ref(None); id_type=Ref(None); id_constness=Ref(None); })),
    [Arg(L(String(("echo", ())))); Arg(Ellipsis(()))]))
```

I guess the problem is due to the artificial function call `!sh_cmd!` that was introduced, and since it's not found in the raw source code, `-fast` assumes that the pattern won't match anything. Of course, `!sh_cmd!` also exists in the target AST but not in the target source. Note that other shell constructs are translated like this, using other functions of the form `!sh_...!` wherever the generic AST doesn't provide the constructs.

If that's indeed the problem, I suggest that `-fast` should ignore identifiers like `!sh_cmd!`. We'd have to agree on a prefix or pattern for this purpose.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-503/-fast-skips-a-target-that-it-shouldnt-bash.

**Comment by mjambon** [comment]
Maybe we should introduce a new kind of `special` ID:
```
| Implicit of string  (* any name that doesn't occur in the source code *)
```
