### ISSUE TITLE
[Java] ... in method calls require at least one elt, but inconsistent with other ...

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#4082]
See https://semgrep.dev/s/nKYd/

origin: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1634326837179000

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-504/[java]-in-method-calls-require-at-least-one-elt-but-inconsistent-with.
