### ISSUE TITLE
--config=auto detects wrong project URL

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4103]
**Describe the bug**
The --config=auto mode detects the project of the current working directory, not the project in the target repository. 

**Expected behavior**
--config=auto should detect the project URL of the target specified, and possibly enforce that only a single  path target is supplied.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by brendongo** [comment]
closing as not relevant since we no longer detect project url for this
