### ISSUE TITLE
[GoLang] Support module path in import resolution matching 

### ISSUE THREAD

**Issue by ulziibay** [semgrep/semgrep#411]
**Is your feature request related to a problem? Please describe.**
When i have two package with the same name: e.g. `crypto/rand` vs `math/rand`, I would like to select for one or the other in Sgrep!

**Describe the solution you'd like**
`math.rand.Int()` should match only the "Int" function of math/random module. See https://sgrep.live/WLE

**Describe alternatives you've considered**
Just using `rand.Int()` matches regardless of package path

**Additional context**
https://sgrep.live/WLE

**Comment by minusworld** [comment]
Similar to https://github.com/returntocorp/sgrep/issues/327

**Comment by ulziibay** [comment]
Closing it as I wont action on it further!
