### ISSUE TITLE
ability to import python packages inside python-where clause 

### ISSUE THREAD

**Issue by ulziibay** [semgrep/semgrep#412]
**Is your feature request related to a problem? Please describe.**
Want to use package like `zxcvbn` as part of the filtering. Motivating Golang is [gosec hardcoded config check](https://github.com/securego/gosec/blob/master/rules/hardcoded_credentials.go)
 
**Describe the solution you'd like**
```
- pattern-where-python: |
   import zxcvbn
   zxcvbn.PasswordStrength(vars["$MYVAR"]) > 80.0
```

**Describe alternatives you've considered**
Can use some other python builtin, but would like to use the best python packages for this.
We can actually have a WHITELIST of python packages that could be used inside this clause documented. 

**Additional context**
Currently gets the following error for the aforementioned pattern
```
python where expression needs boolean output but got: None for import zxcvbn; zxcvbn.PasswordStrength(vars['$VALUE']) > 80.0
```

**Comment by DrewDennison** [comment]
@ulziibay this is a great FR. I ran into this a while ago. IIRC I hacked around this with `output; import import zxcvbn; output = zxcvbn.PasswordStrength(vars["$MYVAR"]) > 80.0;` which doesn't quite work because the whole python expression is passed to `filtered = eval(python string)` and there is type checking for `filtered` has to be a boolean.  Would be nice if it supported a return in the expression to return a later variable after imports etc. cc @brendongo

**Comment by DrewDennison** [comment]
https://github.com/returntocorp/sgrep/blob/375b1478dccf57a3f4e12c0de7e6d4919c2cb86b/sgrep_lint/evaluation.py#L163 is code

**Comment by ulziibay** [comment]
good to know @DrewDennison. Designing a generic enough API for "python-where" is hard. You cannot anticipate what modules users would be trying to bring in and even if you do, you will have to pre-install those libraries in all the environments sgrep-lint is distributed to!

**Comment by ievans** [comment]
The biggest problem I see with this is that the combination of semgrep install + config files is no longer hermetically sealed: you now need a way to track dependencies outside of the config file, which is kind of a pain. Until we see more users asking for this, I would vote to close cc @DrewDennison

**Comment by ievans** [comment]
Per discussion with @DrewDennison, this can be supported already to the degree we'd like with whitelisted python

**Comment by DrewDennison** [comment]
yes we also support multi-line python with the last line needing to return a boolean so the code above in the issue body will work now as long as `zxcvbn` is in the user's python libraries
