### ISSUE TITLE
Really really deep statement matching

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#413]
**Describe the bug**
Certain deep-statement matches are broken in the latest version of sgrep.

**To Reproduce**
See https://sgrep.live/5R0. Without the wrapping function around `jwt.verify(...)` the match is as expected.

**Expected behavior**
The pattern should match.

**Comment by aryx** [comment]
This has never worked before. The flattening of stmt (emulating a deep stmt matching) stops
at function boundaries. What you want, and vassili, is really really deep statement matching.
I didn't do it origianlly because I thought it could be really slow. We can try and see.

**Comment by aryx** [comment]
Also I didn't do it because we were not tagging variables and resolving names, so flattening
function bodies would introduce vars in current scope that could be matched that we don't want.
With the new generic name resolution, maybe this is more doable.

**Comment by aryx** [comment]
Another issue is that the match range will be huge ... it will not point you out the 3 differents
patterns between the '...' but mostly the whole file.
