### ISSUE TITLE
Kotlin pattern-parsing errors when using ellipsis and metavariables in parentheses

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4140]
**Describe the bug**
Kotlin patterns with `(..., $VAR, ...)` do not parse.

**To Reproduce**
https://semgrep.dev/s/lZ6j

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by colleend** [comment]
Another example of this is: https://semgrep.dev/s/krYK

**Comment by aryx** [comment]
Same than the other issue; we just supported ellipsis inside expressions.
We need to allow it also inside arguments, class body, etc.

**Comment by aryx** [comment]
But your first example is weird, there are now 'new' in Kotlin.

**Comment by colleend** [comment]
good point, only the second example is valid Kotlin 👍
