### ISSUE TITLE
[Kotlin] support ellipsis in class body

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4141]
**Describe the bug**
The Kotlin interface syntax (`class x: y {...}`) does not parse as a valid pattern. 

**To Reproduce**
https://semgrep.dev/s/oYpN

**Expected behavior**
Would expect this pattern to parse.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by colleend** [comment]
I can also take a look into these if you're focusing on the newline bug!

**Comment by aryx** [comment]
I think it's because "..." is not allowed yet inside a class body.
I'll fix it. I also need to update to the latest fwcd with your latest improvoements (yeah, 90 -> 93%!)

**Comment by colleend** [comment]
awesome, thanks for doing this!
