### ISSUE TITLE
Ability to specify simple rules via the CLI options

### ISSUE THREAD

**Issue by robbles** [semgrep/semgrep#4167]
**Is your feature request related to a problem? Please describe.**
I've found semgrep's autofix feature to be pretty useful for on the fly refactoring. The one main drag is having to make a YAML file with a bunch of required fields for an ad-hoc rule.

**Describe the solution you'd like**
 It would be pretty useful if semgrep allowed something similar to the `-e` / `--pattern` option, but for a whole rule, allowing you to make and run a ad-hoc rule with a pattern and autofix.
For example, adding an initial argument to all calls to a particular function:
```
semgrep --lang=go --pattern 'myfunction($1, $2)' --fix 'myfunction(ctx, $1, $2)' --autofix ./src
```

**Describe alternatives you've considered**
The YAML file works fine for this - it's just more work. The idea here is to make semgrep more viable as a "inline sed" replacement in addition to the other things it's good for.

**Additional context**
If this feature seems viable, I'm interested in working on a PR in the near future.

**Comment by emjin** [comment]
Does this PR solve your use case? (`--replacement`) https://github.com/returntocorp/semgrep/pull/3734

**Comment by robbles** [comment]
Looks like it! Thank you!
