### ISSUE TITLE
Interpret ~ in CLI arguments

### ISSUE THREAD

**Issue by nedbat** [semgrep/semgrep#4186]
**Is your feature request related to a problem? Please describe.**
I used ~ in a file path on the command line, and semgrep couldn't find the file:
```
$ semgrep --config=~/coverage/lab/string-cat.yml .
WARNING: unable to find a config; path `~/coverage/lab/string-cat.yml` does not exist
no valid configuration file found (1 configs were invalid)

$ ls -l ~/coverage/lab/string-cat.yml
-rw-r--r--  1 nedbatchelder  staff  154 Oct 30 09:04 /Users/nedbatchelder/coverage/lab/string-cat.yml

$ semgrep --config=/Users/nedbatchelder/coverage/lab/string-cat.yml .
Running 1 rules...
(etc...)
```

**Describe the solution you'd like**
Usual shell conventions should be followed.

**Describe alternatives you've considered**
none

**Additional context**
BTW, this is on Mac, using zsh

**Comment by brendongo** [comment]
This is weird. I am also on Mac using zsh and this works fine for me.

```
semgrep --config ~/ret2co/sgrep/semgrep/tests/e2e/rules/paths.yaml .
Running 8 rules...
etc.
```

**Comment by brendongo** [comment]
What version of semgrep is this and what was it installed with (brew/pypi?)

**Comment by nedbat** [comment]
I had installed it with pip.  There's a difference in how you and I invoked it.  You used `--config ~/blah/blah` (with a space).  I used `--config=~/blah/blah` (with an equals sign).  Trying it again, the space works, the equals sign does not.

**Comment by nbrahms** [comment]
@brendongo with the space, perhaps the `~` is being expanded by zsh (rather than Semgrep)?

**Comment by nbrahms** [comment]
Repro on zsh:
```
➜ semgrep --config ~/dev/semgrep/semgrep.yml .
Running 1 rules...
^C
Aborted!
➜  semgrep --config=~/dev/semgrep/semgrep.yml .
WARNING: unable to find a config; path `~/dev/semgrep/semgrep.yml` does not exist
no valid configuration file found (1 configs were invalid)
```

**Comment by brendongo** [comment]
Oh wow would not have thought that would make a difference. Thanks for the bug report @nedbat!
