### ISSUE TITLE
Matching JavaScript arrow functions defined on class

### ISSUE THREAD

**Issue by Piccirello** [semgrep/semgrep#4187]
**Describe the bug**
There doesn't appear to be a way to match exclusively against arrow functions defined on a class. It's only possible to match against all function definitions, and to match against local arrow functions.

**To Reproduce**
It's possible to detect all function definitions: https://semgrep.dev/s/Jxrj
It's also possible to detect local arrow functions: https://semgrep.dev/s/Pb5p

**Expected behavior**
I'd like to be able to match against arrow functions that are defined on a class, without including standard functions.

**What is the priority of the bug to you?**
This is a P1 for us. We walk the prototype of several classes and wrap all functions in a permission check. We recently discovered that arrow functions do not exist on the prototype and thus aren't subject to this permission check. We now want to prevent arrow functions from being defined on the class.

**Comment by aryx** [comment]
Should work now, as long as you set the 'arrow_is_function' and 'flddef_assign' config in your yaml file, as shown in one of the example in the associated PR #4242

**Comment by Piccirello** [comment]
@aryx Thank you for the quick fix!
