### ISSUE TITLE
cannot use semgrepignore

### ISSUE THREAD

**Issue by so87** [semgrep/semgrep#4190]
What I tried:
* using gitignore syntax
* running semgrep from commandline
* scanned a repository with p/owasp-top-ten
* tried in same directory as repo base
* tried in sub directory of repo

Are there any examples of using semgrep ignore file in the docs?

**Comment by ievans** [comment]
Sadly semgrepignore is a semgrep CI feature, not a semgrep feature: 

See the warning at https://semgrep.dev/docs/semgrep-ci/overview/#ignoring-files

**Comment by ievans** [comment]
We can keep this issue open as a feature request though

**Comment by brendongo** [comment]
We do plan on porting this functionality over in ~3 months

**Comment by nbrahms** [comment]
On this quarter's roadmap :D

**Comment by aryx** [comment]
Hopefully this will make the next release

**Comment by brendongo** [comment]
This made the release in 0.76.2 so closing this
