### ISSUE TITLE
brew auto-pr is removing ruamel.yaml.clib dependency

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#4213]
**Describe the bug**
When creating an auto homebrew PR, it removes the ruamle.yaml.clib resource

Looks like this is because ruamel only lists clib as a dependency when running python < 3.10
https://sourceforge.net/p/ruamel-yaml/code/ci/default/tree/__init__.py#l16

And in our release script https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml#L303 we install pipgrip with brew which installs with a 3.10 runtime which means when pipgrip is used to find dependencies of semgrep, it misses clib.

Fix will be to install pipgrip with pip instead so we can run on python < 3.10

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-659/brew-auto-pr-is-removing-ruamelyamlclib-dependency.

**Comment by brendongo** [comment]
Looks like homebrew core expects a brew installed pipgrip to exist and calls that specifically. But brew only installs pipgrip with python 3.10
