### ISSUE TITLE
sgrep-lint should optionally trim config path from rule ids

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#422]
**Is your feature request related to a problem? Please describe.**
When using sgrep within Bento, sgrep reports rule IDs like so:
`https:.sgrep.live.c.r.r2c.python.flask.deprecated-apis.flask-deprecated-apis`. Instead, we'd like to display only `deprecated-apis.flask-deprecated-apis`. (The fact that this rule name is redundant  is a separate issue).

Unfortunately it's not obvious where in the above the config path ends and the rule ID begins, so there's not a good way within Bento to strip off the config path.

**Describe the solution you'd like**
A flag passed to sgrep-lint to cause it not to display the config path.

**Describe alternatives you've considered**
sgrep-lint could not display the config path as a matter of course, but this could break other consumers of the sgrep-lint api.

**Comment by DrewDennison** [comment]
I believe this is fixed

```
python3 -m semgrep --config https://semgrep.live/r/r2c.python
./tests/lint/stupid.py
rule:r2c.python.deadcode.useless-eqeq.eqeq-is-bad: useless comparison operation `a+b == a+b` or `a+b != a+b`; if testing for floating point NaN, use `math.isnan(a+b)`, or `cmath.isnan(a+b)` if the number is complex.
3:    return a + b == a + b
```
