### ISSUE TITLE
Parse failure when using 'override' keyword in TypeScript

### ISSUE THREAD

**Issue by hudsonma** [semgrep/semgrep#4220]
**Describe the bug**
When using the 'override' keyword, several rules result in warnings that cause the GitLab CI analyzer to fail with status code 3.  The 'override' keyword was added in TS 4.3: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag

```json
{
"invocations": [
        {
          "executionSuccessful": true,
          "toolExecutionNotifications": [
            {
              "descriptor": {
                "id": "Syntax error"
              },
              "level": "warning",
              "message": {
                "text": "Semgrep Core WARN - Syntax error: When running eslint.detect-non-literal-require on file.ts: `override` was unexpected"
              }
            },
            {
              "descriptor": {
                "id": "Syntax error"
              },
              "level": "warning",
              "message": {
                "text": "Semgrep Core WARN - Syntax error: When running eslint.detect-non-literal-fs-filename on file.ts: `override` was unexpected"
              }
            },
            {
              "descriptor": {
                "id": "Syntax error"
              },
              "level": "warning",
              "message": {
                "text": "Semgrep Core WARN - Syntax error: When running eslint.detect-object-injection on file.ts: `override` was unexpected"
              }
            }
          ]
        }
      ]
}
```

**To Reproduce**
https://semgrep.dev/s/WpdE

**Expected behavior**
Parsing completes successfully and analysis is performed

**What is the priority of the bug to you?**
P1.  File can be excluded from analysis, but a parse failure seems like a slightly bigger deal

**Environment**
Gitlab CI analyzer v2.3.15, which uses semgrep 0.69.1

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-662/parse-failure-when-using-override-keyword-in-typescript.
