### ISSUE TITLE
Missing detection for try method value

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#4228]
**Describe the bug**
Semgrep currently fails to detect values within a try statement https://semgrep.dev/s/0ykj
```
try ($VALUE) { body }
```
In java semgrep translates it to try { body } in the generic AST and completely forgets about $VALUE.

Semgrep should detect the $VALUE of the try not just the body. There are a lot of cases where code examples in Java show this, and it would be important to detect the use.

**To Reproduce**
https://semgrep.dev/s/0ykj line 51

**Expected behavior**
It should detect the value within line 51.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P1: important to fix or quite annoying

**Environment**
https://semgrep.dev/s/0ykj

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-668/missing-detection-for-try-method-value.

**Comment by IagoAbal** [comment]
We could perhaps encode this combining `WithUsingResource` and `Try`?

**Comment by LewisArdern** [comment]
I'm seeing this hasn't been fixed, we're running into missing catches on production code we're trying to scan 

Here's another example: 
* https://semgrep.dev/s/6gjB

See: https://github.com/returntocorp/semgrep/issues/717 which said it was fixed, and well i think it hasnt been

**Comment by emjin** [comment]
Should match now! https://semgrep.dev/s/0ykj?version=develop. Fix will go out with the release tomorrow
