### ISSUE TITLE
Kotlin metavariable equality statements

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4234]
**Describe the bug**
Kotlin metavariable equality statements (in if-else statements) do not match on expected code snippets.

**To Reproduce**
semgrep.dev currently isn't working for Kotlin (keeps giving wrong matches). What I'm running is: 

_sgrep file:_
```
if ($E) {
  $S
} else {
  $S
}
```

_kotlin file:_
```
class Foo {
    fun foo() {
        // ERROR:
        if (x > 2) {
            foo()
            bar()
        } else {
            foo()
            bar()
        }

        if (x > 2) {
            foo()
            bar()
        } else {
            foo()
        }
    }
}
```

**Expected behavior**
I would expect there to be a match on the first if-else statement, but there are currently no matches for this.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by aryx** [comment]
I think it's because $S matches a single statement. You put those $S inside { } so it will only match blocks with one statement.
But you can get $S to match a whole block (which is a single statemnet) with
```
if ($E)
  $S
else
 $S
```

To double check.

**Comment by colleend** [comment]
I see, that makes sense. hmm, changed it to that and still getting no matches 🤔 ,  but 
```
if ($E)
  $S
else $S
```
works. This might be because of the newline parsing issue with a newline after the `else` in `if_expressions` 🤔  (so might be fixed after your PRs to tree-sitter!)

**Comment by aryx** [comment]
Maybe. I'll check!

**Comment by colleend** [comment]
I'm going to close this issue then because it works (and newline is separate issue :D)
