### ISSUE TITLE
Python 2 fallback parsing not working

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#425]
ParseError on valid Python code. This is a regression: this code parses in 0.4.8 but not in 0.4.9. According to @aryx this ought to fallback to py2 parsing mode, but it does not.

https://sgrep.live/xLL

Code snippet is from psycopg2/tests/test_async_keyword.py:45 https://github.com/psycopg/psycopg2/blob/6cff5a3e089f155519765f9cdd49ef78b23ab740/tests/test_async_keyword.py#L45

EDIT: Since sgrep now defaults to a strict python3 parser, some python2 files in a codebase may report as parseerrors or lexicalerrors. In 0.4.9 sgrep-lint started displaying these errors to stderr, so many more users will see them now. 

This seems like a poor experience. We should either (a) fallback to the py2 parser if the py3 parser fails (a bit wonky) or (b) provide a py2or3 parser that we use as the default for .py files or (c) surpress .py parse failures by default? Looking for more ideas.

**Comment by brendongo** [comment]
https://sgrep.live/nlY

Reproduced minimal example. looks like when the kwarg is async bad things happen

**Comment by brendongo** [comment]
Also with await: https://sgrep.live/E4N
Also yield: https://sgrep.live/7v2

I suspect something from reserved words in python

**Comment by DrewDennison** [comment]
I don't know if it's valid code anymore 😂 

```Python 3.7.0 (default, Feb 14 2019, 13:22:02)
[Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> blah(async=True)
  File "<stdin>", line 1
    blah(async=True)
             ^
SyntaxError: invalid syntax

**Comment by brendongo** [comment]
Are these even allowed as keyword arguments

**Comment by DrewDennison** [comment]
nope 

```
>>> def blah(async):
  File "<stdin>", line 1
    def blah(async):
                 ^
SyntaxError: invalid syntax
>>>
```

**Comment by brendongo** [comment]
I think it is in python 2

**Comment by brendongo** [comment]
So the root cause of issue is kwargs that are reserved in 3 but not in 2 :|

**Comment by DrewDennison** [comment]
yeah not it https://docs.python.org/2.5/ref/keywords.html for py2 and it's in https://docs.python.org/3.7/reference/lexical_analysis.html#keywords

**Comment by DrewDennison** [comment]
@aryx should we make a `python2` lang and leave `python` as 3?

**Comment by aryx** [comment]
thx @brendongo for the minimal example

**Comment by aryx** [comment]
yield kwd argument is also invalid in python2.
