### ISSUE TITLE
C parser failure

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4252]
I *think* this is valid C, but it fails to parse: https://semgrep.dev/s/DzrP

**Comment by aryx** [comment]
What is this syntax?
```
{"secret"} * (rax_19 + 0x10) = calloc(1, 8);
```
I never saw those {"secret"} thing.

**Comment by aryx** [comment]
Can we close then? if it's actually not valid syntax ...

**Comment by ievans** [comment]
Yes, will re-open when I have a proper snippet.
