### ISSUE TITLE
Semgrep 0.72.0 tries to analyze .png files and crashes

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#4258]
**Describe the bug**
Semgrep 0.72.0 tries to analyze .png and other binary files and then crashes with `Pcre.Error(BadUTF8)`:
https://r2c-community.slack.com/archives/C0242656NQ2/p1636567860034600. Affects paying customers.

**To Reproduce**
This can be reproduced on this public repo https://github.com/RecordReplay/devtools/, see https://github.com/RecordReplay/devtools/runs/4169052484?check_suite_focus=true#step:4:19

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by IagoAbal** [comment]
cc @mjambon

**Comment by IagoAbal** [comment]
cc @brendongo @mmcqd

**Comment by jayvdb** [comment]
I encountered this on 0.72 with zips, tar.gz, .eot, .ttf, .woff(2).   I was able to workaround it with both `.semgrepignore` and the semgrep app ignore overrides.

**Comment by IagoAbal** [comment]
This happens using the `regex` language.
