### ISSUE TITLE
[Python] Cannot write a pattern to find useless list comprehensions

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#4260]
Reporting on behalf of @mhoffm-aiven.

**Describe the bug**
Pattern `[$X for $X in $ITERATOR]` does not match `[v for v in iterator]`. The cause seems to be that in Generic, the first `v` is an expression id, whereas the second `v` is a pattern id. We should probably consider both equal when they bind to the same metavariable.

**To Reproduce**
https://semgrep.dev/s/Q91Z

**Expected behavior**
Pattern works, or we provide some workaround.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by aryx** [comment]
I had some refactoring I wanted to do to remove Metavariable.Id and just keep Metavariable.Name. This might solve this issue.

**Comment by aryx** [comment]
Hmm it's also because Naming_AST does not handle correctly those variables. The PatId has a resolved of Global 1
while the Id is unresolved.

**Comment by aryx** [comment]
(found via -dump_named_ast)
