### ISSUE TITLE
Autofix for Python exit -> sys.exit doesn't work in 0.72.0

### ISSUE THREAD

**Issue by SoftwareApe** [semgrep/semgrep#4261]
**Describe the bug**
When runnin autofix on a Python codebase I noticed exit is replaced with sys.exit, but semgrep fails to use the right return code.

e.g.
`exit(1)`

becomes `sys.exit($X)`

**To Reproduce**
autofix python with exits.

**Expected behavior**
should produce the same return code.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17566442/141333665-ac159c12-246b-429b-8a2b-a50aceeb524a.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
pip installed 0.72.0

**Comment by aryx** [comment]
Do you have a semgrep.dev playground link so we could try to reproduce?

**Comment by aryx** [comment]
@SoftwareApe could you link to a semgrep.dev/editor snippet, so we could try to reproduce easily?

**Comment by SoftwareApe** [comment]
I'm not sure what you want there, this is about the rules that are automatically selected by semgrep when applying autofix on the command line. All occurrences are the same for me.

**Comment by aryx** [comment]
What is the exact command you ran? (semgrep --config ???)  and could you copy-paste the python file that exhibits the error?

**Comment by ievans** [comment]
@SoftwareApe I'm unable to reproduce this on 0.77. Can you upgrade Semgrep and try again? Here's a snippet showing it working just fine: https://semgrep.dev/s/PgYp

**Comment by SoftwareApe** [comment]
I'm sorry I can't reproduce this right now,  I don't have my laptop with me.
