### ISSUE TITLE
PHP Alpha: public function causes invalid pattern

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#4262]
**Describe the bug**

Seems like having `public` in the pattern causes an error

**To Reproduce**

https://semgrep.dev/s/krg2

**Expected behavior**

It should work :)

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Comment by dee-see** [comment]
Modified the snippet to include the opening PHP tag (my bad) but it still doesn't work

https://semgrep.dev/s/krg2

**Comment by aryx** [comment]
Should work in the next release (or if you use develop).

**Comment by dee-see** [comment]
Awesome, thanks!
