### ISSUE TITLE
PHP Alpha: Unable to match on a function

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#4263]
**Describe the bug**

I've been playing with this pattern and I just can't figure out how to have a pattern that matches a function, any function really. Am I doing something wrong or it's really a bug?

**To Reproduce**

https://semgrep.dev/s/Pbjz

**Expected behavior**

Demo above should match

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

semgrep.dev

**Comment by dozernz** [comment]
Your test code needs a PHP opening tag. See: https://semgrep.dev/s/dozernz:pbjz for a working example

**Comment by dee-see** [comment]
Ugh, not proud of that one haha. Thanks!
