### ISSUE TITLE
Java control flow analysis false positive

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4265]
**Describe the bug**

**To Reproduce**
Running on [this java file](https://github.com/eclipse/jetty.project/blob/b06ccf286d8b72c745883a8218e065cba455dcf4/jetty-websocket/websocket-jetty-common/src/main/java/org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandler.java#L463)

there is a false positive on the $X == $X rule. See https://semgrep.dev/s/DzWP

**Expected behavior**
The rule should not fire on the file or https://semgrep.dev/s/DzWP

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep 0.72

**Comment by emjin** [comment]
![image](https://user-images.githubusercontent.com/5942585/141383512-d7fc9f9f-8feb-4829-a850-27c5bee17e57.png)

**Comment by IagoAbal** [comment]
Also, we get some of those `Could not resolve label: _label` warnings here... let's fix both.

**Comment by IagoAbal** [comment]
This was a corner case affecting switch statements, when the last statement of the default case is something that ends the execution like a `throw`.
