### ISSUE TITLE
Semgrep hidden files

### ISSUE THREAD

**Issue by roisec** [semgrep/semgrep#4274]
Hi,
I want to scan my repos by semgrep and scan secrets on hidden files.
When .env is in my repo the semgrep ignore him by default.
How can I disable it?

Thanks

**Comment by IagoAbal** [comment]
@RoiSec is `.env` in your `.gitignore`, is it listed in `git ls-files`?

You are welcome to ask questions here in GitHub but I recommend you joining http://r2c.dev/slack for that, you will probably get answers much quicker, and you can also get help from other Semgrep users.

**Comment by mjambon** [comment]
This issue was assigned to me but I'm on sick leave for about 2 more weeks.

**Comment by IagoAbal** [comment]
Closing this issue since the user is not responding. @RoiSec feel very welcome to reopen it or drop by our Community Slack!
