### ISSUE TITLE
patterns as anchors for inserting statements with autofix

### ISSUE THREAD

**Issue by gordonwoodhull** [semgrep/semgrep#4278]
### Problem

Sometimes when fixing vulns, it's sufficient to add some statements in the right place, using metavariables bound on patterns found in an "anchor statement", without modifying any existing statements.

For example, take:

```java
String path = read_user_input();
some_object.do_some(complicated(series_of_calls_with(new File(path))));
```

When we encounter a statement containing the dangerous expression `new File(path)`, we want to insert some statements validating the path and throwing if it's dangerous:

```diff
--- a/semgrep/exper/dangerous-path.java
+++ b/semgrep/exper/dangerous-path.java
@@ -1,2 +1,4 @@
 String path = read_user_input();
+if(Security.path_is_dangerous(path))
+  throw new PathError;
 some_object(do.some(complicated(series_of_calls_with(new File(path)))));
```

The conditional and throw need to be inserted in the right place, which we determine using pattern, pattern-inside, etc. The new statements use metavariables captured in the pattern(s).

### Workaround and its limitations

Currently it seems the best workaround is to write a pattern that matches the anchor statement *and which captures all of it in metavariables*, and duplicate the pattern in the fix with the inserted lines before or after it:

```yaml
rules:
- id: throw-on-dangerous-path
  message: throw on dangerous path
  severity: INFO
  languages:
    - java
  pattern: |
    $F($G($H($I(new File($PATH)))));
  fix: |
    if(Security.path_is_dangerous($PATH))
      throw new PathError;
    $F($G($H($I(new File($PATH)))));
```

Luckily, most of the statements we are trying to match are not that complicated, but in principle we would have to generate a number of rules which is exponential in the complexity of the expressions containing the dangerous code.

The deep expression operator looks promising to simplify this workaround, but unfortunately it doesn't capture, so you can't duplicate in the fix the range of the statement that it matched.

### Simultaneous fix and insertion at enclosing anchor

One more design consideration. Consider SQL injection:

```java
String SQL = "SELECT sensitive, stuff FROM important_table where user=" + login;
statement = connection.createStatement();
return statement.executeQuery;
```

We want to replace non-literal sub-expressions of the query like `login` with the neutralized placeholder `" ? "`, and we *also* want to capture those expressions and use them in inserted statements (e.g. calling `.setString(...)` on the SQL statement object).

I won't get into the details (and yes I am glossing over some other difficulties in this example) but the point is that there is *both* a replacement and the captured metavariables also need to be used in statements inserted nearby.
 
### Proposed solution

I'm open to any syntax or behavior. Given the above requirements, my thought is to implement `before-anchor` and `after-anchor`.

These would behave just like `fix` but
* The value is always a statement or multiple statements.
* The generated code is added before or after the nearest enclosing statement of the matched pattern.
* If there are multiple matches in the same statement, the `before-anchor` and `after-anchor` insertions each aggregate in the order of the matches.

### Alternative solution

As hinted above, another possible solution is a capturing deep expression operator. This could ease the pain of duplicating the pattern into the fix.

However, the disadvantages are:
* Some weird new syntax for specifying the metavariable name to capture to.
* Does not support simultaneous replacement and insertion at enclosing anchor (because there is only one fix).

### Unknowns / Impact on rest of Semgrep

I haven't fully investigated, but I think this means 
1. Pattern matches will have to include the range of the nearest enclosing statement, when `before-anchor` or `after-anchor` is present in the rule, or 
2. `autofix.py` will have to compute the AST/CST when these features are present, or
3. There are perhaps hacky but reliable ways in most languages to scan outwards from a range to the enclosing statement... not sure how these generalize in a multi-language system like Semgrep.

I also haven't looked at the other matchers to see if their patterns would make sense as anchors, or if this impacts the design. 

Thanks in advance for any feedback on the design. Hope we can get this functionality into Semgrep in some form.

**Comment by gordonwoodhull** [comment]
Forgot to mention prior art: this is equivalent to one use of context lines in SmPL, lines without `+` or `-` which need to be matched but are not deleted or added, preceded or followed by `+` lines.

**Comment by IagoAbal** [comment]
Not an expert on _autofix_, and I would have to read this more carefully to understand all the details (may need more examples too). Are you thinking to implement this yourself?

Capturing the AST matched by a deep-expr pattern into a metavariable should be easy. On the engine side, this probably just needs a change in  `Generic_vs_generic`. Don't know what would be the right syntax though, maybe something like `<...$VAR expr-pattern  ...>`?

**Comment by gordonwoodhull** [comment]
Thanks @IagoAbal!

Yes, I will implement some form of this for my demo, and it would make sense to contribute since it's one of the things I can't do with a wrapper script.

Here is a simpler, more relatable example.

It's a joke example but pretty close to what we do to remediate XXE vulnerabilities, where we need to disable dangerous factory and parser options which are enabled by default.

Say that we have a message reader which might blow up the computer if it reads the wrong message, and we are processing messages received from anyone on the internet.

To be safe, we need to set a couple options on the reader factory before instantiating the reader:

```diff
+ dangerousReaderFactory.allowExplosives(false);
+ dangerousReaderFactory.setOption('implosions', false);
  DangerousReader dangerousReader = dangerousReaderFactory.newInstance();
  dangerousReader.readMessage(message);
```

Our scanner Falsicode has informed us that the last line might explode or implode the computer, so we want to add the green-+ lines.

We use `pattern-inside-taint` to search upward in the control flow from the flagged `readMessage` line to the `newInstance` line, and currently we need to write at least two patterns for the `newInstance` line:

```yaml
pattern: DangerousReader $READER = $READERFACTORY.newInstance();
```

and

```yaml
pattern: $READER = $READERFACTORY.newInstance();
```

This is because the fix will contain the same line:

```yaml
fix: |
  dangerousReaderFactory.allowExplosives(false);
  dangerousReaderFactory.setOption('implosions', false);
  DangerousReader $READER = $READERFACTORY.newInstance();
```

So currently we generate two rules, one for the assignment and one for the declaration. It gets worse the deeper the expression might reside in the statement.

A capturing deep expression operator doesn't look so bad, syntactically, the way you have put it, and I am heartened to hear it might be easy.

I guess it wouldn't help directly with the above &mdash; we would still need redundant rules unless we had a "deep *statement* operator". 😉 

But it would reduce the number of redundant rules from exponential to constant.

**Comment by gordonwoodhull** [comment]
I updated my example up top with a more complicated expression-statement to illustrate the problem better.

For now I will try to implement capturing deep expression operator and then generate a rule wrapping the DEO for each relevant `stmt_kind`. 

Thanks again! I will let you know how it goes.

**Comment by gordonwoodhull** [comment]
Thanks @IagoAbal, it was indeed easy to add a capturing deep expression operator `<...$CDEO expr ...>`

I did it by adding it to the Java lexer: the variable is captured inside the left bracket`LDots` and then handled in `Generic_vs_generic.ml`, similar to how `$...ARGS` is a metavariable which is also `...`. I guess the downside is that every lexer would need to be modified, but it works perfectly.

With a little more tooling, this produced a good demo, but I think it is not the optimal solution for the original problem stated above. I will open another issue with a simpler proposal, now that I understand Semgrep better.

I have to work on some other stuff for a while, but it looks like the project is going ahead and I hope to rewrite and contribute some things to give autofix similar functionality to SmPL.

I am tempted to write up my experience report, but using capturing deep expression operator for the above purpose ended up in a lot of esoteric hacks and has fundamental limitations which would probably not be of interest to anyone else. :wink:

**Comment by IagoAbal** [comment]
Happy to hear that you got that implemented easily @gordonwoodhull. Looking forward to your next proposal and eventually some PRs 😄
