### ISSUE TITLE
Add a whole semgrep-rules check for rules with the same id but different fields

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#4283]
While we deduplicate rules by id and behavior, it's also not desired for two rules in our repo to have the same id but do different things. Maybe we can add a warning: "another rule already has this id"

**Comment by aryx** [comment]
In the same rule file? I thought we already had a check for duplicate ids.

**Comment by emjin** [comment]
You're right; updated the issue. I don't think this is as pressing now, though, since we only ignore the metadata field now when comparing rules. I'll close it for now.
