### ISSUE TITLE
Taint tracking across mulit golang src files

### ISSUE THREAD

**Issue by Sebastian1011** [semgrep/semgrep#4284]
I have successfully achived taint tracking in single golang file. 
But I need to do taint tracking across multi golang source files.
I'm curious how to write the rules. 
For example, Project structure like follows and I want to find out relation between variable a in File1 and fmt.Println(name) in File3 :

File1.go
```
type StructA struct {
   Name string
}
func Handler1(a StructA){
   // some code
   B := &StructB{}
  
   B.Handler2(a.Name)

   // some code
}
```
File2.go
```
type StructB struct{}

func (b *StructB) Handler2(name string) {

    C := &StructC{}
    C.Handler3(name)
}
```
File3.go
```
type StructC struct(}
func (c *StructC) Handler3(name string){
    fmt.Println(name)
}
```

**Comment by IagoAbal** [comment]
@Sebastian1011, the short answer is that Semgrep only does intra-file analysis, that is, it analyzes one file at a time and in isolation.

That said, we have an experimental feature https://semgrep.dev/docs/experiments/join-mode/ that may help here. It allows running multiple rules and then "joining" their results. You should be able to use it for taint tracking rules too.

**Comment by ievans** [comment]
Update: this is now a feature in the Pro version of the Semgrep engine: https://semgrep.dev/products/pro-engine/
