### ISSUE TITLE
semgrep does not work on windows 10

### ISSUE THREAD

**Issue by RunFox** [semgrep/semgrep#4295]
Hello. I use pip3 to install semgrep locally. Install succsesfull. But when i try ro run it - it gives error: 
"import resource
ModuleNotFounError: No module named 'resource'

Environment: Windows 10, pip3, python 3.7.3

**Comment by aryx** [comment]
Yes we support Semgrep on Windows only under WSL.

**Comment by RunFox** [comment]
Hello, @aryx . Thank you for reply
