### ISSUE TITLE
FP: string constant inference not correct for non-literal-require

### ISSUE THREAD

**Issue by devd** [semgrep/semgrep#4301]
**Describe the bug**
https://semgrep.dev/s/0y95 should not trigger for the third case. Full string inference is hard but this is pretty basic and common and one line. The ? is to decide whether you are in prod/dev mode, e.g..

**Comment by sabrinabrogren** [comment]
@devd Totally cool! I think this is actually a bug with semgrep and not the rule, so I'm transferring this issue to the relevant repo. Thanks for the bug report!

**Comment by aryx** [comment]
Note that a workaround is to also explicitely whitelist with an additional pattern-not: require($X? "..." : "...")

**Comment by aryx** [comment]
@IagoAbal I guess this would require an e_constness field in expr, just like we have currently for identifier.
