### ISSUE TITLE
Return partial match information when nothing match

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#431]
Sometimes a little something will stop a complex pattern to match some test code in sgrep.live.
See https://github.com/returntocorp/sgrep/issues/429 where the addition/removal of a ';'
change the match result.

It would be nice when nothing match to help the user refine his pattern so that it matches the test code, or at least tell the user about partial match so that he can learn what is the problematic part in a complex pattern.

**Comment by aryx** [comment]
cc @DrewDennison @ievans @nbrahms

**Comment by nbrahms** [comment]
Completed by showing steps.
