### ISSUE TITLE
Installing semgrep via pypi or GitHub on M1 Pro, Max, etc. (arm64) Mac installs semgrep-core compiled for x86_64

### ISSUE THREAD

**Issue by j-martin** [semgrep/semgrep#4311]
**Describe the bug**

Arguably a feature request

We use `pip` to install `semgrep` in our dev setup to ensure everybody uses the same version and therefore gets replicable ouput. Unfortunately, currently, there is no wheel for macOS arm64 so pip installs x86-64 binaries.

https://pypi.org/project/semgrep/#files

The same issue with the artifacts published to [github](https://github.com/returntocorp/semgrep/releases/tag/v0.74.0).

`brew install semgrep` works fine because semgrep-core is compiled for arm64 (unless I am missing something). Unfortunately, the pinning of versions with `brew` is not great and we also have a mix of Linux users.

```
# Semgrep installed via pip ---> x86-64

$ file /Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEn
N-py3.9/lib/python3.9/site-packages/semgrep/bin/semgrep-core
/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/bin/semgrep-core: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped

# Semgrep installed via brew --> arm64

$ file /opt/homebrew/Cellar/semgrep/0.73.0/libexec/lib/python3.9/site-packages/semgrep/bin/semgrep-core
/opt/homebrew/Cellar/semgrep/0.73.0/libexec/lib/python3.9/site-packages/semgrep/bin/semgrep-core: Mach-O 64-bit executable arm64
```

**To Reproduce**

1. On a M1 based (arm64) machine, run `pip install semgrep`.
2. Running a `semgrep --lang java -e 'DSL.or(...)'` inside the virtualenv.

```

$ /Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-
py3.9/bin/semgrep --lang java -e 'DSL.or(...)'
Traceback (most recent call last):
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/cli.py", line 683, in cli
    semgrep.semgrep_main.main(
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/semgrep_main.py", line 202, in main
    ) = CoreRunner(
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/core_runner.py", line 414, in invoke_semgrep
    ) = self._run_rules_direct_to_semgrep_core(rules, target_manager, profiler)
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/core_runner.py", line 354, in _run_rules_direct_to_semgrep_core
    core_run = sub_run(
  File "/Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/util.py", line 133, in sub_run
    result = subprocess.run(cmd, **kwargs)  # nosem: python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use
  File "/Users/jm/.pyenv/versions/3.9.7/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/jm/.pyenv/versions/3.9.7/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/jm/.pyenv/versions/3.9.7/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '


# Executing semgrep-core directly on M1

$ /Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/bin/semgrep-core
zsh: exec format error: /Users/jm/Library/Caches/pypoetry/virtualenvs/semgrep-standalone-vCBicEnN-py3.9/lib/python3.9/site-packages/semgrep/bin/semgrep-core
```

**Expected behavior**

There should be a wheel built for arm64 too.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

Right now, people on M1 machines have to install whatever latest version of `semgrep` `brew` wants to install. Using rosetta is not really an option since the python executable is compiled for arm64.

**Environment**
pypi on python 3.9.7

**Comment by j-martin** [comment]
I updated the ticket to mention that the artifacts on GitHub are also x86-64 only. https://github.com/returntocorp/semgrep/releases/tag/v0.74.0

**Comment by aryx** [comment]
Is this fixed @brendongo or should we lower its priority?

**Comment by j-martin** [comment]
@brendongo is there any timeline on fixing this?

**Comment by jesper** [comment]
Can confirm that this issue still persists in v0.77.0 of sempgrep when installed via pip on M1 macs.

**Comment by brendongo** [comment]
@j-martin Probably will have time for this in the second half of Feb? Currently busy with porting some semgrep-action functionality into semgrep that should be wrapped up by then.

**Comment by j-martin** [comment]
Sounds good. Thanks for the update. :)

**Comment by daghan** [comment]
@j-martin let us know if those timelines are workable.

**Comment by j-martin** [comment]
> @j-martin let us know if those timelines are workable.

Oh yeah, this is totally fine. Also, it's not like you folks owe me/us anything. ;)

**Comment by carjessu-zerohash** [comment]
This issue persists on version [v0.82.0](https://github.com/returntocorp/semgrep/releases/tag/v0.82.0) with M1 macs. Can we get an update on this? Is there anything I can do and/or test to help?

**Comment by brendongo** [comment]
Hi @carjessu-zerohash still busy with other things at the moment. Figuring out what tags the wheel would need to be tagged with to have m1 pypi pull the correct version would be helpful.

**Comment by j-martin** [comment]
For reference: https://pypi.org/project/numpy/1.22.2/#files `numpy-1.22.2-cp310-cp310-macosx_11_0_arm64.whl ` and `numpy-1.22.2-cp310-cp310-macosx_10_14_x86_64.whl `


According to https://github.com/numpy/numpy/blob/813a0c11186ded0b5caeb853fd2b22fb9addd511/doc/RELEASE_WALKTHROUGH.rst.txt#build-wheels it seems to be using this https://github.com/MacPython/numpy-wheels

**Comment by khanhldt** [comment]
Wouldn't this cause problem with people running Semgrep as pre-commit hook on M1 machine? I'm having similar error running Semgrep as pre-commit hook on an arm64 Linux machine.

**Comment by carjessu-zerohash** [comment]
> Wouldn't this cause problem with people running Semgrep as pre-commit hook on M1 machine? I'm having similar error running Semgrep as pre-commit hook on an arm64 Linux machine.

It does. This issue is currently keeping me from rolling this out as a pre-commit hook for our devs since we have a lot of Apple Silicon based macs.

**Comment by tino** [comment]
We run into the same (w/ pre-commit). Our workaround currently is to copy the brew installed `semgrep-core` over on in the virtual env of pre-commit. It's a bit ugly but it works.

**Comment by carjessu-zerohash** [comment]
@[brendongo](https://github.com/brendongo) That's: `semgrep-0.85.0-cp37.cp38.cp39.py37.py38.py39-none-any.whl`. It's referenced here: https://pypi.org/project/semgrep/#modal-close

**Comment by raianul** [comment]
after installing with brew its working in the terminal but getting the same error for pre-commit

```
(.venv) ➜  shorepay-service git:(update-precomit-config) ✗ semgrep --config=semgrep_rules.yaml
Scanning 126 files.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|126/126 tasks

Some files were skipped.
  Scan was limited to files tracked by git.
  Scan skipped: 35 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1 rule on 126 files: 0 findings.

python install raising error also pre-commit retuning same error -

```subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 799, in _start
    self._proc = subprocess.Popen(
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/sayed.kabir/.cache/pre-commit/repov06s4u6d/py_env-python3.10/lib/python3.10/site-packages/semgrep/bin/semgrep-core'
  0% 0/20 [00:00<?, ?it/s]

**Comment by brendongo** [comment]
Yep we are also seeing failures to install with pre-commit on M1 Macs. Currently getting a build on ARM is something we want to do in the next ~2 months but higher priority things keep popping up 😅 

What is necessary is something in github actions that would run our mac osx build script https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml#L135 in an M1 Mac environment or potentially running our linux build steps https://github.com/returntocorp/semgrep/blob/develop/.github/workflows/release.yml#L106 in a docker image that is ARM based. Once that is done it would be simple to get that binary into pypi with the tags people identified above 😄

**Comment by jmgilman** [comment]
Are there build artifacts for `semgrep_core` available for ARM? I don't mind building Python from source, but OCaml is a whole other thing! If anyone happens to be an OCaml expert, several people are [attempting to compile it over on Nix](https://github.com/NixOS/nixpkgs/pull/172808) and we could use some help :)

**Comment by lukaspiatkowski** [comment]
This issue is complete since now pypi installs semgrep-core compiled for arm64 on Apple Silicon, but the installed binary is missing dynamic libraries and doesn't work after `pip install`, see #5423 for bug report.
