### ISSUE TITLE
Scala function pattern results in parse error

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4319]
**Describe the bug**
If we type a pattern similar to `def $FUN(..., $X, ...) {...}` to match a generic function definition with input being passed into said function, semgrep-core gives a pattern parsing error.

**To Reproduce**
https://semgrep.dev/s/oY79

**Expected behavior**
Thought that the pattern would parse!

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by mmcqd** [comment]
This is happening because scala function parameters have to have their types annotated. It works if the pattern is `def $FUN(...,$X : $T,...) = {...}`. See https://semgrep.dev/s/86vj
