### ISSUE TITLE
Commit history scanner

### ISSUE THREAD

**Issue by roisec** [semgrep/semgrep#4325]
Hi,
There will be in the future a git commit history scanner?
Semgrep provides a solution for this? maybe pre-commit scanner?

Thanks

**Comment by aryx** [comment]
What do you mean by commit scanner? You mean just running semgrep on the files modified in HEAD?
or run semgrep on files modified in a specific commitid?

**Comment by roisec** [comment]
@aryx 
https://linuxhint.com/view-the-commit-history-of-the-git-repository/
Commit history can contain secrets and Semgrep does not search there ...
