### ISSUE TITLE
Support for Dockerfile

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4327]
**Describe the solution you'd like**

Support for dockerfile.

[This rule](https://github.com/returntocorp/semgrep-rules/issues/1596) has a false positive due to comments in a Dockerfile. Others have reported similar experience. Dockerfile support would help eliminate these FPs.

**Additional context**
Priority: Low (Not urgent)

**Comment by mjambon** [comment]
I was working on dockerfile support before I broke my arm. Maybe there'll be some preliminary support in 2-3 weeks, i.e. whenever I get back to full-time work.

**Comment by minusworld** [comment]
It's no rush - mainly just wanted to put it here for accounting purposes 👍
