### ISSUE TITLE
update to wcmatch 8.3 in Pipfile

### ISSUE THREAD

**Issue by priv-kweihmann** [semgrep/semgrep#4337]
wcmatch version 8.3 was released a couple of weeks back.
So far I don't see a reason why semgrep needs to be pinned to 8.2 version.

Please allow usage of wcmatch 8.3

**Comment by aryx** [comment]
What do you need from the latest version of wcmatch?

**Comment by priv-kweihmann** [comment]
```
NEW: Officially support Python 3.10. --> this definitely 
NEW: Provide type hints for API.
FIX: Gracefully handle calls with an empty pattern list. --> that's also very good to have
```

**Comment by brendongo** [comment]
Will look into updating it this week!
