### ISSUE TITLE
Generic mode can't bind environment variables to metavariables

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4347]
https://semgrep.dev/s/eobR should have two matches

**Comment by mjambon** [comment]
You have to keep in mind that the target code`$FOO` is parsed into two tokens, `$` and `FOO`. Moreover, the _pattern_ `$FOO` is a metavariable that will match exactly one _word_, which is an alphanumeric sequence of the form [A-Za-z_]+. To match the code `$FOO`, you need a pattern like `$ $ANY`: https://semgrep.dev/s/Q9oo
