### ISSUE TITLE
Generic mode does not find CMD match

### ISSUE THREAD

**Issue by chmccreery** [semgrep/semgrep#4348]
This should match on line 6, but doesn't https://semgrep.dev/s/vq5W

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by mjambon** [comment]
This is a problem with how the generic mode works* and the lack of indentation in dockerfiles. This will solve itself when we have proper dockerfile support, which should arrive soon-ish (January 2022).

*it finds two matches for CMD which both extend to the end of the file, does some pruning keeping only the shorter match, which is then excluded by the "not inside" clause. Excessive pruning may be a problem that could be solved. However, `CMD ...` matching until the end of the file is a deeper problem that can't really be fixed.

**Comment by mjambon** [comment]
We should close this when dockerfile support becomes available.

**Comment by aryx** [comment]
Does the example work @mjambon now that we have dockerfile native support?

**Comment by mjambon** [comment]
@aryx yes, it works. The pattern `CMD ...` matches just the cmd instruction rather than the current line and 9 lines that follow.
