### ISSUE TITLE
Allow object patterns directly for Javascript

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#435]
`{..., xssProtection: false, ...}` fails to parse

https://sgrep.live/405

**Comment by aryx** [comment]
Could be ambiguity with block statements.
In Js it's possible you can have those object definitions just after certain tokens (return, =) but not at the start of a statement.

**Comment by DrewDennison** [comment]
@aryx how should we look for properties in this object then?

**Comment by aryx** [comment]
it's a bit useless but <... { fld: val } ...> will clearly introduce an expression context where there would be no ambiguity. It's a bit ugly though. It would be nice to support { fld: val } directly.

**Comment by mschwager** [comment]
If we add this, don't forget to update the docs: https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#ellipsis-operator
