### ISSUE TITLE
cli: Deprecate --output

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#4354]
Semgrep `--output` may be superfluous given that one can just redirect `stdout`.

**Comment by ievans** [comment]
@IagoAbal I think output is still useful, especially in non-interactive use-cases; what's the reasoning behind getting rid of it?

**Comment by aryx** [comment]
@nbrahms thinks it's not very Unix-y. More discussions on slack.

**Comment by aryx** [comment]
I think @brendongo thinks it's a valid option.
