### ISSUE TITLE
Do not early exit when encountering a false positive while running rules tests.

### ISSUE THREAD

**Issue by aegarbutt-stripe** [semgrep/semgrep#4365]
**Is your feature request related to a problem? Please describe.**

When a false positive is encountered while running rules tests, `semgrep` performs an early exit. No data is sent to `stdout`, but two log lines formatted for human review are sent to `stderr`. This early exist only occurs when there is a rule false positive.

This early exit is problematic since it makes it difficult to include automated rule review in our CI pipeline.

See: https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/test.py#L259-L261

**Describe the solution you'd like**

Do not early exit when a false positive is encountered. The process exit code still exits with an error, but now the JSON output (or the confusion matrix) includes the data on all rules.

See: https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/test.py#L413-L417
and: https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/test.py#L397

**Describe alternatives you've considered**

This would be a change in behavior, does it make sense to put this behind a flag?

**Comment by brendongo** [comment]
Probably doesn't need to be behind a flag. Would have to dig into git history but I don't think early exit was ever an explicit requirement
