### ISSUE TITLE
[python] argument metavariable doesn't match argument with default value

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4367]
**Describe the bug**
Metavariables in argument position don't match arguments with default values

**To Reproduce**
https://semgrep.dev/s/Jx5k

**Expected behavior**
Expect a match

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

(this causes a FN for me)

**Comment by aryx** [comment]
Those are not arguments with default values, those are named arguments.

**Comment by aryx** [comment]
I don't think we should support this.

**Comment by aryx** [comment]
Also there are not use of argument metavariables in your example @nbrahms

**Comment by aryx** [comment]
Or maybe that's what you wanted to write: https://semgrep.dev/s/Dz7v ?

**Comment by aryx** [comment]
The reason it's not maching is because this x=4 is a named argument, it's not an expression.
But why do you want to match with a metavariable named argument? You will not be able to reuse this $X is another
part of the pattern.
