### ISSUE TITLE
Move default Docker analysis directory

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#438]
This directory is currently:

```python
REPO_HOME_DOCKER = "/home/repo/"
```

To shorten Docker volume command line arguments let's move this to something like `/code`.

`docker run -v "${PWD}:/home/repo"` is now coming up a lot - `docker run --rm -v "${PWD}:/code"` is a bit shorter and easier to remember. Also, `sgrep` doesn't require the directory to be a code repository, as far as I can tell. So `repo` is a bit of a misnomer.

We'll probably have to support both locations for a period of time as we deprecate the old one.

**Comment by DrewDennison** [comment]
I like this. I think it used to support both `/home/repo` and then I added `/src` which is what pre-commit requires for it's docker image tools. My vote is for `/src`

**Comment by mschwager** [comment]
Fixed in #1192.
