### ISSUE TITLE
Newlines sometimes break patterns in Go

### ISSUE THREAD

**Issue by mmcqd** [semgrep/semgrep#4392]
**Describe the bug**
The pattern `&http.Transport{...}` works but 
```
&http.Transport{
  ...
}
```
produces an error

**To Reproduce**
https://semgrep.dev/s/KXj9

**Expected behavior**
The two patterns should be equivalent

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by aryx** [comment]
Could be related to ASI (automatic semicolon insertion), which is used in languages like Go and Javascript.

**Comment by aryx** [comment]
See the Parsing_hacks_go.ml

**Comment by mmcqd** [comment]
> Could be related to ASI (automatic semicolon insertion), which is used in languages like Go and Javascript.

That's exactly what it was
