### ISSUE TITLE
Rename to semgrep

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#440]
Rename the `sgrep` directory to `semgrep-core` and rename `sgrep_lint` to `semgrep`. Update names of binaries, constants, and files as required.

**Comment by ievans** [comment]
cc @DrewDennison for the domain names and sgrep.live updates

**Comment by ievans** [comment]
Also, do we really need to rename the sgrep core? What if semgrep is the public name but we just leave the `sgrep` directory alone?

**Comment by dlukeomalley** [comment]
@brendongo @rcoh @nbrahms Since we're getting more users this week for semgrep and meetups continue to happen, could we prioritize the name change this week?

CC @pabloest if external marketing/content needs to change.

**Comment by rcoh** [comment]
I'm working on this today.

**Comment by brendongo** [comment]
> Also, do we really need to rename the sgrep core? What if semgrep is the public name but we just leave the `sgrep` directory alone?

Functionally no but I think we want to avoid having both sgrep and semgrep as executables.

**Comment by DrewDennison** [comment]
@brendongo lmk when you want me to change any domain pointers i.e. sgrep.dev, docs.sgrep.dev, and sgrep.live

**Comment by pabloest** [comment]
What do y’all think of using `.org` as the TLD for semgrep?

**Comment by aryx** [comment]
I think it's better to change also the sgrep internal directories, just so that we also internalize the change. If each time I have to cd semgrep-core, I will remember more that we changed the name.

**Comment by brendongo** [comment]
Status: domain pointers are done, executable is now called semgrep and semgrep-core, directories are now called semgrep and semgrep-core. We have not touched internal ocaml code to convert references from sgrep to semgrep.
