### ISSUE TITLE
[Python] semgrep always highlights one extra character

### ISSUE THREAD

**Issue by IRDonch** [semgrep/semgrep#4400]
**Describe the bug**
When semgrep highlights parts of the shown lines to demonstrate which parts matched the given expression, it always highlights one more character than needed.

**To Reproduce**
Create a file named `test.py` with the following contents:

```python
import sys
sys.exit(0)
```

Then run `semgrep -l python -e sys.exit test.py`. It outputs the following:

```
test.py
2:sys.exit(0)
ran 1 rules on 1 files: 1 findings
```

The following segment is highlighted: `sys.exit(`.

**Expected behavior**
The left parenthesis should not be highlighted.

**Screenshots**
![image](https://user-images.githubusercontent.com/42033526/145252124-e024094c-5286-41ae-aea6-dbbb184f055d.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep 0.76.1 (official binary) running on Python 3.6.

**Comment by ievans** [comment]
Interesting to note this doesn't reproduce in the playground, which is I believe because playground uses `offset`: https://semgrep.dev/s/GgXn
