### ISSUE TITLE
Document how to create unit test files when rule assumes specific file name or path

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#4405]
**Is your feature request related to a problem? Please describe.**
Some Semgrep rules flag issues in files of a specific name. 

For example, perhaps we're looking in a dependency file (`package.json`, `Gemfile`, `Pipefile`, ...), a configuration file (e.g. `web.xml`), `Dockerfile`, etc. To make the rule high signal, since we know only certain files are relevant, we may use the [paths](https://semgrep.dev/docs/writing-rules/rule-syntax/#paths) key to include only the relevant files, like:

```
rules:
  - id: my-rule
    paths:
      include:
        - package.json
```

I see for the Docker rules [here](https://github.com/returntocorp/semgrep-rules/tree/develop/generic/dockerfile/security) the way we seem to handle it is create `my-rule.dockerfile`, or a `.html` or `.mustache` [here](https://github.com/returntocorp/semgrep-rules/tree/develop/generic/html-templates/security).

But the [testing docs](https://semgrep.dev/docs/writing-rules/testing-rules/) only say that a rule named `my-rule.yaml` must have a test file named `my-rule.[py|rb|whatever]`. 

**Describe the solution you'd like**
Does Semgrep already have this functionality and maybe it's just not obvious to me how to use it?

Outcome: I'd like for it to be clear for users how to create unit tests when the rule has specific file name constraints, whether it's for a programming language (e.g. `Gemfile` is Ruby code), generic mode, or other.

Maybe this is already solved, and we just need to update the docs, I'm not sure.

**Describe alternatives you've considered**
Not having tests 😅  This is what we've done for some internal work (e.g. inventory).

**Comment by daisylb** [comment]
I've run into this issue as well. For us, for now, the workaround is that we are just not using `paths.include` on our rules, but that means that, as an example, we have one rule where we only need to be scanning ~1,000 files, but instead we're scanning ~12,000 files.

**Comment by bew** [comment]
Hello, this is still a problem, can someone please re-open this issue?

**Comment by jonny64** [comment]
This is still a problem.
I want to speed up: scan .html only when
```
    paths:
        include:
          - "*/html/*"
```
but this cause broken tests: they reside in `html/rule.html` paired with `html/rule.yaml` , not `html/html`

@ievans  why, why this an documentation problem? this is broken by design
