### ISSUE TITLE
End to end test for build artifacts

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#441]
Have a sanity check of running sgrep-lint from the binaries/build artifacts created by the build scripts/github actions. Running a simple rule over a small file should be sufficient. In particular it would be a good check to install the binaries where system python is 3.5 or even 2.7.

**Comment by DrewDennison** [comment]
@rcoh @brendongo I believe this is done with the validate scripts. I'm gonna close but please open if not

**Comment by rcoh** [comment]
Still need one more for the Ubuntu Installer

**Comment by ievans** [comment]
confirmed with @brendongo that this is fixed
