### ISSUE TITLE
[js-experimental] Add the ability to parse the '::' operator in Semgrep for javascript

### ISSUE THREAD

**Issue by Jason-Lim00** [semgrep/semgrep#4416]
**Is your feature request related to a problem? Please describe:**

Semgrep currently does not support parsing for the '::' operation in javascript. An example can be found in the following error and code snippet below in the additional context.

**Describe the solution you'd like:**

It would be nice to add the ability to parse this to help with faster code writing as well as keeping up with shorthand ways of coding a certain operation.

**Describe alternatives you've considered:**

The only alternative is to revert back to using the bind() operation which is the longhand for that '::' operator.

**Additional context:**

Error:
```
| Semgrep exited with 629 errors:
|    Semgrep Core WARN - Syntax error: When running typescript.react.security.audit.react-html-element-spreading.react-html-element-spreading on js/component/Input/PowerDropdown.js: `::` was unexpected
```

Code snippet that it is faulty on:
```
handleEscapePress = ::this.handleEscapePress;
handleDocumentClick = ::this.handleDocumentClick;
```

**Comment by mjambon** [comment]
I can't find documentation for this. It looks like it was a proposal for ES7 (2016) but there's no trace of it in the [ES7 spec](https://262.ecma-international.org/7.0/) or later. Here's [confirmation](https://news.ycombinator.com/item?id=18041979) that the bind operator `::` wasn't adopted in javascript. It wasn't adopted in typescript either but a [comment indicates that the ES proposal has been recently revived](https://github.com/Microsoft/TypeScript/issues/3508#issuecomment-920288203) (Sep 2021).

We can support whatever is supported by typescript via the [tree-sitter-typescript implementation](https://github.com/tree-sitter/tree-sitter-typescript) but if it's not an official feature of typescript, it's going to be complicated.
