### ISSUE TITLE
semgrep in go

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#442]
Achieve feature parity with current sgrep-lint but in golang

**Comment by ievans** [comment]
What will happen to the "pattern-where-python" functionality in the golang port?

**Comment by aryx** [comment]
This is a mistake ...

**Comment by minusworld** [comment]
Other options mentioned, I think
- ReasonML, which has a JS-like syntax and is interopable with Ocaml, which can then compile
- Rust?
