### ISSUE TITLE
`...` operator doesn't match 0 statements, only 1 or more

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#443]
**Describe the bug**
`...` operator doesn't match 0 statements, only 1 or more in javascript. See code example.

**To Reproduce**
https://sgrep.live/PLW

**Expected behavior**
It's expected that  the snippet:
```
$APP.$METHOD(..., function($REQ, $RES) { 
                ...
                $RES.redirect(...);
                ...
              })
```

matches a superset of what:
```
$APP.$METHOD(..., function($REQ, $RES) { 
                $RES.redirect(...);
              })
```
would match, but this does not happen (see line 19-22 in the snippet provided)

**Comment by aryx** [comment]
That is weird indeed ...

**Comment by aryx** [comment]
Thx Martin!
