### ISSUE TITLE
Rust parse error on 'allow' attribute

### ISSUE THREAD

**Issue by rc-mattschwager** [semgrep/semgrep#4444]
**Describe the bug**

Parse error on `allow` attribute: https://stackoverflow.com/questions/25877285/how-to-disable-unused-code-warnings-in-rust

Similar to https://github.com/returntocorp/semgrep/issues/3762, but not exactly the same.

**To Reproduce**

https://semgrep.dev/s/38Ab

**Expected behavior**

Successfully parses.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by emjin** [comment]
👋

**Comment by rc-mattschwager** [comment]
Hi from the outside! I'm giving Semgrep a go on some Rust projects :)

**Comment by aryx** [comment]
Issue 4444! I'm sure this pleases @rc-mattschwager who likes magic numbers :)
