### ISSUE TITLE
Rust parse error `!` was unexpected

### ISSUE THREAD

**Issue by rc-mattschwager** [semgrep/semgrep#4445]
**Describe the bug**

Getting a Rust parse error: `'!' was unexpected`.

Unfortunately it doesn't tell me which `!` was unexpected, so I've included the whole file.

**To Reproduce**

https://semgrep.dev/s/Pgpq

**Expected behavior**

Successfully parses.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by aryx** [comment]
This works now: https://semgrep.dev/s/Pgpq?version=develop
