### ISSUE TITLE
Limit the result to the function argument

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#4453]
**Is your feature request related to a problem? Please describe.**
For example, if I use the pattern `requests.get(..., verify=False, ...)` to match a function with a specific argument, it will report the entire function call like:
```
requests.get(
  "https//www.example.com",
  params={
    "a": "a",
    "b": "b",
    "c": "c",
  },
  headers={
    "X-REQUEST-ID": "123456",
  },
  timeout=10,
  verify=False,
)
```
Therefore, any changes to other arguments would be reported as a new finding in Semgrep CI.
This might be the desire behavior in some cases, but if a function call (or class initialization) has many arguments, it often reports irrelevant changes.

**Describe the solution you'd like**
A feature to optionally report new findings for changes in only part of a pattern (e.g. argument of a function call).
Throwing out some ideas here.
1. Use special syntax to limit the scope. For example, `requests.get(..., $[[verify=False]], ...)`.
2. A new option to limit the result to a metavariable.
  Something like
```
patterns:
   - pattern-inside: 'requests.get(..., verify=$X, ...)'
   - pattern: $X
```
Doesn't work in general because assume `$X` is `False`, other argument with the value `False` would also be reported.
However, maybe we can have a new field to tell semgrep to only return a metavariable.
For example,
```
pattern: 'requests.get(..., verify=$X, ...)'
result-metavariable: $X
```
3. Similar to option 2, but use a special metavariable.
For example, `pattern: 'requests.get(..., verify=$RESULT, ...)'`
4. Add a new option similar to option 2, but semgrep will return the same finding and only limit the scope in Semgrep CI.
For example,
```
pattern: 'requests.get(..., verify=$X, ...)'
ci-context: $X
```

**Comment by aryx** [comment]
This was on behalf of poning
We might want to give some love to this feature, and actually it can even help optimize those pattern:$X cases.
cc @emjin

**Comment by ievans** [comment]
Great writeup. Related to https://github.com/returntocorp/semgrep/issues/3304
