### ISSUE TITLE
semgrep reports "invalid configuration file" when running from homedir

### ISSUE THREAD

**Issue by adds68** [semgrep/semgrep#4457]
**Describe the bug**
Fresh install of semgrep from brew reports this error when calling 'semgrep' via cli

```
➜  ~ semgrep          
semgrep error: missing keys
  --> .semgrep/settings.yml:1
1 | has_shown_metrics_notification: true

/settings.yml is missing `rules` as top-level key

invalid configuration file found (1 configs were invalid)
```

Config file, which seems to get re-generated if i delete it:

```
➜  ~ cat .semgrep/settings.yml 
has_shown_metrics_notification: true
```

**To Reproduce**
Install 0.77.0 via brew on MacOS 11.6.1 and call semgrep via the cli

**Expected behavior**
No errors reported about configs?

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Installed 0.77.0 from brew

**Comment by ievans** [comment]
I am able to reproduce this, but only when running from my home directory. @adds68 does it work if you run semgrep outside of the home directory?

**Comment by nbrahms** [comment]
@ievans @aryx @adamboros ... I think we should remove implicit yml discovery, and just make `--config` a required option.

**Comment by ievans** [comment]
@nbrahms that would break backwards compatibility for some % of users; what's the advantage of doing that for the general user?

**Comment by aryx** [comment]
I think this has been fixed right @brendongo ?

**Comment by brendongo** [comment]
No but treating all yaml files in a .semgrep directory in CWD when running without `--config` is desired behavior. IMO running from root without a config is fringe enough.

**Comment by mjambon** [comment]
Running `semgrep` in the most naive way should do something pleasant for the user. Ideally, it would do something useful that makes sense. I'm reopening the issue.

**Comment by mjambon** [comment]
@aryx rather than excluding any `.semgrep` folder from the scan, I suggest excluding only `~/.semgrep` because it's unlikely to be the root of a project (some projects [use `.semgrep`](https://github.com/hashicorp/nomad/tree/main/.semgrep) to store their project-local rules as reported by @ievans).
