### ISSUE TITLE
Semgrep fails when method brace is on new line in class expression

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#4459]
https://semgrep.dev/s/sjord:zj74

test.js (edited since this issue was created):
```
export default class {
    someMethod() 
    {
        return 0;
    }
}
```

Actual:
```
$ semgrep -v -e 'return 0;' -l javascript test.js
No .semgrepignore found. Using default ignores rules
Semgrep Core WARN - Syntax error: When running - on test.js: `{        return` was unexpected
ran 1 rules on 1 files: 0 findings
found problems analyzing 1 file; run with --verbose for details or run with --strict to exit non-zero if any file cannot
be analyzed cleanly
Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False
```

Expected:
```
$ semgrep -v -e 'return 0;' -l javascript test.js
No .semgrepignore found. Using default ignores rules
test.js
4:        return 0;
ran 1 rules on 1 files: 1 findings
Not sending pseudonymous metrics since metrics are configured to AUTO and server usage is False
```
```

**Comment by nbrahms** [comment]
Thanks for the bug report @Sjord !

@mjambon tagging you here as the default maintainer for js. Tagging as high prio as this seems like pretty basic parsing.

**Comment by nmote** [comment]
This syntax error message isn't great, but I don't think this is actually a bug. Babel, TypeScript, and Flow all issue an error on this code:

https://babeljs.io/repl#?&code_lz=MYGwhgzhAEDeBQ0nQgewLYFMCymAuAFqgCYAUAlIsgsrdAE74Cu9AdtAAwDcVSAvvD5A

https://www.typescriptlang.org/play?#code/MYGwhgzhAEDeBQ0nQgewLYFMCymAuAFqgCYAUAlIsgsrdAE74Cu9AdtAAwDcVSAvvD5A

https://flow.org/try/#0MYGwhgzhAEDeBQ0nQgewLYFMCymAuAFqgCYAUAlIsgsrdAE74Cu9AdtAAwDcVSAvvD5A

Wrapping the program text with parentheses allows Semgrep to parse it as a class expression: https://semgrep.dev/s/RgP8

Adding the parentheses also addresses the parse errors with Babel, TypeScript, and Flow. I haven't looked at the spec for this change but I think it's likely that this is correct behavior, seeing as three major JS parsers all agree with Semgrep.

**Comment by nmote** [comment]
In fact, it looks like it may be a bug that Semgrep *does* parse a top-level class expression when the brace is on the same line as the method name: https://semgrep.dev/s/A5ww

Babel, TS, and Flow all reject this code.

**Comment by Sjord** [comment]
Thanks, @nmote. It seems that I created invalid JavaScript while trying to reduce the offending file to a minimal test case. It seems the following is valid JavaScript, but not parsed by semgrep. What do you think?

```
export default class {
    someMethod() 
    {
        return 0;
    }
}
```

**Comment by nmote** [comment]
Yes, that certainly looks like a Semgrep bug to me. I checked TS and Flow and both parse that successfully. I don't have time to continue looking into this at the moment but I may in the future.
