### ISSUE TITLE
In taint mode, variables in `pattern-inside` are not exposed to messages and join mode

### ISSUE THREAD

**Issue by jwbth** [semgrep/semgrep#4464]
**Describe the bug**
In taint mode, variables used in `pattern-inside` are not available to the message and rules in join mode.

**To Reproduce**
https://semgrep.dev/s/bX6W
You can see "VAR: a FUNC: $FUNC" in the match message.

**Expected behavior**
"VAR: a FUNC: doSmth" in the match message.

**Details**
This happens only in taint mode. In search mode, if you rename `pattern-sources` to `pattern-either`, variables in `pattern-inside` *are* exposed to messages, see https://semgrep.dev/s/NwOy: "VAR: a FUNC: doSmth".

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

This is important for me as this eliminates a major use case of taint + join mode for me.

**Comment by aryx** [comment]
@IagoAbal I've lowered the priority since nobody fixed it in the last 3 months.
