### ISSUE TITLE
Support XDG Base Directory Specification

### ISSUE THREAD

**Issue by itaranto** [semgrep/semgrep#4465]
Please support the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) on Linux/*nix systems.

Right now `semgrep` puts its config file under `~/.semgrep/`, the correct location should be `$XDG_CONFIG_HOME/semgrep/` with a fallback to `~/.config/semgrep/`.

It doesn't need to be perfect at first, but moving `semgrep` files from the `$HOME` directory would be a good start.  
It's 2021, the standard has been for a while now, and users don't like having junk in their home directories.

Thanks.

**Comment by brendongo** [comment]
I think #4818 handles this

**Comment by itaranto** [comment]
> I think #4818 handles this

This doesn't support the XDG spec properly, to do that, the fallback should be `$HOME/.config/semgrep` not `$HOME/.semgrep`.

@tpetr

**Comment by itaranto** [comment]
Something like this:

```python
if "XDG_CONFIG_HOME" in os.environ and Path(os.environ["XDG_CONFIG_HOME"]).is_dir():
    USER_DATA_FOLDER = Path(os.environ["XDG_CONFIG_HOME"]) / "semgrep"
else:
    USER_DATA_FOLDER = Path.home() / ".config" / "semgrep"
```

**Comment by tpetr** [comment]
Whoops, thanks for catching this. I can make a follow up PR in the near future.
