### ISSUE TITLE
Uname process doesn't close when running in Linux OS

### ISSUE THREAD

**Issue by ghost** [semgrep/semgrep#4466]
**Describe the bug**
Running semgrep CLI from Amazon Linux OS doesn't close the `uname` process what causes a memory leak.

**To Reproduce**
Run Semgrep CLI in Amazon Linux OS.
`uname` processes doesn't close.

**Expected behavior**
after semgrep process has finished - close all the relevant processes.

**Screenshots**
![image](https://user-images.githubusercontent.com/16287464/147869560-6c82d05c-8280-46f0-bc14-27ff260f8c21.png)

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Amazon Linux OS
Semgrep version 0.77.0

**Comment by aryx** [comment]
Can you give us the precise command you run? semgrep --???
so we can try to reproduce the issue on our hand.

**Comment by ghost** [comment]
Hey @aryx  sorry for the late reply, the command that I run is - 
`semgrep -q --json --disable-metrics -c p/r2c-security-audit . -o /tmp/semgrep.json`

**Comment by mjambon** [comment]
@naortalmor this should be fixed in the upcoming semgrep release (0.83.0).

**Comment by ghost** [comment]
@mjambon  cool thanks you very much!
