### ISSUE TITLE
PHP not matching function definitions

### ISSUE THREAD

**Issue by tim-goddard-cybercx** [semgrep/semgrep#4494]
Just testing out the experimental PHP support, and it appears not to match function definitions (whether the function name is defined or wildcarded):

https://semgrep.dev/s/Nw9p

Cheers,

Tim

**Comment by ievans** [comment]
Hi Tim, I don't know PHP, but does the file parse in the regular PHP interpreter? Adding a `<?php` prefix makes your example work for me, see: https://semgrep.dev/s/gXoJ

**Comment by tim-goddard-cybercx** [comment]
Huh, okay - my mistake, sorry.

I thought I'd simplified it to the minimal case, but there must be another reason that's not coming up. If and when I find a genuine issue, will report it :)

**Comment by ievans** [comment]
No problem, thanks for the update!
