### ISSUE TITLE
bash mode doesn't propagate dataflow through backticks (`) 

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4497]
**Describe the bug**
I expected that
```
yy =\`curl $SOME_URL\`
```

Would be matched by a `pattern-source` with \`curl ...\`

But it is not, see: https://semgrep.dev/s/ievans:taint-mode-bash line 7.

**Expected behavior**
The snippet fires on line 7.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

using Semgrep 0.77

**Comment by IagoAbal** [comment]
Is that correct Bash?

This works:
```
yy=`curl $SOME_URL`
```
Adding spaces before or after changes the meaning.

I'm just not sure if
```
yy= `curl $SOME_URL`
``` 
is being parsed correctly, it seems that the `yy=` part is thrown away. cc @mjambon

**Comment by ievans** [comment]
d'oh! Thanks @IagoAbal, you are absolutely right. Correcting the syntax to remove the spaces before and after = fix it.
