### ISSUE TITLE
Semgrep installing the wrong binary for Darwin

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#4505]
**Describe the bug**

Install from pip copy over the wrong semgrep-core binary. 

**To Reproduce**

* pip install semgrep
* run semgrep on a file
```
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/..../venv/lib/python3.8/site-packages/semgrep/bin/semgrep-core'
```
```
file semgrep-core 
semgrep-core: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
```

I am on Mac Intel chip, using zsh.
```
uname -a
Darwin*** 20.6.0 Darwin Kernel Version 20.6.0: Wed Nov 10 22:23:07 PST 2021; root:xnu-7195.141.14~1/RELEASE_X86_64 x86_64
````
Semgrep version: 0.77.0
Python: 3.8.9

**Expected behavior**

Install a MachO semgrep-core.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by IagoAbal** [comment]
Probably the same as #4311.

**Comment by ajinabraham** [comment]
This is Intel Mac

**Comment by brendongo** [comment]
Could be https://github.com/returntocorp/semgrep/issues/2402 ? What version of pip are you running?

**Comment by ajinabraham** [comment]
That was it. Updating pip resolved it. Thanks!
