### ISSUE TITLE
Semgrep trying to scan not supported languages file with ruby rule [regression]

### ISSUE THREAD

**Issue by vedanandusekar** [semgrep/semgrep#4508]
I have reported this issue previously as well but this issue is for `semgrep` is trying to run `ruby` rules against `dockerfile`. 

My previous issue was fixed https://github.com/returntocorp/semgrep/issues/4310. 

our current version of semgrep is `0.77.0`

The error: 

`Checks for divide by zero. Best practice involves not dividing a variable by zero, as this leads to a Ruby ZeroDivisionError.`

Let us know how we can fix it.
Any help would be appreciated

**Comment by vedanandusekar** [comment]
@aryx

**Comment by aryx** [comment]
What is the exact semgrep command you are running, so I can try to reproduce on my end.
Are you still using semgrep via pre-commit?
cc @mmcqd

**Comment by ievans** [comment]
@vedanandusekar sorry about that, and thanks for filing an issue; can you share a rough prioritization? is this a blocker to using Semgrep (p0), big issue (p1), minor annoyance (p2)?

**Comment by vedanandusekar** [comment]
@aryx 
`semgrep --config=p/r2c-security-audit --JSON` this command

**Comment by vedanandusekar** [comment]
@ievans It is P1 as it is giving a lot of false positives.

**Comment by IagoAbal** [comment]
~@vedanandusekar Could you share a (possibly minimized) `Dockerfile` that triggers this error?~ Never mind, I guess the problem here is that the `Dockerfile` is being passed explicitly to Semgrep, so the content of the `Dockerfile` is not very relevant.

**Comment by underyx** [comment]
Hi @vedanandusekar! I'm currently working on file targeting so I tried to take a stab at this issue.

Unfortunately after trying to run `semgrep --config=p/r2c-security-audit` on a couple repositories that have several Dockerfiles in them, I didn't get any results from ruby rules.

Could you share a specific rule and line in a Dockerfile that triggers this bug? Thank you! 🙌

**Comment by brendongo** [comment]
Tried to repro again with `semgrep --config=p/r2c-security-audit Dockerfile` and we don't seem to be scanning the Dockerfile as ruby anymore even with explicit targeting. I'm going to assume this has been resolved. @vedanandusekar feel free to reopen another issue if this is still happening with latest semgrep
