### ISSUE TITLE
[TS] Cannot match annotated variables

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#4515]
Reporting on behalf of customer.

**To Reproduce**

https://semgrep.dev/s/Zj5D

Using `semgrep-core -lang ts -dump_pattern` it seems that when parsing `(v8 as $T)` as a pattern we throw away the type annotation, and this is represented as just `v8` in Generic. However with `-dump_ast`, the type annotation is there (as a Generic `Cast`).

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by ievans** [comment]
after further discussion with the user, bumping to priority:high cc @IagoAbal
