### ISSUE TITLE
Match any string ("...") tackles non string values

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#452]
https://sgrep.live/g1Z

while testing this rule:
```yaml
var $JWT = require("jsonwebtoken");
...
var $T = $JWT.sign($P, "...", ...);
```

it seems like this part `"..."` works even for non string values:

```javascript
const jsonwt = require('jsonwebtoken')
const payload = {foo: 'bar'}
const token4 = jsonwt.sign(payload, {raz: 1, tri: 1})
```

Noticed this behaviour only inside function calls

**Comment by brendongo** [comment]
https://sgrep.live/QyQ Looks like core issue is maybe "..." is matching null

Also: https://sgrep.live/39p

**Comment by aryx** [comment]
Thx @brendongo, yes that's the issue.

**Comment by aryx** [comment]
thx for the minimal test also.
