### ISSUE TITLE
--no-git-ignore isnt being respected

### ISSUE THREAD

**Issue by s-santillan** [semgrep/semgrep#4537]
**Describe the bug**

Default Semgrep ignore behavior (behavior when there is NO explicit .semgrepignore file) overrides the --no-git-ignore flag. This means that running Semgrep by default with `semgrep --no-git-ignore` still skips gitignored files, even though it should not.

**To Reproduce**

**Docs say:** "--no-git-ignore will disable git-aware filtering." So files named in .gitignore should now be scanned.

I tested semgrep on [DjangoGoat](https://github.com/red-and-black/DjangoGoat), a repo for security testing.

1. Because the 0.78 release does not yet state what files are ignored in verbose, I ran semgrep with config auto and noted down which files are the slowest to run (because they will always show up in the summary)
2. I added a "slow" file to the .gitignore, then ran semgrep with config auto AND --no-git-ignore, believing that --no-git-ignore should be respected over default semgrep ignore patterns, so the "slow" file should be scanned.
3. Result: Semgrep still skipped the file.

Add'l note from Brendon:
"Ah i think i know what’s happening, the default semgrepignore includes a gitignore pointer."

**Expected behavior**
--no-git-ignore should still be applied.

**Screenshots**
n/a

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep cli v0.78.0

**Comment by ievans** [comment]
I would love for us to match (possibly exactly) the behavior of `ripgrep`. We might even be able to statically link the rust libraries it uses into Semgrep! https://github.com/BurntSushi/ripgrep/tree/master/crates/ignore

We could have the `--no-ignore-X` flags and the [`-uuu` flags](https://github.com/returntocorp/semgrep/issues/4539)

```
         --no-ignore-dot
            Don't respect .ignore files.

            This flag can be disabled with the --ignore-dot flag.

        --no-ignore-exclude
            Don't respect ignore files that are manually configured for the repository
            such as git's '.git/info/exclude'.

            This flag can be disabled with the --ignore-exclude flag.

        --no-ignore-files
            When set, any --ignore-file flags, even ones that come after this flag, are
            ignored.

            This flag can be disabled with the --ignore-files flag.

        --no-ignore-global
            Don't respect ignore files that come from "global" sources such as git's
            `core.excludesFile` configuration option (which defaults to
            `$HOME/.config/git/ignore`).

            This flag can be disabled with the --ignore-global flag.

        --no-ignore-messages
            Suppresses all error messages related to parsing ignore files such as .ignore
            or .gitignore.

            This flag can be disabled with the --ignore-messages flag.

        --no-ignore-parent
            Don't respect ignore files (.gitignore, .ignore, etc.) in parent directories.

            This flag can be disabled with the --ignore-parent flag.

        --no-ignore-vcs
            Don't respect version control ignore files (.gitignore, etc.). This implies
            --no-ignore-parent for VCS files. Note that .ignore files will continue to be
            respected.

            This flag can be disabled with the --ignore-vcs flag.
```

**Comment by ievans** [comment]
If we used ripgrep's library we would could possibly nail the speedups requested in https://github.com/returntocorp/semgrep/issues/4543 as well

**Comment by s-santillan** [comment]
I think this issue got fixed at some point and we never closed this. Closing as fixed.
