### ISSUE TITLE
Ruby pattern parse error on parameter name: value key pair

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4538]
**Describe the bug**
There is a ruby pattern parse error on a parameter name value key pair separated by a column. It seems like the pattern parser errors on matching statements like: 
```
foo(..., key: value,...)
```

**To Reproduce**
(https://semgrep.dev/s/386D)

**Expected behavior**
Expecting this pattern to parse.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by aryx** [comment]
You were using 4 dots. See https://semgrep.dev/s/qyQB

**Comment by aryx** [comment]
We could create a ticker for improving the error message, to more accurately point out where is the error.

**Comment by colleend** [comment]
🤦‍♀️ 🤦‍♀️ 🤦‍♀️ 

Good catch! An improved error message would definitely be helpful 😅
