### ISSUE TITLE
unit test for pattern-regex always fails locally

### ISSUE THREAD

**Issue by ZyanKLee** [semgrep/semgrep#4540]
**Describe the bug**
I wrote some rules and their corresponding unit tests and use them locally. Since v0.77.0 these tests always fail, up to 0.76.2 they work fine. The very same rules succeed when copy-n-pasting them to the playground:
https://semgrep.dev/s/zyanklee:httpd-rewriterule-too-many-spaces

**To Reproduce**
1. Go to https://semgrep.dev/s/zyanklee:httpd-rewriterule-too-many-spaces
2. Copy rule into a .yaml file, copy test code into a .conf file of same name.
3. run `semgrep --test path/to/files`
4. See error and compar with matches from playground

**Expected behavior**
I expect the unit tests to work properly for generic rules when run locally, too.

**Priority**
How important is this to you?
- [x] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Screenshots**
locally not working:
![grafik](https://user-images.githubusercontent.com/1178490/150119034-d361eb51-c93a-414a-b89c-54e382f90dbc.png)

working in playground:
![grafik](https://user-images.githubusercontent.com/1178490/150118325-bcfe6a50-a7d0-4b3f-8d1d-677a0238a9da.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 91.5.0esr

**Linux:**
 - OS: Ubuntu 20.04 LTS
 - Semgrep: 0.76.2 vs 0.77.0-0.78.0

**Additional context**
Thanks for building this great tool! You are awsome!

**Comment by minusworld** [comment]
@colleend Might this have anything to do with --test changes? I wouldn't think so, but I am wondering if this rings any bells.

**Comment by colleend** [comment]
Hmm, that's a good question -- I'll investigate whether it's related to `--test` changes 👍 . I ran it on my machine (MacOS Monterey). 

With semgrep version 0.75.0, I got the confusion matrix with 1 TN and 3 TP (all tests passed). I then ran it with version 0.78.0, and got `✓ All tests passed!`, with no failure on the `--test` end. 

My being unable to reproduce the issue might also be due to OS differences 🤔 . But I think it might be more likely to have to do with changes in semgrep-core. 🤔

**Comment by ZyanKLee** [comment]
Hello,

thanks @minusworld for moving the ticket.

Thanks @colleend for looking into it. May the issue be related to the fact, that I do not run semgrep on each file individually, but have multiple files in the folder and run the `--test` on the whole folder?

**Comment by ZyanKLee** [comment]
Ok, I tried it with only a single rule in a single .yaml with the corresponding .conf in a separate folder, still it failed:
```
❯ semgrep --test test/     
Running 1 rules...
ran 1 rules on 0 files: 0 findings
The following unit tests did not pass:
--------------------------------------------------------------------------------
        ✖ too-many-spaces                                              expected lines: [5, 8, 11], reported lines: []
         test file path: [redacted]/test/whitespace.conf
```

running it like this seems to succeed, though:
```
❯ semgrep --test test/whitespace.yaml 
✓ All tests passed!
```

**Comment by nbrahms** [comment]
Tagging @IagoAbal to see if there's anything going on with the core engine here.

**Comment by IagoAbal** [comment]
@ZyanKLee could you please try to reproduce with 0.80.0 or 0.81.0 ? I could not reproduce it myself on MacOS 11. Using Semgrep 0.80.0 and doing everything exactly as you described, I got `✓ All tests passed!`.

**Comment by ZyanKLee** [comment]
Hey @IagoAbal, you are right. I can't reproduce with 0.80.0 nor 0.81.0
I guess I will upgrade and we can close this ticket if you do not need it anymore.

Thanks for your support everyone!

**Comment by IagoAbal** [comment]
Great to hear it works for you too! I'll then close, but if someone thinks that we should investigate why it failed, then please reopen.
