### ISSUE TITLE
Ruby metavariable matching in class objects

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4550]
**Describe the bug**
Ruby metavariable representing a serialized class variable is not matching the variable when a new object is created.

**To Reproduce**
https://semgrep.dev/s/Byg7
Would expect this rule to match on line 7

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by aryx** [comment]
Which metavariable are you talking about in your example?
I think the prolbme is the use of :$INPUT and .$INPUT, which are not matched with each other
when it's used as :tags and .tags.

**Comment by colleend** [comment]
was talking about the $INPUT metavariable -- is there a way to get the metavariable to match both the `tag` in `:tag` and the `tag` in `post.tag`?

**Comment by colleend** [comment]
🙏 thanks for fixing this so quickly!
