### ISSUE TITLE
Literal string patterns seem to confuse `metavariable-pattern`

### ISSUE THREAD

**Issue by xmo-odoo** [semgrep/semgrep#4567]
**Describe the bug**
Trying to exclude literal strings from a metavariable match

**To Reproduce**
https://semgrep.dev/s/gXKy

**Expected behavior**
From my (admittedly shallow and probably incomplete) understanding this should exclude the cases where a `getattr`'s second parameter is a literal string.

The behaviour is odd because a literal string seems to match *everything*: if the patttern is flipped (to `- pattern: "..."`) then all the lines match.

If the literal string is replaced by the name `key`, then I get the expected behaviour (only the first two expressions match the pattern).

**What is the priority of the bug to you?**
P2

**Comment by xmo-odoo** [comment]
Note: I downgraded the priority from P1 (quite annoying) because this specific case at least [I can express otherwise](https://semgrep.dev/s/PgzE), but I think the general issue on the behaviour of string literals in metavariable patterns is valid regardless

**Comment by aryx** [comment]
This is because of yaml:
This works: https://semgrep.dev/s/Z3dn
