### ISSUE TITLE
[Terraform] Can't match YAML documents inside Terraform strings with metavariable-pattern

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4582]
**Describe the bug**
I have a rule in which I'm trying to match YAML inside a Terraform string. Examples are in the next section.
I have tried many combinations of patterns, but it seems like it just isn't getting picked up.
I'm still able to match YAML documents in other languages, though.

**To Reproduce**
Case I want to match: https://semgrep.dev/s/GyGq
Full rule I'm trying to write with JSON examples that work: https://semgrep.dev/s/Ry6q
YAML working with metavariable-pattern in Python: https://semgrep.dev/s/AyE2

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by emjin** [comment]
Created a linear ticket for this https://linear.app/r2c/project/support-security-research-team-5beed2a5f2e7/PA

**Comment by IagoAbal** [comment]
The problem with https://semgrep.dev/s/GyGq is that `$STRING` is being bound to
```
schemaVersion:'1.0'description:DocumenttoholdregionalsettingsforSessionManagersessionType:Standard_Streaminputs:s3BucketName:'example's3KeyPrefix:''s3EncryptionEnabled:falsecloudWatchLogGroupName:''cloudWatchEncryptionEnabled:truecloudWatchStreamingEnabled:truekmsKeyId:''runAsEnabled:truerunAsDefaultUser:''idleSessionTimeout:'20'shellProfile:windows:''linux:''
```
So all whitespace is removed for some reason. That's probably why `metavariable-pattern` doesn't work.

**Comment by IagoAbal** [comment]
And this problem seems to come already from the HCL front-end.

**Comment by IagoAbal** [comment]
I believe we need to fix `Parse_hcl_tree_sitter.map_template_literal`.
