### ISSUE TITLE
Unable to catch a contract with its modifier

### ISSUE THREAD

**Issue by ahpaleus** [semgrep/semgrep#4587]
**Describe the bug**
It is unable to catch the whole contract with the specific modifier.

**To Reproduce**
https://semgrep.dev/s/7nk2

**Expected behavior**
Catch the whole:
```solidity
contract MyContract is Initializable {
    uint256 public x;

    function initialize(uint256 _x) public initializer {
        x = _x;
    }
}
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
semgrep.dev & official binary (0.80.0)

**Comment by aryx** [comment]
The problem is because ... inside a contract can't be parsed currently.
See https://github.com/JoranHonig/tree-sitter-solidity/pull/22/files which is the first step needed for this fix.
