### ISSUE TITLE
`r2c-internal-project-depends-on` gives no output when no lockfile is found

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#4591]
**Describe the bug**
Rules using `r2c-internal-project-depends-on` gives no output without a lockfile in the directory that's being scanned. 

**To Reproduce**
Run a semgrep rule that uses that key on in a directory that doesn't have a lockfile.

**Expected behavior**
I'd personally prefer if Semgrep pretends that the `r2c-internal-project-depends-on` key doesn't exist if it can't find a lockfile, and fires on the lines of code that were caught by the rule anyways. Another thing that could be done is have an error message saying that it could not find a lockfile. Preferably both.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Happens with Semgrep CLI

**Comment by aryx** [comment]
Is this fixed now @mmcqd ?

**Comment by mmcqd** [comment]
Right now the SCA rules mean "only fire on this pattern if the dependency is present", and we're conservative in that "no lockfile" means "the dependency is not present". I'll talk to Adam and Kurt to see how this would impact potential customers and whether they agree this would make things easier.
