### ISSUE TITLE
Semgrep playground fails to run from defined branch on page load

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#4599]
**Describe the bug**
When you visit https://semgrep.dev/s/0ykj?version=develop it does not use the 'version' parameter when querying the docker API https://semgrep.dev/api/run. It should first extract the version and run against develop.

**To Reproduce**
1. Visit https://semgrep.dev/s/0ykj?version=develop
2. See no finding was found 
3. Click 'run' see that the finding was found as the develop flag is now included in the api query

**Expected behavior**
On page load the api query should contain the query parameter as a property: 
```
filename:
highlights:
language:
pattern:
target:
yaml:
version: "$VALUE"
```
Current it contains the properties
```
filename:
highlights:
language:
pattern:
target:
yaml:
```

**Screenshots**
On page load
![Issue](https://user-images.githubusercontent.com/2419690/152075474-31f7a925-fcff-4cfa-aa28-b803888d3f35.png)

Clicking run:
![Correct](https://user-images.githubusercontent.com/2419690/152075531-2663914a-581d-4708-acf3-5da82423ce25.png)

**What is the priority of the bug to you?**

- [x] P2: regular bug that should get fixed

**Environment**
https://semgrep.dev/s/0ykj?version=develop

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-815/semgrep-playground-fails-to-run-from-defined-branch-on-page-load.

**Comment by adamberman** [comment]
Hi @LewisArdern! Thanks for reporting this! I've deployed a fix for this issue, so I'll close it. If you feel like this hasn't been fully addressed or if you see it pop up again, feel free to re-open and add more context. Again, thanks for reporting!
