### ISSUE TITLE
[Scala] Parsing error for `main` method example

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#4600]
**Describe the bug**
Parsing error
```json
{"code":3,"level":"warn","message":"Semgrep Core WARN - Syntax error in file target.scala:2\n\t`def` was unexpected","path":"target.scala","type":"Syntax error"}
```
for
```scala
@main
def run(): Unit =
  val message = "Hello world!"
  println(message)
```

**To Reproduce**
https://semgrep.dev/s/gXOZ

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-816/[scala]-parsing-error-for-main-method-example.

**Comment by mmcqd** [comment]
There are two issues here. First is that currently Semgrep can't just parse a function definition in Scala, it needs to be part of some `Object` or `Class`. This is the case in Java too. If being able to do that is important let me know. The other is that your code isn't actually valid Scala 2. The function body needs to be in brackets if it's a series of statements (see: https://scastie.scala-lang.org/38KyRuPNRmufspQaIWKHEQ). With this in mind, you can rewrite your example like so to make it work: https://semgrep.dev/s/1zYv

**Comment by inkz** [comment]
@mmcqd thank you :pray: 
my bad, I guess I bumped into some "Hello world"s from Scala 3
