### ISSUE TITLE
Include extra.lines output in --vim output

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#4626]
**Is your feature request related to a problem? Please describe.**
When you run --emacs it includes the extra.lines output, part of our automated scanning we leverage --vim in our pipeline, it is missing the extra.lines output 

It would be great if they could be aligned, where the --vim flag also can contain the code snippet which is vulnerable. 

semgrep -f value.yaml --emacs:
```
test.java:285:31:warning(pwd-pbkdf2-weak-iter):            PBEKeySpec spec = new PBEKeySpec( password, salt, 100, 256 );:Detected usage of pbkdf2 100.
Refer to blah
```
semgrep -f value.yaml --vim:
```
test.java:285:31:W:pwd-pbkdf2-weak-iter:Detected usage of pbkdf2 100.
Refer to blah
```

**Describe the solution you'd like**

Include the line of code in --vim e.g. 
```
test.java:285:31:W:pwd-pbkdf2-weak-iter:Detected usage of pbkdf2 100.
PBEKeySpec spec = new PBEKeySpec( password, salt, 100, 256 );
Refer to blah
```
**Use case**
This will improve our automated pipeline with the --vim format i think its useful to include the vulnerable line in the output.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-832/include-extralines-output-in-vim-output.

**Comment by brendongo** [comment]
I think this format might be expected by https://github.com/returntocorp/semgrep.vim so that might need to be changed if we ever change this.

@LewisArdern is there a reason you are using `--vim` in CI instead of `--json`?

**Comment by LewisArdern** [comment]
We have a unique case where its an out-of-band scan when an engineer needs to review something ad-hoc, (we save the output of semgrep to a txt file) which they look at (we do not have the luxury to have JSON parsing in this case). 

I have said to use --emacs instead for now as it probably wont break our workflow, but I noticed that there were discrepancies with --vim and --emacs, and wanted to align them it will help our engineers know what the problem is. 

We're basically wanting to use --vim as a way to display data in an easy to consume format, the --json output has too much noise for someone to look at and since we cant parse it in this old process, we want the extra.lines output.
