### ISSUE TITLE
`semgrep -h` does not work

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#4628]
**Describe the bug**

```
❯ semgrep -h
Usage: semgrep -h [OPTIONS] [TARGET]...
Try 'semgrep -h --help' for help.

Error: No such option: -h
```

**To Reproduce**

`$ semgrep -h`

**Expected behavior**

`-h` should have the same output as `--help`

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

Latest develop version

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-835/semgrep-h-does-not-work.

**Comment by 0xDC0DE** [comment]
-h flag has been added
https://github.com/returntocorp/semgrep/pull/4685
