### ISSUE TITLE
Agent gives ambiguous warning on file syntax error

### ISSUE THREAD

**Issue by holdenmcg** [semgrep/semgrep#4630]
**Is your feature request related to a problem? Please describe.**
Running the agent on a file with a syntax error results in an ambiguous/slightly confusing warning: " [WARN] Semgrep Core — Syntax erro ". someone might think this is an issue with their CLI flags/config/etc. , whereas the syntax error is really in a file, and Semgrep is working perfectly fine.

**Describe the solution you'd like**
in this case, perhaps a more specific error message, such as: "[WARN] Semgrep Core - syntax error in [file/line]: a syntax error was found in a scanned file. Some parts of the file might not have been scanned."

**Describe alternatives you've considered**
-

**Use case**
slightly less confusion . :) 

**Additional context**
<img width="345" alt="image" src="https://user-images.githubusercontent.com/50721067/152856434-ae61e27d-5887-41e9-a83f-0682bc0f462f.png">

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-837/agent-gives-ambiguous-warning-on-file-syntax-error.

**Comment by aryx** [comment]
@underyx is this still an issue with semgrep ci? can we close the issue?

**Comment by brendongo** [comment]
Yep this was fixed by https://github.com/returntocorp/semgrep/pull/5013
