### ISSUE TITLE
Semgrep missing highlight in text output mode

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4637]
**Describe the bug**
Semgrep doesn't highlight the matched range when printing textual output on the CLI

**To Reproduce**
Run semgrep on the CLI with some findings

**Expected behavior**

Semgrep used to highlight the matched range with a different color/bold, as described in https://github.com/returntocorp/semgrep/issues/4400
![image](https://user-images.githubusercontent.com/409041/153036493-4ac78c5a-4405-481e-a71b-40286627914d.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
v 0.81.0

**What will fixing this bug enable for you?**
Causes confusion when identical lines are printed that have different matched ranges but no visual differentiators

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-839/semgrep-missing-highlight-in-text-output-mode.
