### ISSUE TITLE
Semgrep missing explanation when skipping large files

### ISSUE THREAD

**Issue by rc-mattschwager** [semgrep/semgrep#4638]
**Describe the bug**

A large HTML file was being skipped by Semgrep for unknown reasons.

**To Reproduce**

```
$ du -h /tmp/index.html 
3.0M	/tmp/index.html
```

```
$ semgrep -l generic -e '<script ...>' /tmp/index.html
ran 1 rules on 0 files: 0 findings
```

```
$ semgrep --verbose -l generic -e '<script ...>' /tmp/index.html
No .semgrepignore found. Using default .semgrepignore rules. See the docs for the list of default ignores: https://semgrep.dev/docs/cli-usage/#ignoring-files

============================[ summary ]============================
Total time: 0.0310 Config time: 0.0015 Core time: 0.0269 Ignores time: 0.0000

Semgrep-core time:
Total CPU time: 0.0000  File parse time: 0.0000  Rule parse time: 0.0000  Match time: 0.0000
Slowest 5/0 files
Slowest 5 rules to run (excluding parse time)
-:                                                                      run time 0.0000  match time 0.0000

Errors:   0 files with errors

ran 1 rules on 0 files: 0 findings
Not sending pseudonymous metrics since metrics are configured to OFF and server usage is False
```

Eventually I suspected the file was being skipped because of it's size. Setting `--max-target-bytes 0` fixed the issue.

**Expected behavior**

When a file is being filtered for size reasons (or any other reasons really) it would be helpful if `--verbose` told you why it was skipped. Bonus points for pointing you to the flag to avoid skipping it 👍 

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

```
$ semgrep --version
0.81.0
```

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-840/semgrep-missing-explanation-when-skipping-large-files.

**Comment by underyx** [comment]
Heya Matt! Perfect timing, we just merged something for this less than 24 hours ago! Could you have a look at whether this is sufficient for you?

https://github.com/returntocorp/semgrep/commit/4a066462da6fea6c1255c41089d8a1d8684fcd31#diff-9db04ed6501345761c7a7fff5a0078f111eeb8d141b73869ed5d01e0af1f3b16R26-R29

**Comment by rc-mattschwager** [comment]
Oh wow, that's perfect! I think `1 files larger than 1.0 MB` would've keyed me into my problem 👍
