### ISSUE TITLE
Support new Java 11+ language specs features.

### ISSUE THREAD

**Issue by tilperion2** [semgrep/semgrep#4644]
**Is your feature request related to a problem? Please describe.**
SemGrep fails to run Java rules for code using new Java 11+ features. As SemGrepo fails to scan such classes, some issues in them may be missed

Features not supported right now:

- Text blocks - “”” (three double-quote marks) - since Java 15+
- Java records - since Java 14+
- Sealed classes/interfaces - since Java  15+
- Pattern Matching for instanceof - since Java 16+
- Pattern Matching for Switch - since java 17+
- Others?

**Describe the solution you'd like**
Update Java language support to handle novice features.

**Describe alternatives you've considered**

**Use case**
What will this feature enable for you? 
Clear and reliable scan results for Java code bases.

**Additional context**
Relates to [this issue](https://github.com/returntocorp/semgrep/issues/3787)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-848/support-new-java-11-language-specs-features.

**Comment by ievans** [comment]
@tilperion2 thanks for the issue. Can you share the relative priority for you / your team?

**Comment by tilperion2** [comment]
We have more and more code updated to newer Java, so our automation scan jobs seeing more and more errors/warnings. So we will happy to get updates sooner, if possible. 

I think generally it will become more and more critical for all semGrep teams, as soon as they will start update to new long term support Java release. 

Also I placed features in bullet list in approximate frequency of theirs usage in the code. So you may do them one by one, as it may work better for you. 
Thanks

**Comment by aryx** [comment]
I think @emjin added support for Record classes at least (I can't find back the closed issue though).

**Comment by emjin** [comment]
I added switch expressions: https://github.com/returntocorp/semgrep/pull/2975
