### ISSUE TITLE
Scala String Interpolator Rules Do Not Match Against 

### ISSUE THREAD

**Issue by justinmoore** [semgrep/semgrep#4655]
**Describe the bug**
Scala 

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
https://semgrep.dev/s/PYpe

**Expected behavior**
The rule should not match against `s""` or `sql""`, only `asdasdawkdpokasd""`. 

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you? Write a rule to detect unsafe String interpolation in Slick SQL queries (e.g. `sql"#$unsafe"`) as well as other String interpolation related vulnerabilities.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-855/scala-string-interpolator-rules-do-not-match-against.
