### ISSUE TITLE
Typed Metavariable Support for C#

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#4657]
**Is your feature request related to a problem? Please describe.**
No, this is a request for an enhancement to C# language support similar to existing functionality for Java and Go.

**Describe the solution you'd like**
Typed metavariables for C#.  Similar to Java's `(String $Y)` syntax: https://semgrep.dev/docs/writing-rules/pattern-syntax/#typed-metavariables

**Describe alternatives you've considered**
You can (sort of) hack around this by enforcing type definitions in your rules via:

```
Type $VAR = new Type(...);
...
$VAR.$PROPERTY = ...; //this will be a Type so you can make some assumptions about $PROPERTY
```

However, modern C# makes heavy use of the `var` keyword and so some AST type awareness is necessary to make rules that rely on strict typing work correctly.

**Use case**
The "killer use case" for this is using `join` and `taint` on .NET Core MVC projects to leverage model types to track dangerous writes via API controller sources such as:
```
[$HTTPATTRIBUTE]
public ActionResult $METHOD($ARG)
```

combined with model writes:
```
(Type $MODEL).$PROPERTY = $ARG
```

and then subsequent potentially hazardous behavior such as

```
Path.Combine("/foo/bar",(Type $MODEL).$PROPERTY)
```

**Additional context**

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-858/typed-metavariable-support-for-c.
