### ISSUE TITLE
Unexpected new-line(\n) character in json output

### ISSUE THREAD

**Issue by faceyacc** [semgrep/semgrep#4661]
**Describe the bug**
A user running semgrep-core is receiving an unexpected new line character before json output. 

**Expected behavior**
The user should be able to run semgrep-core on v0.82.0 without unexpected new line characters

**Screenshots**
<img width="934" alt="Screen Shot 2022-02-11 at 9 11 30 AM" src="https://user-images.githubusercontent.com/42871121/153637034-013d04a3-5269-40dd-ac60-c4de1ae841d9.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
User is running semgrep-core on a local file. 

**Use case**
To run semgrep-core without unexpected new-line characters.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-859/unexpected-new-line\n-character-in-json-output.

**Comment by brendongo** [comment]
@faceyacc can you let them know semgrep-core is used internally by semgrep and has a non stable API (this new line is desired behavior for us)

**Comment by brendongo** [comment]
Closing as wont-fix
