### ISSUE TITLE
Join mode does not respect --exclude options

### ISSUE THREAD

**Issue by jtraglia** [semgrep/semgrep#4663]
**Describe the bug**
When running a `mode: join` rule, it shows findings in excluded directories.

**Expected behavior**
It should hide findings in excluded directories.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Semgrep 0.82.0 on macOS (installed via homebrew).

**Use case**
Join mode is really awesome, but I'm working on a codebase that has a lot of test directories. All of the findings in test directories are really annoying.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-860/join-mode-does-not-respect-exclude-options.
