### ISSUE TITLE
Changing policy on Semgrep app rule board does not appear to update GitHub PR comments

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#4666]
**Describe the bug**
Changing policy on Semgrep app rule board does not appear to update GitHub PR comments to reflect that policy, even though the workflow logs seem to.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
1. Make a PR for a Github repo, and let Semgrep run (with inline PR comments enabled).
2. Add a rule to the app rule board, or modify the policy (change from blocker to audit or vice versa).
3. Rerun the Workflow to get updated results on your PR. The new results appear to show in the Workflow logs, but the PR comments do not appear to properly update.  

**Expected behavior**
Inline PR comments will show the updated policy. In the version I tried, I moved a rule from Audit to Blocker, but the PR comments still showed it was not required to be fixed before submitting.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Github CI + Semgrep App 

**Use case**
What will fixing this bug enable for you?
Knowledge that all open PRs, if the workflow is rerun, will contain the most up-to-date policy.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-863/changing-policy-on-semgrep-app-rule-board-does-not-appear-to-update.

**Comment by nbrahms** [comment]
Thanks for the report @efortuna !

cc @chmccreery -- I think this is because we have logic that prevents duplicate comments for the same findings.

@efortuna I think this is actually our (currently) intended behavior, so I'm going to move this to a feature request. @adamboros tagging you for UX input here.

**Comment by chmccreery** [comment]
Yeah, our PR comments only reflect the config at the time they were left - they do not get updated to match config changes since they were left. I've created a ticket for this for findings team. Thanks @efortuna!

**Comment by aryx** [comment]
Also this should be filed in Linear I think.
