### ISSUE TITLE
Ability to match within multiline python strings

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4669]
**Is your feature request related to a problem? Please describe.**
User wants to match subtext within multiline python string matches

e.g.:
https://semgrep.dev/s/WjpZ

**Describe the solution you'd like**
Any way to match within multiline strings

**Use case**
User is trying to find inefficiencies in Selenium tests

**Additional context**
It appears that https://semgrep.dev/s/0Gyq returns an incorrect match, as multiline Python strings are semantically equivalent to elided single-line strings.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-867/ability-to-match-within-multiline-python-strings.
