### ISSUE TITLE
Invalid SARIF export with rules that have owasp/cwe metadata as array

### ISSUE THREAD

**Issue by janlaan** [semgrep/semgrep#4673]
**Describe the bug**
With certain Semgrep community rules, using the SARIF export option results in invalid SARIF. In the example below, it outputs a SARIF rule with nested tags. See the tags section near the end. [According to the SARIF spec,](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317451) tags can only contain strings, not arrays. 
<details>
<summary>Click to expand SARIF export example</summary>

```
{
    "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
    "runs": [
        {
            "invocations": [
                {
                    "executionSuccessful": true,
                    "toolExecutionNotifications": []
                }
            ],
            "results": [
                {
                    "locations": [
                        {
                            "physicalLocation": {
                                "artifactLocation": {
                                    "uri": "xmldocument-unsafe-parser-override.cs",
                                    "uriBaseId": "%SRCROOT%"
                                },
                                "region": {
                                    "endColumn": 27,
                                    "endLine": 8,
                                    "startColumn": 9,
                                    "startLine": 8
                                }
                            }
                        }
                    ],
                    "message": {
                        "text": "XmlReaderSettings found with DtdProcessing.Parse on an XmlReader handling a string argument from a public method.  Enabling Document Type Definition (DTD) parsing may cause XML External Entity (XXE) injection if supplied with user-controllable data."
                    },
                    "ruleId": "xmldocument-unsafe-parser-override"
                }
            ],
            "tool": {
                "driver": {
                    "name": "semgrep",
                    "rules": [
                        {
                            "defaultConfiguration": {
                                "level": "warning"
                            },
                            "fullDescription": {
                                "text": "XmlReaderSettings found with DtdProcessing.Parse on an XmlReader handling a string argument from a public method.  Enabling Document Type Definition (DTD) parsing may cause XML External Entity (XXE) injection if supplied with user-controllable data."
                            },
                            "id": "xmldocument-unsafe-parser-override",
                            "name": "xmldocument-unsafe-parser-override",
                            "properties": {
                                "precision": "very-high",
                                "tags": [
                                    [
                                        "CWE-611: Improper Restriction of XML External Entity Reference"
                                    ],
                                    "OWASP-['A04:2017 - XML External Entities (XXE)', 'A05:2021 - Security Misconfiguration']"
                                ]
                            },
                            "shortDescription": {
                                "text": "XmlReaderSettings found with DtdProcessing.Parse on an XmlReader handling a string argument from a public method.  Enabling Document Type Definition (DTD) parsing may cause XML External Entity (XXE) injection if supplied with user-controllable data."
                            }
                        }
                    ],
                    "semanticVersion": "0.77.0"
                }
            }
        }
    ],
    "version": "2.1.0"
}
```

</details>

Looking at [the source code of _rule_to_sarif_tags in the SARIF formatter](https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/formatter/sarif.py#L85), it incorrectly assumes that the CWE or owasp sections are strings, and can't be arrays.

**To Reproduce**
Run Semgrep for example using [this rule about xxe](https://github.com/returntocorp/semgrep-rules/blob/develop/csharp/lang/security/xxe/xmltextreader-unsafe-defaults.yaml) which defines both the `cwe` and the `owasp` metadata as an array. (Can't find it in the registry) This is an example, there's 6 rules introduced in the past week which trigger this bug
`semgrep --config csharp/lang/security/xxe/xmltextreader-unsafe-defaults --sarif`

**Expected behavior**
I expect this to produce valid SARIF, so that my SARIF parser can input it. 
I think the correct format for tags in this example is something like:
```
"tags": [
   "CWE-611: Improper Restriction of XML External Entity Reference",
   "OWASP-A04:2017 - XML External Entities (XXE)",
   "OWASP-A05:2021 - Security Misconfiguration"
]
```
**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
We're using semgrep via `pip install semgrep` inside a Docker image.

**Use case**
Fixing this bug will allow us to use all Semgrep community rules. At the moment we are pinning the latest version of the `semgrep-rules` repo that does not trigger this bug (from 9 february)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-871/invalid-sarif-export-with-rules-that-have-owaspcwe-metadata-as-array.

**Comment by janlaan** [comment]
FYI: This also blocks processing results by Github, or using the Visual Studio code SARIF plugin by Microsoft.

Github gives an error when trying to parse this SARIF:
```
Unable to upload "results.sarif" as it is not valid SARIF:
- instance.runs[0].tool.driver.rules[0].properties.tags[0] is not of a type(s) string
```

The Visual Studio code plugin just silently fails and shows 0 results.
