### ISSUE TITLE
Semgrep prints a non-zero findings count but shows no results

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4674]
**Describe the bug**
`semgrep --config auto .` on some repos will show a findings count but no findings.

**Expected behavior**
Findings count should match number of findings

**Screenshots**
```
Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate recommended rules based on
your languages and frameworks.
Fetching rules from https://semgrep.dev/registry ...
Running 191 rules...
100%|██████████████████████████████████████████████████|6/6 files

skipped: all .gitignored files, 2 files matching .semgrepignore patterns
for a detailed list of skipped files, run semgrep with the --verbose flag

ran 191 rules on 4 files: 5 findings
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
CLI v 0.82.0

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-872/semgrep-prints-a-non-zero-findings-count-but-shows-no-results.

**Comment by nbrahms** [comment]
cc. @minusworld @underyx This is most likely erroneously showing the count of inventory findings (which should be hidden in output).

In addition, it seems like we should display a message suggesting that the user re-run after some interval?
