### ISSUE TITLE
warnings rendered on STDOUT break JSON formatting for --gitlab-json

### ISSUE THREAD

**Issue by bdols** [semgrep/semgrep#4676]
**Describe the bug**
warnings about long semgrep runs are included in the output captured in `semgrep-agent --gitlab-json > gl-semgrep-sast-report.json`. this breaks gitlab parsing of the report.json

**To Reproduce**
using the following job spec in gitlab-ci.yml:
```semgrep audit:
  image: returntocorp/semgrep-agent:v1
  script: semgrep-agent --gitlab-json > gl-semgrep-sast-report.json || true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "develop"'
  variables:
    SECURE_LOG_LEVEL: "debug"
    SEMGREP_AUDIT_ON: push
    SEMGREP_GITLAB_JSON: "1"
    SEMGREP_RULES:
      p/security-audit
      p/secrets
  artifacts:
    reports:
      sast: gl-semgrep-sast-report.json
```
the scan took 388 seconds and displays the following:
```=== Semgrep may be taking longer than expected to run (took 388.56 s).
| These files are taking the most time. Consider adding them to .semgrepignore or
| ignoring them in your Semgrep.dev policy.
[........]
| These rules are taking the most time. Consider removing them from your config.
```

**Expected behavior**
the results are scanned by gitlab

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ x ] P2: regular bug that should get fixed

**Environment**
self-hosted gitlab CI

**Use case**
remove the need to debug the job for large repos

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-873/warnings-rendered-on-stdout-break-json-formatting-for-gitlab-json.

**Comment by ievans** [comment]
cc @emjin

**Comment by underyx** [comment]
Fixed here: https://github.com/returntocorp/semgrep-action/pull/516

**Comment by emjin** [comment]
The fix should go out in a release next week!
