### ISSUE TITLE
JSX pattern for `<div>...</div>` not matching all instances of a div

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4678]
**Describe the bug**
It looks like a JSX pattern for `<div>...</div>` doesn't match all instances of `div`s found in a JSX block.

**To Reproduce**
See this link, here: https://semgrep.dev/s/WjWz

**Expected behavior**
I think that this would match all instances of the divs. But, if my reasoning is wrong for some reason, please let me know.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-878/jsx-pattern-for-divdiv-not-matching-all-instances-of-a-div.
