### ISSUE TITLE
Ability to match JSX tags with zero props

### ISSUE THREAD

**Issue by azuline** [semgrep/semgrep#4679]
**Is your feature request related to a problem? Please describe.**

I am not able to match JSX tags with zero props.

Example: https://semgrep.dev/s/0G8J

**Describe the solution you'd like**

**Describe alternatives you've considered**
This is something that plain grep works fine for. But plain grep isn't as integrated with CI as Semgrep.

**Use case**
I am semgrepping components and their prop APIs to collect info and migrate legacy components.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-879/ability-to-match-jsx-tags-with-zero-props.

**Comment by mjambon** [comment]
I'm not sure if this is a bug per se. Writing the rule may require a `pattern` and a `pattern-not` to exclude elements that have at least one attribute like `<div $A=$VAL>...</div>`.

I think we need to fix bug #4678 first.

**Comment by azuline** [comment]
That's an interesting method, I wouldn't have thought of it. Documentation would be enough to resolve this ticket.

**Comment by ievans** [comment]
@azuline where would you hope to find said documentation? I think https://semgrep.dev/docs/writing-rules/rule-syntax/#pattern-not is the closest we have right now

**Comment by azuline** [comment]
My primary lack is documentation on the semantics of the JSX matching rules. I was unaware that `<div>` matches arbitrary props, and also unaware that I could match at least one attribute with `<div $A=$VAL>` (intuitively to me, this matches a tag with one attribute). I had figured out the former in Slack, but not the latter. Knowing both, I would then be able to leverage the rules syntax docs to query for my desired pattern.

**Comment by aryx** [comment]
This should work now with the new option xml_attrs_implicit_ellipsis:
https://semgrep.dev/s/Wjyj?version=0.84.0

**Comment by aryx** [comment]
I think if we fix this: https://github.com/returntocorp/semgrep/issues/2812 then they will be less need for documentation
because the behavior of ... would be more consistent with how it's used in other parts of semgrep.
