### ISSUE TITLE
Very high core time (Windows)

### ISSUE THREAD

**Issue by capc0** [semgrep/semgrep#4683]
I am trying to troubleshoot why the execution on my codebase is so slow.

Im running `returntocorp/semgrep` docker image on windows.

```
============================[ summary ]============================
Total time: 251.3368s Config time: 2.9130s Core time: 248.4213s

Semgrep-core time:
Total CPU time: 8.5493s  File parse time: 4.5128s  Rule parse time: 0.3529s  Match time: 3.0912s
Slowest 5/192 files
...abc.ts ( 58KB): 0.014s (0.204s to parse)
...qwe.ts ( 51KB): 0.013s (0.169s to parse)
...123.ts   ( 30KB): 1.082s (0.156s to parse)
...dummy.ts ( 37KB): 0.009s (0.146s to parse)
...other.ts ( 30KB): 0.009s (0.122s to parse)
Slowest 5 rules to match
...ort.js-node.using-http-server.using-http-server:         0.000s
...transport.js-node.telnet-request.telnet-request:         0.000s
...st-http-client-support.rest-http-client-support:         0.002s
...ure-transport.js-node.http-request.http-request:         0.000s
...ecure-transport.js-node.ftp-request.ftp-request:         0.000s
```

the reported times are not really adding up to the total time of 250seconds.

Any tips?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-880/very-high-core-time.

**Comment by ievans** [comment]
@capc0 what version of Semgrep are you running, and what's the priority of the issue to you?

**Comment by capc0** [comment]
Im using the latest docker image. `--version` prints 0.82.0

We are currently in the process of integrating semgrep. The timing above is only from a small subset of the actual source code, since the entire `/src` folder seems to never finish (manually aborted after a few hours).

Also tested under WSL with Ubuntu, same performance.

**Comment by ievans** [comment]
Thanks! @emjin can you take a look?

**Comment by capc0** [comment]
As a heads up, using the following command:

`docker run --rm -v /path/to/src:/src returntocorp/semgrep --time --config=p/expressjs /src`

Also tested with other (smaller) rule sets or the `config=auto` option.

**Comment by emjin** [comment]
Thank you for the details! Can you run the command you ran to get timing output with `--json` and send me the output json? That will have more information that will help

**Comment by capc0** [comment]
```json
{
    "errors": [],
    "results": [],
    "time": {
        "profiling_times": {
            "config_time": 3.1793746948242188,
            "core_time": 247.18764209747314,
            "ignores_time": 0.00022745132446289062,
            "total_time": 250.36935710906982
        },
        "rules_parse_time": 0.35199403762817383,
        "total_bytes": 1053949
    }
}
```

I stripped out rules and targets. If you require the entire json file, please let me know some form of contact info so I can send it.

**Comment by emjin** [comment]
You can slack me on the community slack (@emma) or email emma@returntocorp.com

**Comment by capc0** [comment]
Additional info: 

When I `ctrl + c` out of the process while its running the stack trace is always the following.

```
^C
Aborted!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in main
    raise Abort() from None
click.exceptions.Abort

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1096, in main
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/semgrep/__main__.py", line 30, in main
    metric_manager.send()
  File "/usr/local/lib/python3.9/site-packages/semgrep/metric_manager.py", line 247, in send
    r = requests.post(
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
```

Looks like something network related (metrics?) might hang the process?

**Comment by emjin** [comment]
Oh, that's very helpful! Thanks! I was just feeling confused because the time output looks perfectly normal. @brendongo do you have any thoughts for why this might be taking a while?

**Comment by ievans** [comment]
There's a 2sec timeout on that call to `requests.post`, so I don't see why or how it could be hanging.

**Comment by capc0** [comment]
Im not sure if thats the underlying issue or a false hint.

If there is any other info I can provide that helps out, please let me know.

**Comment by capc0** [comment]
With `--verbose` it always gets stuck at this log output

```
No .semgrepignore found. Using default .semgrepignore rules. See the docs for the list of default ignores: https://semgrep.dev/docs/cli-usage/#ignoring-files
Unable to ignore files ignored by git (/api-src is not a git directory or git is not installed). Running on all files instead...
```

Then it feels like nothing happens for a few minutes, and afterwards the rules are being checked within 10 secs.

**Comment by emjin** [comment]
To clarify, you're adding `--verbose` to the command that produced this? 

```
============================[ summary ]============================
Total time: 251.3368s Config time: 2.9130s Core time: 248.4213s

Semgrep-core time:
Total CPU time: 8.5493s  File parse time: 4.5128s  Rule parse time: 0.3529s  Match time: 3.0912s
Slowest 5/192 files
```

**Comment by emjin** [comment]
Also, how many total files are in the directory you're scanning? (Not the 192 files semgrep runs on, but all the files in the directory and its subdirectories)

**Comment by capc0** [comment]
Yes, added `--verbose` to that command.

There are 75 subdirectories and 192 files in total. They all are `*.ts` files.

**Comment by emjin** [comment]
hm, can you run the same command but add `-d` after, and time that? I'm trying to isolate the source of the slowness

**Comment by capc0** [comment]
`-d` is not a recognized option, you mean `--debug`?

**Comment by emjin** [comment]
Hm, this is `--dump-command-for-core`, which should be available in 0.82.0+

**Comment by capc0** [comment]
maybe it is just not documented under `--help`.

the output is `/usr/local/bin/semgrep-core -json -rules /home/semgrep/.semgrep/semgrep_rules.yaml -j 12 -targets /home/semgrep/.semgrep/semgrep_targets.txt -timeout 30 -timeout_threshold 0 -max_memory 0 -json_time -fast`

timing info is not printed for some reason (`--time` was specified tho). But it was around 4-5 minutes

**Comment by cofonseca** [comment]
I'm also experiencing this issue. Scanning a small C# microservice took 11 minutes with only 33 rules. I experience this when running in Docker as well as using WSL2 and Python/PIP, using Semgrep 0.83.0

```
python3 -m semgrep --config="p/csharp" --time
Fetching rules from https://semgrep.dev/registry ...
Running 33 rules...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|262/262 files

============================[ summary ]============================
Total time: 630.6169s Config time: 3.2287s Core time: 627.3647s

Semgrep-core time:
Total CPU time: 9.0949s  File parse time: 6.2053s  Rule parse time: 0.1200s  Match time: 0.5229s
Slowest 5/262 files
...rvice.Tests/IntegrationTests/IntegrationTest.cs (144KB): 0.633s (0.516s to parse)
...ymentService/Components/PaymentDataComponent.cs ( 73KB): 0.468s (0.381s to parse)
...ce.Tests/UnitTests/PaymentDataComponentTests.cs ( 42KB): 0.300s (0.254s to parse)
...ymentService/Endpoint/PaymentServiceEndpoint.cs ( 24KB): 0.227s (0.176s to parse)
...e/PaymentProviders/WellsFargoPaymentProvider.cs ( 14KB): 0.184s (0.120s to parse)
Slowest 5 rules to match
csharp.razor.security.html-raw-json.html-raw-json:          0.000s
...r-unsafe-defaults.xmltextreader-unsafe-defaults:         0.000s
...erride.xmlreadersettings-unsafe-parser-override:         0.000s
...ser-override.xmldocument-unsafe-parser-override:         0.000s
csharp.lang.security.ssrf.web-request.ssrf:                 0.000s

Analyzed: 262 csharp files (718KB in 8.975 seconds)
Errors:   0 files with errors


skipped: all .gitignored files, 13 files matching .semgrepignore patterns
for a detailed list of skipped files, run semgrep with the --verbose flag

ran 33 rules on 262 files: 0 findings
```

Apologies in advance if this is somehow user-error - I'm new to Semgrep but would love to start using it more. Please let me know if there's any additional info I can provide to help, or if there's anything I can do to fix this.

**Comment by emjin** [comment]
@cofonseca Thank you for the output! Can you run `time python3 -m semgrep --config="p/csharp" --time -d`?

**Comment by cofonseca** [comment]
@emjin Absolutely. Here's the output:

```
$ time python3 -m semgrep --config="p/csharp" --time -d

Fetching rules from https://semgrep.dev/registry ...
Running 33 rules...
/home/cfonseca/.local/lib/python3.8/site-packages/semgrep/bin/semgrep-core -json -rules /home/cfonseca/.semgrep/semgrep_rules.yaml -j 8 -targets /home/cfonseca/.semgrep/semgrep_targets.txt -timeout 30 -timeout_threshold 0 -max_memory 0 -json_time -fast

real    2m47.060s
user    0m8.884s
sys     0m30.406s
```

**Comment by emjin** [comment]
Thank you! That looks right. Now can you run the command outputted, with `time` in front? If this takes ~400s, then the core engine is slow on one of the rules/files you're running. Otherwise, it might be something about how we process the output.

```
time /home/cfonseca/.local/lib/python3.8/site-packages/semgrep/bin/semgrep-core -json -rules /home/cfonseca/.semgrep/semgrep_rules.yaml -j 8 -targets /home/cfonseca/.semgrep/semgrep_targets.txt -timeout 30 -timeout_threshold 0 -max_memory 0 -json_time -fast
```

**Comment by cofonseca** [comment]
@emjin That last command completed almost instantly, and successfully returned my scan results in json format.

```
real    0m3.029s
user    0m3.189s
sys     0m1.382s
```

**Comment by emjin** [comment]
I just realized you were also running on a Windows machine. Are you able to try running this on a Linux or Mac computer? Unfortunately, we currently don't support Windows and cannot guarantee that we run successfully or quickly. Something about how WSL interacts with semgrep might be causing this slowness for you and @capc0. Comment on https://github.com/returntocorp/semgrep/issues/1330 if you're interested in Windows support; it's definitely something we're tracking the need for.

If you reproduce this slowness on a Linux or a Mac, please let us know here and we can try to debug it!

**Comment by cofonseca** [comment]
Correct - I'm running in a WSL2 Ubuntu environment on Windows 10. 

Is Docker an acceptable way to run semgrep on Windows, or is that also unsupported? I assume not, since Docker on Windows uses WSL2. I experience the same behavior when running semgrep using the official container:
```
docker run --rm -v "${PWD}:/src" returntocorp/semgrep --config="p/owasp-top-ten" --time

METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Fetching rules from https://semgrep.dev/registry ...
Running 480 rules...

============================[ summary ]============================
Total time: 452.4670s Config time: 15.5407s Core time: 436.8765s

Semgrep-core time:
Total CPU time: 15.5224s  File parse time: 18.2536s  Rule parse time: 5.1939s  Match time: 0.3145s
Slowest 5/341 files
...rvice.Tests/IntegrationTests/IntegrationTest.cs (144KB): 0.285s (0.236s to parse)
...ymentService/Components/PaymentDataComponent.cs ( 73KB): 0.171s (0.147s to parse)
...ce.Tests/UnitTests/PaymentDataComponentTests.cs ( 42KB): 0.145s (0.128s to parse)
...grationTests/PaymentProviderIntegrationTests.cs (  5KB): 0.009s (0.120s to parse)
...nServiceProviders/TokenEx/TokenExRestService.cs ( 10KB): 0.011s (0.117s to parse)
Slowest 5 rules to match
...down-insecure-html.react-markdown-insecure-html:         0.000s
...y.react-insecure-request.react-insecure-request:         0.000s
...unsanitized-property.react-unsanitized-property:         0.000s
...act-unsanitized-method.react-unsanitized-method:         0.000s
...nts-injection.react-styled-components-injection:         0.000s

Analyzed: 1 bash files (  2KB in 0.043 seconds)
          262 csharp files (718KB in 6.478 seconds)
          74 generic files ( 60KB in 3.517 seconds)
          4 json files ( 26KB in 0.290 seconds)
Errors:   0 files with errors


skipped: all .gitignored files, 13 files matching .semgrepignore patterns
for a detailed list of skipped files, run semgrep with the --verbose flag

ran 480 rules on 341 files: 0 findings
```

I've also just tested on an Ubuntu machine and cannot reproduce the issue - the same command against the same microservice code completes in 15 seconds or less. I do agree that this seems to be Windows-specific.

**Comment by capc0** [comment]
using `returntocorp/semgrep:latest` the isse seems to be resolved!

can you confirm @cofonseca ?

---

edit: running rules via ubuntu wsl in docker is running fast now. running via docker in windows context is still slow.

**Comment by aryx** [comment]
ok closing @emjin
