### ISSUE TITLE
[Java] can't match a method without specifying the body in the pattern

### ISSUE THREAD

**Issue by evilpan** [semgrep/semgrep#4690]
https://semgrep.dev/s/xXPP

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-882/semgrepdev-bug-report.

**Comment by aryx** [comment]
H5PageImpl(Activity $A1, Bundle $A2, H5ViewHolder $A3) is not a valid pattern @evilpan 
Semgrep usually accepts full construct, so you might want to try

https://semgrep.dev/s/e5JE
