### ISSUE TITLE
Semgrep throws an error with a missing separator

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#4693]
**Describe the bug**

```
{
      "code": 2,
      "level": "error",
      "message": "Error while running rules: Separator is not found, and chunk exceed the limit",
      "type": "SemgrepError"
}
```

**To Reproduce**
Reporting on behalf of a community user: https://semgrep.dev: https://r2c-community.slack.com/archives/C0242656NQ2/p1645089315876449

**Expected behavior**
Semgrep should produce an understandable error message to the user

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-886/semgrep-throws-an-error-with-a-missing-separator.

**Comment by agrawalsmart7** [comment]
Anyupdates on this? I am facing the same error.

**Comment by emjin** [comment]
We're currently trying to reproduce this error. If you could provide a reproduction on code you can share with us (an open source repo, your own code you're comfortable sending directly) that would be a big help!

**Comment by aryx** [comment]
@emjin  someone gave me the last.log showing the problem but I didn't yet have the time to investigate

**Comment by aryx** [comment]
the error string is not in our repo, so it’s probably a python builtin error

[yoann (r2c)](https://app.slack.com/team/UL1MB92F2)  [7 days ago](https://r2c-community.slack.com/archives/C0242656NQ2/p1646651745456959?thread_ts=1646632804.900049&cid=C0242656NQ2)

https://stackoverflow.com/questions/55457370/how-to-avoid-valueerror-separator-is-not-found-and-chunk-exceed-the-limit

**Comment by aryx** [comment]
I've looked at the log reported by the user, but I don't see anything from semgrep-core in it. The problem is that
semgrep-python does not log and show stderr as soon as it arrives.

**Comment by brendongo** [comment]
User on slack confirmed that above commit fixed their issue.
