### ISSUE TITLE
And a --apply flag that lets you easily apply for a job at r2c

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#4708]
**Is your feature request related to a problem? Please describe.**
The problem is that there are awesome people out there who don't yet work at r2c.

**Describe the solution you'd like**
A simple implementation might just hit the Lever API and display our [currently live](https://jobs.lever.co/returntocorp/) list of jobs and a link to them, e.g:

```
We love that you're using Semgrep would you like to... work on it full time?! 😄 

############
# Security #
############

* Senior Security Researcher: https://jobs.lever.co/returntocorp/c0e3a208-9a76-4fc6-9a03-dadc3ebc6f38
* Senior Security Engineer: https://jobs.lever.co/returntocorp/9ac6d4bc-a939-4bf9-8bf0-983774cb23d1

###############
# Engineering #
###############

* Software Engineer, Program Analysis: https://jobs.lever.co/returntocorp/a0185a91-bc99-428c-9441-515489212738
* ...
```

**Describe alternatives you've considered**
Lever, LinkedIn, Twitter, smoke signals, hiring blimps to fly over hacker conferences flying the Semgrep logo, etc.

**Use case**
Hiring a world-class team and taking Semgrep to the moon 🚀 

**Additional context**
@adamberman had this excellent idea and I wanted to write it down.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-891/and-a-apply-flag-that-lets-you-easily-apply-for-a-job-at-r2c.
