### ISSUE TITLE
Ellipsis inside subscription expression fails to match zero elements

### ISSUE THREAD

**Issue by IRDonch** [semgrep/semgrep#4714]
**Describe the bug**
A pattern like `$X[..., <something>, ...]` fails to match code like `x[<something>]`, even though `...` is supposed to be able to match zero elements.

**To Reproduce**
https://semgrep.dev/s/4DLE

**Expected behavior**
The rule should match the type annotations of both `a` and `b`.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build? N/A

**Use case**
I was migrating my code to the usage of `from __future__ import annotations` and trying to find usages of old-style string-based type annotations.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-895/ellipsis-inside-subscription-expression-fails-to-match-zero-elements.
