### ISSUE TITLE
Match the existence of children in JSX

### ISSUE THREAD

**Issue by azuline** [semgrep/semgrep#4717]
**Is your feature request related to a problem? Please describe.**
I would like to match the presence of children in JSX. In https://staging.semgrep.dev/s/z8wZ, the third statement does not have a match. I am not sure how to cause it to match; no standard semgrep syntaxes seem to work.

**Describe the solution you'd like**
To be able to match arbitrary children, but not no children.

**Use case**
I will be able to discriminate between child-less components and component with children. There are some child-less components that I have a linting use case for.

**Additional context**
Seems somewhat related to https://github.com/returntocorp/semgrep/issues/4678.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-898/match-the-existence-of-children-in-jsx.

**Comment by aryx** [comment]
This works now on develop: https://staging.semgrep.dev/s/zvdP?version=develop
It should make the next release (0.85.0) next week.
