### ISSUE TITLE
Get semgrep in homebrew core

### ISSUE THREAD

**Issue by rcoh** [semgrep/semgrep#472]
Currently, semgrep is installed via tap. It meets the requirements to be packaged in homebrew core as is, _but_ this will be easier once semgrep_lint is finalized and it will limit the amount of changes we'll need to make to the brew-core recipe, but could technically start now if we want.

**Comment by aryx** [comment]
I thought there was a minimum number of stars and forks to be accepted in Core. We meet that already?

**Comment by rcoh** [comment]
Yeah it's 80

**Comment by rcoh** [comment]
I think we should deprioritize this -- with the new setup people can brew install with one comman and no manual tapping

**Comment by rcoh** [comment]
The PR is in brew core! https://github.com/Homebrew/homebrew-core/pull/54261 I will monitor and shepherd it over the next few days / weeks to get it merged.

**Comment by brendongo** [comment]
PR was merged so counting this as done!
