### ISSUE TITLE
Python decorators cannot be matched in isolation

### ISSUE THREAD

**Issue by timmc-edx** [semgrep/semgrep#4722]
### Describe the bug
The pattern syntax does not allow matching a Python pattern in isolation, and requires it to be specified along with a function or method.

### To Reproduce
Demo of error: https://semgrep.dev/s/JgRj

Or more simply, any pattern like `@patch(...)` is not permitted.

### Expected behavior
I would expect it to be possible to match decorators as isolated pattern expressions.

### What is the priority of the bug to you?

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

### Environment
`pip install semgrep==0.82.0` on Ubuntu Linux 20.04.

### Use case
Same as https://github.com/returntocorp/semgrep/issues/4721 -- this was an alternative approach that would have avoided the inadvertent removal of any additional decorators, along with the whitespace issues of <https://github.com/returntocorp/semgrep/issues/3070>.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-903/python-decorators-cannot-be-matched-in-isolation.

**Comment by emjin** [comment]
@IagoAbal Does metavariable-focus fix this?

**Comment by IagoAbal** [comment]
@timmc-edx does this https://semgrep.dev/s/e5jE work for you ?

**Comment by IagoAbal** [comment]
We could use `focus-metavariable:` (not yet public feature) if this worked:

```yaml
    - pattern: |
        @$X
        def $F(...):
            ...
```

It does work for some languages but it seems that it doesn't for Python.

**Comment by timmc-edx** [comment]
@IagoAbal Your demo just adds the function to the context, right? See https://github.com/returntocorp/semgrep/issues/4721 and https://github.com/returntocorp/semgrep/issues/3070 for why that's undesirable.

**Comment by IagoAbal** [comment]
@timmc-edx AFAICT my example works and it doesn't suffer from those issues, have you actually tried it?

**Comment by timmc-edx** [comment]
I see, you're using `pattern-regex`. That does seem to work for single-line decorators, but not for multiline. Autofix ends up doing this:

```
    @patch('lms.djangoapps.badges.backends.badgr.BadgrBackend.award', autospec=True)
        'lms.djangoapps.badges.backends.badgr.BadgrBackend.award'
    )
```

**Comment by IagoAbal** [comment]
I believe you can handle multiline cases with `pattern-regex:` too. Maybe @returntocorp/security  or @mmcqd (who is on-call) can help you with this. You may get help quite fast if you ask in https://r2c.dev/slack.

We have an upcoming feature (for now know as `focus-metavariable:`) that would be a better solution than `pattern-regex:`, but first we would need to make this work:

```yaml
    - pattern: |
        @$X
        def $F(...):
            ...
```

**Comment by timmc-edx** [comment]
Unfortunately, `@patch` can and often does take arbitrary (nested) expressions, so a regex can only help for a limited set of inputs. Maybe if you assume the indentation is correct and use backreferences to leading whitespace to identify the closing paren... :-) But I'm not actually blocked on this, since I ended up not wanting to make the autofix that I originally set out to do.

**Comment by yosefAlsuhaibani** [comment]
Hello! this should be fixed in semgrep's next release.
