### ISSUE TITLE
Disable certain JSX equivalences (to be able to match JSX elements without children and attributes)

### ISSUE THREAD

**Issue by azuline** [semgrep/semgrep#4730]
**Describe the bug**
The ellipsis metavariables syntax `$...X` doesn't work for JSX tags.

**To Reproduce**
https://staging.semgrep.dev/s/pGWd

**Expected behavior**
I would expect `<$...X />` to match multiple artibrary components.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Official binary

**Use case**
I am attempting to match components that meet a certain pattern, but don't have children.

This is for a suggestion that we shouldn't have components like `<View mt="8" />`, but instead use the more semantically relevant `<Spacer y="8" />`.

I am trying to match only components without children, because this rule doesn't make much sense once this component has children. But I am unable to make it work.

I have successfully matched a single arbitrary text child with `<View>...</View>` and a single arbitrary component child with `<View> <$X /> </View>`. In the latter, whitespace is significant, which is rather surprising and disappointing, as it makes for a terrible developer experience.

But I have not managed to match multiple children. This means that I cannot enable this rule without bringing around false positives.

There are many other lints I wish to introduce using Semgrep, but cannot due to the lacking nature of the JSX pattern match. I believe that the JSX matching semantics are quite poor, and I'm hesitant to introduce such hard to intuit matching semantics as our custom linting solution.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-909/ellipsis-metavariables-dont-work-for-jsx-tags.

**Comment by aryx** [comment]
An Ellipsis metavariable is a very advanced feature of semgrep that is rarely useful. It's useful only for autofix. In all the other context you can replace an ellipsis metavariable with simply an ellipsis.

Given your use case, what you really want is the ability to disable certain JSX equivalences the matching engine performs, which should be available in the next release thx to the PR above.

**Comment by azuline** [comment]
Thanks!

**Comment by aryx** [comment]
This should work now: https://staging.semgrep.dev/s/oxqd?version=0.84.0
