### ISSUE TITLE
error message has "--dump_ast" flag with underscore instead of "--dump-ast" flag

### ISSUE THREAD

**Issue by 0xDC0DE** [semgrep/semgrep#4733]
**Describe the bug**

error message prints flag with and underscore '_' character instead of a minus '-' character

**To Reproduce**
```
$ semgrep --dump-ast myfile.py
--dump_ast and -l/--lang must both be specified
```

**Expected behavior**
print the flag correctly

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-911/error-message-has-dump-ast-flag-with-underscore-instead-of-dump-ast.

**Comment by 0xDC0DE** [comment]
I think it is printing the semgrep-core flag instead of the semgrep flag.
