### ISSUE TITLE
Simple kotlin patterns are not deteced.

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#4741]
**Describe the bug**
Kotlin patterns are not detected.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
https://semgrep.dev/s/xXoy

**Expected behavior**
Ability to detect simple nested patterns

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
Write kotlin semgrep rules for [mobsfscan](https://github.com/MobSF/mobsfscan).

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-916/simple-kotlin-patterns-are-not-deteced.

**Comment by aryx** [comment]
Ok taking this.

**Comment by aryx** [comment]
Should work now.
It should make the next release  (0.84) tomorrow or thursday.

**Comment by ajinabraham** [comment]
Thanks, will test this out.
