### ISSUE TITLE
Make it easy to discover languages supported by Semgrep from CLI

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#4747]
**Is your feature request related to a problem? Please describe.**
When I'm writing a rule, I want to know what values I can put in the `languages` key. 

For example, for Terraform, should I put `terraform`, `hcl`, other? Is it `csharp`, `c#`, other? 

We've already have some drift in the registry where for one "language" we have a number of different keys across many rules. We should instead just standardize on one key for each "language" and enforce it consistently. And make it easily discoverable for users!

**Describe the solution you'd like**
It should be easy for novice Semgrep rule authors to easily discover which `language` keys are valid.

Maybe this means adding a `--[show]-supported-languages` option that people can discover via `--help`, maybe we include this info in the default `--help` message output, maybe other?

**Describe alternatives you've considered**
You can go to the docs https://semgrep.dev/docs/language-support/ which says at a high level which languages are supported, but it's not clear what I should put in the `languages` key in a Semgrep rule.

If you're clever or lucky, you can find out all the valid keys by using an invalid "language" and Semgrep spits out the supported values:

```bash
$ semgrep -l asdf -e '$X'

  --> None:1
1 | Semgrep bug generating manual config An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

unsupported language: asdf. supported languages are: bash, c, c#, c++, cpp, csharp, docker, dockerfile, generic, go, golang, hack, hcl, html, java, javascript, js, json, kotlin, kt, lua, none, ocaml, php, py, python, python2, python3, r, regex, ruby, rust, scala, sh, sol, solidity, terraform, tf, ts, typescript, vue, yaml
```

**Use case**
When I'm writing a rule, I want to know which values I can put in `languages`.

I want to keep these values consistent across the semgrep-rules registry.

**Additional context**
I'd probably consider this a P1 or P2 - not urgent or blocking anything, but is a nice discoverability feature / helps new users unblock themselves more easily.

**Comment by clintgibler** [comment]
Note: official tags are here (thanks @kurt-r2c): https://github.com/returntocorp/semgrep-langs/blob/main/lang.json

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-925/make-it-easy-to-discover-languages-supported-by-semgrep-from-cli.

**Comment by ievans** [comment]
> We've already have some drift in the registry where for one "language" we have a number of different keys across many rules. We should instead just standardize on one key for each "language" and enforce it consistently. And make it easily discoverable for users!

We've talked about this before and I think it's inconsistent with the philosophy of Semgrep for this to be enforced here. cc @aryx for context. but the gist of it was: why make the user think about whether it's `csharp` or `c#`? Just accept both.

we can of course make things like the registry or semgrep-rules consistent if we want, via automations

**Comment by wu-s-john** [comment]
External Committer here! Solved this issue in my PR (https://github.com/returntocorp/semgrep/pull/4754). Please review!

**Comment by ievans** [comment]
Thanks @wu-s-john!
