### ISSUE TITLE
CLI: Color control characters are output in error messages when piped or the `-o` option is used

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#4752]
**Describe the bug**
When an error occurs during a CLI scan, color control characters are included in error messages in both of the following cases:
1. output is being redirected via a pipe
2. output is being redirected using the `-o` command line argument

This happens even when `--no-force-color` is specified, and I encountered this error when using both the `--json` and `--sarif` format options. Unsure if other output formats are affected.

**To Reproduce**
Run semgrep on a code file that is syntactically incorrect. (A more detailed example will be given in Linear)

**Expected behavior**
Only the raw text should be output in the error messages

**Screenshots**
<img width="1487" alt="Screen Shot 2022-03-04 at 18 04 04" src="https://user-images.githubusercontent.com/14846866/156863533-de9a5aad-b4d7-4858-ad35-a127fd9aeba4.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Semgrep CLI

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-929/cli-color-control-characters-are-output-in-error-messages-when-piped.

**Comment by aryx** [comment]
I think @underyx had a PR related to colors recently. 
Is it related?

**Comment by brendongo** [comment]
Yes color is no longer included in non text formats.
