### ISSUE TITLE
Semgrep integrated in Scanmycode CE (Community Edition) 

### ISSUE THREAD

**Issue by ghost** [semgrep/semgrep#4753]
Hi,

I would like to share information about my Open Source and selfhosted Code Scanning (Quality & Security) solution here.

We also added your Semgrep for checking code.

Here is the repository for the Community Edition of the solution (Code & Wiki)

https://github.com/marcinguy/scanmycode-ce

For transparency, I was involved and am involved in building of it. Took several months with several people.

Thank you for Semgrep being there.

Feel free to contact my directly or here in case of any questions/comments.

Thanks,

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-930/semgrep-integrated-in-scanmycode-ce-community-edition.

**Comment by ievans** [comment]
Hi @marcinguy, congrats on your new release and thanks for sharing! Feel free to add to https://github.com/returntocorp/semgrep-docs/edit/main/docs/extensions.md as well!
