### ISSUE TITLE
[PHP] analyze .tpl files as PHP files

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#4762]
Reference discussion: 

https://r2c-community.slack.com/archives/C018NJRRCJ0/p1646636690448559

See also https://stackoverflow.com/questions/1808294/what-are-tpl-files-php-web-design
and here is an example of repository using it:
https://github.com/JazzrockS07/authorization_for_user/
The smarty templating language is using it. See the use of .tpl files in the example in the documentation:
https://www.smarty.net/docs/en/installing.smarty.basic.tpl#idp31759904

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-938/[php]-consider-tpl-files-as-php-files.

**Comment by aryx** [comment]
Actually looking at https://www.smarty.net/crash_course the Smarty .tpl files are actually not parseable as-is by the PHP
parser. This is more something where the semgrep preprocessor would help, like for the other templating files like .erb. ejs, etc.

**Comment by aryx** [comment]
Still it seems there are repositories using .tpl for regular PHP files (not smarty), e.g.  https://github.com/JazzrockS07/authorization_for_user/
