### ISSUE TITLE
Allow 'CMD ...' to match any CMD instruction

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#4770]
**Describe the bug**

`CMD ...` right now only matches a CMD with shell code. It should also match `CMD ["foo"]` but doesn't.

**To Reproduce**

Go to this URL and **press Enter to add a trailing newline at the end of the pattern** (bug #4771):
https://semgrep.dev/s/mjambon:docker-cmd-catchall

**Expected behavior**

This should match all the CMD instructions.

**Screenshots**

![image](https://user-images.githubusercontent.com/343265/157340814-a6bed7c9-65d1-491e-93fd-570e30528511.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

any

**Use case**

Write dockerfile rules with an explosion of the number of patterns as the number of CMD catch-alls increases. This will avoid writing a pattern with `CMD ...` and another one with `CMD [ ... ]`.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-943/allow-cmd-to-match-any-cmd-instruction.

**Comment by mjambon** [comment]
What we want is:
* `CMD ...` matches any CMD instruction (shell or argv) rather than just shell code
* `CMD ... ;` matches only shell code (already works, see https://semgrep.dev/s/mjambon:docker-cmd-shell). Alternatively, `CMD { ... }` might be a better recommendation (the braces would have to be ignored which isn't the case right now).
* `CMD [ ... ]` matches only argv (already works)

**Comment by ajbt200128** [comment]
@mjambon Checkout the PRs above, fixed this issue, and also fixed a similar issue for `ENTRYPOINT` and `RUN`, and added relevant tests

**Comment by mjambon** [comment]
@ajbt200128 thank you for looking into this, but I don't think it helps. The parser has no difficulty parsing `CMD ...` at the moment because `...` is a valid [semgrep-extended] shell program. I think the question is how it's translated into semgrep's generic AST. We want it to be translated into something like "call the CMD function on one argument that is the Ellipsis". This code is in the semgrep repo, somewhere under `semgrep-core/parsing`. It's getting late now but I'm planning to look into this next week.

**Comment by ajbt200128** [comment]
Yea that's what I figured too, and what I updated. If you check [Parse_dockerfile_tree_sitter.ml](https://github.com/returntocorp/semgrep/pull/4800/files#diff-6268dbfc7a977654c7f773848fed75fba9c8b2cd5ca7b59a71b1469ba9a83026) and [Dockerfile_to_generic.ml](https://github.com/returntocorp/semgrep/pull/4800/files#diff-7897fa9a1fc33e1491a61b88634ef37ac179f5c7347c3a36b59cb7dd3255d7cd) you'll see the relevant changes. Also, in that PR you'll see tests in `semgrep-core/tests/dockerfile`that match and pass the matching functionality you specified above. Let me know if this isn't what you meant

**Comment by mjambon** [comment]
I implemented a solution (#4813) which doesn't touch the grammar, mostly because I want to release this ASAP and the dockerfile grammar needs to be upgraded (it seems). I'll take a look tomorrow.

@ajbt200128 please consult with us next time you feel like contributing. We have a bunch of tasks for you, that's not a problem. Some things are more difficult or urgent than others and are expected to be done in a certain way.

**Comment by ajbt200128** [comment]
Got it, will do next time
