### ISSUE TITLE
Assume newline at the end of dockerfile patterns

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#4771]
**Describe the bug**

Something removes the newlines from dockerfile patterns when using the Playground. The pattern parser then fails to accept it as valid.

Instead, we should accept patterns that don't end with a newline.

See https://semgrep.dev/s/mjambon:dockerfile-missing-newline

![image](https://user-images.githubusercontent.com/343265/157341979-d6ec319a-271c-469e-b6c9-7cd248c4bd1b.png)

A workaround is to manually hit Enter at the end of the pattern(s), every time.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-944/assume-newline-at-the-end-of-dockerfile-patterns.
