### ISSUE TITLE
update schema to allow a single rule in a config .yaml without a `rules:` superkey

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4784]
**Is your feature request related to a problem? Please describe.**
The new editor has a hacked schema that doesn't require nesting under `rules`. Semgrep should just support this natively, as the trend is towards only allowing a single rule in a file anyways.

**Describe the solution you'd like**
Update semgrep schema so that this is a valid rule:

```
id: python-no-prints-in-prod
pattern: old_print($X)
message: Use logging.debug() instead of old_print()
languages:
  - python
```

**Describe alternatives you've considered**
Fix the editor so that it doesn't automagically include `rules:` @underyx 

**Use case**
Easy to copy / paste between editor, playground, local files. Less friction for users.

**Additional context**

**Comment by ievans** [comment]
See also https://linear.app/r2c/issue/AUT-82/if-a-snippet-works-in-the-editor-it-works-locally

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-950/update-schema-to-allow-a-single-rule-in-a-config-yaml-without-a-rules.

**Comment by aryx** [comment]
Note that semgrep-core now accepts such yaml file without the top rules: key.

**Comment by aryx** [comment]
I think this has been tried and reverted. @annikalee or @milanwilliams have more information about it I think.

**Comment by annikalee** [comment]
I'm closing this issue as we have decided to go down the alternative path described above instead.
