### ISSUE TITLE
--baseline-commit doesn't restore deleted files outside working directory

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#4786]
Assume you have semgrep cloned at ~/semgrep.

1. cd ~/semgrep/semgrep-core
2. semgrep -f auto --baseline-commit HEAD~100
3. git status

You'll see a bunch of removed files, because semgrep modifies all of the repo's directories when going back to baseline, but only restores the current working directory when going back to the current version.

Semgrep 0.84

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-952/-baseline-commit-doesnt-restore-deleted-files-outside-working.
