### ISSUE TITLE
Specifying a variable as a source using `$METAVARIABLE: Type` notation does not work in `pattern-sources`

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#4789]
**Describe the bug**
https://semgrep.dev/s/lejliu:mongo-inject-from-request
Ideally, I'd like to be able to not have to specify a specific context using `pattern-inside` and would just like to do
```yaml
pattern-sources:
  - pattern: |
      $REQ: Request
```
so that the rule is more flexible and I don't have to account for all the different ways that a Request object can be created.

I figure this is _supposed_ to work because changing the `pattern-sources` to: 
```yaml
pattern-sources:
  - pattern: req
```
works, but I might be wrong in assuming that that notation should be supported.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Create more flexible taint mode rules for Typescript.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-954/specifying-a-variable-as-a-source-using-dollarmetavariable-type.

**Comment by emjin** [comment]
From slack discussion: Needs to be wrapped in parens
