### ISSUE TITLE
TypeScript Tree-Sitter Bug with override

### ISSUE THREAD

**Issue by faceyacc** [semgrep/semgrep#4798]
**Describe the bug**
A user is running into a `Semgrep Core - Syntax Error` when running a TypeScript file using Typescript decorators. 

**To Reproduce**
Run code snippet in Playground: https://semgrep.dev/s/XZdq

**Expected behavior**
User should be able to run `--config auto` on the code snippet above without running into Syntax Error

**What is the priority of the bug to you?**
- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Local build; Semgrep CLI. 

**Use case**
This fix will better our TypeScript support, and prevent users from running into similar errors when running Semgrep on TypeScript files.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-960/typescript-tree-sitter-bug.

**Comment by aryx** [comment]
This works now: https://semgrep.dev/s/XZdq?version=develop
