### ISSUE TITLE
Add to SARIF formatter the code snippet

### ISSUE THREAD

**Issue by oxeye-yuvalk** [semgrep/semgrep#4805]
The problem is that today the SARIF output does not include the snippet of the code that could help to understand the issue

According to this scheme - https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json

I would like to add code into SARIF formatter

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-978/add-to-sarif-formatter-the-code-snippet.

**Comment by brendongo** [comment]
@oxeye-yuvalk which property are you referring to in the schema? Not sure where under the results object we would add matching code to: https://github.com/oasis-tcs/sarif-spec/blob/master/Documents/CommitteeSpecifications/2.1.0/sarif-schema-2.1.0.json#L2025

**Comment by oxeye-yuvalk** [comment]
Hey :)
the property is snippet under region
I have no problem implementing this on myself :)

**Comment by brendongo** [comment]
Closed by #4812 above
