### ISSUE TITLE
Upgrade Dockerfile grammar

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#4814]
This is a follow-up to https://github.com/returntocorp/semgrep/pull/4813
* the dockerfile grammar has already been extended (https://github.com/returntocorp/ocaml-tree-sitter-semgrep/pull/293) with an ellipsis after CMD/RUN/etc. We should then get rid of the hack that parses `...` using PCRE.
* there are some changes (not sure how many) which require changes here and there in the ocaml boilerplate.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-981/upgrade-dockerfile-grammar.
