### ISSUE TITLE
Update Semgrep to Go 1.18

### ISSUE THREAD

**Issue by raghavjain3** [semgrep/semgrep#4823]
**Is your feature request related to a problem? Please describe.**
Update Semgrep to support the newest [version](https://tip.golang.org/doc/go1.18) of Go (1.18)

**Describe the solution you'd like**
Use Semgrep for generics added in this version

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-990/update-semgrep-to-go-118.
