### ISSUE TITLE
Do not crash when only one of the rule does not parse correctly in semgrep-core

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#4829]
This is related to https://github.com/returntocorp/semgrep/issues/4828

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1003/do-not-crash-when-only-one-of-the-rule-does-not-parse-correctly-in.

**Comment by aryx** [comment]
Just return the id and error message of the problematic rule in the JSON returned by semgrep-core. The CLI can then choose to print a nice error message to the user.

**Comment by aryx** [comment]
As we add more features in semgrep, and the rule format gets extended (e.g., adding metavariable-entropy analysis recently), old version of semgrep may not be able to parse the latest rules and just crash. It's better instead to warn and skip those rules, to not compromise CI jobs just because of a few rules that use rare (and new) features.
