### ISSUE TITLE
Ellipsis metavariable ($...X) doesn't work in HTML mode

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#4841]
**Describe the bug**
The ellipsis metavariable doesn't work in HTML mode:    

>       <script ...>$...JS</script>

**To Reproduce**
doesn't work with `$...JS`: https://semgrep.dev/s/QbAk
works with `...`: https://semgrep.dev/s/3B3e

**Expected behavior**
Expect matches with `$...JS`

**Screenshots**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep 0.85

**Use case**
Customer request.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1007/ellipsis-metavariable-dollarx-doesnt-work-in-html-mode.
