### ISSUE TITLE
"Some filed were skipped. Scan was limited to files tracked by git" outside of Git repos and when no files were actually skipped

### ISSUE THREAD

**Issue by malexmave** [semgrep/semgrep#4847]
**Describe the bug**
(Not sure if this is a bug report or a feature request). When scanning files outside of a Git repository, semgrep still outputs the warning "Some files were skipped. Scan was limited to files tracked by git." after running, even if a) I am not in a Git repository, and b) there weren't actually any files that were skipped. This is unintuitive and always makes me question if there is some interaction that I don't understand, or if I am accidentally operating inside a Git repo.

**To Reproduce**
Run semgrep outside of a Git repository. For example, run this in an empty folder outside of Git:
```bash
$ semgrep -l py -e 'pass'
Nothing to scan.

Some files were skipped.
  Scan was limited to files tracked by git.

Ran 1 rule on 0 files: 0 findings.
```

**Expected behavior**
- Do not say that you limit the scan to files tracked by Git when you are operating outside of a Git repo. 
- Do not say that some files were skipped if no files were actually skipped

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Mac OS, v0.85.0 from brew.

**Use case**
Have more confidence that I am actually scanning what I want to scan.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1012/some-filed-were-skipped-scan-was-limited-to-files-tracked-by-git.

**Comment by QuentinN42** [comment]
I think I've the same problem :
**Environment:**
Docker image `returntocorp/semgrep:4f07d9e468ee7a02bd61febebee163be4a1b3ee8`

```
/path/to/repo # semgrep --config=auto . -v
Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate
recommended rules based on your languages and frameworks.
Fetching rules from https://semgrep.dev/registry.
running 191 rules from 1 config remote-url_0
No .semgrepignore found. Using default .semgrepignore rules. See the docs for the list of default ignores: https://semgrep.dev/docs/cli-usage/#ignoring-files
Rules:

...

Unable to ignore files ignored by git (. is not a git directory or git is not installed). Running on all files instead...
Nothing to scan.

Findings:

============================[ summary ]============================
Total time: 4.5945s Config time: 3.5715s Core time: 1.0222s

Semgrep-core time:
Total CPU time: 0.5828s  File parse time: 0.0000s  Rule parse time: 0.5828s  Match time: 0.0000s
Slowest 5/0 files
Slowest 5 rules to match
...:               0.000s
...:               0.000s
...:               0.000s
...:               0.000s
...:               0.000s

Errors:   0 files with errors


========================================
Files skipped:
========================================

  Always skipped by Semgrep:

   • <none>

  Skipped by .gitignore:
  (Disable by passing --no-git-ignore)

   • <all files not listed by `git ls-files` were skipped>

  Skipped by .semgrepignore:
  (See: https://semgrep.dev/docs/ignoring-files-folders-code/#understanding-
  semgrep-defaults)

   • <none>

  Skipped by --include patterns:

   • <none>

  Skipped by --exclude patterns:

   • <none>

  Skipped by limiting to files smaller than 1000000 bytes:
  (Adjust with the --max-target-bytes flag)

   • <none>


Some files were skipped.
  Scan was limited to files tracked by git.

Ran 191 rules on 0 files: 0 findings.
Sending pseudonymous metrics since metrics are configured to AUTO and server usage is True
```

But there is some git files : 

```
# git ls-files | wc -l
1618
```

**Comment by QuentinN42** [comment]
Arg, this is working if I bind my volume on the path `/src/` ...

**Comment by ievans** [comment]
As of `1.36.0` it looks like we don't say "skipped" anymore, although we do still say "tracked by git" even when not in a git repo.

**Comment by sneko** [comment]
@ievans I want to run tests on a repository I unzip but I face the same issue. Is there a way to tell `semgrep` to work normally even if no Git settings in the current directory?

Thank you,
