### ISSUE TITLE
Parse failure when parsing YAML with braces

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#4849]
This fails to parse as YAML:

```
hello: {{world}}
```

https://semgrep.dev/s/sjord:yaml-braces

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1019/parse-failure-when-parsing-yaml-with-braces.

**Comment by Sjord** [comment]
Semgrep-core seems to use the [Ocaml YAML](https://github.com/avsm/ocaml-yaml) module, and that doesn't support this:

```
utop # Yaml.of_string "hello: {{world}}";;
- : Yaml.value Yaml.res = Result.Error (`Msg "non-string key is not supported")
```

**Comment by Sjord** [comment]
I encountered something like `hello: {{world}}` when scanning a client's project. It is valid YAML, but I guess they pass it through a template engine which replaces `{{anything}}` with a variable. So `{{world}}` signifies a variable to be replaced, not a nested data structure.

I don't care much how semgrep interprets `{{world}}`, but because it raises an error I can't search for other patterns in the file. I am not searching for `hello: {{world}}`, I am searching for something like `security: disabled` which is somewhere else in the file. But because it doesn't parse it doesn't get found.

**Comment by Sjord** [comment]
> Do you have a reference for this being valid YAML syntax?

According to [this](https://yaml.org/spec/1.2.2/#rule-ns-flow-map-implicit-entry), a mapping entry may consist of only a key. So `{world}` would be valid, and equivalent to `{world: null}`.

Further down, it says:

> Note that YAML allows arbitrary [nodes](https://yaml.org/spec/1.2.2/#nodes) to be used as [keys](https://yaml.org/spec/1.2.2/#nodes). In particular, a [key](https://yaml.org/spec/1.2.2/#nodes) may be a [sequence](https://yaml.org/spec/1.2.2/#sequence) or a [mapping](https://yaml.org/spec/1.2.2/#mapping).

So having `{world}` as key is valid, and `{{world}}` would be equivalent to

```
{
    {world: null}: null
}
```

So I think this is valid YAML. However, no one uses it this way. Even in my example, the `{{world}}` indicates a variable to be replaced, and not a nested mapping. So being lenient with the parsing may still be the best solution.

**Comment by emjin** [comment]
Closing for now via the linked PR, reopen if that solution is insufficient
