### ISSUE TITLE
Scala class constructor calls do not work as taint sinks

### ISSUE THREAD

**Issue by Ezzer17** [semgrep/semgrep#4858]
**Describe the bug**
Scala class constructor calls do not work as taint sinks

**To Reproduce**
https://semgrep.dev/s/ezzer17:constructor-taint-bug

**Expected behavior**
Match detected on attached playground

**What is the priority of the bug to you?**
P1: important to fix or quite annoying

**Use case**
Taint analysis with class constructors as sinks

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1026/scala-class-constructor-calls-do-not-work-as-taint-sinks.
