### ISSUE TITLE
At line mvnw:220: `case "$key" in (wrapperUrl) jarUrl="$value"; break ;;      esac` was unexpected

### ISSUE THREAD

**Issue by patpatpat123** [semgrep/semgrep#4874]
Hello Team,

Thanks you for this very cool project.

Just wanted to report:

semgrep -f semgrep_rules/ --json --metrics=off
[WARN] Semgrep Core — Syntax errorAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrepAt line mvnw:220: `case "$key" in (wrapperUrl) jarUrl="$value"; break ;;      esac` was unexpected

Could you please help on this issue please?

Thank you

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1035/at-line-mvnw220-case-dollarkey-in-wrapperurl-jarurl=dollarvalue-break.

**Comment by emjin** [comment]
Hi, can you share a snippet of code where this occurs?
