### ISSUE TITLE
[Docker] Port value of `EXPOSE` is parsed as a String, not an integer.

### ISSUE THREAD

**Issue by 0xDC0DE** [semgrep/semgrep#4875]
**Describe the bug**
The value of the port after the `EXPOSE` keyword is parsed as a string.

It is my assumption that this is why the following rule with `metavariable-comparison` does not work:
https://semgrep.dev/s/pieterdc1:dockerfile-invalid-port

**To Reproduce**
<img width="955" alt="image" src="https://user-images.githubusercontent.com/3809983/159943285-3f6eac79-0225-4ae1-a8f4-918f81260aab.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Porting dockerfile rules from `generic` to `dockerfile`

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1036/[docker]-port-value-of-expose-is-parsed-as-a-string-not-an-integer.

**Comment by nbrahms** [comment]
@pieterdc1 I think you can just use a few options on `metavariable-comparison`:

https://semgrep.dev/s/Y4lo

**Comment by IagoAbal** [comment]
Yeah I think next time you should check the docs @pieterdc1. PR #4977 still makes sense, but this should have been low
priority IMO. Although I would personally recommend:

```
 - metavariable-comparison:
      metavariable: $PORT
      comparison: int($PORT) > 65535
```

**Comment by 0xDC0DE** [comment]
My bad. I did not understand this feature as well as I should have before filing an issue. I was asked to make dockerfile issues medium priority.
