### ISSUE TITLE
Add docs for matching annotations in sgrep rules

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#488]
**Is your feature request related to a problem? Please describe.**
Sgrep currently has functionality for matching annotations in Java and Python. We should add useful examples of how to do this in the documentation, likely in `docs/config/simple.md`.

**Describe the solution you'd like**

We should include at least the following cases:
* [ ] Match annotations on classes as well as methods
* [ ] Match methods with annotation `@A` and `@B`
* [ ] Match methods with annotation `@A` and **not** `@B`
* [ ] Match annotations with one string arg e.g. `@SomeAnnotation("foo")` but not `@SomeAnnotation("bar")`
* [ ] Match annotations with named arg e.g. `@SomeAnnotation(arg = "foo")` but not `@SomeAnnotation(arg = "bar")`
* [ ] Match annotations with named args `@RequestMapping(method = RequestMethod.GET)` - pull out which `RequestMethod.HTTP_METHOD` is used)
* [ ] Match annotations with multiple named args `@RequestMapping(value = "/endpoint", method = RequestMethod.GET)` - match on both `value` and `method`

**Describe alternatives you've considered**
N/A

**Additional context**
Note: we should add docs and examples for Python, and make it clear that Java and Python are the only languages with annotations supported at this point.

**Comment by clintgibler** [comment]
Note: matching specific annotations works (e.g. https://semgrep.live/yoA), but currently there is *not* a way to match an unknown annotation, e.g.

~~~java
@$ANNOTATION
public void $METHOD(...) {
  ...
}
~~~

**Comment by ievans** [comment]
@clintgibler if you added test cases for these in semgrep core, they would automatically propagate to our cheatsheets which would be a nice way to accomplish this!

**Comment by aryx** [comment]
@DrewDennison any idea why the semgrep.live URL don't work anymore? Too old? We reseted the DB at some point?

**Comment by aryx** [comment]
And you can now use metavariable for annotations: https://semgrep.dev/s/boqe/
Closing this as many people actually are using annotations in patterns.
