### ISSUE TITLE
dockerfile: `FROM img AS name` doesn't match `FROM img as name`

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#4881]
`AS` is supposed to be case-insensitive but matching appears to be case-sensitive:

![image](https://user-images.githubusercontent.com/343265/160020688-1a5d118f-5316-47cf-a8ed-87b6764d91a2.png)

https://semgrep.dev/s/mjambon:as

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1037/dockerfile-from-img-as-name-doesnt-match-from-img-as-name.

**Comment by mjambon** [comment]
First findings:
* the tree-sitter parser doesn't seem to be parsing `FROM foo AS bar` correctly
* the ocaml translation to the generic AST ignores the AS part at the moment (the `AS` would have to be downcased for sure, but that's not even the issue yet)
