### ISSUE TITLE
[Dockerfile] Named ellipses would enable autofix for about half of the rules that it currently is not possible

### ISSUE THREAD

**Issue by 0xDC0DE** [semgrep/semgrep#4887]
**Is your feature request related to a problem? Please describe.**
Named ellipses work in other languages but not in Dockerfile.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.](https://semgrep.dev/s/pieterdc1:dockerfile-named-ellipses)

**Use case**
Enables autofix for many more cases where it is currently not possible.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1038/[dockerfile]-named-ellipses-would-enable-autofix-for-about-half-of-the.

**Comment by 0xDC0DE** [comment]
I found another usecase for Named Ellipses in Dockerfile: Matching a shell command in the argument of `RUN`.

Matching the shell command `apk upgrade` in Bash works:
https://semgrep.dev/s/pieterdc1:apk-upgrade

Matching the shell command `apk` in `metavariable-pattern` with Docker works:
https://semgrep.dev/s/pieterdc1:dockerfile-apk

But matching `apk upgrade` in `metavariable-pattern` with Docker does not. I suspect this is because the metavariable can only match a single element.
https://semgrep.dev/s/pieterdc1:dockerfile-apk-upgrade
