### ISSUE TITLE
Support regular expression capture groups in metavariable-regex

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#4913]
**Is your feature request related to a problem? Please describe.**
In `pattern-regex`, you can use `$1`, `$2` like normal metavariables but for regex capture groups. It would be awesome to have this replicated in `metavariable-regex` too.

This request is coming from this example, https://semgrep.dev/s/Jwjo, where a user wants to capture the part of the string following `okta:`. Using `pattern-regex` flags comments, which is undesirable in this circumstance.

**Describe the solution you'd like**
It would be awesome if `metavariable-regex` could also recycle regex capture groups using `$1` or a similar syntax.

**Describe alternatives you've considered**
As shown above, I tried using `pattern-regex` but it also matches comments.

**Use case**
Repeated from above:

This request is coming from this example, https://semgrep.dev/s/Jwjo, where a user wants to capture the part of the string following `okta:`. Using `pattern-regex` flags comments, which is undesirable in this circumstance.

**Additional context**
Community Slack thread: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1647984112886579

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1049/support-regular-expression-capture-groups-in-metavariable-regex.
