### ISSUE TITLE
Incorrect handling of ellipsis metavariables in `semgrep --validate`

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#4918]
**Describe the bug**
Rules with ellipsis metavariables incorrectly fail `semgrep --validate` checks.  This is blocking porting of Brakeman rules to Semgrep.

**To Reproduce**
https://semgrep.dev/s/returntocorp:check-reverse-tabnabbing
https://github.com/returntocorp/semgrep-rules/runs/5699132997?check_suite_focus=true

**Expected behavior**
Ellipsis metavariable usage here is (unfortunately) necessary + correct - test cases for target source code do not pass without this approach.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep App
Semgrep 0.86.5

**Use case**
Finish porting Brakeman rules

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1051/incorrect-handling-of-ellipsis-metavariables-in-semgrep-validate.

**Comment by emjin** [comment]
Fix should go out in next release
