### ISSUE TITLE
javascript AST generic generation error: void 0

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#492]
apparently 
```
if (x === void 0) { // parse error here
            // 
}
```
is valid Javascript. Who knew? https://stackoverflow.com/questions/7452341/what-does-void-0-mean

sgrep currently throws an AstGenericError for this case

https://sgrep.live/zZW

**Comment by DrewDennison** [comment]
https://github.com/denysdovhan/wtfjs is a good source of test cases / patterns we should write

**Comment by ievans** [comment]
@DrewDennison I just checked and it looks like we pass all those cases.
