### ISSUE TITLE
Generic mode pattern-not-inside not filtering out hashtags

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#4926]
**Describe the bug**
In generic mode, trying to filter out potential comments that start with `# ` using `pattern-not-inside` results in matches still.

**To Reproduce**
https://semgrep.dev/s/8kgB 

I would expect the line 11 to not match (it currently matches).

**Expected behavior**
Would expect the inclusion of `pattern-not-inside` to result in filtering of all comment-like cases.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1055/generic-mode-pattern-not-inside-not-filtering-out-hashtags.

**Comment by bmahe** [comment]
Would this solve your problem? https://semgrep.dev/s/0Azk

**Comment by bmahe** [comment]
Alternatively: https://semgrep.dev/s/40j7

**Comment by colleend** [comment]
yes! awesome 👍

**Comment by mjambon** [comment]
The generic mode now has an [option to ignore popular comment syntaxes](https://semgrep.dev/docs/writing-rules/generic-pattern-matching/#ignoring-comments).
```
    options:
      generic_comment_style: shell
```
https://semgrep.dev/s/bAQW

**Comment by colleend** [comment]
awesome feature!!
