### ISSUE TITLE
Typed Metavariable Support for Kotlin

### ISSUE THREAD

**Issue by Gh0u1L5** [semgrep/semgrep#4932]
**Is your feature request related to a problem? Please describe.**
No, this is just an enhancement for Kotlin. So that many Java rules can be migrated to a Kotlin rule set more easily.

**Describe the solution you'd like**
Typed metavariables in Kotlin, just like `(String $X)` in Java.

**Describe alternatives you've considered**
I've considered rules like
``` Kotlin
val $X = A()
...
$X.method()
```
However, there are many edge cases this rule cannot handle, e.g.
``` Kotlin
fun test() {
    // Match
    val object0 = A()
    object0.method()

    // Miss
    val object1 = B() as A
    object1.method()

    // Miss
    val object2 = B()
    (s2 as A).method()

    // Miss
    val object3 = FuncReturnA()
    object3.method()
}

fun FuncReturnA(): A {
    return A()
}
```

I'd write a lot of rules to handle all these edge cases. Instead, if Semgrep can support typed metavariables, life would be much easier.

**Use case**
As explained above.

**Additional context**
Nope.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1083/typed-metavariable-support-for-kotlin.
