### ISSUE TITLE
Python's Relaxing Grammar Restrictions On Decorators (PEP 614) is not supported

### ISSUE THREAD

**Issue by huonw** [semgrep/semgrep#4946]
**Describe the bug**

https://peps.python.org/pep-0614/ (in Python 3.9, released 2020-10-05) generalises Python decorator syntax from `@a.b.c(any, arguments[here])` to accept most expressions, like `@foo[0].bar`. It seems semgrep currently rejects any file that contains this syntax:

```
[WARN] Semgrep Core — Syntax error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line target.py:5: `[` was unexpected
```

**To Reproduce**

Have any Python file (not rule) that contains a decorator using the relaxed syntax. No rules can be evaluated on this file. Example (this code runs and prints `foo`):

```python
x = "bad string"

decorators = [lambda f: f]

@decorators[0]
def foo():
    print("foo")

foo()
```

https://semgrep.dev/s/eJPZ

```json
{"code":3,"level":"warn","message":"[WARN] Semgrep Core — Syntax error\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nAt line target.py:5: `[` was unexpected\n","path":"target.py","type":"Syntax error"}
```

**Expected behavior**

The file should be parseable, and most rules should be evaluated. 

(To be clear, this isn't about improved support for rules about decorators, that's covered by issues like #4722.)

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**

We use the generalised decorator syntax in some cases, and so we're having several files not checked with semgrep.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1090/pythons-relaxing-grammar-restrictions-on-decorators-pep-614-is-not.
