### ISSUE TITLE
Ruby "unless" modifier not correctly supported for functions

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#4948]
**Describe the bug**
The `unless` modifier should parse correctly when using a hash as the final argument of a function, e.g. `function_name $ARGS unless: $CONDITION` is a valid Ruby construction but does not parse correctly.

See: https://rubystyle.guide/#no-dsl-decorating

**To Reproduce**
https://semgrep.dev/s/returntocorp:unless-function-modifier-error

**Expected behavior**
Construction should parse as valid Ruby

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow - impacting a customer's custom rule-writing adoption
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Correct Ruby language support, customer rule-writing

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1094/ruby-unless-modifier-not-correctly-supported-for-functions.
