### ISSUE TITLE
Ruby parser does not support arrow lambdas

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#4950]
**Describe the bug**
Ruby parser doesn't support the ` -> {...}` lambda construction introduced in Ruby 1.9
https://docs.ruby-lang.org/en/2.7.0/Proc.html#class-Proc-label-Creation

**To Reproduce**
[Steps to reproduce the behavior, ideally a link to https://semgrep.dev:](https://semgrep.dev/s/returntocorp:dash-rocket-parse-error)

**Expected behavior**
Ruby parser should support ` -> {...}` lambda construction

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow - blocking customer custom rule-writing adoption
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Ruby parser correctness, customer rule writing

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1095/ruby-parser-does-not-support-arrow-lambdas.
