### ISSUE TITLE
CLI switch to disable color output

### ISSUE THREAD

**Issue by parsiya** [semgrep/semgrep#4951]
**Is your feature request related to a problem? Please describe.**
If we are running Semgrep in a TTY, the text output will have color codes (json and sarif are not affected). 

**Describe the solution you'd like**
I propose a switch to disable this color output.

The switch `--no-force-color` does not disable color output, it just disables forcing the color. I thought it just disables the color.

As a bonus, maybe we could modify the documentation and the "help strings" to clarify their purpose.

**Describe alternatives you've considered**
`--json` and `--sarif` both work and do not have color in the output. Those are machine readable and not for human consumption.

I could also get the text output with color codes and pass it through a simple program (I have written one in Go) to remove them.

**Use case**
It allows me to pipe the output to a file and review it manually in any editor without worrying about color codes and unprintable bytes.

**Additional context**
Some discussion here: https://r2c-community.slack.com/archives/CK86BJ5DW/p1649098236078839.

Previous bug: Color codes appearing in error messages in the JSON output was discussed on Slack at https://r2c-community.slack.com/archives/CK86BJ5DW/p1644972568069339?thread_ts=1644967908.437129&cid=CK86BJ5DW and it's tracked in 
#4752.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1103/cli-switch-to-disable-color-output.

**Comment by underyx** [comment]
We actually have a draft PR open for this already! https://github.com/returntocorp/semgrep/pull/4742

**Comment by parsiya** [comment]
Awesome, will it also be accompanied with a switch sometime?
