### ISSUE TITLE
Taint mode does not handle conditional assignment in Ruby correctly

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#4965]
**Describe the bug**
Ruby supports conditional assignment:

```ruby
foo = if hash[:key]
        hash[:key]
      else
        default_value
      end
```

**To Reproduce**
A minimal example is here: https://semgrep.dev/s/ALK6
This functionality is required to port a Brakeman rule correctly based on this set of test cases: https://semgrep.dev/s/returntocorp:check-symbol-dos

**Expected behavior**
Taint should propagate through conditional assignment.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying - this is blocking completion of a Brakeman check for Ruby < 2.2 / Rails < 5.0
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Porting Brakeman rules, Ruby behavior correctness

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1118/taint-mode-does-not-handle-conditional-assignment-in-ruby-correctly.

**Comment by IagoAbal** [comment]
@kurt-r2c is this the way the actual code looks?
```ruby
  something = if params[:thang]
                params[:thang]
              elsif somevar = "monkeypanda"
                somevar
              end
``` 
This is lacking an `else` branch, what happens if the two `if` conditions are false?
