### ISSUE TITLE
semgrep.dev bug report

### ISSUE THREAD

**Issue by JagadeeshReddy1** [semgrep/semgrep#4974]
https://semgrep.dev/s/AL7L

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1120/semgrepdev-bug-report.

**Comment by nbrahms** [comment]
Hi @JagadeeshReddy1 ,

I think you just had a syntax error in your yaml. Sometimes it can be easier just to use the simple pattern editor. I did that to get:

https://semgrep.dev/s/XWq4

**Comment by nbrahms** [comment]
Please reopen if this didn't solve your issue!
