### ISSUE TITLE
[scala] Functions do not work as taint sinks

### ISSUE THREAD

**Issue by Ezzer17** [semgrep/semgrep#4975]
**Describe the bug**
Simple functions do not work as taint syncs, even though they should.

**To Reproduce**
https://semgrep.dev/s/ezzer17:simple-function-sink-2
If you remove the `return`, it works

**Expected behavior**
Rule has one match

**What is the priority of the bug to you?**

- P1: important to fix or quite annoying

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1121/[scala]-functions-do-not-work-as-taint-sinks.

**Comment by nbrahms** [comment]
Hi @Ezzer17 👋 

Thanks for the bug report! Just to let you know, we haven't released full taint-mode support for Scala yet, so ymmv with taint on Scala.

We'll have a product announcement when we do support taint for Scala.
