### ISSUE TITLE
Developer Feedback "send comment" button should take you somewhere

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#4980]
**Describe the bug**
I hit "not helpful" in github, get taken to the Semgrep page asking for feedback. Type in feedback, and hit "send comment." Hitting that button should change what's on the page to no longer show a text box, so that I can't submit feedback multiple times (and so it's clear it's been accepted)

**To Reproduce**
hit "not helpful" in github, get taken to the Semgrep page asking for feedback. Type in feedback, and hit "send comment." 
Example page:
https://semgrep.dev/issue-sentiment-response?deploymentId=1&hash=54bd08a25f13bedc54930fb5ca886bef48324628b3957dbe90b41c4dd02d6da2&sentiment=bad&issueId=2501623

**Expected behavior**
the webpage should no longer show a text box with the "send comment" button

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1125/developer-feedback-send-comment-button-should-take-you-somewhere.

**Comment by efortuna** [comment]
Ooh, better thought -- the "send comment" takes you back to the github page you were originally on.

**Comment by nbrahms** [comment]
Moved to https://linear.app/r2c/issue/AS-176/developer-feedback-send-comment-button-should-take-you-somewhere

**Comment by nbrahms** [comment]
Closing in favor of the associated Linear ticket
