### ISSUE TITLE
Developer Feedback title and text should be more informative

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#4981]
**Is your feature request related to a problem? Please describe.**
when I click "not helpful" on an inline comment on github, I'm taken to the semgrep page for me to type my feedback. (example page: https://semgrep.dev/issue-sentiment-response?deploymentId=1&hash=54bd08a25f13bedc54930fb5ca886bef48324628b3957dbe90b41c4dd02d6da2&sentiment=bad&issueId=2501623) "Thanks for your feedback" is a bit confusing since it implies I'm providing general feedback on semgrep or something.

**Describe the solution you'd like**
"Thanks for your feedback" should be replaced by "Thanks for telling us that rule wasn't helpful!"

The text below that should include the semgrep suggestion that was not helpful so it's clear what we're providing feedback on, and so that the user has a less confusing context switch since we already have to go to a page away from Github. Maaaaaaybe even the code in github that wasn't helpful? but maybe that would concern users that r2c is looking at their code.

Then below that instead of "additional feedback is welcome" say: "Why is this suggestion not helpful?" 

**Describe alternatives you've considered**
Thumbs down DOESN'T take the user away from github and we simply send the info to semgrep. There's a second button on the github inline comment that has the thumbs down and a plus sign? Something to indicate I want to say WHY this comment isn't helpful instead of just a thumbs down, and _then_ I'm taken to the page we see normally. 

**Use case**
What will this feature enable for you?

Less jarring transition from github to providing feedback on the rule, AND I don't have to switch between tabs to know what rule I"m providing feedback on.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1126/developer-feedback-title-and-text-should-be-more-informative.

**Comment by nbrahms** [comment]
Moved to https://linear.app/r2c/issue/AS-177/

**Comment by nbrahms** [comment]
Closing in favor of the associated Linear ticket
