### ISSUE TITLE
Can't run scans due to: "Additional properties are not allowed ('metavariable-analysis' was unexpected)" error

### ISSUE THREAD

**Issue by utkusen** [semgrep/semgrep#4984]
**Describe the bug**
When I run a scan with `auto`, `owasp-top-ten`, `r2c-security-audit` or `r2c-ci` configs, the following error occurs:

```bash
Failed to download config from https://semgrep.dev/c/auto: semgrep error: Invalid rule schema
  --> https://semgrep.dev/...:5196
5196 |   - patterns:
5197 |     - pattern: |
5198 |         $W(..., aws_secret_access_key="$ACCESSKEY", ...)
5199 |     - metavariable-regex:
5200 |         metavariable: $ACCESSKEY
5201 |         regex: ^[A-Za-z0-9/+=]+$
5202 |     - metavariable-analysis:
5203 |         metavariable: $ACCESSKEY
5204 |         analyzer: entropy
5205 |   - patterns:

Additional properties are not allowed ('metavariable-analysis' was unexpected)

invalid configuration file found (1 configs were invalid)
```

**To Reproduce**
Run a scan with the mentioned rules. For example: `semgrep --config=p/owasp-top-ten`

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
macOS, Linux with official builds

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1132/cant-run-scans-due-to-additional-properties-are-not-allowed.

**Comment by ievans** [comment]
Hello! you need to update to 0.86.5 or higher: some rules in config auto require newer engine feature — we’re working on making this process more graceful & obvious and should have a fix out soon. feel free to re-open if that doesn't solve the issue
