### ISSUE TITLE
Match expressions against type casts of the expression

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#4985]
**Describe the bug**
The following example https://semgrep.dev/s/Ky2L uses an ```as type``` syntax which should be caught under the pattern:
```
              $APP.use(..., $SERVEINDEX(...), ...)
```
It fails to do so, you have to write https://semgrep.dev/s/ZPwp which should not be necessary:
```
              $APP.use(..., $SERVEINDEX(...) as $TYPE)
```

**To Reproduce**
Failing issue: https://semgrep.dev/s/Ky2L
Current solution: https://semgrep.dev/s/ZPwp

**Expected behavior**
The ```...``` operator should catch as type as shown here  https://semgrep.dev/s/Ky2L 

**What is the priority of the bug to you?**

- [x] P2: regular bug that should get fixed

**Use case**
Will save having to consider other typescript edge cases for all rules we write

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1133/typescript-does-not-catch-as-type-via-pattern.

**Comment by nbrahms** [comment]
Note that the solution should apply to type casts regardless of language:

E.g.

```c
(Foo) bar
```
in C / Java

```c
bar.asInstanceOf[Foo]
```
in Scala

**Comment by nbrahms** [comment]
@LewisArdern as a workaround, please try

```
$APP.use(..., <... $SERVEINDEX(...) ...>, ...)
```

**Comment by nbrahms** [comment]
@IagoAbal is this fixed by symbolic propagation?

**Comment by nbrahms** [comment]
@IagoAbal I think this should be matched by symbolic prop.

Cf. https://semgrep.dev/s/lWqG.

**Comment by IagoAbal** [comment]
Unless I'm missing something, making `E` match `E as T` is not something that symbolic propagation will do for you. Deep-expression pattern `<... $SERVEINDEX(...) ...>`, as already suggested, should do the job quite well. Although this rule may benefit from symbolic propagation in case you want to account for intermediate assignments.

We could add an equivalence for type casts too, I guess it makes sense to have special support for it. But is `E as T` the only difficulty here? Shouldn't this perhaps be a taint rule?

**Comment by nbrahms** [comment]
E.g. https://semgrep.dev/s/gGP5

**Comment by nbrahms** [comment]
@LewisArdern please do reopen if this doesn't work for you!
