### ISSUE TITLE
[ruby] certain backslashes break regex matching

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#4991]
**Describe the bug**
Certain character-class sequences in regex break regex matching

**To Reproduce**
https://semgrep.dev/s/WDZE

**Expected behavior**
Regexes match

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1136/[ruby]-certain-backslashes-break-regex-matching.
