### ISSUE TITLE
Allow multiple test case files per yaml file

### ISSUE THREAD

**Issue by timhemel** [semgrep/semgrep#4996]
**Is your feature request related to a problem? Please describe.**
When testing my rules, I am limited to one test case file per yaml file. This can be a problem if I want to test patterns that I cannot duplicate inside a file.

**Describe the solution you'd like**
I would like to be able to have more test cases per yaml file. Ideally, remove the file name based restriction of test files: this is not needed since you can match the correct rule by the rule id. That also allows you to test multiple rules in a single file, although that might involve more complicated parsing of comments like `ok:my-rule-id-1 ruleid:my-other-rule-id-5` and requires rule-ids to be unique.

**Describe alternatives you've considered**
1. match test files with yaml files based on file name, but allow multiple files, such as: detect-eval.1.py, detect-eval.2.py.
2. match all files with all yaml files in the directory and look at the rule-ids (problem: duplicate rule ids across yaml files).
3. put the test files in a directory associated with the yaml file.

**Use case**
I would be able to test rules of patterns that span an entire file, such as rules that check a pattern combined with a specific import statement.

**Additional context**

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1142/allow-multiple-test-case-files-per-yaml-file.
