### ISSUE TITLE
[cli] Line affected by a syntax error should be easier to extract

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#4997]
See https://semgrep.dev/s/6kpK

This is what semgrep-core returns:

> {"matches":...,"errors":[{"rule_id":"-e/-f","error_type":"Syntax error","severity":"warning","location":{"path":"foo.js","start":{"line":1,"col":1,"offset":0},"end":{"line":1,"col":40,"offset":39},"lines":["import {Request, Response} from express"]},"message":"`import {Request, Response} from express` was unexpected"}],"skipped":[],"stats":{"okfiles":0,"errorfiles":1}}

Here ^ the error is pretty clear, and we can easily extract the location of the syntax error.

This is what Semgrep CLI returns:

> {"errors": [{"code": 3, "level": "warn", "message": "\u001b[31m\u001b[41m\u001b[22m\u001b[24m[\u001b[0m\u001b[38;5;231m\u001b[41m\u001b[1m\u001b[24mWARN\u001b[0m\u001b[31m\u001b[41m\u001b[22m\u001b[24m]\u001b[0m Semgrep Core \u2014 Syntax error\nAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep\n\nAt line foo.js:1: `import {Request, Response} from express` was unexpected\n", "path": "foo.js", "type": "Syntax error"}], ...}

Here ^ the error becomes more confusing. The error message could perhaps be more concise (1. Does it matter that this occurred while invoking the Semgrep engine? 2. It may not be a bug but an actual syntax error...), it actually makes you believe that this is definitely a Semgrep bug! Also, the location information isn't as easy to extract, and this doesn't help the Playgroud/Editor to correctly highlight were the syntax error is located.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1145/[cli]-line-affected-by-a-syntax-error-should-be-easier-to-extract.
