### ISSUE TITLE
Semgrep Issue parsing TypeScript functions with object destructuring

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5004]
**Describe the bug**
Semgrep parses various function definitions differently, but there appears to be some unexpected behaviour when dealing with object destructuring values in a function, the following snippet does not get caught for even basic pattern matching examples: 

```
module.exports = function example () {
  return ({ params }: Request, res: Response, next: NextFunction) => {
    const file = params.file
      // ruleid: express-tainted-sendfile
      res.sendFile(path.resolve('ftp/', params.file))
  } 
}
```

**To Reproduce**
* https://semgrep.dev/orgs/LewisArdern/editor/s/LewisArdern:test-express-tainted-sendfile

**Expected behavior**
The above examples should match for both pattern-inside examples from the example on the playground.

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
This will improve TypeScript detection and improve taint mode rules

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1149/semgrep-issue-parsing-typescript-functions-with-object-destructuring.
