### ISSUE TITLE
Getting a summary of the root causes of semgrep parse errors

### ISSUE THREAD

**Issue by clintgibler** [semgrep/semgrep#501]
To better prioritize which semgrep parsing errors to fix first, it would be useful to get a summary of which files failed to parse for which reasons.

## Current State

Currently, running semgrep on a repo will yield a series of errors like this:

~~~bash
$ docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop -f /home/repo/rules.yaml /home/repo/target_dir

sgrep: /home/repo/.../Foo.java: AstGenericError
sgrep: /home/repo/.../Bar.java: AstGenericError
sgrep: /home/repo/.../Baz.java: AstGenericError
~~~

### Problems
* The above prints the same `AstGenericError` even when the root cause is different (see the parsing errors section of https://github.com/returntocorp/enterprise/issues/81).
* Running with `-v` prints a massive amount of debug info that's not easy to manually review. 

## Proposed Solution

It would be nice if there was a separate option, or just using `-v`, that prints out a brief summary of the breakdown of `AstGenericError`s (the `'extra': {'message': THIS_VALUE`).

Example proposed output:
~~~
Fatal Error: Common.Impossible: 3
/home/repo/.../Foo.java
/home/repo/.../Bar.java
/home/repo/.../Baz.java

Handle NewArray with initializer: 2
...
~~~

## Additional context
There may already be a way to do this effectively. If so, please let me know.

**Comment by dlukeomalley** [comment]
Thank you for filing @clintgibler. I think this is a duplicate (a helpfully detailed one!) of #383. If it's ok, I'd like to close this ticket and make sure #383 gets prioritized for this next sprint.
