### ISSUE TITLE
Accept the pattern `{..., Object, ...}` for importing a type in Typescript imports 

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#5012]
**Describe the bug**
Currently, doing `import {Object} from 'lib'` will match regardless of `Object`'s position within the squiggly brackets, but doing `import {..., Object, ...} from 'lib'` throws a Semgrep error.
The latter feels more natural to me given that surrounding something in ellipses is a common way to tell Semgrep "I want this thing and I don't care about the position of it in this structure".

A somewhat relevant Slack discussion will be linked in the comments of the corresponding Linear issue.

**To Reproduce**
https://semgrep.dev/playground/s/enncoded:js-squiggly-bracket-test

**Expected behavior**
Both patterns should match the import

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
What will fixing this bug enable for you?
It's not really going to affect me now that I figured out that you can just do `{Object}`, but I think it would remove confusion for new Javascript/Typescript rule writers who are already experienced in writing Semgrep rules.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1165/accept-the-pattern-object-for-importing-a-type-in-typescript-imports.
