### ISSUE TITLE
Semgrep outputs "0 findings" even when findings are present

### ISSUE THREAD

**Issue by raghavjain3** [semgrep/semgrep#5024]
**Describe the bug**
Semgrep's logs say "0 findings" even though there are findings from the scan

**To Reproduce**
Any Semgrep CI scan on the latest version (that has findings)

**Expected behavior**
Semgrep outputs the correct # of findings from that scan

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
CI

**Use case**
Correct reporting from Semgrep

**Comment by brendongo** [comment]
I could not reproduce: ```semgrep ci --config r/python.lang.correctness.common-mistakes.string-concat-in-list.string-concat-in-list``` on a file with `["abc" "123"]` reported the finding

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1174/semgrep-outputs-0-findings-even-when-findings-are-present.

**Comment by raghavjain3** [comment]
Audit findings are not reported but are documented in the next line of the log output
