### ISSUE TITLE
Included `fixes` in SARIF output

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#5029]
**Is your feature request related to a problem? Please describe.**
> it seems that the SARIF outputed by semgrep doesn't include the [fixes section](https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Ref530139075), making it impossible to use it to generate change suggestions

**Describe the solution you'd like**
--sarif should output the `fixes` field when an autofix is available

This will enable better integration to downstream tools like reviewdog: https://github.com/returntocorp/semgrep/pull/4870

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1176/included-fixes-in-sarif-output.
