### ISSUE TITLE
[JavaScript] object destructuring is not tracked by taint mode

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#5040]
Taint mode do not recognize sources that use destructuring assignment (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)

https://semgrep.dev/s/gGwo

```javascript
function test1(input) {
  const param = input.body.param

  // working
  sink(param)
}

function test2(input) {
  const { param }  = input.body

  // not working
  sink(param)
}
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1183/[javascript]-object-destructuring-is-not-tracked-by-taint-mode.

**Comment by aryx** [comment]
@IagoAbal does this work now? I remember seeing some PRs around better handling of object destructuring.

**Comment by IagoAbal** [comment]
Indeed, this should work now after PR #5192. I will just make a new PR to add this test case and close this issue.
