### ISSUE TITLE
Getting a '/.semgrep' permission denied error after upgrading from 0.57.0 to 0.83.0

### ISSUE THREAD

**Issue by pranavrayakantigs** [semgrep/semgrep#5043]
**Describe the bug**
After doing the semgrep-version upgrade from 0.57.0 to 0.83.0 we are getting '/.semgrep' permission denied error

**Error Logs :**
```
java.lang.RuntimeException: java.lang.RuntimeException: Error encountered while executing the semgrep scan - Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 11, in <module>
    load_entry_point('semgrep==0.83.0', 'console_scripts', 'semgrep')()
  File "/usr/local/lib/python3.7/site-packages/semgrep/__main__.py", line 20, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/semgrep/commands/scan.py", line 692, in scan
    verbose=verbose, debug=debug, quiet=quiet, force_color=force_color
  File "/usr/local/lib/python3.7/site-packages/semgrep/util.py", line 85, in set_flags
    USER_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.7/pathlib.py", line 1273, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.semgrep'
```

**Expected behavior**
Semgrep-Scan should get finish without any errors

**What is the priority of the bug to you?**
- [x] P0: blocking adoption of Semgrep 

**Environment**
running on docker image

**Use case**
What will fixing this bug enable for you? to detect the vulnerabilities on Java Projects

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1184/getting-a-semgrep-permission-denied-error-after-upgrading-from-0570-to.

**Comment by pranavrayakantigs** [comment]
> This issue is synced in Linear at https://linear.app/r2c/issue/PA-1184/getting-a-semgrep-permission-denied-error-after-upgrading-from-0570-to.

I don't have access to this link...

**Comment by pranavrayakantigs** [comment]
Hello @noraj , I see you have resolved a similar kind of error [3379] (https://github.com/BlackArch/blackarch/issues/3379), could you please assist us in resolving this one?

**Comment by brendongo** [comment]
@pranavrayakantigs what environment are you running semgrep docker image in and how are you invoking it? Our published docker image should have the necessary permissions for `/.semgrep`

**Comment by pranavrayakantigs** [comment]
> @pranavrayakantigs what environment are you running semgrep docker image in and how are you invoking it? Our published docker image should have the necessary permissions for `/.semgrep`


Currently, we are seeing this issue in production. During runtime, we are invoking this through a bash script, and fetching below images from docker-hub. do you feel we miss anything in below setup ?

```docker
FROM REDACTED/dx/py-eng/python-images/python3.7-rhel7-prod:current

RUN yum -y install java-11-openjdk-devel curl && \
    yum clean all && \
    pip install -U pip && \
    pip install attrs

COPY --from=REDACTED/returntocorp/semgrep:0.83.0 /usr/local/bin/semgrep-core /usr/local/bin/semgrep-core
COPY --from=REDACTED/returntocorp/semgrep:0.83.0 /semgrep /semgrep

RUN python3 -m pip install /semgrep
RUN chmod -R 777 /usr/local/lib/python3.7/*

ENV Variables  REDACTED


COPY semgrep /semgrep
COPY apps /apps
```

**Comment by brendongo** [comment]
I'm assuming the USER in REDACTED/dx/py-eng/python-images/python3.7-rhel7-prod:current does not have root privileges. You can add a `RUN mkdir /.semgrep && chmod -R 777 /.semgrep`  or letting semgrep run as sudo: `USER root`

**Comment by alexandre** [comment]
??
