### ISSUE TITLE
Document how to set up semgrep dev environment

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#505]
Should have a document that makes it easy for a new developer to get a locally compiled instance of semgrep and semgrep-core running.

This includes:
- [x] dependencies to install like ocaml, opam, etc
- [x] how to install pfff
- [x] how to install semgrep-core
- [x] how to install semgrep

**Comment by mschwager** [comment]
Pinging on the details here.

Seems like we could unify `CONTRIBUTING.md` and `docs/development.md`, although I'm not sure what's missing from those to complete this task.

**Comment by nbrahms** [comment]
FWIW, I was trying to set up development this morning, and was confused that there wasn't information in CONTRIBUTING.md 🤷

**Comment by DrewDennison** [comment]
FYI, CONTRIBUTING.md is a special GH file that shows up in the UI for new contributors

**Comment by brendongo** [comment]
Updated details.

**Comment by aryx** [comment]
I think docs/development.md covers most of nathan's needs.
What it may not cover is the trick around pfff which is a submodule of semgrep,
and the trick to be able to run the big regression tests (e.g., semgrep-rules) with the latest semgrep-core (you need to make install in semgrep-core, cd ../semgrep; make test

**Comment by brendongo** [comment]
I'll add a section on testing then should be good to close this
