### ISSUE TITLE
A parameter being passed directly into java.net.URL function most likely lead to SSRF.   .mvn/wrapper/MavenWrapperDownloader.java

### ISSUE THREAD

**Issue by patpatpat123** [semgrep/semgrep#5057]
**Describe the bug**
A parameter being passed directly into java.net.URL function most likely lead to SSRF.

**To Reproduce**
https://github.com/patpatpat123/springvaultcve
The CI/CD tool will download a maven wrapper in order to execute the CI CD pipeline, which is just a simple mvn clean install

Upon completion, the pipeline will run semgrep.

I look at the report, and this is always being flagged.

**Expected behavior**
May I ask why semgrep would flag this?
How to resolve this please?
Or if it is not possible to resolve this, can we disable semgrep for file which are not part of my repo, but what seems to be downloaded by the CI CD pipeline?

Thank you

**Screenshots**
Description

A parameter being passed directly into java.net.URL function most likely lead to SSRF.
Files

.mvn/wrapper/MavenWrapperDownloader.java
L:97
Code

```
private static void downloadFileFromURL(String urlString, File destination) throws Exception {
        if (System.getenv("MVNW_USERNAME") != null && System.getenv("MVNW_PASSWORD") != null) {
            String username = System.getenv("MVNW_USERNAME");
            char[] password = System.getenv("MVNW_PASSWORD").toCharArray();
            Authenticator.setDefault(new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
            });
        }
        URL website = new URL(urlString);
        ReadableByteChannel rbc;
        rbc = Channels.newChannel(website.openStream());
        FileOutputStream fos = new FileOutputStream(destination);
        fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);
        fos.close();
        rbc.close();
    }
```

**What is the priority of the bug to you?**

- [x ] P2: regular bug that should get fixed

**Environment**
official binary

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1191/a-parameter-being-passed-directly-into-javaneturl-function-most-likely.

**Comment by patpatpat123** [comment]
Hmm, looked at the link, not sure about the relevancy

**Comment by brendongo** [comment]
@patpatpat123 that is for internal tracking mostly :D 

How are you running semgrep? You can run semgrep before you install dependencies or you can add `.mvn` to a .semgrepignore file or you can execute semgrep with `--exclude .mvn/`

**Comment by patpatpat123** [comment]
Understood! Thanks! Trying the proposed solutions and will update the result

**Comment by brendongo** [comment]
@patpatpat123 did this solve your problem for you?

**Comment by patpatpat123** [comment]
Apologies for the lates reply. Both the exclude and the ignore files worked.
Thanks a lot for your time helping on this!
Closing
