### ISSUE TITLE
Semgrep runs rules against files specified in .semgrepignore when passed explicitly

### ISSUE THREAD

**Issue by patrickpichler** [semgrep/semgrep#5058]
**Describe the bug**
When running semgrep in a folder containing a `.semgrepignore` and specifying a file on the command line
which is present in the ignore file, semgrep will print that it will ignore the file, but then executing its rules anyway. 

**To Reproduce**
* Clone the git repo from https://git.sr.ht/~patrickpichler/semgrep-ignore-bug
* If you have docker installed run `./command.sh`
* If not run `semgrep --config p/security-audit --config p/ci -o report.sarif -- Test.java`

**Expected behavior**
`Test.java` should not get scanned, since it is listed in the `.semgrepignore file.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
The issue occurs with both docker and running the official binary

**Use case**
What will fixing this bug enable for you?
We want to use semgrep as part of our CI pipeline. The semgrep-agent doesn't fulfill all our needs,
so we resort to running something like `semgrep --config <some rules> -- $(git diff master...HEAD)` to retrieve
the list of files changed for a certain branch. 

Sadly semgrep wrongfully detects our Jenkinsfile as java and complains about using the `==` operator 
to compare strings. It is a problem in java, but totally fine in groovy. To work around this, we decided to ignore
all Jenkinsfiles in our project via `.semgrepignore`. 

The bug now causes our pipeline to report false positives in the jenkinsfile. 

One workaround would be to use a `nosemgrep` in all the jenkinsfiles, but this doesn't scale really well.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1192/semgrep-runs-rules-against-files-specified-in-semgrepignore-when.

**Comment by ievans** [comment]
hi @patrickpichler -- this looks like a duplicate of https://github.com/returntocorp/semgrep/issues/4978, would you mind taking a look?

(tldr: we have recently finished porting all semgrep-agent functionality into the CLI--we'd recommend switching your invocation to `semgrep ci` which will perform the git-diff-aware subtraction automatically. would be very interested in any feedback about whether that meets your needs)

**Comment by patrickpichler** [comment]
Hey,
Thank you for the fast response :slightly_smiling_face: 
You are right, this is a duplicate, I must have somehow missed it :sweat_smile: 
I will close this issue and thank you for pointing out `semgrep ci`, I will have a look :slightly_smiling_face:
