### ISSUE TITLE
Allow metavariable-pattern to inherit the variable environment from the parent

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5060]
**Is your feature request related to a problem? Please describe.**
Currently when you write a taint rule, you are limited from being able to really dig deep into the 'source' through metavariable-patterns e.g. I want to know if the source is the start of a query, after a variable, or is after a literal string, etc.

If we allowed metavariable-pattern to inherit the variable environment from the parent formula, then we could easily include the source into our validation cases.

 if you could write <... $SOURCE ...> inside a metavariable-pattern and know exactly you are working with the source, and not any $VARIABLE

Example of failing due to current metavariable-pattern: https://semgrep.dev/s/LewisArdern:express-open-redirect 

**Describe the solution you'd like**
We should allow in taint-mode for the metavariable-pattern to inherit the variable environment from the parent formula, then we could easily include the source into our validation cases.

If you look at https://semgrep.dev/s/LewisArdern:express-open-redirect  if we had the ability to access the source through something like <... $SOURCE ...> we could potentially ensure that we do not introduce false positives, currently the pattern-nots are not correct, and will introduce false negatives and false positives. 

**Describe alternatives you've considered**
Hacky hacky https://semgrep.dev/s/rNKW (not useful for most people)

**Use case**
It will enable rule-writers to have a better chance of removing false positives from their rules because you can really ensure the value comes from the source we are capturing

**Additional context**

The reason why  "..."+$REQ matches 

res.redirect("https://google.com/"+req.query.url)

Is because $REQ is in metavariable-pattern so it's not the same mvar used in pattern-sources and it's binding to req.query.url.
But if you try to match "..."+$REQ.query this does not work because $REQ.query cannot match req.query.url , it's the same as trying to match $REQ against req.query and .query against .url, .query and .url cannot be matched.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1194/allow-metavariable-pattern-to-inherit-the-variable-environment-from. _Note_: this link is for r2c use only and is not accessible publicly.
