### ISSUE TITLE
Eliminate fatal to-dos from C# parser

### ISSUE THREAD

**Issue by jn94501** [semgrep/semgrep#5068]
[ERROR] Semgrep Core — Fatal errorAn error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrepAt line src/WinSW.Core/Download.cs:1: Common.Impossible====[ BEGIN error trace ]====Raised at Parse_csharp_tree_sitter.type_ in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2211, characters 6-22Called from Stdlib__option.map in file "option.ml", line 24, characters 57-62Called from Parse_csharp_tree_sitter.explicit_parameter in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2155, characters 11-46Called from Parse_csharp_tree_sitter.formal_parameter_list in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 1960, characters 11-43Called from Parse_csharp_tree_sitter.parameter_list in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2285, characters 16-43Called from Parse_csharp_tree_sitter.statement in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 1752, characters 15-36Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23Called from Parse_csharp_tree_sitter.block in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 807, characters 11-38Called from Parse_csharp_tree_sitter.statement in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 1799, characters 15-27Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Parse_csharp_tree_sitter.block in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 807, characters 11-38Called from Parse_csharp_tree_sitter.function_body in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2127, characters 23-36Called from Parse_csharp_tree_sitter.declaration in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2875, characters 15-35Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Stdlib__list.map in file "list.ml", line 92, characters 32-39Called from Parse_csharp_tree_sitter.declaration_list in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2449, characters 11-42Called from Parse_csharp_tree_sitter.class_interface_struct in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2586, characters 35-58Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23Called from Parse_csharp_tree_sitter.declaration_list in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2449, characters 11-42Called from Parse_csharp_tree_sitter.namespace_declaration in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2549, characters 39-62Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23Called from Parse_csharp_tree_sitter.compilation_unit in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2535, characters 15-64Called from Parse_csharp_tree_sitter.parse.(fun) in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 3007, characters 12-36Called from Parse_tree_sitter_helpers.wrap_parser in file "src/parsing/tree_sitter/Parse_tree_sitter_helpers.ml", line 155, characters 13-29Called from Parse_target.run_parser in file "src/parsing/Parse_target.ml", line 100, characters 18-24Re-raised at Parse_target.run in file "src/parsing/Parse_target.ml", line 193, characters 26-65Called from Parse_target.parse_and_resolve_name_use_pfff_or_treesitter in file "src/parsing/Parse_target.ml", line 359, characters 30-60Called from Parse_with_caching.parse_generic.(fun) in file "src/runner/Parse_with_caching.ml", line 105, characters 12-80Called from Parse_with_caching.cache_computation.(fun) in file "src/runner/Parse_with_caching.ml", line 58, characters 20-24Called from Parse_with_caching.parse_generic in file "src/runner/Parse_with_caching.ml", line 89, characters 4-1023Called from CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 31, characters 17-27Re-raised at CamlinternalLazy.force_lazy_block in file "camlinternalLazy.ml", line 36, characters 4-11Called from Common.with_time in file "src/pfff/commons/Common.ml", line 215, characters 12-16Called from Match_search_rules.matches_of_patterns in file "src/engine/Match_search_rules.ml", line 264, characters 8-67Called from Match_search_rules.matches_of_xpatterns in file "src/engine/Match_search_rules.ml", line 601, characters 6-55Called from Match_search_rules.matches_of_formula in file "src/engine/Match_search_rules.ml", line 931, characters 12-63Called from Match_search_rules.check_rule in file "src/engine/Match_search_rules.ml", line 961, characters 4-74Called from Stdlib__list.map in file "list.ml", line 92, characters 20-23Called from Match_search_rules.check in file "src/engine/Match_search_rules.ml", line 988, characters 2-275Called from Match_rules.check in file "src/engine/Match_rules.ml", line 63, characters 4-88Called from Run_semgrep.semgrep_with_rules.(fun) in file "src/runner/Run_semgrep.ml", line 460, characters 13-182Called from Run_semgrep.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file "src/runner/Run_semgrep.ml", line 305, characters 25-33Called from Common.set_timeout in file "src/pfff/commons/Common.ml", line 1420, characters 12-16Re-raised at Common.set_timeout in file "src/pfff/commons/Common.ml", line 1437, characters 6-13Called from Run_semgrep.timeout_function in file "src/runner/Run_semgrep.ml", line 148, characters 4-73Called from Stdlib__fun.protect in file "fun.ml", line 33, characters 8-15Re-raised at Stdlib__fun.protect in file "fun.ml", line 38, characters 6-52Called from Memory_limit.run_with_memory_limit in file "src/system/Memory_limit.ml", line 79, characters 6-62Called from Run_semgrep.iter_targets_and_get_matches_and_exn_to_errors.(fun) in file "src/runner/Run_semgrep.ml", line 302, characters 17-846=====[ END error trace ]=====

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1202/[error]-semgrep-core-fatal-erroran-error-occurred-while-invoking-the. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
```
Common.Impossible
====[ BEGIN error trace ]====
Raised at Parse_csharp_tree_sitter.type_ in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2211, characters 6-22
```
points to this line: https://github.com/returntocorp/semgrep/blob/44d09a32dd6d7e1e88a845ad70c65003c75122c0/semgrep-core/src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml#L2111

This is some construct that's not supported in a C# source file. It would be best to support it, followed by being able to ignore such constructs.

I'm setting the issue title to reflect this.

**Comment by aryx** [comment]
cc @Sjord

**Comment by Sjord** [comment]
@mjambon You reference line 2111, but the error message says 2211. Because of `Raised at Parse_csharp_tree_sitter.type_`, I expect this line to trigger the error:

https://github.com/returntocorp/semgrep/blob/44d09a32dd6d7e1e88a845ad70c65003c75122c0/semgrep-core/src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml#L2311

@jn94501 Could you perhaps provide the file that failed to parse, src/WinSW.Core/Download.cs? I tried [this file](https://github.com/winsw/winsw/blob/v3/src/WinSW.Core/Download.cs) but I couldn't reproduce it.

**Comment by Sjord** [comment]
I could reproduce it, with the following invalid C# code:

```
public class Foo {
    public void Foo(var a) {
    }
}
```

This gives the same error as in the report:

```
test.cs:1:0: "Fatal error": Common.Impossible
Raised at Parse_csharp_tree_sitter.type_ in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2311, characters 6-22
Called from Stdlib__option.map in file "option.ml", line 24, characters 57-62
Called from Parse_csharp_tree_sitter.explicit_parameter in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2227, characters 11-46
Called from Parse_csharp_tree_sitter.formal_parameter_list in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2026, characters 11-43
Called from Parse_csharp_tree_sitter.parameter_list in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2363, characters 16-43
Called from Parse_csharp_tree_sitter.declaration in file "src/parsing/tree_sitter/Parse_csharp_tree_sitter.ml", line 2968, characters 15-36
```

It is invalid code because the `var` in the argument is an implicit type, and arguments are supposed to have explicit types. So this does not really seem like a parsing bug, but maybe the error message could be a bit better.

**Comment by IagoAbal** [comment]
Should Semgrep be rejecting any code that parses? There is a compiler with a type checker whose job is that one already. I would personally put there some "ERROR" or "TODO" AST node, but I would allow the file to be processed.
