### ISSUE TITLE
Flag to make audit findings visible in semgrep ci output

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#5069]
**Is your feature request related to a problem? Please describe.**
`semgrep ci` hides the findings from audit column rules. While for PR scans it makes sense to hide these, for full scans users might want to export the finding data (--json)

**Describe the solution you'd like**
Expose a `--show-audit-findings` flag that shows the non-blocking audit rules in the output of `semgrep ci`

** Additional Context **
Right now semgrep.dev rule board has three columns: audit, non-blocking notify, blocking. For now `semgrep ci` only includes the blocking findings in the output. We will want to have non-blocking notify always visible in the output and this flag will be to control the visibility of the audit column.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1203/flag-to-make-audit-findings-visible-in-semgrep-ci-output. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
@raghavjain3 brought up that we might want to just make all findings visible by default
