### ISSUE TITLE
semgrep ci does not support --severity flag

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#5075]
**Describe the bug**
It looks like semgrep 0.87 doesn't handle --severity when using ci mode
https://github.com/returntocorp/semgrep-action/issues/135

**To Reproduce**
```
semgrep ci --severity WARNING
Usage: semgrep ci [OPTIONS]

Error: No such option: --severity
```

**Expected behavior**
It should ?

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1208/semgrep-ci-does-not-support-severity-flag. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
@Gby56 we do envision `semgrep ci` to be mostly used with semgrep.dev where users can configure what rules run.

We do want to lean towards only one way of doing things if possible. Is there a reason you need to filter to warning rules in the command line level instead of only having warning rules in the rule board to begin with?

**Comment by Gby56** [comment]
Hi Brendon ! I mean I mostly use semgrep offline that's why, and I now maintain https://github.com/azu/security-alert/issues/21 to have our PR scans commented with "okay" feedback (nowhere near as good as semgrep.dev, don't worry)
I hope to keep using semgrep, but this is as long as r2c promises to keep SARIF output for diff scans then... otherwise I'd have to go as far as scanning twice and diffing SARIFs and so on...

I like the rule configuration system on semgrep.dev, and for now it doesn't even support severity filtering, you only get to choose "ruleset x block, ruleset y comments" but not by severity, which is an actual good feature to have, reusing the same ruleset but separate by severity is a valid use case imo.

This filtering by severity is a "minor" inconvenience given that it means scanning with all rules, but only output some findings in a  PR, but yes it would be cool to also have that choice 😟

**Comment by Gby56** [comment]
@brendongo Hi !
Do you think that will be supported in the future ?... 🙏

**Comment by brendongo** [comment]
@Gby56 sorry for the late reply I have been on vacation :D 

I don't think we will be including this functionality in semgrep cli but we will be improving the rule configuration system on semgrep.dev to better support this in the future

**Comment by markrian** [comment]
Currently `semgrep ci --help` suggests that `--severity` is a supported option, so perhaps that could be removed, if it's not supported?
