### ISSUE TITLE
Docker container running as root - issues with Kubernetes

### ISSUE THREAD

**Issue by malexmave** [semgrep/semgrep#5081]
**Is your feature request related to a problem? Please describe.**
Between v0.85.0 and v0.86.0, the default user of the semgrep docker container changed from semgrep to root.

```bash
$ docker run --rm -v "${PWD}:/src" --entrypoint whoami returntocorp/semgrep:0.85.0
semgrep
$ docker run --rm -v "${PWD}:/src" --entrypoint whoami returntocorp/semgrep:0.86.0
root
```

The change seems to have been introduced as part of merging #4777 in commit https://github.com/returntocorp/semgrep/commit/26e7cc6fe8689ef8d9b21c7d41281b3423fa3b98 (I could not find the exact commit inside #4777 that made this change on short notice, as my git-fu is insufficient 😁).

This causes issues when running the container in a Kubernetes cluster that is configured to disallow images running as root (`runAsNonRoot: true`) - in this case, the semgrep container will not start.

I did not find anything in the linked PR that would explain why the default user was changed. Is there a particular reason why this change was made? It causes [breakage in our secureCodeBox integration](https://github.com/secureCodeBox/secureCodeBox/pull/1127), where we are trying to run as many containers as non-root as possible. If this change was intentional and cannot be reverted, we'll work around it, but I wanted to ensure that this isn't just a mistake that happened somewhere along the way, since running containers as root is [something that semgrep itself will warn about](https://semgrep.dev/r?q=docker+root) 😁.

**Describe the solution you'd like**
Either revert the change of the default Docker user, or tell me that this was intentional (in which case it's fine and I'll work around it).

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1214/docker-container-running-as-root-issues-with-kubernetes. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
@malexmave the change was made so that the semgrep docker image can be used in CI/CD pipelines since they all use the user to setup the image / inject the source code etc. So definitely intentional 😅

**Comment by malexmave** [comment]
Okay, great - thanks for the info, in that case we'll figure out how to work with this on our end :).
