### ISSUE TITLE
Make semgrep (and core) buildable without sudo

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#5126]
### `semgrep-core/src/ocaml-tree-sitter-core/scripts/install-tree-sitter-lib`

```
  # When building from source on homebrew sudo is not allowed
  # but also not needed
  if [[ -z "${HOMEBREW_SYSTEM+x}" ]]; then
    sudo make install
  else
    # brew is present
    make install
  fi
```

this sudo requirement is _undesirable_

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1228/make-semgrep-and-core-buildable-without-sudo. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by underyx** [comment]
Closing as duplicate of https://github.com/returntocorp/semgrep/issues/2956
