### ISSUE TITLE
Range of matched statement patterns is wrong

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#513]
https://sgrep.live/54X?version=experimental

Why `$VAL = '*' ` is not strictly respected and it matches everything else as if `$VAL` is just an un assigned metavar. The matching should stop at `res.set('access-control-allow-origin', x);`

**Comment by nbrahms** [comment]
@aryx Can you confirm that this is due to https://github.com/returntocorp/semgrep/issues/430 ?

**Comment by aryx** [comment]
Yes, probably.

**Comment by DrewDennison** [comment]
FYI @aryx is prioritizing this next

**Comment by DrewDennison** [comment]
this should be fixed in 0.9.0 !
