### ISSUE TITLE
Semgrep Should Match JavaScript Object Property in Taint mode

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5140]
**Describe the bug**
Object property assignment can lead to prototype pollution, semgrep does not capture this in taint mode https://semgrep.dev/s/lewisardern:remote-property-injection e.g.

```
myObj[req.body] = ...
```

**To Reproduce**
https://semgrep.dev/s/lewisardern:remote-property-injection

**Expected behavior**
It should capture the object value where $REQ enters it

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1248/semgrep-should-match-javascript-object-property-in-taint-mode. _Note_: this link is for r2c use only and is not accessible publicly.
