### ISSUE TITLE
Sanitizers appear to not work in Java

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#5141]
**Describe the bug**
In [this example](https://semgrep.dev/s/P1L0), I am trying to remove the second case with the `ok` annotation whenever it looks like a transformation of any kind is done on the string. However, it still reports the line with FileInputStream, which is unexpected.

**To Reproduce**
https://semgrep.dev/s/P1L0

**Expected behavior**
I'm not sure if I'm doing something incorrectly, but it seems to me like this should work. This is not sanitization by side-effect nor does it involve conflicting sanitizers/sources/sinks. Unless I'm reading it incorrectly.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

Would be nice to have by end of next week.

**Use case**
This will let us remove FPs from a new rule that gives matches some findings found by other tools.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1250/sanitizers-appear-to-not-work-in-java. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Try using this as `pattern-sources`:

```java
pattern-sources:
  - patterns:
      - pattern-either:
          - pattern: |
              @RequestMapping(...) $RETURNTYPE $METHODNAME(..., @$ANNOTATION
              $TYPE $PARAMETER, ...) {
                ...
              }
          - pattern: |
              @RequestMapping(...) $RETURNTYPE $METHODNAME(...,
              @$ANNOTATION(...) $TYPE $PARAMETER, ...) {
                ...
              }
          - pattern: |
              $RETURNTYPE $METHODNAME(..., @RequestParam $TYPE $PARAMETER) {
                ...
              }
          - pattern: >
              $RETURNTYPE $METHODNAME(..., @RequestParam($LOOKUP) $TYPE
              $PARAMETER) {
                ...
              }
      - focus-metavariable: $PARAMETER
```

**Comment by IagoAbal** [comment]
Although you'll need to wait for Semrep 0.92.0 to be the default version in the Editor!
