### ISSUE TITLE
[ruby] Regex interpolations not caught by wildcard matches

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#5147]
**Describe the bug**
Regex interpolations should match wildcard regex patterns.

**To Reproduce**
https://semgrep.dev/s/1J9l

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1251/[ruby]-regex-interpolations-not-caught-by-wildcard-matches. _Note_: this link is for r2c use only and is not accessible publicly.
