### ISSUE TITLE
Make language extensions configurable

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#5160]
Currently if you want to scan a folder for terraform code (for example) it only works with `.tf` files. To support `.hcl` files, it requires making a patch upstream to semgrep and waiting for a new release. Could we make this overridable without having to edit code?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1255/make-language-extensions-configurable. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by vighnesh-kadam** [comment]
Hii im new to all this , can you please explain what needs to be done in this issue in easier words?
