### ISSUE TITLE
Can't match private member functions (typescript)

### ISSUE THREAD

**Issue by JosiahOne** [semgrep/semgrep#5162]
**Describe the bug**
Rules that try to match on `private` or `private static` member functions fail to match. The non-private variants seem fine, as does the parsing stage.

**To Reproduce**
https://semgrep.dev/s/josiahone:failing_private_member

**Expected behavior**
Rules should be able to match on private member functions in classes.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
We are trying to write a flexible promise-related rule that currently doesn't work because we can't match inside private member functions. Fixing this will allow us to deploy our new rule.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1256/cant-match-private-member-functions-typescript. _Note_: this link is for r2c use only and is not accessible publicly.
