### ISSUE TITLE
Add environment variable for disabling version checks

### ISSUE THREAD

**Issue by djmattyg007** [semgrep/semgrep#5163]
**Is your feature request related to a problem? Please describe.**
Right now I have to pass `--disable-version-check` manually a lot of the time and in many places because I don't want semgrep to worry about keeping itself up to date (I have other things to take care of that, such as Renovatebot).

**Describe the solution you'd like**
It should be possible to disable version checks once by setting an environment variable. Something like `SEMGREP_VERSION_CHECKS=off`.

**Describe alternatives you've considered**
Continuing to do what I'm already doing - pass the existing flag everywhere.

**Use case**
Unnecessary network traffic is cut down. This also makes it more palatable to run in corporate environments, where these version checks may simply always fail.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1257/add-environment-variable-for-disabling-version-checks. _Note_: this link is for r2c use only and is not accessible publicly.
