### ISSUE TITLE
Ellipsis operator does not work as expected on for loop detection C++

### ISSUE THREAD

**Issue by ChakirBelhaj** [semgrep/semgrep#5164]
**Describe the bug**
Semgrep Ellipsis operator fails inside a for loops semicolon's where the iterators are defined.

**To Reproduce**
Below the given pattern.

```
id: cpprules-for-loop
pattern: for (...) {...}
message: for loop found
languages:
  - c++
severity: WARNING
```

Below the code to be scanned by semgrep.
```
int main() {
    if(5 + 5 == 10){
        return 0;
    }

        for (int i = 1; i <= 5; ++i) {
        cout << i << " ";
        return 0;
    }
    return 0;
}
```
**Expected behavior**
Expected behavior is the recognition of the for loop with any statements inside the semicolons.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Semgrep playground

**Use case**
Ability to recognize any for loops inside code.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1258/ellipsis-operator-does-not-work-as-expected-on-for-loop-detection-c. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
should work in the next release.
