### ISSUE TITLE
Difficult to tell what rules were actually applied in auto mode

### ISSUE THREAD

**Issue by djmattyg007** [semgrep/semgrep#5165]
**Is your feature request related to a problem? Please describe.**
If there is a rule that I think should be applied with auto mode, but no problems related to that rule are being displayed, it's difficult for me to tell why because nothing actually tells me what rules are being applied.

**Describe the solution you'd like**
Some way of previewing what rules are actually applied when using auto mode. This would let me add extra rules if necessary, or raise an issue/start a discussion about why a particular rule isn't being included.

**Describe alternatives you've considered**
Not using auto mode and manually specifying all rules. This is tedious and cumbersome because there is no way to supply command-line arguments with a config file.

**Use case**
I can better understand what rules are being applied, so I can start determining what gaps there are, so I can hopefully start contributing more to the detection algorithms used to apply rules and to start contributing new rules.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1259/difficult-to-tell-what-rules-were-actually-applied-in-auto-mode. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by djmattyg007** [comment]
Please stop marking this as stale, because it isn’t.

**Comment by djmattyg007** [comment]
Not stale.

**Comment by djmattyg007** [comment]
Not stale.

**Comment by djmattyg007** [comment]
Not stale.

**Comment by djmattyg007** [comment]
Lol what on earth is this

**Comment by djmattyg007** [comment]
I literally can’t reopen it. Thanks I guess, at least some code looked at my messages.
