### ISSUE TITLE
Support Ignoring a given rule on a given line using a comment annotation 

### ISSUE THREAD

**Issue by HariSekhon** [semgrep/semgrep#5166]
**Is your feature request related to a problem? Please describe.**
Semgrep can raise false positive alerts that may be samples or comments or otherwise should be ignored

**Describe the solution you'd like**
Ability to ignore false positives via a comment annotation eg.

```
# semgrep: disable=<some-rule>
sample_line_or_comment_triggering_this_rule
```

This is a very standard solution used in many other tools.

**Describe alternatives you've considered**
Disabling entire rules or rule sets is a much worse solution that reduces coverage

**Use case**
Tuning semgrep to real world usages by ignoring false positives and reducing noise

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1261/support-ignoring-a-given-rule-on-a-given-line-using-a-comment. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by HariSekhon** [comment]
Ignore, found in doc here, not sure if this is new or I just missed it before:

https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep
