### ISSUE TITLE
Improve Semgrep memory consumption

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#5172]
From https://github.com/silentsignal/SemGWT/:

One weakness of Semgrep is that it can easily consume (almost) boundless memory. Because of this, rules must be created and tested carefully, and the process needs special parameters for larger files.

In particular, defining code block patterns with ellipses inside (e.g. function $FOO(){var $X; ...}) can have detrimental effect on performance when parsing large inputs, so you should try to avoid this and focus on sequences of statements.

Semgrep has both size and time limits by default. To analyze a 10MB JavaScript file, I had to disable timeouts, and set the size limit above the size of the file:

--timeout 0 \
--max-target-bytes 20 MB
Additionally, to prevent OOM Killer intervention (or system freeze...) it is recommended to set the memory limit. In the above case the semgrep process can easily consume 10 gigabytes of memory:

--max-memory 10240
File sizes are limited by default for a reason: memory requirement of parsing a single large file or orders of magnitude bigger than parsing the same code split into multiple files. It is highly recommended to split the input multiple files during preprocessing. The theoretical cost of this is losing inter-file references, but this shouldn't be a problem in the case of GWT.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1270/improve-semgrep-memory-consumption. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by anotherbridge** [comment]
Are there any news on this issue? 

I am currently struggling with the memory performance of Semgrep.

I ran it with the following flags:
```
--timeout 0
--max-target-bytes 15MB
--max-memory 128
```

Yet on a machine that has 4 GB of memory Semgrep wasn't able to finish due to an OOM Killer.

Thus I would like to know whether there is any progress on this issue?

**Comment by emjin** [comment]
What version of Semgrep are you running? We've made some progress, but this is not a priority right now

**Comment by anotherbridge** [comment]
> What version of Semgrep are you running? We've made some progress, but this is not a priority right now

When I tested I ran version 0.97.0.

**Comment by emjin** [comment]
Is there anything you can share about your case? Obviously a full reproduction (rules/files you're running with) would be best. Failing that, some information that could help is

- Rules you're running with
- File stats (number, size, languages)
- The contents of the largest files

It can also be helpful to us if you can "binary search" through your repo to find out what the conditions are that trigger the OOM.

That being said, I can't guarantee that we'll be able to solve this, since it isn't our current priority. The more information you provide, the more likely it is, but I understand that it can be work to create a shareable reproduction. We appreciate whatever details you provide!

**Comment by anotherbridge** [comment]
I tried running on many different repos and files. Even on a file with just a few hundred KB the issue occured. However, I used the full ruleset. When I tried going for the automatic detection of the rules the kill occured later during the run, but I still got that problem.

**Comment by xm-discover-bot-admin** [comment]
With the most recent release (0.106.0) a lot of these problems have been fixed (I didn't fix them myself, I've just noticed fewer OOM errors on large projects).

**Comment by emjin** [comment]
I'm glad to hear that! I was just about to post an update here that we did some work to address the low-hanging fruit for memory consumption, which should now be available to both action and CLI users. See the 0.104.0 and 0.105.0 changelogs for details on what happened.

**Comment by emjin** [comment]
Also thank you to all the details provided; they helped speed up our understanding of the issue and give confidence that our changes would be broadly impactful.
