### ISSUE TITLE
Kotlin: Pattern parse error

### ISSUE THREAD

**Issue by dpnishant** [semgrep/semgrep#5180]
**Describe the bug**
Discovered a potential bug in the pattern parser for Kotlin language. 
Refer slack thread: https://r2c-community.slack.com/archives/C018NJRRCJ0/p1652110473552519

**To Reproduce**
* Working as expected: https://semgrep.dev/s/dpnishant:kotlin-parsing-bug-1-pass
* Not working as expected: https://semgrep.dev/s/dpnishant:kotlin-parsing-bug-1-fail

**Expected behavior**
The pattern should have matched the Kotlin class with primary constructor arguments

**Screenshots**
Not available. _Links shared above should be self-explanatory_

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep 0.91.0 on macOS via Homebrew (similar behavior observed on semgrep.dev playground as well.

**Use case**
Required for writing rules for Kotlin with better accuracy

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1272/kotlin-pattern-parse-error. _Note_: this link is for r2c use only and is not accessible publicly.
