### ISSUE TITLE
Java: Type inference support in for loop

### ISSUE THREAD

**Issue by sfc-gh-nsfard** [semgrep/semgrep#5181]
**Describe the bug**
Type inference does not seem to propagate in for loops. There may also be an issue with type inference when using type parameters (`<T>`).

**To Reproduce**
https://semgrep.dev/s/sfc-gh-nsfard:java_type_parameter_bug

**Expected behavior**
In the above example, I'd expect to see two findings, not one

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Local

**Use case**
This is for code querying. I'm currently working on a recursive usage search for method calls

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1276/java-type-inference-support-in-for-loop. _Note_: this link is for r2c use only and is not accessible publicly.
