### ISSUE TITLE
Investigate slow semgrep perf

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#520]
Scanning over https://github.com/sobolevn/python-code-disasters has my CPU pinned at 100% for 2 hours.

```
docker run --rm -v $(pwd):/home/repo returntocorp/sgrep:0.4.9 --json --config=https://sgrep.live/c/r/r2c --skip-pattern-validation
```

Adding as a performance investigation / something to add to our perf regression suite.

**Comment by dlukeomalley** [comment]
@nbrahms has hit some similar performance pains with semgrep in Bento recently. Not quite this bad, but perhaps further test cases for us to follow-up on.

**Comment by DrewDennison** [comment]
created https://github.com/returntocorp/semgrep/issues/664 as the root cause of this.

Isaac also discussed `pattern-inside` being slow with a user on slack
