### ISSUE TITLE
Static methods from imported classes are not detected

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#521]
**Describe the bug**
When writing a pattern, does not detect static methods called directly from an imported class.

**To Reproduce**
Here is what I want to write:
https://sgrep.live/jeY

I tried with the fully-qualified path, too:
https://sgrep.live/1vw

But it does work with a metavariable:
https://sgrep.live/9JY

When I dump the AST, it looks like it doesn't check to see if Cipher is an imported entity.

**Comment by dlukeomalley** [comment]
@minusworld @clintgibler @mschwager Have any of you run into this issue recently? Looking through older tickets and seeing if there are any that should be prioritized again. Thank you!

**Comment by mschwager** [comment]
I think this was just fixed: #733

**Comment by dlukeomalley** [comment]
Indeed it is fixed on develop. Closing, thanks @mschwager for the pointer!
