### ISSUE TITLE
generic mode: Offer an option to set the maximum number of lines matched by an ellipsis '...'

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#5211]
There is a default limit of 10 lines to avoid bad performance. However, the performance isn't always bad and sometimes it's useful to:
- match a large number of lines, say 200
- match at most one line

The current solution for matching more than 10 lines is to repeat `...` e.g. `... ... ... ... ...` for a limit of 50 lines. There's no solution to matching fewer than 10 lines.

The proposed feature is to offer an option in the semgrep rule that sets this match limit.

The one-line limit would be useful for configuration formats that are line-oriented and don't use indentation to delimit blocks.
 See for example https://github.com/returntocorp/semgrep-rules/pull/2066.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1285/generic-mode-offer-an-option-to-set-the-maximum-number-of-lines. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
you can use the options: field for that.
There's also Config_semgrep.atd to define those options.

**Comment by mjambon** [comment]
I'll look into this. I also want to use the same mechanism for specifying a comment stripper (#4485).
