### ISSUE TITLE
Support ... in Java annotations

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#522]
**Is your feature request related to a problem? Please describe.**
It looks like sgrep doesn't support `...` in method decorators yet.
See https://sgrep.live/yjx?version=develop, which works, vs.
https://sgrep.live/rrn?version=develop, which does not.

**Comment by minusworld** [comment]
I gave this one a try.

Unintuitively, Java Annotations special-case `ElementValuePair` (https://docs.oracle.com/javase/specs/jls/se7/html/jls-18.html) and these are not considered expressions. This is why metavariables and ellipses do not work for `value = something` in Annotations.

I tried adding a special-case ellipsis operator to `annotation_element` in pfff `parser_java.mly:1017`, but that was the wrong place; that just covers the interior of the annotations arguments.

**Comment by aryx** [comment]
This might work now? @IagoAbal another good first task.

**Comment by colleend** [comment]
@aryx do you think this is a good issue to tackle?

**Comment by aryx** [comment]
Yep, go for it.
