### ISSUE TITLE
junit-xml should join the stacktrace

### ISSUE THREAD

**Issue by greut** [semgrep/semgrep#5223]
**Describe the bug**
When producing a `--junit-xml` output, it show the stacktrace a a list of strings rather than a big strings. Maybe, it's only a `"\n".join(...)` away.

**To Reproduce**
`--junit-xml` :)

**Expected behavior**
The list of str should one str

**Screenshots**
![Screenshot 2022-05-16 at 15-47-47 jenkins _ Pre-pricing_Tarantino _ test_semgrep _ #4](https://user-images.githubusercontent.com/1388/168607534-c131d0b9-9f2b-419d-8a54-aae221e18e87.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
```
Running `semgrep ci` without API token but with configs ('p/golang', 'p/secrets', 'p/security-audit')
Scan environment:
  versions    - semgrep 0.92.1 on python 3.10.4
  environment - running in environment git, triggering event is unknown
```

**Use case**
Wider adoption of semgrep.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1295/junit-xml-should-join-the-stacktrace. _Note_: this link is for r2c use only and is not accessible publicly.
