### ISSUE TITLE
TS/JS -  Arrow function does not accept ellipsis 

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5230]
**Describe the bug**
Inside an arrow function it does not allow an ellipsis of any kind just the hardcoded value and $VALUE this should accept any arbitrary amount of values. 

**To Reproduce**
Works: 
https://semgrep.dev/s/jj3P
https://semgrep.dev/s/25Pr

Does not work: 
```..., $VALUE,...```
https://semgrep.dev/s/25Pr
```...```
https://semgrep.dev/s/X1Kj

**Expected behavior**
Should detect the $VALUE inside arrow function with ellipsis 

**Screenshots**

**What is the priority of the bug to you?**

- [x]  P1: important to fix or quite annoying

**Use case**
React rules will be 🚀

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1301/tsjs-arrow-function-does-not-accept-ellipsis. _Note_: this link is for r2c use only and is not accessible publicly.
