### ISSUE TITLE
TS/JS - dot ellipsis dot should also match field access chain (not just method calls chain) 

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5231]
**Describe the bug**
Probably because of lambdas' but the current assignment does not work with arbitrary ellipsis, which is very important to capture values where a value may be assigned. 

**To Reproduce**
Does not work:
https://semgrep.dev/s/90Dy
Works:
https://semgrep.dev/s/r3OJ

**Expected behavior**
Should capture on Arbitrary ellipsis 

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
TS/React to 🚀 🌔

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1302/tsjs-arbitrary-ellipsis-does-not-work. _Note_: this link is for r2c use only and is not accessible publicly.
