### ISSUE TITLE
Ruby taint parser performs incorrect pattern tokenization (partial string matching)

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#5232]
**Describe the bug**
Taint mode in Ruby occasionally incorrectly performs partial matching against sources

**To Reproduce**
https://semgrep.dev/s/wlNd

**Expected behavior**
`params` is a Rails built-in. The pattern `params` should mark the `params` object (and *only* the `params` object) as tainted. 

Search mode behaves correctly:
https://semgrep.dev/s/Obok

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
This is unexpected (and incorrect) parser behavior for Ruby in taint mode. `params` is one of the most common sources of user-controllable data in a Rails application and will be in most, if not all taint rules. It should behave as expected.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1303/ruby-taint-parser-performs-incorrect-pattern-tokenization-partial. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kurt-r2c** [comment]
on further inspection, this might be an oddity with a sanitizer. Continuing to investigate.

**Comment by kurt-r2c** [comment]
Nevermind. This is correct. Using the new debugger (thanks @IagoAbal) I determined that this is actually matching a downstream function call on a tainted object.
