### ISSUE TITLE
[HTML, JSX] Unable to match empty HTML element

### ISSUE THREAD

**Issue by je-l** [semgrep/semgrep#5235]
**Describe the bug**
Matching an HTML element without any attributes is not possible.

**To Reproduce**
See erroneous output here: https://semgrep.dev/s/zp3n
Tests should pass, but Semgrep yields false positive on `<div attribute="value" />`

**Expected behavior**
Semgrep should not report `<div attribute="value" />` as match.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
I'm experimenting on using Semgrep for detecting accessibility issues in HTML, React and Vue code. Many a11y issues in frontend code are pretty simple, which should be easy to detect with static analysis. E.g. see this description of missing alt-attribute in img element: https://dequeuniversity.com/rules/axe/4.4/image-alt
Semgrep would perhaps make writing checks like this much easier with stronger HTML/JSX/Vue support.

Using generic language mode as workaround seems possible currently.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1306/[html-jsx]-unable-to-match-empty-html-element. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
This is related to https://github.com/returntocorp/semgrep/issues/2812

**Comment by aryx** [comment]
Here is a fix @je-l https://semgrep.dev/s/JbKP

**Comment by aryx** [comment]
I'll update the documentation here: https://semgrep.dev/docs/writing-rules/rule-syntax/#options

**Comment by je-l** [comment]
Great, thanks for the fix! For my use case this seems sufficient, please feel free to close this issue if this is working as intended.

**Comment by aryx** [comment]
Hope this will help: https://github.com/returntocorp/semgrep-docs/pull/539
