### ISSUE TITLE
Support surrounding code around Lambdas 

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5239]
**Describe the bug**
It does analyze lambdas, but Semgrep does that independently and not together with their surrounding code. We need the ability to capture values surrounding lambdas and inside e.g. source -> sink.

Bug:
https://semgrep.dev/s/lewisardern:jdbc
Works:
https://semgrep.dev/s/W7Lo

**To Reproduce**
Bug:
https://semgrep.dev/s/lewisardern:jdbc
Works:
https://semgrep.dev/s/W7Lo

**Expected behavior**
Should find line 213

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
Improve java taint analysis

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1308/java-support-surrounding-code-around-lambdas. _Note_: this link is for r2c use only and is not accessible publicly.
