### ISSUE TITLE
[Kotlin] semgrep crashes when parsing file with v0.92.1 (or lower)

### ISSUE THREAD

**Issue by nikhilvats1** [semgrep/semgrep#5244]
**Describe the bug**
semgrep crashes when scanning the attached file with the error below

```
[WARN] Semgrep Core — Syntax error
An error occurred while invoking the Semgrep engine. Please help us fix this by creating an issue at https://github.com/returntocorp/semgrep

At line UrlManager.kt:10: `}` was unexpected
```

**To Reproduce**
semgrep version: 0.92.1 (and lower)

Command
`semgrep --config=. --strict  --verbose
`

Run the above command in a folder containing the attached files.

**Expected behavior**
The error mentioned in the description above

**What is the priority of the bug to you?**
P0 - blocks the adoption of semgrep for Kotlin file scanning.

**Environment**
Ubuntu

**Use case**
Kotlin file scanning.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1309/[kotlin]-semgrep-crashes-when-parsing-file-with-v0921-or-lower. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by nikhilvats1** [comment]
[UrlManager.kt.txt](https://github.com/returntocorp/semgrep/files/8711063/UrlManager.kt.txt)

**Comment by nikhilvats1** [comment]
[semgrep-kotlin.yaml.txt](https://github.com/returntocorp/semgrep/files/8711367/semgrep-kotlin.yaml.txt)

**Comment by nikhilvats1** [comment]
Added the file that crashes + rule file used to simulate crash
