### ISSUE TITLE
docker image fails to fetch rules from registry

### ISSUE THREAD

**Issue by 5stars217** [semgrep/semgrep#5252]
Hi,
**Describe the bug**
when running the basic setup commands with docker, I am unable to fetch the configuration rules from the registry, regardless of if I run one of the following commands: (new and deprecated) 

` docker run returntocorp/semgrep semgrep scan --config auto`
`docker run returntocorp/semgrep semgrep semgrep scan --config auto`

I get the following failure:

`...More information: https://semgrep.dev/docs/metrics

Fetching rules from https://semgrep.dev/registry.
File not found: semgrep` 

I am runing the latest image:

`docker image pull returntocorp/semgrep
Using default tag: latest
latest: Pulling from returntocorp/semgrep
Digest: sha256:e99bcc36da6827858d8d5e1952f59a4246aacf4e91bfe6a5de98c8d409408128
Status: Image is up to date for returntocorp/semgrep:latest
docker.io/returntocorp/semgrep:latest
`

**To Reproduce**

` docker run returntocorp/semgrep semgrep scan --config auto`
`docker run returntocorp/semgrep semgrep semgrep scan --config auto`

**Expected behavior**
This is my first time using the docker image, I would expect that it would be able to pull the rules from the registry, and begin to scan a tree or ask follow ups. 

**What is the priority of the bug to you?**

- [ ] P1: important to fix or quite annoying

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

Docker, https://hub.docker.com/r/returntocorp/semgrep

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1359/docker-image-fails-to-fetch-rules-from-registry. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by nbrahms** [comment]
Hi @5stars217 ,

Can you try `docker run -v ${PWD}:/src returntocorp/semgrep scan --verbose --config auto .` (with the trailing `.`)?  This works on my machine.

**Comment by 5stars217** [comment]
That did it :) Thank you.
