### ISSUE TITLE
Fix parsing of quoted strings in rules stored in the JSON format

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#5268]
**Describe the bug**

semgrep-core's YAML parser used to parse rules interprets double-quoted strings incorrectly. Note that JSON is a subset of YAML, therefore semgrep-core should accept pure JSON rules without errors.

[Original comment](https://github.com/returntocorp/semgrep/pull/5261#pullrequestreview-978126917)

**To Reproduce**

```
$ cat rules.json
{
  "rules": [
    {
      "id": "x",
      "message": "",
      "languages": ["python"],
      "severity": "WARNING",
      "pattern": "\"hello\""
    }
  ]
}
$ semgrep-core -lang python -rules rules.json
rules.json:8:17: "Pattern parse error": Invalid pattern for Python
```

Surprisingly to me, the following variant works:
```
$ cat rules.yaml 
rules:
- id: x
  message: x
  languages: [python]
  severity: WARNING
  pattern: "\"hello\""
$ semgrep-core -lang python -rules rules.yaml
```

**Expected behavior**

no error output, exit 0

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

any

The `semgrep` wrapper works around the bug by passing rules to semgrep-core in YAML syntax rather than strict JSON, presumably managing to avoid double-quoted strings. It's possible but not certain that this workaround is completely effective. If not, the bug would affect some semgrep rules, resulting in unparseable rules and in particular, unparseable semgrep patterns.

**Use case**

Requires `semgrep` to reformat rules in a special way so as to work around the bug.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1364/fix-parsing-of-quoted-strings-in-yamljson-rules. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
This problem would be fixed properly by https://github.com/returntocorp/semgrep/issues/5269. Meanwhile, we have a workaround.

**Comment by aryx** [comment]
I'm pretty sure this used to work.

**Comment by aryx** [comment]
hmm this is probably the start of the regression: https://github.com/returntocorp/semgrep/pull/3530
https://github.com/returntocorp/semgrep/pull/3530/files#diff-87eda41bcb47ad95c85567086b40a47d3e32940702d714fcba49b75ab863d45dR551

This is when we switched from using a proper JSON parser to using Parse_json which does not interpret the antislash.

**Comment by aryx** [comment]
This does not happen for YAML rules, because the YAML library we use does the right thing and returned the final string (after handling all the escaping).

For context we switched away from using Yjoson to parse rules as JSON because we wanted to get position information.

**Comment by aryx** [comment]
BTW you can also use semgrep-core -dump_rule foo.json to test.
