### ISSUE TITLE
^ and $ should match at the beginning and end of each line

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#5280]
`pattern-regex` currently compiles regexps in the default mode rather than the multiline mode. The multiline mode is more suitable to scanning multiline input, as `^` and `$` will then be used to match the beginning and the end of lines, respectively, rather than only the beginning and end of the input file. Matching the beginning and end of input can still be done with `\A` and `\Z`, if desired.

The main issue is that without multiline mode, matching beginning and end of line is expert-level, solutions being `(^|(?<=\n))` (beginning of line) and `($|(?=\n))` (end of line).

Request: switch to multiline mode

Motivation: https://github.com/returntocorp/semgrep/issues/5148#issuecomment-1125583613

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1368/and-dollar-should-match-at-the-beginning-and-end-of-each-line. _Note_: this link is for r2c use only and is not accessible publicly.
