### ISSUE TITLE
[JS] function's arguments is not tracked by taint mode 

### ISSUE THREAD

**Issue by azu** [semgrep/semgrep#5282]
**Describe the bug**

When pass tracking source to a function as arguments, semgrep stop tracking the source.

Maybe, I met some limitation of semgrep's taint mode…

**To Reproduce**
https://semgrep.dev/s/vkGA

This rule track `event` as sources, but semgrep can not checks `newEval` that is just wrapped `eval` function as sink.

**Expected behavior**

Report `newEval(event["smth"])` as an Error.

**Screenshots**

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/19714/169689734-d5ca00f5-0363-4e99-871e-578ed36da18a.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**

I want to found SQL injection to use builder function like `createQuery`.
However,  [tainted-sql-string](https://semgrep.dev/playground/r/javascript.express.security.injection.tainted-sql-string.tainted-sql-string) example does not work correctly. 
I think that it is same reason to this issue.

```js
function createQuery(message) {
  // semgrep can not found the insecure join
  return "SELECT * FROM `users`" + " WHERE id = '" + message + "'"
}
app.get('/test000-but-it-is-not-found', (req, res) => {
  const query = createQuery(req.query.message);
  const [results, metadata] = await sequelize.query(query);
  res.send(results)
})
```

Reproduce example.
https://semgrep.dev/s/azu:tainted-sql-string-copy

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1370/[js]-functions-arguments-is-not-tracked-by-taint-mode. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by azu** [comment]
Which is this a bug or expected behavior?

**Comment by azu** [comment]
📝 As a memo, I could not reopen this issue.
