### ISSUE TITLE
Good Lines and Bad Lines for a pattern.

### ISSUE THREAD

**Issue by amanagr** [semgrep/semgrep#529]
We in https://github.com/zulip/zulip print `good_lines` and `bad_lines` for pattern to help user better understand the error and how it can be resolved. For eg:

```
        {'pattern': 'subject|SUBJECT',
         'description': 'avoid subject in JS code',
         'good_lines': ['topic_name'],
         'bad_lines': ['subject="foo"', ' MAX_SUBJECT_LEN']},
```

You can see, how we tell user to use `topic` instead of `subject` through a good line example.
Similar examples can be found on https://github.com/zulip/zulip/blob/master/tools/linter_lib/custom_check.py

Ideal solution would be adding fields for `good_lines` and `bad_lines` (which take a list ideally).

I can use the message field with new lines but I would like them to be colored differently and properly formatted which could be hard to achieve in the limited capabilities of a `.yml` file.

@ievans FYI

**Comment by andersk** [comment]
The other use of `good_lines` and `bad_lines` in Zulip that’s just as important, if not more important, is to verify that you wrote the pattern correctly. We print an error if a line in `good_lines` matches or a line in `bad_lines` doesn’t match. This concept would be valuable for `sgrep-lint` too (of course, with `sgrep-lint`, we might be talking about multi-line snippets instead of just single lines).

**Comment by ievans** [comment]
Thanks for that clarification @andersk. We have a similar concept in the sgrep-rules repository around test suites, but they are a comment syntax inside standalone python files instead of living inside the rule file. C.f. https://github.com/returntocorp/semgrep-rules/tree/develop/python/compatibility or the "all tests pass" output in https://semgrep.live/GLp 

This is a good setup because some of the test files can be quite context-dependent compared to a simple grep rule. Still, the ergonomics of "here's a good example, here's a bad example," as well as thinking about how tests might exist outside of our central git repository, are important for us to get right.

**Comment by dlukeomalley** [comment]
Thanks for filing this ticket @amanagr! In the release Zulip uses there is support for a `metadata` key, see [documentation](https://github.com/returntocorp/semgrep/blob/experimental/docs/config/advanced.md#metadata). I think we can use that key to get the good/bad example functionality you need:

```yaml
rules:
  - id: eqeq-is-bad
    patterns:
      - [...]
    message: "useless comparison operation `$X == $X` or `$X != $X`"
    metadata:
      good_lines:
        - "topic_name"
      bad_lines:
        - subject="foo"
        - MAX_SUBJECT_LEN
```

Would this work for you for now?

**Comment by dlukeomalley** [comment]
@amanagr Am I good to close this issue?

**Comment by amanagr** [comment]
We also want the `pattern` to run on them and fail for the `good_lines` and pass for the `bad_lines` so that we know the pattern was correctly written. I understand I can print good lines and bad lines with `--json` argument, this will help us transition to sgrep, but we would still like sgrep to support this feature in coming future.

**Comment by amanagr** [comment]
I tried out the `--json` argument, but its output is ugly. We want `bad_lines` and `good_lines` to be printed just like the `message`. I think this could be a very useful feature for you guys to advertise too.

**Comment by dlukeomalley** [comment]
> I tried out the `--json` argument, but its output is ugly. We want `bad_lines` and `good_lines` to be printed just like the `message`. I think this could be a very useful feature for you guys to advertise too.

@amanagr Do you have sample output you're comfortable sharing here for discussion?

**Comment by dlukeomalley** [comment]
> I tried out the `--json` argument, but its output is ugly. We want `bad_lines` and `good_lines` to be printed just like the `message`. I think this could be a very useful feature for you guys to advertise too.

@amanagr Do you have sample output you're comfortable sharing here for discussion?

**Comment by amanagr** [comment]
on
```
❯ ./tools/lint --only=semgrep-py
```
Output: https://pastebin.com/wT5T52r0

sample:
`
{"results": [{"check_id": "tools.login_required-unsupported", "path": "analytics/views.py", "start": {"line": 81, "col": 2}, "end": {"line": 89, "col": 65}, "extra": {"message": "@login_required is unsupported; use @zulip_login_required", "metadata": {"good_lines": ["@zulip_login_required", "# foo @login_required"], "bad_lines": ["@login_required", " @login_required"]}, "file_lines": ["@zulip_login_required\n", "def stats(request: HttpRequest) -> HttpResponse:\n", "    realm = request.user.realm\n", "    if request.user.is_guest:\n", "        # TODO: Make @zulip_login_required pass the UserProfile so we\n", "        # can use @require_member_or_admin\n", "        raise JsonableError(_(\"Not allowed for guest users\"))\n"
`
On code: https://github.com/amanagr/zulip/tree/sgrep_upgrade

**Comment by amanagr** [comment]
We could reprocess this info and print it, but I think we would like to avoid it and have sgrep naturally support this feature to avoid future maintenance on our side which you guys are already doing.

**Comment by dlukeomalley** [comment]
Thank you for the sample @amanagr! I imagined semgrep's `--json` output being passed to a Zulip-specific formatter before being returned. Could functionality be borrowed from the regex integration's good_lines/bad_lines formatting?

For now, I don't know if `good_lines` and `bad_lines` will be a core semgrep feature and I'd like to wait until a few more users have similar workflow needs before we discuss it further.

Are you willing to use the `metadata` field + custom JSON parsing to get the desired output?

> The other use of `good_lines` and `bad_lines` in Zulip that’s just as important, if not more important, is to verify that you wrote the pattern correctly. We print an error if a line in `good_lines` matches or a line in `bad_lines` doesn’t match. This concept would be valuable for `sgrep-lint` too (of course, with `sgrep-lint`, we might be talking about multi-line snippets instead of just single lines).

@andersk Agreed. I'll open another ticket shortly to track the testing use case.

**Comment by dlukeomalley** [comment]
@andersk @amanagr I opened https://github.com/returntocorp/semgrep/issues/645 for unit testing discussion. 

For now I'd like to close this ticket and revisit it in the future. Thank you so much for your feedback  so far.
