### ISSUE TITLE
Semgrep validate does not report error when config file is missing

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#5293]
```
$ semgrep --validate --config ./notexists.yml
Fetching rules from https://semgrep.dev/registry.
$
```

The command does with an error exit status, but I would expect it to print an error.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1374/semgrep-validate-does-not-report-error-when-config-file-is-missing. _Note_: this link is for r2c use only and is not accessible publicly.
