### ISSUE TITLE
Const keyword is not compatible with semgrep pattern-matching in C++

### ISSUE THREAD

**Issue by ChakirBelhaj** [semgrep/semgrep#5300]
**Describe the bug**

It appears that the ability to search for a const variable is not possible in Semgrep C++.

**To Reproduce**
https://semgrep.dev/s/chakirbelhaj:x1xl

**Expected behavior**
Semgrep detecting const variables in c++.

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
For a particular use case, we are trying to detect variables that are not reassigned AND are not defined as a const. With this, we intend to force that "read-only" variables are defined as a const.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1378/const-keyword-is-not-compatible-with-semgrep-pattern-matching-in-c. _Note_: this link is for r2c use only and is not accessible publicly.
