### ISSUE TITLE
TS/JS - Import drops $VALUE before {...}

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5305]
**Describe the bug**
The addition [for import { } from 'value' ](https://github.com/returntocorp/semgrep/issues/5012) was awesome for TS/JS  but it also would be great to capture the  values before {..} 

```
  - pattern-inside: |
      import {  ...,useRef,... } from "react"
      ...

^ works

      import React,{  ...,useRef,... } from "react"
      ...

^ does not work 
```

Works:
https://semgrep.dev/playground/s/ylo8?develop=true

Does not work:
https://semgrep.dev/s/ylo8

**To Reproduce**
Works:
https://semgrep.dev/playground/s/ylo8?develop=true

Does not work:
https://semgrep.dev/s/ylo8

**Expected behavior**
$REACT should be also captured 

**Priority**
How important is this to you?
- [x] P2: annoying but not blocking me

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1379/tsjs-import-drops-dollarvalue-before. _Note_: this link is for r2c use only and is not accessible publicly.
