### ISSUE TITLE
Scans failing on v0.94.0

### ISSUE THREAD

**Issue by jesse-r2c-test** [semgrep/semgrep#5320]
**Describe the bug**
Semgrep is failing to run scans against a test repo (juice shop)

Relevant scan: https://github.com/jesse-r2c-test/juice-shop/runs/6611340414?check_suite_focus=true

**To Reproduce**
1. Fork [juice-shop](https://github.com/juice-shop/juice-shop)
2. Add the project to Semgrep App
3. Add CI with Github Actions

**Expected behavior**
Scans to succeed and post findings

**Screenshots**
![image](https://user-images.githubusercontent.com/103216875/170519397-144ab486-8168-429e-a3b3-506e8aa39487.png)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1385/scans-failing-on-v0940. _Note_: this link is for r2c use only and is not accessible publicly.
