### ISSUE TITLE
Ellipsis does not work with Dockerfile 'FROM'

### ISSUE THREAD

**Issue by rc-mattschwager** [semgrep/semgrep#5334]
**Describe the bug**

Ellipsis works with most Dockerfile commands, however `FROM` does not appear to work.

**To Reproduce**

```
$ echo 'FROM ubuntu:16.04' | semgrep -l dockerfile -e 'FROM ...' -
Scanning 1 file.

Some files were skipped.
  Scan was limited to files tracked by git.

Ran 1 rule on 1 file: 0 findings.
```

```
$ echo 'RUN ls' | semgrep -l dockerfile -e 'RUN ...' -
Scanning 1 file.

Findings:

  /var/folders/5_/pjcwsmbn4ll0_yy6h8b7z7p40000gq/T/tmpg8x5leka/stdin 
          1┆ RUN ls

Some files were skipped.
  Scan was limited to files tracked by git.

Ran 1 rule on 1 file: 1 finding.
```

```
$ echo 'ENV FOO BAR' | semgrep -l dockerfile -e 'ENV ...' -
Scanning 1 file.

Findings:

  /var/folders/5_/pjcwsmbn4ll0_yy6h8b7z7p40000gq/T/tmpzkw_6rwp/stdin 
          1┆ ENV FOO BAR

Some files were skipped.
  Scan was limited to files tracked by git.

Ran 1 rule on 1 file: 1 finding.
```

**Expected behavior**

Ellipsis operator works with Dockerfile `FROM` command.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

```
$ semgrep --version
0.94.0
```

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1396/ellipsis-does-not-work-with-dockerfile-from. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
👋 The reason for this behavior is that `...` stands for a sequence of items of the same kind. For matching any `FROM` instruction, you should use a metavariable that stands for the image name. This should work:
```
echo 'FROM ubuntu:16.04' | semgrep -l dockerfile -e 'FROM $IMAGE' -
```
Note that `ENV ...` works because the `ENV` instruction takes a list of arguments. `RUN ...` also works because `...` stands for a list of shell commands.
