### ISSUE TITLE
TS/JS - || OR operator prevent capturing assignment value

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5345]
**Describe the bug**
The OR operator prevents the capture of the assignment of the first value:
```
        return_url.current =
                new URLSearchParams(window.location.search).get("return") || undefined;
```
a rule like:
```
$VALUE = new URLSearchParams(window.location.search).get("...") 
```
Should still capture the result since it's an OR operator, if the query parameter did not exist, the value would be set to undefined. 

**To Reproduce**
Issue (15 and 18) :
https://semgrep.dev/s/n8Lg

Works:
https://semgrep.dev/s/EpLP

**Expected behavior**
Should still capture the value before the OR operator with expected rule syntax.

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
React rules

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1398/tsjs-oror-or-operator-prevent-capturing-assignment-value. _Note_: this link is for r2c use only and is not accessible publicly.
