### ISSUE TITLE
Can't install semgrep using Python 3.6

### ISSUE THREAD

**Issue by darshilsaraiya** [semgrep/semgrep#5346]
**Describe the bug**
I have an Oracle Linux environment. I am trying to install semgrep tool by following this page: https://semgrep.dev/docs/getting-started/
Oracle Linux : Linux 5.4.17 (fedora)
Python3 version: Python 3.6.8

**To Reproduce**
When I try to run the the command python3 -m pip install semgrep using this confluence page: https://semgrep.dev/docs/getting-started/
I am getting this error:
`Collecting semgrep
  Using cached https://pypi.eng.netsuite.com/packages/semgrep/0.81.0/semgrep-0.81.0-cp36.cp37.cp38.cp39.py36.py37.py38.py39-none-any.whl
Requirement already satisfied: tqdm>=4.46.1 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: attrs>=19.3.0 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: click-option-group>=0.5.3 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: colorama>=0.4.3 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: jsonschema<5,>=3.2.0 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: peewee~=3.14.4 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: click>=8.0.1 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: wcmatch==8.3 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: ruamel.yaml<0.18,>=0.16.0 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: requests>=2.22.0 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: packaging>=20.4 in /home/nsbuild/.local/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from semgrep)
Requirement already satisfied: importlib-resources; python_version < "3.7" in /home/nsbuild/.local/lib/python3.6/site-packages (from tqdm>=4.46.1->semgrep)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /home/nsbuild/.local/lib/python3.6/site-packages (from jsonschema<5,>=3.2.0->semgrep)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /home/nsbuild/.local/lib/python3.6/site-packages (from jsonschema<5,>=3.2.0->semgrep)
Requirement already satisfied: bracex>=2.1.1 in /home/nsbuild/.local/lib/python3.6/site-packages (from wcmatch==8.3->semgrep)
Requirement already satisfied: ruamel.yaml.clib>=0.2.6; platform_python_implementation == "CPython" and python_version < "3.11" in /home/nsbuild/.local/lib/python3.6/site-packages (from ruamel.yaml<0.18,>=0.16.0->semgrep)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.6/site-packages (from requests>=2.22.0->semgrep)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in /home/nsbuild/.local/lib/python3.6/site-packages (from requests>=2.22.0->semgrep)
Requirement already satisfied: certifi>=2017.4.17 in /home/nsbuild/.local/lib/python3.6/site-packages (from requests>=2.22.0->semgrep)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/lib/python3.6/site-packages (from requests>=2.22.0->semgrep)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/nsbuild/.local/lib/python3.6/site-packages (from packaging>=20.4->semgrep)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /home/nsbuild/.local/lib/python3.6/site-packages (from importlib-resources; python_version < "3.7"->tqdm>=4.46.1->semgrep)
Requirement already satisfied: typing-extensions>=3.6.4; python_version < "3.8" in /home/nsbuild/.local/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema<5,>=3.2.0->semgrep)
Installing collected packages: semgrep
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 365, in run
    strip_file_prefix=options.strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 789, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 854, in install
    strip_file_prefix=strip_file_prefix
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 1069, in move_wheel_files
    strip_file_prefix=strip_file_prefix,
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 287, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
`

**Expected behavior**
semgrep should be installed

**Screenshots**
![image](https://user-images.githubusercontent.com/18083177/170833720-38e75a45-3ceb-4dba-9cbd-f55c1aa5f42a.png)

**What is the priority of the bug to you?**
- P0: blocking your adoption of Semgrep or workflow

**Use case**
We are trying to build a wrapper on the top of semgrep for internal use.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1399/cant-install-semgrep-using-python-36. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spencerdrak** [comment]
Since Python3.6 has been EOL as of December 2021 (per [PEP 494](https://peps.python.org/pep-0494/#lifespan)), we no longer support it. If you have other feedback, please let us know!

Thanks!
