### ISSUE TITLE
JS/TS - Treat <$EL>...</$EL> and <$EL/> separately

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#5347]
**Describe the bug**
Currently https://semgrep.dev/s/BxP6 <$EL/> matches <$EL>...</$EL> considering how a lot of react elements are either:
```
<Basic countries={countries} title={title} href={href} />
```
or
```
<a href={e[1]} target="_blank">
          {e[0]}
</a>
```
We probably want semgrep to treat them as separate elements?
 
**To Reproduce**
https://semgrep.dev/s/BxP6

**Expected behavior**
<$EL/> shouldn't capture <$EL>...</$EL>
**Screenshots**

**What is the priority of the bug to you?**

- [x] P2: regular bug that should get fixed

**Use case**
React/JSX parsing

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1400/jsts-treat-dollareldollarel-and-dollarel-separately. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
We should probably add an `option` to enable/disable the equivalence. It's the kind of thing where you can't make "the right choice", it depends on the context you'll want one thing or another.

**Comment by aryx** [comment]
there's already one.

**Comment by aryx** [comment]
https://github.com/returntocorp/semgrep/blob/0eb7a7ec24c74bd73c748d89817e729618f0c3db/interfaces/Config_semgrep.atd#L56

**Comment by aryx** [comment]
In fact it should probably be at false by default.

**Comment by aryx** [comment]
See https://github.com/returntocorp/semgrep/issues/2812

**Comment by aryx** [comment]
solved example: https://semgrep.dev/s/5AXW
