### ISSUE TITLE
Fails to parse valid Python f"{var:+g}"

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#535]
**Describe the bug**
```console
$ echo 'var = 17; print(f"{var:+g}")' > test.py
$ python test.py
+17
$ sgrep -lang python -dump_ast test.py
Fatal error: exception Parse_info.Parsing_error(_)
```

**Environment**
Official semgrep-v0.4.11b7-ubuntu-16.04.tgz binary.

**Comment by dlukeomalley** [comment]
Queuing this up to investigate. Thank you for the repro steps @andersk.

**Comment by dlukeomalley** [comment]
@andersk We'll include this in a Zulip release tomorrow.
