### ISSUE TITLE
Matching by package and class does not work  in scala

### ISSUE THREAD

**Issue by Strunevskiy** [semgrep/semgrep#5355]
**Is your feature request related to a problem? Please describe.**
In scala, if you are using a class inside  other classes located in the same package, you do not need to specify any import. As a result, there is no way to create a pattern to match usage of one class inside the other class which are located under the same package. You could create a rule to do the search  by class name, but it could result in false alarm where class which is found is not the class you were searching for.

**Describe the solution you'd like**

https://semgrep.dev/s/3Gko

If class CompileSocket is located in scala.tools.nsc, I want to be able to search the usage of CompileSocket in other classes located in the same package.
```
    - patterns:
        - pattern-inside: |
            package scala.tools.nsc
            ...
        - pattern-either:
            - pattern: CompileSocket
```

Also, it would be nice if full package name like  scala.tools.nsc  in the pattern could match varied variations of it in source code
1. 
```
package scala
package tools.nsc
```
2.
```
package scala.tools
package nsc
```

**Describe alternatives you've considered**
You could create a rule to do the search  by class name, but it could result in false alarm where class which is found is not the class you were searching for.

**Use case**
What will this feature enable for you?
It enables searching for the usage of a class inside the same package.

**Additional context**

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1402/matching-by-package-and-class-does-not-work-in-scala. _Note_: this link is for r2c use only and is not accessible publicly.
