### ISSUE TITLE
Support of Typed Metavariables in Scala

### ISSUE THREAD

**Issue by Strunevskiy** [semgrep/semgrep#5376]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to search for the usage of methods on objects across code base. Unlike Semgrep for Java, Scala does not have support to use Typed Metavariables in patterns like  ```(String $B).func()```

**Describe the solution you'd like**
Given scala code
```
def random: ThreadLocalRandom = ThreadLocalRandom.current()
random.nextInt(alphabet.size)
```
I want to be able to use pattern like
```
- pattern: (ThreadLocalRandom $OBJECT).nextInt
```

**Describe alternatives you've considered**
N/A

**Use case**
What will this feature enable for you?
It will allow us to perform search for usage of particular methods on objects across code base.

**Additional context**
The documentation advertises this feature, but it seems like it is not available in scala.
https://semgrep.dev/docs/writing-rules/pattern-syntax/#using-typed-metavariables

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1404/support-of-typed-metavariables-in-scala. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mmcqd** [comment]
Scala does have typed metavariables, but the syntax mirrors Scala type annotations, it's `$X : foo`, not `foo $X`. Testing this did reveal another bug though: https://semgrep.dev/s/PyeE. The example only works when you surround the thing you want to find with parentheses. This is likely because of some parsing weirdness, which I'll fix.

**Comment by Strunevskiy** [comment]
@mmcqd so you are saying that once you fix the bug then we will be able to do it without surrounding the thing you want to find ?

**Comment by mmcqd** [comment]
@Strunevskiy yes
