### ISSUE TITLE
Semgrep ci has --scan-unknown-extensions but not --lang

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#5383]
When running `semgrep ci`, it's not possible to specify a language with `--lang`. This makes the option `--scan-unknown-extensions` quite useless, since that will enable scanning of files with the language specified in `--lang`.

```
$ semgrep ci --help
...
    --scan-unknown-extensions / --skip-unknown-extensions
                                  If true, explicit files will be scanned
                                  using the language specified in --lang.
```

I was trying to scan a certain file extension not supported by semgrep, by running 

    find . -name *.abc | xargs semgrep ci --lang php --scan-unknown-extensions

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1409/semgrep-ci-has-scan-unknown-extensions-but-not-lang. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
@Sjord the --scan-unknown-extensions also uses the languages field in rule definitions. The --lang flag is to inline the language field when `-e` is used to pass a pattern in line. So `--lang` doesnt have use in `semgrep ci`

**Comment by Sjord** [comment]
That is not the behavior I observe, and is also not the documented behavior. The command line help (`semgrep ci --help`) clearly states that `--scan-unknown-extensions` uses "the language specified in --lang".

If I have two files, `test.php` and `test.ext`, `semgrep ci` will scan only `test.php`, whether I specify `--scan-unknown-extensions` or not.

```
$ ls
test.ext test.php
$ semgrep ci -c "r/php.lang.security" --scan-unknown-extensions
Running `semgrep ci` without API token but with configs ('r/php.lang.security',)
Scan environment:
  versions    - semgrep 0.94.0 on python 3.10.4
  environment - running in environment git, triggering event is unknown

Fetching configuration from semgrep.dev
Fetching rules from https://semgrep.dev/registry.
Scanning 1 file with 26 php rules.

Findings:

  test.php
     php.lang.security.eval-use.eval-use
        Evaluating non-constant commands. This can lead to command injection.
        Details: https://sg.run/J9AP

          2┆ eval($_GET['q']);

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 26 rules on 1 file: 1 finding.
Ran 26 blocking rules, 0 audit rules, and 0 internal rules used for rule recommendations.
Found 1 findings from blocking rules and 0 findings from non-blocking rules
Has findings for blocking rules so exiting with code 1
```

**Comment by Sjord** [comment]
From [the code](https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/target_manager.py#L645) it seems that `--scan-unknown-extensions` only work on files passed as argument. E.g. in `semgrep scan test.ext`, `test.ext` is or isn't scanned depending on `--scan-unknown-extensions` or `--skip-unknown-extensions`. But when scanning a directory, `test.ext` is always excluded.

`semgrep ci` does not have the possibility to provide targets. It always scans the current directory, and `semgrep ci test.ext` gives an error. So it seems that the `--scan-unknown-extensions` is not usable there.

**Comment by Sjord** [comment]
@brendongo Could you consider re-opening this issue? If `--scan-unknown-extensions` only works on files passed as argument, and `semgrep ci` doesn't take files as arguments, then this option doesn't make sense.
