### ISSUE TITLE
'Create draft release' workflow should add the .tgz archive hashes in the release body

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#539]
This would save some time when we (or others) try to verify the archive integrity with `sha256sum`, such as here https://github.com/zulip/zulip/blob/859b48c491cf800078eecccddf495677c802aa43/tools/setup/install-sgrep#L6

**Comment by rcoh** [comment]
This is done: https://github.com/returntocorp/semgrep/pull/516, but has never been used on a real release. We can close this issue once we've made a new release and it actually works.

**Comment by brendongo** [comment]
https://github.com/returntocorp/semgrep/releases/tag/v0.5.0b1 has the hashes in the release. Thanks @rcoh
