### ISSUE TITLE
semgrep ci times out during git fetch operation on GitLab CI for big repositories

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#5395]
**Describe the bug**

The timeout in https://github.com/returntocorp/semgrep/blob/8e3e9c6755f4c7e52e8a92109ac83e843817ef77/semgrep/semgrep/git.py#L19 is hard coded to 100 seconds and that's not enough for big repositories (it's failing on https://gitlab.com/gitlab-org/gitlab).

```
Scan environment:
  versions    - semgrep 0.94.0 on python 3.10.4
  environment - running in environment gitlab-ci, triggering event is pull_request
Fetching configuration from semgrep.dev
Command '['git', 'fetch', '[https://gitlab-ci-token:[MASKED]@gitlab.com/gitlab-org/gitlab'](https://gitlab-ci-token:%5BMASKED%5D@gitlab.com/gitlab-org/gitlab'), 'master']' timed out after 100 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/wrapper.py", line 39, in wrapper
    func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/commands/ci.py", line 361, in ci
    baseline_commit=metadata.base_commit_ref,
  File "/usr/local/lib/python3.10/site-packages/boltons/cacheutils.py", line 641, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 444, in base_commit_ref
    return self._fetch_branch_get_merge_base(target_branch, head_sha)
  File "/usr/local/lib/python3.10/site-packages/semgrep/meta.py", line 401, in _fetch_branch_get_merge_base
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/local/lib/python3.10/subprocess.py", line 1149, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/lib/python3.10/subprocess.py", line 2001, in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
  File "/usr/local/lib/python3.10/subprocess.py", line 1193, in _check_timeout
    raise TimeoutExpired(
subprocess.TimeoutExpired: Command '['git', 'fetch', '[https://gitlab-ci-token:[MASKED]@gitlab.com/gitlab-org/gitlab'](https://gitlab-ci-token:%5BMASKED%5D@gitlab.com/gitlab-org/gitlab'), 'master']' timed out after 100 seconds
```

**To Reproduce**

Run `semgrep ci` with a very big repository (and lots of history) in GitLab CI.

It seems like the code for GitHub progressively increases the depth not to require the entire history which is an interesting approach that might speed things up in most cases but I suppose we'd still hit the time out once in a while.

**Expected behavior**

Either a faster way to get the merge base or an extended/configurable timeout value.

**Screenshots**

**What is the priority of the bug to you?**

It would be P0, but some workarounds exist (patching the file or doing the fetch operation before calling semgrep) so it falls back to "quite annoying" :)

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
`returntocorp/semgrep` docker image

**Use case**
What will fixing this bug enable for you?

A new workflow that leverages semgrep for some automated merge request reviews

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1412/semgrep-ci-times-out-during-git-fetch-operation-on-gitlab-ci-for-big. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
For internal tracking too: https://r2c-community.slack.com/archives/C01KY32FDAT/p1654119992102449
