### ISSUE TITLE
Semgrep doesn't pick up .semgrepignore in linux

### ISSUE THREAD

**Issue by Strunevskiy** [semgrep/semgrep#5397]
**Describe the bug**
When .semgrepignore is created and is put under the folder where other files are located for scan, semgrep does not pick up rules. 

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

- semgrep --version 0.93.0
- OS version centos rhel fedora
- The semgrep is run from  CLI  under **semgrep** folder

```
current dir: semgrep
rules files:  semgrep/rules
code for scanning: 
semgrep/jars/folder_1/java_file_one
semgrep/jars/folder_2/java_file_two
semgrep/jars/folder_2/examples/java_file_tree
.semgrepignore location:  semgrep/jars/.semgrepignore
```

.semgrepignore content
```
examples/
```

Note: if .semgrepignore file is left empty, files located in tests or test folders are not ignored.

**Expected behavior**

**java_file_tree**  should not be scanned

**Screenshots**

**What is the priority of the bug to you?**
- [ ] P1: important to fix or quite annoying

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
I am running on linux installed via pip

**Use case**
What will fixing this bug enable for you?
I will allow us to ignore files which are meant to be for testing or examples

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1413/semgrep-doesnt-pick-up-semgrepignore-in-linux. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by emjin** [comment]
Semgrep uses the `.semgrepignore` in the directory that it is run from, so in this case it would be `semgrep`, not `semgrep/jars`. We've found that this generally is the least ambiguous way to do it. If that doesn't work, please open a new issue!
