### ISSUE TITLE
generic.dockerfile.correctness.multiple-cmd-instructions does not support HEALTHCHECK CMD ...

### ISSUE THREAD

**Issue by thomdixon** [semgrep/semgrep#5410]
**Describe the bug**
The multiple `CMD` instruction detection is outdated and does not handle `HEALTHCHECK CMD` correctly.

**To Reproduce**
Here's a copy of the rule with a Dockerfile that matches:

https://semgrep.dev/s/qBxx

**Expected behavior**
The rule should not consider `HEALTHCHECK CMD` as an instance of `CMD` and the above Dockerfile should not match. Something like this:

https://semgrep.dev/s/zov1

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
N/A

**Use case**
Correct handling of newer Dockerfiles.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1427/genericdockerfilecorrectnessmultiple-cmd-instructions-does-not-support. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by thomdixon** [comment]
This was fixed in https://github.com/returntocorp/semgrep-rules/pull/2117
