### ISSUE TITLE
Java cannot match arbitrary long package names

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#5420]
**Describe the bug**
In java it is not possible to match an arbitrarily long package such as `package org.apache.examples.struts.actions.data;`.

**To Reproduce**
https://semgrep.dev/orgs/ben-elttam/editor/s/ben-elttam:convention-annotation-package-info

**Expected behavior**
It should be possible to use a pattern like `package $...PACKAGE;` or even `package $PACKAGE;` that will bind to the package name (e.g.  `org.apache.examples.struts.actions.data`).

**Screenshots**
N/A.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
semgrep 0.94.0 (latest stable release at the time).

**Use case**
What will fixing this bug enable for you?

This will allow matching annotations on packages like:

```java
@Namespace("blah")
package org.apache.examples.struts.actions.data;
```

Capturing the package's name for use in the rule's message.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1431/java-cannot-match-arbitrary-long-package-names. _Note_: this link is for r2c use only and is not accessible publicly.
