### ISSUE TITLE
Pip-installed Semgrep 0.95 fails on Mac M1

### ISSUE THREAD

**Issue by lukaspiatkowski** [semgrep/semgrep#5423]
**Describe the bug**
Semgrep 0.95 installed using `pip` fails (as opposed to `brew` installed) on commands that invoke `semgrep-core` with error `Library not loaded: /usr/local/lib/libtree-sitter.0.dylib`

**To Reproduce**
1. Clone a repo (e.g. `gh repo clone returntocorp/semgrep`)
2. `python -m venv venv`
3. `source ./venv/bin/activate`
4. `pip install semgrep`
5. `semgrep --version` should show 0.95.0
6. `semgrep --config auto .` should fail with https://gist.github.com/e08c4638188392d3487a550ca3b62136

**Expected behavior**
Expected to succeed with (output taken with semgrep 0.95.0 installed using `brew install semgrep`): https://gist.github.com/12cd08a52d3501be1dde23b6f3e79803

**Screenshots**
<img width="1058" alt="Screenshot 2022-06-03 at 09 55 55" src="https://user-images.githubusercontent.com/4467402/171812889-b525ec4e-8a02-44a7-a2d8-5678adc3f754.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Official binary from `pip`.

**Use case**
Using `pip` distributed semgrep on Mac M1s instead of `brew`, which would provide a more conceise environment across M1s, Intel Macs and Linux machines.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1434/pip-installed-semgrep-095-fails-on-mac-m1. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ajbt200128** [comment]
We identified the issue causing this! Will be fixed in the next version (next tuesday)
