### ISSUE TITLE
internal: enable the test suite Unit_metachecking.tests

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#5432]
I found out during https://github.com/returntocorp/semgrep/pull/5431 that the test suite for metachecking wasn't executed. We need to [comment out a line](https://github.com/returntocorp/semgrep/blob/0b7bf3fa27bdf02b7e494d56e1b5429830b33f25/semgrep-core/tests/Test.ml#L69) and fix the test that's failing.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1436/internal-enable-the-test-suite-unit-metacheckingtests. _Note_: this link is for r2c use only and is not accessible publicly.
