### ISSUE TITLE
metavariable-pattern not flagging with PHP code

### ISSUE THREAD

**Issue by colleend** [semgrep/semgrep#5443]
**Describe the bug**
Metavariable-pattern is flagging PHP code with 'generic' mode, but not with 'php' mode.

**To Reproduce**
For instance, this doesn't flag: https://semgrep.dev/s/WRD2

But this does: https://semgrep.dev/s/02Wj

**Expected behavior**
Would expect it to flag with php as the language.

**Priority**
How important is this to you?
- [ ] P0: blocking me from making progress
- [X] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1448/metavariable-pattern-not-flagging-with-php-code. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
@colleend you know that for seceng issues we now use https://linear.app/r2c/project/support-security-research-team-5beed2a5f2e7/PA ?
See https://www.notion.so/r2cdev/How-to-file-an-issue-with-us-00507e1a0be64cd9bbe165397e853ffe

**Comment by colleend** [comment]
Ah yes -- sorry, I totally forgot about this 😅  -- I'll update the issue on linear 👍 . Should I close this GH issue?
