### ISSUE TITLE
Go: Unable to match specific members within a struct initialization when using `pattern-inside`

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#5452]
**Describe the bug**
I'm having trouble matching specific `MemberName: Value` pairs when using a `pattern-inside` along with a `pattern` to match specific members of a struct.

**To Reproduce**
https://semgrep.dev/s/68B1

While playing around with it, I noticed that you can match the `MemberName`s, such as `ServerName` or `InsecureSkipVerify`, but not the `Value`s or `MemberName: Value` pairs.

**Expected behavior**
The `InsecureSkipVerify: true` should match

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Allow me to write more detailed Go rules

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1453/go-unable-to-match-specific-members-within-a-struct-initialization. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
Something like https://semgrep.dev/s/j44N should work---we probably don't try and parse a pattern as being a field right now, although we could change that if using a `metavariable-pattern` & `focus-metavariable` is an issue.

**Comment by enncoded** [comment]
Oh thanks! I didn't think of this. I'll see how far I can go with this for now, but I definitely do think that this is important to fix, as narrowing scope as much as possible using `pattern-inside` and using `pattern` to match internal stuff is a very common rule pattern.

**Comment by aryx** [comment]
We actually do parse the pattern as a field (see -dump_pattern with PartialSingleField). The problem is that the Composite Literal (the tls.Config {xxx}) is internally parsed as a function call with keyword arguments instead of a Record,
and so the PartialSingleField pattern does not match an ArgKwd.
I'll try to fix it by generating a Record. Not sure why we were not doing that in the first place.

**Comment by aryx** [comment]
Hmm I think it's because the composite literal can also be written with the "fields" unnamed as long as they are in the same order.
