### ISSUE TITLE
How can i use registry's rules in Air Gap Environment？

### ISSUE THREAD

**Issue by zhuxindong** [semgrep/semgrep#5457]
for example, i want to use registry's xss rules in an Air Gap Environment , i cannot run "semgrep --config "p/xss" because i cannot access to the internet.
so ,can i download the rules in another computer with internet and transport to Air Gap Environment

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1455/how-can-i-use-registrys-rules-in-air-gap-environment？. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
yes you can curl the rules from the registry. I think curl semgrep.dev/s/p/xss
or something like that. I never remember the exact URL.

**Comment by aryx** [comment]
@s-santillan we constantly get this question so maybe we could add a FAQ or update the registry section in semgrep-docs to cover this case.

**Comment by zhuxindong** [comment]
> yes you can curl the rules from the registry. I think curl semgrep.dev/s/p/xss or something like that. I never remember the exact URL.

yeah, i try to curl semgrep.dev/s/p/xss but got nothing or something error, does it have a pacakge or tar package that can use in Air Gap Environment

**Comment by aryx** [comment]
it's c/, for curl, I should have remembered.
curl https://semgrep.dev/c/p/xss
