### ISSUE TITLE
Concerns around --config auto

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#5464]
From https://github.com/returntocorp/semgrep/issues/4460 

There are concerns re: auto config's default behavior. Opening this issue to track.

Main issue is around config auto sending information without a confirmation step.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1467/concerns-around-config-auto. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ievans** [comment]
We removed this functionality quite a while back, so closing this issue.
