### ISSUE TITLE
(docker) semgrep working directory location changed without notice

### ISSUE THREAD

**Issue by JosiahOne** [semgrep/semgrep#5479]
**Describe the bug**
We run semgrep in CI using the `returntocorp/semgrep` docker image (latest tag).

Today, CI started failing with the following error:

```
WARNING: unable to find a config; path `sep-semgrep-rules` does not exist (since you are running in docker, you cannot specify arbitrary paths on the host; they must be mounted into the container)
invalid configuration file found (1 configs were invalid)
7
```

Which was quite surprising. All previous semgrep versions (including 0.96.0) worked perfectly fine.

Upon local testing, it seems that the working directory must've changed in the 0.97.0 docker image. We were using a relative location for the `config` directory (e.g. `--config semgrep-rules`) rather than `/src/semgrep-rules`). If I switch the `--config` location to be an absolute path, things work fine. 

**To Reproduce**

Create working directory with semgrep rules in `semgrep-rules`. Run:

`docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep --config=semgrep-rules`

(That command will work fine in all prior semgrep versions, but will break in 0.97.0)

**Expected behavior**
Ideally, the behavior wouldn't have stopped working at all.

I understand not wanting users to rely on relative paths (not sure why we were), but this should've been noted in the documentation (https://semgrep.dev/docs/getting-started/).

In addition, the behavior change should've first been noted as a deprecation warning when running similar to what was done for the entrypoint change recently made.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
semgrep docker image running on MacOS and GitLab CI.

**Use case**
At this point nothing since we had to change our config anyway. Reverting the change quickly may prevent other users/customers from having CI failures.

Updating the documentation to specify that you should not use relative paths will likely prevent future inconveniences by users.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1482/semgrep-working-directory-location-changed-without-notice. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
Hmm this change was unexpected 👀

**Comment by underyx** [comment]
Some context:

The docker working directory logic was updated by this commit (not with this intention though): https://github.com/returntocorp/semgrep/pull/5442/commits/6ef4d854f2251a0c46672647406a868d500be26a

And an explanation I had sent on slack:

> We had a behavior to exit with a "mount your stuff" error message whenever /src doesn't exist in a docker execution. But there were two issues:
> - This would theoretically fire even if the scan had an explicit target such as -
> - We created /src in the Dockerfile so in practice the error would never fire
>
> I accidentally fixed the second point while reworking the Dockerfile, so now I have to fix the first point as well :D
>

**Comment by underyx** [comment]
I think the issue is that I removed the `WORKDIR /src` instruction from the Dockerfile to make it possible for us to detect whether `/src` was mounted or not.

**Comment by JosiahOne** [comment]
Additional side effect for anyone who stumbles across this:

After changing our semgrep command to use absolute paths, things were still failing because our ignore rules no longer worked (because now "src" was being prepended to the rule ids on the semgrep side but our comments did not include this).

To fix that I had to add the --no-rewrite-rule-ids flag to our command.

**Comment by underyx** [comment]
The directory should still be changed by our code to `/src` later, but I think that doesn't happen because the function only does it `if env.in_docker and not env.in_gh_action`. @JosiahOne are you running in github actions?

**Comment by JosiahOne** [comment]
Hey @underyx ! I am not. We are running in GitLab CI using docker.

**Comment by underyx** [comment]
@JosiahOne I created a PR which should fix this regression. However, for some reason, I'm unable to reproduce the issue you're describing.

```terminal
/tmp/one via 🐍 v3.10.4
❯ mkdir semgrep-rules

/tmp/one via 🐍 v3.10.4
❯ curl https://semgrep.dev/c/p/python > semgrep-rules/python.yaml

/tmp/one via 🐍 v3.10.4 took 4s
❯ echo "5 == 5" > one.py

/tmp/one via 🐍 v3.10.4
❯ docker run -v ${PWD}:/src --rm --pull always returntocorp/semgrep:latest semgrep --config semgrep-rules
latest: Pulling from returntocorp/semgrep
Digest: sha256:0489a9b14da187becde11e492741508b9cca5cf6a7a4d63d3e116dd2e603c593
Status: Image is up to date for returntocorp/semgrep:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Scanning 1 file with 34 python rules.

Findings:

  one.py
     semgrep-rules.python.lang.correctness.useless-eqeq.useless-eqeq
        This expression is always True: `5 == 5` or `5 != 5`. If testing for floating point NaN, use
        `math.isnan(5)`, or `cmath.isnan(5)` if the number is complex.
        Details: https://sg.run/GeAp

          1┆ 5 == 5

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 34 rules on 1 file: 1 finding.
```

**Comment by underyx** [comment]
more specifically, where is the `sep-` in this path coming from?

> ```
> WARNING: unable to find a config; path `sep-semgrep-rules` does not exist
> ```

**Comment by JosiahOne** [comment]
> more specifically, where is the `sep-` in this path coming from?
> 
> > ```
> > WARNING: unable to find a config; path `sep-semgrep-rules` does not exist
> > ```

Sorry I forgot to modify my later examples to use the sep- prefix. You can consider that to be the same as "semgrep-rules".

I can create an example next week if that's helpful!
