### ISSUE TITLE
Add Support for toplevel Java Record declarations

### ISSUE THREAD

**Issue by Taucher2003** [semgrep/semgrep#5480]
**Describe the bug**
Records can't be parsed and result in an error

**To Reproduce**
https://semgrep.dev/playground/s/9np8

**Expected behavior**
The records can be parsed

**Screenshots**
| Erroring in Semgrep | Validated as valid syntax in IntelliJ |
|---|---|
| ![image](https://user-images.githubusercontent.com/39954661/172918800-9db1195c-61bc-408b-941f-dafafc8d741f.png) | ![image](https://user-images.githubusercontent.com/39954661/172919280-7d7f6085-6066-412d-84e6-cc67cbfaa5fa.png) |

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

It's annoying, but as it does not affect the pipeline status in GitLab, it doesn't affect the workflow

**Environment**
*provided reproduction in semgrep.dev*

**Use case**
It will allow a warn free scan of the code

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1483/add-support-for-java-records. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
Record can be parsed, they just currently have to be nested inside another class.
This works for example: https://semgrep.dev/s/dNEP

**Comment by aryx** [comment]
I'm not sure what's the official Java grammar spec says.

**Comment by aryx** [comment]
https://openjdk.java.net/jeps/359: "Beyond the restrictions above, records behave like normal classes: they can be declared top level or nested," so I guess they can

**Comment by aryx** [comment]
It works now. I think @bmahe fixed it a long time ago but we forgot to close the issue.
