### ISSUE TITLE
Upgrade to ocaml 4.14

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#5483]
Why:

- (add reasons)
- support for ocamldebug!
- stay on top of things

Progress so far:
- ocaml-layer published an updated docker image with ocaml 4.14 but it causes a build error in semgrep: https://github.com/returntocorp/semgrep/runs/6810560366?check_suite_focus=true (see also below*)
- @aryx pinned the CI images to a version that won't change and uses ocaml 4.12 (https://github.com/returntocorp/semgrep/pull/5476)

*error message:
```
Install pfff dependencies
The following dependencies couldn't be met:
  - pfff -> ppxlib = 0.20.0 -> ocaml < 4.13
      base of this switch (use `--unlock-base' to force)
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1485/upgrade-to-ocaml-414. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by underyx** [comment]
I think this error is fixed by this PR: https://github.com/returntocorp/semgrep/pull/5455
