### ISSUE TITLE
Semgrep --test should scan test file regardless of `paths` directive

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#5487]
**Is your feature request related to a problem? Please describe.**

When running `semgrep --test` for a rule file `rule.yml` it can find the semgrep unit test file, like `rule.test.yml`, or `rule.java`. If the rule is using `paths.include` directive, the unit test file must be included in the list.

https://semgrep.dev/docs/writing-rules/rule-syntax/#limiting-a-rule-to-paths

e.g. the rule in file `web-xml.yml` must have:

```yaml
paths:
  include:
    - web.xml
    # unit test file
   - web-xml.xml  # <---
```

Without allow-listing the test file, the rule won't run, the rule(s) won't be tested.

**Describe the solution you'd like**

Since semgrep is already finding the file for the unit test to run it, I would like in test mode to magically bypass the `paths.include`, and scan the file.

e.g. I don't want to have to manually add the unit test files to the allow-list, I want them automagically included only when in test mode.

**Describe alternatives you've considered**

**Use case**
This will enable better Quality of Life.

**Additional context**

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1488/semgrep-test-should-scan-test-file-regardless-of-paths-directive. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by fopina** [comment]
I was almost opening a duplicate from this but I'd like to add an alternative:

Instead of `--test` simply ignoring `paths` constraints (which sounds reasonable and probably works well), there's the option to leverage the fact that everything matching `rule-name*` is initially assessed as test code.

So using a file structure such as below would also work:

```
./my-rule-a/mymodule/views.py
./my-rule-a.yaml
```

This would allow not only to make sure path constraints are not broken (in some rule definition change / regression) but also other more complex scenarios (either for join-mode or deepsemgrep)

Sample rule/test files in https://github.com/fopina/delme/tree/main/semgrep_cannot_test_path_includes

**Comment by ben-elttam** [comment]
> Instead of --test simply ignoring paths constraints (which sounds reasonable and probably works well), there's the option to leverage the fact that everything matching rule-name* is initially assessed as test code.

This is what I wanted. If `rule-name.yml` is going to find `rule-name*` as a test, I want that to be scanned regardless of the rule's `paths.include` directive.

I do like the idea of the tests being a directory tree, which could have many files.

**Comment by fopina** [comment]
> This is what I wanted

Your description was quite clear, I was just re-iterating it (and rephrasing I suppose) to introduce another alternative.

I've submitted a PR on that alternative (linked to this issue), hopefully there'll be feedback on it :)

Btw, if you do need multiple files for the same rule (that do not require a file tree) you can have multiple `rule-name.WHATEVER.extension` files and all will be picked up by `--test` for `rule-name.yaml`.

I think it might be a side-effect of the current test file discovery implementation but it's a very nice one. It's not documented (only `.test.yaml`) so I have opened #6880 hoping that it will be documented and, therefore, not removed in the future 🙏

**Comment by ben-elttam** [comment]
> Btw, if you do need multiple files for the same rule (that do not require a file tree) you can have multiple `rule-name.WHATEVER.extension` files and all will be picked up by `--test` for `rule-name.yaml`.

I didn't know this, so appreciate you've opened #6880 about it.

**Comment by ben-elttam** [comment]
Whilst the exact suggestion in the original post of ignoring the `paths.include` and scanning the matched test file, still doesn't work (v1.6.0). The enhancement in #6883 to allow scanning directories works well and has the added benefit of allowing multiple tests per rule file.

If a rule `web-xml.yaml` has:

```yaml
id: something-else
paths:
  include:
    - web.xml
```

The test file(s) can be put in the `web-xml` or a subdirectory of `web-xml`, e.g. `web-xml/web.xml` or `web-xml/sub/web.xml`.
