### ISSUE TITLE
How can I load and run all PHP rules?

### ISSUE THREAD

**Issue by CaledoniaProject** [semgrep/semgrep#5497]
I'm trying to run all the rules beginning with `php.`, is that supported? 
I've tried `semgrep --config "p/php."` and this does not work

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1491/how-can-i-load-and-run-all-php-rules. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
Yes. You can run `semgrep scan --config r/php`
