### ISSUE TITLE
Metavariables do not work for object reference in Scala

### ISSUE THREAD

**Issue by Strunevskiy** [semgrep/semgrep#5506]
**Describe the bug**
Metavariables do not work for object reference in Scala

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
The link is attached https://semgrep.dev/s/zojz

**Expected behavior**
Based on the link, there should be two matches for the pattern, line 3 and line 8.

**Screenshots**

**What is the priority of the bug to you?**
- [ ] P1: important to fix or quite annoying

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
It allows us to find usage of methods in code base.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1496/metavariables-do-not-work-for-object-reference-in-scala. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Strunevskiy** [comment]
Is there any update on the issue ?

**Comment by aryx** [comment]
It's probably because class fields declared via the class parameters are not currently handled. Only Scala has this feature I think.
