### ISSUE TITLE
Semgrep does not support named parameters in PHP

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#5508]
**Describe the bug**
PHP parsing does not support named parameters in functions [(supported in PHP 8+)](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments)

in PHP 8 and higher, the following is valid PHP:

```php
setcookie("name","value",0,secure:true);
```

Currently, this fails to parse with an "invalid PHP" error in Semgrep as of 0.97.0

```
[ERROR] Pattern parse error in rule untitled_rule:
 Invalid pattern for PHP:
--- pattern ---
setcookie(...,secure:true)

--- end pattern ---
Pattern error: Parsing.Parse_error
Engine(Pattern parse error)
...
```

**To Reproduce**
https://semgrep.dev/s/ykv8

**Expected behavior**
This should parse - it's valid PHP for PHP 8 and above.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev, CLI version 0.97.0

**Use case**
This is a requirement for T1 PHP rule coverage.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1497/semgrep-does-not-support-named-parameters-in-php. _Note_: this link is for r2c use only and is not accessible publicly.
