### ISSUE TITLE
Boolean constant propagation does not behave correctly in PHP

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#5509]
**Describe the bug**
Constant propagation with boolean values does not behave as advertised in PHP.

A rule like 

**To Reproduce**
To illustrate the issue, see the following (correct) Python example:
https://semgrep.dev/s/kPvX

Identical behavior in PHP is not matched as expected:
https://semgrep.dev/s/w2vx

**Expected behavior**
Boolean constant propagation is consistent across languages.

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev, CLI 0.97.0

**Use case**
Required for T1 PHP vuln coverage & PHP GA.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1498/boolean-constant-propagation-does-not-behave-correctly-in-php. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sjord** [comment]
I expect the same applies to `null`, which should also have its own AST node.
