### ISSUE TITLE
[Go] Support typed metavariables in function parameters

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#5512]
**Describe the bug**
Semgrep currently throws an error when writing a pattern that uses typed metavariables in a function parameters.

**To Reproduce**
https://semgrep.dev/s/dNLP

**Expected behavior**
Typed metavariables should work in function parameters.

**Screenshots**
![image](https://user-images.githubusercontent.com/14846866/173470009-db2ce2ce-f082-48ec-a222-fe635c905a2e.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1500/[go]-support-typed-metavariables-in-function-parameters. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
discussed on linear, so closing here.

**Comment by aryx** [comment]
But essentially you don't need (and can't use) typed metavariables in a parameter context; just use parameter definitions.
