### ISSUE TITLE
Pattern match not applied inside Python "with" statement

### ISSUE THREAD

**Issue by alexmac** [semgrep/semgrep#5513]
**Describe the bug**
semgrep doesn't match inside a with statement

**To Reproduce**
https://semgrep.dev/s/J17o

**Expected behavior**
A pattern of "foo()" should match in a block of code like this:

```
with foo():
    pass
```

**What is the priority of the bug to you?**
P2

**Environment**
official docker image / semgrep.dev

**Use case**
catching deprecated function used inside with statements

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1501/pattern-match-not-applied-inside-python-with-statement. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
Looks like we discard the expression if it isn't renamed:

```py
with foo():
    pass
```
results in
```
Pr([OtherStmtWithStmt(OSWS_With, [], Block([OtherStmt(OS_Pass, [Tk(())])]))])
```

whereas 

```py
with foo() as bar:
    pass
```

results in

```
Pr(
  [OtherStmtWithStmt(OSWS_With,
     [E(
        LetPattern(
          PatId(("bar", ()),
            {id_info_id=2; id_hidden=false; id_resolved=Ref(None); id_type=Ref(None); id_svalue=Ref(None); }),
          Call(
            N(
              Id(("foo", ()),
                {id_info_id=1; id_hidden=false; id_resolved=Ref(None); id_type=Ref(None); id_svalue=Ref(None); })), [
            ])))], Block([OtherStmt(OS_Pass, [Tk(())])]))])
```

This should just require a change here:

https://github.com/returntocorp/semgrep/blob/4ef36464d364b3f8d2bbf531b71e2ed618917204/semgrep-core/src/parsing/pfff/Python_to_generic.ml#L725-L729

This should probably be `None -> [ G.E v1 ]`.
