### ISSUE TITLE
Invalid Version in GitLab Sast Output

### ISSUE THREAD

**Issue by spaceraccoon** [semgrep/semgrep#5514]
**Describe the bug**
The GitLab Sast JSON output produced by semgrep has version set to `2.0` (https://github.com/returntocorp/semgrep/blob/develop/semgrep/semgrep/formatter/gitlab_sast.py#L103), but latest versions of the GitLab SAST schema expect semver format `x.x.x`, leading to the following warning message:

```
[Schema] Version 2.0 for report type sast has been deprecated, supported versions for this report type are: 14.0.0, 14.0.1, 14.0.2, 14.0.3, 14.0.4, 14.0.5, 14.0.6, 14.1.0, 14.1.1
[Schema] property '/version' does not match pattern: ^[0-9]+\.[0-9]+\.[0-9]+$
```

**To Reproduce**
Run Semgrep CI using the sample CI config (https://semgrep.dev/docs/semgrep-ci/sample-ci-configs/) with a test repo with a vulnerable code snippet. The report will be generated along with the version warning.

**Expected behavior**

Version number output should be a support version and the warning message should no longer appear.

**Screenshots**

![warning_message](https://user-images.githubusercontent.com/18413849/173511790-2efc5752-884e-418f-b76e-ce5cc14a23d0.png)

**What is the priority of the bug to you?**

This may lead to ingestion failure in the future as per the warning message.

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1502/invalid-version-in-gitlab-sast-output. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spaceraccoon** [comment]
Note: It seems that deprecated versions will not be ingested, so this could be a breaking issue soon. https://gitlab.com/gitlab-org/gitlab/-/merge_requests/86865

**Comment by brendongo** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/5532
