### ISSUE TITLE
Improve Error Message on use of deprecated pattern-where-python

### ISSUE THREAD

**Issue by mmcqd** [semgrep/semgrep#5533]
**Describe the bug**
The error thrown by semgrep-core when it tried to analyze a rule containing pattern-where-python is confusing and does not properly indicate that the feature is deprecated.
```
Error:  Fatal error at line :1:
 (Failure
  "convert_extra: TODO: (Rule.PatWherePython \"vars['$KEY'].strip('\\\"') == vars['$ATT']\")")
====[ BEGIN error trace ]====
Raised at Stdlib__string.index_rec in file "string.ml", line 115, characters 19-34
Called from Sexplib0__Sexp.Printing.index_of_newline in file "src/sexp.ml", line 113, characters 13-47
=====[ END error trace ]=====
```

**Expected behavior**
Semgrep should produce a warning about the deprecation/removal of this feature

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1507/improve-error-message-on-use-of-deprecated-pattern-where-python. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
This has been fixed a few days ago.

**Comment by aryx** [comment]
Here: https://github.com/returntocorp/semgrep/pull/5496
maybe you have an old semgrep-core in your PATH.
