### ISSUE TITLE
Java constructors with modifiers patern not detected

### ISSUE THREAD

**Issue by vladiavramov** [semgrep/semgrep#5558]
**Describe the bug**
When trying to match a pattern to a constructor with modifier inside a class (e.g. public House) the system returns a parse error.

**To Reproduce**
Run the example. (https://semgrep.dev/s/B1R6)
If it's run without the public modifier the patten is captured.

**Expected behavior**
The expected behaviour is for the pattern to be matched.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Tested through the Playground, but otherwise used through CodeGrade.

**Use case**
The bug fix would help in auto-grading code for correct usage of modifiers.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1516/java-constructors-with-modifiers-patern-not-detected. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by backcover7** [comment]
This bug also blocks me when writing rules. Is there any ETA for this bug fix?

**Comment by nmote** [comment]
@backcover7 I have what I believe to be a reasonable fix almost ready for review. It's currently blocked by a tangentially-related problem. I think the fix will be available either in next week's release or the week after.

**Comment by backcover7** [comment]
> @backcover7 I have what I believe to be a reasonable fix almost ready for review. It's currently blocked by a tangentially-related problem. I think the fix will be available either in next week's release or the week after.

@nmote Thank you for the notification. Would you mind linking to a valid playground case here when the fix is applied?

**Comment by nmote** [comment]
Sure, will do

**Comment by nmote** [comment]
A little late to the game here, but this is out in v0.112.x. I should have a fix for #6051 shortly.
