### ISSUE TITLE
Executable check does not work correctly in docker

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#5560]
TargetManager attempts to determine the language for files without an extension by reading the shebang line (e.g. `#!/usr/bin/python` as first line). Shebang lines are only supposed to be read from executable files. TargetManager uses `os.access` to check whether a file is executable. However, this doesn't work correctly in a docker on files mounted from the host system:

```
$ touch hello.txt
$ docker run --rm -v "$PWD:/foo" -w "/foo"  python python3 -c 'import os; print(os.access("hello.txt", os.X_OK))'
True
```

The result is that semgrep checks the shebang line of every file, and potentially scans more files.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1517/executable-check-does-not-work-correctly-in-docker. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by underyx** [comment]
Hmm, this sounds bad. Do you have any context or explanation as to why this doesn't work via docker mounts? 😕 I'm not quite sure what we can do as it stands

**Comment by Sjord** [comment]
Perhaps related: [incorrect accessible() implementation · Issue #43724 · moby/moby](https://github.com/moby/moby/issues/43724)

**Comment by Sjord** [comment]
[access() reports file on bind mount as executable when it is not · Issue #43726 · moby/moby](https://github.com/moby/moby/issues/43726)

**Comment by underyx** [comment]
Thank you for volunteering so much time to track this down! I see they had you move it to https://github.com/docker/for-mac/issues/6367 now.

**Comment by Sjord** [comment]
So, the behavior of `access` in Docker-for-mac is certainly peculiar, but I think that `access` is not the correct way to check whether a file is executable for the purposes of semgrep. From POSIX 2001:

> If the process has appropriate privileges, an implementation may indicate success for X_OK even if none of the execute file permission bits are set.

From the [Linux man page](https://man7.org/linux/man-pages/man2/access.2.html):

> access() does not answer the "can I read/write/execute this file?" question. It answers a slightly different question: "(assuming I'm a setuid binary) can the user who invoked me read/write/execute this file?", which gives set-user-ID programs the possibility to prevent malicious users from causing them to read files which users shouldn't be able to read.

Also, `access` on Linux marks files as non-executable when they are on a volume mounted with NOEXEC, but this doesn't make sense for semgrep.

So I think just doing `stat` and checking the bits is better.

Another possibility is to remove the check, and just try to read the shebang of every file, but that may have a negative performance impact.

**Comment by vivekkhimani** [comment]
https://github.com/returntocorp/semgrep/pull/5703. Can I get a review @underyx?

**Comment by underyx** [comment]
@Sjord this should be fixed in returntocorp/semgrep:edge

If you have a reproduction locally, could you check if the fix worked?

**Comment by Sjord** [comment]
This now works as expected in returntocorp/semgrep:edge.

**Comment by underyx** [comment]
Wonderful! Thanks for verifying, and thanks @vivekkhimani for the fix!
