### ISSUE TITLE
Semgrep's --help needs improvement

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#5563]
**Is your feature request related to a problem? Please describe.**
Semgrep contains undocumented command flags that are not displayed. In the docs it mentions running `semgrep -e '$X == $X' --lang=py path/to/src` what does the -e flag do? If I run `semgrep --help` it doesn't show that flag, and it's not one of the listed "commands". Who knows how many other flags there are that I can use to run. I shouldn't have to dig into the source code to understand this.

**Describe the solution you'd like**
List the other flags that semgrep has under "Options:" when I typed `semgrep -h`

**Use case**
Understanding how to use semgrep from the command line as a *user*

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1519/semgreps-help-needs-improvement. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
fyi I believe this is documented under `semgrep scan --help`, so it might just be a matter of making it clear that `scan` is the default command.

**Comment by efortuna** [comment]
yes, we should do that, then. (and maybe list scan's options under the "Option" section)

**Comment by brendongo** [comment]
IMO we should just not have a default command. More discussion here: https://returntocorp.slack.com/archives/C6A1GN4P3/p1648622835810529

**Comment by efortuna** [comment]
@brendongo amen.

**Comment by aryx** [comment]
maybe just adding in the default --help message:

"Note that by default semgrep run the scan subcommand; to get more information
about this command, run semgrep scan --help"

**Comment by efortuna** [comment]
Sorry, why is this assigned to me?

**Comment by efortuna** [comment]
Sorry, why is this assigned to me? @aryx

**Comment by aryx** [comment]
It's a documentation issue, so anybody can fix those kinds of things.
I can assign the issue to brendon, but I'm  pretty sure he will not fix it given his opposition so it's either
we close the issue or someone who care enough make a PR to fix the documentation.

**Comment by aryx** [comment]
Given you're the one who raised the issue, you might be the best one to craft/improve the help message.
But I can make the PR if you want.

**Comment by brendongo** [comment]
I can take it on.

**Comment by brendongo** [comment]
```
Usage: semgrep [OPTIONS] COMMAND [ARGS]...

  To get started quickly, run `semgrep scan --config auto`

  Run `semgrep SUBCOMMAND --help` for more information on each subcommand

  If no subcommand is passed, will run `scan` subcommand by default

Options:
  -h, --help  Show this message and exit.

Commands:
  ci            The recommended way to run semgrep in CI
  login         Obtain and save credentials for semgrep.dev
  logout        Remove locally stored credentials to semgrep.dev
  lsp           [EXPERIMENTAL] Start the Semgrep LSP server.
  publish       Upload rule to semgrep.dev
  scan          Run semgrep rules on files
  shouldafound  Report a false negative in this project.
```
@efortuna do you think above helptext solves the need?

**Comment by efortuna** [comment]
It does, @brendongo, thanks. I have one countersuggestion. _Ideally_, so as to not clutter up that top section I'd have it read:

```
Usage: semgrep [OPTIONS] COMMAND [ARGS]...

  To get started quickly, run `semgrep scan --config auto`

Options:
  -h, --help  Show this message and exit.

Commands:
  ci            The recommended way to run semgrep in CI
  login         Obtain and save credentials for semgrep.dev
  logout        Remove locally stored credentials to semgrep.dev
  lsp           [EXPERIMENTAL] Start the Semgrep LSP server.
  publish       Upload rule to semgrep.dev
  scan          [DEFAULT] Run semgrep rules on files. Aliases as semgrep [OPTIONS] [ARGS]. 
  shouldafound  Report a false negative in this project.
```

as I think the semgrep SUBCOMMAND --help sentence is _fairly_ expected. (others could argue with me on this one). 
BUT I poked around your codebase, and changing that top line without having it also display when you run `semgrep scan --help` seems like it would be nontrivial given the library (`click`) you're using. If you don't mind having that display, then we can probably just make that change in scan.py.

Also, could we consider putting `scan` at the top of the commands list (I know it breaks alphabetical order, but if it's the default, I think there could be value in this.) if this is Simply Not Done in commandline helps, then please disregard.

My comments above are just suggestions, and I think what you have in your PR is workable.

---

Lastly, I think the other underlying issue (which I didn't fully express in my initial bug report, apologies) is we don't give usage commands for anything other than the top command `semgrep`, which isn't super useful itself since we don't know what the arguments are. Here's what you get if you run any command without the correct arguments:

```
$ semgrep -e
Error: Option '-e' requires an argument.
```

I wonder what my argument is for?  I'd like to see:

```
$ semgrep -e
Error: Option '-e' requires an argument.
Usage: semgrep -e [TEXT]
```
(you could even have it say `Run semgrep scan --help for more information.` after that last line)
But these changes seem possibly challenging given the library you're using to handle commands.

I can file this part as a separate bug if you'd like.

**Comment by brendongo** [comment]
Yes a little non trivial to dig into click internals probably

**Comment by brendongo** [comment]
Yes filing a separate bug would be great

**Comment by brendongo** [comment]
@efortuna re: your counter suggestion: what you pasted was exactly what semgrep --help prints out now if I'm not mistaken?

**Comment by efortuna** [comment]
@brendongo for the counter suggestion, check the description of *scan* specifically. It's different. It reads:
`  scan          [DEFAULT] Run semgrep rules on files. Aliases as semgrep [OPTIONS] [ARGS]. `

**Comment by brendongo** [comment]
Oh I see. I feel lukewarm. Clearly I didn't even notice the difference.

**Comment by efortuna** [comment]
I also said: 

> Also, could we consider putting scan at the top of the commands list (I know it breaks alphabetical order, but if it's the default, I think there could be value in this.)

```
  scan          [DEFAULT] Run semgrep rules on files. Aliases as semgrep [OPTIONS] [ARGS]. 
  ci            The recommended way to run semgrep in CI
  login         Obtain and save credentials for semgrep.dev
  logout        Remove locally stored credentials to semgrep.dev
  lsp           [EXPERIMENTAL] Start the Semgrep LSP server.
  publish       Upload rule to semgrep.dev
  shouldafound  Report a false negative in this project.
```

Either way, If you're trying to look at your available options and scanning through things for the first time, I'm pretty sure you're going to at least look at "[DEFAULT]"
