### ISSUE TITLE
Include regression testing across a large corpus for parser errors as part of release process

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#557]
#555 noted a regression from 0.4.9 to develop in the parsing infrastructure.

It would be fairly easy for us to track the number of parsed errors (ideally baseline = 0) across a bunch of large / popular repos for our supported languages (we could even use platform for this). I know @aryx did this work when initially adding support so we should start by just setting up a test script we can run as part of the release process that makes sure a trivial pattern can successfully run across that pinned set of repos.

We could make this release step also give us stats on performance of the sgrep-rules suite, to help with issues like https://github.com/returntocorp/semgrep/issues/520

**Comment by DrewDennison** [comment]
@brendongo is this done?

**Comment by brendongo** [comment]
Yep. There are still some repos that fail to parse but will work to catch any regressions for now: https://github.com/returntocorp/semgrep/pull/571
