### ISSUE TITLE
Parsing error with Java

### ISSUE THREAD

**Issue by nusco** [semgrep/semgrep#5586]
**Describe the bug**
Semgrep seems to be OK with giving a body to abstract Java methods, which should be a syntax error.

**To Reproduce**
In the Semgrep playground, in "simple mode", set the language to "Java" and the pattern to "class C". Run it over this code:

    abstract class Vehicle {
        abstract void accelerate(int amount) {};
    }

The code above is illegal. It would make the Java compiler fail with an `abstract methods cannot have a body` error. By contrast, Semgrep seems to be fine with it, and it reports a match.

Semgrep also seems to have other similar issues around abstract methods. For example, it has no issues with `private abstract` methods, which would cause a compilation error.

**Expected behavior**
I'd expect Semgrep to complain of a syntax error in the Java code.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1542/parsing-error-with-java. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
semgrep is not a compiler or type checker. It does not try to check the things that your compiler already do.

**Comment by nusco** [comment]
I find this a bit confusing, because matter of fact, Semgrep _does_ check my syntax all the time. I understand that you have to draw a line somewhere, but it's not clear to me as a user where that line is. I started by assuming that Semgrep stops at about lexer level, but then I was surprised by its ability to spot syntax errors–except when it doesn't, and then I'm left wondering why it didn't.

That being said, I do see that it's not possible to take a sweeping "all or nothing" decision on catching syntax errors. Thank you for clarifying why this issue is out of scope.

**Comment by aryx** [comment]
Actually semgrep does not stop at the syntax level; it also does some semantic analysis (hence the name semgrep) so that it can handle constant propagation, some form of type inference, name aliasing, etc.

Semgrep's goal is not to report syntax error, but to perform its role, that is to find matches, it needs to parse the code and understand the code. But knowing/enforcing that methods in abstract classes can't have a body does not really help semgrep, so we don't really care.

**Comment by aryx** [comment]
The line is whatever semgrep needs to be able to find matches to the rules you write.
