### ISSUE TITLE
Taint mode does not interact correctly with Java iterators

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#5590]
**Describe the bug**
Individual items referenced by an iterator of a tainted collection should propagate taint.  Currently, the following valid Java enumerator pattern does not propagate taint correctly if `getCollection(...)` is defined as a source:

```Java
for( Type t : Library.getCollection() ){
  sink(t);
}
```

**To Reproduce**
https://semgrep.dev/s/lJgG

**Expected behavior**
Individual objects created by a tainted iterator should be considered tainted.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev, Semgrep v 0.98.0

**Use case**
Security Research rule-writing for Java

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1546/taint-mode-does-not-interact-correctly-with-java-iterators. _Note_: this link is for r2c use only and is not accessible publicly.
