### ISSUE TITLE
Arrow functions sometime prevent matching

### ISSUE THREAD

**Issue by ristomcgehee** [semgrep/semgrep#5594]
**Describe the bug**
In PHP, when a file contains the arrow function syntax for anonymous functions (e.g. `fn($item) => $item > 3`), Semgrep is not able to match some patterns. There are still some patterns that are matchable with arrow functions in the file.

**To Reproduce**
This playground link shows a code snippet that contains an arrow function and is still able to match the pattern: https://semgrep.dev/s/chrismcgehee:arrow-func-matches

This playground link shows a code snippet that contains an arrow function and is not able to match the pattern: https://semgrep.dev/s/chrismcgehee:arrow-func-no-matches

This playground link shows a code snippet with no arrow function where it is able to match the pattern: https://semgrep.dev/s/chrismcgehee:no-arrow-func-matches

**Expected behavior**
Semgrep is able to match all patterns when an arrow function is present in the file.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
A higher percentage of our codebase will be able to be analyzed by Semgrep. Even with this issue, Semgrep still works on at least 95% of the files in our codebase.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1548/arrow-functions-sometime-prevent-matching. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sjord** [comment]
Thanks, @chrismcgehee. Semgrep has two parsers for PHP, pfff and tree-sitter. I guess the `fn` function is not implemented in pfff, so this forces the PHP file to be parsed using tree-sitter. The pattern is still parsed using pfff. There is a slight difference between these syntax trees, resulting in this bug. Specifically, pfff parses `$this` into `IdSpecial (This)`, and tree-sitter into `Id ("$this")`. These are different, so the pattern doesn't match.
