### ISSUE TITLE
Semgrep GUI interface prepends github link in findings even though the original repository is not from github

### ISSUE THREAD

**Issue by codedbrain** [semgrep/semgrep#5598]
**Describe the bug**
Findings section , https://semgrep.dev/orgs/xyz/findings , lists all of the findings. However, the hyperlink to project has link of github even though the repository is in bitbucket. I have integrated semgrep in bitbucket CI/CD. Now when I click on the individual finding, it takes me to github instead of bitbucket. 

I signed up on semgrep using github account gitxyz, the original organization name in bitbucket is bitxyz. Now the findings appear with link github.com/gitxyz/reponame instead of bitbucket.org/bitxyz/reponame.  

Please resolve the issue.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1550/semgrep-gui-interface-prepends-github-link-in-findings-even-though-the. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
We've created a ticket in our internal separate issue tracker for semgrep app
