### ISSUE TITLE
Output missed/incorrectly detected line in test rather than whole arrays

### ISSUE THREAD

**Issue by erwanlr** [semgrep/semgrep#5600]
**Is your feature request related to a problem? Please describe.**
When a test fails and there are numerous expected lines to be detected, the output is really not helpful and it's hard to quickly see which lines were missed and/or incorrectly detected:

```
	✖ test-rule    expected lines: [4, 7, 10, 13, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 51, 57, 59, 63, 67, 70, 73, 76, 78, 80, 83, 85, 87, 90, 93, 125],
reported lines: [4, 7, 10, 13, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47, 51, 57, 59, 63, 67, 70, 73, 76, 78, 80, 83, 85, 87, 90, 93, 125, 158]
```

**Describe the solution you'd like**
Do a diff of the arrays to output the missed lines (False Negative), as well as incorrectly detected (False Positive) ones when the test fails. e.g:

```
	✖ test-rule   Missed Lines: [44]
                      Incorrectly Detected Lines: [158] 
```

**Describe alternatives you've considered**
Checked the help (`semgrep test -h`) but there does not seem to be an option to have such output.

**Use case**
Won't have to spend some time trying to figure out the diff of the `expected lines` and `reported lines` and kill my eyes in the process

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1551/output-missedincorrectly-detected-line-in-test-rather-than-whole. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by erwanlr** [comment]
Thx a lot @vivekkhimani for this one, that's awesome!!!
