### ISSUE TITLE
yaml incorrect matching

### ISSUE THREAD

**Issue by raghavjain3** [semgrep/semgrep#5607]
**Describe the bug**
Run the sample snippet on [this](https://semgrep.dev/r?q=yaml.docker-compose.security.privileged-service.privileged-service) rule. The match extends beyond where it should to a comment and unnecessary whitespace.  

**To Reproduce**
https://semgrep.dev/r?q=yaml.docker-compose.security.privileged-service.privileged-service

**Expected behavior**
Last matched line should be `privileged: true`

**Screenshots**
<img width="1401" alt="image" src="https://user-images.githubusercontent.com/32291067/175169272-70e770aa-5db5-4e7a-9228-a5ceff8b3cf8.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1553/yaml-incorrect-matching. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by LewisArdern** [comment]
https://semgrep.dev/s/w2Rd

**Comment by mjambon** [comment]
I see this match with @LewisArdern 's link to the playground (https://semgrep.dev/s/w2Rd). Isn't it what we want?
![image](https://user-images.githubusercontent.com/343265/175606930-abea75dc-cf15-4d2f-8294-98e670a65c77.png)

**Comment by raghavjain3** [comment]
@mjambon yup @LewisArdern wrote a fixed rule!

previously, the example snippet [here](https://semgrep.dev/r?q=yaml.docker-compose.security.privileged-service.privileged-service) wasn't matching properly

**Comment by emjin** [comment]
@raghavjain3 Let me know if something still goes wrong here
