### ISSUE TITLE
Add pagination to the selection of GitLab groups

### ISSUE THREAD

**Issue by danymarques** [semgrep/semgrep#5625]
**Is your feature request related to a problem? Please describe.**
The page for selecting GitLab groups displays only the first 100 results. 

**Describe the solution you'd like**
It would be nice to have a pagination widget so you can select groups on subsequent pages.

**Describe alternatives you've considered**
An alternative could be to be able to add a GitLab group with its ID.

**Use case**
Be able to choose the correct group.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1564/add-pagination-to-the-selection-of-gitlab-groups. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by milanwilliams** [comment]
Hi @danymarques - thanks for creating the issue! Is this blocking your ability to set up Semgrep App? I'm tracking this internally on our backlog 😄

**Comment by danymarques** [comment]
Hi @milanwilliams,
Yes it is as the root level group is on the second page. 
It would be cool if you can do it soon :)
I would like to help you but as far as I know, the semgrep app is not open source right?

**Comment by brendongo** [comment]
@danymarques I believe this has been fixed

**Comment by danymarques** [comment]
I had a look now and I can confirm that it has been fixed. Thanks a lot!
