### ISSUE TITLE
$LINE has been added to the .semgrepignore list of ignored paths. Someone from app-sec may want to audit these changes.

### ISSUE THREAD

**Issue by HariSekhon** [semgrep/semgrep#5627]
**Describe the bug**

Semgrep is returning these code scanning errors:

```
$LINE has been added to the .semgrepignore list of ignored paths. Someone from app-sec may want to audit these changes.
```

**To Reproduce**

Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

Commit this file into any repo.

https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/.github/workflows/semgrep.yaml

**Expected behavior**

Firstly `$LINE has been added` is clearly an interpolation bug - it's generating lots of code scanning alerts with this duplicate and less helpful title.

Second, it's not clear what I'm supposed to do about this, other than close the issue under GitHub Security tab?

Will subsequent runs still raise this and cause the workflow to fail?

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

Official semgrep action, called through a reusable workflow as seen in the file above.

**Use case**

Avoid getting thousands of potentially unwanted alerts across my work repos the second I roll this out.

I can't introduce this to my enterprise until I can solve this issue.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1565/dollarline-has-been-added-to-the-semgrepignore-list-of-ignored-paths. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by underyx** [comment]
Seems like this is coming from this rule: https://github.com/returntocorp/semgrep-rules/blob/0fb239e7bee2f1b6f11a82a7937cbcdabfaa4d16/generic/ci/audit/changed-semgrepignore.yaml

The rule is intended to notify the security team about changes to the list of files ignored via `.semgrepignore`. I'm not fully sure why, but this is part of the `p/semgrep-misconfigurations` ruleset which you have enabled. As a workaround you can remove that ruleset — it seems to only have one other rule, anyway. I'll create an issue on the registry repo to ask why this rule is in that ruleset.

And the interpolation issue is separate, so we can leave this issue open to track that.

**Comment by underyx** [comment]
@HariSekhon the noisy rule has been removed from the `p/semgrep-misconfigurations` ruleset. Thanks for the report!

**Comment by ievans** [comment]
Seems like this issue is resolved - @HariSekhon feel free to re-open if not
