### ISSUE TITLE
Run all rules and exclude specific one

### ISSUE THREAD

**Issue by CaledoniaProject** [semgrep/semgrep#5632]
How can I run all the java rules while excluding `java.spring.security.unrestricted-request-mapping.unrestricted-request-mapping`?

I'm currently using `semgrep --config r/java` to do the job. But I'm unable to find an option to exclude certain rules, how can I do that?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1568/run-all-rules-and-exclude-specific-one. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
dupe of #2530
