### ISSUE TITLE
Java: Pattern parse error with consecutive annotations

### ISSUE THREAD

**Issue by dpnishant** [semgrep/semgrep#5646]
**Describe the bug**
The playground URL https://semgrep.dev/playground/s/dpnishant:find-endpoints-via-annotations throws `Engine(Pattern parse error)`. However if either Line `7` or Line `8` is deleted (under the `pattern` block) the rule works fine. It seems there are some issues with parsing pattern with consecutive Java annotations.

**To Reproduce**
https://semgrep.dev/playground/s/dpnishant:find-endpoints-via-annotations

**Expected behavior**
https://semgrep.dev/playground/s/dpnishant:find-endpoints-via-annotations should have executed without throwing `Engine(Pattern parse error)`.

**Screenshots**
Not available. Refer playground URL above.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Occurs on semgrep.dev as well as locally.

**Use case**
Fixing the bug would help us write rules with more patterns.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1578/java-pattern-parse-error-with-consecutive-annotations. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
I agree the error message isn't very helpful, but you can write the pattern (I think) you want this way:
```yaml
pattern: |
  @Controller
  @RequestMapping("$ENDPOINT")
  class $C { ... }
```
Does this help you?

**Comment by dpnishant** [comment]
@IagoAbal Although that works for this particular case, but that does not really meet my need, as the matched content (with the pattern (you suggested)) is much more than actually needed. Secondly & more importantly this does not work for this example: https://semgrep.dev/playground/s/dpnishant:find-endpoints-via-annotations-2. However if we keep just the Line `8` (under the `pattern` block), the pattern works as expected. So there seems to be a parsing bug that needs to be fixed.

**Comment by IagoAbal** [comment]
For sure! I didn't mean to say that this is not a bug or something to improve. I am not sure it's a bug or a feature request, but I agree that those patterns should work. But since it probably won't be fixed right away, I'm trying to provide you with alternatives. For your latest example, you could do this: https://semgrep.dev/s/JOXo

**Comment by IagoAbal** [comment]
cc @aryx

**Comment by dpnishant** [comment]
@IagoAbal Thank you so much for the workarounds. Appreciate it.
