### ISSUE TITLE
Scala for loops parse error

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#5650]
I expected that `for($EXPR2; $IDENT <- $GEN; $EXPR) {yield ... }`
Or `for(...; $IDENT <- $GEN; ...) {yield ... }`

would parse as patterns but they don't as of 0.100: https://semgrep.dev/s/NoNx

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1579/scala-for-loops-parse-error. _Note_: this link is for r2c use only and is not accessible publicly.
