### ISSUE TITLE
Taint mode does not flow taint to sinks inside for comprehension

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#5652]
**Describe the bug**
In Scala, taint mode does not flow taint to sinks inside for comprehension

**To Reproduce**
https://semgrep.dev/s/Q2vD <- expect both tests to pass

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Semgrep 0.101

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1580/taint-mode-does-not-flow-taint-to-sinks-inside-for-comprehension. _Note_: this link is for r2c use only and is not accessible publicly.
