### ISSUE TITLE
Findings list, multi-select boxes unable to be used

### ISSUE THREAD

**Issue by VanessaHenderson** [semgrep/semgrep#5672]
**Describe the bug**
In the Semgrep app, when you are on the findings list, there are the multiselect boxes that allow you to triage multiple items at once. Today, when I went to select them, it took me to a summary of the issue itself and I wasn't able to select the multi-box. You can use the top multi-box to select the whole row, but you still couldn't uncheck them individually.

**To Reproduce**
https://semgrep.dev/orgs/<ORG>/findings?tab=open&dedup=true
Try to select the mutliselect box on the left hand of the screen for a single issue

**Expected behavior**
A single issue is selected

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep.dev application

**Use case**
This bug prevents me to triaging multiple issues at a time which is just plain annoying :)
Update: This actually prevents triaging issues at all unless you are triaging the whole page as there is no triage button in the issue details page like I thought there might be

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1592/findings-list-multi-select-boxes-unable-to-be-used. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by VanessaHenderson** [comment]
Seems to be resolved now
