### ISSUE TITLE
Semgrep not showing the vulnerable code in a file upon clicking the findings in semgrep app

### ISSUE THREAD

**Issue by offsecdawn** [semgrep/semgrep#5675]
**Describe the bug**
When I click on a particular finding in semgrep app, it does not show the actual line where the issue is existing. Instead, it is showing 404 error

**To Reproduce**
1. Run the Semgrep CI using jenkins

**Expected behavior**
All findings should indicate the list of vulnerability upon being clicked on

**Screenshots**
![image](https://user-images.githubusercontent.com/51472598/177180246-bf991a67-4079-4e2a-97f6-2200b8d4f1e5.png)

**What is the priority of the bug to you?**
- [ ] P1: important to fix or quite annoying

**Environment**
Semgrep App and Semgrep CI

**Use case**
Will be able to check all the vulnerabilities clearly

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1597/semgrep-not-showing-the-vulnerable-code-in-a-file-upon-clicking-the. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by VanessaHenderson** [comment]
Its the URL that seems to be incorrect. The url wouldn't contain "monica.git" in the project name, instead it'd just be "monica"
IE the Url you have is 
https://github.com/offsecdawn/monica.git/blob/3d6852b91ad2b88ec06c4c76a4ecf281a915960d/app/Console/Commands/SetupTest.php#L128
vs the actual URL is 
https://github.com/offsecdawn/monica/blob/3d6852b91ad2b88ec06c4c76a4ecf281a915960d/app/Console/Commands/SetupTest.php#L128

It might be something with your environment variables?

**Comment by offsecdawn** [comment]
thanks for help. I changed the `repository_url` excluding the `.git` extension in jenkins pipeline configuration  and the issue is resolved successfully.
