### ISSUE TITLE
[java] Regression in name resolution

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#5690]
**Describe the bug**
https://semgrep.dev/s/A954 no longer works. @ap00rv claims that it worked with previous versions. It makes sense but I cannot easily test this since `?version=x.y.z` stopped being supported in the Playground. _TODO: Find out what was the latest version where this rule worked._

**To Reproduce**
https://semgrep.dev/s/A954

**Expected behavior**
Given `import org.slf4j.Logger` Semgrep should resolve the `Logger` type to `org.slf4j.Logger` and the rule should work.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1610/[java]-regression-in-name-resolution. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
User believes this worked in either 0.101.0 or 0.89.0.
