### ISSUE TITLE
YAML matching sometimes captures too much text

### ISSUE THREAD

**Issue by mmcqd** [semgrep/semgrep#5698]
**Describe the bug**
In this example: https://semgrep.dev/s/P3yp, The match on
```
y:
  foo: true
```
extends past `true` and includes the newline and comment following it.

**Expected behavior**
The match range should begin at `y` and end at `true`

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1612/yaml-matching-sometimes-captures-too-much-text. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by MIJOTHY** [comment]
Also running into this (P1 for me)
