### ISSUE TITLE
Docker Multi-platform Images -- linux/arm64 (and amd64)

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#5704]
**Is your feature request related to a problem? Please describe.**
Currently there is no linux/arm64 docker image for semgrep.

Currently Docker Hub only has a linux/amd64 image and PyPi has Linux and MacOS (x64 and M1).

**Describe the solution you'd like**
It would be nice to have a multi-platform docker image with a linux/arm64 in addition to linux/amd64.

This would possibly allow faster execution in docker on M1 Macs as the it will avoid emulation.

**Describe alternatives you've considered**
Install natively via PyPi, or Homebrew etc. But sometimes it is nice to use Docker.
Use different hardware.

**Use case**
Running semgrep in docker on Apple M1 and other ARM64 architectures using ARM64 natively rather than emulation of x64

**Additional context**
Related to https://github.com/returntocorp/semgrep/issues/2252

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1619/docker-multi-platofmr-images-linuxarm64-and-amd64. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by wilsonehusin** [comment]
I ran into this as well today — I've added a PR and happy to work with reviewers to get it merged in 😄

**Comment by wilsonehusin** [comment]
Next release _should_ have linux/arm64 builds (if I did everything correctly in #5736). However, I didn't realize that the current develop HEAD pushes containers through `tests.yml`, so I'm addressing that in #5747.

**Comment by ben-elttam** [comment]
Thanks for your efforts @wilsonehusin.

I see it got reverted. Maybe this bug should be reopened since #5736 got reverted by #5770.

Docker Engine cannot have multiplatform images (it can have a single image from any platfrom via qemu, but it cannot have multiple simultanously), hence why `load: true` failed.

If I understand correctly I think the solution should be like https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md.

As in:  Remove the `load: true` (default is false).

The tricky bit is the validation of the candidate image before pushing. Probably need to split that up into a matrix to load and test candidate for each platform, before pushing the validated images as a multiplatform image (e.g. with correct manifest).

**Comment by WilkenSteiner** [comment]
Hi! Is this being worked on? Or is it on hold until the dockerd/buildx feature mentioned in #5770 has been solved?

**Comment by ievans** [comment]
Re-opening (go away stale bot) and marking as priority low; @brendongo any context on status?

**Comment by tpetr** [comment]
We are now publishing multi-arch Docker images (linux/amd64 + linux/arm64) for 1.31.2 and beyond
