### ISSUE TITLE
'semgrep' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by BobbyTRU** [semgrep/semgrep#5705]
I installed semgrep with "python3 -m pip install semgrep". All looked good except for some warnings "Ignoring invalid distribution -emgrep". Trying to use the command semgrep --help yields the error "'semgrep' is not recognized as an internal or external command,
operable program or batch file." Tried uninstalling and installing it but that didn't work. Any suggestions what might be the cause of this problem and how to fix it?

Thanks in advance

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1624/semgrep-is-not-recognized-as-an-internal-or-external-command-operable. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ievans** [comment]
@BobbyTRU thanks for the bug report. What platform (operating system, version, python version) are you running on?

**Comment by brendongo** [comment]
FYI we do not support semgrep running on Windows. WSL should just work

**Comment by BobbyTRU** [comment]
Im running it on Windows 11. Version 10.0.22000 Build 22000. Python Version is 3.10.5.

**Comment by brendongo** [comment]
@BobbyTRU did you manage to get this working on WSL?
