### ISSUE TITLE
Support named capture groups in `pattern-regex` and `pattern-not-regex`

### ISSUE THREAD

**Issue by jeremyfelder** [semgrep/semgrep#5713]
**Is your feature request related to a problem? Please describe.**
When using the patterns `pattern-regex` and `pattern-not-regex`, it is not possible to use named capture groups to rename a number capture group to be referenced easily. See [this](https://semgrep.dev/s/rPre) playground as an example; I would have expected that the named group `FINAL` would be mapped to a metavariable just like the group `1` is.

**Describe the solution you'd like**
I would like to be able to reference a capture group both by its number and name if a named capture group is used, otherwise just the number.

**Describe alternatives you've considered**
I am using semgrep within a tool and am considering writing a wrapper that post scan will remap number captured groups to names.

**Use case**
In cases where multiple capture groups are used it can become messy to reference them by number instead of an informative name.

**Additional context**
I looked at previous issues that seemed to relate to this, though none of them address this issue:
- https://github.com/returntocorp/semgrep/issues/3009
- https://github.com/returntocorp/semgrep/issues/3356
- https://github.com/returntocorp/semgrep/issues/5486

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1627/support-named-capture-groups-in-pattern-regex-and-pattern-not-regex. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by d0nut-rh** [comment]
Could this be reopened?
