### ISSUE TITLE
Rust `use` declarations only include last element

### ISSUE THREAD

**Issue by chananloh** [semgrep/semgrep#5717]
**Description**
I have written a simple custom rule for Rust language. Running the custom rule in Semgrep CLI matches lines of code extraneously that does not match the expected output for the custom rule.

**To Reproduce**
python3 -m venv /path/to/venv
source /path/to/venv/bin/activate
python -m pip install semgrep
semgrep --config=prng.yml prng.rs

prng.yml:
```
rules:
- id: rand-prng
  patterns: 
    - pattern: use rand::$X;
  message:
    The product uses a Pseudo-Random Number Generator (PRNG) in a security context, but the PRNG's algorithm is not cryptographically strong. 
  languages: [rust]
  severity: ERROR
```
prng.rs:
```
use rand::FromEntropy;
use rand::prng::XorShiftRng;
use mini_redis::{client, Result};
use rand::prng::ChaChaRng;
use rand::prng::Hc128Rng;

pub async fn send(&self, message: Message) -> Result<()> {

}
```

**Expected behavior**
It is expected that custom rule id: rand-prng would not match:
```
use mini_redis::{client, Result};
```

Actual behaviour:
<img width="672" alt="Screenshot 2022-07-12 at 4 49 12 PM" src="https://user-images.githubusercontent.com/105200180/178450367-0e8bcf1b-093c-47a1-a83c-556f48098582.png">

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
 MacBook Pro, 2021, Apple M1 Max
macOS Monterey 12.4
Python 3.9.13

**Use case**
Fixing this bug enables adoption of semgrep.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1631/rules-have-generated-extraneous-findings-that-does-not-match-expected. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
Looks to me like a parsing/ast-translation bug for Rust imports.

```
use X::Y::Z;
```
currently results in
``` 
Pr([DirectiveStmt({d_attrs=[]; d=ImportFrom((), DottedName([]), ("Z", ()), None); })])
```
but should probably instead be
```
Pr([DirectiveStmt({d_attrs=[]; d=ImportFrom((), DottedName(["X", "Y"]), ("Z", ()), None); })])
```

~~Probably along the lines of https://github.com/returntocorp/semgrep/pull/5343.~~ After some inspection, seems different. Looks like we need to consume the data associated with this in 
https://github.com/returntocorp/semgrep/blob/f4b699a7d565b907f610d9a50cf1bf3ae10be286/semgrep-core/src/parsing/tree_sitter/Parse_rust_tree_sitter.ml#L2483-L2501
