### ISSUE TITLE
Fails to parse valid Python f"{var:,f}"

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#572]
**Describe the bug**
```console
$ echo 'var = 1234567; print(f"{var:,f}")' > test.py
$ python3 test.py
1,234,567.000000
$ semgrep-files/semgrep-core -dump_ast test.py
Fatal error: exception Parse_info.Parsing_error(_)
```

**Environment**
Official semgrep-v0.5.0b2-ubuntu-16.04.tgz binary.

**Comment by dlukeomalley** [comment]
Queuing this up! Should have a few bug fixes landing tomorrow. Thank you @andersk.

**Comment by brendongo** [comment]
Relevant: https://docs.python.org/3.4/library/string.html#format-string-syntax

**Comment by andersk** [comment]
Indeed, although you should look at the [current version](https://docs.python.org/3/library/string.html#format-string-syntax), which has some additions since 3.4.

**Comment by dlukeomalley** [comment]
@andersk We merged a fix which will be included with the next mainline semgrep release.

Is this issue blocking your Zulip work? If so, we can discuss cherry picking the fix to the Zulip release or migrating some of the Zulip specific features to mainline.
