### ISSUE TITLE
Package-lock.json false positives (integrity hashes)

### ISSUE THREAD

**Issue by seanmyath** [semgrep/semgrep#5728]
**Describe the bug**
`generic.secrets.security.detected-username-and-password-in-uri.detected-username-and-password-in-uri` rule is generating hundreds of findings for all repos that use npm inside the package-lock.json files. Semgrep detects integrity hashes of packages as secrets.

**To Reproduce**
Run semgrep scan npm project (and package-lock.json) file with the following rule https://semgrep.dev/r/generic.secrets.security.detected-username-and-password-in-uri.detected-username-and-password-in-uri

**Expected behavior**
This rule should not raise errors for clear sha512 hashes, especially within package-lock files.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker image using `semgrep ci`

**Use case**
Drastically less false positives, while keeping this rule enabled.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1637/package-lockjson-false-positives-integrity-hashes. _Note_: this link is for r2c use only and is not accessible publicly.
