### ISSUE TITLE
Bogus error indicated in JSX expression though rule runs just fine

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#5734]
**Describe the bug**

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/6817500/179132965-550ba331-ac9e-4b60-91e8-8e6baf45f6a8.png">

Note that in advanced mode there is no error squiggle.

**To Reproduce**
https://semgrep.dev/playground/s/msorens:tooltip-empty-string

**Expected behavior**
No error squiggle on a valid JSX expression.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1642/bogus-error-indicated-in-jsx-expression-though-rule-runs-just-fine. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
I checked the reproduction and it looks like this is no longer an issue
