### ISSUE TITLE
HTML Language Strict Processing Doesn't Allow Writing JSP etc

### ISSUE THREAD

**Issue by ben-elttam** [semgrep/semgrep#5735]
**Describe the bug**

Entering patterns that don't match valid HTML, e.g. JSP etc extensions causes a parse error.
A loose processing option that is between HTML and generic mode that would allow matching non-HTML would be nice.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

https://semgrep.dev/playground/s/ben-elttam:jsp-taint

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

Allow writing rules for JSP and similar technologies that extend HTML with templating etc.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1643/html-langauge-strict-processing-doesnt-allow-writing-jsp-etc. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ben-elttam** [comment]
Should this have a label `priority:low`?

**Comment by ben-elttam** [comment]
Is there a way to add a priority label via a bot (via a comment)?

**Comment by ben-elttam** [comment]
Priority should be low.
