### ISSUE TITLE
Broken Pattern example for Yaml

### ISSUE THREAD

**Issue by ashwinkumar01** [semgrep/semgrep#5740]
**Describe the bug**
Under Pattern example, clicking the YAML section shows malformed text
On closer inspection, it appears that most sections have some form of broken content

**To Reproduce**
- Navigate to https://semgrep.dev/docs/writing-rules/pattern-examples/
- Scroll right and click on YAML

- In the Bash section, scroll down and you can see this text:
`This example is missing, or this feature isn't supported yet for Bash in Semgrep. File an issue or make a PR for POLYGLOT/metavar_anno.bash!`

**Expected behavior**
Concrete examples and documentation for YAML

**Screenshots**
<img width="1314" alt="Screenshot 2022-07-18 at 20 16 55" src="https://user-images.githubusercontent.com/11959855/179537912-6ecd47f8-b262-413a-a727-96e5bf95b719.png">

<img width="1315" alt="Screenshot 2022-07-18 at 20 17 13" src="https://user-images.githubusercontent.com/11959855/179537978-484d0117-4258-4575-b099-de435312467e.png">

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
I want be able to see pattern example for YAML

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1647/broken-pattern-example-for-yaml. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by emjin** [comment]
We've been lax creating examples for languages that don't fit the format very well (YAML doesn't have function calls). If you're just looking for examples, would it be helpful if I shared some existing YAML rules with you?

**Comment by ashwinkumar01** [comment]
@emjin yes, for me personally that would be great. 
But the problem also exists for other languages on the page. My recommendation would be to just remove those sections until they're supported

**Comment by emjin** [comment]
You can find a bunch of YAML style lints here: https://semgrep.dev/p/semgrep-rule-lints and kubernetes security checks here: https://semgrep.dev/p/kubernetes. Hopefully these help! I'll leave this issue open for the documentation gap.

**Comment by IagoAbal** [comment]
@emjin Should we add this to Linear/Documentation?

**Comment by emjin** [comment]
Done. But also, we have a bunch of broken links it sounds like. I would like to know how much benefit these examples provide people.
