### ISSUE TITLE
Support `generic` as a destination language for extract mode

### ISSUE THREAD

**Issue by kopecs** [semgrep/semgrep#5741]
There are several use cases where no specific language we support would be the correct destination for an extract mode rule. Examples of this include:

- Django templates; extracting their DSL
- SQL embedded in lots of places (at least until we have robust SQL support)
- Inline asm

One possible issue with the current design is ensuring that relevant generic rules run on the extracted code. The differences in patterns may be sufficient for this, but we should consider if we need an alternative system to ensure your Django filter rule only matches on relevant extracted code, and not also on other configuration files, etc.. where the same text might appear.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1648/support-generic-as-a-destination-language-for-extract-mode. _Note_: this link is for r2c use only and is not accessible publicly.
