### ISSUE TITLE
Python matches on multiline strings report ending line number incorrectly

### ISSUE THREAD

**Issue by bkettle** [semgrep/semgrep#5750]
**Describe the bug**
When a match matches a python multiline string:

```python
x = """
    abc
    def
"""
```

The end line number is reported as being the same as the start line number, when in reality the start and end line numbers should be different.

**To Reproduce**
The behavior shows up here: https://semgrep.dev/playground/s/Jg2y

A simpler example can be seen by running `semgrep -e "\$X = \"\$MULTILINE\"" -l py match.py --json` on the string `x = ...` above. The match is reported as starting on line 1 and ending on line 1, but it should really end on line 4.

**Expected behavior**
Line numbers are reported correctly.

**Screenshots**
Output of above "simple example" includes:

```
"end": {
        "col": 28,
        "line": 1,
        "offset": 27
      }
...
"start": {
        "col": 1,
        "line": 1,
        "offset": 0
      }
"""
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Semgrep.dev, homebrew binary

**Use case**
More predictable behavior and easier debugging in semgrep app!

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1652/python-matches-on-multiline-strings-report-ending-line-number. _Note_: this link is for r2c use only and is not accessible publicly.
