### ISSUE TITLE
Getting error while executing njsscan

### ISSUE THREAD

**Issue by sumitsharma16** [semgrep/semgrep#5758]
**Describe the bug**
Hi

We are getting the below error. It runs for a while and after that it gives the error. Please let us know the solution or the reason.

########################### error ###############################################################

Pattern Match ██████████████████████████████████████████████████████████ 97

    Pattern Match ███████████████████████████████████████████████████████████ 98
    Pattern Match ████████████████████████████████████████████████████████████ 99
    20:48:30 - Semantic Grep 0
    Semantic Grep 1
    Semantic Grep 2
    Semantic Grep 3
    Semantic Grep 4
    Semantic Grep 5
    Semantic Grep 6
    Semantic Grep 7
    Semantic Grep 8
    Semantic Grep 9
    Semantic Grep 10
    Semantic Grep 11
    Semantic Grep 12
    Exception in thread Thread-1:
    20:48:30 Traceback (most recent call last):
    20:48:30 File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    20:48:30 self.run()
    20:48:30 File "/usr/lib64/python3.7/threading.py", line 870, in run
    20:48:30 self._target(*self._args, **self._kwargs)
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
    20:48:30 ret[0] = function(*args, **kwargs)
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
    20:48:30 **kwargs,
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
    20:48:30 deep,
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
    20:48:30 target_manager, filtered_rules, dump_command_for_core, deep
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
    20:48:30 rules, target_manager, dump_command_for_core, deep
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
    20:48:30 returncode = runner.execute()
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
    20:48:30 rc = asyncio.run(self._stream_subprocess())
    20:48:30 File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    20:48:30 return loop.run_until_complete(main)
    20:48:30 File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    20:48:30 return future.result()
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
    20:48:30 preexec_fn=setrlimits_preexec_fn,
    20:48:30 File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    20:48:30 stderr=stderr, **kwds)
    20:48:30 File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    20:48:30 bufsize, **kwargs)
    20:48:30 File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    20:48:30 self._child_watcher_callback, transp)
    20:48:30 File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
    20:48:30 "Cannot add child handler, "
    20:48:30 RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
    20:48:30
    20:48:30 - Semantic Grep 13
    20:48:30 Traceback (most recent call last):
    20:48:30 File "/usr/local/bin/njsscan", line 8, in
    20:48:30 sys.exit(main())
    20:48:30 File "/usr/local/lib/python3.7/site-packages/njsscan/main.py", line 76, in main
    20:48:30 args.config,
    20:48:30 File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 44, in scan
    20:48:30 result = scanner.scan()
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
    20:48:30 self.options).scan(valid_paths)
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
    20:48:30 self.format_output(sgrep_out)
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
    20:48:30 self.findings['errors'] = results['errors']
    20:48:30 TypeError: 'NoneType' object is not subscriptable
    20:48:30 Future exception was never retrieved
    20:48:30 future:
    20:48:30 Traceback (most recent call last):
    20:48:30 File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    20:48:30 self.run()
    20:48:30 File "/usr/lib64/python3.7/threading.py", line 870, in run
    20:48:30 self._target(*self._args, **self._kwargs)
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
    20:48:30 ret[0] = function(*args, **kwargs)
    20:48:30 File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
    20:48:30 **kwargs,
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
    20:48:30 deep,
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
    20:48:30 target_manager, filtered_rules, dump_command_for_core, deep
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
    20:48:30 rules, target_manager, dump_command_for_core, deep
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
    20:48:30 returncode = runner.execute()
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
    20:48:30 rc = asyncio.run(self._stream_subprocess())
    20:48:30 File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    20:48:30 return loop.run_until_complete(main)
    20:48:30 File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    20:48:30 return future.result()
    20:48:30 File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
    20:48:30 preexec_fn=setrlimits_preexec_fn,
    20:48:30 File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    20:48:30 stderr=stderr, **kwds)
    20:48:30 File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    20:48:30 bufsize, **kwargs)
    20:48:30 File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    20:48:30 self._child_watcher_callback, transp)
    20:48:30 File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
    20:48:30 "Cannot add child handler, "
    20:48:30 RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
    20:48:30
    20:48:30 During handling of the above exception, another exception occurred:
    20:48:30
    20:48:30 Traceback (most recent call last):
    20:48:30 File "/usr/lib64/python3.7/asyncio/base_subprocess.py", line 171, in _connect_pipes
    20:48:30 proc.stdout)
    20:48:30 File "/usr/lib64/python3.7/asyncio/base_events.py", line 1452, in connect_read_pipe
    20:48:30 await waiter
    20:48:30 concurrent.futures._base.CancelledError
    20:48:30 + true

NJSSCAN VERSION : njsscan: v0.3.2 | Ajin Abraham | opensecurity.in

Issue raised on njsscan
https://github.com/ajinabraham/njsscan/issues/95

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1655/getting-error-while-executing-njsscan. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by sumitsharma16** [comment]
Hi 
Any update ?

**Comment by toastyghost** [comment]
+1 please respond, we depend on njsscan for security checks prior to product releases

**Comment by brendongo** [comment]
Looks like there was a problem running threads with asyncio. Similar issue without fix: https://github.com/KimiNewt/pyshark/issues/353

Not entirely sure what is happening since it looks like you are running python 3.7. Is this running in an environment that would be hard for multithreading?

**Comment by toastyghost** [comment]
Not OP but same issue on i5 MacBook Pro and had been working fine on biweekly scans for like a year prior to this

**Comment by IagoAbal** [comment]
Are we able to reproduce this with Semgrep alone without calling it via nodejsscan? That could be useful info to have.

**Comment by IagoAbal** [comment]
OK looking at @brendongo's comment I guess this requires nodejsscan calling Semgrep. @sumitsharma16 @toastyghost did this happen after upgrading nodejsscan, Semgrep, Python... something?

**Comment by dlukeomalley** [comment]
CC @ajinabraham who maintains nodejsscan.

**Comment by ajinabraham** [comment]
This started to occur for some users after we updated [njsscan](https://github.com/ajinabraham/libsast/pull/20/files) to use semgrep 0.104
https://github.com/ajinabraham/njsscan/issues/95

**Comment by brendongo** [comment]
@toastyghost @sumitsharma16 are you able to provide reproduction of the issue? Trying out on a few repos we are unable to get this error.

**Comment by spmishra121** [comment]
I ran the semgrep and got below error...

semgrep --config=auto .
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

Auto config uses Semgrep rules to scan your codebase and the Semgrep Registry to generate recommended rules based on
your languages and frameworks.
Fetching rules from https://semgrep.dev/registry ...
Failed to download config from https://semgrep.dev/c/auto: semgrep error: Invalid rule schema
  --> https://semgrep.dev/...:325
325 |   - patterns:
326 |     - pattern-either:
327 |       - pattern-inside: '$JWT = require("jsonwebtoken")
328 |
329 |           ...
330 |
331 |           '
332 |       - pattern-inside: 'import $JWT from "jsonwebtoken"
333 |
334 |           ...
335 |
336 |           '
337 |       - pattern-inside: 'import * as $JWT from "jsonwebtoken"
338 |
339 |           ...
340 |
341 |           '
342 |       - pattern-inside: 'import {...,$JWT,...} from "jsonwebtoken"
343 |
344 |           ...
345 |
346 |           '
347 |     - pattern-either:
348 |       - pattern-inside: '$JWT.sign($DATA,$VALUE,...);
349 |
350 |           '
351 |       - pattern-inside: '$JWT.verify($DATA,$VALUE,...);
352 |
353 |           '
354 |     - focus-metavariable: $VALUE
355 | - id: trailofbits.go.missing-unlock-before-return.missing-unlock-before-return

Additional properties are not allowed ('focus-metavariable' was unexpected)

invalid configuration file found (1 configs were invalid)

**Comment by brendongo** [comment]
@spmishra121 this looks like a different error. You seem to be running a stale version of semgrep. If you upgrade to latest and run again it should work

**Comment by brendongo** [comment]
@sumitsharma16 @toastyghost @ajinabraham closing this as unable to reproduce. Feel free to reopen an issue with a reproduction if this is still happening

**Comment by spmishra121** [comment]
Hi @brendongo , I analysed few things as per required by you and @ajinabraham , Please find the details...
Please find the version of njsscan...

**Python Version: 3.7.10**


**[root@ip-10-25-48-63 workspace]# njsscan --version

**njsscan: v0.3.3 | Ajin Abraham | opensecurity.in**
[root@ip-10-25-48-63 workspace]#**

Result of njsscan
[root@ip-10-25-48-63 workspace]# njsscan .

Pattern Match ████████████████████████████████████████████████████████████ 134
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
ret[0] = function(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
**kwargs,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
deep,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
target_manager, filtered_rules, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
rules, target_manager, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
returncode = runner.execute()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
rc = asyncio.run(self._stream_subprocess())
File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
preexec_fn=setrlimits_preexec_fn,
File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
stderr=stderr, **kwds)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
bufsize, **kwargs)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
self._child_watcher_callback, transp)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
"Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

Semantic Grep 19
Traceback (most recent call last):
File "/usr/local/bin/njsscan", line 8, in
sys.exit(main())
File "/usr/local/lib/python3.7/site-packages/njsscan/main.py", line 76, in main
args.config,
File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 44, in scan
result = scanner.scan()
File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
self.options).scan(valid_paths)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
self.format_output(sgrep_out)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
Future exception was never retrieved
future:
Traceback (most recent call last):
File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
self.run()
File "/usr/lib64/python3.7/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
ret[0] = function(*args, **kwargs)
File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
**kwargs,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
deep,
File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
target_manager, filtered_rules, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
rules, target_manager, dump_command_for_core, deep
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
returncode = runner.execute()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
rc = asyncio.run(self._stream_subprocess())
File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
return loop.run_until_complete(main)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
return future.result()
File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
preexec_fn=setrlimits_preexec_fn,
File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
stderr=stderr, **kwds)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
bufsize, **kwargs)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
self._child_watcher_callback, transp)
File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
"Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib64/python3.7/asyncio/base_subprocess.py", line 171, in _connect_pipes
proc.stdout)
File "/usr/lib64/python3.7/asyncio/base_events.py", line 1452, in connect_read_pipe
await waiter
concurrent.futures._base.CancelledError

**Semgrep Version:
Installing collected packages: semgrep
Attempting uninstall: semgrep
Found existing installation: semgrep 0.104.0
Uninstalling semgrep-0.104.0:
Successfully uninstalled semgrep-0.104.0
ERROR: libsast 1.5.2 requires semgrep==0.104.0, but you'll have semgrep 0.110.0 which is incompatible.
Successfully installed semgrep-0.110.0**
[root@ip-10-25-48-63 workspace]#

Semgrep Result

[root@ip-10-25-48-63 workspace]# semgrep --config=auto .
Fetching rules from https://semgrep.dev/registry.

Scanning across multiple languages:
| 55 rules × 330 files
ts | 196 rules × 132 files
json | 4 rules × 10 files
js | 185 rules × 4 files
bash | 5 rules × 3 files
dockerfile | 5 rules × 2 files

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|481/481 tasks

Findings:

seeder-scripts/default-collection-views/default-collection-views-seeder-scripts/Dockerfile
dockerfile.security.missing-user.missing-user
By not specifying a USER, a program in the container may run as 'root'. This is a security
hazard. If an attacker can control a process running as root, they may have control over the
container. Ensure that the last USER in a Dockerfile is a USER other than 'root'.
Details: https://sg.run/Gbvn

     18┆ CMD ["node", "default-collection-views-seeder.js"]
src/common/handlers/dlss/dlss.service.ts
javascript.express.security.audit.xss.direct-response-write.direct-response-write
Detected directly writing to a Response object from user-defined input. This bypasses any
HTML escaping and may expose your application to a Cross-Site-scripting (XSS) vulnerability.
Instead, use 'resp.render()' to render safely escaped HTML.
Details: https://sg.run/vzGl

    139┆ return res.status(200).send(result);
      ⋮┆----------------------------------------
    335┆ return res.status(200).send(result);
Some files were skipped or only partially analyzed.
Scan skipped: 14 files larger than 1.0 MB, 40428 files matching .semgrepignore patterns
For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1197 rules on 165 files: 3 findings.
[root@ip-10-25-48-63 workspace]#
