### ISSUE TITLE
Add support for Julia language

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#5760]
See https://r2c-community.slack.com/archives/C01LNF69F9B/p1656433053812029 for context

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1657/add-support-for-julia-language. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
Closing this as it's now available in semgrep.
