### ISSUE TITLE
Bug in go r2c.go.deadcode.useless-ifelse matching

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#577]
// Edit (@dlukeomalley): https://semgrep.live/pKxk

**Describe the bug**

running

```
- id: r2c.go.deadcode.useless-ifelse.useless-if-body
  patterns:
  - pattern: |-
      if ($X) {
          $S
      } else {
          $S
      }
  message: useless if statment; both blocks have the same body
  languages: [go]
  severity: WARNING
```

Over https://github.com/palantir/bulldozer specifically

https://github.com/palantir/bulldozer/blob/7d497e18beaee065a6ca90716902126b52cfd2c0/vendor/gopkg.in/yaml.v2/readerc.go#L45 flags

but the bodies are clearly different

```
if avail >= 2 && buf[pos] == bom_UTF16LE[0] && buf[pos+1] == bom_UTF16LE[1] {
		parser.encoding = yaml_UTF16LE_ENCODING
		parser.raw_buffer_pos += 2
		parser.offset += 2
	} else if avail >= 2 && buf[pos] == bom_UTF16BE[0] && buf[pos+1] == bom_UTF16BE[1] {
		parser.encoding = yaml_UTF16BE_ENCODING
		parser.raw_buffer_pos += 2
		parser.offset += 2
	} else if avail >= 3 && buf[pos] == bom_UTF8[0] && buf[pos+1] == bom_UTF8[1] && buf[pos+2] == bom_UTF8[2] {
		parser.encoding = yaml_UTF8_ENCODING
		parser.raw_buffer_pos += 3
		parser.offset += 3
	} else {
		parser.encoding = yaml_UTF8_ENCODING
	}
	return true
```

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://sgrep.live:
https://semgrep.live/scan/8305eb80-6868-4892-8415-3ed024e96d6d?ruleIds=r2c.go.deadcode.useless-ifelse.useless-if-body

**Expected behavior**
These are not the same body

**Screenshots**

**Environment**
If not using sgrep.live: are you running off docker, an official binary, a local build?

**Comment by ievans** [comment]
It looks like as of 0.9.0, the original report is fixed, but now we don't flag when the bodies are actually equivalent: https://semgrep.live/zdkk

**Comment by ievans** [comment]
Duplicated in https://github.com/returntocorp/semgrep/issues/1292, closing this
