### ISSUE TITLE
Pattern is not of type 'array'

### ISSUE THREAD

**Issue by prathya95** [semgrep/semgrep#5786]
I am trying to write the following rule:
`patterns: | #CWE-285

      - pattern: |
        ...

        $THIS = $LOC.objects.filter(...)[$NUM]

        if $THIS:

          $X = $Y.objects.filter(...).order_by(...)

        ...`

For the following code:
`...
try:

      thislocation = Location.objects.filter(service_account = request.user)[0]

        if thislocation:

          visits = Visit.objects.filter(location = thislocation).order_by('-arrival')

...`

But I am getting the following error message, that the above semgrep rule is not of type 'array'. Any idea how to go about this?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1665/pattern-is-not-of-type-array. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ievans** [comment]
@prathya95 would you mind sharing a link from https://semgrep.live as a reproduction?

**Comment by kopecs** [comment]
Closing for now. If you're able to share some more details so we can reproduce this, feel free to open a new issue!
