### ISSUE TITLE
[Go] Generic types from other packages break parsing

### ISSUE THREAD

**Issue by hakosh** [semgrep/semgrep#5799]
**Describe the bug**
When a generic type is imported from another package, semgrep cannot parse the code; meanwhile, go can compile it.

**To Reproduce**

list/list.go
```go
package list

type List[T any] struct {
	Items []T
}

```

main.go
```go
package main

import (
	"project/list"
)

func main() {
	var myList list.List[int]
}
```

Run `semgrep --lang=golang --config=auto --verbose .`
```
[WARN] Syntax error at line main.go:8:
 `list.List` was unexpected
```

**Expected behavior**
semgrep should be able to parse the code above.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
This bug blocks us from modernizing our code with generics.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1668/[go]-generic-types-from-other-packages-break-parsing. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by tdinucci** [comment]
Hello, can you please give an update on the progress of this issue?

**Comment by niamster** [comment]
Hi,
Are there any plans fixing this?
Golang generics become more and more widespread and unfortunately more source code is affected by this issue.
Thanks!

**Comment by aryx** [comment]
Should be part of the next release (0.119)
