### ISSUE TITLE
Regex with negative lookahead and backreferences failing to match correctly

### ISSUE THREAD

**Issue by msorens** [semgrep/semgrep#5800]
**Describe the bug**
Your docs claim PCRE support but I fear not. Either negative lookahead or backreferences (or both) are not working as expected, so the regex is picking up more than it should.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/6817500/180670994-8aa66374-44a9-4ae3-9921-fd54f9f3a4c3.png">

**To Reproduce**
https://semgrep.dev/playground/s/msorens:use-state-inconsistent-naming

**Expected behavior**
All tests shown should pass.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1669/regex-with-negative-lookahead-and-backreferences-failing-to-match. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
The issue here is case-sensitivity: `foo` doesn't match `Foo` in `setFoo`. Placing the backreference `\1` within case-insensitive markup does the job:
```
(?i:\1)
```
The updated rule is https://semgrep.dev/s/returntocorp:use-state-inconsistent-naming-copy
