### ISSUE TITLE
Fatal Error Parsing Javascript Rest Parameter in ForEach

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#581]
Fail to parse object with spread operator when inside a foreach anonymous function definiton:

```
foo.forEach(({ id, ...bar }) => {

});
```

https://semgrep.live/AWg

Real life example https://github.com/apache/incubator-superset/blob/29dd9894838fccb014d870b07cf0a14e0919dd13/superset-frontend/src/dashboard/util/logging/getLoadStatsPerTopLevelComponent.js#L28

**Comment by DrewDennison** [comment]
@aryx good first issue? I assume related to #580 ?

**Comment by aryx** [comment]
Same, I don't think it's a parsing issue, it's a "compiling" issue, that is the way we transform certain pattern-match into something simpler.

**Comment by brendongo** [comment]
Also causing semgrep to fail to parse https://github.com/bkimminich/juice-shop https://github.com/bkimminich/juice-shop/blob/master/data/datacreator.js#L298

**Comment by nbrahms** [comment]
This'll do it:

```
_build/default/bin/Main.exe -dump_ast ../pfff/tests/js/parsing/spread_params.js
Fatal error: exception Ast_js_build.TodoConstruct("ParamPattern:TODO: PatObj pattern not handled", _)
```
