### ISSUE TITLE
Method chaining pattern not supported in Kotlin

### ISSUE THREAD

**Issue by lbbooleans** [semgrep/semgrep#5819]
**Describe the bug**
It seems that method chaining using the `object. ... .method()` syntax is not currently supported for Kotlin.

**To Reproduce**
I wrote the following semgrep rule:

```
- id: spring-frameoptions-disabled
  patterns:
  - pattern: |
      override fun configure($HTTP: HttpSecurity) {
        ...
        $HTTP. ... .frameOptions().disable()
        ...
      }
  message: X-Frame-Options header is disabled in Spring Security
  languages: [kotlin]
  severity: ERROR
```
which I used to match the following Kotlin code:
```
@EnableWebSecurity
@Configuration
class WebSecurityConfig : WebSecurityConfigurerAdapter() {

    override fun configure(http: HttpSecurity) {
        http.headers().xssProtection().disable()
            .and()
            .headers().frameOptions().disable()
    }
}
```

When running the rule with the semgrep CLI, I got the following response:

```
Scanning 1 file.
[ERROR] Pattern parse error in rule spring-frameoptions-disabled:
 Invalid pattern for Kotlin:
--- pattern ---
override fun configure($HTTP: HttpSecurity) {
  ...
  $HTTP. ... .frameOptions().disable()
  ...
}

--- end pattern ---
Pattern error: (Failure "no pattern found")
```

**Expected behavior**
I would expect the rule to validate and find a positive in the supplied Kotlin code.

**Screenshots**
None

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
```
$ semgrep --version
0.106.0
```

**Use case**
Write rules that detect chained methods like I do for Java.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1682/method-chaining-pattern-not-supported-in-kotlin. _Note_: this link is for r2c use only and is not accessible publicly.
