### ISSUE TITLE
FatalError in parsing javascript every

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#582]
Failing to parse https://github.com/apache/incubator-superset/blob/29dd9894838fccb014d870b07cf0a14e0919dd13/superset-frontend/src/dashboard/util/getFilterScopeFromNodesTree.js#L36 correctly.

Managed to get a minimal example of failing to parse here: 
```
Object.entries(tabScopes).every(([key, { scope }]) => scope))
```
https://semgrep.live/Dq2 

but I am not familiar enough with this syntax to know what is wrong in particular.

**Comment by aryx** [comment]
There are different places in the code that can leader to a parsing error.
The lexer in pfff/lang_js/parsing/lexer_js.mll, parser in .../parsing/parser_js.mly, in the conversion from the JS CST to JS AST in .../analyze/ast_js_build.ml, and in the JS AST to AST generic conversion in .../analyze/js_to_generic.ml.
First thing is to identify where the error is. I usually do ~/pfff/pfff -dump_js /path/to/js to see if it's a basic parsing issue, then -dump_ast_js to see if it's the CST -> AST issue, and finally -dump_ast to see if it's the AST -> AST generic issue. (You can also use the ocaml backtrace to directly see which one it is).

**Comment by aryx** [comment]
In this case I suspect it's because it's a complex "pattern" mising an array and record nested pattern, and the translation from the JS CST to JS AST is incomplete.

**Comment by DrewDennison** [comment]
good first issue?

**Comment by aryx** [comment]
Not trivial, can involve the parser, the CST, the AST, and the AST gen and translations between all those steps.

**Comment by nbrahms** [comment]
This appears to be a duplicate of #581

**Comment by nbrahms** [comment]
Not a duplicate of #581 (which involved missing code to handle rest parameters in object destructuring); instead this relates to missing code in `pfff/lang_js/analyze/transpile_js.ml` to handle nested parameters in destructuring expressions.
