### ISSUE TITLE
Semgrep does not properly handle metavariables in Python decorators

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#5837]
**Describe the bug**
Semgrep does not appear to handle metavariables in Python decorators correctly.  I would expect to be able to capture e.g. a Flask route as such:

```
$F = flask.Flask(...)
```
then use the metavariable to ensure that I am in fact matching a Flask route later on:
```
@$F.route(...)
def $FN(...):
  ...
```
**To Reproduce**
https://semgrep.dev/s/9pJz

**Expected behavior**
Functions or classes captured in a metavariable should match in decorator instances

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Security Research rule-writing

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1700/semgrep-does-not-properly-handle-metavariables-in-python-decorators. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
I also think it _should_ work 🤔

But in the meantime it works with `metavariable-comparison`: https://semgrep.dev/s/E47L

**Comment by kurt-r2c** [comment]
the fact that this needs an explicit string cast is....annoying - can we add this to docs?

**Comment by brandonspark** [comment]
Closed by #5858
