### ISSUE TITLE
Deep matching for nested objects (javascript)

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#584]
**Is your feature request related to a problem? Please describe.**
If I want to find all usages of certain expression (e.g. function call) I should look inside objects as situation like this is quite common:
```javascript
var foo = require('foobar')

var x = {
   one: {
      two: {
         three: foo()
      }
   }
}
```
or sometimes I want to find some values inside objects (e.g. secrets) but I do not care how deeply they are nested:

```javascript
var x = {
   smth: {
     user: {
         password: 'secret-password'
     }
   }
}
```

so I would like to have opportunity to find  expression in sub-properties without specifing object structure or depth

**Describe the solution you'd like**
I do not have a strict point here, maybe smth like deep matching syntax would be possible

```
var $FOO = require('foobar');
...
var x = {<... {smth: $FOO()} ...>};
```

in order to catch both:

```javascript
var foo = require('foobar')

var x = {
   smth: foo()
}
```

```javascript
var foo = require('foobar')

var x = {
   one: {
      two: {
         smth: foo()
      }
   }
}
```

**Comment by nbrahms** [comment]
@aryx Naïvely I'd think deep-expression matching should work for this already. Isn't `{ a: 1}` an expression?

**Comment by aryx** [comment]
Yes it is, but I think the problem is that { <... ...> } does not parse because <... ...> is an expression
but insude { } the parser expects a list of fields (not an expression).

**Comment by nbrahms** [comment]
So presumably both
```javascript
{ $FOO: <... { smth: $BAR } ...> }
```
and
```javascript
<... { smth: $BAR } ...>
```
would work?

@inkz does this unblock you?

**Comment by aryx** [comment]
It does not, but it should yes.

**Comment by aryx** [comment]
Here is a test that should work but does not:
https://semgrep.dev/s/D8XY/

**Comment by inkz** [comment]
:wave:

**Comment by aryx** [comment]
@daghan just wanted that this week

**Comment by aryx** [comment]
👋

**Comment by inkz** [comment]
:wave:

**Comment by inkz** [comment]
:wave:

**Comment by 0xn3va** [comment]
@inkz, you should try the following one:

```yaml
- pattern-inside: |
    { ... }
- pattern: |
    smth: $FOO()
```

Check https://semgrep.dev/s/6bE6

**Comment by inkz** [comment]
@0xn3va genius! thanks :pray:

**Comment by inkz** [comment]
Also, since this is merged https://github.com/returntocorp/semgrep/pull/4796 now, I think it is safe to close the issue.
