### ISSUE TITLE
Users expect that we will propagate constants through function calls

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#5851]
**Describe the bug**

Pattern: `func("...")`

Target:
```python
func("HI")
func("HI".read())

def dosomething(param):
    func(param)

dosomething("HI")
```

Users expect that `dosomething("HI")` should match as well as `func("HI")`, because `dosomething` calls `func`.

**To Reproduce**
https://semgrep.dev/playground/s/enelli:confusion3

**Expected behavior**

This isn't a bug according to our current expectations set for constant propagation. Our design expects that a user should use taint. However, I'm filing this issue to represent a common confusion. We should either support this (we could translate constant propagation rules written like this into the equivalent taint rule) or detect this rule-pattern and instruct users to use taint.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
What will fixing this bug enable for you?

Help first time users

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1720/users-expect-that-we-will-propagate-constants-through-function-calls. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
My gut feeling is that many of the rules that rely on const-prop should instead rely on taint. Although even with taint, this example is inter-procedural.

**Comment by emjin** [comment]
> Although even with taint, this example is inter-procedural.

That's true. I filed it on semgrep because we have a bit of that interprocedurality for taint (though I think not for this example). Clearly users like using constant-prop more than taint, so I think we should direct them towards taint or change the semantics of constant prop to work the way they expect.

**Comment by IagoAbal** [comment]
But this would also be inter-procedural const-prop. I am not sure what should we do here, apart from maybe making it more clear in the docs that Semgrep is intra-procedural and point to DeepSemgrep for inter-procedural needs.

It may not be a matter of preference, but Semgrep's default mode is `search` and for historical reasons I presume that most docs, tutorials, etc lean heavily towards using `search` mode even for things for which taint works much better. Because taint rules are even typically much simpler than their search counterparts.

**Comment by IagoAbal** [comment]
I'm not even sure whether inter-procedural const-prop should match `func(param)` with `func("...")`, what if there are calls to `doSomething()` with non-constant arguments? Const-prop is a _must_-analysis.

**Comment by IagoAbal** [comment]
Sorry, it was `dosomething("HI")` that was supposed to match. 🤔 In this case, it could be? Although that sounds more like symbolic propagation? But what if `dosomething()` does something more than just calling `func` ?

**Comment by IagoAbal** [comment]
Playground permalink (just in case): https://semgrep.dev/s/x5rl

Closing because this looks like a request for inter-procedural symbolic propagation. Maybe it's something to move to DeepSemgrep?
