### ISSUE TITLE
Metavariable-pattern requires metavariable to be in every pattern

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#5853]
It is confusing to users that `metavariable-pattern` requires the metavariable to be present in every branch of a pattern-either (among other things). This isn't helped by the fact that our error message is pretty bad. We've added a metacheck, but most people don't run the metachecker. We should make it easier for users to discover why `metavariable-pattern` isn't working and how to fix it.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1722/metavariable-pattern-requires-metavariable-to-be-in-every-pattern. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
This is not specific of `metavariable-pattern`, but `metavariable-pattern` may be the only `metavariable-xyz` operator that warns you when it encounters that the metavariable is not bound in some cases.

My opinion has always been that the metachecker should be made fast (I remember some of the metachecking rules were kinda slow but maybe that changed) and run by default.

Although I think a rule debugger would be useful too.

And what error message is pretty bad?

**Comment by emjin** [comment]
I agree, metachecker by default is probably the best solution. There are some problems with the check it does right now still, because it only guesses what is a valid metavariable, and because some transformations are performed on the formula which the metachecker doesn't know about. We would need to fix that.

Apparently the error message you get when you're trying to use a metavariable that isn't in every branch of a pattern-either is not very helpful.

**Comment by IagoAbal** [comment]
I guess it is this one:
```ocaml
      error env
        (Common.spf
           "metavariable-pattern failed because %s is not in scope, please \
            check your rule"
           mvar);
```
We could rephrase this, I guess not everybody may realize why a metavariable may not be "in scope", or maybe not even everybody knows what that means? The problem is also that at this point we can only hypothesize, it could be that the metavariable is mistyped, or that not all "branches" leading to `metavariable-pattern` bind it, or even that the metavariable is bound by a `pattern-not`. So, many possibilities, and we would need to explain them all (but we can do that of course).

**Comment by emjin** [comment]
I think adding the concrete hypotheses would be helpful, especially if we give examples of what to look for in their code. Even though the text of the "-11/-9" error is not strictly correct (it's not always an OOM), it was helpful to put that guess.
