### ISSUE TITLE
Ocaml error on matched Java annotation

### ISSUE THREAD

**Issue by lbbooleans** [semgrep/semgrep#5860]
**Describe the bug**
Starting from semgrep version 0.107.0, we get an Ocaml error when a specific piece of code is being matched by a specific rule:

```
$ semgrep --config="r/java.spring.security.injection.tainted-file-path.tainted-file-path" .
Fetching rules from https://semgrep.dev/registry.
Scanning 1 file.
[ERROR] Fatal error at line :1:
 (Invalid_argument "output_value: abstract value (Custom)")
====[ BEGIN error trace ]====
(Invalid_argument "output_value: abstract value (Custom)")
Raised by primitive operation at Parmap.marshal in file "src/parmap.ml", line 146, characters 10-48
Called from Parmap.spawn_many.loop in file "src/parmap.ml", line 168, characters 8-23
Called from Parmap.run_many in file "src/parmap.ml" (inlined), line 190, characters 16-45
Called from Parmap.simplemapper in file "src/parmap.ml", line 208, characters 2-678
Called from Run_semgrep.semgrep_with_rules in file "src/runner/Run_semgrep.ml", line 596, characters 4-1023
Called from Run_semgrep.semgrep_with_raw_results_and_exn_handler in file "src/runner/Run_semgrep.ml", line 667, characters 21-58
=====[ END error trace ]=====
```

When we look at the rule implementation of `r/java.spring.security.injection.tainted-file-path.tainted-file-path`, we see this semgrep pattern which appears to cause the problem (we found out by following the process of elimination):

```
- pattern-inside: "$METHODNAME(..., @$REQ $TYPE $SOURCE,...) {\n  ...\n}\n"
```

We've tried to isolate the problem by adjusting the rule gradually, and it turned out that when we remove `@$REQ`, the problem disappears. The problem only occurs when the rule actually matches the code (also see "To reproduce"). When no actual positive is found, everything works fine.

**To Reproduce**
- install semgrep CLI version `0.107.0` (the problem does _not_ occur in 0.106.0, did not check versions prior to that)
- create a file Foo.java with the following content:
```
public class Foo {
    public void bar(@RequestParam String path) {
        File f = new File(path);
    }
}
```
- run the rule r/java.spring.security.injection.tainted-file-path.tainted-file-path on this code:
```
semgrep --config="r/java.spring.security.injection.tainted-file-path.tainted-file-path" .
```

**Expected behavior**
No error should occur, and a true positive should be returned.

**Screenshots**
n/a

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Reproduced on OS X CLI (using both Homebrew and pip versions of semgrep)

**Use case**
True positives in scenarios where Java annotations are used will be found, and less errors. :)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1724/ocaml-error-on-matched-java-annotation. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Thanks for reporting @lbbooleans and for providing that test case. I was already investigating this issue but your test case helped me a lot. We are releasing a quick-fix with 0.108.0 already today.

**Comment by lbbooleans** [comment]
That's great news, thanks for the heads up!

**Comment by adamboros** [comment]
I'm closing this as there was a fix merged.
