### ISSUE TITLE
json token not match

### ISSUE THREAD

**Issue by zhengow** [semgrep/semgrep#5873]
**Describe the bug**
![Kapture 2022-08-03 at 16 09 29](https://user-images.githubusercontent.com/38389586/182557865-34b6fb01-fbac-456f-8659-1ae4adb0e30b.gif)

```
id: untitled_rule
message: Semgrep found a match
languages: [json]
severity: WARNING
pattern: bob
```

```
{
    "bob": 123,
    "alice": "sad",
    "test": {
        "bob": 123
    }
}
```
**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1730/json-token-not-match. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
@zhengow thanks for reporting but please next time include a link to the Playground rather than a screenshot, ~that way we don't spend time copying your rule and example code by hand~. Sorry, you did include all the text in the comment, my bad! Still sharing a Playground link is probably better.

**Comment by IagoAbal** [comment]
Have you tried this https://semgrep.dev/s/9p2r ?

**Comment by zhengow** [comment]
> @zhengow thanks for reporting but please next time include a link to the Playground rather than a screenshot, ~that way we don't spend time copying your rule and example code by hand~. Sorry, you did include all the text in the comment, my bad! Still sharing a Playground link is probably better.

Got it, I don't know that playground can save the code:)

**Comment by zhengow** [comment]
> Have you tried this https://semgrep.dev/s/9p2r ?

That works. But why can't this 👀 
https://semgrep.dev/s/RlEe
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/38389586/182748568-f8d6ae64-f0b2-4240-9660-7c13e2c7243a.png">

**Comment by IagoAbal** [comment]
Because in YAML
```yaml
- pattern: "bob"
```
means the pattern is `bob` (YAML kind of removes the quotes `"` from `"bob"`), the identifier `bob`, which doesn't exist in your target file.

Whereas
```yaml
- pattern: |
    "bob"
```
means the pattern is `"bob"` (exactly as you wrote it), that is a string literal, which is what you really want.

Feel free to ask for further clarification either here or in our Community Slack, but for now I'm closing this issue since it seems that it's just a YAML-related misunderstanding.

**Comment by IagoAbal** [comment]
See https://semgrep.dev/s/vL4b (note that the Playground even removes the `"` because they are not needed...) vs https://semgrep.dev/s/ZBEo.

**Comment by zhengow** [comment]
Okay, nice answer
