### ISSUE TITLE
Inconsistent Playground Behavior

### ISSUE THREAD

**Issue by nicktimko** [semgrep/semgrep#5879]
**Describe the bug**
Inconsistent and confusing behavior of the playground. See GIF below for details. The first run I ever did in it gave me the really confusing "look at these blank lines!" result.

**To Reproduce**
1. Go to https://semgrep.dev
2. Click "Playground"
3. Click "Run". It sometimes flags blank lines for some reason? I don't understand.

**Expected behavior**
Consistent behavior

**Screenshots**
![inconsistent](https://user-images.githubusercontent.com/5297556/182870505-6b90da3b-7eeb-4e55-ad7f-28e609316da7.gif)

**What is the priority of the bug to you?**
- P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Playground that's not confusing and can help learn how to use it

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1736/inconsistent-playground-behavior. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by annikalee** [comment]
I'm going to close this issue since I am unable to reproduce it. Please reopen if you still are having issues!
