### ISSUE TITLE
Python `match` statement not supported

### ISSUE THREAD

**Issue by rouge8** [semgrep/semgrep#5885]
**Describe the bug**
Python's `match` statement is not supported and causes semgrep to completely fail to parse the file.

**To Reproduce**
https://semgrep.dev/s/oLz9

**Expected behavior**
I expect the file to parse without errors.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Fixing this will let us adopt Semgrep for linters. We use `match` heavily in our code and Semgrep failing silently on those files is a dealbreaker.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1739/python-match-statement-not-supported. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by rouge8** [comment]
It looks like this could be solved by updating https://github.com/returntocorp/semgrep-python to the latest [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python)

**Comment by Sjord** [comment]
I think Python is parsed [using pfff, not tree-sitter](https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/src/parsing/Parse_target.ml#L304-L314).

**Comment by brandonspark** [comment]
Fixed in #5949
