### ISSUE TITLE
pip install semgrep

### ISSUE THREAD

**Issue by teslimp34** [semgrep/semgrep#5888]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1742/pip-install-semgrep. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spencerdrak** [comment]
@teslimp34 looks like you're missing some required info here, we're going to close. feel free to re-open with more info.
