### ISSUE TITLE
semgrep/README.md: Broken "Contributing" link

### ISSUE THREAD

**Issue by smcpeak** [semgrep/semgrep#5890]
The README.md file, which is served from github at https://github.com/returntocorp/semgrep, has in the "More" section a link called "Contributing" that goes to:

* https://semgrep.dev/docs/contributing/how-to-contribute/

The link yields "Page not found".  I think the corrected link is:

* https://semgrep.dev/docs/contributing/contributing-code/

Additionally, on the issue submission form where I am typing this, there is a link on the right called "Contributing guidelines" that goes to:

* https://github.com/returntocorp/semgrep/blob/6dee7997ca1571713ebac6821e91ddc1ad5b10d2/CONTRIBUTING.md

which contains a link called "Contribution guidelines can be found in `doc/`" that links to:

* https://semgrep.dev/docs/contributing/how-to-contribute/

which is the same broken link.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1744/semgrepreadmemd-broken-contributing-link. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by underyx** [comment]
fixed by https://github.com/returntocorp/semgrep/pull/5894
