### ISSUE TITLE
semgrep: command not found

### ISSUE THREAD

**Issue by RobertB97** [semgrep/semgrep#5892]
Hello
I installed semgrep with "python3 -m pip install semgrep" which was successful. However using the semgrep --help yields "semgrep: command not found". I am using a vm with ubuntu 20.04. Any idea what the cause of this might be?
Thanks in advance

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1746/semgrep-command-not-found. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
Is the directory where `pip` installs in your `$PATH`? I believe this is `~/.local/bin` by default.

**Comment by RobertB97** [comment]
semgrep is in `~/.local/bin` . When i use `echo $PATH`, the directory `~/.local/bin` is listed so that should be working right?

**Comment by kopecs** [comment]
I would expect that to work, in that case. If it isn't working, here's some additional information which would help troubleshoot:
- The result of `sh -c "echo \$PATH"`
- The contents of your bashrc (or whatever equivalent for your shell), to the extent it modifies your path
- The result of `pip list`
- The result of `which semgrep`

**Comment by RobertB97** [comment]
The result of sh -c "echo \$PATH" 
/sbin:/bin:/usr/bin:/usr/local/bin:/snap/bin:/opt/mssql-tools18/bin:/opt/mssql-tools18/bin:/home/Robert/Downloads/.dotnet:/home/Robert/Downloads/.dotnet

pip list:
Package                 Version             
----------------------- --------------------
apt-xapian-index        0.49                
astor                   0.8.1               
attrs                   21.4.0              
Automat                 0.8.0               
azure-core              1.24.2              
azure-storage-blob      12.13.0             
blinker                 1.4                 
boltons                 21.0.0              
bracex                  2.3.post1           
certifi                 2019.11.28          
chardet                 3.0.4               
click                   8.1.3               
click-option-group      0.5.3               
cloud-init              22.2                
colorama                0.4.3               
command-not-found       0.3                 
config                  0.5.1               
configobj               5.0.6               
constantly              15.1.0              
cryptography            2.8                 
cupshelpers             1.0                 
dbus-python             1.2.16              
defer                   1.0.6               
defusedxml              0.7.1               
distro                  1.4.0               
distro-info             0.23ubuntu1         
entrypoints             0.3                 
face                    20.1.1              
galternatives           1.0.6               
glom                    22.1.0              
graphviz                0.20.1              
httplib2                0.14.0              
hyperlink               19.0.0              
idna                    2.8                 
importlib-metadata      1.5.0               
importlib-resources     5.9.0               
incremental             16.10.1             
isodate                 0.6.1               
Jinja2                  2.10.1              
jsonpatch               1.22                
jsonpointer             2.0                 
jsonschema              4.9.1               
keyring                 18.0.1              
language-selector       0.1                 
launchpadlib            1.10.13             
lazr.restfulclient      0.14.2              
lazr.uri                1.0.3               
lubuntu-update-notifier 0.1                 
macaroonbakery          1.3.1               
MarkupSafe              1.1.0               
more-itertools          4.2.0               
msrest                  0.7.1               
netifaces               0.10.4              
oauthlib                3.1.0               
olefile                 0.46                
packaging               21.3                
peewee                  3.15.1              
pexpect                 4.6.0               
Pillow                  7.0.0               
pip                     20.0.2              
pkgutil-resolve-name    1.3.10              
protobuf                3.6.1               
pyasn1                  0.4.2               
pyasn1-modules          0.2.1               
pycairo                 1.16.2              
pycups                  1.9.73              
PyGObject               3.36.0              
PyHamcrest              1.9.0               
PyJWT                   1.7.1               
pymacaroons             0.13.0              
PyNaCl                  1.3.0               
pyodbc                  4.0.34              
pyOpenSSL               19.0.0              
pyparsing               3.0.9               
pyparted                3.11.2              
PyQt5                   5.14.1              
pyRFC3339               1.1                 
pyrsistent              0.15.5              
pyserial                3.4                 
python-apt              2.0.0+ubuntu0.20.4.7
python-debian           0.1.36ubuntu1       
python-lsp-jsonrpc      1.0.0               
pytz                    2019.3              
pyxdg                   0.26                
PyYAML                  5.3.1               
ranger-fm               1.9.3               
reportlab               3.5.34              
requests                2.22.0              
requests-oauthlib       1.3.1               
requests-unixsocket     0.2.0               
ruamel.yaml             0.17.21             
ruamel.yaml.clib        0.2.6               
SecretStorage           2.3.1               
semgrep                 0.108.0             
service-identity        18.1.0              
setuptools              45.2.0              
simplejson              3.16.0              
sip                     4.19.21             
six                     1.14.0              
sos                     4.3                 
ssh-import-id           5.10                
staticfg                0.9.5               
systemd-python          234                 
tqdm                    4.64.0              
Twisted                 18.9.0              
typing-extensions       4.3.0               
ubuntu-advantage-tools  27.9                
ubuntu-drivers-common   0.0.0               
ufw                     0.36                
ujson                   5.4.0               
unattended-upgrades     0.1                 
urllib3                 1.26.11             
usb-creator             0.3.7               
wadllib                 1.3.3               
WALinuxAgent            2.2.46              
wcmatch                 8.4                 
wheel                   0.34.2              
wrapt                   1.14.1              
xkit                    0.0.0               
zipp                    3.8.1               
zope.interface          4.7.1  

which semgrep returns nothing

**Comment by kopecs** [comment]
Given that `~/.local/bin` isn't in your PATH, it looks like you still need to add that. You can do this by adding
```
export PATH="$HOME/.local/bin:$PATH"
```
to `~/.bashrc` and running `source ~/.bashrc`.

**Comment by RobertB97** [comment]
That works. Thank you very much!

**Comment by ievans** [comment]
@kopecs is this expected behavior on ubuntu 20 or is there something we can fix in our packaging?

**Comment by kopecs** [comment]
@ievans This is expected if you're doing a user install with pip.
