### ISSUE TITLE
Semgrep base usage instructions should not refer me to a website.

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#5896]
**Describe the bug**
At the command line, type:

`$> semgrep`

I see:
`[ERROR] No config given. Run with `--config auto` or see https://semgrep.dev/docs/running-rules/ for instructions on running with a specific config`

I expect to get more comprehensive usage instructions beyond the auto option. If I'm using the command line, I'm used to working my way around the command line, and don't want to search a website for the answer. I want the program I'm interacting with to tell me how to use it. 

**Expected behavior**
I'd expect options that are detailed on the website like:

```
BASIC USAGE
  semgrep [--config auto | rule-id | local_rule.yml ] [-e 'RULE_SYNTAX' --lang=LANGUAGE] [PATH/TO/SOURCE]

DESCRIPTION
Run Semgrep on a the specified file. If no path is given, Semgrep will run on all files in the current directory.

<describe individual commands here>
```

Note how I currently wrote the "basic usage" both the `--config` option and the `-e` option are listed as optional, and we need to anntoate that you must specify one of them. I forget the man syntax for that though.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
command line install v 0.108.0

**Use case**
What will fixing this bug enable for you?
Staying at my terminal rather than having to fire up a web browser. 

I know I've filed a related bug in the past. Sorry.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1751/semgrep-base-usage-instructions-should-not-refer-me-to-a-website. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
> Note how I currently wrote the "basic usage" both the --config option and the -e option are listed as optional, and we need to annotate that you must specify one of them. I forget the man syntax for that though.

I believe `{a | b}` is fairly standard for exactly one of either `a` or `b`. I'd probably expect our usage string to be:
```
semgrep { --config CONF | -e PATTERN -l LANG } [OPTIONS] [FILES ...]
```

**Comment by efortuna** [comment]
@kopecs thanks for cleaning that up for me! 

The point for this bug being, we should do better, at explaining our options rather than referring to a docs page. :-D

**Comment by kopecs** [comment]
Would definitely agree---something like https://github.com/click-contrib/click-man + some handwritten (or generated from docs maybe?) man pages about pattern syntax would potentially be an option for us (though click-man doesn't work out of the box because we have some hidden options without help text it fails on).

**Comment by brendongo** [comment]
Are the configuration options in the `semgrep scan --help` text insufficient?

I disagree that the error message of an improper usage needs to tell the user how to use a tool. `pip3 install nonexsistent.py` doesnt tell the user all about a requirements.txt file, `git status` when used outside a git project doesn't explain more than `fatal: not a git repository (or any of the parent directories): .git` 

Should we just be pointing users to the help text on errors?

**Comment by kopecs** [comment]
I understood this more as commentary on our help message, rather than improper usage behaviour. I would agree with @brendongo to the extent that I would not expect the full help text on an incorrect usage; I think we'd ideally print a usage string or point to `semgrep --help` or a manpage before telling people to use `--config auto`.

**Comment by efortuna** [comment]
printing the output of `semgrep --help` when you type `semgrep` would be sufficient (which gives usage instructions). @brendongo your examples are cherrypicked to not be the top level command. To use your two example programs, if you type `git`, the output is identical to `git --help` (regardless of whether you're in a repo or not) and if you type `pip3` it's identical to `pip3 --help`.

**Comment by brendongo** [comment]
Oh I see. So it's less the improper usage getting instructions and more plain usage without any flags getting instructions.

**Comment by brendongo** [comment]
To get this to work we need to deprecate `semgrep` being an alias for `semgrep scan`
