### ISSUE TITLE
taint mode with pattern-sanitizers+not_conflicting incorrectly missing findings

### ISSUE THREAD

**Issue by efortuna** [semgrep/semgrep#5897]
**Describe the bug**
See the playground rule and test code: https://semgrep.dev/s/307D
Two findings _should_ be produced, but only one is matched. I also tested this on the command line.

I think what happens is semgrep thinks because "all function calls are sanitizers" , and line 8 is ultimately wrapped in a new function call, it's safe. BUT since the taint rule was that `user_input` must not reach qux, it failed to catch it. I also wrote a second use case to show that you don't have to have the source and sink on the same line. 

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
What will fixing this bug enable for you?

Trusting correctness of semgrep's taint mode

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1752/taint-mode-with-pattern-sanitizersnot-conflicting-incorrectly-missing. _Note_: this link is for r2c use only and is not accessible publicly.
