### ISSUE TITLE
Tweak pre-commit hook to add --error, make default flags non-overridable

### ISSUE THREAD

**Issue by aneeshusa** [semgrep/semgrep#5899]
**Is your feature request related to a problem? Please describe.**
I previously filed https://github.com/returntocorp/semgrep/issues/4386
about adding some default flags to the pre-commit hook configuration,
which y'all were able to fix in https://github.com/returntocorp/semgrep/issues/4386 (thanks again).
I have been doing some more semgrep'ing and realized we could make this even more ergonomic:
- The default `args` in the `.pre-commit-hooks.yaml` here don't include `--error`,
  so out of the box the pre-commit hook won't fail on any findings, just emit output.
  This isn't useful for CI validation.
- We set `args` in the .pre-commit-hooks.yaml in this file.
  If you want to add additional args (like `--error`) in a consuming `.pre-commit-config.yaml` file,
  then this overrides the existing `args`,
  meaning you have to copy all of them into your `.pre-commit-config.yaml` file.
  (If you don't set `args` in a `.pre-commit-config.yaml` file then the default `args` are used.)

**Describe the solution you'd like**
I'd like to request two changes:
- Get rid of the `args` in the `.pre-commit-hooks.yaml` file in this repo.
  Instead, add those flags to the `entry` field in the `.pre-commit-hooks.yaml`;
  per https://pre-commit.com/#creating-new-hooks `entry` can contain flags
  that can't be overridden (and don't need to be re-specified) by consumers.
- Add `--error` to the default list of flags (as part of the `entry`).

Still haven't gotten OSS contribution approval, otherwise I would have sent a PR.
Happy to review any PR that gets made for this.

**Describe alternatives you've considered**
The alternative (which I am using so far) is to manually specific `--error`
as well as a copy of all the defaults args
in every one of my repos' `.pre-commit-config.yaml` files that uses the semgrep hook.

**Use case**
Make it easier to use semgrep via pre-commit

**Additional context**
None

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1754/tweak-pre-commit-hook-to-add-error-make-default-flags-non-overridable. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spencerdrak** [comment]
Thanks for the report - we're looking into how to proceed and will be in touch here soon.

**Comment by brendongo** [comment]
The proposed changes sound good btw.

**Comment by aneeshusa** [comment]
I bumped our internal process for OSS contribution approval (currently pending CLA approval).

**Comment by aneeshusa** [comment]
Our process for OSS contribution approval has moved forward and I believe we'll be signing the corp CLA soon.
