### ISSUE TITLE
semgrep --verbose says there is a "list of default ignores: https://semgrep.dev/docs/cli-usage/#ignoring-files"

### ISSUE THREAD

**Issue by smcpeak** [semgrep/semgrep#5903]
If `semgrep` is run with `--verbose`, it prints a message about `.semgrepignore`:

```
$ semgrep -e print -l python --verbose hello.py 
No .semgrepignore found. Using default .semgrepignore rules. See the docs for the list of default ignores: https://semgrep.dev/docs/cli-usage/#ignoring-files
Rules:
[...]
```

First, the link https://semgrep.dev/docs/cli-usage/#ignoring-files is semi-broken.  It gets redirected to https://semgrep.dev/docs/cli-reference/ but without the anchor, meaning the referenced content about ignore files isn't immediately visible.

Second, the message talks about "default ignores", but the linked content does not acknowledge or describe what those are.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

Built from source on Linux/x86_64.  Commit 465f7ee4e3.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1755/semgrep-verbose-says-there-is-a-list-of-default-ignores. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spencerdrak** [comment]
@smcpeak would the docs here provide sufficient information for what you'd expect to see there? https://semgrep.dev/docs/ignoring-files-folders-code/#understanding-semgrep-defaults

**Comment by smcpeak** [comment]
Yes!  That looks exactly like what I'd expect the message to link to.

**Comment by spencerdrak** [comment]
Excellent, we're going to look further into how we want to proceed but we'll make the link between this usage of semgrep and those docs more explicit. Thanks!
