### ISSUE TITLE
semgrep metavariable pattern seems match wrong code

### ISSUE THREAD

**Issue by zhengow** [semgrep/semgrep#5904]
**Describe the bug**
metavariable pattern seems match wrong code

**To Reproduce**
https://semgrep.dev/s/Dx1y

**Expected behavior**
I think it should only match `print(1)`, however it also matches another line.

**Screenshots**
![image](https://user-images.githubusercontent.com/38389586/183796528-59058a7c-1e6a-4579-94f0-182090f5636e.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1756/semgrep-metavariable-pattern-seems-match-wrong-code. _Note_: this link is for r2c use only and is not accessible publicly.
