### ISSUE TITLE
Semgrep 0.108.0 PyPi error on Apple M1 silicon 

### ISSUE THREAD

**Issue by navhits** [semgrep/semgrep#5911]
**Describe the bug**
Semgrep 0.108.0 installation from PyPi on a M1 Silicon Macbook results in error when invoking `semgrep scan` or `semgrep ci`.
This issue is gone when installed from homebrew.

**To Reproduce**
1. On a M1 Macbook, install semgrep from pypi (`pip3 install semgrep==0.108.0`)
2. Scan a repo (`semgrep scan`)

**Expected behavior**

Semgrep should have run successfully

**Screenshots**

Error when running `semgrep ci`

<img width="838" alt="Screenshot 2022-08-11 at 3 17 12 PM" src="https://user-images.githubusercontent.com/22239584/184107681-eb684a4a-7436-4bed-98e1-291a2f0d3cbf.png">

Error when running `semgrep scan`

<img width="842" alt="Screenshot 2022-08-11 at 3 18 57 PM" src="https://user-images.githubusercontent.com/22239584/184107757-f143dec5-22ff-4236-b6ec-c8976e4b2b7f.png">

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

`Darwin FWS-CHE-LT-7567 21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 arm64`
Python version - 3.10.5

**Workaround**
1. Uninstall the PyPi version (`pip3 uninstall semgrep`)
2. Install and use from homebrew (`brew install semgrep`)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1762/semgrep-01080-pypi-error-on-apple-m1-silicon. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by spencerdrak** [comment]
Hi there @navhits, we've tried to repro this error but we're unable to do so from an M1 mac using the same configs on a couple of repos. Is there any chance that you'd be able to provide us with a repo (or some source code) that replicates the failure? thanks!

**Comment by navhits** [comment]
Hi, I reinstalled with PyPi version and tried this again and it works. When I tried this twice before it didn't however.
Assuming some environment variables caused this problem.

**Comment by brendongo** [comment]
🤔 weird. but glad it works now! Closing this issue.
