### ISSUE TITLE
JSON keys bound to metavariables don't unify

### ISSUE THREAD

**Issue by zhengow** [semgrep/semgrep#5912]
**Describe the bug**
The match result is not correct.

**To Reproduce**
https://semgrep.dev/s/0Bjq

**Expected behavior**
It should match `line 2` and `line 5`, which is `    "bob": 123,` and `        "great": 123`

**Screenshots**
![image](https://user-images.githubusercontent.com/38389586/184323218-3b3461d1-0d2f-4a5e-9d11-8c94a9eb568c.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1763/json-semgrep-seems-to-have-bugs. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by kopecs** [comment]
It looks like there's an issue here relating to combining the patterns w/ metavariable equivalence. That said, this should be equivalent to the pattern `$K: 123`, and match lines 2, 3, and 5.
