### ISSUE TITLE
Fingerprint

### ISSUE THREAD

**Issue by iinikolaev** [semgrep/semgrep#5915]
Hello everybody!
Small question for developers.
How semgrep generate fingerprint and md5sum? Tell me the rule pzl or link to source code
Thanks!
![image](https://user-images.githubusercontent.com/32400162/184351029-7beac630-e757-4667-8f70-755bef8147fc.png)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1765/fingerprint. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by brendongo** [comment]
Hi @iinikolaev you can check out the source code here: https://github.com/returntocorp/semgrep/blob/4493cdb81ea7f6bdb7c206cec1d0d1ea86b1115a/cli/src/semgrep/rule_match.py#L269
