### ISSUE TITLE
Range of statements pattern with '...' is wrong

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#593]
https://semgrep.live/Ang?version=develop

```yaml

rules:
  - id: eval_nodejs
    patterns:
      - pattern-inside: |
          const $EXPRESS = require('express');
          ...
          const $APP = $EXPRESS();
          ...
          $APP.$METHOD(..., function $FUNC($REQ, $RES, ...){ ... });
      - pattern: |
          eval(..., "..." + $REQ.$QUERY.$VAR + "...", ...)
```

matches

```javascript
var coolJS = require('cool-js');
var veryCool = coolJS();
veryCool.get(user.data, function (user, prefs) {
    // ok
    var resp = eval("(" + user.info.name + ")");
    // ok
    var z = new Function('arg1', 'arg2', prefs.query.name)
    z(1, 2);
    // ok
    setTimeout('alert(' + prefs.body.name, 0);
    // ok
    setInterval(prefs.body.name, 0);
    res.send('Response</br>' + resp);
});
```

IFF this code block follows a properly matching code block

I think it's related to being greedy until the end of the file

https://semgrep.live/GNB?version=develop matches

and the second code block by itself doesn't match:

https://semgrep.live/RNE?version=develop

**Comment by DrewDennison** [comment]
@aryx can you confirm this is related to https://github.com/returntocorp/semgrep/issues/430?

**Comment by aryx** [comment]
Yes, probably related to #430 , the pattern-inside does not do what is intented because
a stmts pattern will actually return the whole range because of the implicit '...' added at the end
of those stmts in the pattern.

**Comment by aryx** [comment]
With deep stmt matching it makes #430 even worse indeed.

**Comment by dlukeomalley** [comment]
This appears to work now. Closing this ticket! 

@DrewDennison please re-open if I've misunderstood https://semgrep.live/Ang?version=develop
