### ISSUE TITLE
Test-files for json-tests

### ISSUE THREAD

**Issue by fabian-zeindl-oebb** [semgrep/semgrep#5938]
**Describe the bug**
The documentation says that test-files should use a comment to indicate which lines are matching and which aren't.

Unfortunately, json does not support comments, so the behaviour is not clear or at least not documented.

How can multiple test-cases for json be implemented?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1782/test-files-for-json-tests. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
I think the JSON parser we use in semgrep actually just abuse the javascript parser, and so comments are allowed in it. 
See the test files here for example: https://github.com/returntocorp/semgrep/tree/develop/semgrep-core/tests/json
