### ISSUE TITLE
Support XML as a language without ordering of keys

### ISSUE THREAD

**Issue by fabian-zeindl-oebb** [semgrep/semgrep#5939]
**Is your feature request related to a problem? Please describe.**
Many xml-based languages don't care about the ordering of the keys, for example in `pom.xml` the following two snippets are equivalent:

````xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <configuration>
        <somethingInvalid/>
    </configuration>
</plugin>
````

````xml
<plugin>
    <configuration>
        <somethingInvalid/>
    </configuration>
    <artifactId>maven-compiler-plugin</artifactId>
    <groupId>org.apache.maven.plugins</groupId>
</plugin>
````

**Describe the solution you'd like**
I would like to be able to use the following semgrep rule to match both snippets above:

````xml
<plugin>
    <configuration>
        <somethingInvalid/>
    </configuration>
    ...
</plugin>
````

The "..." would match additional keys like in yaml or json.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1783/support-xml-as-a-language-without-ordering-of-keys. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by fopinappb** [comment]
About this, one thing I've learnt is that `...` capture is *greedy*.

So writing a rule like that will only report the first plugin entry, as `...</plugin>` will capture until the last plugin after that match.

Just as an heads up!

**Comment by aryx** [comment]
Ok I think I have a fix for this.

**Comment by underyx** [comment]
@aryx aren't some XML documents order-sensitive though?

**Comment by underyx** [comment]
Ah, I see you added an option `xml_children_ordered`, beautiful ☺️

**Comment by fabian-zeindl-oebb** [comment]
> About this, one thing I've learnt is that `...` capture is _greedy_.
> 
> So writing a rule like that will only report the first plugin entry, as `...</plugin>` will capture until the last plugin after that match.
> 
> Just as an heads up!

Are you sure about this?

The `...` in my rule is indented, so it should not match anything on the outer layer, it should only match inside the `<plugin></plugin>`.

**Comment by aryx** [comment]
There's a new languages: [ xml ] now in semgrep, so you don't have to use anymore the generic mode
to write patterns for XML.
With languages: [ xml ], the indentation of ... does not matter anymore, or the indentation in the target file does not matter either. We're doing the matching at the AST-level.

**Comment by fabian-zeindl-oebb** [comment]
Great, thank you for the clarification.

**Comment by fopina** [comment]
@fabian-zeindl-oebb you're right, if XML is indented that’d work, but mine weren’t

@aryx looking forward to test it and clean up most of my rules! Mostly the ordering patterns  🙏

**Comment by aryx** [comment]
you'll have to use the option: xml_children_ordered : false in your rule, like I did here:
https://github.com/returntocorp/semgrep/commit/f9f61b0fbdad8070e111f69ba9dabe49561fa24b#diff-3e4b4f757303e6afe72aad12202ff49b755a3f630dce54762b04a3d7ef2c53f6
