### ISSUE TITLE
semgrep --test does not scan current directory in docker

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#5965]
Running `semgrep --test` in the docker fails, where I expect it to run the tests in the current directory.

    docker run -v "$PWD:/foo" -w "/foo" returntocorp/semgrep:latest semgrep --test

```
METRICS: Using configs from the Registry (like --config=p/ci) reports pseudonymous rule metrics to semgrep.dev.
To disable Registry rule metrics, use "--metrics=off".
Using configs only from local files (like --config=xyz.yml) does not enable metrics.

More information: https://semgrep.dev/docs/metrics

```

No error message, exit code 2.

When I run `semgrep --test` on my local system, it scans the current directory. That the docker behaves differently can be explained by [`adjust_for_docker`](https://github.com/returntocorp/semgrep/blob/31433af7845808b261e1367de094a478bcfa1c7a/cli/src/semgrep/config_resolver.py#L408-L420).

`adjust_for_docker` raises a SemgrepError, with the message `Detected Docker environment without a code volume, please include '-v "${PWD}:/src"'`. However, this error is not shown in the output. Also, I don't necessarily want to mount my code in `/src`. When I run this in a GitLab pipeline, my repository is mounted somewhere else.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1805/semgrep-test-does-not-scan-current-directory-in-docker. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sjord** [comment]
@spencerdrak What do you think of this issue?

**Comment by spencerdrak** [comment]
@Sjord so sorry for the late reply on this, somehow the notification was lost. I'm actually unsure here, and I'm going to re-assign to the team who owns this now. I'll ping someone here shortly on that. thanks for your patience!
