### ISSUE TITLE
Taint mode bug when matching the foreach statement

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#5971]
**Describe the bug**
The taint mode might not track data flow through `foreach` statement

**To Reproduce**
https://semgrep.dev/s/94LY

**Expected behavior**
The `foreach` statement should be tracked and the sink function in the provided code should be matched.

**What is the priority of the bug to you?**
P1: important to fix or quite annoying. It might ignore lots of potential findings in the code

**Environment**
https://semgrep.dev/playground/

**Use case**
Tried to do taint mode analysis in the source code to do the security research and audit.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1813/taint-mode-bug-when. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
I have a candidate solution for this but I need some time to prepare a PR. Please bear with me!

**Comment by backcover7** [comment]
@IagoAbal I suppose this issue could also be solved by the thought which is regarding to the propagation library we talked about in the slack.

**Comment by IagoAbal** [comment]
I have a fix for this already, but I was quite busy getting #5697 finalized (it may interest you too). I think I can open a PR next week.
