### ISSUE TITLE
`USER` in Dockerfile conflicts with other workflows in self hosted runners.

### ISSUE THREAD

**Issue by rubensf** [semgrep/semgrep#5972]
## Description
Our team uses self hosted runners - in which case they maintain some state between runs, particularly checkouts. Some actions, like the Github Provided [actions/checkout](https://github.com/actions/checkout), will try to clear up resources, eg previous runs. Unfortunately, since the semgrep container acts as [`root`](https://github.com/returntocorp/semgrep/blob/v0.110.0/Dockerfile#L21), other actions that use Github's default user are unable to modify/clear resources.

## Reproduce
Use the suggested configuration for semgrep:
```
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
```

And connect to self hosted runners. Run workflows in a way that you'll get a non-semgrep workflow running on the same runner as the semgrep workflow. The new workflow will fail with: 
```
Run actions/checkout@v3
...
 Error: error: cannot lock ref 'refs/heads/<semgrep prev run branch>': Unable to create '<path to workspace>/.git/refs/heads/<semgrep prev run branch>': Permission denied
  Error: error: Error deleting branch '<semgrep prev run branch>'
  Warning: Unable to prepare the existing repository. The repository will be recreated instead.
  Deleting the contents of '<workspace>'
  Error: Command failed: rm -rf "<workspace>/.git"
```

## Expected Behavior
Future workflows should succeed without issue.

## Priority of the Bug
- [x] P2: regular bug that should get fixed

For now, we can continue using the semgrep action.

## Environment
Trying to use the semgrep docker in github. The default example should trigger this problem.

## Use Case
Migrating from the Github Action to the Docker Container

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1815/user-in-dockerfile-conflicts-with-other-workflows-in-self-hosted. _Note_: this link is for r2c use only and is not accessible publicly.
