### ISSUE TITLE
Sign-in with GitHub uses first account email, not the primary one

### ISSUE THREAD

**Issue by linusg** [semgrep/semgrep#5978]
**Describe the bug**
When choosing to sign up/in with a GitHub account on semgrep.dev, the first email from the GitHub is shown in the organization member settings, not the current primary selection (with no apparent way of changing it beyond removing that email from GitHub).

**To Reproduce**

- Go to `https://github.com/settings/emails`
- Add a second email address
- Set the new email address as the primary address
- Go to `https://semgrep.dev/login`
- Choose "Sign in with GitHub"
- Go to `https://semgrep.dev/orgs/<name>/settings/members`
- First email address is shown, not the primary one

**Expected behavior**
Semgrep should either:
- Respect the primary email address selection
- Add an option to change the email address that is being used

**Screenshots**

Semgrep.dev:

![image](https://user-images.githubusercontent.com/19366641/186676837-f7e51892-2bd0-48d7-890b-ebedb07c76b0.png)

My GitHub email settings:

![image](https://user-images.githubusercontent.com/19366641/186678561-a63b64dd-5dcd-43e9-9a62-f13107ae6d74.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
This is on `semgrep.dev`.

**Use case**
I don't want to leak my personal/private email address when joining an organization. In a company organization, people will have often have a company address associated to their GitHub account, but it still shows the personal email most people used when they once signed up to GitHub.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1816/sign-in-with-github-uses-first-account-email-not-the-primary-one. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by milanwilliams** [comment]
Hi @linusg! We just added a new tab to the Settings page called "Account", where you can change the primary email address Semgrep uses and update your email preferences. Let me know if this works for you!
<img width="888" alt="Screen Shot 2022-08-29 at 9 40 47 PM" src="https://user-images.githubusercontent.com/19784302/187378865-fc531164-27b2-4f63-a269-bf5e77790788.png">

**Comment by linusg** [comment]
Thanks for the quick implementation & response, that looks great! Unfortunately the dropdown is empty for me with no available options to chose from, and doesn't seem to allow manual input either:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/19366641/187398490-801cc1d0-667c-49e2-8983-68c19a944b80.png">

I was able to set my preferred address through a manual API request as done by the update button, so that problem is solved for me 😄
