### ISSUE TITLE
Parsing date format strings in Python

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#599]
Semgrep unable to parse format strings for date objects: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

For example:
```
search = f"SINCE {datetime.date.today():%d-%b-%Y}"
```
will print out `SINCE 28-Apr-2020`.

https://semgrep.live/Y7W

**Comment by aryx** [comment]
Yes right now there is a hack to accept certain tokens after the ':' in fstring, again parser_python.mly
look at the format_token grammar rule. Probably need to add more, or to change the strategy
and use a different lexer for this context but this is more complicated (hence my hack on adding tokens in the list in format_token)

**Comment by brendongo** [comment]
Fixed. Going out on next release.
