### ISSUE TITLE
unable to print if statement body in java

### ISSUE THREAD

**Issue by effortlessdevsec** [semgrep/semgrep#5994]
want to print if statement body but semgrep match full code.

`id: if_else_java
patterns:
 - pattern: |
    if($X==$Y) {...}

message: Semgrep found a match
languages: [java]
severity: WARNING
`
![image](https://user-images.githubusercontent.com/30777722/187063527-37a182fb-e8a0-4206-b834-d88befe5252c.png)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1824/unable-to-print-if-statement-body-in-java. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by effortlessdevsec** [comment]
@r2c-demo  can you provide me some reference how to do this !!! not having permission to access above link

**Comment by aryx** [comment]
Oh the r2c-demo message is for r2c employees only. Just ignore it.

**Comment by aryx** [comment]
Can you share a semgrep.dev link to your example (It's easier to fix from a working semgrep.dev link).

**Comment by aryx** [comment]
@p4p3r answered on Slack: https://semgrep.dev/s/QLEk

**Comment by bmahe** [comment]
Closing that issue since it was answered on slack.
@effortlessdevsec feel free to re-open it in case you still are experiencing that problem.

**Comment by aryx** [comment]
Seems related to a very old issue: https://github.com/returntocorp/semgrep/issues/1375
