### ISSUE TITLE
False negative detections using basic operator expression 

### ISSUE THREAD

**Issue by dmaciejak** [semgrep/semgrep#5997]
**Describe the bug**
Puzzled by the result of the rule and code enclosed. Is it a bug or expected ?

**To Reproduce**
Please check: https://semgrep.dev/s/6qeL

**Expected behavior**
Expecting the operator results to be consistent.

**Screenshots**
NA

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Using semgrep.dev

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1826/false-negative-detections-using-basic-operator-expression. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
This is because of https://semgrep.dev/docs/writing-rules/data-flow/constant-propagation/

**Comment by aryx** [comment]
You can disable it if you want. See https://semgrep.dev/s/8YZq
