### ISSUE TITLE
Spacing in Literal String Interpolation in Python

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#600]
Space inside '{}' in python f string causes parser to fail. 

```
foo = 1
bar = f"{foo }"
```
is valid python

https://semgrep.live/6dw

Real world example: https://github.com/home-assistant/core/blob/893f796df2b3243852f70341c8557109dcc33a80/homeassistant/components/greeneye_monitor/sensor.py#L111

**Comment by aryx** [comment]
still pfff/lang_python/parsing/parser_python.mly
The comments are supposed to be skipped in parse_python.ml, so not sure why
in this context they are not.

**Comment by brendongo** [comment]
Fixed. Going out on next release.
