### ISSUE TITLE
.class property cannot be parsed in Java

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6002]
**To Reproduce**
https://semgrep.dev/s/dzA0

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1828/class-property-cannot-be-parsed-in-java. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
As far as I can tell the issue is that in Pfff `Hello.class` is represented this way:
```
E(
  OtherExpr(("ClassLiteral", ()),
    [T(
       {t_attrs=[]; 
        t=TyN(
            Id(("Hello", ()),
              {id_info_id=1; id_hidden=false; id_resolved=Ref(None); 
               id_type=Ref(None); id_svalue=Ref(None); }));
        })]))
```
And in our Tree Sitter front-end is represented this way:
```
DotAccess(
N(
Id(("Hello", ()),
    {id_info_id=7; id_hidden=false; id_resolved=Ref(
    None); id_type=Ref(
    None); id_svalue=Ref(
    None); })), (),
FN(
Id(("class", ()),
    {id_info_id=8; id_hidden=false; id_resolved=Ref(
    None); id_type=Ref(
    None); id_svalue=Ref(
    None); })))
```

**Comment by aryx** [comment]
@emjin maybe that's the kind of bug we could detect automatically.
Note that semgrep-core -diff_pfff_tree_sitter also shows the difference.

**Comment by aryx** [comment]
Tree-sitter is wrong. I'm not sure why because there is a grammar rule for class_literal, but it does not seem to trigger.

**Comment by aryx** [comment]
Oh someone opened an issue about it: https://github.com/tree-sitter/tree-sitter-java/issues/121

**Comment by aryx** [comment]
This looks like the better fix: https://github.com/tree-sitter/tree-sitter-java/pull/125#pullrequestreview-1111528606
