### ISSUE TITLE
Unsupported ellipsis in symbolic propagation option

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6003]
**Describe the bug**
The ellipsis does not work in symbolic propagation. This issue could be solved by using taint mode. But does semgrep has a simple way to resolve such conditions based on symbolic propagation?

**To Reproduce**
https://semgrep.dev/s/7l6Q

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1829/unsupported-ellipsis-in-symbolic-propagation-option. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Note for whoever takes this issue (possibly myself): `hello.x().y().z()` matches as expected, symbolic propagation already works with `DotAccess`. Presumably we need to make it work in combination with `DotAccessEllipsis` and the example should then work.
