### ISSUE TITLE
Support for output templates

### ISSUE THREAD

**Issue by navhits** [semgrep/semgrep#6012]
I usually parse the result from the Semgrep CLI into a custom template. For this, I would depend on the JSON output and then use Jinja to render any template I want.

If Semgrep CLI supports an additional flag `--output-template`, which takes the path to the template and auto-populates the values, it helps to have a dynamic way for anyone to use any template they want.
The inspiration for this request comes from one of [Tracee's features](https://aquasecurity.github.io/tracee/v0.8.1/integrating/go-templates/).
This feature will help people use their own creative output formats, or they might have the need to have a specific format, say for compliance reasons.

I've so far written a wrapper to handle this templatization. However, the template is manually added to the wrapper.

**Use case**
I'd like to use Semgrep across different pipelines, and devs/teams should have the ability to use a template of their choice instead of me giving a standard format. Although the result JSON is going to be the same.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1833/support-for-output-templates. _Note_: this link is for r2c use only and is not accessible publicly.
