### ISSUE TITLE
Add aarch64 to releases

### ISSUE THREAD

**Issue by ck3mp3r** [semgrep/semgrep#6015]
aarch64 missing in release packages for Linux and Darwin.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1834/add-aarch64-to-releases. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ck3mp3r** [comment]
Closed as "completed"?!

**Comment by klardotsh** [comment]
Likewise would love to see this reopened and tackled if at all possible. Happy to find some time to help, if necessary (and if steps can be identified to help with: I'm not much of an OCaml guy, but I'm familiar with dealing with the aarch64 transition).
