### ISSUE TITLE
Comma in String Interpolation is Implicit Tuple in Python

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#602]
If there is a comma after a variable in an f string interpolation it is treated as an implicit tuple (same behavior if there is a comma outside a string interpolation i.e. `x = 1,` -> x is `(1,)`)

```
foo = "bar"
baz = f"{foo,}/analog/blah"
# baz is "('bar',)/analog/blah"
```

https://semgrep.live/jyZ

**Comment by brendongo** [comment]
Real world example: https://github.com/home-assistant/core/pull/34833

**Comment by aryx** [comment]
pfff/lang_python/parsing/parser_python.mly, yacc file containing the grammar of python.
We may need to modify also ast_python.ml in the same file to express those cases.
and then the right conversion to the generic AST in pfff/lang_python/analyze/python_to_generic.ml

**Comment by brendongo** [comment]
Fixed. Will go out on next release.
