### ISSUE TITLE
Ellipsis in the constructor body fails

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6051]
**Describe the bug**
The fix here https://github.com/returntocorp/semgrep/issues/5558 makes it happen that semgrep now supports Java constructor matching. However, I found the ellipsis in the constructor body will fail the match in develop mode.

**To Reproduce**
https://semgrep.dev/s/K1dd?develop=true

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1852/ellipsis-in-the-constructor-body-fails. _Note_: this link is for r2c use only and is not accessible publicly.
