### ISSUE TITLE
Wheels for Python 3.10 and Python 3.11

### ISSUE THREAD

**Issue by rouge8** [semgrep/semgrep#6063]
**Is your feature request related to a problem? Please describe.**

It would be nice for the Python wheels to be tagged for Python 3.10.

**Describe the solution you'd like**

It would be nice for the Python wheels to be tagged for Python 3.10.

**Describe alternatives you've considered**

Building from the sdist is slow.

**Use case**

Faster installs using pre-commit.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1862/wheels-for-python-310. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by rouge8** [comment]
At this point it would also be good to add wheels for Python 3.11.

**Comment by hanzo** [comment]
Any estimate for when wheels for Python 3.10 will be added? My organization is in the process of migrating to Python 3.10, but we won't be able to migrate our semgrep-dependent functionality without py3.10 wheels.

**Comment by hanzo** [comment]
Any estimate for when wheels for Python 3.10+3.11 will be added? My organization is in the process of migrating to Python 3.11, but we won't be able to migrate our semgrep-dependent functionality without py3.11 wheels.

**Comment by hanzo** [comment]
@rouge8 Wheels for Python 3.10 and 3.11 are available as of today: https://github.com/returntocorp/semgrep/releases/tag/v1.28.0  🎉

**Comment by hanzo** [comment]
@rouge8 The Python wheels are tagged for 3.10 and 3.11 as of today's release: https://github.com/returntocorp/semgrep/releases/tag/v1.28.0 🎉
