### ISSUE TITLE
List metavariable not working in C#

### ISSUE THREAD

**Issue by jods4** [semgrep/semgrep#6065]
**Describe the bug**
Metavariables like `$...ARGS` don't seem to parse: _Invalid pattern for C#_

**To Reproduce**
[Playground demo](https://semgrep.dev/s/g1NZ)

**Expected behavior**
Pattern should parse and variable should be usable in replacements

**Screenshots**
![image](https://user-images.githubusercontent.com/3832820/189153455-49215adc-9b3b-48a4-96ae-f0dbf3cd38a3.png)

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
Not having list metavariables seriously limits the autofixes one can write (matching without metavariables is working fine, though).

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1864/list-metavariable-not-working-in-c. _Note_: this link is for r2c use only and is not accessible publicly.
