### ISSUE TITLE
Rust parser does not support `mod $MOD { ... }`

### ISSUE THREAD

**Issue by Vasco-jofra** [semgrep/semgrep#6066]
**Describe the bug**
It is impossible to match `mod` statements in rust. Currently, Semgrep outputs the following error `error: Invalid pattern for Rust: mod tests {...}`.

**To Reproduce**
Run the following rule (https://semgrep.dev/s/2enD):
```
id: test
patterns:
  - pattern-inside: |
      mod tests {
          ...
      }
message: |
  found `mod`
languages:
  - rust
severity: INFO
```

**Expected behavior**
Semgrep can parse `mod` statements.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1866/rust-parser-does-not-support-mod-dollarmod. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by emjin** [comment]
Hi! Could you let us know the priority of this issue for you? For now I'll set it to low

**Comment by aryx** [comment]
The problem is not the mod, but the ellipsis in the mod body.
