### ISSUE TITLE
Improvement in matching function call

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6067]
**Is your feature request related to a problem? Please describe.**
Semgrep is used by security researchers to locate source and sink functions. For example, `Thread.sleep(...)` can match a potential DoS attack. However, as you know, developers do not write in the same practice. Someone might write code like `Thread.currentThread().sleep(...)`.

So, the general example is `obj.x().y().z()` is a variant of `obj.x(); obj.y(); obj.z();`.

_**Issue 1:**_
In this case, if I only focus on whether the `z()` is called. So in order to match this code, I need to use rule like `obj. ... .z()`. So, when I tried to locate a lot of sources / sinks, I am gonna need to use `...` every time to match these functions in each line of the rule. My ugly rule will look like the following
`obj1. ... .x()`
`obj2. ... .y()`
`obj3. ... .z()`
`obj4. ... .w()`
...

_**Issue 2:**_
If I do not care about the order of the functions call, I am only concerned about which kinds of functions will be called. For example, if only `x()` and `y()` and `z()` are called at the same time, then the vulnerability exists. The rules like the following should be defined in the same time.
`obj. ... .x(). ... y(). ... .z()`
`obj. ... .x(). ... .z(). ... .y()`
`obj. ... .y(). ... .x(). ... .z()`
`obj. ... .y(). ... .z(). ... .x()`
`obj. ... .z(). ... .x(). ... .y()`
`obj. ... .z(). ... .y(). ... .x()`

Obviously, Semgrep is asking me to do all **permutations** here which makes no sense.

**Describe the solution you'd like**
For issue 1, a simple rule like `obj.x()` should work
For issue 2, a simple rule like `obj.x().y().z()` should work

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1867/improvement-in-matching-function-call. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Do you expect to find also:
```
foo = obj
foo.z()
foo.y()
foo.z()
```
?

I see how enumerating all permutations of 3 is a bit annoying, but it seems OK-ish to do once in a while. How many of your rules does this affect? If it affects many, is it because they share the same sources or sinks?

Could you provide a Semgrep rule where you need to do this to get a sense of how complex it gets?

**Comment by backcover7** [comment]
@IagoAbal Actually, I did encounter such cases when trying to match code pattern in XXE issue. Lots of XML parser need factory class to build an instance of the parser and then parse the xml file. So there will be a lot of possible function calls like `transform()`, `newInstance()` before the last sink function `parse()`. So I need to use `...` to match all sink functions and ignore the `newInstance` in the middle.

And sometimes I also need to add `setFeature()` call in the call chain to identify if the call chain is vulnerable or not. Here's an example, functions `setXIncludeAware()`,  `setNamespaceAware` and `setFeature()` could be in any order.

```
public String DocumentBuilderXincludeSec(HttpServletRequest request) {
        try {
            String body = WebUtils.getRequestBody(request);
            logger.info(body);
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();

            dbf.setXIncludeAware(true);
            dbf.setNamespaceAware(true);
            dbf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
            dbf.setFeature("http://xml.org/sax/features/external-general-entities", false);
            dbf.setFeature("http://xml.org/sax/features/external-parameter-entities", false);

            DocumentBuilder db = dbf.newDocumentBuilder();
            StringReader sr = new StringReader(body);
            InputSource is = new InputSource(sr);
            Document document = db.parse(is);  // parse xml

            NodeList rootNodeList = document.getChildNodes();
            response(rootNodeList);

            sr.close();
        } catch (Exception e) {
            logger.error(e.toString());
            return EXCEPT;
        }
        return "DocumentBuilder xinclude xxe vuln code";
    }
```

**Comment by IagoAbal** [comment]
What about this https://semgrep.dev/s/e8Gb ? Just realized this potential solution right now.

**Comment by IagoAbal** [comment]
For me this is a perfect use case for taint labels!

**Comment by IagoAbal** [comment]
What about this https://semgrep.dev/s/QyL4 ? I guess this feels more complex than `obj. ... .x()` but does what you need I think.

**Comment by backcover7** [comment]
> What about this https://semgrep.dev/s/e8Gb ? Just realized this potential solution right now.

This works for ignoring `newInstance`. But you might not want to see my rule which has a lot of ellipsis in it to make sure no false negatives. It is a good rule but I am not sure I want to do this to locate every function call to avoid false negative.

If this feature could be implemented, I believe the false negatives would be eliminated a lot.

**Comment by backcover7** [comment]
> What about this https://semgrep.dev/s/QyL4 ? I guess this feels more complex than `obj. ... .x()` but does what you need I think.

This seems to be the best approach that semgrep can do in the present. And I can understand how hard to implement what I said in the request, and for now, it's a proper solution the permutation issue. But since I was trying to locate a sink code, can I nest the whole rule as a sink of another taint rule? Should I use join mode to refer this rule?

**Comment by IagoAbal** [comment]
Could you share your rule and some target example code with us, perhaps privately? I can't be 100% sure whether there is a simple way of writing the rule you need without that. 😕 I would like to think that taint labels can do the job because it's pretty powerful, perhaps we just need to re-think the rule and look at it from another perspective. I am just speculating.

For example, this rule https://semgrep.dev/s/zrrz uses taint labels to 1) identify the taint source, and 2) identify a sink; and it does so with a single taint rule.

You can indeed use join mode to chain together multiple taint rules.

**Comment by backcover7** [comment]
@IagoAbal Please take a look here (https://semgrep.dev/s/backcover7:xml-copy)
For each kind of xml parser I have to write several rules to match them. And I need to use an ellipsis for each of them. This expands the rule a lot.
