### ISSUE TITLE
semgrep --test should fail in case of parsing error in a target

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#6068]
**Describe the bug**

`semgrep --test` doesn't fail in case of a parsing error. We want it to fail so that we can detect malformed test cases, unlike in a normal Semgrep scan.

**To Reproduce**

See instructions in upcoming pull request.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

CLI

**Use case**

This is important to ensure that the tests in semgrep-rules repo will run correctly rather than being ignored silently.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1868/semgrep-test-should-fail-in-case-of-parsing-error-in-a-target. _Note_: this link is for r2c use only and is not accessible publicly.
