### ISSUE TITLE
Share semgrep-rules test command between semgrep and semgrep-rules to avoid discrepancies

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#6069]
**Describe the bug**

Both repos semgrep and semgrep-rules should run complete and strict tests that validate and test the rules found in semgrep-rules. See upcoming pull requests in semgrep and semgrep-rules.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1869/share-semgrep-rules-test-command-between-semgrep-and-semgrep-rules-to. _Note_: this link is for r2c use only and is not accessible publicly.
