### ISSUE TITLE
Match `foo();` to `return foo();` (javascript)

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#607]
Would be awesome to match "return expression" with expression pattern:
```
foo();
```

```javascript
function yo() {
  return foo();
}
```

multiline example:
https://semgrep.live/Joo

```
var foo = require('foobar');
...
foo();
```

```javascript
const foo = require('foobar');

function yep() {
    return foo();
}
```

**Comment by nbrahms** [comment]
Hi @inkz ... I think `foo();` is a statement pattern, due to the trailing semicolon, not an expression pattern, so it makes sense that it would not match your return statement.

I think that, in order to match, you would want:
```javascript
foo()
```
for a single-line pattern, or
```javascript
var $FOO = require('foobar');
...
<...$FOO()...>
```
for a multiline pattern.

**Comment by inkz** [comment]
@nbrahms 
sorry for always confusing expressions and statements  :innocent:
multiline pattern does not work https://semgrep.live/Jok

```
var $FOO = require('foobar');
...
<...$FOO()...>
```

Parsing error:
```
invalid pattern \"var $FOO = require('foobar');
...
<...$FOO()...>
\": Parsing.Parse_error
```

**Comment by nbrahms** [comment]
@aryx This is a bug, no?

**Comment by aryx** [comment]
<... ...> can appear only in an expression context, and given the previous likes you started to parse a list of statements. You need the semicolon after ...>, but then we go back to the original problem that it's parsed as an expression statement which will not match the return.

**Comment by aryx** [comment]
I think it's ok to have 'foo();'  match 'var x = foo();' (supported already), and 'return foo();' (TODO, what vassili wants).
We also have 'foo();' match any expression statement deeply implicitely, so 'foo();' match also
'print (foo());' currently. I think it's a good default.
