### ISSUE TITLE
metavariable-comparison: $VAR not in [list] construction does not work

### ISSUE THREAD

**Issue by malexmave** [semgrep/semgrep#6072]
**Describe the bug**
The metavariable-comparison rule does not correctly match based on the following construction:
```yaml
  - metavariable-comparison:
      comparison: $ARG not in [443, 80]
      metavariable: $ARG
```

**To Reproduce**
See [this playground example](https://semgrep.dev/playground/s/YZZW), where [the inverse case works properly](https://semgrep.dev/playground/s/644w).

**Expected behavior**
I would expect the example above to produce a single match.

**Workaround**
The correct behavior can be achieved by using the "not $VAR in [list]" construction (thanks for the hint on Slack, @Sjord!).

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Playground and local install.

**Use case**
Matching a metavariable against an allowlist of possible values, and alerting if it has a different value. e.g.: Allowed ports, cryptographic algorithms, ...

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1871/metavariable-comparison-dollarvar-not-in-[list]-construction-does-not. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sjord** [comment]
`G.NotIn` is simply missing from [this list](https://github.com/returntocorp/semgrep/blob/d324d65be084320ae76be5c282e334deb9cb121f/semgrep-core/src/engine/Eval_generic.ml#L224-L287). It reaches [this raise](https://github.com/returntocorp/semgrep/blob/d324d65be084320ae76be5c282e334deb9cb121f/semgrep-core/src/engine/Eval_generic.ml#L287), but apparently that is silently ignored.
