### ISSUE TITLE
Angular component not parsed

### ISSUE THREAD

**Issue by Denis-Podgurskii** [semgrep/semgrep#6073]
**Describe the bug**
Angular app may have a template injection within the @Component declaration and semgrep is not able to parse it properly, so rule doesn't work

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/playground/s/denis-podgurskii:angular-template-injection

**Expected behavior**
Rule should find template injection within @Component declaration

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
All of them

**Use case**
What will fixing this bug enable for you?
Angular app scan

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1872/angular-component-not-parsed. _Note_: this link is for r2c use only and is not accessible publicly.
