### ISSUE TITLE
Semgrep returns complement of pattern result instead of intended target for some Rust patterns

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#6076]
**Describe the bug**
Results for Rust rules are the complement of what the user expects.

**To Reproduce**
https://semgrep.dev/s/2egz

**Expected behavior**
Expected single finding on line 2 in this example. Received a match for everything *except* line 2.

**Screenshots**
![image](https://user-images.githubusercontent.com/98792107/189431319-beeba8d9-ff89-44a2-b82c-4c55e86f9072.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev, also reproduces with Semgrep CLI 0.111.1

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1874/semgrep-returns-complement-of-pattern-result-instead-of-intended. _Note_: this link is for r2c use only and is not accessible publicly.
