### ISSUE TITLE
Python constant propagation failure

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#6079]
**Describe the bug**
Semgrep fails to see a compile-time constant in python.

Example:

```
    # column typarray not available before PG 8.3
    typarray = conn.info.server_version >= 80300 and "typarray" or "NULL"
    # get the oid for the hstore
    # ok: sqlalchemy-execute-raw-query
    curs.execute("""\
SELECT t.oid, %s
FROM pg_type t JOIN pg_namespace ns
ON typnamespace = ns.oid
WHERE typname = 'hstore';
""" % typarray)
```

`typarray` is a constant string, but Semgrep still flags this with the `sqlalchemy-execute-raw-query` rule

**To Reproduce**
https://semgrep.dev/s/rwr6

**Expected behavior**
Semgrep should not match

**Screenshots**
Semgrep 0.112

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1877/python-constant-propagation-failure. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
Is this idiomatic Python?
```python
typarray = conn.info.server_version >= 80300 and "typarray" or "NULL"
```
I would have expected this (assuming I got the meaning correctly):
```python
typarray = "typarray" if conn.info.server_version >= 80300 else "NULL"
```
But we could support this anyways if you think it's common enough.

**Comment by ievans** [comment]
I think it's common enough, but definitely low priority.

**Comment by IagoAbal** [comment]
Minimized example: https://semgrep.dev/s/G3xp

**Comment by IagoAbal** [comment]
In principle the original example doesn't work because `$CONNECTION.execute( $SQL % (...), ...)` does match:
```python
    curs.execute("""\
SELECT t.oid, %s
FROM pg_type t JOIN pg_namespace ns
ON typnamespace = ns.oid
WHERE typname = 'hstore';
""" % typarray)
```
However that seems OK to me.
