### ISSUE TITLE
Allow bitwise operations in metavariable-comparison

### ISSUE THREAD

**Issue by bananabr** [semgrep/semgrep#6099]
**Is your feature request related to a problem? Please describe.**
It is common for C/C++ programs to use bit flags as function arguments.

**Describe the solution you'd like**
Allow bitwise AND and bitwise OR in metavariable-comparison. For example ```$ARG & 4 > 0```.

**Describe alternatives you've considered**
None.

**Use case**
Be able to identify function calls using specific options encoded in bit flags.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1887/allow-bitwise-operations-in-metavariable-comparison. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
sophia's steps
1 - get familiar with Semgrep (semgrep.dev/learn semgrep.dev/docs)
2 - get familiar with the playground
3 - get familiar with semgrep CLI
4 - get familiar with semgrep-core

5 - get familiar with metavariable-comparison
https://semgrep.dev/docs/writing-rules/data-flow/constant-propagation/#metavariable-comparison
6 - find the code that implements this feature: Eval_generic.ml
7 - fix it and test it

**Comment by SophiaSR** [comment]
This seems to work already, here is a link to playground with some test cases. 
https://semgrep.dev/playground/s/9Ype

**Comment by aryx** [comment]
Oh you're right, apparently @IagoAbal closed it in #7284

**Comment by aryx** [comment]
you can now close the issue @SophiaSR

**Comment by aryx** [comment]
easy win :)
