### ISSUE TITLE
Scala: support ellipsis in match body

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#6131]
Add support for `$X match { ... }`

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1898/scala-support-ellipsis-in-match-body. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
reference discussion: https://returntocorp.slack.com/archives/C01NXGX2EHZ/p1663607715926549
