### ISSUE TITLE
Make message and severity fields optional

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#614]
At the moment, the ocaml-core errors if it doesn't get a message or severity field when parsing YAML. No reason not to have defaults for these

**Comment by ievans** [comment]
per convo with @DrewDennison , we would also like to make the -languages tag optional if the user explicitly specifies `--lang` on the CLI the YAML file shouldn't require the `-languages tag`. The core doesn't need to be aware of that, but this would simplify usecases like semgrepe.live

**Comment by ievans** [comment]
I think we've largely solved this problem through the live editor experience @DrewDennison . Feel free to re-open
