### ISSUE TITLE
Bash function pattern parsing rejects some definitions

### ISSUE THREAD

**Issue by kopecs** [semgrep/semgrep#6154]
**Describe the bug**
Bash patterns do not allow a function definition of the form
```
$FUNC() {

}
```
and instead only allow those of the form
```
function $FUNC() {

}
```

**To Reproduce**
See https://semgrep.dev/s/g1Q0 and https://semgrep.dev/s/39EK

**Expected behavior**
Both of the above should be valid patterns, matching the same AST nodes

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
Improve pattern support

I think this might be as simple as changing the `word` here to `_extended_word`, but I haven't had a chance to test: https://github.com/returntocorp/semgrep-bash/blob/8dda10c1abf5b6133d68ab9ad5559f1d3938f624/fyi/semgrep-grammars/src/semgrep-bash/grammar.js#L96

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1901/bash-function-pattern-parsing-rejects-some-definitions. _Note_: this link is for r2c use only and is not accessible publicly.
