### ISSUE TITLE
Symbolic propagation does not propagate `new`

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#6161]
Reporting on behalf of @backcover7.

We expect this https://semgrep.dev/s/vrBA to work but it doesn't.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1911/symbolic-propagation-does-not-propagate-new. _Note_: this link is for r2c use only and is not accessible publicly.
