### ISSUE TITLE
Taint mode does not interpret function parameters with --deep

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#6166]
**Describe the bug**

When another method passes tainted input to a sink, I expect `semgrep --deep` to detect that, but it doesn't.

```
package pack1;

public class C {
    int c() {
        this.callSink(user_input);
    }

    void callSink(String ui) {
        sink(ui);
    }
}
```

I am using the [deep.yaml](https://github.com/returntocorp/deep-semgrep-tests/blob/main/tainting/java/intrafile/deep.yaml) rule file.

```
$ semgrep -c tainting/java/intrafile/deep.yaml tainting/java/intrafile/ --deep
Scanning 2 files.
!!!This is a proprietary extension of semgrep.!!!
!!!You must be logged in to access this extension!!!
Using DeepSemgrep installed in /usr/local/Cellar/semgrep/0.114.0/libexec/lib/python3.10/site-packages/semgrep/bin/deep-semgrep
DeepSemgrep Version Info: (9bb0e9c)
    0%|                                                                                                                                                                                         |0/2 tasks

Findings:

  tainting/java/intrafile/together.java
     tainting.java.intrafile.test-rule
        Test

         18┆ sink(user_input);
          ⋮┆----------------------------------------
         21┆ sink(A.a());
          ⋮┆----------------------------------------
         24┆ sink(B.b());

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 1 rule on 2 files: 3 findings.
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1914/taint-mode-does-not-interpret-function-parameters-with-deep. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by emjin** [comment]
This should be fixed now! The problem was that `this` wasn't resolved, which interfered with our function lookup. If you `semgrep install-deep-semgrep` again it should work.

Please file more issues as you encounter them in DeepSemgrep! We'd also love to hear your thoughts on what you're looking for with DeepSemgrep. Feel free to dm me (Emma)
