### ISSUE TITLE
Make semgrep python 3.6 compliant

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#617]
semgrep should be runnable with python3.6

Add testing in a python3.6 environment and remove more advanced python features

**Comment by mschwager** [comment]
It'd be great to support all Python versions under active development. This currently includes Python 3.5 too: https://devguide.python.org/#status-of-python-branches. Python 3.5 is EOL in 4 months, so it makes sense if we don't want to prioritize that, but I think supporting all active Python versions is good practice for maximizing ease of use/installation for users. Having to install a newer version of Python on your system to use a tool is often enough friction to prevent someone from trying a tool. For now we could say the minimum version supported is 3.6, then support all active versions going forward (e.g. including CI testing for all active versions).

**Comment by brendongo** [comment]
Yeah with EOL so soon and us having a binary that people can run without any python installed as an alternative if they are not 3.6+ figured it was fine :D

**Comment by ievans** [comment]
we should run with https://github.com/returntocorp/semgrep-rules/blob/develop/python/compatibility/python37.yaml then :D
