### ISSUE TITLE
CLI hangs after scan

### ISSUE THREAD

**Issue by aylusltd** [semgrep/semgrep#6170]
**Describe the bug**
I run semgrep as part of a bash script, and for some reason it does not hand control back to the parent script.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
~/.local/bin/semgrep --config auto --json -o ../atd_results/$repo_name.findings.json ./ 
I'm targeting a clone of ["Small Test Repo"](https://github.com/rtyley/small-test-repo)

**Expected behavior**
I get the report on STDERR, I see the json file, but the program just hangs, never terminating.

**Screenshots**
```
 ./test-agent.sh
mkdir: cannot create directory ‘atd_results’: File exists
mkdir: cannot create directory ‘temp_repo’: File exists
Initialized empty Git repository in /home/jason/atd/temp_repo/.git/
url: git@github.com:rtyley/small-test-repo.git
Fetching origin
Switched to branch 'master'
Gathering Code Metrics
Static Code Analysis
Semgrep rule registry URL is https://semgrep.dev/registry.
Scanning 2 files with 52 <multilang> rules.
  100%|███████████████████████████████████████████████████████████████████████████████████████████████████████|2/2 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

(need more rules? `semgrep login` for additional free Semgrep Registry rules)

Ran 1036 rules on 1 file: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help

^C
```
**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
brew installed semgrep on Ubuntu 22.04 in WSL2.0 Windows 11.

**Use case**
I'm trying to get semgrep reports alongside pymetrics into our dashboard.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1917/cli-hangs-after-scan. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aylusltd** [comment]
Hey, my bad. it was the next line in my script. `rm` was failing, not semgrep. I wasn't expecting a write protected file in the results folder. Sorry to have bothered you guys.
