### ISSUE TITLE
Semgrep CLI display findings ruleset origin

### ISSUE THREAD

**Issue by ysebyy** [semgrep/semgrep#6178]
**Is your feature request related to a problem? Please describe.**
When running rules, especially "auto", it would be great to see when a there is a finding, which ruleset it belongs to. Doing comparisons or editing on certain rulesets would be easier to track down in our case, as auto runs way more rules than standard "ruby" for example.

**Describe the solution you'd like**
Just an additional section on the finding itself perhaps, of which rule was ran to produce this result. 
I think adding --verbose flag here, to not pollute the standard output, or an additional flag like --origin (just a suggestion, not a real solution)

**Describe alternatives you've considered**
Haven't really tried alternatives, didn't see any similar options.

**Use case**
Editing more rules to our choice and also specify more strict rules instead of auto that produce the most results for us. Also, rerunning certain rulesets on codebases.

**Additional context**
None!

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1918/semgrep-cli-display-findings-ruleset-origin. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ysebyy** [comment]
Awesome! Thanks!
