### ISSUE TITLE
Publish on Pypi

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#618]
Make semgrep pip installable. The installation will need to download and install the appropriate semgrep-core binary.

**Comment by brendongo** [comment]
Should be done with https://github.com/returntocorp/semgrep/pull/752 but will wait til next release to verify works.

**Comment by mschwager** [comment]
Does this include automatically publishing new releases to PyPI, or just manual? We could wire up auto publishing similar to Bento.

**Comment by rcoh** [comment]
@mschwager this does _not_ include automatic publishing
