### ISSUE TITLE
respect DO_NOT_TRACK

### ISSUE THREAD

**Issue by unhammer** [semgrep/semgrep#6182]
**Is your feature request related to a problem? Please describe.**

semgrep --help suggests running a command which immediately uploads information about my stuff, without respecting my `export DO_NOT_TRACK=1`.

**Describe the solution you'd like**

DO_NOT_TRACK==1 should be treated as if SEMGREP_SEND_METRICS=off
cf. https://consoledonottrack.com/

**Describe alternatives you've considered**

- uninstalling semgrep in despair 
- giving up on computing

**Use case**

- half a second of peace of mind

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1925/respect-do-not-track. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
This https://consoledonottrack.com/ does not seem widely adopted, but sure, why not.
