### ISSUE TITLE
[PHP] Not able to match a chained method call

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#6183]
**Describe the bug**

There is a parsing error when matching a chained method call, without specifying the whole chain, e.g.

trying to match

```php
DB::table('users')->foo()->bar()->pluck($col); 
```

with:

```
DB->...->pluck(...) 
```
throws an error

 (I need to catch DB specifically and that ->pluck(...) is also called somewhere in the chain)

https://semgrep.dev/s/o3wn

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1926/[php]-not-able-to-match-a-chained-method-call. _Note_: this link is for r2c use only and is not accessible publicly.
