### ISSUE TITLE
`this` keyword in Javascript doesn't behave correctly with taint

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#6191]
**Describe the bug**
The `this` keyword in Javascript does not appear to propagate taint correctly - when attempting to taint global properties like `this.window` the engine ignores them.

**To Reproduce**
minimal example:
https://semgrep.dev/playground/s/JvRP

**Expected behavior**
`this` and subproperties should be taintable by the data flow engine.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Taint rule-writing for global properties in JS using `this` keyword.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1929/this-keyword-in-javascript-doesnt-behave-correctly-with-taint. _Note_: this link is for r2c use only and is not accessible publicly.
