### ISSUE TITLE
Taint data flow for C does not correctly propagate into if(...) statements

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#6195]
**Describe the bug**
Taint appears to not correctly propagate into `if(...)` statements. Rewriting an existing rule in taint mode, I discovered a test case that *should* work with taint mode but doesn't (see reproduction link).

**To Reproduce**
https://semgrep.dev/s/OdLk

**Expected behavior**
Tests on repro link should pass.

**Screenshots**

N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**

Upgrading old rules from search mode to taint mode (more accurate)

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1933/taint-data-flow-for-c-does-not-correctly-propagate-into-if-statements. _Note_: this link is for r2c use only and is not accessible publicly.
