### ISSUE TITLE
Semgrep does not support TypeScript  `?` in pattern syntax

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#6201]
**Describe the bug**
In typescript you can write things like this:

`req.user?.accountId` 

Patterns do not accept that as valid and fall over with a parsing error, customers have had pain writing some typescript rules because of this.

**Expected behavior**
support ? as pattern syntax  see the link here https://semgrep.dev/s/1XOk

**Priority**
How important is this to you?
- [x] P2: annoying but not blocking me

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1943/semgrep-does-not-support-typescript-in-pattern-syntax. _Note_: this link is for r2c use only and is not accessible publicly.
