### ISSUE TITLE
Autofix mangles TypeScript expression containing parentheses

### ISSUE THREAD

**Issue by dkasak** [semgrep/semgrep#6233]
**Describe the bug**
I found a case where the autofix functionality incorrectly transforms a TypeScript expression containing parentheses by eating an opening parenthesis.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/s/Aq24

**Expected behavior**

The transformed expression should be

```typescript
function test(obj, first, second, val) {
  obj[first][second] = val
}

test(m, t, (e as SomeType).some_key, e as SomeType);
```

But instead it is

```typescript
function test(obj, first, second, val) {
  obj[first][second] = val
}

test(m, t, e as SomeType).some_key, e as SomeType);
        //^ Note the missing opening parenthesis.
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1955/autofix-mangles-typescript-expression-containing-parentheses. _Note_: this link is for r2c use only and is not accessible publicly.
