### ISSUE TITLE
Permission denied when using semgrep docker image in pre-commit

### ISSUE THREAD

**Issue by aryx** [semgrep/semgrep#6243]
```
[pad@thinkstation semgrep (precommit_jsonnet)]$ pre-commit run --verbose --hook-stage manual semgrep-docker-develop --all
Semgrep Develop Python...................................................Failed
- hook id: semgrep-docker-develop
- duration: 10.98s
- exit code: 1

======= DEPRECATION WARNING =======
The returntocorp/semgrep Docker image's custom entrypoint will be removed by June 2022.
Please update your command to explicitly call semgrep.
Change from:  docker run -v $(pwd):/src returntocorp/semgrep --config p/python --error cli/src/semgrep/formatter/base.py cli/src/semgrep/core_output.py cli/src/semgrep/verbose_logging.py cli/src/semgrep/target_manager.py cli/src/semgrep/bytesize.py perf/corpus.py
Change to:    docker run -v $(pwd):/src returntocorp/semgrep semgrep --config p/python --error cli/src/semgrep/formatter/base.py cli/src/semgrep/core_output.py cli/src/semgrep/verbose_logging.py cli/src/semgrep/target_manager.py cli/src/semgrep/bytesize.py perf/corpus.py
Traceback (most recent call last):
  File "/usr/local/bin/semgrep", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/semgrep/__main__.py", line 8, in main
    cli()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1654, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/semgrep/cli.py", line 58, in cli
    state = get_state()
  File "/usr/local/lib/python3.10/site-packages/semgrep/state.py", line 40, in get_state
    return ctx.ensure_object(SemgrepState)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 638, in ensure_object
    self.obj = rv = object_type()
  File "<attrs generated init semgrep.state.SemgrepState>", line 26, in __init__
  File "<attrs generated init semgrep.terminal.Terminal>", line 5, in __init__
  File "/usr/local/lib/python3.10/site-packages/semgrep/terminal.py", line 24, in __attrs_post_init__
    self.configure()
  File "/usr/local/lib/python3.10/site-packages/semgrep/terminal.py", line 62, in configure
    env.user_log_file.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.semgrep'

```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1958/permission-defined-when-using-semgrep-docker-image-in-pre-commit. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
@brendongo I need to get a fix for this to be able to dogfood using semgrep-jsonnet in pre-commit.
Right now none of our docker images seem to work when used inside pre-commit. We can use the python-based
semgrep, but the docker image seem to fail. What is weird is that it seems to work in CI in GHA (that's where those
manual hook stage are run).

**Comment by aryx** [comment]
I've tried to add --verbose to pre-commit for better logging, but it does not log anything apparently. I don't even know which command is run and how the docker container is called.

**Comment by aryx** [comment]
Looking at the code in env.py and terminal.py it seems like Path.home() must return '/' or None so then the mkdir fails.
Could we do a try around this mkdir and if it fails just set user_log_file to stderr?

**Comment by aryx** [comment]
or is there a way to disable logging so that we don't even try to do this mkdir .semgrep?

**Comment by brendongo** [comment]
Without any code you can override the home directory: with XDG_CONFIG_HOME or you can override the logfile path with  SEMGREP_LOG_FILE envvar

**Comment by brendongo** [comment]
Hmm yeah this is weird that outside pre-commit this seems to work fine. The docker command is being invoked here: https://github.com/returntocorp/semgrep/blob/develop/.pre-commit-hooks.yaml#L23 

Maybe we should just add a MKDIR /.semgrep to the dockerfile?

**Comment by aryx** [comment]
I also thought about the env var, but I don't know how to do that for a docker_image entry in pre-commit.

**Comment by aryx** [comment]
Weird that Path.home() returns /. It should return /root. And weird anyway it can't mkdir /semgrep since the user is root.

**Comment by brendongo** [comment]
Yeah. Maybe pre-commit runs as a different user

**Comment by aryx** [comment]
Ok after instrumenting pre-commit Python code, I got:
```
semgrep jsonnet..........................................................('docker', 'run', '--rm', '-u', '1000:1000', '-v', '/home/pad/github/semgrep:/src:rw,Z', '--workdir', '/src', 'returntocorp/semgrep:develop', 'semgrep', '--config', 'semgrep.jsonnet', '--debug', '--verbose')
```
so yes, it's using a different user.

**Comment by aryx** [comment]
in docker.py in pre-commit source code:
```
def get_docker_user() -> tuple[str, ...]:  # pragma: win32 no cover
    try:
        return ('-u', f'{os.getuid()}:{os.getgid()}')
    except AttributeError:
        return ()


def docker_cmd() -> tuple[str, ...]:  # pragma: win32 no cover
    return (
        'docker', 'run',
        '--rm',
        *get_docker_user(),
        # https://docs.docker.com/engine/reference/commandline/run/#mount-volumes-from-container-volumes-from
        # The `Z` option tells Docker to label the content with a private
        # unshared label. Only the current container can use a private volume.
        '-v', f'{_get_docker_path(os.getcwd())}:/src:rw,Z',
        '--workdir', '/src',
    )
```
which is why it's working in CI, because it's ran from root. But in my case I'm running pre-commit from my arch linux account with user id 1000:1000 and so then it fails when running the semgrep container.
Argh.

**Comment by aryx** [comment]
@brendongo maybe we could just fallback to creating the .semgrep in /tmp if there's an exception raised on the mkdir .semgrep?
Is there other place where we would get a permission denied?

**Comment by brendongo** [comment]
That's so weird. why is pre-commit assuming that the user id in the docker container is the same user id as the running os.

**Comment by aryx** [comment]
yep ...

**Comment by aryx** [comment]
https://github.com/pre-commit/pre-commit/issues/1243

**Comment by brendongo** [comment]
Looks like others have run into similar issue: https://github.com/pre-commit/pre-commit/issues/1243

**Comment by brendongo** [comment]
Oh you found it too :D

**Comment by brendongo** [comment]
Yeah. We can probably have some flag to set the location of the log file? Seems better than falling back silently to a different location

**Comment by brendongo** [comment]
There has to be a way to use the existing envvar. I'll take a quick look

**Comment by aryx** [comment]
does not look like pre-commit allows to set those vars for docker.
the --logfile does not look too bad. I can set it to --logfile /tmp/semgrep.log

**Comment by aryx** [comment]
ah perfect you did it :)
