### ISSUE TITLE
Semgrep tries to parse .elm files even though it doesn't support Elm

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#6247]
Split out from https://github.com/returntocorp/semgrep/issues/6199

> Having said that, we have a small portion of our codebase in Elm. When we run checks (e.g. semgrep scan --config auto ...) it, as expected, fails to parse the elm files with an error like: [ERROR] Fatal error at line myfile.elm:1: (Failure "not a program").

> The problem is that the exit code from semgrep changes depending on whether there is a subset of scanned files fail to parse but there are no findings (exit code 3) or all files fail to parse (exit code 2) and there are no findings. Some of our tooling rely on the exit code to determine what to do next, and these different behaviours impact our workflow. Even without support for Elm, we'd like to run semgrep to check files for things like secrets, but the error when parsing the files is preventing that.

My understanding is the expected behavior is that if we don't support elm, we don't try to parse elm file.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1961/semgrep-tries-to-parse-elm-files-even-though-it-doesnt-support-elm. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by aryx** [comment]
seems related to https://github.com/returntocorp/semgrep/issues/6167

**Comment by aryx** [comment]
This should be fixed by #6335
