### ISSUE TITLE
Add new Operator pattern-missing or pattern-not-found 

### ISSUE THREAD

**Issue by 0xdbe** [semgrep/semgrep#6253]
**Is your feature request related to a problem? Please describe.**

In some cases, default parameters are unsafe and doesn't need any configuration files or classes.

For example, Spring uses logback (as logging framework) and default configuration is loaded without any configuration files or classes.
This default configuration is unsafe  and vulnerable to log injection.
To be safe, a configuration file `logback.xml` is needed with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
          <layout class="ch.qos.logback.contrib.json.classic.JsonLayout">
            <jsonFormatter class="ch.qos.logback.contrib.jackson.JacksonJsonFormatter"/>
            <appendLineSeparator>true</appendLineSeparator>
          </layout>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="console"/>
    </root>

</configuration>
```

Existing operator (patterns, pattern-inside) can be used to find mistake in the configuration, if a configuration block exist.
Semgrep is not able to detect a mistake it `logback.xml` doesn't exist.

Semgrep searches unsafe pattern in a file. 
But in some case, unsafe configuration is defined automatically by framework (such as Spring) and can't be detected by Semgrep.

**Describe the solution you'd like**

new Operator called `pattern-missing` or `pattern-not-found` will be able to raise alert if a pattern is not found at the end of the source code analyse.

**Describe alternatives you've considered**

For configuration file (Yaml, XML, ...), I used conftest but it's quite boring to write rules in  Rego and run 2 tools (Semgrep then Conftest), merge result, ... And Conftest can't parse source code, only configuration files.

**Use case**

Semgrep will be able to find missing code in an application.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1964/add-new-operator-pattern-missing-or-pattern-not-found. _Note_: this link is for r2c use only and is not accessible publicly.
