### ISSUE TITLE
Port semgrep test script to pytest

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#626]
There's a shell script called `run-lint-tests.sh` currently which runs tests for:

- Checking if JSON output for certain scenarios is correct
- Checking if well-written YAML rulesets are parsed successfully
- Checking if badly-written YAML rulesets are rejected gracefully
- Checking if the semgrep-rules repo's rules run successfully

The shell script is super useful, but very hard to work with. Lots of bits are copy-pasted, and test failure output doesn't explain what's wrong very well. I'd much rather write pytest functions that use subprocess calls, to be able to use fixtures, parametrization, and pytest's error reporting UI.

The goal here is to have `make test` call only `pytest`.

**Comment by mschwager** [comment]
Yes plz, the testing system is really difficult to decipher
