### ISSUE TITLE
semgrep rule fails to catch some patterns

### ISSUE THREAD

**Issue by Sirneij** [semgrep/semgrep#6270]
I have a Python (Django) application that needs to be checked for some anti-pattern code writing. I don't want any variable to be included in log messages for some reason. I currently have this rule:

```yml
- id: python.no-variables-in-log-messages
    message:
      Do not include variables in log messages. All variables should be moved to
      logger.$METHOD(..., details={...})
    languages: [python]
    severity: WARNING
    patterns:
      - pattern-either:
          - pattern: logger.$METHOD(..., f'...', ...)
          - pattern: logger.$METHOD(..., message=f'...', ...)
          - pattern: logger.$METHOD(..., msg=f'...', ...)
          - pattern: logger.$METHOD(..., '...'.format(...), ...)
          - pattern: logger.$METHOD(..., message='...'.format(...), ...)
          - pattern: logger.$METHOD(..., msg='...'.format(...), ...)
          - pattern: |
             logger.$METHOD(
                f''
                f''
              )
          - pattern: |
              logger.$METHOD(
                message=(
                  f''
                  f''
                )
              )
          - pattern: |
              logger.$METHOD(
                msg=(
                  f''
                  f''
                )
              )

```
However, running this rule doesn't catch something like:
```python
logger.warning(
                    message=(
                        f'I am {late}'
                        f'due to {reason}'
                    )
                )
```
or:
```python
logger.warning(
            f'I am {late}'
            f'due to {reason}'
)
```
Is there anything I am missing? My `semgrep` version is `0.90.0`.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1981/semgrep-rule-fails-to-catch-some-patterns. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by ievans** [comment]
I think this is expected; is there any reason why your last couple patterns aren't using the elipsis inside the f string? See https://semgrep.dev/s/NvBy, seems to work.

```
- pattern: |
            logger.$METHOD(
              f'...'
              f'...'
            )
        - pattern: |
            logger.$METHOD(
              message=(
                f'...'
                f'...'
              )
            )
        - pattern: |
            logger.$METHOD(
              msg=(
                f'...'
                f'...'
              )
            )
```

Will close this out but feel free to re-open!

**Comment by Sirneij** [comment]
@ievans Thank you for that. I currently still have a problem. I have some logs in my codebase that span multiple lines, such as:
```python
...
logger.error(
        f'...'
        f'...'
        f'...'
        f'...'
        f'...'
        f'...'
)
```
And some only have two `f'...'`s while others 3 `f'...'`, and so on. Is there a scalable way to capture all of these without duplicating rules?

**Comment by IagoAbal** [comment]
@Sirneij what about this https://semgrep.dev/s/L5qo ?

If it doesn't work, please share a Playground link with a bunch of examples that you want to match (annotated with `#ruleid:`), and also with a bunch of examples that you do _not_ want to match.

**Comment by Sirneij** [comment]
@IagoAbal Thank you for this. It caught them effectively. Thank you.
