### ISSUE TITLE
metavariable-pattern does not match as expected when the metavariable is explicitly described as a string in Python

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#6299]
**Describe the bug**
In this example, https://semgrep.dev/s/PBkY, I am trying to match string literals according to a specific regular expression. If I express the `pattern` clause explicitly as `"$URL"` to capture string literals, the`metavariable-pattern` clauses do not match.

If I express the pattern as `$URL` without quotes, the `metavariable-pattern` clause works as expected. See https://semgrep.dev/s/JPdw

**To Reproduce**
see description

**Expected behavior**
I expect metavariable-pattern to work in both cases

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1992/metavariable-pattern-does-not-match-as-expected-when-the-metavariable. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
`metavariable-pattern` without `language` key needs the metavariable to bind to a Python expression or program. With `"$URL"`, `$URL` binds to raw text representing an URL and that is not valid Python. For it to be valid, it should be possible to dump the content of `$URL` into a file, and parse it as Python. If that's not possible, then you are not supposed to use `metavariable-pattern` on that metavariable (without using the `language` key). Ideally this could be detected by the metachecker. We could make `metavariable-pattern` to work on more cases than it currently does, but in this case in particular I think you just need to specify another `language`.

Your example with `"$URL"` works if you add `language: regex`, or `language: generic`, to `metavariable-pattern`.
