### ISSUE TITLE
[PHP] Tainted `$this` not matched in some cases

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#6308]
**Describe the bug**

example https://semgrep.dev/s/ggpJ

While trying to catch tainted `$this->input` it is not highlighted in cases like:

```php
    sink($this->input->get());
    sink($this->input->param2);
```

(but works fine for `$foobar->input`)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1994/[php]-tainted-dollarthis-not-matched-in-some-cases. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by inkz** [comment]
fixed by: https://github.com/returntocorp/semgrep/pull/6279
