### ISSUE TITLE
[PHP] Literal Metavariables

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#6311]
**Is your feature request related to a problem? Please describe.**
Would be very useful to have literal metavariables for PHP like:
https://semgrep.dev/s/GoRp

```php
$my_var = "hello world";
```

```yaml
  - pattern: $X = "$VAL";
```

and for template strings as well

```php
$my_var = "hello {$x} world";
```

```yaml
  - pattern: $X = "$MSG{$VAL}...";
```

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1998/[php]-literal-metavariables. _Note_: this link is for r2c use only and is not accessible publicly.
