### ISSUE TITLE
[Python] Scalable way to catch all cases

### ISSUE THREAD

**Issue by Sirneij** [semgrep/semgrep#6314]
Refer to #6270 

I currently still have a problem. I have some logs in my codebase that span multiple lines, such as:
```python
...
logger.error(
    f'...'
    f'...'
    f'...'
    f'...'
    f'...'
    f'...'
)
```
And some only have two `f'...'`s on separate lines while others 3 `f'...'`s, and so on. 

I am currently duplicating patterns to catch such logs. For example:

```yaml
...
patterns:
  - pattern-either:
     - pattern: |
        logger.$METHOD(
          f'...'
          f'...'
          f'...'
          f'...'
          f'...'
        )
```
Catches those with 5 `f'...'`s on multiple lines. I have to write another pattern for those with 4, 3 and so on.

Is there a scalable way to capture all of these without duplicating patterns?

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-1999/[python]-scalable-way-to-catch-all-cases. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by Sirneij** [comment]
The solution to this can be found [here](https://github.com/returntocorp/semgrep/issues/6270#issuecomment-1286855026).
