### ISSUE TITLE
Checking version of semgrep takes too long (0.2s ± 0.5)

### ISSUE THREAD

**Issue by amanagr** [semgrep/semgrep#633]
**Describe the bug**
Checking version of semgrep  takes more time than expected. It takes about 20% of our time on `null provision` (A script we run to check if all the packages, etc are up-to-date)
```bash
❯ time semgrep --version
0.5.0-dev.2
semgrep --version  (0.2s ± 0.5)s user 0.01s system 99% cpu 0.134 total
```

**Expected behavior**
It should happen instantly. (Under 0.05s or something lower).

**Comment by ievans** [comment]
Thanks @amanagr, we were just talking about this at our standup this morning actually. @underyx is going to investigate a ship a fix!

**Comment by ievans** [comment]
Hi @amanagr - we merged https://github.com/returntocorp/semgrep/pull/640 which took the runtime of semgrep --version runtime to 60ms. Feel free to re-open the ticket if that doesn't work for you! 

(@underyx I'm assuming this will get cut in the release on Tuesday)

**Comment by amanagr** [comment]
Thanks!
