### ISSUE TITLE
Enable full OCaml backtraces for all exceptions

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#634]
As mentioned in https://github.com/returntocorp/semgrep/pull/610#issuecomment-622107108, it would be very helpful to have full backtraces any time an exception occurs. This will not only help us internally when things go wrong, but also when end users are running our code and hit an issue.

It seems exceptions are swallowed up in the following code:

```ocaml
let format_output_exception e : string = 
  (* if (ouptut_as_json) then *)
  let msg = match e with 
    ...
    | exn -> 
      J.Object [  "error", J.String "unknown exception"; "message", J.String (Common.exn_to_s exn); ]
  in 
    Json_io.string_of_json msg
```

Adding `OCAMLRUNPARAM=b` in various places didn't help me with backtraces on exception. I would suggest we enable backtraces everywhere all the time including release builds, then users can explicitly turn them off if there's a performance hit or something they'd like to avoid.

**Comment by dlukeomalley** [comment]
@ievans I see you self-assigned a while back. Any progress or modifications you'd make to this ticket? I'm going through and doing cleanup/pruning. If no longer relevant mind closing?

**Comment by ievans** [comment]
@dlukeomalley thanks for the flag. I unassigned. @rcoh might be the right person to do this, but TBH I'm not sure it's a big priority right now.

**Comment by ievans** [comment]
I haven’t heard anything about this, so assuming it is stale.
