### ISSUE TITLE
symbolic_propagation failed when including Cast type in Java

### ISSUE THREAD

**Issue by backcover7** [semgrep/semgrep#6344]
**Describe the bug**
When the statement contains cast type, the symbolic_propagation feature will fail in matching.

**To Reproduce**
https://semgrep.dev/s/0vAb

**Expected behavior**
The two "either" patterns should be matched because when the cast type is in the statement.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep playground

**Use case**
It is helpful to allow users to use the symbolic_propagation feature when any cast type in the statement.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-2025/symbolic-propagation-failed-when-including-cast-type-in-java. _Note_: this link is for r2c use only and is not accessible publicly.
