### ISSUE TITLE
Labels not being applied correctly to taint rule

### ISSUE THREAD

**Issue by brandonspark** [semgrep/semgrep#6355]
**Describe the bug**
We are producing a finding when we shouldn't be, because a label being used as a "requires" should be preventing the finding, but it is not.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/playground/s/JPRQ

**Expected behavior**
There should be no finding, because the `USERINPUT` label is not satisfied by the source.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
Correctness.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-2029/labels-not-being-applied-correctly-to-taint-rule. _Note_: this link is for r2c use only and is not accessible publicly.
