### ISSUE TITLE
Add Dataflow Traces to SARIF Output Formatter

### ISSUE THREAD

**Issue by jharper-sec** [semgrep/semgrep#6367]
**Is your feature request related to a problem? Please describe.**
Currently the SARIF output only includes information about the `rule_match` location. This is fine for Semgrep rules matching on a single line of code, but for rules with mode `taint`, the output should include the dataflow details. The text formatter output already includes this information when passing the `--dataflow-traces` flag. This dataflow information should be extended to the SARIF output to allow better integration with tools supporting the SARIF standard.

**Describe the solution you'd like**
Add `codeFlows` and associated `threadFlowLocation` information to SARIF output formatter:

* [SARIF Formatter](https://github.com/returntocorp/semgrep/blob/develop/cli/src/semgrep/formatter/sarif.py)

SARIF Spec Details
* [codeFlows](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317740)
* [threadFlowLocation](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317751)

The `threadFlowLocation` information would include information from taint `sources`, `propagators`, and `sinks`.

**Describe alternatives you've considered**
An alternative is to use the raw JSON output and externally parse and transform this output data into SARIF. Since SARIF output is already possible using the `--sarif` flag, it would be preferable to modify this to include the additional data produced with `taint` mode.

**Use case**
Better integration with external tools that support `codeFlows` data in SARIF. An example of this is the `Analysis Steps` functionality within the popular VSCode plugin [SARIF Viewer](https://marketplace.visualstudio.com/items?itemName=MS-SarifVSCode.sarif-viewer)

**Additional context**
Have already started some work on this, so glad to pick it up.

**Comment by IagoAbal** [comment]
> Have already started some work on this, so glad to pick it up.

Does that mean you can work on a PR yourself @jharper-sec ?

**Comment by jharper-sec** [comment]
@IagoAbal Yes, I can start work on a PR and let you know if I have questions as I work through it.

**Comment by IagoAbal** [comment]
Great! cc @nmote who exposed taint traces for users.

**Comment by jharper-sec** [comment]
Linking to PR: https://github.com/returntocorp/semgrep/pull/6377
