### ISSUE TITLE
Go - Symbolic Propagation Not Working With Function

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#6375]
**Describe the bug**
I'd expect Semgrep to produce a match on both line 12 and 14 with symbolic propagation turned on in this example - https://semgrep.dev/s/jeXY

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
What will fixing this bug enable for you?
Write more concise Go rules

**Comment by enncoded** [comment]
This issue is synced in Linear at https://linear.app/r2c/issue/PA-2054/go-symbolic-propagation-not-working-with-function. Note: this link is for r2c use only and is not accessible publicly.

**Comment by IagoAbal** [comment]
This should have been fixed by #6484.
