### ISSUE TITLE
Use ppx visitors instead of maintaining boilerplate code manually

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#6450]
Context: https://github.com/returntocorp/semgrep/issues/6440

This allows deriving the boilerplate for visiting ASTs from the AST type definitions. In particular, the generic AST. The operations that visitors allow include:
* map: copy most nodes, modify some of them
* iter, fold: iterate over a tree and accumulate some result

**Comment by nmote** [comment]
Done
