### ISSUE TITLE
Make generated AST mapper/iterator boilerplate available for copy-paste-edit

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#6452]
Context: https://github.com/returntocorp/semgrep/issues/6440

This task consists in modernizing [ocamltarzan](https://github.com/aryx/ocamltarzan) so that semgrep developers can easily extend the boilerplate code that maps an AST into something else, by copy-pasting generated code and then editing it by hand where necessary.

**Comment by aryx** [comment]
I'll close for now. There's still lots of Todos, but it's a first step.
