### ISSUE TITLE
Bug in semgrepignore parsing logic with colon (":") directive

### ISSUE THREAD

**Issue by khanhldt** [semgrep/semgrep#6456]
**Describe the bug**
Include directive in `.semgrepignore` apparently parses `.gitignore` using the same syntax parser with `.semgrepignore`, which assumes `:` is also a directive.

**To Reproduce**
1. Check out any repo.
2. Create a semgrepignore file that looks like this: https://gitlab.com/gitlab-org/security-products/analyzers/semgrep/-/blob/452f9e47b96b909ff588ff23c3827b543e3b0c2c/semgrepignore#L9 (with `:include .gitignore`)
3. Add a line in `.gitignore` file that contains only `:`
4. Now run semgrep: `semgrep --config auto  .`

It will fail with error "Unknown ignore directive in Semgrep ignore file at /src/REPO: ':'".

**Expected behavior**
Even though that injected line is an error, the `.gitignore` file is still technically parsable, and the error from Semgrep is quite misleading in 2 ways:
- No exact location of error.
- It made it sound more like an error in `.semgrepignore` because `.gitignore` doesn't support ignore directive.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ x ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Semgrep CLI

**Use case**
N/A

**Comment by brendongo** [comment]
Fixed by https://github.com/returntocorp/semgrep/pull/6460 this should be fixed in latest release!
