### ISSUE TITLE
Equivalences only seem to match the first equivalence if it could match multiple equivalences

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#648]
**Describe the bug**
It looks like equivalences only match the first equivalence, even if there are multiple equivalences defined that should take effect.

**To Reproduce**
Here's an example where it should match all three locations:
https://semgrep.live/rbP?version=develop

I also tried it in both directions:
https://semgrep.live/b0P?version=develop

And I tried reversing the expressions:
https://semgrep.live/NYL?version=develop

**Comment by dlukeomalley** [comment]
Hello! This feature was deprecated in 0.61.0, closing now stale tickets 🙏
