### ISSUE TITLE
Equivalences have trouble resolving in multiline patterns

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#651]
**Describe the bug**
It looks like equivalences have some trouble with multiline patterns.

**To Reproduce**
https://semgrep.live/k21?version=develop

**Expected behavior**
In the semgrep.live link above, I would expect it to match both patterns, especially given that https://semgrep.live/wb6?version=develop works like a charm.

**Comment by nbrahms** [comment]
Just noting that we do want to address this still

**Comment by dlukeomalley** [comment]
This feature has been deprecated. Cleaning up old tickets and going to close 🙏
