### ISSUE TITLE
Python f"..." matches "hello" "world"

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#654]
I would expect `f"..."` to match any f-string, but it also incorrectly matches concatenated normal strings like `"hello" "world"`: https://semgrep.live/n11.

**Comment by ievans** [comment]
Thanks @andersk, this is definitely a fix we'd like to make.

**Comment by aryx** [comment]
ok so we want "..." to match regular strings and fstrings, but f"..." to match only fstrings
