### ISSUE TITLE
Rust language beta support mega-issue

### ISSUE THREAD

**Issue by rc-mattschwager** [semgrep/semgrep#6545]
Hi all,

We currently have a moderate amount of Rust code within our organization. However, there are not many Rust Semgrep rules available yet, which makes it difficult to adopt Semgrep on our Rust codebases. Rust is also growing very quickly, and becoming a darling of the open source community. With that, I'd like to purpose an initiative to move Rust from experimental -> beta support in Semgrep.

As you know, there are [three requirements](https://semgrep.dev/docs/supported-languages/) to make this happen:

- Parse rate
- Feature support
- Rule count

[`semgrep-rules`](https://github.com/returntocorp/semgrep-rules) does not currently have any Rust rules. I'd be happy to contribute 5-10 of Rust's first rules to `semgrep-rules` if r2c can handle the parse rate and feature support.

Rust is [currently sitting at 98.8% parse rate](https://dashboard.semgrep.dev/metric/semgrep.core.rust.parse.pct), very close to the 99% requirement for beta. I haven't investigated Rust's missing beta feature support, so that would have to be done as part of this task.

Of course, once this is done it could be accompanied by the usual language promotion blog post 👍 

Related issues:

- https://github.com/returntocorp/semgrep-rules/issues/1442

**Comment by rc-mattschwager** [comment]
Here are some relevant tasks I've created regarding Rust rule and language support:

- https://github.com/returntocorp/semgrep/issues/6593
- https://github.com/returntocorp/semgrep/issues/6594
- https://github.com/returntocorp/semgrep-rules/pull/2568

**Comment by aryx** [comment]
Hi Matt!
Haha, the mega issues are back! :)

**Comment by aryx** [comment]
I think the parsing rate can be improved easily by removing rust from the projects.txt file. It contains lots of test code
exercising edge cases in the grammar and so is not really representative of typical rust code.

**Comment by aryx** [comment]
I've fixed a few things. I think we should be close to beta.

**Comment by aryx** [comment]
@rc-mattschwager I think we're good for Beta.
Would you like to write a blog post about it?

**Comment by rc-mattschwager** [comment]
> @rc-mattschwager I think we're good for Beta. Would you like to write a blog post about it?

Woohoo! Sure that'd be great

**Comment by aryx** [comment]
Let me contact marketing to see what we could do to assist you.
