### ISSUE TITLE
C#: loops seemingly cannot be matched through patterns

### ISSUE THREAD

**Issue by gheijer** [semgrep/semgrep#6568]
**Describe the bug**
It seems impossible to find `while`, `for` and `foreach` loops in C# through patterns. Strangely enough, the exact same code in Java can be found. Also substituting `while` with `if` in both the code and the pattern (so the code and pattern are the same otherwise) does result in a match.

**To Reproduce**
[Link to https://semgrep.dev `while` in C#](https://semgrep.dev/s/O5lb) <= cannot be found
[Link to https://semgrepdev `while` in Java](https://semgrep.dev/s/yv0Z) <= can be found
[Link to https://semgrep.dev `if` in C#](https://semgrep.dev/s/pvPd) <= can be found

**Expected behavior**
I would expect a match on the `while` loop with the current C# code and pattern. Also in general, I would expect `while` and other types of loops (`for`, `foreach`) to be detectable in C#, like they are in Java.

**Screenshots**
![image](https://user-images.githubusercontent.com/31206336/203101437-eb86c79b-7d44-4545-89c7-aa210e71e68a.png)

![image](https://user-images.githubusercontent.com/31206336/203104937-cd0f85dd-426a-47c2-b771-5514245a9899.png)

![image](https://user-images.githubusercontent.com/31206336/203105747-c51f2c23-2903-4c2d-b552-a0532cef4818.png)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
-

**Use case**
What will fixing this bug enable for you?
For educational purposes, we provide automatically generated feedback on the code of students. Additionally we wish to automatically detect if the student has written the code as intended. Fixing this bug means we can do both these things when it comes to loops.

**Comment by IagoAbal** [comment]
We need immutable links here:

https://semgrep.dev/s/O5lb <= cannot be found
https://semgrep.dev/s/yv0Z <= can be found
https://semgrep.dev/s/pvPd <= can be found

**Comment by gheijer** [comment]
I've edited links in the original post. I've used `Permalink`; is this what you needed?

**Comment by IagoAbal** [comment]
Yes, we would need permalink here to make sure the content has not changed. You can still update the description and fix the links later if needed, but then we know the update is intentional. Also, sometimes people forget they used these links on GitHub and may just delete them.

**Comment by gheijer** [comment]
Thank your for the explanation; it is clear now.

Regarding the issue with loops: there seems to be a very similar issue with C# constructors that might be related to this one. Would it be best to create a separate bug report and have them refer to each other?

**Comment by IagoAbal** [comment]
You can share the example here if you want and we decide.

This issue may be related to the condition, `...` works but not a metavariable: https://semgrep.dev/s/AW9p

**Comment by gheijer** [comment]
Here are the examples. Since you've mentioned the `...`, I've added examples without parameters as well.

The C# semgreps for constructors all result in an error, whereas the ones for loops do not. In addition, using `...` instead of a metavariable (examples not included) still results in an error and not a match. So maybe the loop and constructor issues are not related after all.

https://semgrep.dev/s/qz4z <= C# constructor with no parameters; error
https://semgrep.dev/s/K2O7 <= C# constructor with 1 parameter; error
https://semgrep.dev/s/lqDy <= Java constructor with no parameters; match
https://semgrep.dev/s/YlOe <= Java constructor with 1 parameter; match

**Comment by IagoAbal** [comment]
In C# it seems that you need to enclose the pattern in a class for it to work: https://semgrep.dev/s/63Ao. You can open a separate issue for that.
