### ISSUE TITLE
print "foo", fails to parse

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#663]
**Describe the bug**
`print "\n",` to parse fails to parse even with `--lang python2`
**To Reproduce**
https://semgrep.live/BJv fails to parse even though it's valid python2 and the idiomatic way to print without a new line https://stackoverflow.com/a/11266091
**Expected behavior**
It should parse

Found when trying to parse https://github.com/sobolevn/python-code-disasters

**Comment by nbrahms** [comment]
Fixed in https://github.com/returntocorp/semgrep/pull/857

**Comment by brendongo** [comment]
https://semgrep.live/BJv?version=0.9.0 Released in 0.9.0
