### ISSUE TITLE
Support super(...) in Semgrep Pattern  Java

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#6638]
**Describe the bug**
Currently Semgrep patterns don't allow matching super(...) as a pattern

https://semgrep.dev/s/9PWY

it works in JavaScript/TS
https://semgrep.dev/s/yRDx

**To Reproduce**
https://semgrep.dev/s/9PWY

**Expected behavior**
Super should be a valid pattern value

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
Better java rule writing

**Comment by carlosvillasanchez** [comment]
Thank you for creating the issue in GitHub from the report in slack!
