### ISSUE TITLE
LINQ queries don't match because of opportunistic string matching

### ISSUE THREAD

**Issue by Sjord** [semgrep/semgrep#6666]
C# has LINQ queries, like this:

```
from m in somelist select m.foo;
```

This is parsed and rewritten to a method invocation, because the AST_Generic doesn't know about LINQ. It is rewritten as follows:

```
somelist.Select(m => m.foo)
```

Now, when a query like that is ran against source code, it seems that some optimization logic first checks whether the code even contains `Select`. It doesn't, so it doesn't attempt to match.

This can be confirmed by adding a comment containing `Select` in the source file. The pattern `from m in somelist select m.foo;` will [match the following](https://semgrep.dev/playground/s/sjord:linq.working):

```
from m in somelist select m.foo;
// Select
```

But not [without the comment](https://semgrep.dev/playground/s/sjord:linq.notworking):

```
from m in somelist select m.foo;
```

[Working](https://semgrep.dev/playground/s/sjord:linq.working), [Not working](https://semgrep.dev/playground/s/sjord:linq.notworking)

**Comment by aryx** [comment]
A link to semgrep.dev playground example would be nice.

**Comment by Sjord** [comment]
[Working](https://semgrep.dev/playground/s/sjord:linq.working), [Not working](https://semgrep.dev/playground/s/sjord:linq.notworking)

**Comment by aryx** [comment]
Why not generating a somelist.select(m => ...)? why Select which then leads to this issue?

**Comment by Sjord** [comment]
> Why not generating a somelist.select(m => ...)? why Select which then leads to this issue?

Because [Select](https://learn.microsoft.com/en-us/dotnet/api/system.linq.enumerable.select?view=net-7.0) is the name of the method that is actually being called. .NET does pretty much the same translation as semgrep here, converting LINQ queries in method calls.

The idea is that `from somelist select m.foo` and `somelist.Select(m => m.foo)` are identical, and semgrep should treat them that way.

But of course I was not aware that this would lead to string-matching issues.

**Comment by aryx** [comment]
Got it. Anyway I've found the right fix.
