### ISSUE TITLE
[Java] Regression: `$X.$Y` can no longer match `Foo.class`

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#6684]
This used to work but it no longer does: https://semgrep.dev/s/AWR2

(The original example is https://semgrep.dev/playground/s/obRd and comes from our taint-mode documentation, it was provided by Kurt.)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by IagoAbal** [comment]
cc @aryx, PR #6041 could have broken this example. It was working in 0.111.1 and broke starting 0.112.0 which is when #6041 was released.

**Comment by ihji** [comment]
Shouldn't this be `$X.class` instead of `$X.$Y`? `$X.$Y` is interpreted as a dot access and `Foo.class` is parsed as a class literal after the change introduced in #6041.

**Comment by IagoAbal** [comment]
@ihji I'm fine with that, just documented the regression. The `Foo.class` does have the same shape as `$X.$Y` and intuitively I would expect it to match, on the other hand it's a special "class literal". 🤷‍♂️ I'm not sure what benefit do we get by not interpreting it as a `DotAccess` for a `class` field, I would expect the test case in #6041 to work either way.

**Comment by IagoAbal** [comment]
Seems like the Pfff parser was already parsing `Foo.class` as a `ClassLiteral`. It may be more correct this way, although I would personally interpret it as a field-access which seems to give you more flexibility. Anyways, it's probably not worth spending time on it unless it's an external user who requests this.
