### ISSUE TITLE
Suggestion: Add bounties?

### ISSUE THREAD

**Issue by zcesur** [semgrep/semgrep#6697]
Hi! Sorry if this is an overreach, but with all the issues/requests in this repo, I thought you might find it helpful to introduce bounties.

With [algora.io](https://algora.io) you can reward your contributors using bounties. [You can see some examples in action here.](https://github.com/remotion-dev/remotion/issues?q=label%3A%22%F0%9F%92%8E+Bounty%22)

I want to be transparent: I've built Algora and I'm currently seeking early adopters. If this suggestion is not welcome, please accept my sincere apology and feel free to close or delete this issue!

**Comment by aryx** [comment]
I've sent the link to algora.io to r2c managers on our internal Slack (they are the one who can make a decision about this). I'll close for now but who knows, we might get in contact.
