### ISSUE TITLE
Check for update every N runs in non-blocking thread

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#673]
We've fixed a lot of bugs in the latest semgrep release, but since we're not in a package manager most users who have installed binaries may not be aware of that. We should have a feature that notifies a user that an upgraded version of the tool is available. 

Suggestion: Check for update every N runs in non-blocking thread

**Comment by dlukeomalley** [comment]
@nbrahms I recall we discussed this recently, but don't remember if we decided to explicitly deprioritize it. Do you think this fits in near term for UX?

**Comment by nbrahms** [comment]
Seems reasonable.

One thought: if we want to avoid network, can we just check the install time of the binary? Given that we're on a timed release cadence, we know the tool is out of date after 14 days.

**Comment by mschwager** [comment]
I'll get this done :+1:

**Comment by dlukeomalley** [comment]
Sounds good. @DrewDennison may have some ideas. Overall we want to make sure that:

* is not blocking (happens async in the background)
* doesn't appear when running with `--quiet` or machine formats like `--json`
* sends the absolute minimal set of data required to figure out if an upgrade is needed, perhaps just making a GET call and running logic locally

For now I think it's fine to link to a README section about upgrading. Stretch goal would be it actually tells you how to upgrade (but could require us to know if someone installed via brew, pip, binary, other).

Bento has some nice formatting around this that was taken from npm.

**Comment by mschwager** [comment]
> Sounds good. @DrewDennison may have some ideas. Overall we want to make sure that:
> 
>     * is not blocking (happens async in the background)

For simplicity's sake, can we do a blocking call with a very short timeout (1sec, 2sec) to start? Then we can iterate if users find this too much. I think the network error will be instant if, e.g. they're not connected to wifi, vs. if there's simply network congestion or slow speeds. This means users not connected to wifi will get much faster feedback vs. simply a slow connection (which I would expect most of our users to have a decent internet connection **if** they're connected).

>     * doesn't appear when running with `--quiet` or machine formats like `--json`

:+1: 

>     * sends the absolute minimal set of data required to figure out if an upgrade is needed, perhaps just making a GET call and running logic locally

As the resident privacy connoisseur, this sounds good to me. I don't think we need to send any data at all, we can pull the latest version from the endpoint and make the comparison locally.

@DrewDennison does this sound reasonable?

**Comment by DrewDennison** [comment]
SGTM. Did you see the api for checking the version?

**Comment by mschwager** [comment]
> SGTM. Did you see the api for checking the version?

Yup! I'll use it :+1:
