### ISSUE TITLE
Go: Typed metavariables don't work with := &MY_STRUCT{}

### ISSUE THREAD

**Issue by obwan02** [semgrep/semgrep#6733]
**Describe the bug**
When using a short variable declaration, semgrep doesn't detect the type of a metavariable if the right hand side of the assignment is a reference to a struct (or new)

Example:
```go
client := &http.Client{}
// OR
client2 := new(http.Client)
```

**To Reproduce**
[semgrep playground link](https://semgrep.dev/s/obwan02:golang-taint-sources)

**Expected behavior**
I would expect similar behaviour to javascript/typescript's var keyword , C++'s auto keyword, Java's var etc. where assignment propagates the type of the RHS to the LHS.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Running in semgrep.dev

**Use case**
We need this to make accurate rules for static analysis

**Comment by nmote** [comment]
Permalink to playground: https://semgrep.dev/s/RN8v
