### ISSUE TITLE
Apply equivalences only to current rule

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#674]
**Is your feature request related to a problem? Please describe.**
Currently, equivalences are specified inside a rule yaml file. Intuitively, this implies that the equivalences will only operate on that rule.

However, in reality, equivalences are flattened and applied across all rules for a single invocation of semgrep. This is because semgrep also flattens all patterns for a language, making it difficult to apply equivalences to relevant patterns.

**Describe the solution you'd like**
Based on discussion, the preferred solution is:
- Have semgrep-core figure out which equivalences to apply based on the rule id.

**Describe alternatives you've considered**
An alternative solution is:
- Invoke semgrep once per rule file instead of flattening everything and invoking once.

**Additional context**
Applying equivalences across all rules is probably fine... until we start running a bunch of rules together and equivalences start causing unintended consequences.

**Comment by nbrahms** [comment]
@brendongo @minusworld Is this still an issue?

**Comment by minusworld** [comment]
> @brendongo @minusworld Is this still an issue?

I think not after refactoring to run once per rule.
