### ISSUE TITLE
Custom ruleset argument to execute existing public rulesets.

### ISSUE THREAD

**Issue by c-goosen** [semgrep/semgrep#6753]
**Is your feature request related to a problem? Please describe.**
I would like to write a yaml file with references to other existing r2c public ruleset to include to my ruleset. This would allow one --config per language, instead of needing mutliple --config for different languages supported internally.

**Describe the solution you'd like**
Just being able to pass a single yaml file or directory with a ruleset in it that executes other rulesets.

**Describe alternatives you've considered**
Multiple commandline arguments with --config. This would be a pain to maintain accross mutliple CI setups.

**Use case**
A single repo with custom rulesets other developers can reference, that also trigger the public and very good rulsets out there already.

**Additional context**
Something like this

`
rules:
  - id: existing-public-rulesets
    public-rulesets:
     - p/python
     - p/owasp-top-10
     - p/r2c-security-audit
     - p/cwe-top-25
    languages:
      - python
    ....
`

**Comment by aryx** [comment]
We're planning to allow people to write rules using jsonnet. This might solve your problem.
See for example how we use jsonnet internally to specify rules to run: https://github.com/returntocorp/semgrep/blob/develop/semgrep.jsonnet

**Comment by c-goosen** [comment]
@aryx that sounds great.

Would there still be the possibility to see it in the yaml too? 

Or would a PR be accepted for it?

**Comment by c-goosen** [comment]
@aryx any approximate timelines on jsonnet?

**Comment by aryx** [comment]
jsonnet is already working, unofficially. We're using it in our CI for semgrep itself (see semgrep.jsonnet).
The plan is probably to announce it officially for semgrep 2.0, in march.
Regarding seeing it in yaml, I'm not a fan of yaml, and it would require to invent a new format just for that feature
(that's the nice thing about jsonnet, you can get many features for free just by adding support for jsonnet because jsonnet is programmable).

**Comment by c-goosen** [comment]
@aryx . Got it to work. Thank you for the suggestion, gonna close this for now. 

Will definitely need more docs. Want me to take a stab at documenting it somewhere? Things like install jsonnet dependency

**Comment by aryx** [comment]
it's not meant for public consumption yet, so we don't really want to document it for now.
