### ISSUE TITLE
Highlight tainted path

### ISSUE THREAD

**Issue by BitTheByte** [semgrep/semgrep#6754]
I'm relatively new to semgrep and this might be already implemented. 

Is it possible to show taint path using semgrep's taint mode

```
x = user_input()
... Unrelated
b = x
... Unrelated
eval(b)
```

I want the following path to be highlighted showing the complete path from source to sink

**Comment by nmote** [comment]
Yes, try the `--dataflow-traces` flag. It's currently experimental and may change, but it should provide the information you are looking for.
