### ISSUE TITLE
Loosen pin on python attrs to >=21.3

### ISSUE THREAD

**Issue by Redoubts** [semgrep/semgrep#6757]
Are you able to loosen the pin on attrs to support v22.*? I think you currently set it to `attrs~=21.3`, but for my project, it conflicts with our airflow dependency, which requires `attrs>=22.1.0`

Ideally `attrs>=21.3` would work here.

**Comment by nmote** [comment]
I haven't looked into this, but it would likely be fairly straightforward. However, we're in the middle of migrating the Python part of Semgrep to OCaml, so I'm not sure how relevant this will be. @aryx what do you think?

**Comment by aryx** [comment]
if it's easy to loosen, we should do it. I don't think it matters for our migration effort.

**Comment by nmote** [comment]
Sounds good. @Redoubts are you interested in putting up a pull request?

**Comment by Redoubts** [comment]
Alright, tossed something out there.
