### ISSUE TITLE
Traceback is printed for "only `['pattern-either']` or `['patterns']` expressions can have multiple subpatterns"

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#678]
When [this evaluation error occurs](https://github.com/returntocorp/semgrep/blob/e6ac0a63/semgrep/semgrep/evaluation.py#L244-L246) we print an `AssertionError` traceback. We should print a nicely formatted error message instead.

The immediate need for this is that we want to test the error message, but tracebacks are user-specific due to included absolute paths.

By the way, Python skips `assert` statements if a user runs with `PYTHONOPTIMIZE=1`, so we shouldn't ever user `assert`s anyway.

**Comment by dlukeomalley** [comment]
@underyx @rcoh Was this addressed by #680 or #773?

**Comment by rcoh** [comment]
Closed via #1033
