### ISSUE TITLE
pfff is still actively maintained?

### ISSUE THREAD

**Issue by D3vil0p3r** [semgrep/semgrep#6781]
Hello,
I'm looking for pfff by https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/src/pfff/README.md but it is not clear it is still maintained or deprecated.

I'm searching for source files and I landed on https://github.com/returntocorp/pfff/wiki#install for the installation that should refer to the "master" branch of https://github.com/returntocorp/pfff repository.

Despite it, the latest release time is 3 years ago and it still uses a deprecated dependency as json-wheel: https://github.com/returntocorp/pfff/issues/538

So, pfff is still maintained? If so, the latest source files should be retrieved from https://github.com/returntocorp/pfff master branch? When the deprecated dep will be replaced?

**Comment by aryx** [comment]
Pfff itself is deprecated. Its code is still used inside semgrep and a few other of my projects (e.g., codemap, codegraph), but
we tend to prefer to use tree-sitter grammars to parse languages than the original grammars I wrote inside pfff.
In the long term we hope to divide semgrep (and the pfff code now inside semgrep) in different packages that we could
publish on OPAM so one could for example reuse the javascript parser inside semgrep in their own code, without having to depend on the whole semgrep project.

What do you want to do with pfff?

**Comment by D3vil0p3r** [comment]
> Pfff itself is deprecated. Its code is still used inside semgrep and a few other of my projects (e.g., codemap, codegraph), but we tend to prefer to use tree-sitter grammars to parse languages than the original grammars I wrote inside pfff. In the long term we hope to divide semgrep (and the pfff code now inside semgrep) in different packages that we could publish on OPAM so one could for example reuse the javascript parser inside semgrep in their own code, without having to depend on the whole semgrep project.
> 
> What do you want to do with pfff?

An old version of pfff is in BlackArch repository https://github.com/BlackArch/blackarch/tree/master/packages/pfff and of course by building this PKGBUILD won't work. For this reason, we would like to understand if pfff could have a future or if we must remove it from BlackArch because of its deprecation.

So, according your statement, is it deprecated and there is no future for releasing it as the past, right?

**Comment by aryx** [comment]
yes there is no point in releasing pfff anymore. Regarding blackarch, I think adding a package for semgrep
would make far more sense anyway than adding a pfff package.
semgrep is partially designed to help pen testers.
