### ISSUE TITLE
Single-line patterns being parsed differently with and without a pipe

### ISSUE THREAD

**Issue by enncoded** [semgrep/semgrep#6872]
**Describe the bug**
Patterns with single-line string values, such as
```
pattern: |
  "asdf"
```

is parsed differently from
```
pattern: asdf
```

**To Reproduce**
https://semgrep.dev/s/EKvP Produces no match, while https://semgrep.dev/s/72Yk does
I added another link in the Linear issue with an SSC rule that demonstrates inconsistent behavior in the inverse way

**Expected behavior**
Both of them should match

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
Writing more concise rules and reducing confusion for future rules. SR is particularly interested in this for to make handling JS/Python imports easier, as libraries can be imported in a vast variety of ways in both languages. Currently, we have to have a separate pattern for each way, but using taint labels with just the library's name in a string as a source label alleviates that issue.

**Comment by enncoded** [comment]
I added more context in the Linear issue: https://linear.app/r2c/issue/PA-2407/bug-single-line-patterns-being-parsed-differently-with-and-without-a

**Comment by aryx** [comment]
this is because when you write pattern: asdf, we think this is the identifier asdf.
When you write pattern : | "asdf",
we know it's the string asdf.

Another case of yaml-is-great-at-first-but-has-so-many-edge-cases-it's-terrible

**Comment by enncoded** [comment]
I understand that, but I feel like it's incredibly confusing behavior when the more explicit expression of a string `pattern: |\n "async"` does not match the string whereas the pattern that looks like a symbol `pattern: async` matches a string. It would be incredibly confusing to someone who's new to writing Semgrep rules and makes it look like Semgrep just does not work. Like, the the first rule is _very_ obviously trying to match the string `"async"`.

Furthermore, the "yaml-is-great-at-first-but-has-so-many-edge-cases-it's-terrible" quirks that you mentioned leads experienced users to try to be as explicit as possible when writing Semgrep rules by putting pipes before _every_ pattern to avoid quirks like this. Both @kurt-r2c, @brandonspark, and I agreed with this in an [internal Slack discussion](https://returntocorp.slack.com/archives/C01AX0QCEET/p1674002180588479?thread_ts=1673993433.632929&cid=C01AX0QCEET), and I've talked to power users that also made a habit of doing that.

I think that while this is ultimately not our fault (and is almost certainly weird YAML parser/spec behavior), it makes for an incredibly confusing user experience for both newcomers and experienced users alike. Fixing this particular case also makes writing JS SSC rules _way_ easier because we don't have to manually handle all the different ways to do imports in those languages. We can just have a label that's the package name and require it in the sources.

**Comment by aryx** [comment]
cc @emjin

**Comment by emjin** [comment]
The problem with the first rule is not a YAML issue (either because of the spec or the parser), it's a Javascript parser issue. If you don't make this a taint pattern, and instead just try to match `pattern: |\n "async"`, you'll see that it matches string literals.

I'm not the expert on Javascript imports, Nat is, but let's talk about this first so we can make sure I have a full understanding of the frustrations with YAML.
