### ISSUE TITLE
Support fully featured regexp in strings (e.g. PCRE)

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#688]
**Is your feature request related to a problem? Please describe.**
A motivating example is to match a 16-digit hex field (e.g. when searching for a hard-coded hexidecimal API key):
```python
$KEY = "=~/[A-Fa-f0-9]{16}/"
```

With vanilla ocaml regex, I'd need to instead write:

```python
$KEY = "=~/[A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9][A-Fa-f0-9]/"
```

**Describe the solution you'd like**
Support more fully featured regex dialects. For example, https://mmottl.github.io/pcre-ocaml/ would allow detection of pcre.

**Comment by DrewDennison** [comment]
Would also be nice since `pattern-regex` will have PCRE support. Alternatively, we could make it so all regexing is done in python and you have to do something like 

```yaml
patterns:
    - pattern: $KEY = "..."
    - pattern-regex: "[A-Fa-f0-9]{16}"
```

and let the and logic make the magic happen. Related to #629

**Comment by mschwager** [comment]
Can we close this? You need to use `pattern-inside`, but what @nbrahms is describing is now available.

**Comment by aryx** [comment]
Should work now
