### ISSUE TITLE
Match inside JS regex

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#689]
https://semgrep.live/kjO?version=experimental

How do I match inside JS regex?

**Comment by ievans** [comment]
Hi @ajinabraham ! Are you familiar with the regex syntax for finding strings inside code: https://github.com/returntocorp/semgrep/blob/develop/docs/pattern-features.md#strings ? Just checking before I dig in.

**Comment by ajinabraham** [comment]
@ievans Yes I am familiar. I am trying to match a special case where a regex is constructed with user input.
```
/^([a-zA-Z0-9_\.\-])+\@/ + user_input + /(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/.test('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
```

**Comment by ievans** [comment]
Ah, as I see it, semgrep is not interpreting the regex as a string literal, so the string literal syntax matching doesn't work.

**Comment by dlukeomalley** [comment]
@ajinabraham What's the relative priority of this ticket versus some of the others you've filed? We're gearing up for our next 2-week sprint and want to tackle the highest priority items for you. Thanks!

**Comment by ajinabraham** [comment]
I would say medium again. This blocks me from adding a rule that can check for regular expression DoS.

**Comment by nbrahms** [comment]
Fixed in 0.10

**Comment by devd** [comment]
Hey! I am not sure if I understand this issue+fix correctly. I am trying to detect Ruby regexes using ^ or $ (cos they should very likely be using \A \z and not ^ $) and I can't match regexes. If I understand this issue+fix, it seems like I should be just be able to match regexes like a normal string. https://semgrep.dev/s/KWj5/ only seems to match one regex. (but I also think it would be nice if regexes were treated as a first class syntactic element)

**Comment by colleend** [comment]
hmm seems like Ruby regexes are parsed a little differently -- the pattern `\...\` for ruby is translated to the AST 
`E(L(Regexp(("...", ()))))`, which won't match the `A.Regexp(("/.../", a)), B.regexp((_s,b))` that went into this fix. I would say that this is a separate issue, as this one mainly focused on Javascript -- I'll open a separate one for your Ruby issue 👍 

Created [this](https://github.com/returntocorp/semgrep/issues/3372) issue to track, please feel free to edit and add your priority level!

**Comment by aryx** [comment]
Note that there's a tree-sitter-regexp! so potentially we could use metavariable-pattern: to have powerful matching inside the regexps themselves! (hardcore).
