### ISSUE TITLE
Variable rendering on single python file problem

### ISSUE THREAD

**Issue by achiar99** [semgrep/semgrep#6895]
I have this simple python file:
```
a = 5
b = a
c = b

def aaa(my_var):
    hello = my_var

aaa(5)

def bbb():
    return 5

e = bbb()
```

And i have this very simple rule:

```
{
   "rules":[
      {
         "id":"-",
         "languages":[
            "py"
         ],
         "message":"$X = 5",
         "pattern":"$X = 5",
         "severity":"ERROR"
      }
   ]
}
```

When i run the semgrep core command the result contains only 3 matches: 

1┆ a = 5
⋮┆----------------------------------------
2┆ b = a
⋮┆----------------------------------------
3┆ c = b 

I expect to have 5 matches. also:
`aaa(5)`
`e = bbb()`

The command to reproduce:
`semgrep -e "\$X = 5" --lang=py /path/to/file`

Any idea why i dont have these missing matches?  There is a way to print the graph with the variable rendering data?
Maybe im doing something wrong?

Thanks!

**Comment by ievans** [comment]
repro: https://semgrep.dev/s/ABB2

This is a limitation of constant propagation in the engine. cc @adamkvitek do we have docs that discuss that?

You probably want to re-write this rule to use [taint mode](https://semgrep.dev/docs/writing-rules/data-flow/taint-mode/), which when combined with [DeepSemgrep](https://semgrep.dev/docs/deepsemgrep/deepsemgrep-introduction/ ) could find these cases.

Feel free to re-open / continue commenting on the thread if there's other ways we can help!
