### ISSUE TITLE
Docker Build Failing on install-deps-for-semgrep-core

### ISSUE THREAD

**Issue by adamtimmins** [semgrep/semgrep#6897]
**Describe the bug**
Attempting to build a local Docker image and keep running into the same error.

I have already tried to update the submodules following the documentation here: https://semgrep.dev/docs/contributing/troubleshooting/

```
#20 26.74 # Fetch, build and install the tree-sitter runtime library locally.
#20 26.74 cd libs/ocaml-tree-sitter-core \
#20 26.74 && ./configure \
#20 26.74 && ./scripts/install-tree-sitter-lib
#20 26.74 /bin/sh: ./configure: not found
#20 26.74 make: *** [Makefile:192: install-deps-for-semgrep-core] Error 127
```

**To Reproduce**
git clone 
git submodule init && git submodule update --recursive
docker build .

**Expected behavior**

**Screenshots**

**What is the priority of the bug to you?**

- [ X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Docker

**Use case**
What will fixing this bug enable for you?

**Comment by aryx** [comment]
Can't reproduce locally on my machine (and seems like all our docker CI jobs are working too).
This is what I get with a freshly cloned semgrep repo, the submodule command you listed and
then 'docker build -t semgrep .'

```
...
# Fetch, build and install the tree-sitter runtime library locally.
cd libs/ocaml-tree-sitter-core \
&& ./configure \
&& ./scripts/install-tree-sitter-lib
Downloading tree-sitter 0.20.6 (lazy = true).
...
```

**Comment by aryx** [comment]
Do you have a libs/ocaml-tree-sitter/core/configure script locally?
What is your machine? OS? Linux? MacOS?

**Comment by adamtimmins** [comment]
Resolved, I wasn't pulling the submodule fully. Cheers.
