### ISSUE TITLE
Support '...' inside for header as in for (...) { 

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#690]
**Is your feature request related to a problem? Please describe.**

How do I look for a property, something like `foo.length`
How to look inside `for()` or `while()` loops?
No luck with these: https://semgrep.live/DGv?version=experimental and https://semgrep.live/0xr?version=experimental

**Describe the solution you'd like**
1. ability to look inside `for()` or  `while()` 
2. or ability to look for object properties anywhere. For example 
```
for (i =0; i<obj.length; i++){}
while(foo && obj.length <1 && any_condition)
```

**Additional context**
Slack conversation: https://r2c-community.slack.com/archives/CK86BJ5DW/p1588528544033500

**Comment by dlukeomalley** [comment]
@ajinabraham Looking for relative priority here as well. Thank you sir!

**Comment by ajinabraham** [comment]
I would say medium. This blocks me from adding a rule that can check for application layer DoS

**Comment by aryx** [comment]
The main issue is that '...' is currently not allowed inside for(...).
I'll add support for it.

**Comment by aryx** [comment]
Should work now!
