### ISSUE TITLE
semgrep 0.6.0 outputs "<internalonly>" as the message

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#691]
semgrep 0.6.0 outputs "<internalonly>" as the message

    $ semgrep --config=r2c tests/
    tests/utils/test_email.py
    rule:python.tempfile.tempfile-without-flush: <internalonly>    ### <------
    106:        attachment = tempfile.NamedTemporaryFile()

**Comment by brendongo** [comment]
Fixed in 0.6.1
