### ISSUE TITLE
Use the library `hypothesis` for property testing

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#694]
We currently have some tests that run semgrep on various real world repos just to get a wide array of inputs and make sure we don't crash on them.

Unit tests could also make use of https://hypothesis.readthedocs.io/en/latest/ to automatically generate many test cases for functions that are meant to never error.

**Comment by nbrahms** [comment]
Going to close this out as it seems like we aren't going to jump on this soon. @underyx please reopen if you start implementing this.
