### ISSUE TITLE
Add semgrep unit test coverage reporting

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#695]
We should start tracking our unit tests' test coverage with pytest-cov. We could also use https://codecov.io/ as an additional CI check to ensure test coverage of new features once we have that.

**Comment by aryx** [comment]
Well semgrep-core is now getting some coverage information! We could push this a little bit more
and indeed send the coverage data to codecov.io or coverall.

**Comment by aryx** [comment]
But at least semgrep-core/scripts/run-coverage.sh satisfy your title, so I'll close this.
We can create another ticket to send the data to codecov or coverall.
