### ISSUE TITLE
Enable mypy on semgrep tests

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#699]
It took lots of effort to get type hinting working on tests so we just disabled it. See http://calpaterson.com/mypy-hints.html which suggests this too. Here's a discussion anyway to try re-adding type hints down the line.

**Comment by ievans** [comment]
@underyx is this actually important? I'd vote to close. We use mypy on the actual code so I think we're getting the 80/20 in terms of value

**Comment by underyx** [comment]
I should've clarified that I'm against this. @nbrahms would you still want to add mypy?

**Comment by nbrahms** [comment]
@chmccreery and I just wasted a bunch of time waiting for CI to fail because mypy wasn't running on test code. IMO we should enable a weaker configuration of mypy just to aid development speed.

**Comment by underyx** [comment]
How do you imagine weaker configuration? And can you describe what the issue was you needed caught?

**Comment by nbrahms** [comment]
FWIW, I'd like to see the following checks in test code:
- Functions with known types are used appropriately

Whereas the following aren't necessary:
- Explicit type annotations in test code
