### ISSUE TITLE
[python] Match implicit generator expressions

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#705]
**Is your feature request related to a problem? Please describe.**
Certain generator expressions are equivalent:
```python
list((a for b in c))
```
is equivalent to
```python
[a for b in c]
```

or:

```python
foo(a for b in c)
```
is equivalent to
```python
foo((a for b in c))
```

**Describe the solution you'd like**
All of these should match the pattern:
```python
(a for b in c)
```

**Describe alternatives you've considered**
Alternatively, they could match `a for b in c` (without the parends), although that technically isn't a stand-alone expression in python

**Comment by mschwager** [comment]
Note that `foo(a for b in c)` is not always the same as `foo((a for b in c))`. Or, at least, sometimes the extra parentheses are required:

```
In [112]: sum((i for i in [1,2,3]))                                                                     
Out[112]: 6

In [113]: sum((i for i in [1,2,3]), 5)                                                                  
Out[113]: 11

In [114]: sum(i for i in [1,2,3], 5)                                                                    
  File "<ipython-input-114-84faa1d42ce9>", line 1
    sum(i for i in [1,2,3], 5)
       ^
SyntaxError: Generator expression must be parenthesized if not sole argument
```

This shouldn't be a big deal - hopefully there's not a lot of Python code floating around with syntax errors. The only place I could see this being an issue is if we tried to autofix the parentheses version to the non-parentheses version and it has more arguments.
