### ISSUE TITLE
Gracefully handle missing files

### ISSUE THREAD

**Issue by rcoh** [semgrep/semgrep#706]
**Describe the bug**
If you run semgrep on a file that doesn't exist, it panics:
```
➜  Downloads semgrep script.py -l python -e '$X == $X'
an internal error occured while invoking the semgrep engine: unknown exception: Unix.Unix_error(Unix.ENOENT, "stat", "script.py").

An error occurred while invoking the semgrep engine; please help us fix this by filing an an issue at https://semgrep.dev
```

**To Reproduce**
Run semgrep on a file that doesn't exist.

**Expected behavior**
An error about a file not existing.

**Screenshots**

**Environment**
pip package v0.6.0

**Comment by ievans** [comment]
cc @brendongo will your work fix this soon?

**Comment by nbrahms** [comment]
An alternative solution is to silently skip the file, but this solution was discarded as being a confusing user experience.
