### ISSUE TITLE
pattern-inside reaches beyond 'boundaries'

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#708]
**Describe the bug**
Sometimes pattern-inside will go beyond what it looks like the 'boundaries' should be.

**To Reproduce**
https://semgrep.live/oQx?version=develop

**Expected behavior**
To myself and others, it seems like the bottom `eval` should not be matched.

> @DrewDennison Why is this matching the eval outside?
> 
> https://semgrep.live/oQx?version=develop
> 
> _Originally posted by @ajinabraham in https://github.com/returntocorp/semgrep-rules/pull/354/files_
>

**Comment by dlukeomalley** [comment]
This appears fixed in 0.9 and above. Please re-open this ticket if I've closed it in error. Thank you @minusworld!
