### ISSUE TITLE
Semgrep fails to parse highcharts

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#710]
```
git clone https://github.com/highcharts/highcharts
semgrep --patttern '$X==$X' --lang python --lang javascript highcharts
```

Or see https://semgrep.live/scan/ee4135e6-74ff-4384-a3e3-76949d9e8580

As of 0.6.1

**Comment by dlukeomalley** [comment]
Still fails as of 0.9.0. @brendongo would this be a good candidate to add to our test suite?

**Comment by nbrahms** [comment]
Note that `exporting-server/java/highcharts-export/highcharts-export-web/target/highcharts-export-web/WEB-INF/jspf/config.js` is not JavaScript; it is a JSON file instead.

**Comment by aryx** [comment]
seems to work now with develop
