### ISSUE TITLE
Semgrep core generic AST input instead of target file

### ISSUE THREAD

**Issue by achiar99** [semgrep/semgrep#7164]
Hello,
There is a way to pass generic AST (json/binary) as the core input and skip the files parsing part?

**Comment by aryx** [comment]
Passing the JSON of the generic AST could actually take longer than parsing the file from scratch ...
For the binary, semgrep-core has a  -generate_ast_binary option and I think if the target filenames contain
.ast..binary semgrep-core recognize it.
But all of this is quite experimental and the interface might change.

**Comment by achiar99** [comment]
@aryx thank you! this is really helpful
There is way to convert json AST into binary AST easily?

**Comment by aryx** [comment]
I don't think so. Not currently. The JSON AST contains also a little bit less information than
the regular ASTs and binary AST, so I'm not even sure it would work.
We export the AST as JSON (and even export its bindings to it for other languages via ATD) so other people can
do their own analysis on it, but it's not really designed to be imported back.
