### ISSUE TITLE
nosemgrep not working on yaml file

### ISSUE THREAD

**Issue by Integralist** [semgrep/semgrep#7183]
**Describe the bug**
Semgrep reports error even though `nosemgrep` is defined.

**To Reproduce**
I have the following yaml configuration...

```yaml
        # nosemgrep: generic.secrets.security.detected-private-key.detected-private-key
        secret_key:
          - |
            -----BEGIN PRIVATE KEY-----
            <REDACTED>
            -----END PRIVATE KEY-----
```

**Expected behavior**
I expected the use of either `# nosemgrep` or `# nosemgrep: generic.secrets.security.detected-private-key.detected-private-key` to cause the semgrep CLI report to ignore the private key.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
I'm installing semgrep via Homebrew and running it locally.

**Use case**
It will mean I don't have to ignore the rule completely via the CLI's `--exclude-rule` flag.

**Comment by aryx** [comment]
it's because nosemgrep needs to be just at the line before (or on the same line) than the finding.
So here the match probably starts at the ----, so the #nosemgrep needs to be just before that.

**Comment by Integralist** [comment]
Thanks for the feedback. The issue then is that the preceding pipe character means the nosemgrep would become part of the yaml string value rather than a code comment
