### ISSUE TITLE
tree-sitter-lang.hcl defined twice

### ISSUE THREAD

**Issue by chenrui333** [semgrep/semgrep#7190]
while trying to [ocaml to 5.0.0](https://github.com/Homebrew/homebrew-core/pull/118465), found an issue while regression build semgrep 1.12.1
```
dune build
Error: Public library tree-sitter-lang.hcl is defined twice:
- languages/terraform/tree-sitter/semgrep-hcl/lib/dune:1
- languages/hcl/tree-sitter/semgrep-hcl/lib/dune:1
make[1]: *** [minimal-build] Error 1
make: *** [core] Error 2
```

**Comment by aryx** [comment]
it's because of issues when moving around submodule.
if you rm -rf languages/hcl/
you should be fine.

**Comment by chenrui333** [comment]
okay, let me give that a try.
