### ISSUE TITLE
Constant propagation fails to consider branches and conditionals

### ISSUE THREAD

**Issue by andrecsilva** [semgrep/semgrep#7199]
**Describe the bug**

In what follows, both methods are functionally the same.

```java
class A {
    
    public void method(boolean condition){
      var str = "hello";
      if(condition){
        if("goodbye".equals(str = "goodbye"))
	  X.test(str);
      }
      // ruleid: untitled_rule
      X.test(str);
    }

    public void method2(boolean condition){
      var str = "hello";
      if(condition && "goodbye".equals(str = "goodbye")){
        X.test(str);
      }
      // ruleid: untitled_rule
      X.test(str);
    }
}
```

~~- The pattern `X.test("hello")` fails to match the second call in both methods. It is possible if `condition` is `false`.~~
~~- The pattern `X.test("goodbye")` fails to match the second call in the first method. It is possible if `condition` is `true`.~~
See @IagoAbal's comment (https://github.com/returntocorp/semgrep/issues/7199#issuecomment-1440347945) below. The behavior for `X.test("hello")` is correct but still wrong for `X.test("goodbye")`, as it should not match the second call on `method2`.

**To Reproduce**
[https://semgrep.dev/s/elDE](https://semgrep.dev/s/elDE)

**Expected behavior**
~~`X.test("hello")` should match the second `X.test(str)` call and `X.test("goodbye")` should match all calls.~~
`X.test("goodbye")` should not match the second call on `method2`.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Comment by ievans** [comment]
@IagoAbal ?

**Comment by IagoAbal** [comment]
> The pattern X.test("hello") fails to match the second call in both methods. It is possible if condition is false.

That's correct behavior, const-prop is a _must_ analysis, it is not enough that in _one_ branch something can be constant, it must be constant in all potential paths. If you want a _may_ analysis, it's better to use taint-mode.

> The pattern X.test("goodbye") fails to match the second call in the first method. It is possible if condition is true.

The bug is actually that it matches the second `X.test(str)` call in `method2`, it shouldn't match it because `str` is not guaranteed to be `"goodbye"`. I am guessing this could be an issue with the translation from Generic AST to the Dataflow IL.

**Comment by IagoAbal** [comment]
As I said, you may want to use taint-mode instead, the rule would look like this: https://semgrep.dev/s/dqeZ/. The bug I mentioned still affects the case when `"hello"` is the source.

**Comment by andrecsilva** [comment]
Thanks for the clarifications @IagoAbal, I've updated the bug report.

**Comment by IagoAbal** [comment]
Minimized: https://semgrep.dev/s/YPyD

**Comment by IagoAbal** [comment]
Working on a fix,  hopefully it will be on time for next week's release.
