### ISSUE TITLE
remove internal representation from json output

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#721]
`metavar` and `md5sum` from the `extra` property shouldn't be output as they are internal and will change from run to run if the internals of `pfff` change

**Comment by underyx** [comment]
@mschwager has a use for these values, so not removing. Instead I'm masking the MD5 values in the test snapshots.

**Comment by DrewDennison** [comment]
@mschwager what's the use? Note that these will be highly unstable with different values of the hash for each version of pfff. @underyx are you sure the need isn't for `pattern-regex` and they can be kept internally but not needed for `--json` i.e. in the final output. This feels a bit like exposing the internal structure of a linter in the json output which I haven't seen other tools do

**Comment by mschwager** [comment]
> @mschwager what's the use? Note that these will be highly unstable with different values of the hash for each version of pfff. @underyx are you sure the need isn't for `pattern-regex` and they can be kept internally but not needed for `--json` i.e. in the final output. This feels a bit like exposing the internal structure of a linter in the json output which I haven't seen other tools do

Here, take a look: https://github.com/returntocorp/routes/blob/master/generate_tree.py#L161

Note that this doesn't make use of things like `md5sum`, but if I understood correctly the original PR fixing this, it was removing ALL `metavars` information, which the above code relies on.
