### ISSUE TITLE
Parse list of statements in pattern

### ISSUE THREAD

**Issue by ulziibay** [semgrep/semgrep#723]
**Describe the bug**
A list of statements cannot be used in pattern!
https://semgrep.live/Bo9

**To Reproduce**
https://semgrep.live/Bo9

**Expected behavior**
It should match the given code.

**Screenshots**

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

**Comment by ulziibay** [comment]
@returntocorp/admins please add Emma to this repo so she can work on it.

**Comment by emjin** [comment]
See working run here. https://semgrep.live/GQq?version=develop
