### ISSUE TITLE
Kotlin multiple extends support

### ISSUE THREAD

**Issue by johnzeringue** [semgrep/semgrep#7248]
**Describe the bug**
Similar to #1850, matching supertypes in Kotlin isn't simple if there can be multiple.

**To Reproduce**
https://semgrep.dev/s/0O8b

**Expected behavior**
`AlsoShouldMatch` in my example should match my rule. In general, rules shouldn't need to consider how many other types are also extended/implemented.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Use case**
Easily matching a single superclass or implemented interface without specifying a bunch of variations.

**Comment by aryx** [comment]
Kotlin supports multiple inheritance?
Java can implements multiple interfaces, but only inherit one class. In kotlin you can inherit multiple classes?

**Comment by aryx** [comment]
Looking at https://medium.com/@rafalmanka/multi-inheritance-in-kotlin-through-composition-53e72d9a095e 
it looks like it's forbidden with the error:
```
Error:(19, 23) Kotlin: Only one class may appear in a supertype list
```

**Comment by johnzeringue** [comment]
Like in Java, you can only have one superclass in Kotlin, but you can implement multiple interfaces. They all appear in the same "supertype" list. Example from the [Kotlin docs](https://kotlinlang.org/docs/inheritance.html#overriding-rules):

```
open class Rectangle {
    // ...
}

interface Polygon {
    // ...
}

// Equivalent to "public final class Square extends Rectangle implements Polygon" in Java
class Square() : Rectangle(), Polygon {
    // ...
}
```

**Comment by aryx** [comment]
Does the order matter? Like does the inherited class must be listed first and the interface after?

**Comment by johnzeringue** [comment]
No, [order doesn't matter](https://pl.kotl.in/BLltha3j5). The only requirement is that the inherited class has to have the parentheses even if there are no args since it represents a call to the superclass constructor.

So maybe the pattern
```
class $CLASS(...) : Whatever {
    ...
}
```

should match

```kotlin
class MyClass : Whatever
```
but not
```kotlin
class MyClass : Whatever()
```

and the opposite should be true for the pattern

```
class $CLASS(...) : Whatever(...) {
    ...
}
```

**Comment by johnzeringue** [comment]
@aryx thanks for the quick response! This is awesome tech 🙂
