### ISSUE TITLE
metavariable-pattern parse errors in one rule skips other rules?

### ISSUE THREAD

**Issue by becojo** [semgrep/semgrep#7271]
**Describe the bug**

**To Reproduce**
Analyze this [GitHub action workflow](https://github.com/ethersphere/bee/blob/af392148ce7ce715aadf08e6d85452a7b019ba9a/.github/workflows/beekeeper.yml):
```
wget https://raw.githubusercontent.com/ethersphere/bee/af392148ce7ce715aadf08e6d85452a7b019ba9a/.github/workflows/beekeeper.yml
```

Running only `r/yaml.github-actions.security.run-shell-injection.run-shell-injection` returns 4 results:
```
semgrep --config="r/yaml.github-actions.security.run-shell-injection.run-shell-injection" 
```

If I add `r/yaml.github-actions.security.curl-eval.curl-eval` to the config, semgrep produces no results
```
semgrep --config="r/yaml.github-actions.security.run-shell-injection.run-shell-injection"  --config="r/yaml.github-actions.security.curl-eval.curl-eval"
```

In the JSON report, I can see that the `metavariable-pattern` in the rule `r/yaml.github-actions.security.curl-eval.curl-eval` is causing a parsing error:
```json
    {
      "code": 3,
      "level": "warn",
      "message": "Syntax error at line /tmp/tmp-1280322-236379.mvar-pattern:1:\n `bash .github/bin/beekeeper_artifacts.sh local-dns\nexport FAILED='no-test'\nif ${{ steps.pingpong.outcome=='failure' }}; then FAILED=pingpong; fi\nif ${{ steps.fullconnectivity.outcome=='failure' }}; then FAILED=fullconnectivity; fi\nif ${{ steps.settlements.outcome=='failure' }}; then FAILED=settlements; fi\nif ${{ steps.pss.outcome=='failure' }}; then FAILED=pss; fi\nif ${{ steps.soc.outcome=='failure' }}; then FAILED=soc; fi\nif ${{ steps.pushsync-chunks-1.outcome=='failure' }}; then FAILED=pushsync-chunks-1; fi\nif ${{ steps.pushsync-chunks-2.outcome=='failure' }}; then FAILED=pushsync-chunks-2; fi\nif ${{ steps.retrieval.outcome=='failure' }}; then FAILED=retrieval; fi\nif ${{ steps.manifest.outcome=='failure' }}; then FAILED=manifest; fi\nif ${{ steps.content-availability.outcome=='failure' }}; then FAILED=content-availability; fi\ncurl -sSf -X POST -H \"Content-Type: application/json\" -d \"{\\\"text\\\": \\\"**${RUN_TYPE}** Beekeeper Error\\nBranch: \\`${{ github.head_ref }}\\`\\nUser: @${{ github.event.pull_request.user.login }}\\nDebugging artifacts: [click](https://$BUCKET_NAME.$AWS_ENDPOINT/artifacts_$VERTAG.tar.gz)\\nStep failed: \\`${FAILED}\\`\\\"}\" https://beehive.ethswarm.org/hooks/${{ secrets.TUNSHELL_KEY }}\necho \"Failed test: ${FAILED}\"\n` was unexpected",
      "path": "/tmp/tmp-1280322-236379.mvar-pattern",
      "type": "Syntax error"
    }

```

**Expected behavior**
I want rules to produce results even if other rules failed. 

**Priority**
How important is this to you?
- [X] P0: blocking me from making progress
- [ ] P1: this will block me in the near future
- [ ] P2: annoying but not blocking me

**Additional context**
I'm using semgrep 1.14.0 from pypi.

**Comment by IagoAbal** [comment]
Thanks a lot for the bug report, I can reproduce, and yeah I agree that Semgrep should still produce those 4 findings.

**Comment by IagoAbal** [comment]
~May be a CLI issue? The core engine can produce the results as expected if you pass it those two rules.~

It seems like a problem when producing the JSON output in the core engine, with non-JSON output it works as expected

Update: Parsing exceptions when evaluating `metavariable-pattern` were not being handled and they could abort the analysis of the file. This wasn't noticeable with this example and using text mode, because text mode immediately prints results.
