### ISSUE TITLE
Remove Nuitka in docker

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#728]
We don't need to have semgrep as a binary inside the docker container since we can run directly with python.

**Comment by ievans** [comment]
@brendongo FYSA, last time this was benchmarked, the built python binary was faster and smaller (https://github.com/returntocorp/semgrep/pull/221)

**Comment by brendongo** [comment]
Yeah looks like it adds ~70MB going from alpine to python:alpine image would be a fair bit of work to get a more minimal install of python and given benchmarked perfomance decrease above will deprioritize this for now.

**Comment by rcoh** [comment]
Fixed in #764

**Comment by brendongo** [comment]
Closed without size increase and no immediate performance decrease
