### ISSUE TITLE
Literal metavariables do not work in Julia

### ISSUE THREAD

**Issue by aviks** [semgrep/semgrep#7280]
**Describe the bug**
Literal metavariables do not work in Julia. See the linked playground. Changing the language from _julia_ to _python_ makes the same pattern match. 

**To Reproduce**
https://semgrep.dev/s/aviks:literal-metavariable

**Expected behavior**
The pattern matches. 

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Playground

**Use case**
More accurate patterns

**Comment by aviks** [comment]
Not sure if that is related, but I also noticed that the metavariable binding in Julia does not const-propagate. 

See this playground: https://semgrep.dev/s/aviks:const-propagation-metavariable

Changing the language to `python` and using a literal metavariable `"$X"` make this pattern work.

**Comment by IagoAbal** [comment]
Thanks for reporting! Minimized example: https://semgrep.dev/s/l6Lj.

**Comment by brandonspark** [comment]
Thanks for the bug report @aviks! Sorry for getting to it so late -- we were at an offsite last week, so I didn't have as much time to catch up. This should be fixed by https://github.com/returntocorp/semgrep/pull/7312.
