### ISSUE TITLE
`semgrep login` could open a browser tab automagically

### ISSUE THREAD

**Issue by leifdreizler** [semgrep/semgrep#7295]
**Describe the solution you'd like**
It would make it faster for new users to get started if `semgrep login` opened a browser tab with the activation link

**Additional context**
This[ StackOverflow post](https://stackoverflow.com/questions/38147620/shell-script-to-open-a-url) could be helpful

**Comment by ievans** [comment]
agreed; cc @rajaraodv @milanwilliams
