### ISSUE TITLE
Clojure: naming resolution broken

### ISSUE THREAD

**Issue by Gby56** [semgrep/semgrep#7311]
**Describe the bug**
I'm currently trying to match an import/require/use statement with a later usage of a function, through an alias.
It looks like this:
```clj
(require '[clojure.xml :as xml]
         '[clojure.zip :as zip])
     


(defn zip-str [s]
  (zip/xml-zip 
      (xml/parse (java.io.ByteArrayInputStream. (.getBytes s)))))

(zip-str "<a href='test.com'/>")
[{:tag :a, :attrs {:href "test.com"}, :content nil} nil]

(println (xml/emit-element (zip/root [{:tag :a, :attrs {:href "test.com"}, :content nil} nil])))
```

And I'm trying to do this, to catch a direct use, maybe later check if XXE protections have not been enabled etc.... (inspiration here https://github.com/clj-holmes/clj-holmes-rules/blob/main/security/xxe-clojure-xml/xxe-clojure-xml.yml)

```
    patterns:
      - pattern: |
          ... clojure.xml :as $X ...
      - pattern: |
          ... 
          ($X/parse ... ) 
          ...
```

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
https://semgrep.dev/s/rgkj

**Expected behavior**
It should show me a match, because both patterns work independently I think (remove $X for the xml/parse call)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Use case**
Making more rulez !!! Clojure seriously has zero tooling

**Comment by aryx** [comment]
One of the issue is that xml/parse is parsed as a single token, so is $X/parse, so you can't even
get $X/parse match xml/parse.

**Comment by aryx** [comment]
Ideally you would just write (clojure.xml/parse ...) and it would match the code, even if clojure.xml was imported and aliased
(just like we do for the other languages).
Is (clojure.xml/parse ...) valid Clojure syntax? Or you can write (clojure.xml.parse ...) ?
What does this '/' operator does? It just works for stuff you've required first?

**Comment by Gby56** [comment]
well I didn't know that was considered as a single token ! Interesting
Sometimes I wished there was a debug mode to show the tokenization in the supplied example code in the playground, it would really help understanding what can be matched/what cannot
I understand your PR will allow for matching that sub package ? basically the main need is to match aliases from imports, and then reuse that alias in a function call yeah.

In python I guess it's the same thing, you can do

```python
import package as p1
...
p1.function_call()
```

There, the equivalent in Clojure is
```clj
(p1/function_call ... ) 
```

https://clojuredocs.org/clojure.core/alias

**Comment by aryx** [comment]
you can use semgrep-core -l clojure -dump_ast foo.clj to see the internal representation.
At some point this was accessible from the playground but we removed it I think.
