### ISSUE TITLE
JavaScript relaxed rule.

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#732]
**Is your feature request related to a problem? Please describe.**

For JavaScript, you can define a global variable without `var`, `let` or `const` etc.
Does it make sense for 

`var $FOO = 1`  to match both `foo = 1;` and `var foo=1;`
or 
`$FOO = 1`  to match both `foo = 1;` and `var foo=1;`

**Describe the solution you'd like**
Example:

Consider a pattern:

```
- pattern: |
              var $INP = $REQ.$FOO.$BAR;
              ...
              var $QRY = {$where: <... $INP ...>};
              ...
              $OBJ.find(<... $QRY ...>, ...);
```

Having the ability for `var $QRY = {$where: <... $INP ...>};` to match both

`var query = {$where: this.username == '${username}' }`
and 
`query = {$where: this.username == '${username}' }`

is desirable.

**Comment by dlukeomalley** [comment]
@ievans @aryx Any thoughts on the `var $FOO =` vs. `$FOO = ` equivalences?

**Comment by aryx** [comment]
We already support the equivslence if you use the right part.

**Comment by aryx** [comment]
Note that it could be nice in smegreplive to propose a suggestion/warning on the pattern saying they may prefer to use an assign instead of a declaration to match more cases

**Comment by ajinabraham** [comment]
This is not relevant now. Closing this.
