### ISSUE TITLE
XML: support attribute patterns

### ISSUE THREAD

**Issue by gand3lf** [semgrep/semgrep#7344]
Hi guys!
Please consider this example: https://semgrep.dev/s/GZX1
Probably the pattern-inside excludes the attributes from the current match. Is it possible to fix it?
```  
patterns:
      - pattern-inside: <application ... />
      - pattern: android:allowBackup="true"
 ```
There are some workarounds that can be used but I think that the trivial and standard solution does not work.

I would like to do something like:
```
<$EL $...HERE/>$...HERETOO</$EL>
```
For example: https://semgrep.dev/playground/s/WP7z

Thank you!

**Comment by aryx** [comment]
The issue is that a pattern like 'foo="bar"' is not recognized as an attribute, but as XML text, so
the matching does not occur.
