### ISSUE TITLE
semgrep.live can't make test pass

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#738]
https://semgrep.live/5o3?version=develop
Actually there are 9 matches and but add true positive tests can identify only 8.
Also make test pass not working.

**Comment by minusworld** [comment]
It looks like two different rules are firing on the same line, which is confusing "Make Tests Pass" and the test harness.  We should make sure to account for this case.

![image](https://user-images.githubusercontent.com/2374948/81974991-3a7f0200-95db-11ea-9464-68534c3650cc.png)

In the meantime I'm going to see if I can make only the correct rule fire there.

**Comment by minusworld** [comment]
I made a comment about this here:
https://github.com/returntocorp/semgrep-rules/pull/481/files#r425397852

I'm going to make a new issue about handling the cases when multiple rule IDs fire on the same line.

**Comment by minusworld** [comment]
New issue: https://github.com/returntocorp/semgrep/issues/753
