### ISSUE TITLE
Duplicate search-mode matches when target has an explicit cast

### ISSUE THREAD

**Issue by kurt-r2c** [semgrep/semgrep#7403]
**Describe the bug**
Matches for patterns containing casts produce duplicates, one including the cast and one without.

See https://github.com/returntocorp/semgrep/pull/7109

**To Reproduce**
https://semgrep.dev/s/0wlB

**Expected behavior**
This should return one finding, not two.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Exposed via internal rule-writing efforts

**Comment by IagoAbal** [comment]
This is very likely a consequence of #7109. We actually had an idea to simplify the implementation https://github.com/returntocorp/semgrep/pull/7109#discussion_r1129691821. I think to fix this issue we just need to use the `is_root` parameter that we already use for sym-prop. We probably only want to apply this _(T) E = E_ equivalence when `not is_root` (same as sym-prop), that way we can match `return E` against `return (T) E`, while the pattern `E` by itself will only match `E` and not `(T) E`.
