### ISSUE TITLE
How to scan all commits related to an MR using semgrep

### ISSUE THREAD

**Issue by Ncoder2** [semgrep/semgrep#7482]
Hi Team,

I would require help in scanning only the commits related to a merge request using semgrep with git cli.
I tried to use the --baseline-commit option, however i am a little unclear as to how it works. 

My scenario:

- I have a working branch called branch1
- My default branch is develop
- Raised a merge request MR 1 with a few commits starting from c1 to cn (all related to only the MR)
- /rules are my custom rules folder
- Also, i am running this inside the folder where the code resides
- I retrieved the FIRST MR COMMIT HASH for the MR and passed it to baseline-commit like this:

FIRST COMMAND:
`semgrep --config /rules --verbose --json -o results.json --metrics off --baseline-commit=FIRST_MR_COMMIT_HASH`

SECOND COMMAND:
`semgrep --config /rules --verbose --json -o results.json --metrics off --baseline-commit=$(git merge-base FIRST_MR_COMMIT_HASH HEAD)`

In both these command's output, the commits scanned by semgrep listed in the output were different from the commits related to the MR.

**Comment by nmote** [comment]
My first guess is that you haven't checked out the branch associated with the MR before running these commands. Semgrep will scan whatever revision you currently have checked out. You'll also want to pass the commit BEFORE the first MR commit hash as the baseline commit, not the first commit itself.

We recommend using `semgrep ci` for this sort of thing, which will handle it all for you. Setting up Semgrep in GitLab is documented here: https://semgrep.dev/for/gitlab

In general we try to keep our GitHub issues to only bug reports and feature requests. If you have any followup questions or future support requests, please ask on the community slack: https://go.semgrep.dev/slack
