### ISSUE TITLE
Semgrep tests cannot handle multiple rule IDs firing on the same line.

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#753]
**Describe the bug**
The discussion on https://github.com/returntocorp/semgrep/issues/738 led us to discover that semgrep tests assume that only one rule ID will fire per line.  In the linked discussion, this was actually caused by testing multiple rules in a larger test file -- a rule was firing in an unlikely situation because we have to organize "whole programs" inside our test files.

So, while the above case isn't an issue, there may be situations in the future where rule IDs need to fire on the same line.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.live: https://semgrep.live/5o3?version=develop

**Expected behavior**
It would be nice to be able to do two comments for ruleid. Or to have a comma-separated list. Or something like that.

```
// ruleid: rule1
// ruleid: rule2
System.out.println("...");
```

```
// ruleid: rule1,rule2
System.out.println("...");
```

**Comment by ievans** [comment]
c.f. https://github.com/returntocorp/semgrep-rules/issues/61
