### ISSUE TITLE
Semgrep Scanning Mismatched Results

### ISSUE THREAD

**Issue by Thamaraiselvan942** [semgrep/semgrep#7569]
Hi Team,

 When scanning a repository with Semgrep, we noticed that it sometimes shows more vulnerabilities and sometimes shows less vulnerabilities each time we scan the repository without any commit. This causes issues when we try to compare daily Semgrep results with the previous day's results because the changes in the number of vulnerabilities are not consistent.

**Expected Result:**
We expect Semgrep to consistently show the same number of vulnerabilities each time we scan the repository without any commit.

**Actual Result:**
When we scan the repository multiple times without any commit, Semgrep shows different numbers of vulnerabilities each time.

**Comment by ievans** [comment]
@Thamaraiselvan942 thanks for this report, we certainly intend for Semgrep to be deterministic. Can you provide a reproduction?

**Comment by Thamaraiselvan942** [comment]
@ievans Thanks for updating, Is there any options to get the difference between two gitlab-sast file

**Comment by Thamaraiselvan942** [comment]
> @Thamaraiselvan942 thanks for this report, we certainly intend for Semgrep to be deterministic. Can you provide a reproduction?

now again reproduce the same issue, while scan a repo in 1st time it shows 2372 vulnerabilities and in second time shows 2374
vulnerabilities , and also I found 3 new  id's added in 2rd.
I test this without any commit changes made in repo .
![Screenshot (466)](https://user-images.githubusercontent.com/68262845/233335453-94b7d6a1-42b4-4834-90a3-1fc52c672aed.png)

**Comment by ievans** [comment]
@Thamaraiselvan942 can you provide us access to the repo, or a minimal reproduction, that shows the non-determinism?
