### ISSUE TITLE
Pattern parse error in rule clojure.lang.security.use-of-md5.use-of-md5

### ISSUE THREAD

**Issue by jonny64** [semgrep/semgrep#7654]
**Describe the bug**
{
  "$schema": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/schemas/sarif-schema-2.1.0.json",
  "runs": [
    {
      "invocations": [
        {
          "executionSuccessful": true,
          "toolExecutionNotifications": [
            {
              "descriptor": {
                "id": "Pattern parse error"
              },
              "level": "error",
              "message": {
                "text": "Pattern parse error in rule clojure.lang.security.use-of-md5.use-of-md5:\n Invalid pattern for Clojure:\n--- pattern ---\n(MessageDigest/getInstance \"MD5\")\n--- end pattern ---\nPattern error: (Failure \"clojure is not supported yet\")\n"
              }
            }
          ]
        }
      ],
      "results": [],
      "tool": {
        "driver": {
          "name": "semgrep",
          "rules": [],
          "semanticVersion": "1.3.0"
        }
      }
    }
  ],
  "version": "2.1.0"
}

**To Reproduce**
--config p/default

**Expected behavior**
no errors

**Screenshots**

**What is the priority of the bug to you?**

- [x ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
docker :1.3.0

**Use case**
fixing rule.. maybe ?

**Comment by michael-altis** [comment]
Just had the same bug happen to me, turns out it was a pinned semgrep version in my pre-commit (I was still on 1.6.0).
Upgrading to current latest version (1.20.0) fixed the error, perhaps it'll work for you as well.

**Comment by jonny64** [comment]
pinned version is OK, random analyzer version is not OK for large project...

my current workaround `--exclude-rule clojure.lang.security.use-of-md5.use-of-md5`

how do I disable clojure language for my project?

**Comment by jonny64** [comment]
https://github.com/returntocorp/semgrep-rules/pull/2916

**Comment by ievans** [comment]
@jonny64 as mentioned, this should be fixed by upgrading to the latest version of Semgrep, not by deleting clojure rules from the registry.
