### ISSUE TITLE
Support `dot dotdotdot dot` ellipsis in swift

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#7664]
**Describe the bug**
Currently the engine does not support `$VALUE. ... .FOO(...)` or `$VALUE. ...` which makes it fairly hard to write certain rules in swift.

**To Reproduce**
Visit https://semgrep.dev/s/JK8W click run

**Expected behavior**
https://semgrep.dev/s/JK8W should pass 

`$VALUE. ... .$FOO(...)`
and
`$VALUE. ...`

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
Help writing swift rules

**Comment by nmote** [comment]
Fixed in #7816
