### ISSUE TITLE
Support $...METAVARIABLE in swift

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#7666]
**Describe the bug**
Currently `$...ARGS` is not supported in swift

**To Reproduce**
Visit https://semgrep.dev/s/Kq1X click run

**Expected behavior**
$...ARGS should work

**Screenshots**

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Use case**
improve swift coverage in rules

**Comment by ihji** [comment]
Fixed in #7825
