### ISSUE TITLE
javascript pattern-not with null not working as expected

### ISSUE THREAD

**Issue by ajinabraham** [semgrep/semgrep#768]
Is this expected?
https://semgrep.live/BEx?version=develop

works if I replace metavar with `hash`
`- pattern-not: if (hash == null) { ... };`

**Comment by dlukeomalley** [comment]
@ajinabraham I'm having a hard time understand the pattern you want to match and what you don't want to match. Mind sharing more details or examples? Thank you.

**Comment by ajinabraham** [comment]
@dlukeomalley I want to catch all `==` comparisons but it should not match comparisons with `null`

example:  
match
```
hash == '12ss33'
hash == 123
123 == hash
```
do not match

```
hash == null
hash == undefined
hash == NaN
```

**Comment by ajinabraham** [comment]
@dlukeomalley I want to prioritize this over the rest since this is already throwing a lot of false positives in existing rule.

**Comment by minusworld** [comment]
@ajinabraham Does changing the metavariable work? Something like this: https://semgrep.live/bwZZ?version=develop?

**Comment by ajinabraham** [comment]
Thanks that works. So that metavar has scope in both pattern cases? I thought it had scope only under the single `pattern:`

**Comment by minusworld** [comment]
Yep! I think that was added in 0.7.0. But it looks like it didn't make it into the CHANGELOG. I'll amend that. :x

**Comment by minusworld** [comment]
I added the bit about how metavariables match across patterns in the CHANGELOG: https://github.com/returntocorp/semgrep/blob/develop/CHANGELOG.md#070---2020-05-12. Thanks for bringing this to our attention! 🙏

**Comment by minusworld** [comment]
@ajinabraham Let me know if this comes up again! I'm going to close this ticket. Thanks again!
