### ISSUE TITLE
performance tests: Set up saving snapshots upon releases

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#770]
We want to see charts of how semgrep performance has change over time for all the various test cases. See for example [speed.pypy.org](https://speed.pypy.org/timeline/?exe=3%2C6%2C1%2C5%2C8%2C9%2C10%2C11&base=5%2B388&ben=sqlalchemy_declarative&env=1&revs=1000&equid=off&quarts=on&extr=on#/?exe=3,6,1,5,8,9,10,11&base=5+388&ben=sqlalchemy_declarative&env=1&revs=1000&equid=off&quarts=on&extr=on) — we could do with something much simpler of course.

### Option 1

We could commit snapshots with github actions and open a PR to add them to `develop` upon every release tag.

### Option 2

We could publish artifacts with github actions and later gather those artifacts somehow.

**Comment by brendongo** [comment]
Simplified perf tests in https://github.com/returntocorp/semgrep/pull/1373 makes this n/a
