### ISSUE TITLE
performance tests: Add a github action that benchmarks PRs when a comment is sent

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#772]
I'd want to be able to comment `/benchmark 10%` on PRs, which would run the full benchmark suite on the base and the head versions, and would fail CI if the new code is 10% slower in any of the scenarios.

**Comment by dlukeomalley** [comment]
Closeable given @brendongo perf benchmarking?

**Comment by brendongo** [comment]
Yeah with current benchmark we fail CI if semgrep becomes 15% slower than our 0.17.0 release on a given set of repos on every PR.
