### ISSUE TITLE
Example doesn't work: Unknown option -lang.

### ISSUE THREAD

**Issue by Nudin** [semgrep/semgrep#774]
**Describe the bug**
I tried the example from the README:
```
$ semgrep --lang python --pattern '$X == $X' test.py
Unknown option -lang.
non-zero return code while invoking semgrep with:
	semgrep-core -lang python -rules_file /tmp/tmpyfdsrogh -j 6 test.py
Command '['semgrep-core', '-lang', 'python', '-rules_file', '/tmp/tmpyfdsrogh', '-j', '6', 'test.py']' returned non-zero exit status 2. Expecting value: line 1 column 1 (char 0)

An error occurred while invoking the semgrep engine; please help us fix this by filing an an issue at https://semgrep.dev
```
**To Reproduce**
- Download Ubuntu version and follow the Example Usage in the README.md

**Environment**
- Binary from the Ubuntu tgz in version 0.7.0, on Arch Linux (since it is static build this shouldn't be an issue).

**Comment by rcoh** [comment]
**First off,** to immediately unblock yourself, you can use the dockerized verison:
```
docker run --rm -v "${PWD}:/home/repo" returntocorp/semgrep --version
```

**Next** to debug:
We're actually not shipping static binaries until this weeks release (coming out tomorrow, 0.8.0), so it's possible that's the issue? (although you're not getting some glibc error, so I'm not sure it's a linking issue at all.)

In the meantime, did you use the install script or attempt to install manually from the archive? I did a quick test running the install script (manually removing calls to sudo) in the archlinux docker image and it resulted in a working semgrep installation.

My suspicion is `semgrep-core` is somehow pointing to the wrong thing? Can you run the following and let me know what it prints?
```
semgrep --version
which semgrep-core
semgrep-core -version
```

**Comment by Nudin** [comment]
You are right: I don't know how, but I apparently managed to have a wrong binary in 'semgrep-core'-binaries place:
```
$ semgrep-core -version
The OCaml runtime, version 4.07.1
```
Thanks and sorry for the effort.
