### ISSUE TITLE
Kotlin does not detect flow of string inside Objects 

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#7742]
**Describe the bug**
Semgrep appears to ignore dataflow inside objects https://semgrep.dev/s/JKYj 

```
object Hi {
    private const val MYSTRING = "123"

    // should match
    private val magicString = Base64.decode(MYSTRING, Base64.DEFAULT).toString(Charsets.UTF_8)

}
```

Is ignored from the pattern in the rule above

**To Reproduce**
https://semgrep.dev/s/JKYj

**Expected behavior**
The rule should match inside objects too

**What is the priority of the bug to you?**

- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
Match more findings in Kotlin

**Comment by IagoAbal** [comment]
I think this is just a Kotlin bug? See https://semgrep.dev/playground/s/o2nR vs https://semgrep.dev/playground/s/o2nR.

**Comment by IagoAbal** [comment]
Despite of the bug, could you rely on const-prop instead @LewisArdern ? https://semgrep.dev/playground/s/o2nR
