### ISSUE TITLE
Either change or add option to make check IDs independent of config location

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#775]
Right now, check IDs depend on the location of the config.

E.g., using the config `r/r2c` from semgrep.live, vs. downloading and running that same config from a local directory "dir", yield two different check ids:

`r2c.python....`

vs.

`dir.r2c.python...`

This breaks archiving with the semgrep action, as the archive can not easily be run locally.

The ask here is to either:
1. Make check IDs a constant function of config location
2. Add an option to make them so

**Comment by brendongo** [comment]
There is an existing flag `--no-rewrite-rule-ids` that does not append the path to the file to the rule_id. Since check packs look like they have a flattened structure (already include `r2c.python....` in the rule_id) we don't have to worry about this flag stripping those out.

**Comment by nbrahms** [comment]
Looks good enough for my usage. Thanks!
