### ISSUE TITLE
Too chatty for CLI tools, weird behavior on validation errors

### ISSUE THREAD

**Issue by dpc** [semgrep/semgrep#7756]
**Describe the bug**

I'm running `semgrep` in our git precommit hooks and CI. If everything is OK, it should be silent. If something is wrong, it should display errors. So I'm using `semgrep scan -q` to avoid some of the noisy messages. But with `-q` `semgrep` will not display anything when the configuration file is invalid... which is very important when our developers are editing/adding rules.

I thought about doing:

```
semgrep scan --validate config.yaml && semgrep scan -q config.yaml
```

but that `semgrep scan --validate` is again super-chatty, displaying irrelevant messages, yet with `-q` will *not* display validation errors even though that was the primary reason to run it.

**To Reproduce**

```
> semgrep --version
1.0.0
```

**Expected behavior**

Validation errors should always be printed on stderr. If someone really doesn't want *any* output, even on errors, they can always `2>/dev/null`.

**Comment by mjambon** [comment]
Acknowledged. See also https://github.com/returntocorp/semgrep/issues/7661
