### ISSUE TITLE
metavariable-regex for variable in pattern-not-include leads to no match in Go

### ISSUE THREAD

**Issue by cokeBeer** [semgrep/semgrep#7771]
**Describe the bug**
metavariable-regex for variable in pattern-not-include leads to no match

**To Reproduce**
https://semgrep.dev/s/eWw8

**Expected behavior**
one match. not match the statement in a filtered if condition

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ✅] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
filter out some false positive cases by metavariable-regex for variable in pattern-not-include

**Comment by cokeBeer** [comment]
Any feedback ?

**Comment by ihji** [comment]
The reason for this is that the `metavariable-regex` is not linked to the `pattern-not-inside` above. As a workaround, you can consider creating nested patterns like the following:
```
- pattern-not-inside:
    patterns:
        - pattern: |
            if $S(...) {
                ...
            }
        - metavariable-regex:
            metavariable: $S
            regex: ^(?i)\w*(filter|check|validate)\w*$
```
