### ISSUE TITLE
Designation for a non-string value

### ISSUE THREAD

**Issue by inkz** [semgrep/semgrep#784]
**Is your feature request related to a problem? Please describe.**
Recently there was a lot of rules intended to find usage of a value that is non-literal string
```javascript
// using string value
foo("yo");

// using non-string value
foo(bar);
```
usually, I tackle it like

```yaml
- pattern: |
    foo($BAR);
- pattern-not: |
    foo("...");
```
but sometimes there are too many patterns like this inside one rule,
e.g. https://github.com/returntocorp/semgrep-rules/blob/ac70ce84c0a82f1342cf16d7f926ac77a32b705b/java/lang/security/audit/ognl-injection.yaml

 so I wonder is there opportunity to create a designation for a non-string value? which is basically the direct opposite of `"..."` 

**Describe the solution you'd like**
No strict point, maybe smth like `!"..."` ?

**Comment by ievans** [comment]
cc @emjin for consideration in your work

**Comment by aryx** [comment]
I think the pattern-not is what we should use for that. I don't think it's good to invent too many
special features.
