### ISSUE TITLE
Strange indentation of findings (test_check.py::test_terminal_output)

### ISSUE THREAD

**Issue by hannesm** [semgrep/semgrep#7843]
**Describe the bug**

The test `pytest tests/e2e/test_check.py::test_terminal_output` shows pretty strange indentation for the second finding:

```
    targets/basic/stupid.py 
       rules.eqeq-is-bad
          useless comparison operation `a + b == a + b` or `a + b != a + b`;
  possible bug?
          Details: https://sg.run/xyz1

            3┆ return a + b == a + b
```

The indentation of `  possible bug?` looks very strange to me. If put onto the previous line, it'd still be only 59 characters (when running semgrep in an interactive terminal instead of pytest, I can't reproduce the behaviour). If the output should be put on a new line, I'd expect it to be aligned with `useless` from the pevious line.

From `rules/eqeq.yaml`: ``message: "useless comparison operation `$X == $X` or `$X != $X`; possible bug?"``

So, nothing special in that message (no control characters).

In earlier code (before commit b3190747acd0bf885760f8565410373033e9ef35, Mar 24 2023), the ouput was different:
```
-  targets/basic/stupid.py 
-     rules.eqeq-is-bad
-        useless comparison operation `a + b == a + b` or `a + b != a + b`; possible bug?
-        Details: https://sg.run/xyz1
- 
-          3┆ return a + b == a + b
+    targets/basic/stupid.py 
+       rules.eqeq-is-bad                                              
+          useless comparison operation `a + b == a + b` or `a + b != a + b`;    
+  possible bug?                                                                 
+          Details: https://sg.run/xyz1                                          
+                                                                                
+            3┆ return a + b == a + b
```

Now, the outputting code (`message_text = click.wrap_text(f"{message}", width, 8 * " ", 8 * " ", True)`) did not change at all.

Since I try to get the test passed with osemgrep, I'm curious whether the behaviour above in pysemgrep is intentional (and if so, maybe someone could elaborate why the indentation is 2 spaces for the `possible bug`).

Best, Hannes

**Comment by aryx** [comment]
@underyx any idea why the Rich library introduces this weird newline and weird reindentation?

**Comment by hannesm** [comment]
I suggest: we don't dig into why the python code in that environment acts like it does.

Instead, we ignore the python output inconsistency, adapt the rule to emit a shorter message (to easily fit on one line), update the snapshots data. WDYT?

**Comment by aryx** [comment]
Yep, go for it

**Comment by hannesm** [comment]
I'm closing this issue, since it has been solved (by adapting the test case) -- in the end there's a divergence between python and OCaml indentation.
