### ISSUE TITLE
Fix hacky performance test fixtures

### ISSUE THREAD

**Issue by underyx** [semgrep/semgrep#788]
> So, I'm kinda confused about the architecture here. From what I understand about this PR, we're performing these fixture operations when tests are *collected*, not when they're *run*. This gives us a performance hit because these fixtures take a while to run. Is that right?

> Based on above, I have a few questions:

> * Are these fixtures being run because they don't have the `benchmark` argument/fixture? That's why adding it below causes the fixtures to be avoided unless we're actually benchmarking?
> * Why do we have two separate fixtures here that only appear to be used with each other? Could this be one fixture to simplify things?
> * It seems we could leverage existing pytest functionality rather than checking this information ourselves. Whether that's something like adding `benchmark` here to only run this fixture during benchmarking, or leveraging `pytest.mark.parametrize` with `indirect=True` to run the fixture during test-setup instead of test-collection. Am I missing something that makes that not possible?

_Originally posted by @mschwager in https://github.com/returntocorp/semgrep/pull/786_

**Comment by brendongo** [comment]
Simplified perf tests in https://github.com/returntocorp/semgrep/pull/1373 are basically does running these rules on these repos finish in expected amount of time. Closing as n/a
