### ISSUE TITLE
Connecting to Semgrep Registry through Nexus Repository

### ISSUE THREAD

**Issue by 0xdu** [semgrep/semgrep#7922]
**Is your feature request related to a problem? Please describe.**
In an internet-restricted environment, only outbound connections are allowed through the Nexus repository. Can semgrep connect to the registry through the nexus repository?

**Comment by ievans** [comment]
You can set a proxy as described here: https://github.com/returntocorp/semgrep/issues/5084#issuecomment-1113866650

Feel free to re-open this issue if that doesn't work!
