### ISSUE TITLE
Add integration tests for pip package

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#794]
It should install and run on 

- [ ] Ubuntu 16.04 +
- [ ] Debian Stretch +
- [ ] Centos 7 +
- [ ] Alpine
- [ ] Travis & Jenkins base images
- [ ] NodeJS official docker image

https://github.com/pypa/manylinux should cover most of them

**Comment by rcoh** [comment]
We install into maylinux as part of the wheel build process. We should also do ubuntu

**Comment by DrewDennison** [comment]
cc @ajinabraham for vis

**Comment by ajinabraham** [comment]
Will this be tested on Mac?
