### ISSUE TITLE
Expiration date check in the metavariable-comparison condition

### ISSUE THREAD

**Issue by gand3lf** [semgrep/semgrep#7992]
Hi guys!
I would like to check if a date has expired, as in this simple example: https://semgrep.dev/playground/s/DrwY

In the case where you are asking yourself for practical examples. I need this feature to verify inside some XML files that some TLS certificates are not expired.
(Example: https://developer.android.com/training/articles/security-config look at the `<pin-set>` expiration attribute)

As always, thank you guys! :heart:

**Comment by aryx** [comment]
We probably need to find the name of the Python function to get the current date as we mostly used Python operators and builtins until now in the language supported by metavariable-comparison

**Comment by aryx** [comment]
src: https://semgrep.slack.com/archives/C018NJRRCJ0/p1686153533002539
