### ISSUE TITLE
Constant propagation not happening in basic C function case

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#8037]
**Describe the bug**
The function is simply:
```
void fun() {
  int fixed = 42;
  // ruleid: match_fixed_size_buffer
  char a[42];
  // ruleid: match_fixed_size_buffer
  char b[fixed];
  // ok: match_fixed_size_buffer
  char c[unknown];
}
```

But the rule
```
rules:
  - id: match_fixed_size_buffer-copy
    patterns:
      - pattern: |
          $TYPE $BUF[42];
    message: var $BUF - size $SIZE
    languages:
      - c
    severity: WARNING
```
fails to match

**To Reproduce**
https://semgrep.dev/playground/s/b36Q

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/semgrep/issue/PA-2844/constant-propagation-not-happening-in-basic-c-function-case. _Note_: this link is for r2c use only and is not accessible publicly.
