### ISSUE TITLE
Is SemGrep support SCA. 

### ISSUE THREAD

**Issue by salmankhwaja** [semgrep/semgrep#8103]
**Is your feature request related to a problem? Please describe.**
Is Semgrep providing SCA as well. 

**Describe the solution you'd like**
Going through the Github it looks like it does in free version. Going through pricing, in free version, SCA is crossed off. 

**Describe alternatives you've considered**
I think the documentation of Pricing should be updated. 

**Use case**
Confusion would be cleared. 

**Additional context**
Nothing.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/semgrep/issue/PA-2880/is-semgrep-support-sca. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by salmankhwaja** [comment]
https://semgrep.dev/pricing

**Comment by mjambon** [comment]
As you found out, this is on the pricing page above. In general, a good way to get a fast response from a human is the community Slack workspace: https://go.semgrep.dev/slack
