### ISSUE TITLE
Timeouts are not reported as errors

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#811]
Taking the code from https://semgrep.live/NAy and running it locally, I see the following output:
```
$ semgrep --json --config=https://semgrep.live/c/Zpw .
scanning code...
TIMEOUT on ./test.js
{"results": [], "errors": []}
```

I would expect that we should report a "timeout" error for test.js in the returned JSON, and that if `--strict` is specified, semgrep fails with an error code. This would fix semgrep.live as well.

Additionally, we should add a --timeout option to the CLI.

**Comment by nbrahms** [comment]
cc. @brendongo for release planning
