### ISSUE TITLE
Add a parsing --timeout

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#812]
Currently semgrep has a hard-coded timeout for giving up on parsing files (per-file basis). We should make this a user-configurable option and have the python CLI set the default. Suggestion: --timeout=5 gives a 5 second timeout for parsing.

**Comment by nbrahms** [comment]
cc. @brendongo for release planning

**Comment by brendongo** [comment]
Duplicate of https://github.com/returntocorp/semgrep/issues/1368 and handled in #1385
