### ISSUE TITLE
Failure to parse javascript files using non-breaking space

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#814]
C.f. https://raw.githubusercontent.com/OWASP/NodeGoat/master/app/routes/benefits.js

```
ine@imbp4 ~/D/r/s/test (develop)> semgrep --json --config=https://semgrep.live/c/Zpw .
scanning code...
semgrep: ./benefits.js: LexicalError
{"results": [], "errors": [{"data": [{"check_id": "LexicalError", "path": "./benefits.js", "start": {"line": 1, "col": 8}, "end": {"line": 1, "col": 9}, "extra": {"message": "Lexical error: unrecognised symbol, in token rule:\ufffd", "line": "const {\u00a0BenefitsDAO } = require(\"../data/benefits-dao\");"}}], "message": "SemgrepCoreRuntimeErrors"}]}
```

The specific issue comes from the first line with a https://en.wikipedia.org/wiki/Non-breaking_space: 

![Screen Shot 2020-05-21 at 10 49 44 AM](https://user-images.githubusercontent.com/409041/82589300-c9969780-9b50-11ea-9ecd-80995c1baa5a.png)

I'm not sure what the specs say about this, but Node parses it just fine.

**Comment by nbrahms** [comment]
Removing the `good first issue` label...

Per https://dev.realworldocaml.org/parsing-with-ocamllex-and-menhir.html, we likely need to install a 3rd-party library to add unicode support to Lex.

(cc. @aryx )

**Comment by nbrahms** [comment]
cf. https://www.ecma-international.org/ecma-262/5.1/#sec-7.2

**Comment by nbrahms** [comment]
FWIW, despite the fact that Inria's docs imply that unicode string literals should be allowed in Lex files (https://caml.inria.fr/pub/docs/manual-ocaml/lex.html, https://caml.inria.fr/pub/docs/manual-ocaml/lexyacc.html#s%3Aocamlyacc-syntax), using ocamllex 4.07.1 on a match to `"\u{A0}"` yields:
```
File "lexer_js.mll", line 232, character 29: illegal backslash escape in string: '\u'.
```
