### ISSUE TITLE
feat(rule syntax): Support metavariable-type field for Kotlin, Go, Scala

### ISSUE THREAD

**Issue by ihji** [semgrep/semgrep#8147]
Support metavariable-type field for Kotlin, Go, Scala.

Context: #8119

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/semgrep/issue/PA-2901/featrule-syntax-support-metavariable-type-field-for-kotlin-go-scala. _Note_: this link is for r2c use only and is not accessible publicly.
