### ISSUE TITLE
semgrep login choosing GitHub 

### ISSUE THREAD

**Issue by merkleID** [semgrep/semgrep#8157]
**Describe the bug**
can't login through browser and choosing GitHub as authenticator with the url provided by "semgrep login"
**To Reproduce**
do "semgrep login" in command line
copy-paste the provided url+token in browser
try to login using GitHub 

**Expected behavior**
to login
**Screenshots**
it simply doesn't login using GitHub 
**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
brew on macOS 
**Use case**
What will fixing this bug enable for you?
more semgrep rules

**EDIT**
I guess it's a site problem.
I tried a plain simple https://semgrep.dev/login without tokens generated through "semgrep login" and there's still no way to login through GitHub.

**Comment by r2c-demo** [comment]
This issue is synced in Linear at https://linear.app/semgrep/issue/PA-2906/semgrep-login-choosing-github. _Note_: this link is for r2c use only and is not accessible publicly.

**Comment by mjambon** [comment]
Thanks for reporting this. I'm closing the issue here as it is tracked internally in Linear.
