### ISSUE TITLE
--test ignores include path 

### ISSUE THREAD

**Issue by LewisArdern** [semgrep/semgrep#8192]
**Describe the bug**

Currently --test is fairly limited, the requirement is that it 'must' contain the same name as the rule.

Semgrep ignores the `includes` key e.g. https://semgrep.dev/playground/r/wdUYl9/lewisardern.ats-insecure-media-loads?editorMode=advanced which uses

```    
paths:
      include:
        - Info.plist
```
running --test locally with Info.plist

`No tests for fixes found.`

Renaming it to ats-media-load.plist returns
```	
✖ ATS-insecure-media-loads
	missed lines: [4], incorrect lines: []
	test file path: /3/ats-media-load.plist
```

commenting out the paths key returns
` 1/1: ✓ All tests passed`

Overall this feels like not a fun experience for those writing rules locally and this may throw an error a failing test when I add it into the registry --test should respect the paths include as part of the test fixture.

**To Reproduce**
Run --test locally with https://semgrep.dev/playground/r/wdUYl9/lewisardern.ats-insecure-media-loads?editorMode=advanced as an Info.plist

**Expected behavior**
Allow --include to be used to specify what should be used in test or look for the include in the --test and try to find the path or file based on the requirement 

**What is the priority of the bug to you?**

- [x] P1: important to fix or quite annoying

**Environment**
all

**Use case**
Enable better testing

**Comment by LewisArdern** [comment]
Note this also fails in the playground for languages other than generic and regex.

**Comment by aryx** [comment]
@hannesm once you ported --test to osemgrep, hopefully we can also fix this issue (and fix it only in osemgrep).

**Comment by IagoAbal** [comment]
So I think one solution could also be to let `semgrep test`  _ignore_ the `paths` key. Doesn't `semgrep-core` already do this?

**Comment by IagoAbal** [comment]
Having a naming convention that allows you to easily find the test file(s) for a rule is useful. So another way could be that for a rule `a-b-c.yaml` we allow either `a-b-c.ext` as target, or a folder `a-b-c/` that contains the target files that then must satisfy the `paths` key.

**Comment by aryx** [comment]
Let me disable the paths: when we're in --test context mode, so that you can create ats-media-load.plist and get it processed.
