### ISSUE TITLE
... not capturing string literal

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#821]
**Describe the bug**
From #818, I ran into a bug where `"...."` was required for matching an instance of string concatenation. See https://semgrep.live/JLW

**Expected behavior**
I expect both of the following patterns to match string concatenations:

```yml
$SQL.append(... + $PARAM + ...);
```

```yml
$SQL.append("..." + $PARAM + "...");
```

**Comment by ievans** [comment]
@aryx does this require the deep expression matching operator?
