### ISSUE TITLE
pattern-syntax case-insensitive feature not work

### ISSUE THREAD

**Issue by tuhaolam** [semgrep/semgrep#8210]
**Describe the bug**
pattern-syntax case-insensitive feature not work.

**To Reproduce**
as follow:
[Steps to reproduce the behavior, ideally a link to https://semgrep.dev:](https://semgrep.dev/playground/r/qNUD3k/tuhaolam.inner-iprange-detect-2)

**Expected behavior**
It should support case-insensitive pattern match.

**Screenshots**
-

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
pip install, version 1.30.0
and saas version, such as playgroud

**Use case**
-

**Comment by mjambon** [comment]
Hi, the Playground link doesn't match the bug description. Can you please check this and provide more info?

**Comment by ievans** [comment]
Closing as unresponsive, but feel free to re-open with more info
