### ISSUE TITLE
JS parse bug

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#823]
semgrep fails to parse ES6 template strings. e.g.

```javascript
const AButton = styled.div`
  float: left;
`;
```

https://semgrep.live/ELe

**Comment by DrewDennison** [comment]
More complete example https://semgrep.live/7rW

**Comment by aryx** [comment]
It parses template strings, (you can do a = `this is ${handled}`), but not this specific kind that is attached to a method.
