### ISSUE TITLE
Directly supply a symlink to semgrep CLI will break the entire execution

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#8236]
**Describe the bug**
Executing `semgrep --config rules.yml x.py symlink.py`, where `symlink.py` is a symbolic link, will result in the following error: `[ERROR] File not found: symlink.py`.

**Expected behavior**
It should handle the symlink gracefully instead of aborting the entire execution. For example, we can ignore the symlink but still show the finding in `x.py`.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Use case**
We don't have to check whether a file is symlink or not ourselves. It is especially annoying in some automation.

**Comment by mjambon** [comment]
I believe this behavior is intentional since `symlink.py` is passed explicitly on the command line rather than a broken link that would be discovered while scanning the file tree.

As a workaround, I suggest prefiltering the targets. Here's an example in Bash:
```
candidate_targets="x.py symlink.py"
targets=""
for x in $candidate_targets; do
  if [[ -e "$x" ]]; then
    targets+=" $x"
  fi
done

semgrep --config rules.yml $targets
```

**Comment by Isaac0616** [comment]
Why it is the intentional behavior? Like why it is better to abort the entire execution than handle it gracefully?
There definitely are workarounds, but that's not ideal.
