### ISSUE TITLE
NoTokenLocation min_max, empty list exn while processing file

### ISSUE THREAD

**Issue by ghbren** [semgrep/semgrep#824]
**Describe the bug**

I ran `semgrep --config r2c` on my code and got 

```
an internal error occured while invoking the semgrep engine: unknown exception: (Failure
  "NoTokenLocation min_max, empty list exn while processing ./short.js for rule 55..3, with metavar $Y, close location = { \"line\": 2, \"col\": 5, \"offset\": 43 }").  
```

**To Reproduce**

Just run  `semgrep --config r2c`  on file containing
```
async function bar(msg) {
    let x, y;
    y = foo(msg);
}
```

**Expected behavior**

I expect no message on internal error

**Screenshots**

**Environment**
If not using semgrep.live: are you running off docker, an official binary, a local build?

local build installed from brew

**Comment by dlukeomalley** [comment]
Thank you for opening this issue @ghbren. Adding this to my queue to investigate first thing Tuesday (given Memorial Day). Are you blocked and would you like me to prioritize this sooner?

@ievans Is this related to #670? Defer to you on deduping.

**Comment by ievans** [comment]
It is probably not related

**Comment by ghbren** [comment]
@dlukeomalley No need to prioritize this sooner. Please enjoy the long weekend  😃

**Comment by aryx** [comment]
@ievans how do I find the rule corresponding to rule 55..3 in semgrep-rules?
Here is the error:
  "NoTokenLocation min_max, empty list exn while processing ./short.js for rule 55..3, with metavar $Y, close location = { \"line\": 2, \"col\": 5, \"offset\": 43 }").

**Comment by aryx** [comment]
In the mean time, each time there is an error in semgrep-core, I save the rule file passed from semgrep to /tmp/semgrep_core_xxx.yaml so that should be enough.
