### ISSUE TITLE
Autocomplete on zsh errors on no config given

### ISSUE THREAD

**Issue by davidholsgrove** [semgrep/semgrep#8254]
**Describe the bug**
Following documentation (https://semgrep.dev/docs/cli-reference/#autocomplete) on adding 

```
eval "$(_SEMGREP_COMPLETE=zsh_source semgrep)"
```

to `~/.zshrc`, the cli is printing error message on shell start that the config is invalid;

```
[ERROR] invalid configuration file found (1 configs were invalid)
```

The reason being `One of these properties is missing: 'rules'`. 

Adding in an empty `rules: []` to `~/.semgrep/settings.yml`, the config is considered "valid" but the error on `_SEMGREP_COMPLETE=zsh_source semgrep` is now (exit code 7):

```
[ERROR] No config given. Run with `--config auto` or see https://semgrep.dev/docs/running-rules/ for instructions on running with a specific config
```

**To Reproduce**
Move `~/.semgrep/settings.yml` aside, login with the cli, then attempt to add zsh autocomplete.

**Expected behavior**
The documented process worked previously, until a recent semgrep cli update.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Homebrew installed semgrep cli `1.31.2`

**Use case**
Use of autocomplete, and clean shell starting

**Comment by emjin** [comment]
@ajbt200128 maybe you know something about this?

**Comment by ajbt200128** [comment]
Hmm this was happening to me too, but I just assumed it was because I mess with my zshrc file and break things all the time. I'll take a look, I think something just broke it

**Comment by armchairlinguist** [comment]
Thanks y'all - FYI the same symptoms were affecting me with Bash, which might make it more likely to be a general breakage.

**Comment by ajbt200128** [comment]
Closed by https://github.com/returntocorp/semgrep/pull/8360
