### ISSUE TITLE
"semgrep login" doesn't work with either Github and Gitlab as identity provider

### ISSUE THREAD

**Issue by merkleID** [semgrep/semgrep#8279]
**Describe the bug**
can't do a semgrep login using either github and gitlab as id-provider
platform: macOS
shell: zsh

**To Reproduce**
enter semgrep login
get the url+token and open it in browser 
press github or gitlab 
takes me back to https:://semgrep.dev/login 
no authorization given to command line 

**Expected behavior**
my identity confirmed 

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
official binary on macOS installed through brew 

**Use case**
getting more rules for semgrep

**Comment by annikalee** [comment]
@merkleID I'm looking into this. Were you able to login to the semgrep.dev at any point since you filed this?

**Comment by merkleID** [comment]
Tried to login just now using GitHub as SSO, seems working.

thank you!

**Comment by annikalee** [comment]
@merkleID that's great to hear! Just want to confirm all methods are working again for you? (semgrep.dev and semgrep login from the CLI)? If so I'm happy to close this ticket for now and if you have any other trouble, let us know!

**Comment by merkleID** [comment]
Hi,
I forgot to test the cli command 'semgrep login' and no, it still doesn't work.
I copy paste the generated url, open it in browser, click on Github, but still no login after a few pop-ups, and the cli is still waiting for a response 

Tested on Safari, Firefox, Chromium

**Comment by annikalee** [comment]
@merkleID That's not great. I'll take a look and update you as soon as I can

**Comment by merkleID** [comment]
Thank you very much.

Let me know if you need any further/different test on my side.

**Comment by AlbertSPedersen** [comment]
I'm experiencing the exact same issue: the CLI does not receive a callback after I sign in using the provided URL.

**Comment by merkleID** [comment]
> @merkleID That's not great. I'll take a look and update you as soon as I can

and it finally works after a 'brew upgrade' which took semgrep 1.34.1 to 1.35.0

did a 'semgrep login', cliked on the generated link, did login through github, and I finally got this back:

Saved login token

	[REDACTED]

in /Users/luca/.semgrep/settings.yml.
Note: You can always generate more tokens at https://semgrep.dev/orgs/-/settings/tokens

thank you!

**Comment by annikalee** [comment]
@merkleID Glad to hear it's working for you now! We are doing some more improvements to this flow, so hopefully it is even smoother moving forward!

@AlbertSPedersen Are you also able to login when you upgrade to 1.35.0? If so, I'm happy to close this ticket out.

**Comment by AlbertSPedersen** [comment]
It's working for me on 1.34.1. I think my issue was never with the client though, rather, it was an issue with the Semgrep sign-in flow. After signing in with GitHub, I was just sent back to the sign-in screen (even though sign-in was successful, as evident by my GitHub profile picture in the top right corner).

I now know I was supposed to get an "Activate" button after signing in, but this didn't happen, so I thought the client was just not picking up the token. It is working now though :)

**Comment by annikalee** [comment]
@AlbertSPedersen Ah I see. Yes that's a bug that I'm also working on fixing. Glad you got it working though! I'm going to close this ticket and continue to fix the bug that you encountered. I appreciate the feedback from both of you and hopefully this whole process is smoother soon!
