### ISSUE TITLE
Golang fails to parse when function defined in if statement

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#829]
```go
if v, ok := interface{}(x).(interface{ Validate() error }); ok {
    return 0
}
```

fails to parse. See https://semgrep.live/bvE

**Comment by aryx** [comment]
The semgrep live example is not a valid Go file. You can't have statements at the toplevel.
They need to be inside a function.
But indeed, even inside a function you have a problem. Should be easy to fix.
