### ISSUE TITLE
semgrep 0.8.0 --version reports 0.8.1.dev0+gb3c2930.d20200521

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#830]
**Describe the bug**
The official binary 0.8.0 release reports an incorrect version number. (This complicates a programmatic check for whether the correct version is installed.)

```console
$ curl -L https://github.com/returntocorp/semgrep/releases/download/v0.8.0/semgrep-v0.8.0-ubuntu-16.04.tgz | tar -xz
$ semgrep-files/semgrep --version
0.8.1.dev0+gb3c2930.d20200521
```

**Expected behavior**
```console
$ semgrep-files/semgrep --version
0.8.0
```

**Comment by dlukeomalley** [comment]
Queuing up for discussion this morning with the team. Thanks for filing @andersk.

**Comment by brendongo** [comment]
There was an issue in the building steps. Releasing 0.8.1 without this problem.

**Comment by brendongo** [comment]
Fixed in https://github.com/returntocorp/semgrep/pull/836/commits/72c70951c1d4eb1ae3fb01a80e26491be2a069a5

**Comment by brendongo** [comment]
Verified this regression no longer exists on ubuntu 0.8.1 release :D Thanks for filing the bug @andersk!
