### ISSUE TITLE
--lang fails to set input file language

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#831]
**Describe the bug**
The help for `--lang` says “parse pattern and all files in specified language”, but this does not happen (so it’s impossible to lint Python scripts without a `.py` extension):

```console
$ cat .semgrep.yml 
rules:
  - id: test
    languages: [python]
    pattern: bad()
    severity: ERROR
    message: do not call bad()
$ cat bad.py
bad()
$ semgrep --lang=python bad.py
bad.py
ERROR rule:test: do not call bad()
1:bad()
$ mv bad.py bad
$ semgrep --lang=python bad
$
```

**Expected behavior**
```console
$ semgrep --lang=python bad
bad
ERROR rule:test: do not call bad()
1:bad()
```

**Environment**
Official binary (`semgrep-v0.8.0-ubuntu-16.04.tgz`).

**Comment by dlukeomalley** [comment]
Queuing up this one too for discussion with the team @andersk.

**Comment by nbrahms** [comment]
Hi @andersk ,

I believe `--lang` is meant to apply a filter to the files that are inspected, rather than tell `semgrep` what the file language is. It sounds like we probably have a documentation bug to clarify this point.

For your use case, would it be sufficient for `--lang python` to tell `semgrep` to inspect files with a `#!/bin/.../python` shebang?

Best,
Nathan

**Comment by andersk** [comment]
A Python shebang can take many shapes.

*     #!/usr/bin/python

*     #!/usr/bin/env python

*     #!/usr/bin/env python3

*     #!/usr/bin/env pipenv-shebang

*     #!/bin/sh
      "exec" "`dirname \"$0\"`/zulip-py3-venv/bin/python3" "$0" "$@"

*     #!/usr/bin/env nix-shell
      #!nix-shell -i python3 -p "python3.withPackages (ps: [ps: numpy])"

Since Zulip already has a framework to determine which files are in which languages, we would rather have `semgrep` respect this information than have it try to apply independent heuristics.

Also, it definitely doesn’t make sense for `semgrep --lang python my-python-script` to silently ignore `my-python-script` and do nothing. Perhaps `--lang` could act as a filter for passed *directory* names but should force the language for passed *file* names? Or perhaps there could be a separate `--force-lang` option and the above usage should warn?

**Comment by nbrahms** [comment]
@andersk Thanks for the clarification! We'll get this prioritized for you.

**Comment by brendongo** [comment]
After #863 going to pull in the file targeting logic from bento into semgrep
