### ISSUE TITLE
 Fatal Error Occurred while Scanning Large Dataset

### ISSUE THREAD

**Issue by Afaq-Hashmi** [semgrep/semgrep#8342]
Hi,
I have attempted to limit the memory consumption of semgrep to prevent fatal errors during the scan, but unfortunately, my efforts have been unsuccessful. As a result, the scan continues to throw fatal errors, as depicted in the attached screenshots.

While I don't mind a slower scan, my primary goal is to complete the analysis on a large dataset without encountering any errors. I would greatly appreciate any guidance or assistance you can provide to resolve this issue and ensure a successful scan without memory-related errors.

![2023-07-21 18_42_02-Termius - Customer Portal DEV (1)](https://github.com/returntocorp/semgrep/assets/57212826/ea483db2-611e-49f0-83c0-ed70fa50de73)
![2023-07-21 17_14_36-Termius - Customer Portal DEV](https://github.com/returntocorp/semgrep/assets/57212826/048781ac-e2a3-4a2b-a0f3-806b32a5f7ab)

**Comment by emjin** [comment]
Hi! Can you share the semgrep command you're running?

**Comment by Afaq-Hashmi** [comment]
The issue is resolved after using **--max-memory 500 -j 1**
