### ISSUE TITLE
Is it possible to ignore code block by a config file ?

### ISSUE THREAD

**Issue by adpeyre** [semgrep/semgrep#8382]
Hello,

Is there a way to ignore code blocks by a config file ? I don't like add tool-specific annotations directly in my code.

Ty

**Comment by ievans** [comment]
You can ignore at the file and directory level: https://semgrep.dev/docs/ignoring-files-folders-code/#defining-ignored-files-and-folders-in-semgrepignore, but there's no support for doing it at the code block level. Most users who are doing ignores but don't want to annotate code use the web UI on semgrep.dev. Feel free to re-open this issue as a feature request for the local CLI!
