### ISSUE TITLE
semgrep fails to parse solidity-workshop

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#839]
semgrep fails to parse https://github.com/coinbase/solidity-workshop

**Comment by nbrahms** [comment]
@brendongo Can you add reproduction info?

I ran `semgrep -e '$X==$X' --lang js .` on the root of `solidity-workshop` as of commit `0c0ad9759` using version 0.8.1, with no errors.

**Comment by brendongo** [comment]
https://github.com/returntocorp/semgrep/pull/886/files

Looks like this issue can be closed :D
