### ISSUE TITLE
Allow using autofix via the command line

### ISSUE THREAD

**Issue by rtpg** [semgrep/semgrep#840]
**Is your feature request related to a problem? Please describe.**
Sometimes I just want to fix up a pattern once through the codebase. I can search for the problem pattern via the command line but am unable to just fix it as-is

**Describe the solution you'd like**
something like 
```
semgrep --lang python --pattern 'self.assertEqual($X,$Y)' --fix 'assert $X == $Y'`
```
**Additional context**

I understand the value of checking in this kind of stuff to a config file. But when doing things like operating on a repo where I have limited control, being able to use `semgrep` is still useful

**Comment by aryx** [comment]
We can do that by storing the pattern/message/fix in a local semgrep.yml file right?
@brendongo we could also allow it via the cli without an intermediate yaml file? Like we also want to support
the --message in #1885

**Comment by msorens** [comment]
Yes, please! This would be terribly useful.

**Comment by msorens** [comment]
Responding to the stale-bot, please keep this active. 🎉

**Comment by somebody1234** [comment]
especially useful if you don't want to make an entire config file for a single rule, you'd be able to just add `semgrep -e 'foo' --replacement 'bar' -l lang ./src` or something
