### ISSUE TITLE
Outdated references to vulnerable react components

### ISSUE THREAD

**Issue by alisabryant** [semgrep/semgrep#8436]
**Describe the bug**
In the dashboard, it took me to this link https://legacy.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml when it should have pointed me to this link
https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html

**To Reproduce**
Scan a repository with a finding related to Dangerously setting the inner HTML, and you'll notice that it provides an outdated link. 

**Expected behavior**
I would have expected to be taken to the most up-to-date link. When clicking the current link, it takes me to a help repository that has been outdated since March 2023 (not that long, but still outdated, nevertheless)

**Screenshots**
![image](https://github.com/returntocorp/semgrep/assets/65581330/e994f68b-a0ed-4923-9f99-c2d1d9ce76f4)

![image](https://github.com/returntocorp/semgrep/assets/65581330/4ecacd16-632f-4516-95da-bc4ad448457f)

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Local build

**Use case**
It will enable me better trust and confidence in the product that the information is up to date and valid. By being directed to an outdated help page for a coding language, I feel as though I might be missing important and relevant information. Secondly, it will enable me less clicks and as a user, I feel as though that is important because I might not take the time to do the extra clicks in the future. Also, once I did the extra clicks (clicking on the link at the top of the react page, then searching for the same term, then getting taken to an overall information page, then getting to the similar page relevant to the outdated information) I was presented with better information than the outdated information that was a better user experience because it was laid out different and provided different examples that were more intuitive.

**Comment by IagoAbal** [comment]
cc @p4p3r this seems like something to fix in semgrep-rules ?
