### ISSUE TITLE
Brew SHA256 Mismatch

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#844]
**Describe the bug**
I ran `brew install returntocorp/semgrep/semgrep` on a machine with no prior semgrep installation. Brew reports a SHA256 mismatch.

I tried the installation twice, removing the semgrep tar file inbetween.

```
Error: SHA256 mismatch
Expected: 9a004d1246b0b969a893fd571e548ecfbdab752f3535abe4c6b02ca201ad8f4a
  Actual: ee2235597de4396d01c016db111f1682abe7b44dbf79c387b93f4c5d000910c8
 Archive: /Users/luke/Library/Caches/Homebrew/downloads/c365e41a54d57e161c95c8a86fe7bc223036764ba8119cb13d79e2c258703567--semgrep-0.8.1.tar.gz
To retry an incomplete download, remove the file above.
```

**To Reproduce**
`brew install returntocorp/semgrep/semgrep`

**Comment by dlukeomalley** [comment]
@brendongo @rcoh Any thoughts here? Is this a "me" problem? :)

**Comment by rcoh** [comment]
It's not a you problem it reproduces for me. @brendongo we need to get the CI job on a cron to catch this.

**Comment by brendongo** [comment]
I just reran it and I don't get a sha mismatch?

**Comment by brendongo** [comment]
Why does the shasum change?

**Comment by brendongo** [comment]
Fixed https://github.com/returntocorp/homebrew-semgrep/commit/0663f7874d64aa9279bd595784ca615f89d1f86d
