### ISSUE TITLE
Don't throw an error when no config file

### ISSUE THREAD

**Issue by Zeioth** [semgrep/semgrep#8497]
**Is your feature request related to a problem? Please describe.**
Yes. I use semgrep through null-ls on neovim. Every time I open a file I get an error notification because there is no semgrep config file, even though it works correctly.

**Describe the solution you'd like**
Display the message as `info`, not as an `error`.

**Describe alternatives you've considered**
Or just don't show it at all.

**Use case**
Using semgrep on neovim without errors.

**Additional context**
![screenshot_2023-08-19_07-19-29_426211758](https://github.com/returntocorp/semgrep/assets/3357792/5b04bc70-cdad-4609-a633-72f361104a92)

**Comment by Zeioth** [comment]
In the meantime, pasting this into my `~/.semgrep/settings.yml` stops the notification.
https://github.com/returntocorp/semgrep/blob/develop/semgrep.yml

But this is not a final solution: We'd like [our users](https://github.com/NormalNvim/NormalNvim) to not have to manualy setup semgrep.

**Comment by ievans** [comment]
@aryx did your work to remove ~/.semgrep affect this?

**Comment by aryx** [comment]
maybe. @Zeioth can you reproduce the issue with semgrep 1.38.3?

**Comment by Zeioth** [comment]
Still showing error I think? 

![screenshot_2023-09-07_17-26-32_825493695](https://github.com/returntocorp/semgrep/assets/3357792/43b79e95-2a1a-411b-883a-40da061da1d2)

I run it from the source tar.gz because in arch linux we are still on v1.28 (`semgrep-bin` from AUR)

I removed .semgrep before testing this.

**Comment by adamboros** [comment]
#8562 changed this error to a help message which should resolve this. I'm gonna close this ticket, but if the issue persist in the latest version, please reopen the ticket.
