### ISSUE TITLE
javascript ... overly greedy

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#856]
For the pattern:

```
Object.defineProperty(..., {
  get: function (){
    ...
     return ...;
   }
});
```
doesn't match:

```

Object.defineProperty(p, "age", {
    get: function (){
        // no returns.
        return "foo"
    }
});
```

However, removing the ... on line #3 of the pattern does work. See broken example at https://semgrep.live/OrlB

**Comment by nbrahms** [comment]
Hi @ievans . Thanks for the bug report. FYI this appears to be a duplicate of #443 . I'm going to close it as such. Please respond and reopen with a comment if I misunderstand this ticket.
