### ISSUE TITLE
The semgrep scan no longer allows the use of --output flag in v1.38.0

### ISSUE THREAD

**Issue by jamie-bousfield-ea** [semgrep/semgrep#8602]
**Describe the bug**
When using the semgrep scan cli with the --output flag the following error message is generated:
`semgrep scan: unknown option '--output'.`

**To Reproduce**
1. Pull  returntocorp/semgrep:1.38
2. Run the container and mount the volume. 
3. Run `semgrep --config=auto --verbose --sarif --output=semgrep.sarif /{mounted_volume}`
5. Error message is reported `semgrep scan: unknown option '--output'.`

**Expected behavior**
In V1.37 this works correctly and produces the sarif output file

**What is the priority of the bug to you?**
* We have rolled back to v1.37.0

- [] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
Using the docker container provided by `returntocorp/semgrep`

**Comment by jacky9813** [comment]
+1 here.

Also provides more information here.

I tested with `--legacy` flag in 1.38.0 and it returned to how previous version behaves.

Still, missing `--output` option is quite a good reason to not use new interface.

**Comment by aryx** [comment]
Ok will fix today.

**Comment by aryx** [comment]
Just curious though @jamie-bousfield-ea and @jacky9813 why you use this feature (I never used it). Can't you just use shell redirection to redirect the output of semgrep to a file?

**Comment by fcanogab** [comment]
@aryx I use --

> Just curious though @jamie-bousfield-ea and @jacky9813 why you use this feature (I never used it). Can't you just use shell redirection to redirect the output of semgrep to a file?

I use this feature because I execute semgrep within Python and I don't like to use redirections within scripts if there is an option available. I guess it's a matter of personal preference.

**Comment by aryx** [comment]
How are you calling semgrep from Python? Via exec or via the semgrep python modules?

**Comment by aryx** [comment]
(asking because the python modules will disappear gradually, so better to call semgrep via exec/fork rather than those unofficial Python API)

**Comment by fcanogab** [comment]
@aryx calling it with subprocess. Not sure if it is the best way.

**Comment by aryx** [comment]
perfect, that's the best and more stable way from Python

**Comment by ben-manes** [comment]
This feature is used by your GitHub actions documentation. That’s how it [failed](https://github.com/ben-manes/caffeine/actions/runs/6046555113/job/16422133742) for me.

**Comment by aryx** [comment]
1.38.1 is now released, with the fix
