### ISSUE TITLE
1.38 scan option missing --output

### ISSUE THREAD

**Issue by agmcleod** [semgrep/semgrep#8606]
**Describe the bug**
Our CI utilizing 1.37 had no issues, however since utilizing 1.38 our builds started to fail.

**To Reproduce**
Here's the command our CI is running:

```
/home/runner/.local/bin/semgrep --metrics=off --no-rewrite-rule-ids --include=README.md --include=path/to/changed/file.rb --json --output=semgrep-report.json --config=/home/runner/.wealthsimple-semgrep/ws/ /home/runner/work/app
```

Here's the error we receive:

```
semgrep scan: unknown option '--output'.
Usage: semgrep scan [OPTION]… [TARGETS]…
```

**Expected behavior**
Ideally it should run without errors and report if there are any findings

**Screenshots**

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
We install it through pip in Github Actions

**Use case**
We locked our CI step to install 1.37 rather than latest, but will be stuck here until it is fixed.

**Comment by bradleybonitatibus** [comment]
Seeing this issue in our CI as well using 1.38.

**Comment by rodrigoprimo** [comment]
Another option that is missing on 1.38: https://github.com/returntocorp/semgrep/issues/8610. I'm not sure if there is a relation between those two issues or not.

**Comment by aryx** [comment]
1.38.1 fix the --output issue

**Comment by aryx** [comment]
Note that you can also use shell redirection instead of --output
