### ISSUE TITLE
semgrep.live scan shows error when Python rules run on Go project

### ISSUE THREAD

**Issue by danmx** [semgrep/semgrep#864]
https://semgrep.live/scan/4d0005e0-7126-4a39-9072-74d726dbe370

**Comment by dlukeomalley** [comment]
@danmx, anything you'd like us to investigate with the above scan error?

**Comment by danmx** [comment]
@dlukeomalley I was using Python rules for Go. Maybe instead throwing an error you could print something else that would speed up finding the error 😄

**Comment by dlukeomalley** [comment]
I love that idea. I'm going to re-open this and get the team's input. Thank you @danmx!

**Comment by ievans** [comment]
Closing as the /scan page has been deprecated for a while now
