### ISSUE TITLE
min-version/max-version mismatch should skip a rule with unknown fields

### ISSUE THREAD

**Issue by mjambon** [semgrep/semgrep#8648]
**Describe the bug**

```
$ cat version-new-field.yml 
rules:
 - id: hello
   min-version: 99.0.0
   foo: bar
   pattern: "hello"
   languages: [apex]
   message: "found hello"
   severity: ERROR
```

should skip the rule due to the version constraint. It should not complain about field foo being unknown. This is the current behavior:

```
$ semgrep -c version-new-field.yml toto.cls
semgrep error: Invalid rule schema
  --> version-new-field.yml:2
2 |  - id: hello
3 |    max-version: 0.0.0
4 |    foo: bar
5 |    pattern: "hello"
6 |    languages: [apex]
7 |    message: "found hello"
8 |    severity: ERROR

Additional properties are not allowed ('foo' was unexpected)

[ERROR] invalid configuration file found (1 configs were invalid)
```

**Expected behavior**

Skip the rule with only an info-level error.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

any

**Use case**

Don't fail on rules that use a new field.

**Comment by mjambon** [comment]
I believe this is due to a schema-based validation done in Python before the version check is done, in OCaml. I also believe OCaml does such validation anyway. If that's the case, we can hopefully just remove the validation on the Python side.

**Comment by brendongo** [comment]
@mjambon does ocaml validation print out a nice error message like python side validation? If so we can switch over

**Comment by brendongo** [comment]
Alternatively we can also just adjust the schema to allow for additional/unexpected fields

**Comment by mjambon** [comment]
good suggestions, @brendongo.

**Comment by mjambon** [comment]
to-do list:
* check that the validation on the OCaml side prints the same/nice error messages as in pysemgrep (should be/be added to the osemgrep roadmap if not already done)
* relax the schema used by pysemgrep to allow unknown fields: https://github.com/returntocorp/semgrep-interfaces/pull/129
* consider an option `--strict-rules` that would allow unknown fields in semgrep-core/osemgrep by default (not sure about it; create a ticket for it)
