### ISSUE TITLE
Document all "unspecified match more" metavariable nodes

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#868]
**Is your feature request related to a problem? Please describe.**
Metavariables bound to certain AST nodes will match a large variety of code AST nodes.

For example:

```java
class $CLAZZ {
}
```

will match `MyClass extends AParentClass` in Java.

However, I don't know which metavariable binding sites have this behavior, and which do not, by reading the documentation in `/docs/`.

**Describe the solution you'd like**
Add documentation, discoverable from the README, that documents this behavior, and which binding sites are affected.

**Comment by mschwager** [comment]
Per an internal conversation, we came to the conclusion that these are the "unspecified match more" features:

```
$ fd 'less_.*.sgrep'
semgrep-core/tests/java/less_inheritance.sgrep
semgrep-core/tests/js/less_class_complex.sgrep
semgrep-core/tests/js/less_class_complex_2.sgrep
semgrep-core/tests/js/less_inheritance.sgrep
semgrep-core/tests/js/less_xml_attr.sgrep
semgrep-core/tests/js/less_xml_body.sgrep
semgrep-core/tests/python/less_attributes.sgrep
semgrep-core/tests/python/less_inherits.sgrep
semgrep-core/tests/python/less_typehint.sgrep
```

**Comment by nbrahms** [comment]
@mschwager @aryx It seems like there should be something for Java annotations in addition to this list, correct?
