### ISSUE TITLE
--dump-ast flag not working

### ISSUE THREAD

**Issue by pattersonz** [semgrep/semgrep#8700]
When using the command
$semgrep --lang java --dump-ast test.java

I get the following:
Usage: semgrep --lang [OPTIONS] [TARGETS]...

Error: No such option: --dump-ast Did you mean --dump-engine-path?

This should be printing out the ast, I know this works with prior versions of semgrep/ on other machines

Semgrep version: 1.39.0 (installed through brew)
Machine: Macbook Pro
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 16 GB 2667 MHz DDR4

**Comment by aryx** [comment]
Did you try 1.40.0?  I think it's fixed in 1.40.0

**Comment by pattersonz** [comment]
1.40 does indeed fix it.
