### ISSUE TITLE
java parser spews output to stderr, should be hidden/fixed

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#873]
When parsing echelon-backend, as observed in @dlukeomalley run this am: 

ine@imbp4 ~/D/r/echelon-backend (develop)> semgrep --config=https://semgrep.live/c/p/java
scanning code...
depth_angle < 0, -1
Tag17 ([((" ", 14047, 408, 51, "./analysis/analyzers/r2c/synode/external/test/com/google/javascript/jscomp/TemplatesMinner.java"))])

I believe this comes from:
https://github.com/facebookarchive/pfff/blob/ec21095ab7d445559576513a63314e794378c367/lang_java/parsing/parsing_hacks_java.ml#L40

**Comment by mschwager** [comment]
Similar, or same as #927?

**Comment by ievans** [comment]
Different code paths (one is Java, the other Javascript) AFAICT
