### ISSUE TITLE
Matching PDO methods with semgrep

### ISSUE THREAD

**Issue by CaledoniaProject** [semgrep/semgrep#8741]
I want to match the PHP code with semgrep

```
$pdo = new PDO($dsn, $user, $pass, $driver_options);
$pdo->exec($args);
```

I could write rule to match `$pdo->exec`, but how can I also ensure $pdo is an instance of PDO class, not AnotherClassThatIsNotPDO?

**Comment by nmote** [comment]
For support requests, please visit our community slack
