### ISSUE TITLE
Can't match dynamic method call with semgrep

### ISSUE THREAD

**Issue by CaledoniaProject** [semgrep/semgrep#8743]
Take the following PHP code snippets for example,

```
$a = 'php';
$b = 'info';
$c = $a.$b;
$c();
```

Does semgrep support evaluating the `$c` value and match the call to `phpinfo();`?

**Comment by nmote** [comment]
Most likely not, but feel free to ask about this in the community slack. In the future please follow the new issue template when opening an issue here.
