### ISSUE TITLE
Port Bento results display to Semgrep

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#879]
Specifically:
- [ ] ~~Progress bar output~~ (Excluded after Semgrep workflow discussion)
- [ ] Clippy formatting
- [ ] Clear stderr vs. stdout segregation
- [ ] ~~Some pager support?~~ (optional) (Excluded after Semgrep workflow discussion)

**Comment by nbrahms** [comment]
**Motivation**

Current ripgrep- and json-style formatters can be confusing for check-pack user personas. We've learned how users like to consume findings data from our experience with Bento. Let's use those findings as a starting point for further development.

**Spec**

1. **Only result output should go to stdout** -- this should be true regardless of format

2. **Add Bento-style Clippy formatter** -- This should be cribbed directly IMO, including dedenting and color formatting

3. **Add `-f/--format` option** -- Formats should be `rg` for current default ripgrep-style output, `json` for JSON output, `clippy` for Clippy-style. `--json` should be deprecated in favor of `--format json`

4. **JSON output should not have a trailing newline** -- For ease of integration

**Comment by nbrahms** [comment]
cc. @brendongo @dlukeomalley

**Comment by ievans** [comment]
IMO `--json` is intuitive and useful for CLI workflows to have it as a top level flag rather than `--format=json`. Basically because users are lazy. This is what ripgrep does, for instance. 

What's the impetus for porting the bento-style clippy formatter? Why should we have more than one formatter? Maybe we could pull bento data to see if anyone ever used the non-default formatter.

**Comment by dlukeomalley** [comment]
For reference, `rg` output below:

```sh
Downloads/1314-48051-223246.ics
146:    .wrapper .red-footer ul li h5 {
497:    .wrapper .red-footer ul li h5 {
710:    .wrapper .red-footer ul li h5 {
923:    .wrapper .red-footer ul li h5 {
1136:    .wrapper .red-footer ul li h5 {
1349:    .wrapper .red-footer ul li h5 {
1562:    .wrapper .red-footer ul li h5 {
1775:    .wrapper .red-footer ul li h5 {

Downloads/1314-48051-223246 (1).ics
146:    .wrapper .red-footer ul li h5 {
497:    .wrapper .red-footer ul li h5 {
710:    .wrapper .red-footer ul li h5 {
923:    .wrapper .red-footer ul li h5 {
1136:    .wrapper .red-footer ul li h5 {
1349:    .wrapper .red-footer ul li h5 {
1562:    .wrapper .red-footer ul li h5 {
1775:    .wrapper .red-footer ul li h5 {
```

![image](https://user-images.githubusercontent.com/605906/83668289-8c84c900-a584-11ea-8f23-28a84ae2a04d.png)

Would we augment this @ievans @nbrahms to include file and check-id, excluding message or extra fields? The goal is to make it feel "light" and I worry all of the other fields we use work against us there.

Strawman, noting that I don't know how the tool runs and if it's possible to quickly group file and or check-id output:

```sh
python.lang.security.secure-set-cookie:
     Downloads/1314-48051-223246.ics:
          146:     .wrapper .red-footer ul li h5 {
          497:     .wrapper .red-footer ul li h5 {
          710:     .wrapper .red-footer ul li h5 {
          923:     .wrapper .red-footer ul li h5 {
          1136:    .wrapper .red-footer ul li h5 {
          1349:    .wrapper .red-footer ul li h5 {
          1562:    .wrapper .red-footer ul li h5 {
          1775:    .wrapper .red-footer ul li h5 {
```

**Comment by dlukeomalley** [comment]
I'll note that this format seems challenging in a CI setting, but I do accept the point that people haven't run it in CI yet beyond our team.

**Comment by dlukeomalley** [comment]
Per discussion in standup, closing this ticket in favor of a downscoped modification of existing Semgrep output.
