### ISSUE TITLE
osemgrep: `String.rindex_from` raising `Invalid_argument`

### ISSUE THREAD

**Issue by IagoAbal** [semgrep/semgrep#8792]
**Describe the bug**

I was debugging and left some `logger#flash` or something around. When I was committing, I got an `Invalid_argument` exception in this function:

File src/osemgrep/Matches_report.ml:
```ocaml
let wrap ~indent ~width s =
  let pre = String.make indent ' ' in
  let rec go indent width pre s acc =
    let real_width = width - indent in
    if String.length s <= real_width then List.rev ((pre, s) :: acc)
    else
      let cut =
        let prev_ws =
          try String.rindex_from s real_width ' ' with
          | Not_found -> 0
        and prev_dash =
          try 1 + String.rindex_from s real_width '-' with
          | Not_found -> 0
        in
        let m = max prev_ws prev_dash in
        if m = 0 then real_width else m
      in
 ...
```

I think it's worthwhile double-checking that `real_width` here is always within bounds.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

**Comment by aryx** [comment]
Full backtrace in CI: 
```

┌─────────────────┐
│ 2 Code Findings │
└─────────────────┘

    js/tests/Test_jsoo.ml 
Error: exception Invalid_argument: String.rindex_from / Bytes.rindex_from
Raised at Stdlib.invalid_arg in file "stdlib.ml", line 30, characters 20-45
Called from Matches_report.wrap.go in file "src/osemgrep/reporting/Matches_report.ml", line 96, characters 14-49
Called from Matches_report.pp_text_outputs.print_one in file "src/osemgrep/reporting/Matches_report.ml", line 248, characters 8-55
Called from Matches_report.pp_text_outputs.(fun) in file "src/osemgrep/reporting/Matches_report.ml", line 272, characters 23-51
Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
Called from Matches_report.pp_text_outputs in file "src/osemgrep/reporting/Matches_report.ml", line 267, characters 4-241
Called from Stdlib__List.iter in file "list.ml", line 110, characters 12-15
Called from Output.output_result in file "src/osemgrep/cli_scan/Output.ml", line 209, characters 2-59
Called from Scan_subcommand.run_scan_files in file "src/osemgrep/cli_scan/Scan_subcommand.ml", line 471, characters 6-67
Called from Scan_subcommand.run_scan_conf in file "src/osemgrep/cli_scan/Scan_subcommand.ml", line 579, characters 4-70
Called from CLI.dispatch_subcommand in file "src/osemgrep/cli/CLI.ml", line 194, characters 20-52
Called from CLI.safe_run in file "src/osemgrep/cli/CLI.ml", line 225, characters 8-12

Error: fatal error
```

**Comment by aryx** [comment]
full trace: https://github.com/returntocorp/semgrep/actions/runs/6553837587/job/17799850589?pr=9033

**Comment by aryx** [comment]
Here is the code of rindex_from: 
```
let rindex_from s i c =
  if i < -1 || i >= length s then
    invalid_arg "String.rindex_from / Bytes.rindex_from"
  else
    rindex_rec s i c
```

**Comment by aryx** [comment]
@IagoAbal the call to rindex_from is in the else branch of this test: `String.length s <= real_width`
so that means in the else branch we have `string.length s > real_width`, so I don't see how we can raise invalid_arg ...

**Comment by hannesm** [comment]
AFAICT the `let real_width = width - indent` can be a negative number, i.e. there's nothing ensuring that there's at least some space to print something. Now, in the backtrace and code, `indent` is passed as `7`, and width is unknown (CI system).

**Comment by aryx** [comment]
Yes, that must be it.
I've tried with an xterm with less than 8columns and got some issues
