### ISSUE TITLE
Offline execution

### ISSUE THREAD

**Issue by brynary** [semgrep/semgrep#8793]
**Describe the bug**
When running `semgrep scan --metrics=off --config .semgrep.yaml`, Semgrep seems to be making network calls.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

1. Disable networking
2. Run `semgrep scan --metrics=off --config .semgrep.yaml`
3. The runtime increases massively relative to when running the same command with networking enabled (a few seconds vs almost one minute)

**Expected behavior**
Given that metrics are off, and I am providing a local `.semgrep.yaml` file, I would expect that Semgrep would not need to access the network. (Or, that there would be an option to disable that.)

Is it possibly doing a latest version check, or accessing the registry for some reason?

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Within Docker.

**Use case**
Running Semgrep while networking is disabled.

**Comment by ievans** [comment]
yes, Semgrep checks to see whether it's running the latest version (we only support a few versions back typically on semgrep.dev):
```
$ semgrep --help
...
       --disable-version-check
           negates --enable-version-check
```

**Comment by brynary** [comment]
@ievans thanks!

Am I understanding correctly that in the case where `--config FILE` is specified, no connection to semgrep.dev is necessary?

If so, would it make sense to automatically disable the version check when run with `--config FILE` to speed up execution?

**Comment by melsabagh** [comment]
@ievans I can reproduce this on the latest Semgrep. Running `semgrep --disable-version-check --metrics off --validate --config test.yaml` while offline fails with `Failed to download config from https://semgrep.dev/c/p/semgrep-rule-lints: ...`

**Comment by melsabagh** [comment]
OK, looks like this `--validate` behavior has been already reported here: https://github.com/semgrep/semgrep/issues/4620.
