### ISSUE TITLE
Consider display the scan result in real-time which is convenient for rule-debugging.

### ISSUE THREAD

**Issue by w3-9** [semgrep/semgrep#8877]
**Is your feature request related to a problem? Please describe.**
When scanning large projects, we could wait for 30-40 mins for a single rule which is cumbersome.

**Describe the solution you'd like**
Display the scan result in real time which is perfect for rule-debugging.

**Describe alternatives you've considered**
When the hit hits 1000/500/200, display the result onto the screen.

**Use case**
Rule Debugging.

**Additional context**
None

**Comment by aryx** [comment]
You can get this behavior by using the --develop flag.
It switches to the bleeding-edge semgrep that offers incremental display of findings, but there are lots
of small differences with regular semgrep regarding file targeting and ignoring files which is why it's not yet the default.

**Comment by w3-9** [comment]
Thanks!
