### ISSUE TITLE
Rust parser does not properly handle token trees within macros

### ISSUE THREAD

**Issue by fcasal** [semgrep/semgrep#8884]
**Describe the bug**
In Rust code, the `matches!($X, ...)` Semgrep pattern does not find instances of `matches!(foo, Foo::A(_))`

**To Reproduce**
Playground example with tests https://semgrep.dev/playground/s/DPrP?editorMode=advanced

**Expected behavior**
The Rust parser properly handles macros and finds and matches all instances.

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Comment by aryx** [comment]
I thought you fixed that @brandonspark ?

**Comment by brandonspark** [comment]
@aryx I fixed it for very select cases, but a full fix would require essentially re-implementing the Rust parser. Although, actually, I have an idea. Let me get back to you.
