### ISSUE TITLE
python.aws-lambda.security.dangerous-subprocess-use.dangerous-sub remediation not accurate

### ISSUE THREAD

**Issue by svbfromnl** [semgrep/semgrep#8963]
**Describe the bug**
The remedy for the test described in this rule link (https://sg.run/XZ7B) is not accurate. Python shlex does not have an escape() method, even back in Python2. Please update the rule and provide a new remediation tactic for tainted event objects.

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Local semgrep 1.43.0 binary install on MacOS and use in pre-commit gitlab pipeline.

**Use case**
Will be able to use semgrep in Lambda code pipeline

**Comment by aryx** [comment]
cc @0xDC0DE maybe can update the rule?

**Comment by aryx** [comment]
Probably better to report such issues on the semgrep-rules repository instead. This is more for bugs in the semgrep engine itself (not the rules).

**Comment by aryx** [comment]
Probably better to report such issues on the semgrep-rules repository instead. This is more for bugs in the semgrep engine itself (not the rules).

**Comment by svbfromnl** [comment]
@aryx do you want me to close this one and reopen another issue in that repo?

**Comment by aryx** [comment]
Yes thx!

**Comment by svbfromnl** [comment]
Recreated here: https://github.com/returntocorp/semgrep-rules/issues/3162
Closing this issue.
