### ISSUE TITLE
Do not limit urllib3 to 1.26.x

### ISSUE THREAD

**Issue by matejsp** [semgrep/semgrep#9006]
**Is your feature request related to a problem? Please describe.**
We want to upgrade to latest urllib3 but are restricted because of semgrep.
Current version is 2.0.6 and should be compatible (except for bumped minumum openssl to 3).

**Describe the solution you'd like**
Supoort for urllib3 2.x.x

**Describe alternatives you've considered**
/

**Use case**
https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html
Upgrade to latest version.

**Additional context**
```
The first step to supporting urllib3 v2.0 is to make sure the version v2.x not being excluded by install_requires. You should ensure your package allows for both urllib3 1.26.x and 2.0 to be used:
```

**Comment by drewler** [comment]
@aryx I think this one can be closed (solved by https://github.com/semgrep/semgrep/pull/9428).
