### ISSUE TITLE
Reduced performance for complex rules since v1.42.0

### ISSUE THREAD

**Issue by craigmarksmith** [semgrep/semgrep#9034]
**Describe the bug**

I'm seeing a reduction in performance since v1.42.0 for a particularly complex rule I'm running. The change looks to have been introduced in https://github.com/returntocorp/semgrep/commit/84464131d659c174b1a66f3191de1870eecf5f8b

@emjin @aryx I hope you don't mind me tagging you both. I've done so as the [PR](https://github.com/returntocorp/semgrep/pull/8787) is linked to both of your names.

**To Reproduce**

clone a repository to run the scan against. I've been using [gradle](https://github.com/gradle/gradle/tree/master/subprojects/core/src/main/java/org/gradle)

```
git clone https://github.com/gradle/gradle/tree/master/subprojects/core/src/main/java/org/gradle
```

Create a complex Java rule. I'm using [this one in the semgrep playground](https://semgrep.dev/playground/s/0zPj)

Run semgrep against the gradle repo, only importing that rule. 

```
docker run -it --rm -v /PATH/TO/RULES:/rules -v /PATH/TO/GRADLE:/src returntocorp/semgrep:sha-844613-nonroot semgrep -f /rules --debug
```

This takes ~50 seconds to run, but running on the previous commit takes 3 seconds.

```
docker run -it --rm -v /PATH/TO/RULES:/rules -v /PATH/TO/GRADLE:/src returntocorp/semgrep:sha-0eac396-nonroot semgrep -f /rules --debug
```

**Expected behavior**

The latest version of semgrep  should run the above scan in ~3 seconds

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

docker

**Use case**
What will fixing this bug enable for you?

I'll be able to upgrade semgrep. I'm currently stuck at v1.41.0

**Comment by emjin** [comment]
Wow, this is amazing! We've just fixed this via https://github.com/returntocorp/semgrep/pull/9010 (to be released soon), but thank you so much for doing the work to find the bug in this report!

**Comment by craigmarksmith** [comment]
Thanks so much for this @emjin. I've just checked that `sha-5dd2349-nonroot` and it's working great. Thank you again 🙇 
I've gone ahead and closed this issue.

**Comment by aryx** [comment]
@emjin do we have an issue tracking the slowness of analyze_rule? Maybe we could take this playground example as a test case?

**Comment by emjin** [comment]
I have it on my radar for this week, but made one so we don't lose track of it https://github.com/returntocorp/semgrep/issues/9040
