### ISSUE TITLE
Investigate speed of prefilter computation

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#9040]
For some rules, especially kotlin.ktor.nosqli.ktor-mongo-java-driver.ktor-mongo-java-driver and kotlin.spring.mongo-driver-nosqli.mongo-driver-nosqli, prefilter computation can take a long time and the limits set are quite generous. The effect is not too bad, because prefilters are cached, but we should see if we can speed this up.

**Comment by emjin** [comment]
See also #9034 for an example of a rule that triggers this

**Comment by aryx** [comment]
thx!
