### ISSUE TITLE
Java parse error

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#905]
This Java pattern fails to parse (observed in an Eclipse project):
```
if (key == IShowInTargetList.class) {
			return (T) (IShowInTargetList) () -> new String[] { JavaUI.ID_PACKAGES, IPageLayout.ID_PROJECT_EXPLORER };
		}
```
reproduction: https://semgrep.live/kxWX

**Comment by ievans** [comment]
actually, it's possible this is the same error as #906

**Comment by nbrahms** [comment]
This looks to be a duplicate issue with #906. Since we've started work on that issue, I'll close this one in it's favor.

Please reopen with a comment if this closure is an error.
