### ISSUE TITLE
Metavariable's range of multi-line string in yaml is incorrect.

### ISSUE THREAD

**Issue by Isaac0616** [semgrep/semgrep#9082]
**Describe the bug**
Comparing to the entire matched pattern, when a metavariable matches a multi-line string in yaml, it will match a trailing new-line character and the ending line number will be increased by one, even if it is out of the range of the file. 

**To Reproduce**
semgrep.dev won't show the ending line, so here is the example.
rule:
```yaml
rules:
- id: yaml-multiline
  patterns:
    - pattern: |
        test:
          policy: $POLICY
  message: test
  languages: [yaml]
  severity: WARNING
```
file:
```yaml
test:
  policy: |
    line1
    line2
```
result:
```json
{
  "errors": [],
  "paths": {
    "scanned": [
      "aws.yml"
    ]
  },
  "results": [
    {
      "check_id": "yaml-multiline",
      "end": {
        "col": 11,
        "line": 4,
        "offset": 38
      },
      "extra": {
        "engine_kind": "OSS",
        "fingerprint": "d390cbf4d8968768d47be00a4846dbd426cd79ad749f5e867cec691fa75f7187cc9946c0a57ee9e56a30cf2b148d2c26fd3bb7ef6a1faf18ff6a26f5db14c5c9_0",
        "is_ignored": false,
        "lines": "test:\n  policy: |\n    line1\n    line2",
        "message": "test",
        "metadata": {},
        "metavars": {
          "$POLICY": {
            "abstract_content": "\n    line1\n    line2\n",
            "end": {
              "col": 1,
              "line": 5,
              "offset": 38
            },
            "start": {
              "col": 12,
              "line": 2,
              "offset": 17
            }
          }
        },
        "severity": "WARNING",
        "validation_state": "NO_VALIDATOR"
      },
      "path": "aws.yml",
      "start": {
        "col": 1,
        "line": 1,
        "offset": 0
      }
    }
  ],
  "skipped_rules": [],
  "version": "1.46.0"
}
```
Noted that the top level `end` is 
```
{
  "col": 11,
  "line": 4,
  "offset": 38
}
```
but the `end` of `$POLICY` is
```
{
  "col": 1,
  "line": 5,
  "offset": 38
}
```
The issue is exacerbated when combining with `focus-metavariable` and could result in flagging something outside of the range of a file.

**Expected behavior**
The range of a metavariable of a multi-line string in yaml should be consistent with the the normal pattern. 

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Official binary (version: 1.46.0)

**Use case**
Correctly flag findings for yaml files.

**Comment by nmote** [comment]
Closing as I believe this was addressed in #9104
