### ISSUE TITLE
Metavariable syntax is misinterpreted on bash command line

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#909]
The `$X` syntax isn't command line friendly and requires escaping. I expected semgrep to be optimized for the command line and `-e` and was surprised that its syntax required escaping. I'm able to adapt and include `\`, but know I'll make this mistake again in the future.

```sh
$ semgrep -e "$X.set_cookie(...)" -l py
invalid pattern ".set_cookie(...)": Parsing.Parse_error
```
Instead:

```sh
$ semgrep -e "\$X.set_cookie(...)" -l py
zerver/middleware.py
475:                        response.set_cookie(
476:                            settings.SESSION_COOKIE_NAME,
477:                            request.session.session_key, max_age=max_age,
478:                            expires=expires, domain=session_cookie_domain,
479:                            path=settings.SESSION_COOKIE_PATH,
480:                            secure=settings.SESSION_COOKIE_SECURE or None,
481:                            httponly=settings.SESSION_COOKIE_HTTPONLY or None,
482:                            samesite=settings.SESSION_COOKIE_SAMESITE,
```

Preferably the Semgrep pattern syntax would be able to run on the command line without modification or special escape characters.

**Comment by mschwager** [comment]
Single quotes here also solve the problem: `'$X.set_cookie(...)'`

https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash

Oh the joys of bash :)

**Comment by nbrahms** [comment]
I'm going to go ahead and close this. Single quotes solve this issue, and we're unlikely to change this API due to its widespread use.

Please reopen if you have follow up :)
