### ISSUE TITLE
Inline if statements not matched if the pattern includes braces

### ISSUE THREAD

**Issue by emjin** [semgrep/semgrep#910]
**Describe the bug**
(Potentially not a bug, but was surprising behavior.) A pattern using an if statement without braces does not match inline if statements

**To Reproduce**
https://semgrep.live/v8ZX
Note that both are caught without the braces: https://semgrep.live/d87P

**Expected behavior**
Expected both if statements to match

**Comment by ievans** [comment]
Looks like the latter, inline `if` doesn't have a "Block" wrapper. @DrewDennison it's so easy to see the ASTs on semgrep.live!

![Screen Shot 2020-06-03 at 3 55 16 PM](https://user-images.githubusercontent.com/409041/83696980-a5a46e80-a5b2-11ea-9ff9-2ccc797392d5.png)

**Comment by mschwager** [comment]
Both of @emjin's examples work now!
