### ISSUE TITLE
DockerHub image returntocorp/semgrep:latest tag pointing to 1.46.0

### ISSUE THREAD

**Issue by pog-charlesinglese** [semgrep/semgrep#9164]
**Describe the bug**
On DockerHub, the [returntocorp/semgrep:latest](https://hub.docker.com/layers/returntocorp/semgrep/latest/images/sha256-ff93a38e78dbaa03c97c48f95bcf2ab4512256eb336fc3e8c92c8d002bbfc059?context=explore) is still pointing to `DIGEST:sha256:ff93a38e78dbaa03c97c48f95bcf2ab4512256eb336fc3e8c92c8d002bbfc059`, even though [v1.47.0](https://github.com/semgrep/semgrep/releases/tag/v1.47.0) was released on 1-NOV-23

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
* Navigate to DockerHub [returntocorp/semgrep](https://hub.docker.com/r/returntocorp/semgrep)
* Search for latest in Tags
* Compare the SHA256 digest between `latest` and `1.47.0`

**Expected behavior**
`latest` should point to `1.47.0`

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
Docker

**Use case**
What will fixing this bug enable for you?
Allow for using the `latest` tag in our CI/CD pipeline again, since v1.46.0 broke the sarif output feature, reference [Issue 9091](https://github.com/semgrep/semgrep/issues/9091)

**Comment by pog-charlesinglese** [comment]
@nmote, @aryx - It looks like the CI/CD pipeline isn't tagging the release images with `latest`:
- https://github.com/semgrep/semgrep/actions/runs/6773937531/job/18410757486#step:6:351
- https://github.com/semgrep/semgrep/actions/runs/6773539951/job/18408788908#step:6:291

**Comment by nmote** [comment]
We had some issues with the 1.47 release. I just released 1.48 and we'll be updating `latest` to 1.48 shortly.

**Comment by nmote** [comment]
Feel free to use the `canary` tag, by the way, if you'd like 1.48 now.

**Comment by pog-charlesinglese** [comment]
Doesn't the `canary` tag get promoted to `latest` after a successful test workflow? I'd rather pull the verified/validated/tested `latest` image rather than the `canary`, especially since the current `latest` tagged image is also not working as expected.

- https://github.com/semgrep/semgrep/blob/develop/.github/workflows/release.yml#L96
- https://github.com/semgrep/semgrep/blob/develop/.github/workflows/set-semgrep-docker-tag.yml

**Comment by nmote** [comment]
It's a new process, but my understanding is that we manually promote `canary` to `latest` after a couple of days.

**Comment by harmw** [comment]
so we'll just have to wait for someone to run the manual promotion to `latest`? since https://hub.docker.com/r/returntocorp/semgrep/tags?page=1&name=latest is not updated yet 😅 (`canary` is though)

**Comment by aryx** [comment]
Yes, like Nat said we should promote to latest tomorrow. If you want to live on the edge you can use the :canary tag though :)
