### ISSUE TITLE
Don't require "$" for variable names in pattern-where-python vars array

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#917]
I was surprised that `$` was required to access variables within `pattern-where-python`. `$` feels like a special character in our syntax to denote a variable, but it doesn't feel part of the variable name. For example, `$FNAME` is the variable named `FNAME`.

![image](https://user-images.githubusercontent.com/605906/83802693-12c20d80-a660-11ea-9ca4-dd5a70576cf2.png)

Proposal: strip `$` from the vars array and variable name in `patter-where-python` and our ast-dump.

**Comment by DrewDennison** [comment]
seems low pri to me

**Comment by mschwager** [comment]
The documentation includes the `$`: https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#pattern-where-python. Would you expect it to work with and without a `$`?

One thing I would take care to consider here is that the `metavars` field in JSON output includes the `$` also. Removing the `$` will break backwards compatibility with existing scripts depending on the JSON output. This change may also break existing `pattern-where-python` patterns. We could check for, e.g. `FIELD` and `$FIELD`, but I tend to avoid "automagic" behavior whenever possible in favor of encouraging users to use the paved road. While helpful initially, it often makes behavior harder to reason about as more and more automagic behavior accumulates.

At the very least, this seems low priority :+1:

**Comment by DrewDennison** [comment]
agreed

**Comment by dlukeomalley** [comment]
I'd expect it to work only without `$`. I agree low-pri, on the flip side it's easier to change this now with fewer folks using python-where 🤷

**Comment by nbrahms** [comment]
One thought I had here is to override `getattr` on the `vars` object, so
you would access metavars using:

```python
vars.X
```

but

```python
vars["$X"]
```

would still work for backwards compatiblity.

Watcha think?

**Comment by nbrahms** [comment]
It looks like `metavariable-regex` is allowing us to move away from `pattern-where-python` anyway, and in a much safer manner.

I'm going to close this issue in favor of that usage.

Please reopen this ticket if you have further thoughts!
