### ISSUE TITLE
for php/symfony project, returning new RedirectResponse($url); response is not flagged in rule php.symfony.security.audit.symfony-non-literal-redirect.symfony-non-literal-redirect

### ISSUE THREAD

**Issue by jgroc-de** [semgrep/semgrep#9208]
**Describe the bug**
in symfony, using the method 
```php
    /**
     * Returns a RedirectResponse to the given URL.
     *
     * @param int $status The HTTP status code (302 "Found" by default)
     */
    protected function redirect(string $url, int $status = 302): RedirectResponse
    {
        return new RedirectResponse($url, $status);
    }
```
from Symfony\Bundle\FrameworkBundle\Controller\AbstractController

will trigger the rule php.symfony.security.audit.symfony-non-literal-redirect.symfony-non-literal-redirect

using directly the object Symfony\Component\HttpFoundation\RedirectResponse will not trigger it.

**To Reproduce**
create a route that return the object RedirectResponse
```
    #[Route(
        path: '/redirection-with-query-parameters',
        name: 'redirection',
        methods: ['GET']
    )]
    public function showWithdrawal(Request $request): RedirectResponse {
        $userUrl = $request->query->get('url');

        return new RedirectResponse($userUrl);
    }
```

**Expected behavior**
returning object RedirectResponse should trigger the rule php.symfony.security.audit.symfony-non-literal-redirect.symfony-non-literal-redirect ?

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
official binary

**Use case**
catch cases of redirection using crafted url

**Comment by aryx** [comment]
Could you report this bug on the semgrep-rules repo instead?
Or do you think the issue is in the engine?

**Comment by jgroc-de** [comment]
ah you are right thank you. I move this issue.
