### ISSUE TITLE
Infinite loop on parameter that shadows a name in its own type

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#923]
This case, reduced from `zulip/zerver/lib/email_mirror.py`, causes `semgrep` to spin in an infinite loop:

https://semgrep.live/GdeG

Pattern:
```
if $X:
    $S
else:
    $S
```

Code:
```python
import email.message as message

def process_message(message: message.Message):
    if 1:
        message
    else:
        message
```

**Comment by ievans** [comment]
Oof. Thanks for the bug report @andersk!

**Comment by aryx** [comment]
It's a bug in the Naming_AST.ml phase.
Looking.
