### ISSUE TITLE
Parse error on Unicode identifiers

### ISSUE THREAD

**Issue by andersk** [semgrep/semgrep#924]
This isn’t a priority for my project, but I happened to notice that `semgrep` fails to parse this file with lots of Unicode identifiers in another project:

https://github.com/uber-archive/pyflame/blob/v1.6.7/tests/sleeper_%E3%83%A6%E3%83%8B%E3%82%B3%E3%83%BC%E3%83%89.py

```console
$ semgrep --lang py --dump-ast sleeper_ユニコード.py 
Fatal error: exception Parse_info.Lexical_error("unrecognized symbol: \195", _)
error invoking semgrep with:
	semgrep-core -lang py -dump_ast sleeper_ユニコード.py
Command '['semgrep-core', '-lang', 'py', '-dump_ast', 'sleeper_ユニコード.py']' returned non-zero exit status 2.
```

https://semgrep.live/AbvQ

**Comment by dlukeomalley** [comment]
Thank you for filing @andersk.

**Comment by aryx** [comment]
This should be fixed by https://github.com/returntocorp/pfff/pull/170

**Comment by aryx** [comment]
This should work with the next release of semgrep.
Thx for the bug report!
