### ISSUE TITLE
Ensure CI time for this repo <= 10 min

### ISSUE THREAD

**Issue by nbrahms** [semgrep/semgrep#931]
Long CI times make development take longer... let's ensure that our CI completes in under 10 minutes under normal conditions.

**Comment by DrewDennison** [comment]
I think we can move the parse test suite to 1) nightly with slack notify on failure and 2) if a change to `pfff` is in the PR then run?

**Comment by dlukeomalley** [comment]
Chatted with @DrewDennison and closing for now. If this issue persists or people find it adds friction I trust that it'll be resolved with/without a ticket. Thank you for filing!
