### ISSUE TITLE
osemgrep: cannot make path ... relative to project root "."

### ISSUE THREAD

**Issue by fopinappb** [semgrep/semgrep#9377]
**Describe the bug**

When running `semgrep --experimental` with absolute paths it fails with

```
Error: cannot make path "/Users/fipina/tmp/ll/a/a.py" relative to project root "."
```

**To Reproduce**

* Prepare directory
   ```
   ➜  ll pwd
   /Users/fipina/tmp/ll
   ➜  ll find .
   .
   ./code
   ./code/a.py
   ./rules
   ./rules/a.yaml
   ```
* Run osemgrep (from anywhere) using full paths
   ```
   ➜  ll semgrep --experimental -f /Users/fipina/tmp/ll/rules/a.yaml /Users/fipina/tmp/ll/code/a.py
   ...
   Loading rules from local config...
   Error: cannot make path "/Users/fipina/tmp/ll/code/a.py" relative to project root "."
   Error: fatal error
   ```

**Expected behavior**

Same as using pysemgrep (that properly manages to find the relative path to project root `.` or uses some different default project root)

```
➜  ll semgrep -f /Users/fipina/tmp/ll/rules/a.yaml /Users/fipina/tmp/ll/code/a.py
...
Ran 1 rule on 1 file: 1 finding.
```

Specifying a `--project-root` (any at all, absolute) works around the issue

```
semgrep --experimental -f /Users/fipina/tmp/ll/rules/a.yaml /Users/fipina/tmp/ll/code/a.py --project-root $(pwd)
...
```

Specifying path to code already in relative format also works around it

```
➜  ll semgrep --experimental -f /Users/fipina/tmp/ll/rules/a.yaml code/a.py
...
```

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
macos semgrep 1.50

**Use case**

Similar behavior to pysemgrep. This does not block my use case as the workaround (specifying `--project-root` to any path) already enables me to use it in the same conditions I need.

**Comment by mjambon** [comment]
Thanks for reporting this.

**Comment by mjambon** [comment]
We just merged made various fixes regarding paths. This works for me now in the dev version of Semgrep which should be released this week or next week. I know there are still issues when the scanning roots and/or the projects that contain them are symlinks. Let us know if it's still failing for you.
