### ISSUE TITLE
Match Python Annotations with metavariables

### ISSUE THREAD

**Issue by minusworld** [semgrep/semgrep#938]
**Is your feature request related to a problem? Please describe.**
I'd like to match Python annotations with metavariables. Like this: https://semgrep.live/Ew5E.

It looks like the ASTs are pretty close but that the metavariable isn't applied?

**Comment by nbrahms** [comment]
It looks like the `(...)` on the annotation in your pattern, together with older Semgrep code, was causing the mismatch.

Are you unblocked with https://semgrep.dev/X2Bj/?version=develop ?

**Comment by aryx** [comment]
Any idea why the semgrep.live URL do not work anymore?
Did we reset the DB at some point?
Anyway, I think you can now use metavariable on annotations.
