### ISSUE TITLE
Filter Semgrep Result by Confidence Level

### ISSUE THREAD

**Issue by farhanardiya** [semgrep/semgrep#9409]
**Is your feature request related to a problem? Please describe.**
In the early stages of SAST implementation, we are often faced with a lot of results to review. In which many of them are noise / false positives. This results in resources depleted to do false positive analysis.

**Describe the solution you'd like**
I would like to be able to filter semgrep cli result by its confidence level. This is basically identical with filtering by severity which already exists as a feature, but the confidence level filter will further help to prioritize issues. I propose a --confidence flag similar to the --severity flag as a simple solution for filtering results.

**Use case**
This feature will enable users to prioritize false positive analysis much better, since we can filter the confidence level of the results being generated.

**Comment by aryx** [comment]
yep, sounds like a useful feature
Confidence is not formally specified though right now. It's just part of the metadata. What are the possibilties?
low/high/medium?

**Comment by farhanardiya** [comment]
yes @aryx , as per the documentation on security category rule, there are 3 possibilities of confidence level (low / medium / high)
https://semgrep.dev/docs/contributing/contributing-to-semgrep-rules-repository/#confidence

**Comment by ievans** [comment]
We're unlikely to implement this as the CLI output can already be exported to a structured format and filtered with `jq` or other tools, and we'd like to encourage users to take large CLI outputs and upload them to semgrep.dev, VScode, or a more suitable viewer.
