### ISSUE TITLE
$Y = {$X: "..."}; matches too many things

### ISSUE THREAD

**Issue by DrewDennison** [semgrep/semgrep#941]
It should only match line 1 in
https://semgrep.live/BYL6

not lines 3 and 5.

```js
x = {password: "str"}
x = {y: {password: 123}}
x = {y: {password: "str"}}
x = {y: {password: {z: 123}}}
x = {y: {password: {z: "str"}}}

```

**Comment by aryx** [comment]
It's because a field definition is considered the same than a variable definition.
{x: 1, y: 2} is transformed internally as   { x = 1, y = 2 }

**Comment by aryx** [comment]
In the same way, methods and definitions are both converted to a common FuncDef.

**Comment by aryx** [comment]
I'll try to add a FieldDef in addition to the existing VarDef to make the difference.
We might get regressions though in other test files.
