### ISSUE TITLE
v1.53.0 issues with python and multiple nosemgrep rules on the same line

### ISSUE THREAD

**Issue by andrewfraley** [semgrep/semgrep#9463]
**Describe the bug**
v1.53.0 seems to be broken with respect to Python and the use of multiple rules on a single nosemgrep line.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:

```
mkdir /tmp/semgreptest
cd /tmp/semgreptest
echo "# nosemgrep: python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use, python.lang.security.audit.subprocess-shell-true.subprocess-shell-true" > test.py
echo "subprocess.run(args=some_command, check=True, shell=True)" >> test.py
docker run --rm -v "$(pwd)":/src returntocorp/semgrep:1.53.0 semgrep --verbose  --error --config "auto" /src ; echo $?
```

**Expected behavior**
When running v1.52.0 it exits 0, but v1.53.0 instead exits 2 and this is seen:

```
[WARN] Other syntax error at line NO FILE INFO YET:-1:
 Rule_ID.Malformed_rule_ID("python.lang.security.audit.dangerous-subprocess-use.dangerous-subprocess-use,")
```

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Docker

**Use case**
Unable to adopt v1.53.0 until this is fixed

**Comment by starcraft66** [comment]
Experiencing the same problem here with terraform rules.
