### ISSUE TITLE
Relax Python 3.8 requirement

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#950]
We've had a few complaints and comments about the initial Semgrep installation via Brew taking a long time because of Semgrep's Python 3.8 requirement. For users who are on 3.6/3.7, download time is primarily spent here. From one user and supporter, they said:

> it makes me hate it

I'd like to investigate what it would take to reduce our Python requirement and remove this part of the download process.

**Comment by rcoh** [comment]
wow. OK, I thought I needed to specify a tagged Python version with brew...I'll look into it.

**Comment by dlukeomalley** [comment]
@rcoh This isn't an absolute deal breaker. If it looks like it'll be extensive work let's just close this ticket as `wont-fix`. If it's quick (1-2 hours?) let's try to knock it out. @DrewDennison may have more context than I.

**Comment by rcoh** [comment]
Fixed here: https://github.com/returntocorp/homebrew-semgrep/pull/22

It's worth noting that _every_ recipe in brew-core names Python 3.8 explicitly so I think they must have done that for a reason.

**Comment by dlukeomalley** [comment]
For that reason should we avoid this change?

**Comment by rcoh** [comment]
it's fine for our tap, but is unlikely to be accepted into brew-core. They are doing it so they can safely upgrade the default version for brew-python to 3.8 on a formula by formula basis, IIRC

**Comment by DrewDennison** [comment]
ah then I think we should just tell folks to do `brew install semgrep` since we're down to 3 hours between release. i.e. deprecate the tap. Let's stick with 3.8 if that's the new standard in core
