### ISSUE TITLE
Semgrep matches appear off-by-one

### ISSUE THREAD

**Issue by dlukeomalley** [semgrep/semgrep#959]
I've noticed in presentations and demos, both locally in the CLI and on semgrep.live, that the trailing `)` is often excluded in matches.

See https://semgrep.live/8GRj

![image](https://user-images.githubusercontent.com/605906/84222434-6c756e00-aa8c-11ea-9f51-8da467515b0b.png)

Semgrep 0.9

**Comment by aryx** [comment]
it's because parenthesis for Calls are not in the generic AST (because some languages such
as OCaml or even Ruby do not require them)

**Comment by aryx** [comment]
maybe we should add them in the generic AST yhen

**Comment by dlukeomalley** [comment]
@aryx Is that related to some of the autofix bugs like #841?

**Comment by aryx** [comment]
Yes it's related

**Comment by dlukeomalley** [comment]
I can't tell you how excited I am for this 🎉 Thank you @aryx !

**Comment by aryx** [comment]
This will pave the way for a correct autofixer and other more good stuff.
