### ISSUE TITLE
Other syntax error at line NO FILE INFO YET:-1:

### ISSUE THREAD

**Issue by calto001** [semgrep/semgrep#9628]
**Describe the bug**
When running a full semgrep ci scan The following error is incurred. \
`Encountered error when running rules: Other syntax error at line NO FILE INFO YET:-1:` \
`Invalid_argument: String.sub / Bytes.sub`

**To Reproduce**

1. Run `semgrep ci --gitlab-sast`

NOTE - Only happens on a certain repo. Running same command in a different repo results in no errors. 

**Expected behavior**
No errors and results are sent.

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?
Docker image 1.57.0 in Gitlab \
I tried lower versions of semgrep and got same error

**Use case**
What will fixing this bug enable for you?
I will be able to perform a full scan on our repo

**Comment by emjin** [comment]
Hey! Unfortunately, this is really hard for us to debug without more information. The options are:

- Share the entire repo with us (easiest for you if it's open source)
- Find a minimal reproduction of the problem by removing folders and files and share that with us
- Add `--debug` to the run and share your debug output with us. Then we'll iterate from there.

If you're a customer, please work with our CSEs to get help for this!

**Comment by calto001** [comment]
Unfortunately the repo is private. Yes I have started trying to eliminate file types and folders but its still in progress.

**Comment by calto001** [comment]
Cause of the bug is due to a comment in a Dockerfile. See below

```
FROM alpine:3.19

CMD echo "foo" && \
   # Bug happens because of this comment (remove comment and see no bug) \
   echo "bar"
```
