### ISSUE TITLE
[1.57.0] Crash due to terminal width being set to zero in CLI CI run

### ISSUE THREAD

**Issue by zenmonkeykstop** [semgrep/semgrep#9630]
**Describe the bug**
In very specific circumstances, a Docker container running in CircleCI, the terminal width is being set to 0, causing `semgrep scan` to error out. Downgrading to 1.56.0 clears the error

**To Reproduce**
It might be hard to reproduce, but here's our CI log: https://app.circleci.com/pipelines/github/freedomofpress/securedrop/6888/workflows/c09d91bd-6fe7-41ff-81a5-e5bc9ea43485/jobs/76065

I haven't been able to reproduce it locally. Docker is being run with the -it flag and a tty is available.

Looks like it might have been introduced with changes at https://github.com/semgrep/semgrep/commit/2cda16d704a55a8c6f872617712d2e55f6136aa3#diff-b1c303826f60514473cf5e1c3c6954d8f4a6791a6ee88a22cb767eef8b58d9b0L46 ?

**Expected behavior**
Text width would be calculated to something >0 and semgrep scan would complete without error.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
Docker in circleCI

**Use case**
Using latest version of semgrep

**Comment by emjin** [comment]
Fixed here https://github.com/semgrep/semgrep/pull/9629! Should be fine in the next release

**Comment by zenmonkeykstop** [comment]
that's crazy fast, thanks all!
