### ISSUE TITLE
Pattern parse error in rule go.lang.security.audit.net.pprof.pprof-debug-exposure.semgrep-legacy.10022

### ISSUE THREAD

**Issue by ashep** [semgrep/semgrep#9632]
**Describe the bug**

```
[ERROR] Pattern parse error in rule go.lang.security.audit.net.pprof.pprof-debug-exposure.semgrep-legacy.10022:
 Invalid pattern for Go:
--- pattern ---
go func() { ... }

--- end pattern ---
Pattern error: Sys_error("<file>: No such file or directory")
```

**To Reproduce**

https://semgrep.dev/playground/r/nWTYAz/go.lang.security.audit.net.pprof.pprof-debug-exposure.semgrep-legacy.10022

**Expected behavior**

Run `semgrep scan` without error.

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**

An official binary, version 1.57.0.

**Comment by nvuillam** [comment]
The same error has been observed in MegaLinter

https://github.com/oxsecurity/megalinter/actions/runs/7595115288/job/20687345018?pr=3298#step:9:323

**Comment by nvuillam** [comment]
Same issue with semgrep-1.56.0 :(

https://github.com/oxsecurity/megalinter/actions/runs/7595771747/job/20688714162?pr=3300#step:9:524

Maybe it is not semgrep itself but one of its dependencies ?

**Comment by ashep** [comment]
> Maybe it is not semgrep itself but one of its dependencies?

Perhaps. Could you please suggest to me how to reach developers of that dependency? Thank you.

**Comment by nvuillam** [comment]
The python dependencies have the same version so I don't think it's python dependencies...

Maybe something internal to SemGrep ? What could trigger such error, which seems related to a single semgrep rule ?

**Comment by ashep** [comment]
It seems fixed for now.
