### ISSUE TITLE
Missing docker syntax equivalence on ENTRYPOINT parsing

### ISSUE THREAD

**Issue by nitinb83** [semgrep/semgrep#9726]
**Describe the bug**
The semgrep uses missing-user-entrypoint rule to check if there is any code execution using high privilege user 

**To Reproduce**
Steps to reproduce the behavior, ideally a link to [https://semgrep.dev:](https://semgrep.dev/playground/r/dockerfile.security.missing-user-entrypoint.missing-user-entrypoint?editorMode=advanced)

And use testcode as follows, observe that no vulnerability is detected.

```
ENTRYPOINT ["dotnet" ,"abc.dll"]
```

When changes made to the syntax of the code, a vulnerability is detected.

```
ENTRYPOINT dotnet abc.dll
```

**Expected behavior**
The rule is unable to identify variables in square brackets and missing the vulnerability.

**What is the priority of the bug to you?**
P2: regular bug that should get fixed

**Environment**
Using latest docker image

**Use case**
It shall ensure that vulnerability is not missed in CI\CD pipeline

**Comment by ievans** [comment]
Seems we are missing a docker syntax equivalence on ENTRYPOINT parsing, updated the description

**Comment by mjambon** [comment]
Update: still needs fixing. The issue is specific to the ellipsis-metavariable pattern.

A regular ellipsis works:
```
$ semgrep -l dockerfile -e 'ENTRYPOINT ...' <(echo 'ENTRYPOINT ["a"]')
                  
                  
┌────────────────┐
│ 1 Code Finding │
└────────────────┘
                                             
    /tmp/tmpwt7apser/dev_fd_63
            1┆ ENTRYPOINT ["a"]

                
                
┌──────────────┐
│ Scan Summary │
└──────────────┘

Ran 1 rule on 1 file: 1 finding.

⏫  A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading
```

Minimal repro:
```
$ semgrep -l dockerfile -e 'ENTRYPOINT $...VARS' <(echo 'ENTRYPOINT ["a"]')
                
                
┌──────────────┐
│ Scan Summary │
└──────────────┘

Ran 1 rule on 1 file: 0 findings.

⏫  A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

✨ If Semgrep missed a finding, please send us feedback to let us know!
    See https://semgrep.dev/docs/reporting-false-negatives/
```
(should give us one finding)

**Comment by saghaulor** [comment]
This issue duplicates #9109
