### ISSUE TITLE
Support semantic equivalence between keyword arguments and positional arguments

### ISSUE THREAD

**Issue by Enr1g** [semgrep/semgrep#973]
Expected rule `func(x=1, y=2)` to match `func(1, 2)` for the function with the following signature:

```python
def func(x=3, y=4):
    return x
```

Live example: https://semgrep.dev/s/Nb1n

**Comment by dlukeomalley** [comment]
Hi @Enr1g, thanks for filing this ticket. My understanding is that because you're trying to match positional arguments (rather than keyword arguments), the pattern `func(1, 2)` is what you likely want: https://semgrep.live/wd3N

If you used the pattern `func(x=1, y=2)`, Semgrep would look for calls to `func` with *named* keyword arguments `x` and `y`, like this `boto3` example: https://semgrep.live/OreR

**Comment by Enr1g** [comment]
Is this an intended behavior? Let's consider dummy API to fetch resource:

```python
def fetch_resource(url, verify_ssl=True):
    # implementation
    ...
```

Let's also imagine that in the analyzed code base this API is used in different yet equivalent ways:

```python
fetch_resource("https://some.url/1", False)
# or
fetch_resource("https://some.url/2", verify_ssl=False)
```

How can I match both with one rule? Or there is no canonical way to do it?

**Comment by ievans** [comment]
@Enr1g indeed, the examples you've provided are semantically equivalent. There is experimental support for allowing you to directly program more _equivalences_ into the semgrep engine. You can use this to say "this is equivalent to that" and make the patterns more concise. In this case:

```
rules:
- id: some_id
  equivalences:
    - equivalence: fetch_resource($X, verify_ssl=False) ==> fetch_resource($X, False)
  pattern: fetch_resource($X, verify_ssl=False)
```
https://semgrep.live/4blL

However I agree with you this is a generally useful semantic pattern that we'd like to support in a first-class way. I'll edit the name of this ticket to reflect that an enhancement! In the meantime, hopefully using the equivalences API unblocks you.

**Comment by aryx** [comment]
The problem is that currently semgrep is local to a file and the definition of func may be in another file in which case we don't know what is the actual position of x and y.
We could do something indeed if the definition is in the same file.

**Comment by ievans** [comment]
Keep
