### ISSUE TITLE
Add Javascript import metavariable usage

### ISSUE THREAD

**Issue by mschwager** [semgrep/semgrep#974]
It looks like pure import detection works: https://semgrep.live/Zq4x?version=develop

However, you cannot re-use an import metavariable from what I can tell: https://semgrep.live/nJKg?version=develop

There's been an external ask to support this behavior.

**Comment by ievans** [comment]
Is this related / dup of https://github.com/returntocorp/semgrep/issues/285?

**Comment by coreyferguson** [comment]
Similarly, this pattern cannot be parsed, although something like it should work. The intent: I'd like to know if something is imported and then USED.

```
import {..., $X, ...} from 'dependency';
...
$X(...);
```

https://semgrep.live/7KYk

**Comment by mschwager** [comment]
> Is this related / dup of #285?

Ahhh, yes, looks like it. #285 covers additional use-case's as well :+1:

**Comment by aryx** [comment]
@coreyferguson my fix should help for your pattern, but you don't need the ..., $X, ...
just import { $X } from 'foo' will handle all the variations.

**Comment by aryx** [comment]
I've added an example in the PR linked above PR #986
