### ISSUE TITLE
Address semgrep-core timeouts

### ISSUE THREAD

**Issue by brendongo** [semgrep/semgrep#978]
With https://github.com/returntocorp/semgrep/commit/19513df850d03051349f31e34931818f12379e44 repos that are timing out are now surfacing the error. https://github.com/returntocorp/semgrep/pull/977 shows which of the test repos are timing out. Should investigate these timeouts.

**Comment by brendongo** [comment]
Quick glance looks like we are timing out on large minified js files.

**Comment by ievans** [comment]
@brendongo can you update / close this?
