### ISSUE TITLE
Version check running when disabled

### ISSUE THREAD

**Issue by brynary** [semgrep/semgrep#9805]
**Describe the bug**
Semgrep version check is running when disabled.

**To Reproduce**
```sh
semgrep --metrics=off --disable-version-check --config .semgrep.yaml --sarif --output=output.txt <FILENAME>
```

**Expected behavior**
Because Semgrep is being run with the `--disable-version-check` flag, it should not make a version check.

With this invocation, we would expect `semgrep` not to make any network calls.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
Local, pip-based installation

**Comment by ievans** [comment]
hey @brynary I don't see this behavior -- can you share what version of Semgrep you are using, your environment (OS/distro), and how you are determining whether it is making a network call?

**Comment by brynary** [comment]
@ievans thanks for the fast reply. This was on v1.40.0 on macOS.

I made the assumption of the network call based on a message I saw which said something like: A new version of semgrep is available.

However, I cannot reproduce this in my re-run just now. Is the upgrade check programmed to run every time, and/or does it use any on-disk state/cache?

**Comment by brynary** [comment]
@ievans OK, so I have a lead. As before, the message I got was "A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading"

However, I think this message may have come from the `pip install` shell command I ran, rather than the `semgrep` invocation itself. Does the version check run on install?

**Comment by ievans** [comment]
Probably; I'm less familiar with how we package python these days but looking at https://github.com/semgrep/semgrep/blob/develop/scripts/validate-wheel.sh#L24 it seems likely we run --version and also a quick test after install.

**Comment by ievans** [comment]
I looked through our flags and didn't see any way for it to happen otherwise, so I will close this but feel free to reopen if you find a different reproduction,
