### ISSUE TITLE
No findings in Github Security

### ISSUE THREAD

**Issue by Sof0-0** [semgrep/semgrep#9809]
Semgrep successfully finished scanning and uploading sarif; however, no findings were found even though the codebase is vulnerable as other tools uploaded over 300+ alerts. Here are the screenshots and configuration file:
<img width="981" alt="Screenshot 2024-02-20 at 17 41 55" src="https://github.com/semgrep/semgrep/assets/104607214/60be0432-1ae0-4df2-8029-5896f0befffc">
<img width="783" alt="Screenshot 2024-02-20 at 17 42 19" src="https://github.com/semgrep/semgrep/assets/104607214/2cd596df-2462-497f-ac4d-e57c2c51e953">

**Comment by ievans** [comment]
can you share project you are running Semgrep on so we can try to reproduce, or link directly to the Github action output?
