### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by Sof0-0** [semgrep/semgrep#9810]
Semgrep properly scans all files, but fails on the upload step with this error:
<img width="1017" alt="Screenshot 2024-02-20 at 18 17 51" src="https://github.com/semgrep/semgrep/assets/104607214/50f47854-74ef-4c22-85d9-2a4e225fb056">

Also attaching config file:
<img width="427" alt="Screenshot 2024-02-20 at 18 18 24" src="https://github.com/semgrep/semgrep/assets/104607214/52893cc8-4bad-4819-8893-b1e601904167">

**Comment by ievans** [comment]
What repository is this scan happening on? Can you provide so we can reproduce?
