### ISSUE TITLE
Very few findings in the vulnerable repository

### ISSUE THREAD

**Issue by Sof0-0** [semgrep/semgrep#9834]
Hello. I have scanned one of the vulnerable repositories using this configuration: 

<img width="582" alt="Screenshot 2024-02-23 at 11 17 13" src="https://github.com/semgrep/semgrep/assets/104607214/7974c569-5c29-4765-b08f-6ff38a6d1d58">

And compared to other tools (that reported 300+ findings), Semgrep only found 3 findings. During the scan, it is mentioned that it used 400+ rules on many files, but it did not detect the main vulnerabilities. Is it possible to configure it to report properly?

<img width="936" alt="Screenshot 2024-02-23 at 11 19 40" src="https://github.com/semgrep/semgrep/assets/104607214/1b67c5ad-35a5-4f67-8779-e1305885a8b0">

I would appreciate your help!

**Comment by ievans** [comment]
@Sof0-0 can you link to the repo you scanned so we can investigate? What specific findings do you expect to see but do not?
