### ISSUE TITLE
Semgrep OSS [config]

### ISSUE THREAD

**Issue by abi1915** [semgrep/semgrep#9841]
On running below on Local installation and on github actions
semgrep scan --error --metrics=off --config="p/default" --sarif -o test_report.sarif

On output it will display the issues but additional it will display semgrep oss. 
like rules[{
defaultConfiguration: {
level: warning
}
fullDescription:
text:
help:
helpUri:
id:
name:}
etc...........]

What exactly is this because  issue result already display above and it will print approx 29914 line.

**Comment by ievans** [comment]
Can you link to a github action output on a public repo, or share the repository that causes this result? What version of Semgrep are you running, andw hat's the priority of this issue to you?
