### ISSUE TITLE
Semgrep scan failing with error code 7

### ISSUE THREAD

**Issue by qw1212** [semgrep/semgrep#9864]
I am encountering an issue with semgrep scans failing with error code 7. I am using the semgrep CLI command within a Docker container to scan various pieces of code. Up until February 3, 2024, the scans were running successfully. However, all scans after February 5, 2024, are failing for all projects. I would like to understand the reason behind this. I downloaded the rules from https://semgrep.dev/c/p/default and saved them locally as auto.yml. I then used the --config parameter to specify this auto.yml file as the rule set. Below is the command I used for scanning:

![image](https://github.com/semgrep/semgrep/assets/62467963/31ea66ee-c928-4580-b0b0-0e705caab046)

Thank you for any assistance you can provide in resolving this issue.

**Comment by ievans** [comment]
Hey @qw1212, what version of Semgrep do you have pinned in your docker image? If you use the latest rules (--config=auto) do you still see the error? What's the priority of this issue to you?

**Comment by qw1212** [comment]
Thank you for your response! The version of Semgrep in my Docker image is returntocorp/semgrep:sha-1f8cf28. Even when using the latest rules (--config=auto), I still see the error. However, the issue has been resolved by switching to the latest image (returntocorp/semgrep:latest).

**Comment by qw1212** [comment]
using the latest version of the image.
