### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by zoranuri** [semgrep/semgrep#9888]
I've seen in the `develop` branch that you've been working on supporting semgrep on Windows without relying on WSL.
Do you have a ballpark estimation of when it will be officially released?
If I run the recently added GHA workflow for Windows, should I expect it to work? 
Alternatively, would only building and running semgrep-core for Windows work? Any recommendations on how to go about building it?

Thanks!

**Comment by ievans** [comment]
hey @zoranuri -- this would probably be a better question for our slack, https://go.semgrep.dev/slack if you don't mind posting there!

you can follow https://github.com/semgrep/semgrep/issues/1330 as well
