### ISSUE TITLE
semgrep.live bug report - Java parsing fails because of lower case in class name

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#990]
https://semgrep.live/BYy7

This fails to parse:
```java
package com.test;

import java.util.HashMap;
import java.util.Map;

final class Test<T> {
    final Map<T, otherTest<T>> abc = new HashMap();

    Test() {
    }
}
```

This works:
```java
package com.test;

import java.util.HashMap;
import java.util.Map;

final class Test<T> {
    final Map<T, OtherTest<T>> abc = new HashMap();

    Test() {
    }
}
```

The only difference is the PascalCase on `OtherTest`, which is Java standard but I'm running this on some ugly code. :)

**Comment by ievans** [comment]
+1 to this issue, I noticed it in a large Java repo I started work on today as well.

**Comment by dlukeomalley** [comment]
This is queued up for work. Thank you for filing @dee-see.

**Comment by aryx** [comment]
Do you have know repo I could test this one @ievans and @dee-see ? just to make sure I don't introduce regressions in other files.

**Comment by aryx** [comment]
It's just that right now the Java parser uses some heuristics to parse generics, which are ambiguous when using  an LALR(1) parser generator like yacc, and those heuristics assume PascalCase. I can relax the condition, but maybe in code like  if (a < b, b > 3) the a < b, b> could be interpreted as a generic (leading to parse error when encountering the 3).

**Comment by aryx** [comment]
So I need to relax the condition but add more heuristics to not convert too much cases as generics, hence the need for repo to tests those heuristics (note that tree-sitter-java probably handle better those things in the long-term).

**Comment by aryx** [comment]
Ok we should have a fix for this by the end of the week; It should go in the next semgrep release, in 0.15.
