### ISSUE TITLE
"at least one rule needs to execute arbitrary code" not printed out till after run is complete

### ISSUE THREAD

**Issue by ievans** [semgrep/semgrep#991]
current behavior:
```
> semgrep --config=r2c .
using config from https://semgrep.live/c/p/r2c. See https://semgrep.live/registry for more options.
scanning code...
at least one rule needs to execute arbitrary code; this is dangerous! if you want to continue, enable the flag: --dangerously-allow-arbitrary-code-execution-from-rules
```

expected behavior:
I would expect that this message be printed earlier, and that it be reworded to say "if you want to enable these rules..." rather than "if you want to continue"

$ semgrep --version
0.10.1

**Comment by ievans** [comment]
Closing this as stale; almost no rulesets use where-python now thanks to the new metavariable comparison work.

**Comment by mschwager** [comment]
This may help: #2450
