### ISSUE TITLE
semgrep.live bug report - Java parser does not support unicode characters

### ISSUE THREAD

**Issue by dee-see** [semgrep/semgrep#997]
https://semgrep.live/9Ave

I added this line to the sample

```java
   private static final char A = '傳';
```

It works with an ascii character.

**Comment by dee-see** [comment]
There is [this other issue](https://github.com/returntocorp/semgrep/issues/924) about unicode but it seemed different enough to open another one

**Comment by aryx** [comment]
This should work with the next release of semgrep.
Thx for the bug report!
