### ISSUE TITLE
Can semgrep resolve fully qualified name for imported type in C#?

### ISSUE THREAD

**Issue by jiseongg** [semgrep/semgrep#9997]
Hi there,

I am trying to use semgrep just for fun, and have just became curious about its name resolution. I am inspecting the source code seriously, and found `src/naming` and `src/matching` modules. However, as a new-comer I find it difficult to understand everything on my own.

Consider a class `A` resides in `Some.Name.Space`.

```c#
using Some.Name.Space;

A a = new A();
```

For this code, can semgrep figure out that the `A` in line 3 is actually `Some.Name.Space.A` ?

Thanks.

**Comment by ievans** [comment]
Hi @jiseongg, questions like this are best suited for the #contributing channel on our community slack: https://go.semgrep.dev/slack -- many of the devs hang out there!
